### ISSUE TITLE
Need an `ALTER FUNCTION` DDL

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#1006]
Currently functions only have `CREATE` and `DROP` DDL, which means that function annotations cannot be altered once they are set (or not set, for that matter).

**Comment by vpetrovykh** [comment]
The PR above doesn't fix the lack of  `ALTER` command for functions, it merely prevents some issues with SDL function definitions that happened because of the missing `ALTER`.

**Comment by elprans** [comment]
Functions are alterable now.
