### ISSUE TITLE
Serialization of RPC between main process and the compiler

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#1020]
# Motivation

Currently, we have:
1. Main process and compiler process communicating over Unix socket
2. The protocol uses pickle as serialization
3. Compiler process connects to Postgres on its own

This isn't going to work for the main process in Rust and supporting cloud:
1. While it's [possible](https://crates.io/crates/serde-pickle) to work with Pickle in Rust it isn't a good idea
2. We want a many-to-many relationship between the processes in the cloud
3. Holding by a compiler onto a Postgres connection is inefficient (connections are costly in Postgres)

# The Proposed Protocol

## Framing

@tailhook is used to use WebSocket framing for everything nowadays:
1. It's standard, ubiquitously supported
2. Sufficiently extensible
3. Exposing (Prometheus?) metrics over HTTP on the same port is a plus
4. It has a standard connection liveness protocol (Ping/Pong packets)

### Alternative Framing

1. We could use HTTP for most things, but being able to find out connection liveness reliably is a very big advantage. And we'll probably need some non-RPC messages, see below
2. Roll-your-own will require provisioning ping/pong and future extensions. While it isn't particularly complex, I don't think it's justified.
3. Use postgres framing. The downsides are:
    * It's just framing, we still need to specify how actual request/response, ping/pong and other packets look like
    * We still need to decide how to serialize or own data

## Serialization

@tailhook is used to [CBOR](http://cbor.io/):
1. It's standard
2. There is Concise data definition language ([CDDL](https://tools.ietf.org/html/draft-ietf-cbor-cddl-00)) to describe CBOR structures
3. It's binary, fast and sufficiently extensible
4. It's relatively compact. While preserving field names it's still comparable to protobuf after gzipping (there is a standard compression extension in websocket protocol when we need one). *We can also replace field names with 1-byte numbers or use arrays if we have lots of small objects.*
5. There are fast encoders for every language including Python and Rust

### Alternative Serialization

Lots of them:
1. Protobuf [is not a starter](http://reasonablypolymorphic.com/blog/protos-are-wrong/index.html).
2. Cap'n'proto is unnecessarily complex and bad at backward compatibility
3. JSON is bad at binary data and not compact enough
4. Postgres protocol: there are two different protocol serializations there: one for message structure and one for the data. The latter one requires describing types upfront and is suited only for tabular data, and also is not very compact. The former is not self-descriptive. Which makes debugging harder.

Can go over and over, have to just pick one.

## Semantics

To make complier completely stateless, we move all communication to Postgres into the main process.

### Compile To SQL

There are perhaps two API calls:
```
compile_to_sql(query_text, schema_hash) -> (compiled_query, Option<changes_to_schema>)
compile_to_sql_given_schema(query, schema) -> (compiled_query, Option<changes_to_schema>)
```
Note:
1. It's stateless. If there is no schema with that hash compiler returns an error and the main process calls the second method.
2. The slow path here is when the actual schema changes, which is fine.
3. ❓ The DDLs probably don't need any dedicated processes with these semantics
4. ❓ Schemas might not need to be tied to a user or a database. So multiple tutorial users can share the same schema if the hash matches.

There are few *performance optimizations* can be done on top:
1. The main process keeping track of which schemas are cached (i.e. compiler publishes hashes as it receives schemas)
2. Forcing preload of specific schemas when connecting to a compiler (this is probably only justified in the paid tier).

The obvious question here is: **Is it fast enough to transfer schema like this**?
1. Well, obviously we need to do it one way or another
2. For paid tier, it will always be preloaded anyway (but asserting on a hash is still useful)
3. For free tiers (i.e. try.edgedb.com) we should have a small limit on the schema size to avoid DoS (and hopefully we can reuse the same schema for most users)

## Alternative Semantics

Well, there are a lot of different approaches and combinations on them. Please comment!

-----

@tailhook: I've marked by "❓" my pure speculations that need more research.

**Update 1:** added notes about using postgres protocol
**Update 2:** mention CDDL

**Comment by 1st1** [comment]
> Well, there are a lot of different approaches and combinations on them. Please comment!

Yes, I was going to build a small protocol on top of Postgres framing. Then the Rust infrastructure built for EdgeDB binary protocol and for Postgres protocol can be reused. This is also super straightforward, simple, and requires almost zero new code to be written / zero third-party deps. 

I'm -1 on using protobuf, pickle, cbor, websockets etc simply because that complexity is unwarranted.

**Comment by tailhook** [comment]
> Yes, I was going to build a small protocol on top of Postgres framing. Then the Rust infrastructure built for EdgeDB binary protocol and for Postgres protocol can be reused. This is also super straightforward, simple, and requires almost zero new code to be written / zero third-party deps.

Well, while there is "postgres-like framing" there is no common "Postgres protocol" between edgedb protocol and real postgres protocol. So it will require more new code to be written. With CBOR (or any other generic serializer) it a matter just defining structures (`derive` does all the work):
```
#[derive(Deserialize)]
struct Request {
    query_text: String,
}
```
Compare that to [the chunk of code in rust](https://github.com/edgedb/edgedb-rust/blob/master/edgedb-protocol/src/client_message.rs#L122-L182) or [python](https://github.com/edgedb/edgedb-python/blob/master/edgedb/protocol/protocol.pyx#L737-L755) to handle our current protocol.

I've listed Postgres protocol's downsides in the alternatives above, which boils down to:
1. We need to define structure of each message anyway, only reusing 4-byte framing. Every message of this protocol and other two (except perhaps error and log messages) are different.
2. We need to define even ones already defined in websockets: ping/pong (and perhaps a handshake).
3. The messages aren't self-descriptive as in CBOR. Self-descriptiveness means you can copy your binary chunk of data to `import cbor; cbor.decode(b'data')` and decode the thing (without the context of where this message comes from).
4. My experience says that it will be less compact even with self-descriptive CBOR (but I don't have the proof right now)
5. We already talked about gzipping, it's defined for websockets, but we need to define it for our protocol themselves (Also TLS, but that might be straightforward).

So at the end of the day, I think WebSocket+CBOR is a lot less work than adopting edgedb protocol's approach.

**Comment by elprans** [comment]
> there is no common "Postgres protocol" between edgedb protocol and real postgres protocol

There is. Actual data is serialized using PostgreSQL binary encoding, and this is the main issue here.

>  it took me about two weeks in total and 11 documentation fixes to implement the current protocol in Rust so far

OK, so we already have the implementation both in Python and in Rust. I don't see how the protocol issue is relevant now. I doubt we will introduce any other language to the server anytime soon, and if we do, it is highly likely that we would have the protocol implemented there as well.

> The messages aren't self-descriptive as in CBOR

The Type Descriptor is exactly the description of a message, is it not?

The *main reason* why we want to go with Postgres data serialization is that the schema and other state are *in Postgres* and so, by definition, are encoded using that.  Going with alternative serialization formats, no matter how nice they are, will introduce a requirement to re-serialize such data after it is extracted from Postgres. Given that schemas may be very large, this is a non-trivial performance cost.

Lastly, the RPC/IPC here is fairly small in scope, and will likely stay that way, so I don't see a real value in bringing in a full-blown RPC system given the downsides of doing so, and the context in which we operate.

To clarify, I don't think CBOR is bad, and we can certainly look into adopting it for RPC between services outside of the server core.

**Comment by elprans** [comment]
> Holding by a compiler onto a Postgres connection is inefficient (connections are costly in Postgres)

The compiler process does not need to hold onto the connection. It only needs it to read the current schema, and that will likely be a single query or a few of them. It's not clear if serializing and passing the schema via RPC would more efficient than re-reading the schema. That said, not doing it in the compiler process is technically cleaner, so it's worth exploring.

**Comment by tailhook** [comment]
> The compiler process does not need to hold onto the connection. It only needs it to read the current schema, and that will likely be a single query or a few of them. It's not clear if serializing and passing the schema via RPC would more efficient than re-reading the schema

I don't think it's more efficient. It may be less efficient. But my considerations are:
1. We eliminate race conditions when we send a request with one schema but Postgres already contains another one.
2. We eliminate the network time from the compiler, it's now pure CPU resource. The important use case here is when the compiler tries to fetch the schema and Postgres is holding locks on some of the data because another upgrade is in progress.
3. When spreading the load over compiler processes we don't need to think of how many connections compiler will open simultaneously to fetch the schema (especially it's important when request cache is clean, i.e. on application start or after schema change). It may exhaust Postgres limits in the other case.
3. We don't need to give the database address to compilers
4. We improve security by not letting compiler processes access the data and credentials
5. I think it's clearer to compute the hash on the received schema than storing the hash in Postgres (and then if the main process already has a schema, why not just send it)

> The main reason why we want to go with Postgres data serialization is that the schema and other state are in Postgres and so, by definition, are encoded using that.

You're right at everything with one assumption: *you're going to store schema as rows received from postgres*. Which I'm sure isn't true. We should make dicts from lists of rows and build all kinds of auxiliary structures. So I propose to serialize the schema in more robust and easily hashable form than that.

**Comment by tailhook** [comment]
> OK, so we already have the implementation both in Python and in Rust. I don't see how the protocol issue is relevant now.

Yes, but we also eventually might need a Wireshark plugin to debug production issues. Using CBOR over websocket (both of which already have decoders in Wireshark) is going to be so much easier and little-maintenance than our own protocol. This is just an example that easy implementation still makes sense, though.

**Comment by elprans** [comment]
> You're going to store schema as rows received from postgres. 

Store where? Isn't the idea that we only store state in Postgres?

> Which I'm sure isn't true. We should make dicts from lists of rows and build all kinds of auxiliary structures.

This isn't how this is going to work.  The new version of schema introspection code will use EdgeQL and will return a properly shaped data block.  Yes, you would still need to parse that into whatever structures the in-process schema representation is using, but that parsing would happen in the compiler process.

So, if I understand your proposal correctly, the introspection flow would look roughly like this:

`Postgres --> Custom unpacking code (a-la current intromech) --> CBOR --> RPC --> CBOR unpack --> Unpacking code to get from CBOR to schema.Schema`

What I propose:

`Postgres -> RPC -> Unpacking code to get from typedesc/data to schema.Schema`

> We eliminate race conditions when we send a request with one schema but Postgres already contains another one.

Not sure I understand this point.  Outside of transactions we make no guarantees as to what schema your query would be compiled against (just like Postgres BTW).  It is fundamentally wrong for the caller to make any other assumptions,

> The important use case here is when the compiler tries to fetch the schema and Postgres is holding locks on some of the data because another upgrade is in progress.

I don't see a scenario where an `ACCESS_EXCLUSIVE` lock would be held on an internal schema metadata table. Migrations only lock user tables.

> We don't need to give the database address to compilers
> We improve security by not letting compiler processes access the data and credentials

I don't disagree here. The discussion here assumes that we pass the schema via RPC.

**Comment by tailhook** [comment]
> > You're going to store schema as rows received from postgres.
> 
> Store where? Isn't the idea that we only store state in Postgres?
> 

In-memory

> So, if I understand your proposal correctly, the introspection flow would look roughly like this:
> 
> `Postgres --> Custom unpacking code (a-la current intromech) --> CBOR --> RPC --> CBOR unpack --> Unpacking code to get from unpacked CBOR to schema.Schema`
> 
> What I propose:
> 
> `Postgres -> RPC -> Unpacking code to get from typedesc/data to schema.Schema`
> 

That's correct. My point of view on this:
1. Unpacking from CBOR is much easier (I think we can perhaps leverage CBOR hooks to deserialize directly into schema, without intermediate representation, but I'm not sure)
2. Understanding schema by main process is nice, at least recomputing hash is useful (I don't think we can get a hash right from the rows for many reasons). It's also future-proof for moving more features to the main process in the perspective
3. Even if we keep serialization of the schema via postgres protocol the **outer** protocol is different (we don't need to send prepare + describe requests from compiler). So we still need to invent that protocol.

Other than that, yes, me might consider passing just a chunk of data from the postgres without repacking.

> > We eliminate race conditions when we send a request with one schema but Postgres already contains another one.
> 
> Not sure I understand this point. Outside of transactions we make no guarantees as to what schema your query would be compiled against (just like Postgres BTW). It is fundamentally wrong for the caller to make any other assumptions,
> 

In the proposed implementation, it's no different whether it's outside or inside a transaction. The compiler works the same. We don't allocate a special compiler process for a transaction.

When we were discussing compiler fetching the schema on its own, how it could fetch the schema inside the same transaction?

But anyway, you seemed to agree that passing schema via RPC makes sense.

> > The important use case here is when the compiler tries to fetch the schema and Postgres is holding locks on some of the data because another upgrade is in progress.
> 
> I don't see a scenario where an `ACCESS_EXCLUSIVE` lock would be held on an internal schema metadata table. Migrations only lock user tables.
> 

I may be misunderstanding how it works. But I used to think that we upgrade metadata and altering tables in the same transaction. So locking is still possible.

Actually, it's pretty hard to prove that locking of metadata is not possible, so assuming the worst is a safe bet for me.

> > We don't need to give the database address to compilers
> > We improve security by not letting compiler processes access the data and credentials
> 
> I don't disagree here. The discussion here assumes that we pass the schema via RPC.

------

So if we agree that passing schema via RPC makes sense. Then regardless of the serialization format of the schema itself, the **outer** protocol is different: we don't need to send prepare + describe requests from compiler; even if we were doing that it would be the other way around (from server to client, because I'm assuming the main process is the client here). So we still need a different protocol here.

**Comment by elprans** [comment]
> Understanding schema by main process, at least recomputing hash is useful

There is no need to hash the schema at all.  Maintaining a monotonous version counter per-database is sufficient.

> I may be misunderstanding how it works. But I used to think that we upgrade metadata and altering tables in the same transaction. So locking is still possible.

It is only possible if you `ALTER` or `DROP` the metadata tables themselves, which we don't do. Postgres locks are per-relation (and sometimes per-row).

> So we still need a different protocol here.

I'm not convinced. Using the existing framing and encoding conventions of our *main* protocol means that we have to maintain and reuse just one implementation. We must continue to improve and enhance it with tooling *anyway*, so the argument that it's new or badly documented or lacks Wireshark support does not hold in perspective. I do not think that the introduction of CBOR and WebSockets will lower the overall complexity and maintenance burden in this context.

**Comment by 1st1** [comment]
>  I do not think that the introduction of CBOR and WebSockets will lower the overall complexity and maintenance burden in this context.

+1.

My view on this is that we shouldn't approach this in breadth-first fashion. Right now we have a working compiler<>IO infrastructure written in Python. We want to replace the IO part with Rust code. For that we need to replace pickle with something more sensible. Because we don't need to encode complicated structures (QueryUnit and Error are the two we need) using existing Postgres framing would be sufficient.

The Rust implementation won't happen overnight. And I don't want to mess with WebSockets/CBOR in our current Python code. I want a solution that we can code in a day or two and not depend on HTTP/WebSockets and other third-party libraries. 

And maybe once we switch to Rust server we want to explore CBOR and WebSockets -- it just doesn't seem to be a good idea right now.

**Comment by tailhook** [comment]
> > Understanding schema by main process, at least recomputing hash is useful
> 
> There is no need to hash the schema at all. Maintaining a monotonic version counter per-database is sufficient.
> 

Well, hashes are much more reliable and informative. Especially if you consider recovering from a backup a possible scenario.

Also, as I've already said, reusing the same schema for multiple tutorial databases should be possible if using hashes.

> > So we still need a different protocol here.
> 
> I'm not convinced. Using the existing framing and encoding conventions of our _main_ protocol means that we have to maintain and reuse just one implementation.

We already have two: one for postgres and one for edgedb. Which one is main? (Well, the question is rhetorical, but I guess you understand the irony)

> We must continue to improve and enhance it with tooling _anyway_, so the argument that it's new, or badly documented, or lacks Wireshark support does not hold in perspective.

Well, from my perspective it sounds like: we already made a mistake let's hold on it as long as possible (I don't mean to sound insulting if it sounds like that, just show that opinion from a different perspective).

> The Rust implementation won't happen overnight. And I don't want to mess with WebSockets/CBOR in our current Python code. I want a solution that we can code in a day or two and not depend on HTTP/WebSockets and other third-party libraries.

This just increases the amount of work on the rust side. I've already shown that this kind of protocol construction is substantially more work in rust (I believe it's the same in python too, BTW). But...

> And maybe once we switch to Rust server we want to explore CBOR and WebSockets -- it just doesn't seem to be a good idea right now.

I would approach this from a different perspective: let's make the whole networking part of the compiler in Rust. It means we need only a single implementation of the protocol (and will also allow to send and receive data while compiler holds GIL as a nice bonus). It shouldn't be hard.

I.e. don't upgrade python implementation from IPC/Pickle to RPC/something. Just refactor internals a bit to allow multiple schemas and plugging in the networking in rust.

**Comment by elprans** [comment]
> We already have two: one for postgres and one for edgedb. Which one is main?

They are substantially similar, so can be considered a single protocol.

> we already made a mistake let's hold on it as long as possible 

I'm not sure what mistake you're trying to point out and based on what evidence.  I have enough experience working with systems based on Protobuf and Thrift to say that they're very far from being a perfect solution, especially from the standpoint of expressiveness (the type system), performance, and ability to extend them. Specific implementations are not stellar (at least for Python). As for CBOR: yeah it has an RFC, but who's actually using it? The combined download monthly total of cbor and cbor2 on PyPI is around 100k (compare to 28M for protobuf and 3M for thrift, 3M for msgpack).  Given this, I don't have much confidence that we would not have to spend time debugging an issue in the third party cbor module or crate, or writing feature PRs against them to support our use cases.

> I've already shown that this kind of protocol construction is substantially more work in rust

I thought you liked writing Rust ;-) As far as I can tell, the RPC implementation would require two new protocol envelopes: `RPCRequest` and `RPCResponse`, all the hard work of implementing SerDe is done (and, come on, it's not *that* bad).

**Comment by elprans** [comment]
Also, @tailhook, please remember that we are discussing an implementation of a single RPC interface with a handful of methods, which is not public, has a single client, and no requirement to be backward compatible.

**Comment by 1st1** [comment]
> I would approach this from a different perspective: let's make the whole networking part of the compiler in Rust.

Paul, sorry, but I don't think that I can buy this approach. We'll rewrite `edb.server.edgecon`, `.pgcon`, and http/graphql ports first, leaving `edb.server.compiler` as is. This is big enough task as there's quite a lot of complexity and intricate code in edgecon etc. After we get the new IO working we can discuss rewriting the `edb.server.compiler` package and the rest of them.  Let's put this issue on hold.

**Comment by elprans** [comment]
Yes, I don't think the particular framing/serialization of the RPC messages is the most important (or difficult) issue here.  @tailhook raised other concerns in the top post, I suggest breaking them out into another issue (and not discuss the wire formats there).

**Comment by tailhook** [comment]
> The combined download monthly total of cbor and cbor2 on PyPI is around 100k (compare to 28M for protobuf and 3M for thrift, 3M for msgpack).

In rust, the situation is different. There is almost no msgpack (because CBOR is basically a nicer and standarized msgpack). And 0.7M downloads (50K monthly). It quite a lot for rust crate. And yes, writing both sides in rust should be easier and faster. (on the other hand, I've never measure the quality of a product by the number of downloads).

> As far as I can tell, the RPC implementation would require two new protocol envelopes: RPCRequest and RPCResponse,

No, we need:
1. A handshake. A really new one, because we aren't going to have the same protocol version for our "main protocol" and this one (well, yes the kinda same one with a different version is usually worse)
2. In the way that current protocol is written:
   * Request for compilation with schema, Response
   * Request for compilation without schema, Response
3. Ping/Pong packets (load balancing will be very bad if we don't know liveness of the connections)
4. Preload the schema notifications (or request/reply)
5. Some metrics interface (with this protocol on a different port)
6. Graceful shutdown message

This is just from the top of my head. I looks like you really underestimate what is needed there.

> all the hard work of implementing SerDe is done (and, come on, it's not that bad).

It's really bad:
1. There are a bunch of `ensure!(.., Underflow)` statements which are subject of off by one and copy-pasting issues (yes I've already caught some)
2. There are a bunch of "slice the buffer then advance the pointer" which is also easy to mess up
3. Mixing up with any offsets is reported in a very unreadable way (because something next is misinterpreted, and we can't do anything about that)
4. [Ints](https://github.com/edgedb/edgedb/issues/848) are handled inconsistently within the protocol, and also different size of strings...
5. There are a bunch of reserved fields which make serialization non-symmetric

I really don't understand why you like that over `Request(**cbor.loads(buffer))`.

------

And yes, I also want to stop discussing serialization here.

**Comment by 1st1** [comment]
To clarify, what I propose for the initial Rust rewrite:

1. Process pool logic `server/procpool` -- Rust will spawn CPython processes and communicate with them either via TCP or Unix sockets.  The communication protocol is now using pickle -- we want to switch it to use Postgres framing. There would be only two messages in that new protocol -- QueryUnit and Error.

2. `server/mng_port/edgecon` -- this is the server-side EdgeDB proto implementation.

2. `server/pgcon` -- implementation of the necessary low-level bits of Postgres protocol.

3. `server/http_edgeql_port`, `server/http_graphql_port` -- EdgeQL and GraphQL HTTP endpoints.

4. `server/dbview` -- tracks db state

5. `server/main` -- edgedb server

6. `server/cluster` -- bits and pieces to run & control Postgres instance

------

* `server/compiler` won't be rewritten as part of this initial Rust effort.  I don't want to use HTTP/WebSockers/CBOR or anything else in that code right now.

**Comment by 1st1** [comment]
> This is just from the top of my head. I looks like you really underestimate what is needed there.

Elvis and I both understand that it isn't going to be a 2 liner. Using an HTTP/WebSocket/CBOR layer while looks easier also introduces third-party deps and frankly, the state of HTTP support in Python is so so. We both have extensive experience working with protocol buffers and thirft and their quality in Python is very questionable.

If you really had experience with CBOR in Python we can try using it instead of Postgres framing (@elprans would you be OK with that?), but I'm still -1 on using websockets or http for communicating with Python.

**Comment by tailhook** [comment]
> To clarify, what I propose for the initial Rust rewrite:

I still don't understand higher-level architecture. Here is my take on it. We have:
```
client -> main process -> compiler -> postgres
```
As long as I understand we want to rewrite the whole "main process" in rust. Am I wrong? Are there any really huge and complicated things in the main process?

Also, we drop the connection between compiler and Postgres, right? (it looks like @elprans somewhat agreed with that, but that agreement looks vague). 

> Rust will spawn CPython processes and communicate with them either via TCP or Unix sockets

I expect to skip this. We can have a tiny script that spawns rust, compiler, and Postgres (for me vagga solves that, but nevermind). And for production, there are tons of supervisors that can do that job (for the cloud we're going to run them on different VMs anyway).

I kinda have a lot of experience in writing supervisors and it's quite a bit of work. Also, spawning processes and async code is not a great combination.

> If you really had experience with CBOR in Python

Yes, albeit 5 years ago or so.

**Comment by tailhook** [comment]
Here is another complication of the protocol: https://github.com/edgedb/edgedb/issues/1023

**Comment by elprans** [comment]
> I still don't understand higher-level architecture. 

Currently, it's more like this:

```
client -> main process <-> compiler
               | # queries    | # load schema
               v              | 
             postgres <-------/   
```

> Also, we drop the connection between compiler and Postgres, right? (it looks like @elprans somewhat agreed with that, but that agreement looks vague).

I said I agree that this makes a cleaner separation, but we need to think this through to see if possible downsides outweigh the upside.

> I expect to skip this. We can have a tiny script that spawns rust, compiler

NAK. This will make development and testing a mess with stray processes.  I still want my server process to be attached to a TTY, and I want ^C to do the right thing.

**Comment by tailhook** [comment]
> > Also, we drop the connection between compiler and Postgres, right? (it looks like @elprans somewhat agreed with that, but that agreement looks vague).
> 
> I said I agree that this makes a cleaner separation, but we need to think this through to see if possible downsides outweigh the upside.
> 

Sure. This is why I'm bringing it in advance. Please keep us updated if you find any.

> > I expect to skip this. We can have a tiny script that spawns rust, compiler
> 
> NAK. This will make development and testing a mess with stray processes. I still want my server process to be attached to a TTY, and I want ^C to do the right thing.

So what is a problem with that:
```
-+= python -m edb.supervisor_for_elvis
 |--- rustish_server
 |--- python -m edb.server.protocol.worker
 \--- postgres
```
Even if, for whatever reason, we want to rewrite that in rust, it still doesn't have to be the same process/codebase. And also there are few things that do that including Ctrl+C handling: supervisord, docker-compose and vagga to name a few.

**Comment by elprans** [comment]
> So what is a problem with that

As long as it's not worse than what we currently have, I'm fine with whatever approach.  I'm NOT fine with having to hunt and `kill` orphaned subprocesses.  In my workflow I restart the server very often, so it needs to start quickly and shut down cleanly.  Docker and other virtualization/containerization is a non-starter for me due to long startup time.

**Comment by tailhook** [comment]
> Docker and other virtualization/containerization is a non-starter for me due to long startup time.

Just FYI: Vagga starts in < 100ms per container for most containers. And containers (not docker though) is the most reliable way to kill process subtree on linux (killing pid 1 kills everything in the container).

All of that is not true when running (docker) from MacOS, though.

**Comment by elprans** [comment]
> Vagga starts in < 100ms per container

Does that include the time needed to rebuild the container image?

**Comment by tailhook** [comment]
> Does that include the time needed to rebuild the container image?

No. But it includes (some) versioning. I.e. it checks whether the image needs to be rebuild. And with vagga you only need to rebuild the image if dependencies change (that's a very coarse description, but this is offtopic here).

**Comment by msullivan** [comment]
Is there still something here?

**Comment by tailhook** [comment]
Nothing that is going to implemented soon.
