### ISSUE TITLE
Authentication is under documented

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#1021]
First, it took me ~30 minutes to figure out:
```
edgedb --admin configure insert auth --method=scram --priority=1
```
And I'm not sure is priority right.

Second, how does `create role` works? I.e. I can create a role and set a password. I still don't know to give that role access to a given database.

**Comment by elprans** [comment]
The `Auth` configuration object is documented here: https://edgedb.com/docs/admin/configuration
I agree that this deserves a dedicated section, though.

> I still don't know to give that role access to a given database.

Auth entries in EdgeDB are analogous to `pg_hba`. You can specify role/database mapping for a given auth rule with `--user` and `--database`:

```
edgedb --admin configure insert auth --method=scram --priority=1  --user=foo --database=foo
```

**Comment by tailhook** [comment]
> The `Auth` configuration object is documented here: https://edgedb.com/docs/admin/configuration
> I agree that this deserves a dedicated section, though.
> 

Well, it was hard to even find out that passing `Auth` and `--method` in that form. I've tried `auth.method` and `auth_method` and maybe few others. And also `set` vs `insert`.

> > I still don't know to give that role access to a given database.
> 
> Auth entries in EdgeDB are analogous to `pg_hba`. You can specify role/database mapping for a given auth rule with `--user` and `--database`:
> 
> ```
> edgedb --admin configure insert auth --method=scram --priority=1  --user=foo --database=foo
> ```

* So after creating a role I also need to add a configuration record? (sounds weird to me)
* What records without role and database mean then? Are they only for "trust all" records.
* Priorities aren't clear: is priority=1 highest or lowest priority? (I also see `-1` in tests).
* How can I list those configuration records?

**Comment by tailhook** [comment]
This doesn't work:
```
> edgedb --admin create role test_user1 --password 
Password: 
Repeat for confirmation: 
> edgedb --admin configure insert auth --method=scram --priority=3 --user=test_user1 --database=tutorial
CONFIGURE SYSTEM
> edgedb --user test_user1 --password -d tutorial                                         
Password: 
Could not establish connection to tutorial: could not authenticate
```

**Comment by elprans** [comment]
> So after creating a role I also need to add a configuration record? (sounds weird to me)

This is exactly how Postgres works as well.

> What records without role and database mean then? Are they only for "trust all" records.

Hm.  There seems to be an issue here.  We should either make them required or default to '*' (ie "all").

> Priorities aren't clear: is priority=1 highest or lowest priority? (I also see -1 in tests).

Lower number means higher priority.  Perhaps we should rename the property.

> How can I list those configuration records?

By querying the config:

```
SELECT cfg::Config.auth {
   priority,
   method,
   ...
}
```

> Could not establish connection to tutorial: could not authenticate

A record you've created previously is being matched, and since it contains an empty set of databases, auth fails.  Remove it, and things should work:

```
edgedb configure reset auth --priority=1
```

**Comment by tailhook** [comment]
Well, I needed also `--allow-login` (why isn't it a default?) and reset `priority=0` trust record.
