### ISSUE TITLE
Discussing complied query cache (spin off of #1020)

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#1023]
Basically there are two possible methods:

(1) The main process checks the cache **(preferred)**:
```
client -> main process -> complier
          \----->cache
```
(2) The compiler checks cache itself:
```
client -> main process -> complier -> cache
```

## Implications

This feature interacts with **constant extraction**:
> The constant extraction is the feature that turns request like
> ```
> SELECT User FILTER .username = "john"
> ```
> Into:
> ```
> SELECT User FILTER .username = <str>$var1
> ```
> So that we can cache compiled query with different constant values

This feature means that if we want method (1) we need to send to the compiler process not the textual query but a token stream:
```
[Token(SELECT, position=(1,1)), Token(User, position=(7,1)) ...
```
Because text-to-text transformed string would yield invalid error positions.

I.e. request like this:
```python
def compile(query: str, schema: Schema): ...
```
Turns into this:
```python
def compile(query: List[Token], schema: Schema): ...
```

**Comment by elprans** [comment]
> (1) The main process checks the cache (preferred):

Yes, this is preferred and is already the case.

> This feature means that if we want method (1) we need to send to the compiler process not the textual query but a token stream:

Sure, that seems reasonable, although we might still want to have a two-level cache, i.e. check by query text first, since, in practice, the vast majority of production queries will already be parametrized.

**Comment by 1st1** [comment]
Anything we should do here?

**Comment by elprans** [comment]
This was implemented with the Rust tokenizer and constant extraction, so closing.
