### ISSUE TITLE
InternalServerError: relation "m~2" does not exist

### ISSUE THREAD

**Issue by vpsx** [edgedb/edgedb#1033]
Hello! I was following the tutorial pretty closely up until after the steps "add Zendaya" and "update Dune" but before the step "use SDL to update Person type with computable name". At this point I decided to mess around a bit and try:

```
tutorial> UPDATE Movie
......... FILTER Movie.title IN {'Dune', 'Blade Runner 2049'}
......... SET {
.........     director := (
.........         INSERT Person {
.........             first_name := 'vpsx',
.........             last_name := 'the Amazing'
.........         }
.........     )
......... };
```
and I got
```
InternalServerError: relation "m~2" does not exist
```
I searched edgedb issues for InternalServerError and didn't find this but found 930 suggesting I file an issue so here I am. 

EdgeDB seems very cool!!!

**Comment by elprans** [comment]
Hi @vpsx! Thanks for reporting.  This particular issue has been fixed in 4a3bef762c3ea39990486b124552a6fb3dfde342. We'll be cutting a release with this and many other fixes soon.
