### ISSUE TITLE
Error on updating enum link property: Schema does not exist

### ISSUE THREAD

**Issue by kfrp** [edgedb/edgedb#1038]
Hello, I've referenced this schema [before](https://github.com/edgedb/edgedb/issues/904#issuecomment-561610223) so am reporting a couple of new errors that I got on trying it with the latest build. 

Note that I get the same error if, instead of an enum for ratings, I use a custom scalar with a `one_of` constraint. However, everything works as expected if I use a string as the link property and put the constraint directly on it. 

Schema:
```
scalar type Rating extending enum<'1', '2', '3', '4','5'>;
type User { ... }
type Product {
  multi link users -> User {
    property rating -> Rating 
    # but this works: property rating -> str { constraint one_of ('1','2','3','4','5') }
  }
}
```

EdgeQL query:
```
With P := (SELECT Product FILTER .id= $productID ),
U := (SELECT Person FILTER .id = $userID)
UPDATE P SET {
  users := (
    FOR b IN { (P.users, <str>P.users@rating ?? '') UNION (U, '2') }
    UNION b.0 { @rating := <Rating>b.1 IF b.1 != '' ELSE <Rating>{} }
  )
};
```
Error:
```
InternalServerError: schema "edgedb_613d5cac-2faa-11ea-8129-139f1568d892" does not exist
```
Here's another error I saw while trying to select the UNION tuple directly. This happens regardless of the rating type (enum or string link property with constraints).
Query:
```
With P := (SELECT Product FILTER .id= $productID )
SELECT ( (P.users, P.users@rating ?? '' ) UNION ((SELECT User FILTER .id = $userID LIMIT 1), '2') );
```
Error:
```
InternalServerError: cannot describe type default::User
```

String + constraint works totally fine for my use case, but I am curious about whether enums come with any kind of default indexing that makes it relatively faster to query e.g. all orders with a 1 rating. I also tried to see how to set an index on a link property but I got a syntax error saying 'Unexpected index'. 

Thanks and happy new year!

**Comment by elprans** [comment]
Hi @cosmophile,

Thanks for reporting the issues!

> I am curious about whether enums come with any kind of default indexing that makes it relatively faster to query

Enums make use of PostgreSQL's enum types.  The main advantage is that they're represented as a small integer value internally, whereas a string with a one-of constraint would get stored/indexed repeatedly, wasting storage space.  I don't think there's a measurable performance difference between the two, though.  Enums also come with caveats: you cannot remove an enum value from an existing enum type (you can only drop and recreate the type), and when you add an enum value to an enum type, you cannot refer to that value in the same transaction as the DDL adding the value.

**Comment by 1st1** [comment]
@elprans anything to act on this one? Close if not.

**Comment by msullivan** [comment]
I think this is fixed
