### ISSUE TITLE
Drop JSON mode from REPL

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#1043]
The JSON output mode is a historical relic of when it was the only option.  It serves no purpose anymore.

**Comment by tailhook** [comment]
Still, I think it makes sense to keep JSON for non-interactive mode. I.e. for piping it to `jq` tool.

**Comment by 1st1** [comment]
> It serves no purpose anymore.

Well, first, it lets people know that EdgeDB *has JSON* mode.  Second, what if you have a quick analytical/regular query and you just want to copy/paste its results somewhere? JSON makes that easy. Lastly, I agree with Paul that it's useful for non-interactive mode.

So I'd like to hear a better motivation for removing this feature.

**Comment by elprans** [comment]
OK. Let's keep it.
