### ISSUE TITLE
Overloading read-only flag

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#1047]
Currently it's possible to override a `readonly` flag when extending a type, which seems fine until we consider the following issues:
```
type A {
   property foo -> str;
}

type B extending A {
   overloaded property foo -> str {
      readonly := True;
   }
}
```
Currently the above schema will not allow the command `UPDATE B SET {foo := 'new'}`, but will allow the `UPDATE A SET {foo := 'new'}`, which will happily update all of `B`. There are 3 options for resolving this:
1) Treat `readonly` like cardinality and completely forbid overloading it in any way.
2) Treat `readonly` like constraints and implement a run-time check instead of a compile-time check for this.
3) Treat `readonly` as a flag that can only be overloaded from `True` to `False` - this is easy to implement as a static check, but leads to possibly counter-intuitive behavior.

Another example to consider when deciding the appropriate strategy is highlighted by multiple inheritance and by union types:
```
type C {
   property foo -> str {
      readonly := False;
   }
}
type D {
   property foo -> str {
      readonly := True;
   }
}
type E extending C, D;
type F extending D, C;

type G {
   link bar0 -> C | D;
   link bar1 -> E;
}
```
Should the `readonly` flag in E and F be same or different (based on inheritance order)? What should `UPDATE G.bar0 SET {foo := 'new'}` vs.`UPDATE G.bar1 SET {foo := 'new'}` do?

Note that, In principle, `readonly` defines valid data operations, whereas `constraint` defines the data domain, so they don't have to behave similarly.

We can implement option 1) as the most conservative for the time being and then decide if we want to relax it in any way later.

**Comment by vpetrovykh** [comment]
This incidentally makes me wonder how we handle interaction between `on target delete allow` and `readonly`. More specifically, should we forbid `on target delete allow` if `readonly` flag is set for the link?

**Comment by elprans** [comment]
This seems to be done.
