### ISSUE TITLE
Slash commands are cryptic

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#1053]
Currently, we have slash commands like `\d`, `\l`, '\lm` in REPL, which are hard to remember.

I.e. after about 7 years of mostly using postgres I'm still struggling to remember what's difference between `\d` and `\dt`. But I still remember `SHOW TABLES` from mysql. Which is clean, easy to remember and I don't think typing speed matters here.

For now, I don't think we need to introduce full-featured language syntax for introspection, but I think we can have full-length aliases for commands like:
* `\decribe`
* `\list databases`
* `\list modules`

Not sure how it affects commands grammar, but since we already have some long commands it should be implementable.

What do you think?

**Comment by tailhook** [comment]
Second thought, we can directly map these long commands to a command-line, so dash style might be better here (and perhaps easier to parse):
* `\list-roles` -> `edgedb list-roles`
* `\describe Movie` -> `edgedb describe Movie`

**Comment by ambv** [comment]
+1 on more descriptive names for backslash commands. I have the same bad experience with sqlite. For some reason the magic single letter forms don't stick.

**Comment by elprans** [comment]
Longer commands are, well, longer to type, but I don't disagree with the memorability argument.  I think we can have both, i.e. `\lr` and `\list-roles`.

**Comment by tailhook** [comment]
Done, in rustic repl.
