### ISSUE TITLE
DDL syntax to revert changes to some schema object.

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#1065]
There are situations where reverting some changes to the schema is desirable. Consider the following examples:

### Annotations
We start off with a schema like this:
```esdl
abstract inheritable annotation my_anno;

type Foo {
  annotation my_anno := 'forever';
}
type Bar extending Foo {
  annotation my_anno := 'nope';
}
```
Then we decide that actually it wasn't a great idea overriding the inherited annotation `my_anno` in `Bar`, so we want to migrate to:
```esdl
abstract inheritable annotation my_anno;

type Foo {
  annotation my_anno := 'forever';
}
type Bar extending Foo;
```
But how will this be implemented? How to do this in DDL? Currently the only way is to first `DROP ANNOTATION my_anno` from Foo, then add it back. This is somewhat round-about way of doing this especially if the inheritance hierarchy is deeper and contains more places where the inherited annotation is overridden which we don't want to change.

### Links
We start with the following:
```esdl
type Foo {
  link stuff -> Object;
}
type Bar extending Foo {
  overloaded link stuff -> Foo;
}
```
Once we've added some data we decide that in retrospect we don't want `Bar.stuff` to link exclusively to `Foo`, but the base class approach was just fine.
```esdl
type Foo {
  link stuff -> Object;
}
type Bar extending Foo;
```
So the question is how is this migration done? Ideally we expect the data to be preserved and there's nothing particularly ambiguous about the intent here, but we can't just drop the link and re-create it like with annotations since that will discard data. So the question is: what's the correct DDL to use here? (Incidentally, SDL migration works fine preserving the data)

The obvious user choice for DDL is `ALTER TYPE Bar {ALTER LINK stuff {SET TYPE std::Object}};`, but that makes the link `overloaded` rather than actually inheriting without alterations. There are some system fields that are used by the SDL migration that user-DDL simply cannot use, like `is_local`. This has little _functional_ difference, but it does result in a different schema ultimately.

**Comment by elprans** [comment]
This was implemented in c6cc25da9c46d and 529da2d4f8ada.
