### ISSUE TITLE
Cannot create new type within module

### ISSUE THREAD

**Issue by agritheory** [edgedb/edgedb#1072]
Recreating the issue:

<pre><font color="#585858"><b>EdgeDB 1.0.alpha.1</b></font>
<font color="#585858"><b>Type &quot;\?&quot; for help.</b></font>

<font color="#A8A8A8">edgedb&gt; </font><font color="#D75F5F">CREATE</font> <font color="#D75F5F">DATABASE</font> test_ledger;                                                                                                                  
<font color="#585858"><b>CREATE</b></font>
<font color="#A8A8A8">edgedb&gt; </font><font color="#D75F5F">CREATE</font> <font color="#D75F5F">MODULE</font> ledger;                                                                                                                         
<font color="#585858"><b>CREATE</b></font>
<font color="#A8A8A8">edgedb&gt; </font><font color="#D75F5F">START</font> <font color="#D75F5F">TRANSACTION</font>;                                                                                                                            
<font color="#585858"><b>START TRANSACTION</b></font>
<font color="#A8A8A8">edgedb&gt; </font><font color="#D75F5F">WITH</font> <font color="#D75F5F">MODULE</font> ledger 
<font color="#878787">....... </font><font color="#D75F5F">CREATE</font> <font color="#D75F5F">MIGRATION</font> test_what_module_type_is_created_in <font color="#D75F5F">TO</font> { 
<font color="#878787">....... </font>  <font color="#D75F5F">type</font> Currency { 
<font color="#878787">....... </font>    <font color="#D75F5F">required</font> <font color="#D75F5F">property</font> name <font color="#D75F5F">-&gt;</font> <font color="#AFD700">str</font> { 
<font color="#878787">....... </font>        <font color="#D75F5F">constraint</font> <font color="#AFD700">exclusive</font>; 
<font color="#878787">....... </font>    } 
<font color="#878787">....... </font>    <font color="#D75F5F">required</font> <font color="#D75F5F">property</font> precision <font color="#D75F5F">-&gt;</font> <font color="#AFD700">decimal</font>; 
<font color="#878787">....... </font>    <font color="#D75F5F">property</font> enabled <font color="#D75F5F">-&gt;</font> <font color="#AFD700">bool</font>; 
<font color="#878787">....... </font>    <font color="#D75F5F">index</font> currency_idx <font color="#D75F5F">on</font> (<font color="#AFD700">__subject__</font>.name); 
<font color="#878787">....... </font>  } 
<font color="#878787">....... </font>};                                                                                                                                            
<font color="#585858"><b>CREATE MIGRATION</b></font>
<font color="#A8A8A8">edgedb&gt; </font><font color="#D75F5F">COMMIT</font> <font color="#D75F5F">MIGRATION</font> test_what_module_type_is_created_in;                                                                                         
<font color="#585858"><b>COMMIT MIGRATION</b></font>
<font color="#A8A8A8">edgedb&gt; </font><font color="#D75F5F">WITH</font> <font color="#D75F5F">MODULE</font> schema 
<font color="#878787">....... </font><font color="#D75F5F">SELECT</font> ObjectType { 
<font color="#878787">....... </font>    name, id 
<font color="#878787">....... </font>};                                                                                                                                            
<font color="#AFAF5F">{</font>
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;std::Object&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3f35c65c-1b5e-11ea-89d6-0f311d0b2fec&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Object&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3f76ff3e-1b5e-11ea-b9dc-ab2d88a6ab14&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Type&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3f785026-1b5e-11ea-944a-e76a73a8e6a6&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::PseudoType&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3f794b1e-1b5e-11ea-956c-7f977ea39b01&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Module&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3f7d1b4a-1b5e-11ea-9e6f-33b304d94d7c&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::CollectionType&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3f7db6b6-1b5e-11ea-93aa-b159d24ac3cb&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Array&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3f7e6eb8-1b5e-11ea-a000-11fba0d2683c&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::TypeElement&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3f82a828-1b5e-11ea-b760-419732bfa8b5&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Tuple&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3f8757ec-1b5e-11ea-a8d3-f1677ea1289c&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Delta&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3f8d7a90-1b5e-11ea-9364-d50242a02a3e&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Annotation&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3f913f02-1b5e-11ea-8856-35ff20e011db&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::AnnotationSubject&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3f929ff6-1b5e-11ea-869d-87013d94f36f&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::InheritingObject&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3f9799b0-1b5e-11ea-9e31-4d149df42587&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Parameter&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3fa1857a-1b5e-11ea-a64e-61f469f3322e&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::CallableObject&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3fab5a36-1b5e-11ea-880c-6fe7b20ac958&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Constraint&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3fb64c58-1b5e-11ea-88e0-fbc0004352c1&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::ConsistencySubject&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3fc3fa38-1b5e-11ea-bc34-2dfc418aff02&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Index&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3fcf5f18-1b5e-11ea-8c7c-ad61330ba79c&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Source&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3fd13a40-1b5e-11ea-8bd1-6fa980d66e0f&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Pointer&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3fd807e4-1b5e-11ea-93c6-c13a9638b2db&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::ScalarType&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3fe2879e-1b5e-11ea-b7fd-fbbbe670ff48&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::ObjectType&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3fe664e4-1b5e-11ea-a89f-91b5d9fdc129&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::UnionObjectType&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3fe80af6-1b5e-11ea-a5db-c3c9770858d8&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::DerivedObjectType&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3fe96e1a-1b5e-11ea-88e9-e19d7322d83b&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Link&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3feace02-1b5e-11ea-a16f-fbc587bb7695&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::DerivedLink&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3fec3a1c-1b5e-11ea-bac2-39f558e1bba5&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Property&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;3fed9752-1b5e-11ea-a8ce-a7dd15d1539d&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Function&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;4007a99e-1b5e-11ea-b8f8-07b90d8d1178&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Operator&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;4008904a-1b5e-11ea-8e47-751058b8b087&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;schema::Cast&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;400e92a8-1b5e-11ea-b7f9-13a5028fb687&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;sys::Database&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;40345d6e-1b5e-11ea-989a-0bc1709642da&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;sys::Role&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;4036b566-1b5e-11ea-a73b-d3d4165b7d52&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;cfg::Port&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;405c8cc6-1b5e-11ea-ace5-5184345e6951&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;cfg::AuthMethod&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;4068687e-1b5e-11ea-810c-f76fc2fe45dd&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;cfg::Trust&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;40691280-1b5e-11ea-a880-f5f58e43cafd&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;cfg::SCRAM&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;4069ae6c-1b5e-11ea-ae88-5fca24b07ec0&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;cfg::Auth&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;406b731a-1b5e-11ea-ae18-3b5498ca2923&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;cfg::Config&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;407feb74-1b5e-11ea-b5b6-fff433274d0c&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;stdgraphql::Query&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;409e55f0-1b5e-11ea-b2a5-4f0272d94b2d&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;stdgraphql::Mutation&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;40a19af8-1b5e-11ea-ae51-83a72f8e691b&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>,
    <font color="#AF5FD7"><b>Object {</b></font> <font color="#5F875F"><b>name</b></font>: <font color="#5FAF00">&apos;default::Currency&apos;</font>, <font color="#5F875F"><b>id</b></font>: <font color="#585858"><b>&lt;uuid&gt;&apos;00c857e8-3354-11ea-948d-1dffadfdf51f&apos;</b></font> <font color="#AF5FD7"><b>}</b></font>
<font color="#AFAF5F">}</font>
<font color="#A8A8A8">edgedb&gt; </font> 
</pre>

The `WITH MODULE ledger` declaration has no effect when declaring a type in a migration as far as I can tell.

**Comment by elprans** [comment]
Hey @agritheory.  Thanks for the report!  This has been fixed in the upcoming Alpha 2 (in #907).

**Comment by 1st1** [comment]
Since this is fixed in a2 (should be out in just a few days), I'm going to close this one. Thanks for reporting the bug though!

**Comment by agritheory** [comment]
Thanks guys. Looking forward to alpha 2.
