### ISSUE TITLE
server bootstrap did not complete successfully

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#1094]
I tried running docker image of edgedb with:
```
docker run -it --rm -p 5656:5656 -p 8888:8888 \
            --name=edgedb-server \
            -v $PWD/edb:/var/lib/edgedb/data \
            edgedb/edgedb:nightly -l d
```
I tried both `nightly` and `latest` tags, none of them worked.

Debug log from nightly container: https://gist.github.com/Fogapod/6be88881ef28b858efac78b4face4ee1

My guess is that the problem might be low available resources. Server only has 500mb ram in total and a weak 1 core cpu.

**Comment by elprans** [comment]
Yes, this might be an OOM situation, although it doesn't show in the log.  Server kernel logs might show this.

**Comment by Fogapod** [comment]
Kernel logs showed that this was an OOM.
```
[364748.564073] Out of memory: Kill process 2639 (postgres) score 298 or sacrifice child
[364748.566865] Killed process 2639 (postgres) total-vm:415220kB, anon-rss:133544kB, file-rss:0kB, shmem-rss:13828kB
```
What are the recommended minimum requirements for running edgeql?

**Comment by 1st1** [comment]
I think we discussed this in another issue #1221
