### ISSUE TITLE
Allow DML statements only in top-level WITH

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#110]
This follows from the PostgreSQL restriction on [DML CTEs](https://www.postgresql.org/docs/current/static/queries-with.html#QUERIES-WITH-MODIFYING).  

Theoretically, we might be able to unwind and linearise the query in such a way that would put all DML statements on the top level, but that's not guaranteed and is a lot of work.  Thus, allow using `INSERT`, `UPDATE` and `DELETE` as expressions only in the top-level `WITH` block.

**Comment by vpetrovykh** [comment]
We also need to make sure that `UPDATE` statements don't execute nested `INSERT` if the set to be updated turns out to be empty.

**Comment by 1st1** [comment]
@elprans @vpetrovykh what's the plan on this one?

**Comment by elprans** [comment]
The plan is to retain the current ability to use DML as expressions arbitrarily, but add a restriction that prohibits them in conditionals (i.e. `IF`, `??` etc).

**Comment by elprans** [comment]
See also #684

**Comment by 1st1** [comment]
So we close this one?

**Comment by elprans** [comment]
Yeah, I'll open a new issue instead.
