### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#1123]
EdgeDB version: `1.0-alpha.2+dev.505.g5b68ec24` (docker image)
Docker version: `19.03.5-ce, build 633a0ea838`

I noticed that EdgeDB uses 5GB of RAM on my server after a few days of running it.
I found out that there are a lot of processes:
```bash
~ ps -ef|grep edgedb|wc -l
141
```

Looks like the reason for that are unclosed interactive sessions:
```bash
~ docker exec -it edgedb-server edgedb -u modbay_beta
# ...
~ ps -ef|grep edgedb|wc -l
142
```

After restarting containers all these processes are gone and RAM usage is under 150mb:
```bash
~ docker restart edgedb-server
edgedb-server
~ ps -ef|grep edgedb|wc -l
7
```

**Comment by Fogapod** [comment]
Update: process number stopped growing after container restart. It increased by 1 every time before, but now it remains constant.

How I can debug high memory usage in future?
What else could cause this? Dirty disconnects? I might had some.

**Comment by elprans** [comment]
> Dirty disconnects? 

Yes, that's the most likely cause, but EdgeDB should obviously handle this better.

**Comment by Fogapod** [comment]
It looks like memory usage raises even without dirty disconnects.
I made sure I always call `await pool.aclose()` and I always check that there are no tracebacks.
I have to restart db container at least once a day because memory usage raises to several gigs.

Is there a way to list active sessions or other way to list active resources?

**Comment by 1st1** [comment]
> Is there a way to list active sessions or other way to list active resources?

Not yet. We'll see if we can add functions / repl commands to inspect the resources consumption.

**Comment by Fogapod** [comment]
The situation improved a lot since then. I have edgedb instance running for days, I created and closed a lot of connections and repl sessions, no noticeable memory usage increase, process count is low.

**Comment by 1st1** [comment]
Thanks for the update!

**Comment by elprans** [comment]
> The situation improved a lot since then. I have edgedb instance running for days

Closing.  Feel free to open a new issue if you see abnormal behavior again.
