### ISSUE TITLE
Insane CPU usage during client connection

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#1126]
EdgeDB version: `1.0-alpha.2+dev.505.g5b68ec24` (docker image)
Python lib version: `0.7.0a9`
Docker version: `19.03.5-ce, build 633a0ea838`

I run my client on a remote host, each time I try to connect to the server, CPU usage raises from 1-2% to 100% and stays there for a few seconds.
![image](https://user-images.githubusercontent.com/22667809/72547597-fcc4d380-389d-11ea-9260-49bd6ac0124b.png)

Top processes are:
![image](https://user-images.githubusercontent.com/22667809/72547940-bae85d00-389e-11ea-8675-1ca0dcc95e04.png)

This does not happen when I connect to database using CLI tool from host machine.
CPU usage on client machine is always low.

CPU information:
```
~ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   40 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           62
Model name:                      Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
Stepping:                        4
CPU MHz:                         2099.998
BogoMIPS:                        4199.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        16 MiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0-3
```

**Comment by elprans** [comment]
Looking at your Python code would be helpful.  Do you use a connection pool?

**Comment by Fogapod** [comment]
Yes, I do:
```python
app["edgedb"] = await edgedb.create_async_pool(**app["config"]["edgedb"])
```
Just running this line causes problem for me.

**Comment by elprans** [comment]
This is a known issue.  Brand new connections are currently expensive due to slow schema introspection.  We are working on solving this by making introspection more efficient.  We will also add support for a built-in connection pool that supports regular EdgeDB protocol, in addition to EdgeQL+HTTP (https://edgedb.com/docs/clients/90_edgeql/index).  Connections to application ports would be very cheap.

**Comment by 1st1** [comment]
Closing this one as I don't think we can do anything about this.
