### ISSUE TITLE
It's hard to find errors in long REPL queries

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#1148]
- EdgeDB Version: `1.0-alpha.2+dev.505.g5b68ec24`
### Description
Error output currently looks this way: 
![Screenshot_2020-01-19-19-54-53](https://user-images.githubusercontent.com/22667809/72684911-9c2fd380-3af5-11ea-8ab1-a53ea733cb8d.jpeg)

This is fine for small queries, but what if query has 100 or more lines?

I faced this problem trying to debug my migration, python driver does not return line number of error yet.
REPL does this by using small `^` symbol without syntax highlighting.

### Proposals
- REPL can print number of line if length of query is more than X lines
- Highlight problematic part with colors somehow
- Put something something like `#!!` at the beginning of line containing error instead of `###`

**Comment by tailhook** [comment]
Thank you for reporting!

The new rust version of the REPL now shows only the erroneous line, like this:
![new_error](https://user-images.githubusercontent.com/321799/75770843-741ccc80-5d51-11ea-9563-aacc1ff94243.png)

Hopefully, it's good enough.
