### ISSUE TITLE
EdgeQL features test coverage

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#115]
This is a rough list of how well various features are tested. There are 3 levels of test coverage:
- ✅ there are lots of thorough tests
-  🔴 there are some tests, so probably we caught major issues
- :worried: this feature is barely tested if at all 

- [x] basic element-wise arithmetic operators ✅
- [x] tuples ✅
- [x] simple functions ✅
- [x] simple aggregates ✅
- [x] IF ✅
- [x] FILTER ✅
- [x] DELETE ✅
- [x] INSERT ✅
- [ ] DDL 🔴
- [ ] cardinality 🔴
- [x] DISTINCT ✅
- [x] UNION ✅
- [ ] arrays 🔴
- [x] link properties (SELECT) ✅
- [ ] shapes / views 🔴
- [ ] GROUP 🔴
- [ ] scoping 🔴
- [ ] transactions 🔴
- [ ] maps 🔴
- [x] coalesce ✅
- [ ] functions with complex signatures :worried:
- [ ] FOR 🔴
- [ ] UPDATE 🔴
- [ ] link properties (INSERT/UPDATE) :worried:
- [ ] constraints 🔴
- [ ] DETACHED 🔴

**Comment by 1st1** [comment]
Should this one be closed or? @vpetrovykh

**Comment by vpetrovykh** [comment]
The list is both outdated and too difficult to maintain.
