### ISSUE TITLE
Prohibit or handle long database names

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#1158]
I finally realized why `test_dump01_restore_compatibility` is failing on macOS.  The path to the dump file is longer than the PostgreSQL's limit of 63 characters, and since the test uses the full path name for the database name, it fails, because Postgres silently truncates long names (it issues a NOTICE response, but not an error).

We have graceful handling of other schema classes in those cases, but not databases.

**Comment by 1st1** [comment]
Should this be closed now?

**Comment by elprans** [comment]
No, the linked PR is related, but does not fix the issue at hand.
