### ISSUE TITLE
EdgeQL cheat sheet

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#1163]
### Databases:
- [x] list databases
- [x] create a database
- [x] connect to a database

### Configuration:
- [x] configure a port
- [x] configure auth
- [x] create a role

### Types:
- [x] type list commands
- [x] create an object type
- [x] extend an object type
- [x] create a scalar type
- [x] extend a scalar type
- [ ] create an enum type
- [ ] extend an enum type

### Annotations:
- [ ] create an annotation
- [x] annotate a type

### Constraints:
- [ ] create a constraint
- [x] apply a constraint to a property
- [ ] apply a constraint to a link
- [ ] apply a constraint to a type

### Indexes:
- [x] create an index
- [ ] remove an index

### Aliases:
- [x] create an alias with a computable property
- [x] create an alias with a computable link (using backwards links)

### Queries:
- [x] select nested shapes
- [x] select filters
- [x] select sub-queries
- [x] select sub-queries using `WITH` block
- [ ] select cross-product
- [x] select correlated tuple elements (like name and count of friends)
- [x] insert data
- [x] nested insert data
- [x] delete query
- [x] update query
- [x] for query

### Migrations:
- [x] make a new SDL migration
- [ ] list migrations history

### Grammar:
- [x] regular vs quoted identifiers
- [x] different numeric literals
- [x] different string literals

### Functions:
- [ ] list functions
- [x] define a new function
- [x] remove a function

### GraphQL:
- [x] simple query
- [x] query with filter
- [x] query with order
- [x] insert mutation
- [x] update mutation

**Comment by vpetrovykh** [comment]
A few cheatsheet samples:
```
List databases:

.. code-block:: edgeql-repl
    db> \l
    List of databases:
      db
      tutorial

Create a database:

.. code-block:: edgeql-repl
    db> CREATE DATABASE my_new_project;
    CREATE

Connect to a database:

.. code-block:: edgeql-repl
    db> \c my_new_project
    my_new_project>

Select movies with Keanu Reeves:

.. code-block:: edgeql

    SELECT Movie {
        id,
        title,
        year,
        description,
    }
    FILTER .cast.full_name = 'Keanu Reeves'
```
These would belong to a couple different sections: such as "Databases" and "Queries".

**Comment by vpetrovykh** [comment]
We possibly want to add a whole GraphQL section to the cheat sheet, because GraphQL is hard to describe formally otherwise. Well, it's possible to describe, but because it's verbose a general description is not easy to read, since there are no "operators" or "filters" in it on the language level, making any reference to them a bit obscure.

**Comment by 1st1** [comment]
>We possibly want to add a whole GraphQL section to the cheat sheet, because GraphQL is hard to describe formally otherwise. Well, it's possible to describe, but because it's verbose a general description is not easy to read, since there are no "operators" or "filters" in it on the language level, making any reference to them a bit obscure.

Sure. Feel free to add it to the current cheat sheet PR or submit a new one today

**Comment by 1st1** [comment]
I'd say we're done with this.
