### ISSUE TITLE
Add constraint syntax to object types

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#1164]
Currently we allow declaring constraints only on properties and links (syntactically), but not on object types.  This is largely an oversight, since we already have all the necessary mechanisms.

**Comment by dlax** [comment]
Does this mean something like this?
```
type Person {
    required property first_name -> str;
    required property last_name -> str;
    constraint exclusive on ((__subject__.first_name, __subject__.last_name));
}
```

**Comment by elprans** [comment]
> Does this mean something like this?

Yes, that's correct.

**Comment by CodesInChaos** [comment]
The examples and tests all use `constraint exclusive`. Does this feature work with other constraints as well?

**Comment by elprans** [comment]
> Does this feature work with other constraints as well?

Absolutely.  This works:

```
create type User {
    create property first_name -> str;
    create property last_name -> str;

    create constraint max_value(20)
        on (len(array_join([__subject__.first_name, __subject__.last_name], " ")))
    {
        set errmessage := 'combined length of first and last name must not exceed 20 characters'
    }
};
```

> The examples and tests all use `constraint exclusive`

Yes, we need more tests and examples: #1609.
