### ISSUE TITLE
Computable links validation

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#117]
In EdgeDB a computable link is indistinguishable in behavior from a regular link. Which means that just like a regular link a computable link must point to *distinct* targets. This means that if we cannot prove that a computable link target only contains distinct objects, we must raise a compile time error.

E.g. the following is an error:
```
SELECT Issue {
    foo := Issue.owner UNION User
};
```
To resolve the error, an explicit `DISTINCT` can be added:
```
SELECT Issue {
    foo := DISTINCT (Issue.owner UNION User)
};
```

In particular, Views with some defined computable links are indistinguishable from Concepts with those same links for the purposes of querying. For example, a path involving a View is guaranteed to produce distinct objects.

**Comment by 1st1** [comment]
@elprans are we ready to close this?

**Comment by elprans** [comment]
This is still outstanding.

**Comment by 1st1** [comment]
@elprans please lay out the plan to fix this for @vpetrovykh or others.

**Comment by elprans** [comment]
The plan would be to introduce the new inferer for distinctness and enforce it like we do cardinality.
