### ISSUE TITLE
Current version does not automatically update in /var/lib/edgedb/current alpha1 to alpha2

### ISSUE THREAD

**Issue by agritheory** [edgedb/edgedb#1174]
- EdgeDB Version: switching from alpha1 to alpha2
- OS Version: ubuntu 18.04

Steps to Reproduce:

1. Install apha2
2. Uninstall alpha1
3. Start alpha2 
3. Run `edgedb` command

This returns:
> /usr/bin/edgedb: 15: exec: /usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/bin/edgedb: not found

This can be resolved manually (on ubuntu) with:
cd /var/lib/edgedb/
sudo nano current

Edit `/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/bin` to `/usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/bin`

**Comment by 1st1** [comment]
@elprans this one is likely a release blocker. See also https://spectrum.chat/edgedb/general/error-when-updating-from-alpha1-to-alpha-2~89091ce2-a31c-4af9-864e-77a90ea0102e

**Comment by elprans** [comment]
@1st1 We are shipping the Rust CLI in the next release, so this whole thing with managing the installation slots for the CLI will go away entirely.

**Comment by 1st1** [comment]
Alright, I'm closing this one then.
