### ISSUE TITLE
failed to lookup transaction error

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#1177]
`connection.execute` triggers an internal server error on the following script:

```
START TRANSACTION;
CREATE MIGRATION test TO {
    module default {
        scalar type MyEnum extending enum<"A", "B">;
        type Row {
            property an_enum -> MyEnum;
        }
    }
};
COMMIT MIGRATION test;
COMMIT;
```

**Comment by 1st1** [comment]
See also https://spectrum.chat/edgedb/general/struggling-with-enum-creating-with-python~274f6e6d-e45a-4b94-a430-652ddc89814e

**Comment by elprans** [comment]
Another instance of this error: https://spectrum.chat/edgedb/general/how-to-create-autoincrement-and-change-default-id-property-type~e05f7402-eb3d-438e-8e77-df582a9fa89c
