### ISSUE TITLE
No `to_datetime` variant for Unix timestamp conversion.

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#1183]
`to_datetime(epochseconds: float64) -> datetime` is missing.

**Comment by 1st1** [comment]
I'd say 'unix: float64' would be better. "epoch" means a different thing in Postgres so there's potential confusion.

**Comment by elprans** [comment]
We already have `epochseconds` in `datetime_get`.  `epoch` mode in Postgres is actually Unix, it has no relation to the internal timestamp "epoch".

**Comment by 1st1** [comment]
ok

**Comment by 1st1** [comment]
@vpetrovykh Relatively low priority, but would be nice to have in alpha 3 if you have time for this.

**Comment by RobertoPrevato** [comment]
I started working on this yesterday. It's a good one for me because I am learning more about how built-in functions work and are configured.
