### ISSUE TITLE
Create a Snap package for linux distors

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#120]
https://snapcraft.io

**Comment by ansarizafar** [comment]
Is there any progress on this issue?

**Comment by 1st1** [comment]
We'll work on packaging closer to the alpha release in a couple of months.

**Comment by ansarizafar** [comment]
> We are working full steam on preparing the code base to be released. Hopefully we'll have a first preview version available in the very beginning of 2016
https://www.reddit.com/r/Database/comments/3l72ga/new_object_database_edgedb_soon_to_be_released/

Edgedb is a great idea but painfully slow development is really discouraging. A formal road map/Timeline and an proper installer package will encourage developers to try Edgedb and contribute.

**Comment by thomaszdxsn** [comment]
@ansarizafar +1

**Comment by 1st1** [comment]
Our internal timeline for releasing first alpha is 2-3 months. Things will go faster after that.

**Comment by ansarizafar** [comment]
Is there any chance of a stable release with JavaScript bindings this year?

**Comment by 1st1** [comment]
Beta release with node bindings yes.

**Comment by 1st1** [comment]
I understand your frustration, but there's nothing you can do to change our schedule. We have enough things to worry about right now and are actually busy working on edgedb and many related things. Please stop complaining here, it's not productive.

**Comment by 1st1** [comment]
We now have the packaging infra and will ship native packages for many linux distributions. No need for snap packages now; closing this.
