### ISSUE TITLE
Unexpected cardinality error

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#1201]
```
db> WITH
...     MODULE schema,
...     I := Constraint
... SELECT I {
...     cons_subj := I.subject {
...         of := I.subject[IS Pointer].<pointers[IS Source] {
...             of := I.subject[IS Pointer].<pointers[IS Source][IS Link].<links[IS Source].name,
...         },
...     },
... }
... FILTER
...     .cons_subj.of.name LIKE 'default::%'
...     OR .cons_subj.of.of LIKE 'default::%';
QueryError: possibly more than one element returned by an expression where only singletons are allowed
```
What's odd about this is that there's nothing in this query that I can think of that requires singleton cardinality.
Another issue is that this is not 100% reproducible, occasionally the query just goes through, so there's some non-deterministic component in this bug.

**Comment by dmgolembiowski** [comment]
Does adding a `LIMIT 1;` after `OR .cons_subj.of.of LIKE 'default::%' resolve the issue?

**Comment by elprans** [comment]
The error is that in the @vpetrovykh query there aren't any clauses that require singletons, this is actually caused by improper link cardinality inheritance in one of the computables.
