### ISSUE TITLE
Edgedb hogs port 8888

### ISSUE THREAD

**Issue by kevinsullivan** [edgedb/edgedb#1208]
- EdgeDB Version: alpha 2
- OS Version: OSX

Steps to Reproduce:

1. Setup edgedb according to tutorial (which among other things sets listen port to 8888)
2. Use EdgeQL to configure listen port to 5656
3. Check and you will see edgedb is listening there but it also listens on 8888
4. I see no obvious way to turn this off -- maybe have to remove the 8888 record somewhere?
5. In a related vein, I see no documentation on how to start and stop the edgeql server
6. Furthermore, if I kill serve using kill -9, it automatically restarts and claims 8888 again

The problem with this is it conflicts with part of my build process (using Gatsby and bundle_analyzer plugin, which also wants 8888). There are workarounds, but still, it seems to be a rough edge that needs smoothing out.

Schema:

**Comment by 1st1** [comment]
Most likely this is a GraphQL port. You've probably created it if you followed our tutorial.

Please run `select cfg::Port {port, database, protocol};` to see the configured ports in your instance.

To drop all configured ports you can run `configure system reset Port;` which would remove all configured ports. 

Please let us know if this helps.

**Comment by kevinsullivan** [comment]
> Most likely this is a GraphQL port. You've probably created it if you followed our tutorial.
> 
> Please run `select cfg::Port {port, database, protocol};` to see the configured ports in your instance.
> 
> To drop all configured ports you can run `configure system reset Port;` which would remove all configured ports.
> 
> Please let us know if this helps.

Here's the output. Looks like you are right.

```
edgedb> select cfg::Port {port, database, protocol};
{
    Object { port: 8888, database: 'tutorial', protocol: 'graphql+http' },
    Object { port: 8080, database: 'tutorial', protocol: 'graphql+http' }
}
edgedb>
```

Thanks for your prompt reply. I'm looking forward to the evolution of this system.
