### ISSUE TITLE
Add the "current_database()" to our builtins

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#1213]
Postgres has a nice `current_database()` function that returns the name of the database you're connected to. This is a nice utility function to have. The proposal is to map it onto `sys::get_current_database()`.

The main reason I ran into this was that I was working on a fix to handle "cannot drop the currently open database" error and realized that the easiest way to write a test for this would be to actually ask the name of the test database first and then attempt to delete it, rather then set up a whole different test where I control the test database name.

**Comment by 1st1** [comment]
We also need current user. I see to options:

* add a `sys::get_session_info() -> tuple<user: str, database: str>` function. We can add more fields to the return tuple in future releases.

* have individual functions for every functionality bit -- `sys::get_current_database()`, `sys::get_current_user()`, etc.

The latter option seems like a simpler one to implement and manage, so I like it better.

**Comment by elprans** [comment]
+1 for the separate functions

**Comment by vpetrovykh** [comment]
Should it be `sys::get_current_user()` or `sys::get_current_role()`?

**Comment by 1st1** [comment]
Role, but you can't map that function to anything though (we can't use postgres for that). I'll add the current role myself.

**Comment by elprans** [comment]
> but you can't map that function to anything though (we can't use postgres for that)

Why not?  We have a 1:1 mapping between EdgeDB roles and Postgres roles.

**Comment by vpetrovykh** [comment]
> Role, but you can't map that function to anything though (we can't use postgres for that). I'll add the current role myself.

Yeah, I'm confused as to what the problem with having a function with SQL body `SELECT current_user;` is?

**Comment by elprans** [comment]
> I'm confused as to what the problem

It wouldn't work currently, because we always connect to postgres as "edgedb" currently.  We need to fix this by switching the authorization context when EdgeDB picks a backend connection.  Is `current_user` blocking something?  If not, I'd postpone this.

**Comment by elprans** [comment]
Closing this, since the subject is done, and `current_user` depends on a functional role system, which we don't have yet.
