### ISSUE TITLE
Add PROVISIONAL keyword

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#122]
Add a keyword to enable unstable features (such as functions that aim to be in the standard library, but aren't there yet, are unstable, etc.).

```
WITH PROVISIONAL foo_count
...
```

**Comment by 1st1** [comment]
I don't think we need this; marking a builtin or a syntax feature as "provisional" in the docs is usually good enough.

Having a keyword like this implies that I'm supposed to go over my queries and remove it from them in some EdgeDB releases, adding a lot of overhead. Marking things "provisional" shouldn't imply that we can break or change them. It should be used to allow us to do that only in extreme cases. I don't expect that to happen a lot, and neither do I expect us to mark many things as provisional.  Using this keyword to enable new syntaxes is always questionable: those who want experimental syntaxes can always run EdgeDB nightly.

Closing as "not going to fix".
