### ISSUE TITLE
Protocol inconsistency in handling tuples

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#1220]
# Issue

Tuple codec for output from edgedb is basically this (sans error handling):
```
        elem_count = <Py_ssize_t><uint32_t>hton.unpack_int32(frb_read(buf, 4))
        for i in range(elem_count):
            frb_read(buf, 4)  # reserved
            elem_len = hton.unpack_int32(frb_read(buf, 4))
            elem_codec = <BaseCodec>self.fields_codecs[i]
            elem = elem_codec.decode(frb_slice_from(&elem_buf, buf, elem_len))
```
And tuple codec for input to edgedb is:
```
        elem_data = WriteBuffer.new()
        for i in range(objlen):
            sub_codec = <BaseCodec>(self.fields_codecs[i])
            sub_codec.encode(elem_data, item)

        buf.write_int32(4 + elem_data.len())  # buffer length
        buf.write_int32(<int32_t><uint32_t>objlen)
        buf.write_buffer(elem_data)
```

I.e. it has **omitted reserved bytes**.

While descriptors look equivalent:
```
InputDescr [
    BaseScalar(
        BaseScalarTypeDescriptor {
            id: 00000000-0000-0000-0000-000000000101,
        },
    ),
    Tuple(
        TupleTypeDescriptor {
            id: 19b56b7d-56b4-0004-38f0-fef54e18d8e2,
            element_types: [
                TypePos(
                    0,
                ),
            ],
        },
    ),
]
Output Descr [
    BaseScalar(
        BaseScalarTypeDescriptor {
            id: 00000000-0000-0000-0000-000000000101,
        },
    ),
    Tuple(
        TupleTypeDescriptor {
            id: 19b56b7d-56b4-0004-38f0-fef54e18d8e2,
            element_types: [
                TypePos(
                    0,
                ),
            ],
        },
    ),
]
```

**Update:** same issue with `NamedTuple`

# Possible Fixes

1. Document current behavior
2. Drop old tuple type descriptor and bump major protocol version

Since this is a server-sent descriptor I don't see a way to deprecate this without major protocol upgrade. The protocol negotiation could be used to revert gracefully though.

**Comment by elprans** [comment]
Hm, yes, this seems like a problematic oversight.  Fixing the input tuple format is the correct fix.  Although we don't support nested tuple inputs, and the top argument tuple is decoded by edgedb-server and not Postgres, this might change in the future.

**Comment by tailhook** [comment]
So I propose tag this thing with some specific flag and fix as soon as we get a major protocol bump anyways or if we accumulate more issues that justify major protocol bump.

**Comment by 1st1** [comment]
Good catch. We should bump the protocol version now and start sending the reserved bytes.

**Comment by elprans** [comment]
Yes, let's do it now and move support for `JSON_ELEMENTS` to this version as well.

**Comment by 1st1** [comment]
To clarify, the server should support both versions. Also please bump edgedb-python to 0.8.x

**Comment by elprans** [comment]
> major protocol bump.

To clarify, bumping protocol version to `0.8` is sufficient, i.e. we're not bumping to `1.x` until EdgeDB 1.0.

**Comment by tailhook** [comment]
Unless I'm missing something, there isn't anything decoded by edgedb. Here is what is sent to postgres:
```
b'\x00\x01\x00\x01\x00\x02\x00\x00\x00\x05test1\x00\x00\x00\x05test2\x00\x01\x00\x01'
```

It doesn't look like there are any reserved bytes, just the number of arguments is 16bit. Do we still want to fix this?

**Comment by elprans** [comment]
What you are seeing is the [`Bind` message](https://www.postgresql.org/docs/current/protocol-message-formats.html).  It's still worth fixing the format symmetry in EdgeDB protocol, because we may later add support for nested tuples in args, and those *do* need a reserved word there.
