### ISSUE TITLE
Graphql - Declaring enumarations with string values containg - throws in graphql

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb#1226]
- EdgeDB Version: alpha 2
- OS Version: Ubuntu 18

Steps to Reproduce:

1. Create the following module
```
create migration test to {
  module bug1{
    scalar type position extending enum<'front-end', 'back-end', 'devops', 'full-stack'>;
  }
};
```
2. Expose the database as a graphql API

Error is seen in graphiql explore
![image](https://user-images.githubusercontent.com/8558836/74652470-629ac880-5186-11ea-9191-4a22f8b87a6d.png)

```
AssertionError: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"front-end\" does not.
```

**Comment by haikyuu** [comment]
Note that changing `-` to `_` works fine

**Comment by elprans** [comment]
This doesn't seem like a bug, rather a mismatch in EdgeQL and GraphQL spec.  The latter expects enum elements to be valid GraphQL identifiers, whereas in EdgeQL they're arbitrary string literals.  Documenting this fact is necessary, though.

**Comment by haikyuu** [comment]
Good to know. Thanks @elprans

**Comment by haikyuu** [comment]
One more issue is that even though the enum is defined in Graphql

![image](https://user-images.githubusercontent.com/8558836/74673960-9854a700-51b0-11ea-9592-07996092cea1.png)

The property is not found in the types that have it!
