### ISSUE TITLE
GraphQL - enums cannot be used in InsertTYPE mutations

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb#1233]
- EdgeDB Version: alpha2
- OS Version: Ubuntu
Even though the enum is defined in Graphql

![image](https://user-images.githubusercontent.com/8558836/74673960-9854a700-51b0-11ea-9592-07996092cea1.png)

The property is not found in the types that have it. Meaning `InsertPrice` mutation in graphql doesn't accept currency property.
```
type Price{
  property currency -> Currency {
   default := <Currency>'USD';
  };
}
```

**Comment by vpetrovykh** [comment]
I think #1237 fixes this issue as well. At least I can use `currency` in mutations tests. As far as I can tell the same bug that was causing problems with `required` enum property was also responsible for the missing field in insert mutation.
