### ISSUE TITLE
EdgeDB interactive tutorial

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#1240]
Having a guided interactive tutorial would make it easier to showcase the various features of EdgeDB without overwhelming the user. Importantly it would allow to present the material gradually from simple queries, to inserts, updates, deletes, and then schema mutation.

This would require a copy of pre-populated running EdgeDB that the users could interact with. That way we don't need to rely on users first creating a schema and data to work with.

A more elaborate sample schema could be used, since it's pre-populated. This would allow showcasing more EdgeDB features, like type polymorphic queries, link properties and backward link traversal. The suggestion is that the schema should represent some social media system. This is something fairly familiar to most users and presents opportunities for complex concepts as well.

**Comment by ambv** [comment]
For the social network schema, the main EdgeDB concept we'd like to show is polymorphic links and queries. As I see it, the main thing to show is:
- Users can follow each other;
- Users can follow hashtags;
- there is a base Media object that has an author and possible hashtags;
- there are concrete objects that inherit from Media like Text, Photo, Video.

I would leave privacy alone: everything in this minifeed is public. We can introduce some fun things later when there's granual access control.

For now, there's already plenty of fun queries to make:
- show me all media by a given user ordered by date;
- show me all photos with a given hashtag;
- show me a feed that a given user will see (so all media of users and hashtags the given user follows).

**Comment by vpetrovykh** [comment]
So I'm thinking of using this schema:
```
type User {
    required property name -> str;
    required property email -> str {
        constraint exclusive;
    }
    multi link follows -> User;
}

abstract type Media {
    required link author -> User;
    multi property hashtags -> str;
    property post_date -> datetime;
}

type Text extending Media {
    property title -> str;
    required property body -> str;
}

abstract type UploadedMedia extending Media {
    required property uri -> str;
}

type Photo extending UploadedMedia;
type Video extending UploadedMedia;
```

The tutorial would start with simple queries and build up to more elaborate stuff. With scructure roughly as follows:
- Learn properties, links and paths
  * SELECT a user based on email property
    `SELECT User FILTER .email = 'some@email.com'`
  * SELECT some photos of a specific user
    `SELECT Photo FILTER .author.email = 'some@email.com'`
  * SELECT users based on backwards 'follows' path (i.e. all followers)
    ```
    WITH U := (SELECT User FILTER .email = 'some@email.com')
    SELECT U.<follows[IS User]
    ```
- Learn about shapes
  * get everyone I follow
    ```
    WITH Me := (SELECT User FILTER .email = 'my@email.com')
    SELECT Me.follow {
        name,
        email
    }
    ```
  * get all photos with hashtag
    ```
    SELECT Photo {
        author: {
            name,
            email,
        },
        uri,
        hashtags,
    }
    FILTER .hashtags IN {'kittens', 'puppies'}
    ```
  * get all media from a user (polymorphic)
    ```
    SELECT Media {
        hashtags,
        type := __type__.name,
        [IS Text].title,
        [IS Text].body,
        [IS UploadedMedia].uri,
    }
    FILTER .author.email = 'some@email.com'
    ```
  * feed of a user (all media they follow)
    ```
    SELECT Media {
        hashtags,
        type := .__type__.name,
        [IS Text].title,
        [IS Text].body,
        [IS UploadedMedia].uri,
    }
    FILTER .author.<follow[IS User].email = 'my@email.com'
    ORDER BY .post_date DESC
    LIMIT 10
    ```
  * User page with last post + feed (put everything learnt so far together in one query)
    ```
    SELECT User {
        name,
        email,
        last_post := (
            SELECT .<author[IS Media] {
                hashtags,
                type := .__type__.name,
                [IS Text].title,
                [IS Text].body,
                [IS UploadedMedia].uri,
            }
            ORDER BY .post_date DESC
            LIMIT 1
        ),
        feed := (
            SELECT .follows.<author[IS Media] {
                author: {
                    name,
                    email,
                },
                hashtags,
                type := .__type__.name,
                [IS Text].title,
                [IS Text].body,
                [IS UploadedMedia].uri,
            }
            ORDER BY .post_date DESC
            LIMIT 10
        ),
    }
    FILTER .email = 'my@email.com'
    ```
- Learn about insert/update
  * add a Text post by a user
    ```
    INSERT Text {
        title := 'Learning EdgeDB',
        body := "I'm in the middle of the tutorial.",
        author := (SELECT User FILTER .email = 'my@email.com')
    }
    ```
  * edit content of a text post
    ```
    UPDATE Text
    FILTER
        .author.email = 'my@email.com'
        AND
        .title := 'Learning EdgeDB'
    SET {
        body := .body ++ " Doing great so far!",
    }
    ```
  * add some hashtags to a text post
    ```
    UPDATE Text
    FILTER
        .author.email = 'my@email.com'
        AND
        .title ILIKE '%edgedb%'
    SET {
        hashtags := .hashtags UNION 'edgedb',
    }
    ```
  * Going to need a brief list of available operators, so that people can experiment with UPDATE.
- Migrations:
  * start with User and Text
  * add "follows"
  * add abstract "Media", "UploadedMedia", "Photo", and "Video"
  * add "hashtags"
- More advanced stuff:
  * add indexes for Text title, User name and Media post_date
  * add a computable multi link "followers" to User to avoid confusion with the backward links

**Comment by vpetrovykh** [comment]
Try the bare-bones interactive tutorial version: https://github.com/vpetrovykh/edgedb-guide

**Comment by haikyuu** [comment]
@vpetrovykh the link isn't working

**Comment by 1st1** [comment]
This is pretty much done with some polishing steps still required. Closing this one, we'll open new issues as necessary.
