### ISSUE TITLE
A table disappears after being created

### ISSUE THREAD

**Issue by Mulugruntz** [edgedb/edgedb#1246]
- EdgeDB Version: alpha-2
- OS Version: the edgedb/edgedb docker

Hi!

I created this repo to make it easy to reproduce the problem: https://github.com/Mulugruntz/edgedb-playground/tree/b241ebd66e5b873ba3c446c96d9d057b08130698

Everything is explained there in the README.

But basically, a table creation that was committed seems to have disappeared after another table creation.

I tried to follow all the examples and documentation on the website. And I'm not sure whether it's a bug on EdgeDB side (I doubt it) or a documentation issue that could be improved (maybe) or something else.

I can also reply to messages on irc (I'm on #python and #python-fr, I'll reply if you send a message to my nic: Mulugruntz).

Thanks for your great work!

PS: I've also sent a question [there](https://spectrum.chat/edgedb/general/a-table-disappears-after-being-created~c58d5d5c-7c6a-4896-adc7-51cc025cffb4) but as I'm not sure whether it's a bug or me not understanding how to use the api, I'm posting it here as well.

**Comment by elprans** [comment]
This is working as intended.  You are using a `MIGRATION` to amend the schema, and the migration block must include the **entire** schema, not just the new additions.  For incremental, programmatic schema modifications you want to use the imperative DDL syntax instead. So:

```
conn.execute("""
CREATE TYPE B { ... };
""")
```

instead of 

```
conn.execute("""
CREATE MIGRATION m TO {  
module default {
  type B
}};
""")
```

**Comment by elprans** [comment]
@vpetrovykh we need to ensure that the semantics of `CREATE MIGRATION` is clear from the docs.

**Comment by Mulugruntz** [comment]
Ohhhhh 😱 
Now I see! Yeah, the documentation is not clear... yet 😉.
That's confusing as (I just did a quick check after reading your explanation), the `migration` term is used by many systems (Django, Laravel, Rails, MS Entity Framework, FlywayDB, ...) to describe the changes to apply to migrate to a new schema... and not the target schema itself.
Anyway, that's still a very cool objective!!

But yeah, reusing semantics for different things may make it harder to "migrate" db skills 😜 

Thanks!

**Comment by elprans** [comment]
>  and not the target schema itself.

In Django etc. the target schema is implicitly read from your models.  In EdgeDB you have to let the database know the desired state of the target schema somehow, but the end result -- the `migration` object is exactly like the one in an ORM framework -- a script to migrate to a certain schema state.

We are working on adding the necessary tooling to enable the familiar migration workflows, please see [RFC 1000](https://github.com/edgedb/rfcs/blob/master/text/1000-migrations.rst) for some details.

**Comment by Mulugruntz** [comment]
Thanks! I stumbled upon RFD 1000 this afternoon when I was trying to understand what was happening.

And you're right... the keywords are "create migration", implying that the command creates a migration and is not a migration itself. Makes sense (now that I have been given the solution ^^).
