### ISSUE TITLE
Bad type names in errors (raw object representation)

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#1258]
- EdgeDB Version: `1.0-alpha.3+dev.69.g4f0eef61.d20200222`

Initially I wanted to comment on #1134, but I found a few more bad errors and decided to create a separate issue that can be used for tracking bad error messages.

Steps to reproduce:
|                   operation                  | good |                                query                               |
|:--------------------------------------------:|:----:|:------------------------------------------------------------------:|
| create constraint - missing type             |   ✅  | ALTER TYPE b ALTER PROPERTY b CREATE CONSTRAINT std::regexp(r'b'); |
| create constraint - missing property         |   ⬜️  | ALTER TYPE a ALTER PROPERTY b CREATE CONSTRAINT std::regexp(r'b'); |
| drop constraint - missing type               |   ⬜️  | ALTER TYPE b ALTER PROPERTY b DROP CONSTRAINT a;                   |
| drop constraint - missing property           |   ⬜️  | ALTER TYPE a ALTER PROPERTY b DROP CONSTRAINT a;                   |
| drop constraint - missing constraint         |   ⬜️  | ALTER TYPE a ALTER PROPERTY a DROP CONSTRAINT a;                   |
| alter type annotation - missing type         |   ✅  | ALTER TYPE b ALTER ANNOTATION title := 'a';                        |
| alter type annotation - missing annotation   |   ⬜️  | ALTER TYPE a ALTER ANNOTATION title := 'a';                        |
| alter property annotation - missing type     |   ✅  | ALTER TYPE b ALTER PROPERTY b ALTER ANNOTATION title := 'a';       |
| alter property annotation - missing property |   ⬜️  | ALTER TYPE a ALTER PROPERTY b ALTER ANNOTATION title := 'a';       |
| drop type - missing type                     |   ✅  | DROP TYPE b;                                                       |
| drop property - missing type                 |   ⬜️  | ALTER TYPE b DROP PROPERTY b;                                      |
| drop property - missing property             |   ⬜️  | ALTER TYPE a DROP PROPERTY b;                                      |

Queries that are not "good" produce results like `InvalidReferenceError: schema item 'default::default|a@@default|__|b@@default|b@da39a3ee5e6b4b0d3255bfef95601890afd80709' does not exist`.

Schema:
```
CREATE TYPE a { 
   CREATE PROPERTY a -> str { 
     CREATE CONSTRAINT std::regexp(r'a'); 
   }; 
};
```

**Comment by elprans** [comment]
This is a good one.  Thanks @Fogapod!  This should be a relatively easy enhancement, so feel free to tackle it if you wish.

**Comment by Mulugruntz** [comment]
I would be interested in implementing this one, as it's been labelled `easy`, should be a good starting point :-).

Do we know what kind of clean messages we'd like to have?

**Comment by elprans** [comment]
The majority of these errors are generated by this piece of code:

https://github.com/edgedb/edgedb/blob/32c9445ae1c511ec09a88682e422e38295ae28d0/edb/schema/delta.py#L1343-L1361

For most errors we use the `Object.get_verbosename()` method that formats the name of the object nicely.  The complication here is that `get_verbosename()` is an instancemethod, and we don't have an instance in `Command.get_object()` yet.  Ideally, we need a classmethod version of `get_verbosename()` (and `get_displayname()`).

Here's what I suggest:

1. Remake all current implementations of `get_displayname()` and `get_verbosename()` into classmethods accepting full object name.  The names would have to be different, .e.g `get_displayname_from_name`

2. For compatibility with existing code, and convenience in general, implement a wrapper `Object.get_displayname()` and `Object.get_verbosename()` that would call the new classmethod implementations.

3. Finally, teach `Schema.get()` to call `get_verbosename_from_name()` when formatting the error message.

**Comment by Mulugruntz** [comment]
Thanks @elprans for your reply.

I'm trying to dig in the code to make sense of the info you just gave me.

It seems that sometimes the expected **type** in the error message is not the correct one. For example, 

drop property - missing type  `ALTER TYPE b DROP PROPERTY b;`

leads to a `property 'default::__|b@@default|b' does not exist` message. Where @Fogapod was expecting a `type 'default::b' does not exist`,  it actually fails at `property 'b' of type 'default::b' does not exist`.

Not sure if what I'm trying to say is clear, but it seems to check the existence of a property within a given type before checking the existence of that type?

**Comment by elprans** [comment]
> It seems that sometimes the expected type in the error message is not the correct one.

Ah, that's an unrelated bug, I'll look into fixing that.

> what we want to achieve for the "ideal" error messages.

We want to use the output of `get_verbosename()`, which looks like:

`constraint 'c' of property 'b' of type 'default::a'`

**Comment by Mulugruntz** [comment]
Sorry for not replying these past few days. Personal issues here in Tokyo (stolen wallet) made it difficult for me to find time recently. Tons of phone calls and police-related stuff.

I'm not giving up on this :-) but it'll take longer than initially expected. :(

**Comment by elprans** [comment]
> stolen wallet

Bummer :-(

> but it'll take longer than initially expected

No problem!  This isn't blocking anything.

**Comment by 1st1** [comment]
@vpetrovykh this is relatively low priority. Please pick it up later this week.

**Comment by elprans** [comment]
From the list of things to do in my [comment](https://github.com/edgedb/edgedb/issues/1258#issuecomment-618052607) above I already implemented the first two, so the only things left to do is fix `Schema.get()` and write some tests.
