### ISSUE TITLE
Limit injection in REPL broke my query

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#1271]
This problem arises for me in the current master branch a81f852cf87ad4054d7e924063540fdc361fd242

I have the following query in my tutorial:
```
SELECT User {
    name,
    email,
    last_post := (
        SELECT .<author[IS Media] {
            hashtags,
            type := .__type__.name,
            [IS Text].title,
            [IS Text].body,
            [IS UploadedMedia].uri,
        }
        ORDER BY .post_date DESC
        LIMIT 1
    ),
    feed := (
        SELECT .follows.<author[IS Media] {
            author: {
                name,
                email,
            },
            hashtags,
            type := .__type__.name,
            [IS Text].title,
            [IS Text].body,
            [IS UploadedMedia].uri,
        }
        ORDER BY .post_date DESC
        LIMIT 5
    ),
}
FILTER .email = 'alice@tutorial.com'
```

Which actually already has small limits and does produce the expected result via the python API. The problem arises in REPL, where the query produces many more nested results for "last_post" and "feed". If I disable limit injection by using `\limit 0` then things go back to correct expected output.

This is broken w.r.t. limit injection in python REPL. Having said that, does rust REPL even try to do limit injection at this point?

In rust REPL I think the polymorphic part of the query is the one that breaks things (i.e. if I remove all the `[IS Text].title` etc. from the shape, it works fine, but breaks with those).

Steps to reproduce: 
0) Run the tutorial server so that it creates a database
1) Connect to the tutorial database with REPL (the database name is "queries")
2) Run the above query

Sorry I don't have a tiny test case for it yet.

Could @elprans and @tailhook take a look at this?

**Comment by elprans** [comment]
Limit injection is done at the compiler level (via a protocol hint), it's not really a REPL thing.

**Comment by elprans** [comment]
Here's where it happens (roughly): https://github.com/edgedb/edgedb/blob/a81f852cf87ad4054d7e924063540fdc361fd242/edb/edgeql/compiler/stmt.py#L69-L74

**Comment by vpetrovykh** [comment]
So the only thing the REPL does is supply that hint, right? Is that why I see a different result in python vs. rust REPL?

I'll try looking for a smaller query that breaks things in rust REPL and open a separate bug for that then.
