### ISSUE TITLE
Querying type with a query variable not working while it works with a string

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb#1297]
- EdgeDB Version: alpha 2

Steps to Reproduce:

1. Create an enum
2. Try the following query
```graphql
query($enum:String!){
  __type(name:$enum){
    enumValues{
      name
    }
  }
}
# variable
{ "enum": "Position" }
```
![image](https://user-images.githubusercontent.com/8558836/77440909-1e37c380-6de9-11ea-88c1-50f927582620.png)

But this one works fine:
```graphql
query{
  __type(name:"Position"){
    enumValues {
      name
    }
  }
}
```

Here is a similar query that works for reference https://serve.onegraph.com/short/FHRKVT

**Comment by 1st1** [comment]
@tailhook @vpetrovykh

**Comment by tailhook** [comment]
This is fixed in #1294 . We can probably wait for that to land, instead of patching this issue twice.

**Comment by tailhook** [comment]
@haikyuu, this should already work on master/nighly.

**Comment by haikyuu** [comment]
Thanks @tailhook
