### ISSUE TITLE
Native Windows Version

### ISSUE THREAD

**Issue by sirinath** [edgedb/edgedb#1306]
Can you add a Windows installer also to try on MS Windows?

**Comment by elprans** [comment]
We recommend using Docker or WSL to run EdgeDB on Windows for now.  Native Windows support is not currently a priority.

**Comment by 1st1** [comment]
We need to make sure our "Download" page suggests people how to work with edgedb on Windows. Will keep this open until we update it.

**Comment by 1st1** [comment]
Note to myself: this will be part of the new website design.

**Comment by PastelStoic** [comment]
Just a reminder that this issue is solved and can be closed.
