### ISSUE TITLE
HTTP server not accepting options

### ISSUE THREAD

**Issue by gsouf** [edgedb/edgedb#1313]
- EdgeDB Version: `EdgeDB server (1.0-alpha.2+g16f75ece5.d20200122)`
- OS Version: Official docker image running on ubuntu 19.10

Steps to Reproduce:

1. enable http API (graphql or edgeql, issue is the same) on port 8888
2.  Run the following javascript in chrome:

```
    const xhr = new XMLHttpRequest();
    xhr.open('POST', 'http://127.0.0.1:8888');
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.onreadystatechange = (r) => {};
    xhr.send('{}');
````

Server returns http 400 - `expected a GET or a POST request`.

Because of CORS the browser sends an OPTION request that is rejected by edgedb http server.

I'm going to workaround for the moment, but ultimately the http server should accept OPTION requests 

Thanks

**Comment by elprans** [comment]
Yes, this is a known issue: #1230.  Will fix in the next release.
