### ISSUE TITLE
Cannot issue new command

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb#1314]
- EdgeDB Version: `EdgeDB 1.0-alpha.3+dev.102.g176dac70`
- OS Version: Ubuntu

Steps to Reproduce:

1. Expose an HTTP Port 
2. Send 2-3 requests at the same time

```
{
  message: 'cannot issue new command',
  type: 'InternalServerError',
   code: 16777216
 }
```

**Comment by elprans** [comment]
Does this happen on a particular query for you or regardless of a query?

**Comment by 1st1** [comment]
> Send 2-3 requests at the same time

What's your `concurrency` setting?

**Comment by haikyuu** [comment]
Concurrency is set to 4

**Comment by haikyuu** [comment]
But 4 doesn't mean 4 requests at the same time max. Does it?

**Comment by haikyuu** [comment]
> Does this happen on a particular query for you or regardless of a query?

I did a `reset Port` and created a new Port and i was able to send queries just fine.

It seems some errors mess up with Ports.

**Comment by haikyuu** [comment]
When that happens, all queries return that same error. Even if i send one query.

**Comment by 1st1** [comment]
> But 4 doesn't mean 4 requests at the same time max. Does it?

It means that only 4 previously unseen queries can be compiled in parallel. But in any case, the server shouldn't error with what you see, so this is most definitely a bug. I'll investigate.

**Comment by haikyuu** [comment]
@1st1 I think i've found a reproduction scenario.

- Create HTTP Port.
- Make requests
- Alter schema
- `cannot issue new command`

**Comment by ambv** [comment]
I can reproduce this. After altering schema, the subsequent (compiled) query works once more, then fails with ISE `"unexpected message type '3'"` and subsequent requests fail with ISE `"cannot issue new command"`.
