### ISSUE TITLE
Prohibit pointer name shadowing in shapes

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#1321]
Currently, EdgeDB would silently accept queries like:

```
SELECT Foo { bar, bar }
```

Confusingly, even though the output contains two properties, internally the latter definition "wins", shadowing the first one:

```
db> SELECT Foo { bar, bar := 'spam' }
{Object { name: 'spam', name: 'spam' }}
```

This behavior is even more confusing in the polymorphic shapes.

We *could* fix this by adding internal disambiguation, but then the ambiguity will simply shift to the output, where one would have two identically named fields.  IMO, it would be best to simply disallow such queries.

**Comment by elprans** [comment]
Also, see the original report by @hsteindev on [Spectrum](https://spectrum.chat/edgedb/general/some-potential-issues-i-came-across-when-doing-my-first-experiments-with-edgedb~49e55a68-7013-4908-a14f-21c37e50e5a2).

**Comment by nsidnev** [comment]
I would try to take this. I changed the sources a bit, and now it's handled like this:

![image](https://user-images.githubusercontent.com/22559461/80282941-f8217e00-871c-11ea-90f4-b08ccf9d5f16.png)

If this is OK, then I can write some tests and open PR, right?

**Comment by elprans** [comment]
Hi @nsidnev, yes please add some tests and open a PR. Thanks!
