### ISSUE TITLE
ISE: there is no range var for (__derived__::expr~1) source in <pg.SelectStmt at ...>

### ISSUE THREAD

**Issue by ambv** [edgedb/edgedb#1335]
- EdgeDB Version: nightly in edbcloud
- OS Version: edbcloud

Getting the ISE like in the title while creating the following function (SDL syntax):

```
    function is_public(p: Publishable) -> bool
    using EdgeQL $$
        SELECT
          (NOT p.deleted)
          AND (
              p.public_since < datetime_current()
              IF p.public_since ?!= <datetime>{}
              ELSE false
          )
          AND (
              p.public_until > datetime_current()
              IF p.public_until ?!= <datetime>{}
              ELSE true
          )
        ;
    $$;

    abstract type Publishable {
        property public_since -> datetime;
        property public_until -> datetime;
        property deleted -> bool;
    }
```

What I'm trying to accomplish here is to make `is_public` return `true` if:
- the Publishable is not deleted; and
- it has a non-empty `public_since` which is in the past; and
- either it doesn't have a `public_until`; or
- it has a non-empty `public_until` in the future.

**Comment by 1st1** [comment]
@elprans Can we fix this for alpha 3? If not please move to alpha 4.

**Comment by elprans** [comment]
This feels like a simple bug, but quite visible also, will try to tackle it for a3.
