### ISSUE TITLE
InternalServerError: cannot drop schema

### ISSUE THREAD

**Issue by Slyfoxy** [edgedb/edgedb#1369]
- EdgeDB Version: EdgeDB 1.0-alpha.2+g16f75ece5.d20200122
- OS Version: Windos 10 Educational, Version: 1909, Build: 18363.778

Steps to Reproduce:

```
START TRANSACTION;
CREATE MIGRATION m1 TO {
    module test1 {
        type TestType;
    }

};
COMMIT MIGRATION m1;
COMMIT;

START TRANSACTION;
CREATE MIGRATION m2 TO {
    module test2 {
        scalar type test_scalar_type extending str;
    }
};
COMMIT MIGRATION m2;
COMMIT;
```

Error log:
```
InternalServerError: cannot drop schema edgedb_cd88351f-87ec-11ea-8acc-e913c9a88c7c because other objects depend on it
```

**Comment by nsidnev** [comment]
We also tested this on `1.0-alpha.3+dev.163.gad37ad85.d20200426`. Deleting schema using `DROP <schema> CASCADE` directly in PostgreSQL helped here.
