### ISSUE TITLE
Incorrect result for a value computed in WITH block

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#1381]
Run the following in the existing scope tests dataset (from `test_edgeql_scope.py`):
```
WITH 
    MODULE test,
    avg := math::mean({len(Card.name)})
SELECT Card {name, a := avg};
```
Instead of being the same value across all results `a` is different for each as if the function call was inlined.

**Comment by vpetrovykh** [comment]
I can even simplify it further to:
```
WITH 
    MODULE test,
    avg := count({Card.name})
SELECT Card {name, a := avg};
```
Or even
```
WITH 
    MODULE test,
    avg := Card.name
SELECT Card {name, a := avg};
```

**Comment by 1st1** [comment]
@elprans can we fix this for alpha 3?

**Comment by 1st1** [comment]
(if not move it to Alpha 4)

**Comment by elprans** [comment]
The fix isn't trivial, so Alpha 4.

**Comment by msullivan** [comment]
Also: `WITH X := {1, 2}, Y := X+1 SELECT (X, Y)`.
Should produce a cross-product output with 4 results, actually produces 2.
