### ISSUE TITLE
Feature Request: Add introspection property to indicate system databases

### ISSUE THREAD

**Issue by jaclarke** [edgedb/edgedb#1387]
Can an introspection property be added to `sys::Database`, indicating if the database is user created or a system database?  
This would be useful for filtering out databases like 'edgedb0' in UI's and the repl `\l` command, which give a `InternalServerError: database "edgedb0" is not currently accepting connections` error when connecting to them.

**Comment by elprans** [comment]
This is done.  All system-defined objects now have a "builtin" property.
