### ISSUE TITLE
New eschema syntax for constraints subjectexpr

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#14]
Not until long ago it was possible to specify `subjectexpr`s for parameterless constraints simply by re-using args syntax:

```    
link translated_label to str:
    constraint unique := (subject@source, subject@lang)
```

To do the same thing now, we need to be explicit:

```    
link translated_label to str:
    constraint unique:
        subject := (subject@source, subject@lang)
```

An idea to simplify this:

```
link translated_label to str:
    constraint unique on (subject@source, subject@lang)
```

But this would require to complicate the lexer or the grammar. Maybe we can come up with a better sugar syntax for this?

**Comment by 1st1** [comment]
This has been implemented, right @elprans?

**Comment by elprans** [comment]
Yes.
