### ISSUE TITLE
Consider renaming `to_str(array)` and `to_array(str)` to `str_split` and `array_join` respectively.

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#1401]
`to_str(array, delimiter)` and `to_array(str, delimiter)` are, at a glance, consistent with other conversion/constructor functions, but `to_array(str, delimiter)` is an odd and undisoverable way of naming a string-splitting function, and `str_split()` would be a better name.  On the other hand, `to_str(array, delimiter)` has a better claim at being similar to other "formatting" functions, but is also distinct in that it converts a collection type into a scalar type, so naming it `array_join` would not be too bad.

**Comment by haikyuu** [comment]
Also, People coming with a Python or JavaScript experience would expect `join` and `split`.

**Comment by 1st1** [comment]
Victor, please work on this tomorrow.

**Comment by shankarj67** [comment]
Can I work on this issue?

**Comment by 1st1** [comment]
> Can I work on this issue?

Sure, go ahead!

**Comment by 1st1** [comment]
@vpetrovykh Please handle this today.

**Comment by shankarj67** [comment]
Hi,

Can you share some pointer on where to look for these functions: to_str(array) and to_array(str, delimiter)

**Comment by 1st1** [comment]
https://github.com/edgedb/edgedb/tree/master/edb/lib

Basically you need to update signatures there and then fix all tests & docs. If this isn't done today somebody will pick this up tomorrow as we have a release on Wednesday.

**Comment by shankarj67** [comment]
Sure, I will do it today.
