### ISSUE TITLE
Duck typing `UNION` results

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#145]
Union types make `UNION` difficult to use because all the links and properties disappear in a heterogeneous object union. This is even worse for a `UNION` between an ObjectType and a View on that same type.

```
# this results in an error as property "name" cannot be found
db> SELECT {LayUser, AdminUser}.name;
```
```
# this works, but has an unintuitive result, because 'foo' is completely lost
db> SELECT {User{name := 'foo'}, User}.name;
[['Elvis', 'Yury', 'Elvis', 'Yury']]
```

The result of a heterogeneous object `UNION` should be a *duck type* with the following qualities:
- all links and properties that are actually the same (e.g. extending from the same `ObjectType`) are reflected in the *duck type*
- all link and properties that have the same name (but are not the same from the inheritance stand point) are also reflected in the *duck type* as long as their types are compatible

A `UNION` between a View and a pure Type also generates a *duck type* where:
- if a link or property appears as a computable in the View, it is **omitted** from the *duck type*
- otherwise all links and properties of the Type are reflected

A `UNION` of scalars is only legal if they are of compatible types and the resulting type is whatever is that compatibility type.

These rules also come into play when merging links or properties through inheritance.

With this schema:
```
type A:
    property foo -> int
    property bar := 3

type B:
    property foo -> float
    property bar -> float

type C extending A, B
```
Consider these queries:
```
db> SELECT C.foo.__type__.name;
[['float']]
db> SELECT C.bar.__type__.name;
[['float']]
db> INSERT C;
db> SELECT C{foo, bar};
[[{foo: None, bar: 3}]]
```

This kind of approach allows to minimize the use of `[IS Blah]` when dealing with a heterogeneous object union. At the same time it prevents errors stemming from ambiguity of resolving links of the same name but of different "nature" (different types or computables).

**Comment by 1st1** [comment]
@elprans what should we do about this one?

**Comment by elprans** [comment]
This was partially fixed, so for properties and links that are not defined as computables things work as expected.  Still need to fix the computable case.
