### ISSUE TITLE
Split the package build-and-test workflow job into two jobs: build and test.

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#1454]
Currently, package build and built package tests are done as steps of the same job.  Unfortunately, it seems like Github Actions have an (undocumented) job run time limit on macOS of 60 minutes (the documentation claims that the limit is 6 hours).  It might be a fluke or a temporary bug.  Regardless, separating build and test into separate jobs seems like a cleaner arrangement anyway.

**Comment by ambv** [comment]
So to split Build from Test we'd need to pass the artifacts somehow. Do you have a better idea than just the regular `actions/upload-artifact@v1`?

**Comment by elprans** [comment]
> Do you have a better idea

No, `upload-artifact`/`download-artifact` is the idomatic way to pass stuff between jobs.
