### ISSUE TITLE
Creating type named `str` in default confuses edgedb

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#1457]
- EdgeDB Version: 1.0-a3

Steps to reproduce:
```
db> CREATE TYPE str;
OK: CREATE
db> SELECT "x";
ERROR: InternalServerError: insufficient data left in message
```
Compiled query assumes it's uuid for some reason:
```
                                                                                                                     
        (SELECT/*<pg.SelectStmt at 0x7fe5da5545e0>*/
                    ($1)::uuid AS "expr~1_identity~1"     
            ) AS "expr-1~2"                                                                
            INNER JOIN "edgedb_8e7140a2-a409-11ea-8bbb-dbade5f70ff0"."e779608c-a409-11ea-9ca9-e5640d314547" AS "str~1"
                ON ("expr-1~2"."expr~1_identity~1" = "str~1".id)
```
Explicit variables crash like this:
```
db> SELECT <str>$0;
ERROR: InternalServerError: cannot describe type default::str
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/work/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
        File "/work/edb/server/compiler/compiler.py", line 1480, in compile_eql_tokens
          return self._compile(ctx=ctx, tokens=eql_tokens)
        File "/work/edb/server/compiler/compiler.py", line 1141, in _compile
          comp: dbstate.BaseQuery = self._compile_dispatch_ql(ctx, stmt)
        File "/work/edb/server/compiler/compiler.py", line 1104, in _compile_dispatch_ql
          return self._compile_ql_query(ctx, ql)
        File "/work/edb/server/compiler/compiler.py", line 637, in _compile_ql_query
          in_type_data, in_type_id = sertypes.TypeSerializer.describe(
        File "/work/edb/server/compiler/sertypes.py", line 335, in describe
          type_id = builder._describe_type(
        File "/work/edb/server/compiler/sertypes.py", line 133, in _describe_type
          subtypes = [self._describe_type(st, view_shapes,
        File "/work/edb/server/compiler/sertypes.py", line 133, in <listcomp>
          subtypes = [self._describe_type(st, view_shapes,
        File "/work/edb/server/compiler/sertypes.py", line 328, in _describe_type
          raise errors.InternalServerError(
      edb.errors.InternalServerError: cannot describe type default::str
```
Which is almost fine, but error should be more helpful, using `std` helps:
```
db> SELECT <std::str>$0;
Parameter <str>$0: xxx
{'xxx'}

```

**Comment by tailhook** [comment]
Note to myself: probably should use `std::` for all extracted variables.

**Comment by 1st1** [comment]
> Note to myself: probably should use std:: for all extracted variables.

I've just seen this -- could have saved me 10 minutes debugging :) Yes, we need to prefix with `std::` types of extracted constants.

> Explicit variables crash like this:

That's a separate issue, I think.

**Comment by 1st1** [comment]
todo:

- [ ] Add `__std__` alias
- [ ] Investigate @tailhook's "Explicit variables crash like this:"

**Comment by tailhook** [comment]
> > Explicit variables crash like this:
> 
> That's a separate issue, I think.

Yes. Any object type works this way. Which is still weird, but different issue.

Assigned issue to you, because not sure how to want to do `__std__` alias.

**Comment by vpetrovykh** [comment]
I think it might be related to #1439 - essentially this is our unqualified name resolution acting up if things of the same name exist in the default module. Although for types the correct solution would still be using the fully qualified name as it's 100% unambiguous.

**Comment by 1st1** [comment]
> I think it might be related to #1439 - essentially this is our unqualified name resolution acting up if things of the same name exist in the default module. Although for types the correct solution would still be using the fully qualified name as it's 100% unambiguous.

This issue is unrelated to #1439. Here the problem is that the compiler sometimes inlines references to things `std` implicitly, and those should continue to work even if `std` is shadowed.

**Comment by elprans** [comment]
This is fixed.
