### ISSUE TITLE
JSON functionality

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#146]
In order to be able to work with JSON in EdgeDB, we need the following minimal set of functionality implemented:

- [x] `json_typeof(json) -> str` function that returns the name of the type for a `json` element.
- [x] `json_array_unpack(json) -> SET OF json` function that converts a `json` array into a set of `json` elements. 
- [x] `json_object_unpack(json) -> SET OF tuple<json, json>` function that converts a `json` object into a set of `json` key/value tuples. 
- [x] `json_get(json, VARIADIC str) -> OPTIONAL json` function that allows "safe" navigation on any `json` value. If the navigation is impossible due to missing path or wrong type of `json` (number instead of array, etc.), the funciton returns `<json>{}`.
- [x] `json_to_str(json) -> str` function to produce a string representation of arbitrary JSON
- [x] `str_to_json(str) -> json` function to parse a string representation into JSON
- [x] casting *from* `json` of any scalars types
- [x] element access using `[...]` of `json`
- [x] slicing of `json` using `[...]` 
- [x] casting to `json` of any types (much like `str`); this includes object types and views.

Using the special `json_` functions would allow to handle heterogeneous `json` data in EdgeQL, by first unpacking it and filtering based on type, etc.

Casting a JSON `null` into any scalar type should yield an empty set of that scalar type. 
```
db> SELECT <int><json>'null' ?= <int>{};
[[True]]
```
A JSON `null` is a valid element of a set of `json` type. It is not the same as an empty set of `json`.
```
db> SELECT <json>'null' ?= <json>{};
[[False]]
```
Here's a different way to get an empty set of `json`:
```
db> SELECT (SELECT j := <json>'1' FILTER j = <json>'2') ?= <json>{};
[[True]]
```

Casting a `json` array into an EdgeDB `array` should be the same as creating an array literal from individual elements of the `json` array.
```
db> SELECT <array<int>>str_to_json('[1,2,3]') = 
...    array_agg(<int>json_array_unnest(str_to_json('[1,2,3]')));
[[True]]
```

In particular this means that any `null` elements in the `json` array will need some special treatment because otherwise they will render the result an empty set (see #251).

**Comment by 1st1** [comment]
We should probably change `json_object_unpack` signature to: `json_object_unpack(json) -> SET OF tuple<str, json>`  @elprans your thoughts?

**Comment by 1st1** [comment]
re "casting to json of any types (much like str); this includes object types and views." -- is this done?
