### ISSUE TITLE
Add streamlined "get or create" functionality on nested insert

### ISSUE THREAD

**Issue by cthoyt** [edgedb/edgedb#1467]
This issue comes from a short discussion on Twitter (https://twitter.com/cthoyt/status/1268279890782142465). It is related to https://github.com/edgedb/edgedb/issues/684, but not exactly the same. I would want to be able to do a select if exists, otherwise insert, when making a query like this:

```
INSERT Movie {
    title := 'Dune',
    year := 2020,
    image := 'dune2020.jpg',
    directors := (
        SELECT Person
        FILTER
            .last_name = 'Villeneuve'
    )
}
```

Such that if there were not a person with the last name `Villenueve`, it would automatically create a record. I think a lot of people will have this scenario. For example, if you're iterating through a table that models an N-1 relationship and only want to make one pass, this would be very helpful.

I'm not sure how it would make sense to change the `SELECT Person` part of the syntax to make it also able to incorporate other information - our discussion on twitter mentioned the coalesce ?? operator but I'm not familiar with that yet. If there's an obvious solution already, then it would be great to add to the docs!

**Comment by elprans** [comment]
The plan is to specialize the `??` operator:

```
INSERT Movie {
    title := 'Dune',
    year := 2020,
    image := 'dune2020.jpg',
    directors :=
        (SELECT Person FILTER .last_name = 'Villeneuve') 
        ?? (INSERT Person {last_name := 'Villeneuve'}),
}
```

The requirement here would be for `.last_name` to also have a unique constraint so that we can use the `ON CONFLICT` SQL clause to make this efficient.

**Comment by cthoyt** [comment]
If you have something like this, is it automatically optimized? Or does it still mean that if this query is run in batch, that it will run the same select over and over?

**Comment by elprans** [comment]
If you pass the data as an array and use a `FOR` statement to insert, then this approach should be fairly efficient.

**Comment by elprans** [comment]
This is being worked on in #1639.
