### ISSUE TITLE
InternalServerError: 'NoneType' object has no attribute 'ptrref'

### ISSUE THREAD

**Issue by jaclarke** [edgedb/edgedb#1471]
- EdgeDB Version: 1.0-alpha.3+dev.247.g04b74247

Steps to Reproduce:
Error occurs when a computed property has a link property path on a subquery, eg.

```
WITH MODULE schema
SELECT ObjectType {
  name,

  # error occurs with this line:
  annotationValues := (SELECT .annotations)@value

  # these are ok:
  # annotationValues := .annotations@value
  # annotationNames := (SELECT .annotations).name
  # annotationNames := .annotations.name
  
} FILTER EXISTS .annotations
```

**Comment by elprans** [comment]
`(SELECT .annotations)@value` should be a `ReferenceError`.  The only valid form of link property reference is `.link@prop`.
