### ISSUE TITLE
Need to add tests for creating/dropping indexes (with DDL too)

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#148]

**Comment by vpetrovykh** [comment]
In accordance with #149, I'll use `__subject__` instead of `__self__`.

**Comment by 1st1** [comment]
@elprans can this be closed now?

**Comment by 1st1** [comment]
@elprans @vpetrovykh close this?

**Comment by elprans** [comment]
Yeah, we have tests for indexes now.
