### ISSUE TITLE
edgedb wipe or edgedb restore --force

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#1486]
EdgeDB seem to be missing the ability to reset database to initial state.
I had some troubles with `edgedb restore` recently, there were a few types in `edgedb` database which can not be removed and thus each of them had to be removed for `edgedb restore` to work.
My suggestion is to add `edgedb wipe` CLI command for resetting database. `edgedb restore --force` could be a shortcut for it.

**Comment by elprans** [comment]
Why not just create a new instance?

**Comment by Fogapod** [comment]
Bootstrapping a new instance takes a lot of time on my weak CPU, would resetting database take as long?

**Comment by elprans** [comment]
> Bootstrapping a new instance takes a lot of time on my weak CPU

This should no longer be the case in alpha 3 builds, which ship the template EdgeDB database as a regular Postgres dump.

>  would resetting database take as long

The only reliable way to do a factory reset would be to drop the databases and re-create them, which would be the same process as the bootstrap itself.

**Comment by Fogapod** [comment]
`edgedb destroy` and `edgedb init` are the commands now and initialization is much cheaper.
