### ISSUE TITLE
Bad error reporting after constant extraction

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#1496]
```
edgedb> SELECT ''' 1 ''';
error: Unexpected '('
  ┌─ query:1:10
  │
1 │ SELECT ''' 1 ''';
  │          ^^^^^^ error
```
There is no paren in original text so error is misleading.

**Comment by 1st1** [comment]
As discussed offline we can mitigate this by adding a check to the lexer: error with SyntaxError if a literal token immediately follow another literal token. IIRC we don't have any legal syntax like that in EdgeQL.

**Comment by tailhook** [comment]
The error from #1676 is different:
```
select str{'1'};
error: Unexpected '('
  ┌─ query:1:12
  │
1 │ select str{'1'};
  │            ^^^^ error
```
While bug is basically the same. We can't apply what @1st1 suggests to this error. So should we fallback to re-parsing original text on any syntax error instead?

**Comment by 1st1** [comment]
Why do we inject `(`?

**Comment by tailhook** [comment]
> Why do we inject `(`?

Because some operators have greater precedence than `<type cast>`.

**Comment by 1st1** [comment]
I only see the `[index]` operator having greater precedence than cast (`DETACHED` is irrelevant for constant extraction). Perhaps we can do something about that? E.g. see if the constant is followed by `[` and only then inject `(`s?

**Comment by tailhook** [comment]
We discussed that (it's possible but not future proof). But then it woulld be `unexpected '<'` which isn't any better.

**Comment by 1st1** [comment]
> But then it woulld be unexpected '<' which isn't any better.

Ah, that's right. :/

> So should we fallback to re-parsing original text on any syntax error instead?

I guess there's no way around that. @elprans thoughts?

**Comment by elprans** [comment]
> So should we fallback to re-parsing original text on any syntax error instead?

Yes, and I don't see a problem with that.
