### ISSUE TITLE
Update documentation on building resource requirements

### ISSUE THREAD

**Issue by ctmattice** [edgedb/edgedb#1508]
Not sure if this is a actual feature requestion or a documentation change. In the edgedb docs internals section covering building from source, I found on fedora 32 that cargo and python3-rust is also required. I presume that it would also be a requirement of RHEL/CentOS and Ubuntu.

Not sure on the python3-rust package as it is possible that pip would/could install that requirement.

**Comment by 1st1** [comment]
cc @tailhook

**Comment by tailhook** [comment]
> I found on fedora 32 that cargo

Yes, we were assuming that installing rust = installing cargo. But adding it to the list of dependencies makes sense.

>  and python3-rust is also required.

I'm not sure what is it? What error do you have when you don't have the package?

We use `setuptools-rust` for buliding, and setup.py is crafted carefully to allow pip installing this package itself.

**Comment by tailhook** [comment]
"Cargo" is added to the list. Please reopen if something left to do.
