### ISSUE TITLE
QueryError: operator '-' cannot be applied to operands of type 'default::A' and 'default::A'

### ISSUE THREAD

**Issue by dmgolembiowski** [edgedb/edgedb#1511]
- EdgeDB Version: edgedb-1-alpha2
- OS Version: Debian 10 (Buster)

Steps to Reproduce:

1. Create an object of type A to be multi-linked
2. Create an object of type B that has a (non-required) multi link such that:

```sql
create type A;
create type B {
    create multi link a_objects -> A;
};
insert B;
with some_B := {(select B)}
update B
filter B = some_B
set {
    a_objects := B.a_objects union ( insert A )
};
{Object { id: <uuid>'73c5a04e-bced-11ea-8476-e3011ef40cb2' }}
```
3. Confirm that the multi link is intact.

```sql
select B { a_objects };
{Object { a_objects: {Object { id: <uuid>'86871df6-bcee-11ea-8476-a3f2f1f22374' }} }}
```

4. Try to drop the link before deleting the object:

```sql
with some_b := {(select B filter .id = <uuid>'73c5a04e-bced-11ea-8476-e3011ef40cb2')},
     some_a := {(select A filter .id = <uuid>'86871df6-bcee-11ea-8476-a3f2f1f22374')}
update B
filter B = some_b
set {
    a_objects := {B.a_objects} - {some_a}
};
```

5. Get the error:
```sql
QueryError: operator '-' cannot be applied to operands of type 'default::A' and 'default::A'
Hint: Consider using an explicit type cast or a conversion function.
### with some_b := {(select B filter .id = <uuid>'73c5a04e-bced-11ea-8476-e3011ef40cb2')},
###      some_a := {(select A filter .id = <uuid>'86871df6-bcee-11ea-8476-a3f2f1f22374')}
### update B
### filter B = some_b
### set {
###     a_objects := {B.a_objects} - {some_a}
###                  ^
### };
```

The recreation steps above were meant to recreate a different (correct) error when trying to delete an object that was multiply-linked to a parent object. I reasoned that to satisfy a `ConstraintViolationError: deletion of <x> is prohibited by link target policy` error, I first needed to "un-link" two objects by taking the difference of two sets. However, it looks like EdgeDB didn't agree with my heuristic.

**Comment by 1st1** [comment]
I guess the expectation that `-` would work is created by the new `:-` operator?

**Comment by dmgolembiowski** [comment]
> I guess the expectation that `-` would work is created by the new `:-` operator?

That's a fair observation; I might just need to bite the bullet and update. :smile:

**Comment by msullivan** [comment]
Yeah I don't think this is a bug?
