### ISSUE TITLE
Start Migration command does not work.

### ISSUE THREAD

**Issue by mistyharsh** [edgedb/edgedb#1559]
- EdgeDB Version: 1.0 Alpha 4
- OS Version: Docker

`start migration` command does not work. Following the documentation at [Getting Started](https://edgedb.com/docs/tutorial/createdb), I tried to create a simple user type;

```
start migration to {
  module default {

    type User {
      required property firstName -> str;
      required property lastName -> str;

      required property email -> str;
      required property password -> str;
      required property passwordSalt -> str;
      required property passwordHash -> str;
    };

  };
};
```
Ideally command should automatically start transaction but I get the following error:
![Error](https://user-images.githubusercontent.com/4905303/87871952-6c915380-c9d2-11ea-92e8-62ad988a8393.png)

However following command works:
```
start transaction;
create migration first to {
  module default {
    type User {
      required property firstName -> str;
      required property lastName -> str;

      required property email -> str;
      required property password -> str;
      required property passwordSalt -> str;
      required property passwordHash -> str;
    };
  };
};

commit migration first;
commit;
```

Am I missing anything?

**Comment by elprans** [comment]
It looks like the `edgedb/edgedb:latest` tag didn't get updated to point to `alpha-4` and so you seem to be running Alpha 3 image still.  This is now fixed, please `docker pull` and try again.  Thanks!

**Comment by mistyharsh** [comment]
Yes. This work after pulling the docker image again. Thanks!
