### ISSUE TITLE
Multiple GraphQL mutations do not work

### ISSUE THREAD

**Issue by mistyharsh** [edgedb/edgedb#1566]
- EdgeDB Version: 1.0 Alpha 4
- OS Version: Docker

### Steps to Reproduce:
1. Create a simple database & connect to it.
2. Expose the GraphQL layer for this database.
3. Try running one mutation - it works.
4. Try running more than mutation - **it doesn't work**

The error is:
```json
{
  "errors": [
    {
      "message": "AttributeError: 'NoneType' object has no attribute 'dummy'"
    }
  ]
}
```

Schema and steps used to create the database and GraphQL layer:
```
start migration to {
  module default {

    type Project {
      required property name -> str;

      multi link tests -> TestCase;
    };

    type TestCase {
      required property name -> str {
        constraint exclusive;
      };
    };

  };
};
populate migration;
describe current migration;
commit migration;

# Open port for GraphQL
CONFIGURE SYSTEM INSERT Port {
    protocol := "graphql+http",
    database := "testdb",
    address := "0.0.0.0",
    port := 8888,
    user := "http",
    concurrency := 4
};
```

### What works:
```gql
mutation {
  insert_Project(data: [{ name: "Project 1" }]) {
    id
    name
  }
}
```

and
```gql
mutation {
  insert_TestCase(data: [{ name: "Hello world 1" }]) {
    id
    name
  }
}
```

### What does not work (multiple mutations in same request):
```gql
mutation {
  insert_Project(data: [{ name: "Project 1" }]) {
    id
    name
  }

  insert_TestCase(data: [{ name: "Hello world 1" }]) {
    id
    name
  }
}
```

A question (on a side note) - How does EdgeDB handle GraphQL mutation requests? If there are multiple mutations, is the full mutation request considered automatic? Is it running within a single transaction or multiple DB transactions per mutation?

**Comment by elprans** [comment]
> How does EdgeDB handle GraphQL mutation requests? If there are multiple mutations, is the full mutation request considered automatic? Is it running within a single transaction or multiple DB transactions per mutation?

All mutations are executed as a single query atomically.
