### ISSUE TITLE
Add support for type expressions in casts and type assertions

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#1577]
Currently, type assertions (`[IS <Type>]`) only support simple types and not Unions or Intersections (although it should be possible to emulate Intersection by chaining `[IS `).

See #219 for a longer story on type expressions and type operators.

**Comment by msullivan** [comment]
To add some context, the goal here is supporting things like `select Object[is Card | User]`

**Comment by dnwpark** [comment]
Resolved by #7274 and #7172.
