### ISSUE TITLE
Getting started document need more

### ISSUE THREAD

**Issue by Tembocs** [edgedb/edgedb#1613]
I've been trying to learn EdgeDB. One of the initial huddle I faced is the fact that the getting started section seem to have skipped important information. I have successful install EdgeDB. Running ```edgedb --version``` gives ```edgedb-cli 1.0.0-alpha.4``` which speaks for successful installation. Running ```edgedb``` hoping to get into EdgeDB shell gives error message ```Error: Password required for the specified user/host```. Somewhere down the documentation there are information on how to set password which are not very clear and gives error messages.

I suggest the following:
1. Inform the user on how to install EdgeDB.
2. Inform the user on how to configure EdgeDB for FIRST USE, including how to set password, how to create roles and possible error messages and how to solve them. THIS IS WHERE MORE PROBLEMS ARISE!
3. Inform the user on how to start EdgeDB and the shell too.
4. Then talk of the schema creation.

**Comment by elprans** [comment]
Hi @Tembocs.  Thank you for the report!  We are working to make the auth configuration part of the initial setup (see edgedb/edgedb-cli#91).  Unfortunately, that feature didn't make it into a4, but the docs were updated as if it did.  We'll amend the docs to include the manual instructions until the initial auth setup is automated.

**Comment by Tembocs** [comment]
Hi @elprans, any updates on this issue? I still can't learn/test/use EdgeDB as there is nowhere I can find information on how to properly configure EdgeDB/instance and start the shell. Just for the purpose of giving more information in case you need it.
I tried to install EdgeDB in another Ubuntu machine. [This section](https://edgedb.com/docs/admin/setup) says to use the command ```edgedb server init -I<instance-name>``` for creating new EdgeDB instance. Based on that I tried to run ```edgedb server init -Iresults``` and EdgeDB gives the below error message:
```
error: Found argument '-I' which wasn't expected, or isn't valid in this context

If you tried to supply `-I` as a PATTERN use `-- -I`
...
```
Putting a space between ```-I``` and ```results``` didn't help. Over this week I've been reading around the documentation unsuccessful hoping to find a section with a better explanation on this. Since the project need people to start testing EdgeDB I believe the very initial steps of setting up EdgeDB/instance should be laid out as clear and simple as possible with examples.

**Comment by elprans** [comment]
Hi @Tembocs.  The documentation seems to be wrong about the actual syntax of the `edgedb server init` command.  The correct syntax is:

```
edgedb server init <instance-name>
```

@tailhook is this intentional?  Other commands seem to be using `-I` to specify the instance name.

**Comment by tailhook** [comment]
> @tailhook is this intentional? Other commands seem to be using `-I` to specify the instance name.

Currently `-I` only works for specifying instance in REPL and other command requiring database connection. For command that manipulate server instances `<instance-name>` is a positional argument. I don't think we reached consensus that this has to be changed, just mentioned that it could be.

**Comment by PastelStoic** [comment]
The `server init` command seems to have been depreciated, and the installation method is now vastly different. If my assumptions are correct, this issue can be closed as no longer relevant.
