### ISSUE TITLE
Declaring an overloaded link optional fails on commit

### ISSUE THREAD

**Issue by CodesInChaos** [edgedb/edgedb#1619]
- EdgeDB Version: Alpha 4
- OS Version: ubuntu 20

Run the following migration on an empty database:

```
START MIGRATION TO {
module default {
	abstract type Version {
		optional link copied_from -> Version;
	}

	type ItemVersion extending Version {
		overloaded optional link copied_from -> ItemVersion;
	}
}
};
POPULATE MIGRATION;
COMMIT MIGRATION;
```

The commit return the following error

> ERROR: SchemaError: cannot drop required qualifier of an inherited link 'copied_from'

The generated DDL is:

```
CREATE ABSTRACT TYPE default::Version {
    CREATE OPTIONAL SINGLE LINK copied_from -> default::Version;
};
CREATE TYPE default::ItemVersion EXTENDING default::Version {
    ALTER LINK copied_from {
        DROP REQUIRED;
        SET TYPE default::ItemVersion;
    };
};
```

an implicitly optional link doesn't generate the `DROP REQUIRED;` part and works.

If the link already exists, even the variant with an explicitly optional link works, since it doesn't emit any DDL statements.

While the workaround is simple (just don't specify `optional` when overloading), the dependency on the current database state makes this issue pretty annoying to troubleshoot.

**Comment by elprans** [comment]
This was fixed yesterday in #1612. Thanks for the report!
