### ISSUE TITLE
Type without attributes in esdl

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#1626]
Why is `type User {}` an illegal esdl statement? `error: Unexpected '}'`
This could happen during some weird code generation or during testing.
I see no reason why it should not be allowed.

`type User` is a valid way to define type without attributes.

**Comment by CodesInChaos** [comment]
Same applies to properties, links and constraints. Sometimes I comment out an attribute within, and then have to remove the `{}` just to get it to compile again.

**Comment by Fogapod** [comment]
Same is also true for all DDL it seems: `CREATE TYPE User {};` `error: Unexpected '}'`
