### ISSUE TITLE
Specialize 'select-or-insert' and 'update-or-insert'

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#1639]
Recent work on adding the select-or-insert and update-or-insert idioms to EdgeQL (#1628, #684) spawned a discussion on whether using a general-purpose conditional operator `??` is a good idea after all.

The approach committed in #1628 has lots of technical limitations, and, although most of those can be fixed with more work, the main issue with it remains: it gives a misleading appearance of generic support for conditional DML which is impossible as long as it is in PostgreSQL.

For this reason I propose reverting the select-or-insert and update-or-insert to a specialized form of the `INSERT` statement:

```
INSERT Type { <shape> } 
UNLESS CONFLICTS [ <conflict-target> [ ELSE <alternative-stmt> ] ]
```

where `alternative-stmt` may be any other query, including `UPDATE` or `DELETE`.

This is semantically much closer to PostgreSQL's `INSERT ... ON CONFLICT ...` and allows explicit specification of the conflict target (i.e. the constraint expression).

**Comment by elprans** [comment]
An important question to answer in this formulation is whether the `Type` reference is bound in the `ELSE` clause.  If it is, then the alternative statements would not need a `FILTER`, so 

```
INSERT User { ... } UNLESS CONFLICTS .name 
ELSE SELECT User
``` 

and

```
INSERT User { ... } UNLESS CONFLICTS .name
ELSE UPDATE User SET { ... }
```

FWIW, PostgreSQL binds the name of the table in `ON CONFLICT DO UPDATE`.

Another option would be to add a special keyword to refer to the conflicting object (e.g `__conflicting__`), but I prefer that less.

**Comment by vpetrovykh** [comment]
If I understand this proposal correctly I can write:
```
INSERT Foo {bar := 1} UNLESS CONFLICTS
```
Which will return an `{}` in case of conflict instead of raising an exception. So it should be legal to write:
```
SELECT (INSERT Foo {bar := 1} UNLESS CONFLICTS) ?? (SELECT Foo FILTER .bar = 1)
```
or, if I want a different fallback:
```
SELECT (INSERT Foo {bar := 1} UNLESS CONFLICTS) ?? (SELECT Foo FILTER .bar = 42)
```

How is using an `ELSE` clause really helping here? Especially if the `Foo` reference is bound as suggested, then the last expression would have to be:
```
WITH Foo2 := Foo  # going to need this for selecting a default 
                  # that's something other than the conflicted value
INSERT Foo {bar := 1} UNLESS CONFLICTS ON .bar ELSE (SELECT Foo2 FILTER .bar = 42)
```

**Comment by vpetrovykh** [comment]
Also, I'm not too keen on equating the `Foo` in the `INSERT` to the `Foo` in the `SELECT`. They are semantically different, the `INSERT` has to refer to a specific non-abstract object type, `SELECT` can have any expression of some object type preceeding the shape, so `Foo` there is a set reference. I think that `__conflicting__` object placeholder is far better. So this is a **+1** to `__conflicting__`.

On the other hand, can I nest these? Can I do:
```
INSERT Foo {bar := 1} UNLESS CONFLICT ON .bar ELSE
(INSERT Foo {bar := 2} UNLESS CONFLICT ON .bar ELSE SELECT __conflicting__)
```
In the above, what would `__conflicting__` refer to (`bar = 1` or `bar =2`)? Same question if we don't use `__conflicting__`, but use a bound version of `Foo`? If this is allowed, then it seems that binding `Foo` or explicit `__conflicting__` placeholder are both bad and an explicit `SELECT Foo FILTER .bar = 1` is better.

**Comment by elprans** [comment]
> How is using an `ELSE` clause really helping here?

It helps with when you put `UPDATE` in `ELSE` and for rationale about that see the initial message above.

> They are semantically different

From the standpoint of variable binding, they're not different, and that's why we disallow self-referential `INSERT`.  Yes, you can only refer to a non-abstract type in the `INSERT` clause, but once you do, you are still _binding_ the name to an object that is being constructed.  I see no conflict here. The question here isn't any apparent semantic difference but rather that of whether `INSERT ON CONFLICT ELSE` behaves like `IF`, i.e. both leaves are in different scope, or like `??`, where symbols in LHS are bound in the RHS.

Oh, and your example with nested `INSERT` actually disqualifies `__conflicting__` altogether.

**Comment by vpetrovykh** [comment]
> It helps with when you put `UPDATE` in `ELSE` and for rationale about that see the initial message above.

But _can_ I just put an empty set in the `ELSE` part (or omit it) and move on with my `??` construct? If I can, then I will still have the appearance of generic support for conditional DML, no?

> Oh, and your example with nested `INSERT` actually disqualifies `__conflicting__` altogether.
Cool, kill `__conflicting__`, but if you insist on binding the `Foo`, the ambiguity in my nested example remains. What does this return?
```
INSERT Foo {bar := 1} UNLESS CONFLICT ON .bar ELSE
(INSERT Foo {bar := 2} UNLESS CONFLICT ON .bar ELSE SELECT Foo)
```

Also, can I do this?
```
INSERT Foo {bar := 1} UNLESS CONFLICT ON .bar ELSE
(
   WITH F1 := Foo  # store first conflict 
   INSERT Foo {bar := 2} UNLESS CONFLICT ON .bar ELSE 
   WITH F2 := Foo, # store second conflict? 
   INSERT Foo {bar := Foo1.bar + Foo2.bar}
)
```
Basically, can I capture each conflicted value in my nested `INSERT UNLESS CONFLICT` construct to maybe make a record of them?

**Comment by vpetrovykh** [comment]
Is this the correct way to "try inserting one thing, then a fallback, then update the first one if the fallback doesn't work"?
```
INSERT Foo {bar := 1} UNLESS CONFLICT ON .bar ELSE
(
   WITH F1 := Foo  # store first conflict 
   # try another one
   INSERT Foo {bar := 2} UNLESS CONFLICT ON .bar ELSE 
   # update the first one
   UPDATE F1 SET {bar += 1000}
)
```

**Comment by elprans** [comment]
> But _can_ I just put an empty set in the `ELSE` part (or omit it) and move on with my `??` construct? If I can, then I will still have the appearance of generic support for conditional DML, no?

No, you cannot put DML in the RHS of `??`.  You can, of course, omit `ELSE` and coalesce with any non-DML expression.

> the ambiguity in my nested example remains

There is no ambiguity in your example: it's an error.  You cannot have `Foo` bound in two different `INSERT` statements (it's the same as self-referencing nested `INSERT`).

**Comment by vpetrovykh** [comment]
> There is no ambiguity in your example: it's an error. You cannot have `Foo` bound in two different `INSERT` statements (it's the same as self-referencing nested `INSERT`).

Wait, does this mean that I cannot try inserting one thing and then on conflict insert same object type but with a different bunch of values?
```
# pretend that we have some function that basically guarantees to return a unique int
INSERT Foo {val := 1} UNLESS CONFLICT ON .val INSERT Foo {val :=  timestamp_as_int64()};
```

**Comment by elprans** [comment]
> Wait, does this mean that I cannot try inserting one thing and then on conflict insert same object type but with a different bunch of values?

You can't, because `Foo` in `ELSE` would be bound to the _conflicting object_, and you can't `INSERT` an existing object again.  So, you must disambiguate by aliasing `Foo` in the top `WITH` or something.

**Comment by 1st1** [comment]
I see two different spellings here: `UNLESS CONFLICTS` and `UNLESS CONFLICT`. I'm +1 for the latter. Also, I think that the optional `<conflict-target>` should be prefixed by `ON`.

```
INSERT Type { <shape> } 
UNLESS CONFLICT [ ON <conflict-target> [ ELSE <alternative-stmt> ] ]
```

**Comment by vpetrovykh** [comment]
Do we also have a `DELETE ... UNLESS CONFLICT`? Technically those aren't conflicts, but `on target delete` restrictions, but I think "conflict" is a good enough term for that as well.

**Comment by elprans** [comment]
No, `DELETE UNLESS CONFLICT` would have a drastically different implementation and the use case for it isn't clear.
