### ISSUE TITLE
Function ignores default value for new object's link

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#1644]
- EdgeDB Version: `1.0-alpha.4+dev.116.g83e9f530`
- OS Version: Docker

### Query
```edgeql
START TRANSACTION;

CREATE TYPE User;
CREATE FUNCTION insert_user() -> User {
    USING (
        INSERT User
    )
};

START MIGRATION TO {
    module default {
        type User {
            required link global_role -> GlobalRole {
                default := (
                    SELECT GlobalRole
                    FILTER .name = "Default"
                    LIMIT 1
                );
            };
        }

        type GlobalRole {
            required property name -> str;
        }

        function insert_user() -> User {
            using EdgeQL $$
                INSERT User
            $$
        }
    }
};

POPULATE MIGRATION;
COMMIT MIGRATION;

INSERT GlobalRole {
    name := "Default",
};

INSERT User;  # this works
SELECT insert_user();  # this does not work
# ERROR: MissingRequiredError: missing value for required property default::User.global_role
```

### Explanation
In this migration I define function with DDL as a workaround: https://github.com/edgedb/edgedb/issues/1625#issuecomment-670159385
This is first migration, so I had to define User with DDL before function.
After performing SDL migration function complains about missing default value for link even though it has default value.

I also tried this with required property with default value, it worked.

**Comment by elprans** [comment]
Yep. This is because EdgeDB injects defaults at compile time and it looks like we forget to recompile function bodies in a scenario where an object changes its defaults like in the above.

**Comment by msullivan** [comment]
We've disallowed inserts in functions for years now, closing
