### ISSUE TITLE
We need `+=` and `-=` operators for UPDATE

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#165]
When updating some link with `*` cardinality it is often useful to only add or remove targets rather than redefine the entire target set. To this end we can add `+=` and `-=` operators in place of `:=`. They would only appear in `SET` clause of `UPDATE` statements.

**Comment by vpetrovykh** [comment]
In EdgeQL `+` and `-` are specifically numerical addition and subtraction, so it could be misleading to use `+=` and `-=` to mean "add more items to the set" and "remove these items from the set" respectively. We don't have a short symbolic operator for set `UNION`, and we don't even have any special operator for set subtraction (as this is a function of `FILTER`). We should use some operators that would be consistent and recognizable, so one option is to pretend what would "set union" and "set subtraction" look like and use their derivatives in `UPDATE`.

We could treat `|` as `UNION`, but subtraction is a little weirder: the  [common symbol](https://en.wikipedia.org/wiki/Set_(mathematics)) is `\` or `-`. We would like to avoid `-` to avoid ambiguity, but the `\` is commonly used in escaped characters and may also look a bit confusing. Still, this would result in `|=` and `\=` for "add" and "remove" items in update. One of the downsides of these symbols is that they look similar to each other.

**Comment by elprans** [comment]
If we keep `+=` and `-=` exclusively for the purpose of adding/subtracting from pointer target set, then, I think, the potential for confusion isn't that large.  The alternatives look too arcane.

**Comment by elprans** [comment]
@vpetrovykh, the implementation for this has landed, we need to update the docs and add this to the tutorial/cheatsheet etc.
