### ISSUE TITLE
DDL results in SQL syntax error

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#1667]
- EdgeDB Version: EdgeDB 1.0-alpha.4+dev.130.g9e96c03f
- OS Version: LInux

Steps to Reproduce:

Try this in REPL:
```
CREATE TYPE Foo {CREATE LINK left -> Foo};
```

I get an error:
```
  Server traceback:
      edb.errors.InternalServerError: syntax error at or near "left"
```

Note that this also happens for `rgiht`. It appears that the identifier `left` is not quoted and clashes with a SQL keyword.

**Comment by elprans** [comment]
`needs_quoting` in `pgsql/common.py` needs to be updated to always quote all keywords except `UNRESERVED_KEYWORD`.
