### ISSUE TITLE
Wrong parentheses symbol in error message

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#1676]
- EdgeDB Version: `1.0-alpha.4+dev.116.g83e9f530`
- EdgeDB CLI Version: `1.0.0-alpha.4+d20200806.g089f60fef`

Steps to Reproduce:

```edgeql
select str{'1'};
error: Unexpected '('
  ┌─ query:1:12
  │
1 │ select str{'1'};
  │            ^^^^ error
```

Message should say `{`, not `(`.

**Comment by elprans** [comment]
It's edgedb/edgedb#1496
