### ISSUE TITLE
TypeDescritpor should reflect lower cardinality bound in Shapes

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#1679]
Currently query type descriptors communicate only the upper cardinality bound of an element in an object shape (indirectly via the class of the linked type descriptor: `Type` vs `Set`).  For the benefit of client languages with non-optional types (e.g. Rust), we should also communicate the lower bound, i.e whether or not link or link property is `required`.

I see two possible ways to fix this: break compatibility and add another field to `ShapeElement` struct, OR keep compatibility and add a `required` flag to `flags`.

**Comment by 1st1** [comment]
> OR keep compatibility and add a required flag to flags.

I'd prefer to have a proper cardinality enum. So perhaps we should use two bits to encode it.

**Comment by elprans** [comment]
> So perhaps we should use two bits to encode it.

That's fine by me.
