### ISSUE TITLE
Restrict the usage of DML in DDL and within shapes.

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#1688]
There are some limitations to using DML (`INSERT`, `DELETE`, `UPDATE`)
statements as part of other expressions:

* They cannot appear as branches of conditional expressions (#684, #1639).
* They shouldn't appear inside function bodies (although this
  limitation can be relaxed in the future #1661).
* They cannot be correlated with other query components, basically
  they must always be independent of the rest of the query in such a
  way that refactoring them into a `WITH` block doesn't change the
  semantics.

The last point results in some additional restrictions that need to be enforced:

* DML cannot appear as a computable in a shape
* DML cannot appear as a computable in a type or aliased type
  declaration at all (even in a `WITH` block), because that
  potentially results in issues with correlation of the DML and the
  rest of the object whenever that type appears in a query.

It is, however, legal to use DML in a `default` expression, for example:

```
type Foo {
    required property val -> str;
}

type Bar {
    required link foo -> Foo {
        default := (INSERT Foo)
    }
}
```

Which means that if `foo` is omitted at creation time, a new `Foo`
object will be created automatically for that link.

**Comment by elprans** [comment]
@vpetrovykh Is this done?

**Comment by vpetrovykh** [comment]
This appears to be done. Special case of possibly allowing DML in functions is a separate issue #1661
