### ISSUE TITLE
Can't define tuple properties

### ISSUE THREAD

**Issue by CodesInChaos** [edgedb/edgedb#1728]
- EdgeDB Version: alpha-5
- OS Version: ubuntu 20

Steps to Reproduce:

first migrate to (works):
```
START MIGRATION TO {
module default {
type User  {
     required property x -> str;
}

}};
POPULATE MIGRATION;
COMMIT MIGRATION;
```

and then migrate to (fails):

```
START MIGRATION TO {
module default {
type User  {
    required property x -> tuple<a:str, b:str>;
}
 
}};
POPULATE MIGRATION;
COMMIT MIGRATION;
```

fails with

> Error: ERROR: InternalServerError: column "x" cannot be cast automatically to type "63cafebd-2e5a-af78-dc9c-ed5fa314c43f_t"
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: column "x" cannot be cast automatically to type "63cafebd-2e5a-af78-dc9c-ed5fa314c43f_t"

**Comment by CodesInChaos** [comment]
appears to be fixed in nightly

**Comment by elprans** [comment]
Actually it seems like the issues are during a migration from a *non-empty* schema.  Specifically `"x" cannot be cast automatically to type` is caused because you can't always change the type of a property without specifying some conversion expression (support for that is being worked on).

Can you show the schema you were migrating *from* when you got the original exception?

**Comment by CodesInChaos** [comment]
Doing the following first seems to trigger the behaviour:
```
START MIGRATION TO {
module default {
type User  {
     required property x -> str;
}

}};
POPULATE MIGRATION;
COMMIT MIGRATION;
```

**Comment by CodesInChaos** [comment]
Speaking of migrations from a non empty schema, I have one where migrating form the schema to an empty schema fails. But it's I haven't reduced it to a minimal example. Can I share a private schema with you, e.g. by giving access to a private github repo?

**Comment by elprans** [comment]
> Doing the following first seems to trigger the behaviour:

Yes, that one is well understood.  I was referring to the error that you had in an earlier version of this ticket:

> `ERROR: InvalidReferenceError: reference to a non-existent schema item 4f31df1d-e916-11ea-8f44-17f6b7b2d761 in schema <Schema gen:3640 at 0x7fb0186ceb20>`

> Or should I email it?

Sure, send an email to support@

**Comment by CodesInChaos** [comment]
> > `ERROR: InvalidReferenceError: reference to a non-existent schema item 4f31df1d-e916-11ea-8f44-17f6b7b2d761 in schema <Schema gen:3640 at 0x7fb0186ceb20>`
I don't think I can reproduce this specific instance of this error. In general this kind of migration error occurs so often and is so annoying to debug that my program always drops the database before applying a new schema to avoid these path dependent problems.

**Comment by elprans** [comment]
> I don't think I can reproduce this specific instance of this error.

If it happens again, it'd be great to have a look at the base schema for the migration.  And for all migration bugs in general, because most depend on where you're migrating *from*.

**Comment by CodesInChaos** [comment]
I generally start with an empty *before* schema (I might give incremental migrations a try after #1625 and the bug where I can't migrate from my schema to an empty schema are fixed). In this case I accidentally migrated from a non empty schema while trying to produce the minimal example for another problem.

**Comment by CodesInChaos** [comment]
Probably can close this once. The "cannot be cast automatically to type" problem appears to be a known limitation and I don't think I'll be able to reproduce the `InvalidReferenceError`. My best guess is that the `InvalidReferenceError` is the same issue I emailed you.

**Comment by elprans** [comment]
OK, closing.
