### ISSUE TITLE
Can't create tuple property containing custom scalar

### ISSUE THREAD

**Issue by CodesInChaos** [edgedb/edgedb#1730]
- EdgeDB Version: nightly (1.0a6.dev5038+g7cd6dcc4)
- OS Version: ubuntu 20

```
START MIGRATION TO {
module default {
	scalar type MyScalar extending str;

	type User {
		required property tup -> tuple<x:MyScalar>;
	}
}
};
POPULATE MIGRATION;
COMMIT MIGRATION;
```

fails with 
> ERROR: InvalidReferenceError: type 'default::MyScalar' does not exist

**Comment by elprans** [comment]
Yes, the dependency resolver gets it wrong in this case.
