### ISSUE TITLE
edgedb --admin fails on ubuntu 20

### ISSUE THREAD

**Issue by CodesInChaos** [edgedb/edgedb#1733]
- EdgeDB Version: alpha 5
- OS Version: ubuntu 20 (mate)

Steps to Reproduce:

Install edgedb via cli. Run `edgedb --admin`. It fails with:

> Error: Can't connect to unix socket "/var/run/edgedb/.s.EDGEDB.admin.5656": No such file or directory (os error 2)

(not sure if this is a bug in edgedb-server or edgedb-cli)

**Comment by elprans** [comment]
CLI-installed servers use named instances:

```
edgedb server install
edgedb server init myinstance
edgedb --admin -Imyinstance
```

We need to make the CLI try the default local instance instead of going to 5656 (or `/var/run/edgedb`)

**Comment by 1st1** [comment]
This should be fixed now, closing the issue. Feel free to reopen if you see this happening again.
