### ISSUE TITLE
Require a FILTER on DELETE and UPDATE?

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#1742]
There was some discussion earlier about requiring FILTER on DELETE and UPDATE statements, to help prevent mishaps. `FILTER true` could be used when operating on everything is actually desired.

(Relevant: https://www.youtube.com/watch?v=i_cVJgIz_Cs)

**Comment by 1st1** [comment]
Yes, +1. Let's make it happen before the next release.

**Comment by elprans** [comment]
I think we should only do this if *X* in `DELETE X` is a universal set.

That is the following should be legal: 

```
WITH ToDelete := (SELECT Foo FILTER ...)
DELETE ToDelete
```

or

```
function delete_foo(foo: Foo) -> Foo using (DELETE foo)
```

**Comment by elprans** [comment]
> Why `function delete_foo(foo: Foo) -> Foo using (DELETE foo)` should be legal?

I wouldn't be now, but if we re-enable DML in functions at some point in the future, it would be.  It's just an example of constrained input to `DELETE`, which IMO should not require a `FILTER true`.

**Comment by 1st1** [comment]
>  It's just an example of constrained input to DELETE, which IMO should not require a FILTER true.

Ah, I missed that the function example says `DELETE foo` (not `DELETE Foo`). +1 to what you said in https://github.com/edgedb/edgedb/issues/1742#issuecomment-686640403

**Comment by msullivan** [comment]
Should we allow
```
WITH ToDelete := Foo
DELETE Foo
```
?

**Comment by 1st1** [comment]
I don't think we should; the main intent of this new limitation is to prevent accidental removal of too much data, and this query while obscure can still be an accidental one.

**Comment by vpetrovykh** [comment]
Omitting the `FILTER` in `INSERT Foo {...} UNLESS CONFLICT ON .bar ELSE (DELETE Foo)` should be fine as well as `Foo` is actually bound to a singleton there. (I'm aware that the query as written is a bit odd)

On the other hand we should be able to detect that this is still a universal set (and therefore illegal):
```
WITH U := User
DELETE U;
```

While this is no longer universal (and therefore legal):
```
WITH User := (SELECT User FILTER .name ILIKE 'A%')
DELETE User;
```

**Comment by elprans** [comment]
On the other hand, tracking whether or not a set is constrained in general is harder, and I'm not sure the RoI is worth it in those cases.

**Comment by vpetrovykh** [comment]
Wouldn't the compiler know? I mean, doesn't the compiler keep track of this kind of information already?

**Comment by elprans** [comment]
No, this isn't tracked because there was no reason to before.  The compiler only looks at `FILTER` specifically when inferring cardinality, but nothing more.

**Comment by vpetrovykh** [comment]
So, to track something like this we'd need to start off sets as universal and then mark them as constrained if we see any `FILTER`, `OFFSET`, or `LIMIT` applied to them. That seems relatively straight-forward and possibly doable in the main compile pass. Am I missing something?

**Comment by elprans** [comment]
A set may become constrained not just via clauses, but also through correlation, or, as in the example above, a function argument.  Again, IMO we should not invent elaborate mechanisms to handle the 3% of cases where your indirect expression in `DELETE` ends up being a universal set.

**Comment by elprans** [comment]
See https://github.com/edgedb/edgedb/pull/1773#issuecomment-722615788 for the planned approach to handling this.
