### ISSUE TITLE
document date types

### ISSUE THREAD

**Issue by CodesInChaos** [edgedb/edgedb#1768]
Currently the [documentation for date/time types](https://edgedb.com/docs/datamodel/scalars/datetime/) is missing:
* minimum and maximum values
  Are they different for pure dates and datetime types?
  The postgres documentation gives year ranges for its types, but doesn't state if this means the complete year or if they end in the middle of a year (because they ran out of bits). It's also not clear if edgedb types are identical to those postgres types.
* What calendar they use (proleptic gregorian like postgres?)

I think it'd be a good idea to limit all of them to the same range, so splitting/combining date and time to a datetime is infallible.

**Comment by CodesInChaos** [comment]
**local_date**
* minimum: `0001-01-01`
* maximum `+294276-12-31`
* can't parse years larger than 9999

**local_datetime**
* minimum `-004713-11-24T00:00:00.000` (MJD=0 in proleptic Gregorian)
* maximum: somewhere around 272k (problems with crashes)
* Can't parse negative years
* Can't parse years large than 9999


---

also the following query crashes the interactive tutorial front-end:
```
SELECT <cal::local_datetime>'9999-12-31T00:00:00' + <duration>'2000000000 hour' + <duration>'400000000 hour';
```

**Comment by 1st1** [comment]
Yeah. Our datatime type is a relatively thin wrapper of Postgres' `timestamptz`. So whatever limitations that type has, `std::datetime` has them too. Would appreciate a PR.

**Comment by CodesInChaos** [comment]
The limits for `local_date` appear to be different from postgres, and I'm not sure if they make sense. I think all date-time types should have conistent limits (unlike postgres where dates have larger range than datetimes).

**Comment by vpetrovykh** [comment]
The gotchas are now documented. It seems that all the implementation and documentation in the core of EdgeDB is done at this point. The issue with rust bindings mentioned here doesn't need to be tracked in this ticket.
