### ISSUE TITLE
Extreme datetime arithmetic crashes the interactive tutorial

### ISSUE THREAD

**Issue by CodesInChaos** [edgedb/edgedb#1769]
EdgeDB Version: Interactive Tutorial

Steps to Reproduce:

Execute

```
SELECT <cal::local_datetime>'9999-12-31T00:00:00' + <duration>'2000000000 hour' + <duration>'400000000 hour';
```

in the interactive tutorial. The backend appears to return a normal response, but the whole frontend crashes with "An unexpected error has occurred".

**Comment by 1st1** [comment]
James, I think we should solve this the way we do for int64s -- add a special codec to render datetime in a custom object and then render that. See `compat.ts/decodeInt64ToString` and `numbers.ts/Int64StringCodec`
