### ISSUE TITLE
Migration features

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#1772]
The general idea is that anything with a name should support renaming. We also want creation and deletion work for all items (this would make migrations reliable at least in the simple cases).

Create/drop:
- [x] abstract annotation
- [x] annotation
- [x] abstract constraint
- [x] property constraint
- [x] link constraint 
- [x] type constraint 
- [x] scalar type
- [x] enum type
- [x] object type
- [x] abstract link
- [x] link
- [x] abstract property 
- [x] property 
- [x] link property 
- [x] alias
- [x] index 
- [x] function

Rename:
- [x] abstract annotation
- [x] annotation
- [x] abstract constraint
- [x] property constraint
- [x] link constraint 
- [x] type constraint 
- [x] scalar type
- [x] enum type
- [x] object type
- [x] abstract link
- [x] link
- [x] abstract property 
- [x] property 
- [x] link property 
- [x] alias
- [x] function

Additionally we want to alter some things without a name change when they are already in use:
- [x] alter alias expression 
- [x] alter function body
- [x] alter computable link
- [x] alter computable property 
- [x] add a type to extending 
- [x] remove a type from extending 
- [x] change required status
- [x] change from single to multi property 
- [x] change from single to multi link

**Comment by 1st1** [comment]
cc @elprans @msullivan

**Comment by msullivan** [comment]
:firework: :tada:
