### ISSUE TITLE
Inconsistency with volatile calls

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#1784]
1) `FOR x IN {1, 2, 3} UNION (x, random());` returns identical values
2) `FOR x IN {1, 2, 3} UNION (SELECT (x, random()));` returns different values
3) `SELECT (FOR x IN {1, 2, 3} UNION (SELECT (x, random())));` returns identical values (!)

I /think/ that all 3 ought to return different values but 2 and 3 definitely should do the same thing.

**Comment by 1st1** [comment]
Yeah, this is a known issue, see also https://github.com/edgedb/edgedb/issues/492.

It would be great if we were always consistent when volatile funcs are used without `CORRELATED TO`. Perhaps we should remove hacks that @elprans added to make edge cases work, implement the new syntax, and educate users.

**Comment by msullivan** [comment]
Yeah, I hit this while thinking about #492. 

My intuition about it was that it clearly makes sense according to our semantics that `SELECT (Object, random())` should always return the same value (and, in fact, it would be pretty wrong if it didn't!), the obvious seeming interpretation of our semantics is that `FOR x IN {1, 2, 3} UNION (x, random())` should return different values, and so it should be possible to accomplish whatever we need to do without new syntax. So I figured I'd work through some examples of what workarounds were needed, which would help illuminate to me what is needed from sugar to make it easier.

(Thinking about it a little more, the most obvious reading of our semantics I think also implies that ORDER BY random() ought to work, too, though.)

(There's a plausible semantics where it is *always* allowed to get factored out, also, but my understanding is there are cases where we need that to not be the case. And it's less nice, IMO.)

**Comment by elprans** [comment]
>  Perhaps we should remove hacks

Those aren't hacks.  Our query execution model should be well-defined for things to mostly work intuitively without explicit `CORRELATED` hints.  Specifically, when iterating over an expression that serves as a shape source, we must evaluate all expressions in the shape `N` times, where `N` is the cardinality of the source set (including, possibly 0).  Same applies to `FOR` expressions.  So, in this case, I propose to extend implicit `CORRELATED TO` injection to volatiles inside the body of `FOR`.  Should be a relatively simple fix.

**Comment by elprans** [comment]
> I think also implies that ORDER BY random() ought to work, too, though.

I'm not sure.  Semantically, clauses are basically just fancy operators, and so if in `(Object, random())` we only evaluate `random()` once, `SELECT Object ORDER BY random()` should be the same, since there's no explicit correlation of the `ORDER BY` expression with `Object`.  

That said, we *can* explicitly define `ORDER BY` (and other clauses) to evaluate its expression for every input element regardless of correlation.

What is the intuitive behavior of `SELECT Object FILTER Object.prop > random()`?

**Comment by msullivan** [comment]
> My intuition about it was that it clearly makes sense according to our semantics that `SELECT (Object, random())` should always return the same value (and, in fact, it would be pretty wrong if it didn't!)

Actually, I take this back. The "Iterate over the set of input tuples, and on every iteration evaluate the query expression" semantics does I think imply that it ought to call `random()` for each row, since there will be an input tuple for each Object. But a query like `SELECT ({1,2,3}, random())` would call random() once, because there is only one input tuple.
(This matches what currently happens in my evaluator model.)

Is this a nonstarter in terms of performance/implementation? Anything we need to do we could only do if we detect a volatile, so maybe the hypothetical perf impact isn't that bad, but correlating with every input set seems painful.

So we need to rethink how we specify the semantics, then, too, if our desired (AKA implementable) behavior is somewhere in between what we currently specify and what we implement.

**Comment by elprans** [comment]
>  The "Iterate over the set of input tuples, and on every iteration evaluate the query expression" semantics does I think imply that it ought to call `random()` for each row, since there will be an input tuple for each Object. But a query like `SELECT ({1,2,3}, random())` would call random() once, because there is only one input tuple.

This matches the algorithm description as is currently written, but I think this behavior would be utterly confusing.  `SELECT ({1, 2, 3}, random())` and `WITH X := {1, 2, 3} SELECT (X, random())` shouldn't produce different results.

> Is this a nonstarter in terms of performance/implementation? 

If you're referring to implicit correlation of expressions in a tuple, I'm afraid yes, it's a nonstarter, because the only way you can implement this is with a left-to-right implicit correlation (e.g. a `LATERAL JOIN`), so `SELECT (X, random())` would give different values, but `SELECT (random(), X)` would not, which is obviously a problem.  

> So we need to rethink how we specify the semantics

I think the missing piece here is specifically correlated expressions.  We can say that uncorrelated expressions form independent sets that get added to the input tuple and that on every iteration we evaluate only the (possibly implicitly) correlated expressions.

**Comment by CodesInChaos** [comment]
> SELECT Object FILTER Object.prop > random()

I'd expect this to independently choose each object with probability `1 - prop`

IMO if `ORDER BY random()` doesn't shuffle, it shouldn't compile at all. Perhaps limit the places where `random` can occur, similarly to the limits imposed on INSERT?

**Comment by msullivan** [comment]
Elvis and I talked about this offline for a while yesterday and the salient points are:

For some concreteness, and to illuminate some issues, consider the user-definable volatile function `randscale(x: std::float64) ->  std::float64` that calls `random()` and scales it by `x`, and consider the query `SELECT (Foo.num, Bar.num, randscale(Foo.num), randscale(Bar.num))`

There are basically two reasonable semantic interpretations to give to this query:
 1. That randscale is called twice for every row in the output. This corresponds to our currently specified semantics based on iterating over the input tuple.
 2. That randscale is called once for each row in Foo and once for each row in Bar, and then the cross product of the two is produced. My plan for specifying this more formally is that we would keep a cache, for each volatile function call (or just each function call or even each expression), keyed by the *identity* of all enclosing iteration constructs and any paths that appear in the argument. (The identity bit is annoying and I need to think about how to specify it, but we have to do something similar in the implementation for iterators over scalar types.)

Now, the snag is, if I run the example query right now, we generate pretty reasonable looking code that calls `randscale(Foo.num)` once for every row in `Foo` and `randscale(Bar.num)` once for every row in `Bar`. This is, of course, *neither* of the "sensible" semantics given above. And, in fact, it probably can't be relied on either. Postgres apparently has some unspecified behavior around these things, though I'm having trouble finding a document where they spell this out.

This means that going with option 2 as the definition of the semantics is probably impossible. Option 1 is likely implementable, but we'd need to force all volatile functions to be correlated with essentially every visible path. This seems expensive and painful and I think is probably over constraining; the input tuple set is a modelling choice and we probably don't want to deeply embed it in the actual implementation in an expensive way.

The way forward seems like it probably has to be to suffer some unspecified behavior of our own: we specify option 2 as a *baseline* but allow implementations to make *more* calls to volatile functions that the semantics require. So if we specify it in the way I sketched using a cache, we would say that implementations MUST execute the function if the call is not in the cache, that it MAY execute the function if the call *is* in the cache, and that programs SHOULD NOT depend on whether that is done or not.

Sigh.

**Comment by elprans** [comment]
> `randscale(Bar.num)` once for every row in `Bar`

Correction: for every row in `Foo` x `Bar`

**Comment by msullivan** [comment]
We chatted some more on this:
1. We'd like to restrict uses of volatile functions such that performing a multiple cardinality operation on expressions with volatile is illegal unless it is an explicit iteration. So `SELECT (Foo, random())` would be prohibited but `FOR x IN {Foo} UNION ((Foo, random())` and `WITH X := (SELECT random()) SELECT (Foo, X);` would be allowed. I think with sufficiently strict rules on this, we might be able to dodge the unspecified semantics, and with less strict rules we'll need to keep it but hopefully still be able to mitigate most user confusion. I do think the devil is very much in the details on this, though, and that it's possible that we won't be able to find behavior here that holds together and is worth the costs, so we'll see.
2. Clauses should be thought of as explicit iteration constructs. So `FILTER BY random() > 0.5` and `ORDER BY random()` should work.
3. With clauses and FOR as iteration constructs, I think we don't need CORRELATED TO, so we should put that on hold until it is clear we do.

**Comment by 1st1** [comment]
> <...> I think with sufficiently strict rules on this, we might be able to dodge the unspecified semantics, and with less strict rules we'll need to keep it but hopefully still be able to mitigate most user confusion. <...>

Hm, I've trouble interpreting this. Stricter or less strict than _"uses of volatile functions such that performing a multiple cardinality operation on expressions with volatile is illegal unless it is an explicit iteration"_? How can this specific rule be more strict or less strict?

**Comment by msullivan** [comment]
I guess what I was thinking of is whether we should disallow something like `SELECT (Foo, (FOR x IN {Bar} UNION (SELECT (x, random()))))`. The `random()` is wrapped in explicit iteration, but still surrounded by multi-cardinality stuff, so a strict reading says we should ban it. 

That felt too aggessive to me in the morning but does not in the evening, so maybe that's fine. It would mean that we restrict the placement of calls to `random()` more than we restrict DML, though. Maybe that means we should restrict DML more too. INSERTs all have a volatile call in them, so those will automatically be restricted, and we should probably do DELETE and UPDATE while we're at it.

**Comment by 1st1** [comment]
>  The random() is wrapped in explicit iteration, but still surrounded by multi-cardinality stuff, so a strict reading says we should ban it.

Got it.

> That felt too aggessive to me in the morning but does not in the evening, so maybe that's fine.

Same. I think we should do a more aggressive version which we can always relax if we find it inconvenient for our users.

**Comment by msullivan** [comment]
- [ ] Implement correlation with FOR and clauses
- [ ] Disallow volatile calls we can't be sure about
