### ISSUE TITLE
Prohibit inheriting scalar types from more than one non-abstract scalar type

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#1790]
Currently:

```
select> CREATE SCALAR TYPE test::myint EXTENDING std::int64, std::str;
OK: CREATE
```

We have to prohibit this by enforcing that there must be exactly one base non-abstract scalar type in the ancestry of a new non-abstract scalar type.

**Comment by CodesInChaos** [comment]
Why that rule instead of requiring a single root scalar type?

**Comment by elprans** [comment]
> Why that rule instead of requiring a single root scalar type?

Because multiple inheritance from different abstract scalar types is useful.  For example:

```
CREATE SCALAR TYPE std::bigint EXTENDING std::anynumeric, std::anyint;
```
