### ISSUE TITLE
Rename `schema::Object.builtin` to `is_builtin`

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#1793]
We're using an `is_` prefix pretty consistently for bool flags. @vpetrovykh please fix this one and take a close look if we have other inconsistencies.

**Comment by vpetrovykh** [comment]
So there are also the following:
```
CREATE TYPE schema::Annotation EXTENDING schema::Object {
    CREATE PROPERTY inheritable -> std::bool;
};

CREATE TYPE schema::Constraint
    EXTENDING schema::CallableObject, schema::InheritingObject
{
    CREATE PROPERTY delegated -> std::bool;
    ...
};

CREATE ABSTRACT TYPE schema::Pointer
    EXTENDING
        schema::InheritingObject, schema::ConsistencySubject,
        schema::AnnotationSubject
{
    CREATE PROPERTY required -> std::bool;
    ...
};

CREATE TYPE schema::Function
    EXTENDING schema::CallableObject, schema::VolatilitySubject
{
    CREATE PROPERTY session_only -> std::bool {
        SET default := false;
    };
};
```

Do we convert all of these to use `is_` prefix, too?

**Comment by 1st1** [comment]
Can you list all bool flags with `is_` and without `is_` here in one bullet point list?

**Comment by vpetrovykh** [comment]
Sure, let's mark which ones we want to have `'is_` prefix (this is from finding all boolean properties in system library):
- [x] is_internal
- [x] is_abstract
- [x] is_final
- [x] is_owned
- [x] is_abstract
- [x] is_superuser
- [x] builtin
- [ ] inheritable
- [ ] delegated
- [ ] required
- [ ] session_only
- [ ] allow_implicit
- [ ] allow_assignment

**Comment by 1st1** [comment]
Oh, so it's almost a 50/50 split (I thought `is_` versions dominate the non-is ones.)

TBH, I don't like the `is_` prefix and I think we can instead drop `is_`. Looks like `abstract` and `final` are unreserved keywords so it shouldn't be a problem.

@elprans green light from you to drop is?

Another question, what is `is_internal`?

**Comment by vpetrovykh** [comment]
I suspect that it's mainly force of habit that makes me want to keep `required` without a prefix. Ultimately consistent `is_` for boolean flags appeals to my sense of strict formalism, as natural laguages are notoriously bad with everything boolean. I'd probably keep `allow_` prefixes as is, though as they seem to follow the same pattern as `is_`.

**Comment by vpetrovykh** [comment]
I think that `is_internal` flag marks parts of the schema that are needed, but shouldn't be exposed for one reason or another, isn't that exactly the distinction between all of shcema and user-introspectible schema that @elprans talked about?

```
victor> WITH MODULE schema
....... SELECT ObjectType {
....... name
....... } FILTER .is_internal;
{
  Object {name: 'schema::QualifiedObject'},
  Object {name: 'schema::ObjectFragment'},
  Object {name: 'schema::DerivableObject'},
  Object {name: 'schema::DerivableInheritingObject'},
  Object {name: 'schema::ReferencedObject'},
  Object {name: 'schema::ReferencedInheritingObject'},
  Object {name: 'schema::AnnotationValue'},
  Object {name: 'schema::InheritingType'},
  Object {name: 'schema::Collection'},
  Object {name: 'schema::CollectionExprAlias'},
  Object {name: 'schema::ArrayExprAlias'},
  Object {name: 'schema::TupleExprAlias'},
  Object {name: 'schema::ComputableRef'},
  Object {name: 'schema::IndexableSubject'},
}
```

**Comment by elprans** [comment]
> sn't that exactly the distinction between all of shcema and user-introspectible schema that @elprans talked about?

That's correct.

**Comment by vpetrovykh** [comment]
So to clarify what I mean by "my sense of formalism is in strong opposition of actual natural language use" I mean that personally consistent `is_` prefixes for `bool` flags seem appealing to me. However, having them as part of the names makes it awkward to write actual English sentences like "If the property in question is `is_required` ..." and forces re-wording like "If the property has an `is_required` flag set to `true` ...". In spoken English it's not a big deal, but in a written manual/example it becomes a bit awkward.

So `1 IF link.is_required ELSE 0` may look good in code, but it's awkward in docs. I think I just made a case against `is_` prefix...
