### ISSUE TITLE
SELECT 1e+100n IS decimal; gives {false}

### ISSUE THREAD

**Issue by Dhghomon** [edgedb/edgedb#1804]
- EdgeDB Version: Alpha 5
- OS Version: Windows 10 Ubuntu (Windows subsystem)

Steps to Reproduce:

1. `SELECT 1e+100n IS decimal;`

In https://edgedb.com/docs/datamodel/scalars/numeric/ this shows an output of {true} but I am getting false. 

- Removing the n does give {true} for IS float64, and
- Outright casting with <decimal> does turn it into one,

but n alone doesn't change it into a decimal.

**Comment by elprans** [comment]
The docs are wrong. `1e+100n` is not a `decimal`, it's a `bigint`.

**Comment by elprans** [comment]
To clarify, if you want a decimal literal, you must use a dot:

```
SELECT 1.0e+100n IS decimal;
{true}
```

**Comment by 1st1** [comment]
Yeah, this docs snippet was written before we introduced BigInt. @vpetrovykh please take a look if we have other inconsistencies with BigInt/Decimal in the docs.
