### ISSUE TITLE
Incorrect factoring fence in a link property + type interesection case

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#1822]
Currently, the following query would fail to compile:

```
    WITH
      MODULE schema
    SELECT Type {
      multi bases_list :=
        (SELECT Type[IS InheritingObject].bases {
          id
        } ORDER BY @index ASC).id

    };
```

Type intersections (`[IS Type]`) have `AT_MOST_ONE` cardinality, so we should forgo the refactoring fence enforcement on such paths if the immediate prefix of the intersection is visible above in the scope tree.

I made an attempt to fix this earlier in 4495543a496c75d92f8b3a411df1510e7751964c, but evidently when the expression is a path prefix it's still present.

**Comment by msullivan** [comment]
Fixed, apparently
