### ISSUE TITLE
Backlinks don't work in computables when the link is defined in an abstract class

### ISSUE THREAD

**Issue by jonaird** [edgedb/edgedb#1824]
- EdgeDB Version: Alpha 5
- OS Version: Mac OS 10.15.6

Steps to Reproduce:

Create a schema where a computable link uses a backlink for a link defined in an abstract class

For example the following schema:
```
abstract type Action{
    required property txid -> str{
        constraint exclusive;
    }
    required property timestamp -> int32;
    
        required link user -> User;

    
}

type Post extending Action{
  ...
}

type User {
  ...
  posts := .<user[IS Post];
}
```
produces the error: `InternalServerError: reference to an undefined item default::Post@user in default::User@posts`

If I don't include the IS intersect, i.e.:
```
type User {
  ...
  posts := .<user;
}
```
I get the following error: `SchemaError: cannot get 'name' value: item '3b64a89d-50f4-e418-acaa-c19c327e41d9' is not present in the schema <Schema gen:4106 at 0x7f857a0be820>`

**Comment by elprans** [comment]
Two bugs here:

1. SDL dependency sorter gets confused about inheritance.
2. Opaque union types produced by naked backlinks don't get added to the schema properly (I opened #1830).
