### ISSUE TITLE
Consider non-technical topic for example schema in docs

### ISSUE THREAD

**Issue by djrobstep** [edgedb/edgedb#184]
The example schema in the docs is for a github-style dev platform.

This is good for people who are experienced developers, but for the less experienced, it means trying to grok how github-like platforms *and* unfamiliar databases work, at the same time.

Perhaps a more familiar sample schema might be more accessible for less-experienced developers?

**Comment by ansarizafar** [comment]
A simple tutorial like https://www.apollographql.com/docs/tutorial/introduction.html would greatly help less experienced developers. We can also use https://scrimba.com/ for interactive tutorials and examples.

**Comment by fmoor** [comment]
Current examples are non-technical :tada:
