### ISSUE TITLE
Various errors when using local_time, local_date, and others

### ISSUE THREAD

**Issue by Dhghomon** [edgedb/edgedb#1845]
- EdgeDB Version: Alpha 5
- OS Version: Windows 10 (Ubuntu Windows subsystem)

I originally assumed that local_time and local_date couldn't be subtracted to get a <datetime> (because it didn't work for me) but noticed that the documentation says it should work:

https://www.edgedb.com/docs/edgeql/funcops/datetime

SELECT <cal::local_date>'2020-09-09' - <cal::local_date>'2020-09-01';
error: operator '-' cannot be applied to operands of type 'cal::local_date' and 'cal::local_date'

SELECT <cal::local_time>'12:09:09' - <cal::local_time>'10:09:09';
error: operator '-' cannot be applied to operands of type 'cal::local_time' and 'cal::local_time'

On top of this, a large number of code samples from the same page generate errors even when copied and pasted unchanged.

**- ISO8601 format errors** 

The first one is fixed by changing the format to ISO8601 but `1 day` is generates `Units bigger than days cannot be used for std::duration.`:
SELECT <datetime>'January 01 2019 UTC' -
  <duration>'1 day';
ERROR: InvalidValueError: invalid input syntax for type std::datetime: 'January 01 2019 UTC'
  Hint: Please use ISO8601 format. Alternatively "to_datetime" function provides custom formatting options.

SELECT <datetime>'January 01 2019 UTC' -
 <datetime>'January 02 2019 UTC';
ERROR: InvalidValueError: invalid input syntax for type std::datetime: 'January 01 2019 UTC'
  Hint: Please use ISO8601 format. Alternatively "to_datetime" function provides custom formatting options.
edgedb>                 

SELECT to_datetime(
  <cal::local_datetime>'January 1, 2019 12:00AM', 'HKT');
ERROR: InvalidValueError: invalid input syntax for type cal::local_datetime: 'January 1, 2019 12:00AM'
  Hint: Please use ISO8601 format. Alternatively "to_local_datetime" function provides custom formatting options.

 SELECT cal::to_local_time(
  <datetime>'December 31, 2018 10:00PM GMT+8', 'US/Pacific');
ERROR: InvalidValueError: invalid input syntax for type std::datetime: 'December 31, 2018 10:00PM GMT+8'
  Hint: Please use ISO8601 format. Alternatively "to_datetime" function provides custom formatting options.

SELECT cal::to_local_datetime(
<datetime>'December 31, 2018 10:00PM GMT+8', 'US/Central');
ERROR: InvalidValueError: invalid input syntax for type std::datetime: 'December 31, 2018 10:00PM GMT+8'
  Hint: Please use ISO8601 format. Alternatively "to_datetime" function provides custom formatting options.

**- Say function does not exist but solved by adding `cal::`**

SELECT time_get(
  <cal::local_time>'15:01:22.306916', 'minutes');
ERROR: InvalidReferenceError: function 'time_get' does not exist
(works as cal::time_get)

SELECT to_local_date('2018-05-07');

SELECT to_local_date('May 7th, 2018', 'Mon DDth, YYYY');

SELECT to_local_date(2018, 5, 7);

**- Say function does not exist, then generate ISO error after adding `cal::`**

SELECT date_get(
    <cal::local_date>'2018-05-07T15:01:22.306916',
    'century');
SELECT date_get(
    <cal::local_date>'2018-05-07T15:01:22.306916',
    'year');
SELECT date_get(
    <cal::local_date>'2018-05-07T15:01:22.306916',
    'month');
SELECT date_get(
    <cal::local_date>'2018-05-07T15:01:22.306916',
    'doy');
SELECT to_local_date(
  <datetime>'December 31, 2018 10:00PM GMT+8',
  'US/Central');

**Other errors:**

SELECT to_datetime('May 7th, 2018 15:01:22 +00',
               'Mon DDth, YYYY HH24:MI:SS, TZM');
ERROR: InvalidValueError: missing required time zone in format: 'Mon DDth, YYYY HH24:MI:SS, TZM'
  Hint: Use one or both of the following: 'TZH', 'TZM'

SELECT duration_to_seconds(<duration>'10 second 100 millis');
ERROR: InvalidValueError: invalid input syntax for type std::duration: "10 second 100 millis"

**Comment by 1st1** [comment]
@vpetrovykh please take a look

**Comment by TomFaulkner** [comment]
The first example mentioned on this issue is still in the documentation.

From OP:
> SELECT cal::local_date'2020-09-09' - cal::local_date'2020-09-01';

Docs
> local_date - local_date -> duration

https://github.com/edgedb/edgedb/blame/master/docs/stdlib/datetime.rst#L505

In practice the result seems to be an error:
```
edgedb> select {<cal::local_date>'2022-03-22' - <cal::local_date>'2000-03-21'};
error: InvalidTypeError: operator '-' cannot be applied to operands of type 'cal::local_date' and 'cal::local_date'
  ┌─ query:1:9
  │
1 │ select {<cal::local_date>'2022-03-22' - <cal::local_date>'2000-03-21'};
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Consider using an explicit type cast or a conversion function.
```
