### ISSUE TITLE
1_0a4.dump fails to restore on master (1.0a6.dev5102)

### ISSUE THREAD

**Issue by ambv** [edgedb/edgedb#1848]
File edgedb/tests/dumps/dump01/1_0a4.dump added in #1846 (generated from the `releases/1.0a4` branch) fails to restore on 1.0a6.dev5102 with a fairly black box error:
```
subprocess.CalledProcessError: Command '['edgedb', '--host', 'localhost', '--port', '58556', '--user', 'edgedb', '--password-from-stdin', '-d', 'TestDump01_1_0a4', 'restore', '/Users/ambv/Dropbox/Python/edgedb/tests/dumps/dump01/1_0a4.dump']' returned non-zero exit status 1
```

**Comment by ambv** [comment]
Running this manually lets me see the output which is:
```
Error: Error initiating restore protocol: ERROR: InternalServerError: unexpected object type in restore type descriptor: None
  Server traceback:
      Traceback (most recent call last):
        File "/Users/ambv/Dropbox/Python/edgedb/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
        File "/Users/ambv/Dropbox/Python/edgedb/edb/server/compiler/compiler.py", line 2136, in describe_database_restore
          raise AssertionError(
      AssertionError: unexpected object type in restore type descriptor: None
```

**Comment by ambv** [comment]
All other files restore fine (including the newly added 1_0a5).

**Comment by elprans** [comment]
Tracked this down: this is because the a4 dump is generated with this server version string: `1.0-alpha.5+dev.0.g6df187d3.d20200930`, which is actually parsed as a5 and so certain backwards-compatibility checks are not triggering.  In this case it's the change in name mangling that trips things up.

**Comment by ambv** [comment]
🤦🏻‍♂️ It's because I generated it from a remote branch (git switch origin/releases/1.0a4) and setuptools-scm bit us yet again. I'll recreate this in the morning.

**Comment by ambv** [comment]
The origin/ branch confused setuptools-scm but it also recognized the `gen-test-dumps` as a dirty directory, hence bumping the version. Magic all the way down.

**Comment by ambv** [comment]
```
SUCCESS
  tests ran: 1
```
