### ISSUE TITLE
Migrations going wrong

### ISSUE THREAD

**Issue by brassel** [edgedb/edgedb#1865]
- EdgeDB Version 1.0-alpha.5+g83a2a4fac.d20200826
- OS Version: Docker image a1594eed87be

Steps to Reproduce:

1. Walk through tutorial
2. Then make this create, populate, commit this migration:

    START MIGRATION TO { module default { type Movie { property month -> int64; } } };

3. query via graphql 

    { Movie { month } }

4. get result with data belonging to another field from tutorial

```
{
  "data": {
    "Movie": [
      {
        "month": 2017
      },
      {
        "month": null
      }
    ]
  }
}
```

5. Recreate, populate, commit migration from tutorial

```
START MIGRATION TO {
    module default {
         type Movie {
             required property title -> str;
             # the year of release
             property year -> int64;
             required link director -> Person;
             multi link actors -> Person;
        }
         type Person {
            required property first_name -> str;
           required property last_name -> str;
         }
     }
 };
```

6. get error

```
Error: ERROR: InternalServerError: unhandled error while calling interpret_backend_error()
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      RuntimeError: unhandled error while calling interpret_backend_error()
```

I think the result in 4 is already weird.

**Comment by brassel** [comment]
At least the weirdness is explained, after looking at the populated migration. There is an explicit "ALTER PROPERTY" there. Very smart!

**Comment by tailhook** [comment]
Looks like you've added required property to the object that already has some data. So while error message is definitely inadequate here, it would be error anyway.

**Comment by brassel** [comment]
So, do I understand this correct? 
You cannot migrate to an object with more properties?

Or is it just that you need to use that "DDL" and not this "SDL" language to execute such migrations?

**Comment by 1st1** [comment]
> So, do I understand this correct?
> You cannot migrate to an object with more properties?

You can easily migrate your type to a type with more "optional" properties. Adding a required property is tricky, because there's existing data you your DB that would lack that required property after the migration is applied.  E.g. consider

```
type User {
  required name: string;
}

# and you have this data in your DB:

   - User {name: 'Alice'}
```

If you migrate to

```
type User {
  required name: string;
  required email: string;
}
```

then the Alice object in the db would be in an invalid state, so we prohibit that.


@tailhook 
> Looks like you've added required property to the object that already has some data. So while error message is definitely inadequate here, it would be error anyway.

Right, this has to be fixed. cc @elprans @msullivan 

We also should add a clear strategy on how to add required properties/links.  Perhaps recommend adding a `default := ` to them, or explain that the migration should be performed in two stages both in the docs and in the tutorial:

1. Add the property as optional.
2. Write EdgeQL that would populate the property for all objects.
3. Migrate the property to be required.

**Comment by tailhook** [comment]
> We also should add a clear strategy on how to add required properties/links.

I think the original idea was that you can type the expression to populate the data once when creating migration. But it was implemented neither in server nor in CLI I think.

**Comment by tailhook** [comment]
Also while not mentioned here, I've got that internal server error when I were applying the migration. Until we have proper expression support we should disable (or at least warn) users of such changes at the `create-migration` stage.

**Comment by 1st1** [comment]
I'll be curious to hear @elprans thoughts here

**Comment by elprans** [comment]
Adding a new required property to an existing object type would require the user to provide an expression with which to populate the property for the existing objects, not dissimilar to the change of type where the new type is not automatically castable.  This isn't implemented yet, but is on an immediate todo list.

**Comment by brassel** [comment]
> would require the user to provide an expression with which to populate the property for the existing objects

This sounds great! What information could the expression use? Every piece of date in the migrated object or less or even more?

**Comment by elprans** [comment]
> What information could the expression use? Every piece of date in the migrated object or less or even more?

Equivalent to default expressions, i.e. an arbitrary query with access to the parent object.

**Comment by msullivan** [comment]
1. When using `POPULATE MIGRATION`, we now produce a proper error `MissingRequiredError: missing value for required link 'director' of object type 'default::Movie'`
2. When using the interactive migration flow, we will prompt for a fill expression to populate the field.

So I think we are good?

**Comment by msullivan** [comment]
And the first weird bit, where year turns into month, can also be prevented with the interactive prompting stuff, so I think that's good now too.
