### ISSUE TITLE
Issues with some role names

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#1879]
If current (unix) user is named `user` or when running `edgedb-server --default-database-user=user` I get this error:
```
2. asyncpg.exceptions.PostgresSyntaxError: syntax error at or near "user"

---- Source Context ----

    query, line 1, in query
        > SET ROLE user;
```

**Comment by tailhook** [comment]
Should we now drop creating role that matches unix user at all and deprecate `--default-database-user`? As we now agreed to use default `edgedb` user and write that into a credentials file.

**Comment by elprans** [comment]
> Should we now drop creating role that matches unix user at all 

Yes.

> If current (unix) user is named `user` or when running `edgedb-server --default-database-user=user` I get this error:

This is due to lack of proper quoting at SQL level.  Should be easy to fix.
