### ISSUE TITLE
min/max trigger ISE when used on unsupported types

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#1920]
`std::min`/`std::max` nominally take `anytype` but the backing SQL function doesn't support `uuids` or tuples, among other things;

`SELECT min(Object.id);`, `SELECT min(Object)` and `SELECT min({(1,2), (3,4)});` all produce ISEs.

We should at least properly disallow the unsupported ones but since they have working less than operators it would be best if we could support it actually. (But I'm not sure if that is plausible.)

(I think there might be other similar things, but I couldn't find more at a quick glance.)

**Comment by elprans** [comment]
From PostgreSQL docs:

> Available for any numeric, string, date/time, or enum type, as well as inet, interval, money, oid, pg_lsn, tid, and arrays of any of these types.

@vpetrovykh, please change the definition of `min` and `max` to the appropriate subset of the above and check if we have other instances of overly generic aggregates that have no basis in Postgres.
