### ISSUE TITLE
ISE when doing `SET` on an invalid proprety

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#1936]
`CREATE TYPE Lol { SET ha := "crash"; };`
produces
```
ERROR: InternalServerError: schema class 'ObjectType' has no field 'ha'
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
```
Same story with migrations;

The error does, tbh, make it pretty clear what the problem is, but we ought to produce a real error.

**Comment by 1st1** [comment]
`errors.InvalidDefinitionError` should be good enough
