### ISSUE TITLE
Unique constraint on abstract type doesn't work?

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#1938]
Here is the error:
```
edgedb> CREATE ABSTRACT TYPE Base { create property test1 -> str; create property test2 -> str; create constraint exclusive on ((.test1, .test2));};
OK: CREATE
edgedb> CREATE TYPE Test2 EXTENDING Base;
error: could not resolve partial path
  ┌─ query:1:28
  │
1 │ CREATE TYPE Test2 EXTENDING Base;
  │                            ^^^^^^^ error

edgedb> CREATE TYPE Test2 EXTENDING default::Base;
error: could not resolve partial path
  ┌─ query:1:28
  │
1 │ CREATE TYPE Test2 EXTENDING default::Base;
  │                            ^^^^^^^ error
```
Also note that error message is a way off, so I guess it refers to a constraint definition rather than the DDL here.

There are three possible action points:
1. Fix constraint to work
2. Or disable some kinds of constraints in abstract types (at least temporarily)
3. And figure out what's wrong with the error position and how we can fix that (I think we need to ship actual source code of the expression via error message to correctly point to the error).

**Update:** when using `create-migration` error pops up only on `migrate` the migration is created without errors.

**Comment by 1st1** [comment]
FWIW in this case I think you wanted to use a ["delegated constraint"](https://www.edgedb.com/docs/edgeql/ddl/constraints#create-constraint).

@elprans I think it's an error we allow non-delegated constraints to be defined on abstract types, right?

**Comment by elprans** [comment]
I think non-delegated constraints on abstract types are a valid use case, albeit an uncommon one.  A non-delegated `exclusive` constraint on an abstract parent means that a value must be unique across all descendants as opposed to within a subset of each individual descendant type.

The original error should be a relatively easy fix.

**Comment by tailhook** [comment]
> A non-delegated exclusive constraint on an abstract parent means that a value must be unique across all descendants as opposed to within a subset of each individual descendant type.

For my use case it's wasn't important. But I did know nothing about delegated constraints. So if for any reason you decide that non-delegated constraint is hard to be implemented in short-term (or at all), we should error out on creation of constraint and give a hint about delegated one.

**Comment by msullivan** [comment]
To be clear, the work item right now is just fixing the error message? Or is it actually supporting this?

**Comment by msullivan** [comment]
Oh, I guess it hopefully won't be hard to fix since this works for properties.

**Comment by elprans** [comment]
This is a bug in constraint inheritance, which needs to be fixed.
