### ISSUE TITLE
Unless conflict does not work on two-field indexes?

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#1939]
I get this error with `UNLESS CONFLICT ON (.field1, .field)`:
```
edgedb.errors.QueryError: ON CONFLICT argument must be a property
```
And this error on `UNLESS CONFLICT ON .field1, .field2`:
```
edgedb.errors.EdgeQLSyntaxError: Unexpected ','
```
I.e. it look like not a bug, but just syntactically incorrect

**Comment by Mulugruntz** [comment]
In the meantime, what's the official recommendation?
I have `constraint exclusive on ((.field1, .field2, .field3));` 
For now, that's the only index I have on this table.
But even if I do `UNLESS CONFLICT ON .field1`, it fails with
`edgedb.errors.QueryError: UNLESS CONFLICT property must have a single exclusive constraint`

**Comment by tailhook** [comment]
I'm using `try...except`:
```
try:
    await pool.query("INSERT ...")
except ConstraintViolationError:
    await pool.query("UPDATE...")
```
This might be wrapped in transaction or a loop if object can be deleted in the meantime. Also note: that this relies on the fact that this is the only constraint can be violated which is exclusivity on respective index. But in your case it might be more complex.

**Comment by Mulugruntz** [comment]
Thanks for the suggestion. I'll probably do that in the meantime.

Too bad, as I'm doing bulk inserts.

```
FOR x IN {
    json_array_unpack(<json>$data)
}
UNION (
    INSERT MyTable {
        # ...
    }
    UNLESS CONFLICT ON (.field1, .field2, .field3)
    ELSE (
        UPDATE MyTable SET {
            # ...
        }
    )
);
```

So if it fails once, I won't know where it would have failed.

**Comment by msullivan** [comment]
Oh, I had meant to update this: we don't yet support a direct syntax for this, but there is a simple workaround: use a computed property.

So with a schema like
```
type Entry {                                                              
    required property field1 -> str;                                      
    required property field2 -> int64;                                    
    required property field3 -> bool;                                     
    property key {                                                        
        using ((.field1, .field2));                                       
        constraint exclusive;                                             
    };                                                                    
}
```

You can do queries like
```
INSERT Entry { field1 := "test", field2 := 42, field3 := false } 
UNLESS CONFLICT ON (.key) ELSE (UPDATE Entry SET { field3 := true });
```

**Comment by Mulugruntz** [comment]
@msullivan Thanks for your proposition. However, when I tried it I got the following error message:
```
edgedb.errors.InvalidPropertyTargetError: invalid property type: expected a scalar type, or a scalar collection, got collection 'tuple<default::SubTable, default::MyEnum, std::datetime>'
```

I think it comes from `default::SubTable` being a type and not a scalar type.
Is there another trick around it?

**Comment by msullivan** [comment]
Oh, yeah, darn, that is going to be more of a pain.

I think you can probably make something work by duplicating the `id` of the target object in the source table, and using that in your constraint. That should work but it's super unsatisfying, since you shouldn't ever have to think about `id`s in edgedb!

**Comment by Mulugruntz** [comment]
Seems like a  pain :-(.

Thanks @msullivan . Do we know when a tuple `UNLESS CONFLICT ON` will be on the roadmap?

**Comment by elprans** [comment]
@Mulugruntz, this is currently set for the 1.0 milestone, but chances are we can get support for matching constraints with expressions in `UNLESS CONFLICT` into the next beta.

**Comment by Mulugruntz** [comment]
Thanks for your hard work guys!

Hopefully in the meantime, @msullivan 's solution will be useful for other people. :-)
