### ISSUE TITLE
In dev build, `edgedb` can't connect to default `edb server`

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#1945]
- OS Version: Ubuntu 20.04

1. Make a fresh venv, and follow the https://www.edgedb.com/docs/internals/dev instructions
2. `edb server`
3. `edgedb`

`Error: Error authenticating: ERROR: AuthenticationError: database "sully" does not exist`

Also:
`$ edgedb -d edgedb`
`Error: Error authenticating: ERROR: AuthenticationError: authentication failed`

**Comment by tailhook** [comment]
Fixed in edgedb/edgedb-rust@ad5a354 and edgedb/edgedb-cli#189

**Comment by msullivan** [comment]
I still observe this problem. Am I doing something wrong?

**Comment by tailhook** [comment]
Should have been fixed in edgedb/edgedb-cli#190. Please reopen if you have more issues.
