### ISSUE TITLE
std::str_lpad etc. don't seem to be deprecated yet

### ISSUE THREAD

**Issue by Dhghomon** [edgedb/edgedb#1972]
- EdgeDB Version: 1.0a6.dev5056+g4fb6cf00-2020090700~bionic.nightly (nightly)
- OS Version: Windows 10 (Ubuntu subsystem)

Looks like none of these have been deprecated yet.

Steps to Reproduce:

1. None of these work:

SELECT str_pad_start('nice', 10);
SELECT str_pad_end('nice', 10);
SELECT str_trim_start('nice', 'n');
SELECT str_trim_end('nice', 'e');

While the old function names are still there:

SELECT str_lpad('nice', 10);
SELECT str_rpad('nice', 10);
SELECT str_ltrim('nice', 'n');
SELECT str_rtrim('nice', 'e');

**Comment by 1st1** [comment]
```
EdgeDB 1.0-alpha.7+dev.5194.g82532a78d (repl 1.0.0-alpha.6)
Type "\?" for help.
edgedb> SELECT str_pad_start('nice', 10);
{'      nice'}
edgedb> SELECT str_lpad('nice', 10);
{'      nice'}
edgedb>
```

Hm, works for me. The EdgeDB version you stated (`EdgeDB Version: 1.0a6.dev5056+g4fb6cf00-2020090700~bionic.nightly (nightly)`) seems to be a nightly build. Can you try to install the latest alpha6?

**Comment by 1st1** [comment]
> While the old function names are still there:

They will be there until 1.0 I think.

**Comment by Dhghomon** [comment]
Okay, good to hear - looks like it's just my nightly build and works for you and others so nothing to fix.
