### ISSUE TITLE
ISE: attempted to insert multiple rows in single INSERT statement

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#1973]
I get this error:
```
edgedb.errors.InternalServerError: duplicate key value violates unique constraint "21873252-2474-11eb-884d-fd1173a232f5_pkey"
```
When trying to insert duplicate value. The issues are:
1. It shouldn't be InternalServerError
2. I want to know what constraint I'm violating

EdgeDB version: 1.0-alpha.6+g152b06e73.d20201008

**Comment by tailhook** [comment]
Well, actually the problem is a bit deeper. This is a primary key. So does it creates a duplicate `id` for the object? (Obviously I don't pass `id` as that would be rejected by a complier).

**Comment by tailhook** [comment]
Okay the issue is, the query compiles to `INSERT (..) (SELECT(...))` and that select returns two rows with the single id. All dependencies should contain a single row, so I'm not sure where second row comes from.

**Comment by tailhook** [comment]
> Okay the issue is, the query compiles to `INSERT (..) (SELECT(...))` and that select returns two rows with the single id. All dependencies should contain a single row, so I'm not sure where second row comes from.

Hm, I'm wrong on this point a bit. It's like:
```
INSERT { link_value := (SELECT LinkTarget FILTER ...) }
```
And that `SELECT LinkTarget` returns two rows.

So while the query is erroneous the error should either be compilation error: `query could return more than one row` or earlier runtime error `subquery SELECT LinkTarget .. returned more that one row`

**Comment by msullivan** [comment]
This does not really have enough information to investigate. I'm guessing the issue was that the subquery managed to return something that wasn't a proper set, but we now do multiplicity inference that should prevent that? Reopen with some more information if I'm wrong?
