### ISSUE TITLE
`ALTER .. SET default := ...` works unexpectedly.

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#1977]
- EdgeDB Version: 1-alpha.6

Steps to Reproduce:
I had a schema:
```
type Object {
    optional property prop1 -> str; 
}
```
Now I change it to:
```
type Object {
    required property prop1 -> str {
        default := 'something';
    }; 
}
```
Migration is generated properly:
```
  ALTER TYPE default::Object {
      ALTER PROPERTY prop1 {
        SET default := 'something';
        SET REQUIRED;
      };
  };
```
But applying it doesn't work:
```
ERROR: MissingRequiredError: missing value for required property default::Object.prop1
```
If I apply just `default` without `SET REQUIRED` then I still see empty set `prop1: {}` values in the database.

Is this how `default` is supposed to work? So the only workaround is the data migration? Note: if the latter is the case then `SET REQUIRED` should not be "safe" migration (i.e. it shouldn't apply in `--non-interactive` mode and should ask for an expression, or at least "do you really know that there aren't any inserted objects with empty value in this field?")

**Comment by elprans** [comment]
The `default` is currently interpreted as "the default value for newly inserted objects", it's not used to populate existing values.  The `SET REQUIRED` operation should ask for an expression to use (with an option to use the `default`).

**Comment by tailhook** [comment]
This looks like fixed.
