### ISSUE TITLE
ISE with some type-filtered reverse pointers

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#1986]
`SELECT schema::Array {name, incoming := schema::Array.<target[IS schema::Link]};`
crashes with
```
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/astutils.py", line 253, in find_column_in_subselect_rvar
          raise RuntimeError(f'cannot find {name!r} in {rvar} output')
      RuntimeError: cannot find 'c9a357e0-2aa0-11eb-8146-1b095e5df57b' in <pg.RangeSubselect at 0x7f1e82f79af0> output
```

`SELECT schema::Array {name, incoming := .<type[IS schema::TupleElement]};` works, but
`SELECT schema::Array {name, incoming := .<type[IS schema::Parameter]};` doesn't.

**Comment by elprans** [comment]
#1887 looks similar

**Comment by msullivan** [comment]
I think the issue is caused by the type rewriting logic from `7f29af4c7c0629f2ff03c99a501ece0bc85c5d85`. It seems like the issue stems from failing to find the column in the CTE for a filtered type (when we would be able to find it in just a Relation)

**Comment by msullivan** [comment]
Long fixed
