### ISSUE TITLE
Can't set computable property for abstract links

### ISSUE THREAD

**Issue by adriangb** [edgedb/edgedb#2003]
- EdgeDB Version: Alpha 6
- OS Version: Official docker container

It seems that computables that refer to other link properties do not work in SDL:
```
START MIGRATION TO {
    module default {
        abstract link my_link {
            property prop := (
                1
            );
        }
    }
};
```
The equivalent for types works just fine:
```
START MIGRATION TO {
    module default {
        type MyType {
            property prop := (
                1
            );
        }
    }
};
```

All testing done on a fresh (DROP -> CREATE) database.

**Comment by msullivan** [comment]
It looks like computable link properties just don't work ever.

**Comment by adriangb** [comment]
Thanks for the quick fix!
