### ISSUE TITLE
Shapes rooted at the same object can mask each other.

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#201]
Two different shapes rooted at the same object mask each other if they appear in the same scope (such as sibling tuple elements).

```
WITH MODULE test
SELECT _ := (User { name }, User { id });
```

See `test_edgeql_scope_tuple_03`.

**Comment by elprans** [comment]
This is fixed in d5d9b01a087b6c65506b60079873572eafa7ca9f
