### ISSUE TITLE
No way to supply --runstate-dir on edgedb init

### ISSUE THREAD

**Issue by isidentical** [edgedb/edgedb#2069]
When trying to setup an EdgeDB instance on a limited environment; EdgeDB throws this warnings,
```
$ ~/.edgedb/bin/edgedb server init --nightly default
...
2020-12-20T11:44:34.0903426Z CRITICAL 6748 2020-12-20 11:44:34,089 edb.server: cannot create the runstate directory: '/run/user/1001' does not exist; please use --runstate-dir to specify the correct location
```
but I couldn't find how to pass this as an option;
```
 $ ~/.edgedb/bin/edgedb server init --runstate-dir x --nightly test
error: Found argument '--runstate-dir' which wasn't expected, or isn't valid in this context

If you tried to supply `--runstate-dir` as a PATTERN use `-- --runstate-dir`

USAGE:
    edgedb server init [FLAGS] [OPTIONS] <name>

For more information try --help
```
or
```
 $ ~/.edgedb/bin/edgedb --runstate-dir server init x --nightly test 
error: Found argument '--runstate-dir' which wasn't expected, or isn't valid in this context

If you tried to supply `--runstate-dir` as a PATTERN use `-- --runstate-dir`

USAGE:
    edgedb [FLAGS] [OPTIONS] [SUBCOMMAND]

For more information try --help
```

**Comment by NatureGeorge** [comment]
same issue in WSL2 (win10) for `1.0a7-2020122418~focal`

```bash
(base) zzf@LAPTOP-MGPQT3HG:~$ edgedb server init myinstance
┌──────────────────────┬───────────────────────────────────────────────┐
│ Instance Name        │ myinstance                                    │
│ Mode                 │ User Service                                  │
│ Data Directory       │ /home/zzf/.local/share/edgedb/data/myinstance │
│ Credentials Path     │ /home/zzf/.edgedb/credentials/myinstance.json │
│ Database Server Port │ 10701                                         │
│ Default User         │ edgedb                                        │
│ Default Database     │ edgedb                                        │
│ EdgeDB Version       │ 1.0a7-2020122418~focal                        │
└──────────────────────┴───────────────────────────────────────────────┘
WARNING 133 2020-12-25 22:02:52,021 py.warnings: /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/server/main.py:598: DeprecationWarning: Option `--bootstrap` is deprecated, use `--bootstrap-only`
  warnings.warn(

Failed to connect to bus: No such file or directory
WARNING 205 2020-12-25 22:03:09,464 py.warnings: /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/server/main.py:606: DeprecationWarning: Option `--default-database-user` is deprecated. Role `edgedb` is always created and no role named after unix user is created any more.
  warnings.warn(

WARNING 205 2020-12-25 22:03:09,464 py.warnings: /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/server/main.py:621: DeprecationWarning: Option `--default-database` is deprecated. Database `edgedb` is always created and no database named after unix user is created any more.
  warnings.warn(

INFO 205 2020-12-25 22:03:09,465 edb.server: EdgeDB server (1.0-alpha.7+gd5b9e9025.d20201224) starting.
CRITICAL 205 2020-12-25 22:03:10,430 edb.server: cannot create the runstate directory: '/run/user/1000' does not exist; please use --runstate-dir to specify the correct location
[2020-12-25T14:03:39Z ERROR edgedb::server::init] Bootstrap error, cleaning up...
edgedb error: cannot bootstrap /home/zzf/.local/share/edgedb/data/myinstance: cannot establish connection for 30s: No such file or directory (os error 2)
```

**Comment by 1st1** [comment]
cc @tailhook

**Comment by tailhook** [comment]
Just set `XDG_RUNTIME_DIR=/something` in your environment. This is a common way to do that on Linux.

That said, it it weird that your distributions don't provide a valid `XDG_RUNTIME_DIR`. On recent Ubuntu `/run/user/$USERID` is provided by systemd by default. So perhaps you have disabled some parts of systemd or use different way to login. (Do you use `sudo -u <username>`?)

On our side, we can probably check the directory earlier, in CLI, and make proper suggestion.

But anyway, providing valid `XDG_RUNTIME_DIR` would probably help not just edgedb but potentially other programs too.

**Comment by elprans** [comment]
@tailhook, perhaps fallback to using the datadir as runstate dir when `XDG_RUNTIME_DIR` is unset?

**Comment by tailhook** [comment]
> @tailhook, perhaps fallback to using the datadir as runstate dir when `XDG_RUNTIME_DIR` is unset?

Hm, I've thought that default is provided by spec, but it's not, so maybe us picking that directory is wrong.

I'm not sure that datadir is a good choice, though. I think datadir should eventually be overridable at `init` stage and then `edgdb -Ixxx --admin` or `edgdb -Ixxx reset-password` may be unable to find that directory.

So we can probably fallback to `~/.edgedb/run/instance_name` as we already do in macos?

**Comment by tailhook** [comment]
By the way, looking at original issue: https://github.com/reizio/reiz.io/pull/24 (/cc @isidentical )

1. You may use `edgedb/setup-edgedb` github action to install edgedb
2. Not having `XDG_RUNTIME_DIR` means you don't have systemd user daemon too, as far as I remember. You may try:
    ```
    edgedb init --start-conf=manual default
    edgedb server start --foreground default
    ```
    (i.e. running server as a subprocess rather than service and backgrounding via shell)
3. We may want to create `edgedb/run-edgedb` github action to run a server (and configure credentials)

**Comment by isidentical** [comment]
Thanks for the tips @tailhook, it would be amazing to see the 3rd option happening. Even if not, I'll apply your suggestions in the weekend, and give it a shot in that way (I was actually thinking about custom runners, but this would definietly be easier for me.)

**Comment by 1st1** [comment]
> We may want to create edgedb/run-edgedb github action to run a server (and configure credentials)

@elprans what do you think about that?

**Comment by elprans** [comment]
I think we can add the "start the server" bit as a parameter to "setup-edgedb".

**Comment by tailhook** [comment]
> I think we can add the "start the server" bit as a parameter to "setup-edgedb".

That's also an option. I've thought that it would be easier to run multiple instances with a separate action, but multiple `setup-edgedb` should be handled fine too. Probably specifying instance name should be enough to start a server.

**Comment by isidentical** [comment]
After checking out some code from JS/Go drivers of edgedb (and learning things like `--temp-dir`/`--echo-runtime-info`), with setup-edgedb everything works well for me (even without touching any sort of runstate_dir logic) https://github.com/reizio/reiz.io/blob/ad7fefb2be42f1c73672cbf7d41200a6f5dd2f25/.github/workflows/test.yml#L11-L42

**Comment by tailhook** [comment]
Okay, here is the problem with defaulting `XDG_RUNTIME_DIR` to something other than systemd default that is currently set:
1. `systemd --user` daemon requires `XDG_RUNTIME_DIR` and it is usually set by [`pam_systemd`](https://www.freedesktop.org/software/systemd/man/pam_systemd.html#%24XDG_RUNTIME_DIR)
2. So for bootstrap we can use any dir, but `init` will fail anyway when trying to contact systemd (at least in this case where systemd is not running, but XDG_RUNTIME_DIR is used by `systemctl --user` itself)
3. If bootstrap went well, and `systemd --user` is actually running (although perhaps started by different user session), any other command will be unable to contact edgedb (and perhaps systemd) if we put runtime dir in any different dir from what was used for `systemd --user`. The latter dir is `/run/user/<user_id>` on most systems unless they have very arcane configuration, and this is the dir we default to for how.

So we can either error out on non-existing `XDG_RUNTIME_DIR` earlier, to make error more clear. Or can check `systemctl --user status` or something to find out that systemd is not running early and suggest `--start-conf=manual` (or both?)

**Comment by tailhook** [comment]
We should also put a doc page on how to run edgedb in CI

**Comment by elprans** [comment]
> or both

Let's do both.

**Comment by haikyuu** [comment]
I'm hitting this issue as well.

```
Found `edgedb.toml` in `/home/runner/work/perfect-stack/perfect-stack`
Initializing project...
Checking EdgeDB versions...
┌────────────────────────┬───────────────────────────────────────────────────────────┐
│ Project directory      │ /home/runner/work/perfect-stack/perfect-stack             │
│ Project config         │ /home/runner/work/perfect-stack/perfect-stack/edgedb.toml │
│ Schema dir (non-empty) │ /home/runner/work/perfect-stack/perfect-stack/dbschema    │
│ Installation method    │ Native System Package                                     │
│ Version                │ 1.0b3+gb4f275394.cv202108020000-202108152250~focal        │
│ Instance name          │ perfect_stack                                             │
└────────────────────────┴───────────────────────────────────────────────────────────┘
Initializing EdgeDB instance...
2021-09-07 10:10:54.626 UTC [3920] LOG:  starting PostgreSQL 12.7 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
2021-09-07 10:10:54.627 UTC [3920] LOG:  listening on Unix socket "/home/runner/.local/share/edgedb/data/perfect_stack/.s.PGSQL.5432"
2021-09-07 10:10:54.643 UTC [3921] LOG:  database system was shut down at 2021-09-07 10:10:54 UTC
2021-09-07 10:10:54.647 UTC [3920] LOG:  database system is ready to accept connections
2021-09-07 10:10:59.739 UTC [3920] LOG:  received fast shutdown request
2021-09-07 10:10:59.740 UTC [3920] LOG:  aborting any active transactions
2021-09-07 10:10:59.742 UTC [3920] LOG:  background worker "logical replication launcher" (PID 3927) exited with exit code 1
2021-09-07 10:10:59.742 UTC [3922] LOG:  shutting down
2021-09-07 10:10:59.763 UTC [3920] LOG:  database system is shut down
2021-09-07 10:10:59.850 UTC [3941] LOG:  starting PostgreSQL 12.7 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
2021-09-07 10:10:59.851 UTC [3941] LOG:  listening on Unix socket "/home/runner/.local/share/edgedb/data/perfect_stack/.s.PGSQL.5432"
2021-09-07 10:10:59.872 UTC [3942] LOG:  database system was shut down at 2021-09-07 10:10:59 UTC
2021-09-07 10:10:59.875 UTC [3941] LOG:  database system is ready to accept connections
2021-09-07 10:11:00.866 UTC [3941] LOG:  received fast shutdown request
2021-09-07 10:11:00.870 UTC [3941] LOG:  aborting any active transactions
2021-09-07 10:11:00.873 UTC [3941] LOG:  background worker "logical replication launcher" (PID 3948) exited with exit code 1
2021-09-07 10:11:00.873 UTC [3943] LOG:  shutting down
2021-09-07 10:11:00.894 UTC [3941] LOG:  database system is shut down
Failed to connect to bus: No such file or directory
INFO 3955 2021-09-07 10:11:02,994 edb.server: EdgeDB server (instance-name: 'perfect_stack', version: 1.0-beta.3+gb4f275394.cv202108020000) is starting.
INFO 3955 2021-09-07 10:11:04,071 edb.server: Using 69 max backend connections based on total memory.
CRITICAL 3955 2021-09-07 10:11:04,080 edb.server: cannot create the runstate directory: '/run/user/1001' does not exist; please use --runstate-dir to specify the correct location
[2021-09-07T10:11:32Z ERROR edgedb::server::create] Bootstrap error, cleaning up...
edgedb error: cannot bootstrap /home/runner/.local/share/edgedb/data/perfect_stack: cannot establish connection for 30s: No such file or directory (os error 2)
Error: Process completed with exit code 1.
```

Here is the link to the github action itself https://github.com/haikyuu/perfect-stack/runs/3532504913

**Comment by haikyuu** [comment]
Is there a workaround for now?

I am using the same CI config as `edgedb-js` repo.

**Comment by tailhook** [comment]
@haikyuu two posible workarounds:
1. Do as [edgedb-js](https://github.com/edgedb/edgedb-js/blob/master/test/globalSetup.ts#L59-L175) (temporary runtime dir, and propagate it to the actual test manually)
2. Set `env: {XDG_RUNTIME_DIR: "${{ runner.temp }}/edgedb"}` in the environment, covering all actions that touch edgedb and client apps (e.g. root of your workflow or a job)

**Comment by msullivan** [comment]
I don't think this command exists anymore?
I'm going to close this issue.
Feel free to reopen if I've missed something important.
