### ISSUE TITLE
Migrations fail after dump/restore cycle

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#2071]
- EdgeDB Version: 1-alpha.6 -> 1-alpha.7

Steps to Reproduce:

1. Use `edgedb dump --all` for the database containing migrations
2. Use `edgedb restore --all` for that dump

The result of `edgedb show-status` is the following:
```
Database is empty. While there are 15 migrations on the filesystem. Run `edgedb migrate` to apply
```
While schema is there. `edgedb migrate` fails with:
```
edgedb error: ERROR: SchemaError: ObjectType <QualName default::Type1> is already present in the schema <FlatSchema gen:2 at 0x7f317b5c0550>
```
(which is kinda expected). And I'm not sure if there is any workaround to reanimate this kind of schema.

**Comment by elprans** [comment]
Please attach the original schema.

**Comment by tailhook** [comment]
Does the bug need specific schema to be triggered? At least the schema from #2057 triggers this bug. But I guess any one would do. If it only fails on some schemas, please make sure that it at least crashes if it fails to load migrations instead of silently skipping them (but I guess they aren't present in the dump).

**Comment by elprans** [comment]
Oh, sorry, I misread your initial message.  This is, indeed, because we omit `Migration` objects from `DESCRIBE` currently.  Should be easy enough to fix (and backpatch).

**Comment by elprans** [comment]
Fixed.
