### ISSUE TITLE
Introspect queries produces an error

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb#2098]
Introspecting queries is quite limited at the moment. [See discussion](https://github.com/edgedb/edgedb/discussions/2093#discussioncomment-257331)

```
SELECT INTROSPECT
.......   typeof (select shop::Category{id, description} LIMIT 1);
error: cannot introspect transient type variant
  ┌─ query:2:3
  │
2 │   typeof (select shop::Category{id, description} LIMIT 1);
  │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ error

```

The ability to introspect a query might come in very handy for multiple use cases like generating language specific types for a queries. Typescript for example.

**Comment by 1st1** [comment]
FWIW it's possible to introspect the exact return type of any query via preparing it at the [protocol level](https://www.edgedb.com/docs/internals/protocol/overview#granular-flow). Our JS driver has some private APIs to do that.

**Comment by haikyuu** [comment]
Good to know @1st1 I think that would be good for my use case. As I'm planning to make a little type generator that does the following:
- get all `EdgeQL` queries in the project
- generate a `queries.d.ts` file that contains the return types of these queries

I scanned edgedb-js repo to see where query preparation happens, but I couldn't find any lead. Can you show me where to look or even better an example?

Thank you

**Comment by 1st1** [comment]
It's basically this: https://github.com/edgedb/edgedb-js/blob/512760521477118a9890dea0c395608bbda443c5/src/client.ts#L1194-L1253

Note that this isn't final API by any means and will likely change.

**Comment by jaclarke** [comment]
For an example there's this: https://github.com/jaclarke/edgedb-js/commit/b35d0d25606b8b7b87bbdf3996086dd6dade261f

It quite an old fork though, and I think there's been protocol changes since, so I'm not sure if it still works. Also it modifies the internals a bit, so it's probably not a recommended (or officially supported) way of doing it.

**Comment by msullivan** [comment]
I don't think this is really a bug
