### ISSUE TITLE
Can't reference user defined functions in constraints

### ISSUE THREAD

**Issue by adriangb** [edgedb/edgedb#2106]
On nightly docker (``), I can't create a constraints calling simple user defined functions:

```
CREATE TYPE MyType {
};
CREATE FUNCTION test_fun(arg: MyType) -> int64 {
    USING( SELECT 1 );
};
ALTER TYPE MyType {
    CREATE CONSTRAINT expression ON (
        test_fun(__subject__) < 2
    );
};
```

The function works just fine:

```
SELECT test_fun((INSERT MyType));
{1}
```

And so does using std functions in constraints:

```
ALTER TYPE MyType {
    CREATE CONSTRAINT expression ON (
        to_float32('1') < 2
    );
};
```

With the exception of aggregation functions, for some reason:

```
ALTER TYPE MyType {
    CREATE CONSTRAINT expression ON (
        count({1}) < 2
    );
};
edb.errors.InternalServerError: aggregate functions are not allowed in check constraints
```

**Comment by elprans** [comment]
Aggregate functions cannot be used in constraints.  This is a PostgreSQL limitation.

**Comment by adriangb** [comment]
> Aggregate functions cannot be used in constraints. This is a PostgreSQL limitation.

Is the limitation that no aggregate functions can be called/used within a constraint, or that they can't be used directly? For example, could I have a function:

```
type ThingContainer {
    multi link things -> Thing;
    constraint expression on (
        count_things(__subject__) < 2
    );
}
function count_things(thing: Thing) -> int64 {
   using(count(thing.things));
}
```

**Comment by elprans** [comment]
The limitation is not syntactic, it's functional and so wrapping will not help.  To use arbitrary queries a trigger must be used instead (although we don't expose triggers yet).  Triggers are notably more expensive than regular constraints, though.

**Comment by adriangb** [comment]
Got it, thank you very much for the response!
