### ISSUE TITLE
Error initializing server

### ISSUE THREAD

**Issue by puchm** [edgedb/edgedb#2153]
- EdgeDB Version: 1-alpha5
- OS Version: Docker container (edgedb/edgedb)

Steps to Reproduce:

1. I tried setting up an EdgeDB instance in a docker container using this Dockerfile:
```Docker
FROM edgedb/edgedb

EXPOSE 5656

USER daemon

RUN edgedb server upgrade
RUN edgedb server init
```
2. I am getting the following error:
```
#6 0.815 [2021-01-26T08:10:21Z ERROR edgedb::server::init] Bootstrap error, cleaning up...
#6 0.815 Error: failed to clean up /usr/sbin/.local/share/edgedb/data/default: No such file or directory (os error 2)
```
3. I am not sure if I am doing this correctly because I am also quite new to Docker. I switched the user to daemon because it had trouble when run as root and daemon was apparently a user that was already created. What I want to do is I want to create a Docker container which sets up and runs my database.

Am I doing something wrong?

**Comment by elprans** [comment]
The correct way to set up an EdgeDB to run in a docker container is to use the `edgedb server` commands on the _host_:

```
$ edgedb server install --method=docker
```

**Comment by puchm** [comment]
Thanks. I tried it but I am still doing something wrong. I decided to go with Postgres for now as the database is not my main focus point right now. I might give it another try if your docs are a bit more detailed.

**Comment by 1st1** [comment]
That's very unfortunate. Could you at least share the error log if any, or the steps to repro, with us?

**Comment by puchm** [comment]
Sure, the Dockerfile I am using is:
```
FROM edgedb/edgedb

EXPOSE 5656

USER daemon

RUN edgedb server install --method=docker
```

I am building with `docker build -t edgedb_test .`.

The error is:
```
> [2/2] RUN edgedb server install --method=docker:
#5 1.078 edgedb error: No installation method chosen, add:
#5 1.078  * --method=package -- to install Debian native package (recommended)
#5 1.078  * Note: Error initializing Docker method. Command-line tool: not found, docker 
socket: not found
#5 1.078 or run `edgedb server install --interactive` and follow instructions
------
executor failed running [/bin/bash -c edgedb server install --method=docker]: exit code: 
1
```

The real issue is that I think that the documentation doesn't tell you a lot, especially about the setup. If I understand this correctly, there are multiple ways to run EdgeDB and they differ depending on the environment you are in.
What I would like to see is a step by step guide using the Docker image you provide, then setting up a first schema and inserting and querying some data. You are advertising EdgeDB to have a low entry barrier on your website and I don't think that's the case currently.

**Comment by elprans** [comment]
The `edgedb server install` is meant to be used on the **host** to setup and run EdgeDB instances without having to use the `docker` CLI directly.  You shouldn't normally need to run it in an `edgedb/edgedb` container, because the image already has the server installed and ready to use.  You can run it as such:

```
docker run --name=edgedb -p5656:5656 -it --rm -v /tmp/data:/var/lib/edgedb/data edgedb/edgedb:20210128023945dde634
```

(I used the nightly image above, because `:latest` and `:1-alpha7` are unfortunately broken due to https://github.com/edgedb/edgedb-docker/issues/9)

> The real issue is that I think that the documentation doesn't tell you a lot, especially about the setup

Point taken.  We've made lots of changes to the setup flow recently with the introduction of `edgedb server` CLI and the docs currently focus on that.  We are working on putting together Docker/Docker Compose guides as well for the upcoming Beta.

**Comment by puchm** [comment]
Thank you for that command. I gave it another try and now I am struggling with the steps after that.
As you suggested, I set up the database with
```
docker run --name=edgedb -p 5656:5656 -it --rm -v /tmp/data:/var/lib/edgedb/data edgedb/edgedb:20210128023945dde634
```
This is the output:
```
INFO 1 2021-02-03 15:21:55,348 edb.server: EdgeDB server (1.0-alpha.8+dev.5355.gdde634f6) starting.
INFO 1 2021-02-03 15:21:58,913 edb.server: Serving on 127.0.0.1:5656
INFO 1 2021-02-03 15:21:58,913 edb.server: Serving on /run/edgedb/.s.EDGEDB.5656
INFO 1 2021-02-03 15:21:58,913 edb.server: Serving admin on /run/edgedb/.s.EDGEDB.admin.5656
```
I then tried setting up the database following [this guide](https://www.edgedb.com/docs/tutorial/createdb). 
I sh'ed into the container using
```
docker exec -it -u edgedb CONTAINER_ID sh
```
I hope that edgedb is the right user.

When running `edgedb -Idefault`, I got the following error:
```
edgedb error: cannot read credentials file /var/lib/edgedb/.edgedb/credentials/default.json: could not read file `/var/lib/edgedb/.edgedb/credentials/default.json`: No such file or directory (os error 2)
```

Since that didn't work I tried
```
edgedb server init  --nightly my_instance
```
I added the `--nightly` flag because it is a nightly build which apparently would get ignored otherwise.
Sadly, this also crashed with the following error:
```
CRITICAL 525 2021-02-03 15:41:43,988 edb.server: cannot create the runstate directory: '/run/user/999' does not exist; please use --runstate-dir to specify the correct location
[2021-02-03T15:42:12Z ERROR edgedb::server::init] Bootstrap error, cleaning up...
edgedb error: cannot bootstrap /var/lib/edgedb/.local/share/edgedb/data/my_instance: cannot establish connection for 30s: No such file or directory (os error 2)
```
I then tried running the same command with a `--runstate-dir` option but apparently that argument is not valid in that context.

Thank you for your help in advance.

**Comment by tailhook** [comment]
> When running edgedb -Idefault, I got the following error:

Yes `-Idefault` is to access named instances, we don't support using named instances in the containers. Either you create an instance from the host system `edgedb server init default --method=docker` or don't use `-I`.

You should be able to connect via plain `edgedb` in that scenario, or use a workaround `edgedb --admin` if you have already set up credentials and don't want to use them here (this command works only in the same container though).

> Since that didn't work I tried
>```
> edgedb server init  --nightly my_instance
>```

We don't support `init` in containers yet.

**Comment by tailhook** [comment]
As of edgedb/edgedb-cli#238 we emit an error message when running `edgdb server install` in container. I think there is nothing actionable left in this issue.
