### ISSUE TITLE
large microsecond durations don't work

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb#2191]
This fails:
```
edgedb> SELECT <duration>'3074457345618258602us';
ERROR: InternalServerError: interval field value out of range: "3074457345618258602us"
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: interval field value out of range: "3074457345618258602us"
```

This value is bigger than the one above and works fine. It seems like it shouldn't matter what units are used in the string. 
```
edgedb> SELECT <duration>'854015930h';
{3074457348000s}
```

- EdgeDB Version: 1.0a8.dev5287+g53ed2609-2020122100~focal.nightly
- EdgeDB CLI Version: edgedb-cli 1.0.0-alpha.7
- OS Version: Linux 5.8.0-40-generic #45~20.04.1-Ubuntu SMP Fri Jan 15 11:35:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fmoor** [comment]
It looks like postgres doesn't handle converting overflow seconds to days or months. Perhaps its not worth trying to change this behavior? @elprans

**Comment by elprans** [comment]
This is fine.  Let's properly adapt the error, though, so it's not an ISE.
