### ISSUE TITLE
Migrations aren't propagated to existing connections

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#2204]
- EdgeDB Version:1.0-alpha.8+dev.5386.g6933b454f
Steps to Reproduce:

1. Start `edgedb` (repl) and do a query:
```
edgedb> SELECT Counter;
error: object type or alias 'default::Counter' does not exist
  ┌─ query:1:8
  │
1 │ SELECT Counter;
  │        ^^^^^^^ error
```
2. Then in another shell do `edgedb migrate` to create the type
3. Then return back to this shell and confirm that error still there (while it shouldn't be):
```
edgedb> SELECT Counter;
error: object type or alias 'default::Counter' does not exist
  ┌─ query:1:8
  │
1 │ SELECT Counter;
  │        ^^^^^^^ error

```
4. Also try and confirm that it works in a new connection:
```
edgedb> SELECT Counter;
{}
```

**Note:** this doesn't reproduce with `CREATE TYPE` only with migrations.

**Comment by elprans** [comment]
This would be fixed by the rework in the `iocomp` branch.

**Comment by elprans** [comment]
This is fixed.
