### ISSUE TITLE
Constraint expressions with backlinks give ISE

### ISSUE THREAD

**Issue by holmesmr** [edgedb/edgedb#2207]
- EdgeDB Version: 1.0a7-2021011304
- OS Version: macOS 11.2

A type with a constraint expression containing a backlink causes an `edb.errors.InternalServerError: unexpectedly long path in simple expr` to be raised. SDL that reproduces is provided, but from testing, equivalent DDL statements cause the same issue, so it's not purely an issue with SDLs.

Steps to Reproduce:

1. Prepare the schema for migration.

2. Populate and commit the transaction.

Schema:
```
module default {
    abstract type User {
        required property name -> str;
        multi link groups -> MemberGroup;
    }

    type MemberGroup {
        required property name -> str;

        # Only Bob can have groups.
        constraint expression on (
            __subject__.<groups[IS User].name = "Bob"
        );
    }
}
```

**Comment by elprans** [comment]
This shouldn't be an ISE, but it's a valid error: we don't support reaching across links in constraints yet, only immediate properties/links can be used in a constraint expression.
