### ISSUE TITLE
Update documentation for the migration workflows

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#2230]
The Getting Started flow, tutorials, the cheatsheet, as well as the reference need to be updated to include the CLI-based migration flows.

**Comment by 1st1** [comment]
Yeah, the deadline for this is "yesterday". :)

Couple of notes re Getting Started:

* No DDL in it.
* Showcase CLI to download & install EdgeDB.
* Use CLI to apply migrations (not repl). Explain where to put our ESDL files, etc.
* Enabling GraphQL should be done via adding `using extension graphql` to the ESDL file (coming soon, @elprans is working on that)

**Comment by dmgolembiowski** [comment]
Aaah this is so great! Thank you!

**Comment by elprans** [comment]
@vpetrovykh, is this done?
