### ISSUE TITLE
`on target delete delete source` does not delete object extending abstract type

### ISSUE THREAD

**Issue by dermetfan** [edgedb/edgedb#2231]
- EdgeDB Version: `1.0-alpha.7+g85a3931a7.d20210113` from [Docker Hub](https://hub.docker.com/layers/edgedb/edgedb/latest/images/sha256-ec9ec924f0d91769db32c6530f70406d637734f0dc579e4ca6ca73dd8c7e3f8e?context=explore)
- OS Version: Official Docker image running on `NixOS 21.03pre-git (x86_64)`

Steps to Reproduce:

1. `INSERT B { value := (INSERT C) };`
2. `DELETE C;`

Now `B` should be deleted through the `A.value` link target deletion policy, but it was instead set empty. Check with `SELECT B { value };`.

Schema:

```edgeql
abstract type A {
	link value -> C {
		on target delete delete source;
	};
}

type B extending A {}

type C {}
```

**Comment by elprans** [comment]
@msullivan, this looks like the issue you've been looking into recently.
