### ISSUE TITLE
`constraint expression` from parent type is not checked on link target deletion

### ISSUE THREAD

**Issue by dermetfan** [edgedb/edgedb#2232]
- EdgeDB Version: `1.0-alpha.7+g85a3931a7.d20210113` from [Docker Hub](https://hub.docker.com/layers/edgedb/edgedb/latest/images/sha256-ec9ec924f0d91769db32c6530f70406d637734f0dc579e4ca6ca73dd8c7e3f8e?context=explore)
- OS Version: Official Docker image running on `NixOS 21.03pre-git (x86_64)`

Steps to Reproduce:

1. `INSERT B { value := (INSERT C) };`
2. `DELETE C;`

Step 2 should throw an error because the constraint is no longer satisfied.

Schema:

```edgeql
type A {
	link value -> C {
		on target delete allow;
	};

	constraint expression on (
		EXISTS .value
	);
}

type B extending A {}

type C {}
```

**Comment by elprans** [comment]
This is actually related to #2231: the cascade trigger doesn't fire properly and the link value in `B` doesn't get deleted.

**Comment by dermetfan** [comment]
It looks like it does get deleted, but the constraint is not re-evaluated. That is why I opened a separate issue:

```edgeql
edgedb> SELECT B { value };
{default::B {value: default::C {id: d0a97a24-6fda-11eb-9e82-1fba434b7ce4}}}

edgedb> DELETE C;
{default::C {id: d0a97a24-6fda-11eb-9e82-1fba434b7ce4}}

edgedb> SELECT B { value };
{default::B {value: {}}}
```

**Comment by elprans** [comment]
The target `C` object _is_ deleted, so you get an empty set in the query. But the link column in the `B` table doesn't get `NULL`-ed properly which doesn't trigger the `NOT NULL` constraint violation that implements the `EXISTS .value` constraint.

**Comment by dermetfan** [comment]
Ah, thanks for the clarification. Feel free to close this issue if that is how you handle duplicates.

**Comment by msullivan** [comment]
No, it's a bug.
