### ISSUE TITLE
datetime casting is asymmetric

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb#2248]
It seems surprising to me that some datetimes can be cast to str but not cast back to datetime. This happens if the year has more than 4 digits.

```
edgedb> SELECT to_datetime(999999999999);
{<datetime>'+33658-09-27T01:46:39.000064Z'}
edgedb> SELECT <datetime><str>to_datetime(999999999999);
ERROR: InvalidValueError: invalid input syntax for type std::datetime: '33658-09-27T01:46:39.000064+00:00'
  Hint: Please use ISO8601 format. Alternatively "to_datetime" function provides custom formatting options.
<!-- Please search existing issues to avoid creating duplicates. -->
```

- EdgeDB Version: package:1.0a8.dev5375+g8205d736c-2021020400~focal.nightly
- OS Version: Linux 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by elprans** [comment]
Fixed in #2252 by restricting the valid year range to 1-9999.
