### ISSUE TITLE
1-beta1 is slow compared to 1-alpha7

### ISSUE THREAD

**Issue by unmade** [edgedb/edgedb#2285]
### The Problem

After upgrading to `1-beta1` my tests run very slow - almost 3 minutes. With `1-alpha7` test suit runs in 30 seconds.

Do you know what could be the problem or how can I trace what causes this slowdown?

### My Setup:

- Test suit is running on macOS BigSur (rMBP 15 early 2013) and also in GitHub Actions
- The [project](https://github.com/unmade/shelf-back) is in Python with latest at the moment (0.13.0) `edgedb-python`
- EdgeDB run with [docker-compose](https://github.com/unmade/shelf-back/blob/master/docker-compose.yml) and with [services in GitHub Actions](https://github.com/unmade/shelf-back/blob/master/.github/workflows/test.yml#L18)
- Test suit includes:
    - [creating test database](https://github.com/unmade/shelf-back/blob/master/tests/conftest.py#L75-L90) - (runs once)
    - [creating connection pool](https://github.com/unmade/shelf-back/blob/master/tests/conftest.py#L93-L101) (runs once)
    - [migration](https://github.com/unmade/shelf-back/blob/master/tests/conftest.py#L104-L110) (runs once)
    - [tables clean up](https://github.com/unmade/shelf-back/blob/master/tests/conftest.py#L119-L123) (runs after each test)

**Comment by elprans** [comment]
Thanks for a great report, @unmade!  The fix will be rolled into a b1 fixup revision tonight.
