### ISSUE TITLE
What changed between alpha-8-5340 and beta-1 regarding arrays

### ISSUE THREAD

**Issue by isidentical** [edgedb/edgedb#2287]
I was trying to upgrade [reiz](https://github.com/reizio/reiz.io/) to use edgedb beta-1/2 in the weekend though I guess I burnt a lot of time while investigating some queries resulting in an empty set instead of what is expected from them. This only happened when running under the `1.0-beta.1+gc654bc4cd.d20210222` but not `1.0-alpha.8+dev.5340.g76e0688b`. Here is a reproducer;
```
CREATE DATABASE test_reiz;
\c test_reiz;

START MIGRATION TO {
    module ast {
        type arguments {
            multi link posonlyargs -> arg;
            multi link args -> arg;
        }
        type arg {
            required property arg -> str;
        }
    }
};

POPULATE MIGRATION;
COMMIT MIGRATION;

INSERT ast::arguments {
    posonlyargs := {
        (INSERT ast::arg { arg := 'bar' })
    },
    args := {
        (INSERT ast::arg { arg := 'baz' })
    }
};


SELECT ast::arguments
FILTER (
    WITH
        sequence_50150f83 := array_agg(.posonlyargs),
        sequence_12faedad := array_agg(.args)
    SELECT (
        len(sequence_50150f83) = 1
        AND len(sequence_12faedad) = 1
        AND sequence_50150f83[0].arg = 'bar'
        AND sequence_12faedad[0].arg = 'baz'
    )
);
```

Expected screenshot;
![image](https://user-images.githubusercontent.com/47358913/109434635-4aab8500-7a27-11eb-8859-17a6d0de69d5.png)

Current result;
![image](https://user-images.githubusercontent.com/47358913/109434625-3ebfc300-7a27-11eb-942e-55f517d198d4.png)

As it can be seen, the select returns the proper value under alpha-8 but returns an empty under beta-1. This seems like a really weird behavior, but I don't know when exactly it got broken. (OS: ubuntu 20)

**Comment by elprans** [comment]
This is an unfortunate regression from 1ee59553667b5922798291f40d14750f2ec65866, which apparently wasn't caught by the test suite.
