### ISSUE TITLE
Lots of failures migrating to empty schemas

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#2296]
After manually having run into issues several times trying to drop everything using a migration, I modified `_assert_migration_equivalence` to always migrate to an empty schema at the end (`migrations = migrations + ['']`), and it shakes out 9 test failures.

**Comment by msullivan** [comment]
The failing tests are:
test_schema_migrations_equivalence_35
test_schema_migrations_equivalence_annotation_05
test_schema_migrations_equivalence_annotation_06
test_schema_migrations_equivalence_collections_26
test_schema_migrations_equivalence_compound_01
test_schema_migrations_equivalence_constraint_03
test_schema_migrations_equivalence_linkprops_08
test_schema_migrations_equivalence_linkprops_10
test_schema_migrations_equivalence_collections_15

**Comment by elprans** [comment]
> I modified `_assert_migration_equivalence` to always migrate to an empty schema at the end

That's a good idea.
