### ISSUE TITLE
document ordering a set of scalars

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb#2318]
As a new user of EdgeDB I tried to figure out how to sort a set of scalars and failed. It seems like this scenario should be documented somewhere.

```
SELECT {3, 1, 2} ORDER BY ?;
```

My best guesses at the solution looked like this:
```
SELECT {3, 1, 2} ORDER BY .;  # attributes can be specified by .name so maybe . is the root?
SELECT {3, 1, 2} ORDER;
```

Asking @elprans I got this answer.
```
SELECT foo := {3, 1, 2} ORDER BY foo;
# or 
WITH foo := {3, 1, 2} SELECT foo ORDER BY foo;
```

**Comment by 1st1** [comment]
@vpetrovykh Should probably add this to the cheatsheet. And make sure that this is discoverable in the reference too.
