### ISSUE TITLE
Allow passing tuples as arguments

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#2326]
We currently prohibit passing tuples as arguments, because Postgres doesn't support them either ("input of anonymous composite types is not implemented").  

We already to a limited form of argument buffer rewrite before sending it to Postgres to inject array type OIDs (`recode_bind_args`), so we could add another transformation there to convert an incoming tuple into an array of bytestrings: `anytuple -> <array<bytes>>`, where bytes are the binary representation of the corresponding tuple element.  We could then prepare argument tuple casts to handle this by parsing the bytestrings into actual data by invoking appropriate Postgres `recv` functions directly, reconstructing the tuple.  This last bit is probably most elegantly implemented by defining casts from `bytes` to all types and then the above transform could be implemented via the generic cast framework, which is a big plus, because it would handle arbitrary nesting for us.

**Comment by elprans** [comment]
Argh, it appears we _can't_ call `recv` functions directly from SQL because they are declared as receiving `internal`, which stands in for their internal buffer pointer.  I'd wrongly assumed that `recv` is like `in` (the text variant), which receives a string, which we _can_ pass.

**Comment by msullivan** [comment]
Yury and I figured out a workable strategy. The hard part here is dealing with tuples that appear inside arrays, and additionally nested arrays that appear inside those tuples.

The basic strategy is to decompose an array of tuples into multiple parameters that take arrays of scalars. In the case of multiply nested arrays, we produce fully flattened arrays of all of the scalars that appear in them and introduce an extra `array<int64>` parameter that indicates how the flattened arrays get associated into arrays.

So for example, if we have a parameter type `array<tuple<array<str>>` and the input data
```
[
    (['a'],),
    (['b','c'],),
    (['d','e','f'],),
]
```
we turn that into being two parameters, `array<int64>` and `array<str>`, with the values `[0, 1, 1, 2, 2, 2]` and `["a", "b", "c", "d", "e", "f"]`.

I hacked up prototype implementations of a type translator, encoder, decoder, and edgeql decoder compiler: https://gist.github.com/msullivan/b45e3c785c55d5d8ea4db196e1d9cb55

I /think/ the python decoder runs in `O(|input size| * |nesting depth|)` but I need to think about it harder.

Then clients will send tuples to the server using the obvious encoding, we will have an encoder in the protocol server that flattens all of the arguments out into arrays of scalars, and generate a decoder that is inserted into the generated SQL query.

**Comment by msullivan** [comment]
Actually, that approach doesn't quite work, because it fails to distinguish between containing an empty array and being empty. There are modifications that do work, but they performed pretty slowly in my tests, I think because using group by is pretty bad here.
The new approach has the `array<int64>` store the ranges instead, so it would look like `[0, 1, 3, 6]` in the example above, corresponding with slices `0:1`, `1:3`, `3:6` to take from the array of strs.
