### ISSUE TITLE
errors casting json values don't provide location

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb#2327]
It would be much more helpful if errors gave a path to the error location in the json data. Ideally this information would be both obvious to humans reading the error message and available programmatically.

```python
>>> con.query("SELECT <tuple<a: int64, b: str>><json>$0", '{"a": 1}')
InvalidValueError: invalid null value in cast

>>> con.query("SELECT <tuple<a: int64, b: array<str>>><json>$0", '{"a": 1, "b": [2]}')
InvalidValueError: expected json string or null; got json number
```

- EdgeDB Version: package:1.0b2.dev5500+g2f67186c8-2021030200~focal.nightly
- OS Version: Linux 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by msullivan** [comment]
This should be possible but it will touch a wide range of things.

We'll want to report paths in the json something like:
* `."a"`
* ".b"[0]`
for the examples above.

Our big composite casts from json work by breaking down the operation into a bunch of smaller casts, so we'll need to arrange to pass down extra information for error messages into those casts, and create a way for that to be passed into the cast functions.

It's possible that actually including the indexes in array casts will make it too expensive, though, in which case we'd need to be a bit less ambitious.
