### ISSUE TITLE
Feature request: multiple string prefixes at once

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#2332]
Currently you must use either `r` or `b`, not both:
```
edgedb> br"";
error: prefix "br" is not allowed for strings, allowed: `b`, `r`
  ┌─ query:1:1
  │
1 │ br"";
  │ ^ error
```
Prefixes can be combined in python, would be nice if EdgeDB could support this too.

**Comment by 1st1** [comment]
Yeah, it's an oversight we don't have them.
