### ISSUE TITLE
PostgreSQL wire protocol v3 support

### ISSUE THREAD

**Issue by mcaramma** [edgedb/edgedb#236]
Will EdgeDB server be able to support PostgreSQL wire protocol v3?

It would be nice to have the opportunity to connect via standard JDBC and leverage available PG client drivers and tools.

**Comment by 1st1** [comment]
No, unfortunately that's not possible. 

EdgeDB binary protocol reuses Postgres' messages format and overall protocol structure but the actual message types and sequences are different.  The object model is also fundamentally different and the client implementation has to be built around it.
