### ISSUE TITLE
Protocol docs

### ISSUE THREAD

**Issue by tbremer** [edgedb/edgedb#237]
This is more of a question than an Issue…

Is there a plan to post or write docs for connecting to edgedb using other languages? Say I wanted to chat over HTTP or TCP? I see there is a port (5656) exposed by default, but I was not able to quickly find how to communicate over the wire?

Thanks!

**Comment by 1st1** [comment]
> Is there a plan to post or write docs for connecting to edgedb using other languages?

Absolutely.  The protocol is likely to be unstable for the first couple months after the initial alpha release though.

> Say I wanted to chat over HTTP or TCP?

We'll expose an HTTP REST endpoint for EdgeQL and GraphQL queries.

**Comment by tbremer** [comment]
That's great to hear! I'll learn some moderation and contain myself for coming releases. If you need any testers or implementers I am available to help. This is an exciting project, it's been fun to watch it evolve.

**Comment by tbremer** [comment]
Javascript is where I would be most effective.

**Comment by 1st1** [comment]
Closing this one. Protocol docs are here: https://edgedb.com/docs/internals/protocol/overview
