### ISSUE TITLE
New Server Implementation

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#238]
Latest summary:

### Management Port

By default EdgeDB will expose itself on one "management" port.  Edge connections to that port will always use the binary protocol; have 1 associated backend connection; have 1 associated compiler process.  We will expose a `--max-connections` config options similar to the one that Postgres exposes.  This is the type of a connection that system tools including repl will use.

Key characteristics: 

* High latency for new connections
* Can run DDL and other admin commands
* Hard limit on the total number of connections
* Protocols: `binary`

### Application Ports

EdgeDB will allow to run pools of "application" connections.  Application Ports will have the following characteristics: 

* The application port will service a single database
* Low latency for new connections
* Can't run DDL or admin commands
* No limit on the total number of connections
* An application port can serve one of the following protocols: `binary`, `http+edgeql`, `http+graphql`
* It is possible to have multiple application ports for the same or many different databases
* The application port will have a preconfigured number (called "concurrency") of always available backend connections and compiler processes 

### Command Line Options

* Running a server with only a management port open:

  ```shell
  $ edgedb-server --port 5667 --max-connections=100
  ```

* Running a server with a management port and a few application ports:

  ```shell
  $ edgedb-server --port 5667 --max-connections=100 \
      --app-port "[::]:50000; protocol:binary; dbname:movies; concurrency:100"
      --app-port "[::]:50000; protocol:binary; dbname:music; concurrency:50"
      --app-port "[::]:50001; protocol:http+graphql; dbname:movies; concurrency:20"
  ```

**Comment by ansarizafar** [comment]
We should have another port for Admin UI for monitoring and managing server/databases. like CockroachDb https://www.cockroachlabs.com/docs/v2.1/start-a-local-cluster.html for monitoring server and https://hasura.io/ for managing databases with embedded graphql playground https://github.com/prisma/graphql-playground.

**Comment by 1st1** [comment]
Yeah, that's the plan. We'll open a new issue (or project) for that once we're ready to discuss details.

**Comment by ansarizafar** [comment]
I'm happy to hear that. I would love to work on this project If you need help.

**Comment by 1st1** [comment]
This has been all implemented (except binary edgeql ports); this can be closed now.
