### ISSUE TITLE
create-migration fails when a property was moved to an abstract base type

### ISSUE THREAD

**Issue by ambv** [edgedb/edgedb#2380]
- EdgeDB Version: 1.0b1
- OS Version: macOS 10.15.7

Schema before:
```esdl
module commonplace {
    type User {
        required property name -> util::Slug {
            constraint exclusive;
        };
        index on (__subject__.name);
    };
};
```

Schema after:
```esdl
module commonplace {
    type User extending
        Named;

    type Content extending
        Named;

    abstract type Named {
        required property name -> util::Slug {
            constraint exclusive;
        };
        index on (__subject__.name);
    };
};
```

create-migration failing:
![2021-03-18 15 29 59](https://user-images.githubusercontent.com/55281/111643823-8ef89c80-87ff-11eb-80ee-7987f7544ff6.gif)

**Comment by ambv** [comment]
Trying to drop the index first results in a different error, about the exclusivity constraint now:
```
did you drop constraint 'std::exclusive' of property 'name'? [y,n,l,c,b,s,q,?]
y
error: cannot drop inherited constraint 'std::exclusive' of property 'name' of object type 'commonplace::User'
  ┌─ query:3:9
  │
3 │         DROP CONSTRAINT std::exclusive;
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ error
  │
  = constraint 'std::exclusive' of property 'name' of object type 'commonplace::User' is inherited from:
    - property 'name' of object type 'commonplace::Named'
```

Answering "no" to the question results in:
```
ERROR: InternalServerError: uncompiled expression in the field 'expr' of constraint <QualName commonplace::std|exclusive@commonplace|__||name&commonplace||User@da39a3ee5e6b4b0d3255bfef95601890afd80709>
```

**Comment by elprans** [comment]
> create-migration failing:

Confirmed.

> Trying to drop the index first 

Hm, the error seems to suggest `User` is already inherited from `Named`.  You cannot drop constraints inherited from parent type.

> Answering "no" to the question results in:

This was fixed in b2.nightly.

**Comment by msullivan** [comment]
@ambv what tool do you use to make the animations?

**Comment by ambv** [comment]
> @ambv what tool do you use to make the animations?

Gifox 2 on macOS
