### ISSUE TITLE
ISE when doing UPDATE on result of union

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#2383]
With a schema like
```
type Bar { property x -> str; }
type Baz { property x -> str; }
```
If we do `WITH W := (Bar UNION Baz) UPDATE W SET { x := "1" }`, we get an ISE from pgsql about a column not existing.
If we make x a multi property, instead we get an "unexpected union link" out of `range_for_ptrref`.

I don't think it would be terrible if we rejected this (though it also may not be hard to support).

**Comment by elprans** [comment]
Should be easy to support `Bar UNION Baz` is essentially equivalent to `Bar extending Baz`, we just need to generate DMLParts from `union_components` too.

**Comment by msullivan** [comment]
Also, as a note, we'll need to make sure that we correctly find any constraints we need to generate conflict checks for

**Comment by msullivan** [comment]
Huh, this seems to have been partially fixed at some point. It is broken when we do typename injection, but works without it.

This is actually a *problem*, though, because since it got fixed accidentally, the "correctly generate conflict checks" thing that I mentioned above didn't happen.
