### ISSUE TITLE
Implement support for link target deletion policy

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#239]
We need the ability to specify what happens when a link target is deleted, similar to the `ON DELETE` clause of the `FOREIGN KEY` constraint in Postgres.

The proposed declaration syntax is as follows:

```
# eschema:
type Foo:
    link bar -> Spam:
        on target delete: <action>

# DDL:
CREATE TYPE Foo CREATE LINK bar -> Spam ON TARGET DELETE <action>;
```

Where *<action>* is one of the following:

- `RESTRICT` -- produce an error indicating that deletion cannot be done due to an existing link.  This is the default.
- `DEFERRED RESTRICT` -- same as the above, but the check is postponed until the end of the current transaction, if there is no transaction, equivalent to `RESTRICT`.
- `SET EMPTY` -- remove the link, can only be used with links that are not `required`.
- `SET DEFAULT` -- remove the link, and replace it with links pointing to the objects returned by the default expression, if the default expression returns an empty set, and the link is required, an error is produced,
- `DELETE SOURCE` -- remove the link and the source of the link (cascaded deletion).

The actions have no inherent "weight", and are equal and mutually exclusive.  This means that whenever a link subitem is derived from a combination of similarly named links in parent types, and those links have conflicting deletion actions, an explicit resolution would be required:

```
type A:
    link foo -> Foo:
        on target delete: restrict

type B:
    link foo -> Foo:
        on target delete: set empty

type C extending A, B  # error, cannot resolve the target deletion action on link C.foo 
    
type C extending A, B:
    link foo -> Foo:
        on target delete: restrict  # OK
```

**Comment by 1st1** [comment]
Mostly implemented in https://github.com/edgedb/edgedb/commit/ef120bd52bbb3bd846be303f850571b895998e29 (except `SET DEFAULT`)

**Comment by gsouf** [comment]
@elprans I believe this syntax does not work with migration:

```
START TRANSACTION;
CREATE MIGRATION m TO {
  module default {

    type Foo
    {
      multi link Bar -> Bar ON TARGET DELETE ALLOW;
    };

    type Bar
    {
      required property bar-> str;
    };
  };
};
COMMIT MIGRATION m;
COMMIT;
```

Getting "Unexpected 'ON'"

**Comment by elprans** [comment]
You need to use nested brackets:

```
    type Foo
    {
      multi link Bar -> Bar {
        on target delete allow;
      }
    };
```

**Comment by elprans** [comment]
The syntax doc is here: https://edgedb.com/docs/edgeql/sdl/links#syntax

**Comment by CSFlorin** [comment]
@elprans Could we have conditional delete policies like `on target delete delete source if source.target is Post`? I noticed the source deletion policy has something close `on source delete delete target if orphan;` though I'm not sure it if it allows an arbitrary expression

**Comment by elprans** [comment]
No, `if orphan` is syntax, arbitrary expressions are not allowed currently.  Feel free to open a feature request with the description of your use case and we can discuss there.
