### ISSUE TITLE
Improve documentation and tutorials on non-trivial mutations

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#2401]
EdgeQL allows non-trivial mutations: nested `INSERT` and `UPDATE` and insert-or-update-or-select via `UNLESS CONFLICT`.  The tutorial/cheatsheet documentation level is currently very skimpy with respect to the examples those.

**Comment by 1st1** [comment]
@vpetrovykh Please also check out how easy edgedb covers those and maybe we can suggest Dave to change some hings if necessary. https://edgedb-staging.vercel.app/easy-edgedb
