### ISSUE TITLE
Add support for runtime cardinality assertion

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#2402]
There are many occasions in queries and schema where the compiler must prove that the expression result has a certain cardinality.  Not all cases are provable statically, either in principle or due to inference shortcomings, so we customarily use the `LIMIT 1` workaround on such expressions, which is bad, because it simply hides the fact that an expression might return multiple values, effectively negating the soundness check.

Instead of `LIMIT 1` there should be an explicit runtime assertion instruction, which would raise an exception at runtime if the desired cardinality is violated.

For example:

```
INSERT Obj { foo := ASSERT SINGLE (SELECT Foo FILTER <complex-filter-eliminating-all-but-one>) }
```

**Comment by msullivan** [comment]
This could be a function, right? `assert_single(...)`? (Albeit maybe one that requires special handling in pgsql)

**Comment by elprans** [comment]
Syntactically, sure it can be function-like.  That said, I generally lean toward preferring operator syntax for special stuff like this, which is why, for example, `DETACHED` is an operator and not a function.
