### ISSUE TITLE
Server could not figure out migrations

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#2409]
- EdgeDB Version: 1.0-beta.2+dev.5560.g9e95b0fa7

Just doing `create-migration` for this schema from scratch makes an error:
```
module default {
    type Category {
        required property title -> str;
        required property deleted := EXISTS(.<element[IS DeletionRecord]);
    };
    type Article {
        required property title -> str;
        required property deleted := EXISTS(.<element[IS DeletionRecord]);
    };
    type DeletionRecord {
        required link element -> Article | Category {
            on target delete delete source;
            constraint exclusive;
        }
    }
};
```
Removing `title` or `deleted` from either `Article` or `Category` fixes the issue (perhaps making object not so similar), but adding another property doesn't. 

CLI output:
```
did you create object type 'default::Article'? [y,n,l,c,b,s,q,?]
y
did you create object type 'default::Category'? [y,n,l,c,b,s,q,?]
y
did you create object type 'default::DeletionRecord'? [y,n,l,c,b,s,q,?]
y
Following extra DDL statements will be applied:
    ALTER TYPE default::Article {
        CREATE REQUIRED PROPERTY deleted := (EXISTS (.<element[IS default::DeletionRecord]));
    };
(approved as part as part of an earlier prompt)
Following extra DDL statements will be applied:
    ALTER TYPE default::Category {
        CREATE REQUIRED PROPERTY deleted := (EXISTS (.<element[IS default::DeletionRecord]));
    };
(approved as part as part of an earlier prompt)
edgedb error: Server could not figure out migration with your answers. Please retry with different answers
```

**Comment by elprans** [comment]
I don't see a link to `Category` in the schema and yet the output implies it's there.

**Comment by tailhook** [comment]
> I don't see a link to `Category` in the schema and yet the output implies it's there.

`element` is a link to an union `Article | Category`

**Comment by elprans** [comment]
Yes, I see `element`, but not `category`.

**Comment by tailhook** [comment]
> Yes, I see `element`, but not `category`.

Well, that one is commented out, without it bug also reproduces. I've updated CLI output in the issue description.

**Comment by msullivan** [comment]
This one should be fun: the underlying issue seems to be that we don't recompute the contents of union types when one of the constituents is altered.
