### ISSUE TITLE
Json cast does not give correct ISO format on timestamp

### ISSUE THREAD

**Issue by Mulugruntz** [edgedb/edgedb#2412]
- EdgeDB Version: Docker image: edgedb/edgedb:1-beta1
- OS Version:

Steps to Reproduce:

```sql
edgedb> select <json>(ImportedFile { filename, imported_timestamp}) limit 2;
{
  "{\"filename\": \"Temperature_2016-12-20.csv\", \"imported_timestamp\": \"2021-03-30T17:32:42.190469+00:00\"}",
  "{\"filename\": \"Temperature_2017-07-03.csv\", \"imported_timestamp\": \"2021-03-30T17:33:03.82454+00:00\"}",
}
```

As we can see on the second item, there's a `0` missing in the microseconds. It should have a precision of 6 and not of 5.
Because of that:
```python
>>> datetime.datetime.fromisoformat('2021-03-30T17:32:42.190469+00:00')
datetime.datetime(2021, 3, 30, 17, 32, 42, 190469, tzinfo=datetime.timezone.utc)
>>> datetime.datetime.fromisoformat('2021-03-30T17:33:03.82454+00:00')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: Invalid isoformat string: '2021-03-30T17:33:03.82454+00:00'
```

**Comment by 1st1** [comment]
@elprans do you think we can do something about this?

**Comment by elprans** [comment]
>  It should have a precision of 6 and not of 5.

Well, this is how Postgres formats it.

There's nothing in the standards that mandates minimum precision in the fractional second part.  Both RFC3339 and ISO 8601 define it as ` time-secfrac    = "." 1*DIGIT`.

In fact, Python documentation states this:

> This does not support parsing arbitrary ISO 8601 strings - it is only intended as the inverse operation of datetime.isoformat(). A more full-featured ISO 8601 parser, dateutil.parser.isoparse is available in the third-party package dateutil.

**Comment by Mulugruntz** [comment]
Hmmm I see.
Would it still make sense to have a more rigid output format in edgedb? So that the python driver would work more "seamlessly".
Thanks for the `dateutil.parser.isoparse`, I did my own hack, but I'm gonna replace it with the one from `dateutil`.

If that comes from Postgres, I think I already know the answer though ^^

**Comment by Mulugruntz** [comment]
Actually, I'm gonna close it, as my title is wrong. It's correct as ISO, **even though Python says `Invalid isoformat string`**.
This has therefore nothing to do with edgedb.

If edgedb team wishes to create a more rigid format, then it should not be because of ISO motivations but for other ones (and a new ticket will be opened).
