### ISSUE TITLE
Enums aren't accepted as input variables in GraphQL

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#2415]
This is in response to https://github.com/edgedb/edgedb/discussions/2413

The issue is that although enums should behave like scalars, they aren't accepted as inputs. So a query like:

```graphql
mutation updateItem($category: Category) {
  update_Item(data: {category: {set: $category}}) {
    category
  }
}
```
results in an error like:
`QueryError: Only scalar input variables are allowed. Variable 'category' has non-scalar value.`

**Comment by jnnkB** [comment]
Thank you for opening this issue
