### ISSUE TITLE
rolling back to nested savepoint error

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb#2420]
This error seems correct to me. It doesn't seem like this is a bug, but the error message says it is.

```
EdgeDB 1.0-beta.2+dev.5539.g6596bc813 (repl 1.0.0-beta.1)
Type "\?" for help.
edgedb> START TRANSACTION;
OK: START TRANSACTION
edgedb[tx]> DECLARE SAVEPOINT p1;
OK: DECLARE SAVEPOINT
edgedb[tx]> DECLARE SAVEPOINT p2;
OK: DECLARE SAVEPOINT
edgedb[tx]> ROLLBACK TO SAVEPOINT p1;
OK: ROLLBACK TO SAVEPOINT
edgedb[tx]> ROLLBACK TO SAVEPOINT p2;
Error: ERROR: InternalServerError: savepoint "p2" does not exist
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: savepoint "p2" does not exist
edgedb[tx:failed]>
```

- EdgeDB Version: EdgeDB 1.0-beta.2+dev.5539.g6596bc813 (repl 1.0.0-beta.1)
- OS Version: Linux 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 1st1** [comment]
> It doesn't seem like this is a bug,

Why? When you rollback to `p1` the state no longer knows about `p2` -- from its point of view `DECLARE p2` never happened.

**Comment by fmoor** [comment]
I was thinking that the bug is that it prints this part of the message.

```
 Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: savepoint "p2" does not exist
```

Erroneously printing this message seems like it would hurt user adoption.

**Comment by 1st1** [comment]
> Erroneously printing this message seems like it would hurt user adoption.

Yeah, absolutely, I'm looking into this. We do have a check for savepoint existence, but for some reason it's not engaging.
