### ISSUE TITLE
DatabaseConnectionView object has no attribute 'name'

### ISSUE THREAD

**Issue by Mulugruntz** [edgedb/edgedb#2428]
- EdgeDB Version: Docker image: edgedb/edgedb:1-beta1
- OS Version:

I'm finding out that the server crashes with this error quite a lot.
I already had something similar https://github.com/edgedb/edgedb/issues/2316
I'm giving most of my dev machine's resource to EdgeDB (so everything else is pretty slow). Therefore, trying to give more resource is not an option (sadly).

To be noted: Even though the error message is indeed different (or maybe not, after re-reading the debug logs, not sure anymore...), it sometimes still results in the famous "recovery mode". Then, I have to manually kill the container, restart it.

<details>

    INFO 1 2021-04-02 01:57:30,516 edb.server: EdgeDB server (1.0-beta.1+g2eee1afe4.d20210301) starting.
    INFO 1 2021-04-02 01:57:50,088 edb.server: Serving on 0.0.0.0:5656
    INFO 1 2021-04-02 01:57:50,090 edb.server: Serving on /run/edgedb/.s.EDGEDB.5656
    INFO 1 2021-04-02 01:57:50,091 edb.server: Serving admin on /run/edgedb/.s.EDGEDB.admin.5656
    ---- Exception occurred: 'edb.server.dbview.dbview.DatabaseConnectionView' object has no attribute 'name' ----

    1. AttributeError: 'edb.server.dbview.dbview.DatabaseConnectionView' object has no attribute 'name'

    ---- Traceback ----

        uvloop/cbhandles.pyx, line 69, in uvloop.loop.Handle._run
            > trimmed = Field(bool, default=False)
        uvloop/handles/basetransport.pyx, line 169, in uvloop.loop.UVBaseTransport._call_connection_lost
            > ExceptionContextList = checked.CheckedList[ExceptionContext]
        edb/server/protocol/binary.pyx, line 2081, in edb.server.protocol.binary.EdgeConnection.connection_lost
            

    AttributeError: 'edb.server.dbview.dbview.DatabaseConnectionView' object has no attribute 'name'
    ERROR 1 2021-04-02 02:20:14,437 asyncio: Exception in callback UVTransport._call_connection_lost
    handle: <Handle UVTransport._call_connection_lost>
    ---- Exception occurred: 'edb.server.dbview.dbview.DatabaseConnectionView' object has no attribute 'name' ----

    1. AttributeError: 'edb.server.dbview.dbview.DatabaseConnectionView' object has no attribute 'name'

    ---- Traceback ----

        uvloop/cbhandles.pyx, line 69, in uvloop.loop.Handle._run
            > trimmed = Field(bool, default=False)
        uvloop/handles/basetransport.pyx, line 169, in uvloop.loop.UVBaseTransport._call_connection_lost
            > ExceptionContextList = checked.CheckedList[ExceptionContext]
        edb/server/protocol/binary.pyx, line 2081, in edb.server.protocol.binary.EdgeConnection.connection_lost
            

    AttributeError: 'edb.server.dbview.dbview.DatabaseConnectionView' object has no attribute 'name'
    ERROR 1 2021-04-02 02:20:15,745 asyncio: Exception in callback UVTransport._call_connection_lost
    handle: <Handle UVTransport._call_connection_lost>
    ---- Exception occurred: unable to perform operation on <TCPTransport closed=True reading=False 0x556b0faf7330>; the handler is closed ----

    2. RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x556b0faf7330>; the handler is closed

    ---- Traceback ----

        edb/server/protocol/binary.pyx, line 1666, in edb.server.protocol.binary.EdgeConnection.main
            
        edb/server/protocol/binary.pyx, line 1597, in optimistic_execute
            
        edb/server/protocol/binary.pyx, line 1478, in _execute
            
        edb/server/protocol/binary.pyx, line 1444, in edb.server.protocol.binary.EdgeConnection._execute
            
        edb/server/pgcon/pgcon.pyx, line 771, in parse_execute
            
        edb/server/pgcon/pgcon.pyx, line 706, in _parse_execute
            
        edb/server/protocol/binary.pyx, line 289, in edb.server.protocol.binary.EdgeConnection.write
            
        edb/server/protocol/binary.pyx, line 324, in edb.server.protocol.binary.EdgeConnection.flush
            
        uvloop/handles/stream.pyx, line 673, in uvloop.loop.UVStream.write
            
        uvloop/handles/handle.pyx, line 159, in uvloop.loop.UVHandle._ensure_alive
            

    RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x556b0faf7330>; the handler is closed

    ---- During handling of the above exception, another exception occurred ----

    1. RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x556b0faf7330>; the handler is closed

    ---- Traceback ----

        edb/server/protocol/binary.pyx, line 1719, in edb.server.protocol.binary.EdgeConnection.main
            
        edb/server/protocol/binary.pyx, line 324, in edb.server.protocol.binary.EdgeConnection.flush
            
        uvloop/handles/stream.pyx, line 673, in uvloop.loop.UVStream.write
            
        uvloop/handles/handle.pyx, line 159, in uvloop.loop.UVHandle._ensure_alive
            

    RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x556b0faf7330>; the handler is closed
    ERROR 1 2021-04-02 02:22:12,023 asyncio: unhandled error in edgedb protocol while handling an error
    protocol: <edb.server.protocol.binary.EdgeConnection object at 0x7fd06b366120>
    task: <Task pending name='Task-35' coro=<EdgeConnection.main() running>>
    transport: <TCPTransport closed=True reading=False 0x556b0faf7330>
    ---- Exception occurred: unable to perform operation on <TCPTransport closed=True reading=False 0x556b0fe517a0>; the handler is closed ----

    2. RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x556b0fe517a0>; the handler is closed

    ---- Traceback ----

        edb/server/protocol/binary.pyx, line 1666, in edb.server.protocol.binary.EdgeConnection.main
            
        edb/server/protocol/binary.pyx, line 1597, in optimistic_execute
            
        edb/server/protocol/binary.pyx, line 1478, in _execute
            
        edb/server/protocol/binary.pyx, line 1444, in edb.server.protocol.binary.EdgeConnection._execute
            
        edb/server/pgcon/pgcon.pyx, line 771, in parse_execute
            
        edb/server/pgcon/pgcon.pyx, line 706, in _parse_execute
            
        edb/server/protocol/binary.pyx, line 289, in edb.server.protocol.binary.EdgeConnection.write
            
        edb/server/protocol/binary.pyx, line 324, in edb.server.protocol.binary.EdgeConnection.flush
            
        uvloop/handles/stream.pyx, line 673, in uvloop.loop.UVStream.write
            
        uvloop/handles/handle.pyx, line 159, in uvloop.loop.UVHandle._ensure_alive
            

    RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x556b0fe517a0>; the handler is closed

    ---- During handling of the above exception, another exception occurred ----

    1. RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x556b0fe517a0>; the handler is closed

    ---- Traceback ----

        edb/server/protocol/binary.pyx, line 1719, in edb.server.protocol.binary.EdgeConnection.main
            
        edb/server/protocol/binary.pyx, line 324, in edb.server.protocol.binary.EdgeConnection.flush
            
        uvloop/handles/stream.pyx, line 673, in uvloop.loop.UVStream.write
            
        uvloop/handles/handle.pyx, line 159, in uvloop.loop.UVHandle._ensure_alive
            

    RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x556b0fe517a0>; the handler is closed
    ERROR 1 2021-04-02 02:22:31,701 asyncio: unhandled error in edgedb protocol while handling an error
    protocol: <edb.server.protocol.binary.EdgeConnection object at 0x7fd06b366040>
    task: <Task pending name='Task-34' coro=<EdgeConnection.main() running>>
    transport: <TCPTransport closed=True reading=False 0x556b0fe517a0>
</details>

What I'm currently doing: adding millions of rows into the DB, about a few tens of thousands at a time. I have 2 async connections open that I acquire from a pool (min=2). I now added a sleep of 1 seconds after each batch.
It looks a bit like:

```python
@asynccontextmanager
async def db_connect() -> AsyncContextManager:
    async with await edgedb.create_async_pool(
        min_size=2, **DB_CONNECTION_PROPS
    ) as pool:
        yield pool

async def save_data(pool, data):
    async for tx in pool.retrying_transaction():
        async with tx:
            await delete_data_if_needed(tx, data)
            await insert_data(tx, data)
            metadata = get_metadata(data)
            await insert_or_update_metadata(tx, metadata)

async def func_in_worker(queue: asyncio.Queue):
    async with db_connect() as pool:
        while True:
            await save_data(pool, await queue.get())
            queue.task_done()
            await asyncio.sleep(1.0)

async def get_workers_its_magic(workers, func):
    # just some black magic here
    pass

async def run_client():
    workers = await get_workers_its_magic(workers=2, func=func_in_worker):
    workers.start()
    await workers.join()

if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(run_client())
```

Obviously, my code is a bit different but you'll understand the gist of it. I'll make public the lib I developed for making async pools (not related to Edge pools) some time in the future (need to cleanup and add more pytest, only 4 for now) but for now, you'll just have to trust me that it works *"roughly"* like that (at least, should be an understandable equivalent).

According to my code, I should have only 2 workers concurrently accessing the DB. And they only reuse the `tx` Retrying Transaction inside each working iteration. They don't create new connections. At the next batch, it's a new transaction they get from the pool. They only share the same pool and input queue. Nothing else. So there shouldn't be any long-lived Edge items, except for the `AsyncIOPool`.

Am I reaching the limits of EdgeDB? Or is my machine not powerful enough to run EdgeDB? Or am I misusing EdgeDB? Or bad settings?

Thanks for your time and dedicated work, as always.

**Comment by elprans** [comment]
This is clearly a bug in the error handling code.  Thanks for the report!

> Am I reaching the limits of EdgeDB? Or is my machine not powerful enough to run EdgeDB? Or am I misusing EdgeDB? Or bad settings?

We've made some improvements for RAM-constrainted machines recently, specifically reducing the maximum number of Postgres connections EdgeDB is allowed to keep in its pool (#2369).  See if things work better on the nightly.

**Comment by Mulugruntz** [comment]
Is there a way to see how many PG connections are currently in EdgeDB's pool?

I might check the nightly later today. Or another day.

**Comment by elprans** [comment]
`ps ax | grep postgres | grep <db-name>` should give a good estimate
