### ISSUE TITLE
Document & ensure that int64 isn't JSON serializable

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#245]

**Comment by vpetrovykh** [comment]
This isn't limited to JSON. There are other cases where `int64` can cause problems. The most notable one is array indexing.

In PostgreSQL the following will produce an "ERROR:  integer out of range":
```SQL
SELECT (ARRAY[1,2,3])[9223372036854775800];
```
While this will happily produce `1`:
```SQL
SELECT (ARRAY[1,2,3])[1::bigint];
```

So, right now strictly speaking our indexing should also be limited to `int32`. Does this mean that we should type-check that at compile time and force explicit casts for use in `[]` (e.g. `Foo.bar[<int32>Bar.baz]`)? This does seem rather bulky.

**Comment by vpetrovykh** [comment]
In PostgreSQL `to_json` will gladly convert a number that's even larger than `bigint` without complaints.

**Comment by elprans** [comment]
An explicit type cast would produce the same error at runtime, so I fail to see the value in introducing such a requirement.

**Comment by elprans** [comment]
The JSON spec does not explicitly prevent numerics larger than those JavaScript can support, hence such serialization is valid.
