### ISSUE TITLE
Disallow volatile operations in schema computables

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#2467]
For example
```
type Foo {
    property rand := random();
}
```
or more excitingly `link best_friends := (SELECT .friends FILTER random() > .5)`
ought to both be disallowed.

**Comment by RobbieMcKinstry** [comment]
Could you say a little more about why this is disallowed? I have a rather inoculous use case.

I'm trying to create a "Magic Link" for user logins. The link should expire after 24 hours, and I figured I could use a computed property to set that, since `datetime_current()` is allowable elsewhere in the schema definition (`default := datetime_current()`.

```
module default {
    abstract type MagicLink extending Timestamped {        
        required link user -> User;
        required property verification_code -> str;

        required property created_at -> datetime {
            readonly := true;
            default := datetime_current();
        }

        property expired := datetime_current() - .created_at < <duration>'24 hours';
    }
```

However, I get the following error:

```
$ edgedb migration create
[2022-12-05T19:59:06Z WARN  edgedb::version_check] Newer version of edgedb tool exists 2.2.6+7eabbf9 (current 2.0.1)
error: volatile functions are not permitted in schema-defined computed expressions
   ┌─ dbschema/default.esdl:21:29
   │
21 │         property expired := datetime_current() - .created_at < <duration>'24 hours';
   │                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ error

edgedb error: cannot proceed until .esdl files are fixed
```

**Comment by franckdsf** [comment]
Similar use case as @RobbieMcKinstry , I don't get why this is prohibited.

**Comment by fmoor** [comment]
Volatile means that each time a function is called during a transaction it could produce a different result even though it's inputs are the same. `datetime_current()` returns the current time which is different each time the function is called. This makes the function volatile. `datetime_of_transaction()` on the other hand always returns the same time during a given transaction so it is not volatile.

This is a valid schema as of EdgeDB 2.8:
```
module default {
  type MyThing {
    required property created_at -> datetime {
      default := datetime_of_transaction();
    };
    required property expired := (datetime_of_transaction() - .created_at) > <duration>'24h';
  };
}
```

**Comment by RobbieMcKinstry** [comment]
That's sufficient for my use case -- I don't need the time down to the milisecond, just a close estimate of when it was created. I'll use `datetime_of_transaction()` instead. Thanks for the explanation! I appreciate it :)
