### ISSUE TITLE
AWS Lightsail postgres LC_CTYPE: invalid locale name: "C.UTF-8" 

### ISSUE THREAD

**Issue by clmno** [edgedb/edgedb#2478]
DB Version: EdgeDB server (1.0-beta.2+dev.5588.ge24df84a3.d20210421) starting in DEV mode
OS: Ubuntu 20.04LTS

I tried setting up a remote pg instance from my Ubuntu 20.04 VM instance. But I get an error when I try to bootstrap the database

```
asyncpg.exceptions.WrongObjectTypeError: invalid locale name: "C.UTF-8"
```

@fantix had made a fix for a locally-started remote Postgres on Debian/Ubuntu in 48dcc9210e77033fbdb33ad5dd8aa3bea2e64433. But I still face this issue.

I've asked a question on StackOverflow - [Invalid local name: C.utf8 even though the collname exist in pg_collation.collname](https://stackoverflow.com/questions/67189212) - to see if it's something I can fix (a good first issue 🤞)

### Here is what happens

1. This SQL fails
    ```sql
    CREATE DATABASE __edgedbtpl__  OWNER='edgedb' IS_TEMPLATE = TRUE TEMPLATE='template0' ENCODING='UTF8' LC_COLLATE='C' LC_CTYPE='C.UTF-8';
    ```
    with this error
    ```
    ERROR:  invalid locale name: "C.UTF-8"
    ```
2. But @fantix made a fix to check if `UTF-8` is a valid local using the below SQL
    ```sql
    SELECT collname FROM pg_collation WHERE lower(replace(collname, '-', '')) = 'c.utf8' LIMIT 1;
    ```
    but `UTF-8` is not seen for these two runtime parameters using [SHOW](https://www.postgresql.org/docs/9.1/sql-show.html)
    ```sql
    SHOW LC_CTYPE;
      lc_ctype   
    -------------
     en_US.UTF-8
    (1 row)
    
    
    
    SHOW LC_COLLATE;
     lc_collate  
    -------------
     en_US.UTF-8
    (1 row)
    ```
3. Previously I didn't have an issue here because previous to 48dcc9210e77033fbdb33ad5dd8aa3bea2e64433 the above SQL was always returning a null. And so `LC_CTYPE` was set to `en_US.UTF-8`.

### Question
1. Is this a `good first issue`?

**Comment by clmno** [comment]
Had a discussion with @laurenz on SO, but was unable to find a solution for this. It might be a AWS specific issue and so I've raised an issue at forums.aws.amazon.com - [Link](https://forums.aws.amazon.com/thread.jspa?threadID=339264)

**Comment by elprans** [comment]
Well, I think the issue here is simple.  The fix in 48dcc92 changed locale detection to include the dashless spelling of `UTF-8`, but the `CREATE DATABASE` statement still uses the dashed spelling.  Changing it to `C.utf8` should help.

> Is this a good first issue?

If the above hypothesis is correct, then yes :-)

**Comment by clmno** [comment]
I tried `C.utf8`, but that doesn't help.

```sql
CREATE DATABASE __edgedbtpl__  OWNER='edgedb' IS_TEMPLATE = TRUE TEMPLATE='template0' ENCODING='UTF8' LC_COLLATE='C' LC_CTYPE='C.utf8';
```

I still get the same error:
```sql
ERROR:  invalid locale name: "C.utf8"
```

From an answer to my question on SO
> Collation names are identifiers, not string literals in PostgreSQL. Use double quotes instead of single quotes. Also, case and spelling matter, so use "C.utf8"

So I tried using `single quotes`, changed the spelling, etc. But haven't yet got to make it work. I've asked a question on AWS forum too - [Link](https://forums.aws.amazon.com/thread.jspa?threadID=339264). But yet to receive an answer.

Note: If I use `en_US.UTF-8` it works

**Comment by elprans** [comment]
Well, if it doesn't work no matter how you spell it, then it's evidence that AWS's setup is broken.  Despite the fact that `C.utf8` is present in `pg_collations`, it's not actually a functional locale in the system.  We'll need to modify our check to actually try and use the locale instead of looking into `pg_collations`.

**Comment by clmno** [comment]
Yes. So a `try except`? Looks ugly but I think this is the only way to solve vendor specific setup for databases.
