### ISSUE TITLE
Ask for default when adding new required property

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb#2486]
- EdgeDB Version: 1-beta.1
- EdgeDB CLI Version: beta.1
- OS Version: macOS Big Sur

Steps to Reproduce:

I made a minimal repro of how I got my schema into an inconsistent state.

1. Create an initial schema

```
module default {
    type BlogPost {
        property title -> str;
    }
};
```

2. Add some data;

```
INSERT BlogPost;
```

3. Update
```
module default {
    type BlogPost {
        property title -> str;
        required property name -> str;
    }
};
```

4. Run `create-migration` (works fine). If you make an existing non-required property required, the migration tool prompts you for a default, but not if you define a new required property.

5. Inconsistent state:

Running migrate:

```
$ edgedb -I inconsistent migrate
edgedb error: ERROR: MissingRequiredError: missing value for required property 'name' of object type 'default::BlogPost'
```

Runing create-migration (e.g. after setting a default for .content):

```
$ edgedb -I inconsistent create-migration
edgedb error: Database must be updated to the last migration on the filesystem for `create-migration`. Run:
  edgedb migrate
```

**Comment by msullivan** [comment]
I have fixes for the updated test case where we add a new required property, but frustratingly, the *original* issue of adding a property via a new parent class might be a bit trickier. I'm going to spend a couple hours looking at it, but I might put up a partial fix without handling that case yes.
