### ISSUE TITLE
Improve support for JSON casts

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#251]
Currently, casting to and from `std::json` is supported only for scalar types. This proposes to extend JSON casting support to collection types as well as allowing to cast objects to `std::json`.

New rules:

1. `<json>Object` returns a `json` value containing the output representation of the object.  That is, the result is the same as `SELECT Object` in JSON mode, including the type shape.

2. Scalar casts now work only for _scalar_ JSON values, so casting a non-scalar JSON value to `std::str` is an error, and `<json>'{"foo":"bar"}'` returns a JSON *string* (`"{\"foo\":\"bar\"}"`), not a JSON object.

3. Non-scalar string-to-JSON and JSON-to-string casting is accomplished by the new `str_to_json(str) -> json` and `json_to_str(json) -> str` functions correspondingly.

4. `<json>array_value` returns a JSON array 

5. `<array<type>>json_value` returns an EdgeQL array of the given type.  `null` values in input produce an error (if the target type is not `json`, use `json_array_unpack` for fine-grained casting).

5. `<json>tuple_value` returns a JSON array and conversely `<tuple<...>>json_value` converts a JSON array into a tuple. `null` elements in input produce an error (if the target element type is not `json`).

6. `<json>named_tuple_value` returns a JSON object and conversely `<tuple<name: type...>>json_value` converts a JSON object/array into a named tuple. `null` values in input produce an error (if the target type is not `json`).

**Comment by vpetrovykh** [comment]
Currently the casts from JSON to tuples are broken. The JSON docs will need to be updated once this is fixed.

**Comment by haikyuu** [comment]
I am getting an error while trying to cast a string to an enum

```
error {
message: "cannot cast 'std::json' to 'default::Position'",
type: 'QueryError',
code: 67108864
 }
```
Query

```
INSERT Job {
            position := <Position>$position
          }
```
And i'm passing a string as a variable.

Is this related? or should strings be considered as str instead of `json`?

**Comment by 1st1** [comment]
@vpetrovykh Please check if str->enum casts work in EdgeQL+HTTP / GraphQL contexts correctly.

**Comment by 1st1** [comment]
@elprans @vpetrovykh Should this be closed now?

**Comment by elprans** [comment]
I think we need to allow casting `json` to `anyenum` directly.  @vpetrovykh please look into this.

**Comment by elprans** [comment]
Remaining work items in this issue:

- [ ] allow casting `json` to `anyenum` and vice versa (should be similar to the `std::str` cast in `enumoperators.edgeql`)
- [ ] allow casting `json` to `tuple` types
- [ ] allow casting `json` to `array` types

**Comment by msullivan** [comment]
I think this is done
