### ISSUE TITLE
Migration issue when cyclic dependency is altered

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#2536]
- EdgeDB Version: 1-beta.2

Steps to Reproduce:

1. Apply the following schema:
```
module default {
    type Article {
        required property deleted := (EXISTS (.<element[IS default::DeletionRecord]));
    };
    type Category {
        required property deleted := (EXISTS (.<element[IS default::DeletionRecord]));
    };
    type DeletionRecord {
        required link element -> (default::Article | default::Category) {
            on target delete  delete source;
            constraint std::exclusive;
        };
    };
};
```
2. Change to:
```
module default {
    abstract type Removable {
        property deleted := EXISTS(.<element[IS DeletionRecord]);
    }
    type Article extending Removable {
    };
    type Category extending Removable {
    };
    type DeletionRecord {
        required link element -> Removable {
            on target delete delete source;
            constraint std::exclusive;
        };
    };
};
```
3. Get the following error on `create-migration`:
```
did you create object type 'default::Removable'? [y,n,l,c,b,s,q,?]
y
error: 'default::Removable.<element' does not resolve to any known path
  ┌─ query:2:41
  │
2 │     CREATE PROPERTY deleted := (EXISTS (.<element[IS default::DeletionRecord]));
  │                                         ^^^^^^^^^ error

Rolling back last operation...
did you create object type 'default::Removable'? [y,n,l,c,b,s,q,?]
```

On the other hand, schema from (2) works fine if applied from scratch

**Comment by msullivan** [comment]
Hm, we now reject the first schema with
```
ERROR: SchemaError: it is illegal to create a type union that causes a computable property 'deleted' to mix with other versions of the same property 'deleted'
```

**Comment by msullivan** [comment]
Oh, but if I make the names different, and then try to migrate, it still fails, so.

**Comment by tailhook** [comment]
> Hm, we now reject the first schema with
> 
> ```
> ERROR: SchemaError: it is illegal to create a type union that causes a computable property 'deleted' to mix with other versions of the same property 'deleted'
> ```

Actually I don't understand what it means. You can make an union of two types which have a property that is named the same, right? So what makes it broken? The fact that both (or any) are computed? Is the limitation fundamental or temporary? (i.e. I used to think that any property can be changed to computable, e.g. for backwards compatibility, this limitation seems arbitrary for me)

**Comment by elprans** [comment]
>  Is the limitation fundamental or temporary

Temporary, until the compiler learns to actually produce correct queries for polymorphic computables.

**Comment by tailhook** [comment]
Good. Can we rephrase error to something like:
```
it is illegal to create a type union from multiple types having computable property `deleted`
```
Or:
```
multiple matches for `deleted`, each type in an union must have unique computable properties
```

**Comment by elprans** [comment]
> Can we rephrase error to something like

We prohibit mixing non-computables with computables as well, not just different computables, but I agree that the error message needs clarification.  I'd actually specialize the message to each prohibited combination (i.e. computable and non-computable and computable/computable).

\cc @vpetrovykh
