### ISSUE TITLE
Nested mutation with same object type errors out

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb#2542]
- EdgeDB Version: beta 2
- OS Version: macOS Big Sure

Steps to Reproduce:

Reproduction repo: https://github.com/colinhacks/edgedb-update-insert-bug

Schema:

**Comment by elprans** [comment]
Need to decide whether to allow or prohibit this like we prohibit selecting self-references in mutation body.  An ISE is a bug either way.

**Comment by msullivan** [comment]
It looks like we reject this now with "cannot reference correlated set"
