### ISSUE TITLE
Nested upsert not working as expected 

### ISSUE THREAD

**Issue by limx0** [edgedb/edgedb#2555]
I'm having some trouble understanding why a nested upsert is failing in some circumstances. From reading some recent issues / PRs on `UNLESS CONFLICT ON` it appears as though this _should_ work. I'm unsure if this related to https://github.com/edgedb/edgedb/issues/2542

- EdgeDB Version: 1.0b2+ga7130d5c7.cv202104290000
- OS Version: macOS Big Sur (11.3.1)

Steps to Reproduce:

1. Create db with schema below
2. Execute the following upsert, which returns `{}` (as opposed to the expected inserted uuid) 
```
SELECT (
  INSERT InstrumentId {
    value := "instrument",
    symbol := (
      INSERT Symbol {value := "symbol", } 
      UNLESS CONFLICT ON Symbol.value ELSE (SELECT Symbol)
    ),
    venue := (
      INSERT Venue {value := "venue"} 
      UNLESS CONFLICT ON Venue.value ELSE (SELECT Venue)
    ),
  }
  UNLESS CONFLICT ON InstrumentId.value ELSE (SELECT InstrumentId)
); 
```
Some notes: 
- On a fresh instances it seems to insert the `symbol`, but fail on the `venue` (for reasons unclear to me), exiting out.
- If I start fresh, insert the `venue` first and run the above, it works as expected. 
- It also works if I move the nested upserts into variables under a WITH statement at thee top of the query. 
- I've used the fully qualified names everything to ensure I wasn't get confused about scopes etc.

Could anyone shed some light on why this particular case fails? I could always pull my nested upserts out, but I have more complex objects than this, and I would like to just be able to generate nested queries if possible (avoiding some toposort of required variables under a WITH statement. 

Schema:
```
module default {
    abstract type Identifer {
        required property value -> str;
        constraint exclusive on ( .value );
    }

    type Symbol extending Identifer {}
    type Venue extending Identifer {}

    type InstrumentId extending Identifer {
        link symbol -> Symbol; 
        link venue -> Venue;
    }
}
```

**Comment by msullivan** [comment]
Yeah, definitely a bug!
