### ISSUE TITLE
Make behavior of explicit computable links consistent with shapes

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb#2558]
- EdgeDB Version: beta2

Steps to Reproduce:

Currently the following schema treats `User.tweets` as detached in queries:

```ts
module default {
  type User {
    property name -> str;
    multi link tweets := User.<author[IS Tweet];
    # treated differently than:
    # multi link tweets := .<author[IS Tweet];
  }
  type Tweet {
    link author -> User;
  }
}
```

Moreover, switching between the explicit and implicit "User" is treated as a schema change by `edgedb create-migration`.

These should be treated as equivalent for the sake of consistency with how the dot shortcut works inside query shapes: https://edgedb.slack.com/archives/C09QSK72B/p1621902198005900

**Comment by elprans** [comment]
For clarity, references to the source type in schema computables should be replaced with `__source__`, unless the expression is inside `DETACHED`.  This probably needs an AST visitor akin to `compiler/normalization.py`.
