### ISSUE TITLE
InternalServerError: operator is not unique: timestamp with time zone `-` duration_t

### ISSUE THREAD

**Issue by jaclarke** [edgedb/edgedb#2617]
- EdgeDB Version: 1.0-beta.3+dev5686.d2021062412.g99e1f5eec.cv202106090000

Steps to Reproduce:

```edgeql
select datetime_current() - <duration>'10s';
```

**Comment by elprans** [comment]
This seems to be a regression from the addition of `relative_duration`.  Somehow our operator permutation tests aren't catching this.
