### ISSUE TITLE
InternalServerError: duplicate key value violates unique constraint "9802c422-d5d1-11eb-9b10-459c32f1a94a_source_target_key"

### ISSUE THREAD

**Issue by isidentical** [edgedb/edgedb#2622]
- EdgeDB Version: Beta 1
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Use this schema
```
START MIGRATION TO {
    module ast {
        type Compare {
            multi property ops -> cmpop;
        }
        scalar type cmpop extending enum<'Eq', 'NotEq', 'Lt', 'LtE', 'Gt', 'GtE', 'Is', 'IsNot', 'In', 'NotIn'> {}
    }
};

POPULATE MIGRATION;
COMMIT MIGRATION;
```

2. Execute the following command
```
bug_report> INSERT ast::Compare {ops := {<ast::cmpop>'Eq', <ast::cmpop>'Eq'}};
ERROR: InternalServerError: duplicate key value violates unique constraint "9802c422-d5d1-11eb-9b10-459c32f1a94a_source_target_key"
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: duplicate key value violates unique constraint "9802c422-d5d1-11eb-9b10-459c32f1a94a_source_target_key"
```

This is kinda weird because, you can use multiple *different* operators as well as you can individually construct a set of `Eq` objects. But the problem arises when you have multiple of them on a link.

**Comment by elprans** [comment]
This is because currently we prohibit multiplicity > 1 in properties (i.e. the values must be unique), and the error isn't handled correctly here.  However, there's a plan to remove property multiplicity constraints: https://github.com/edgedb/edgedb/discussions/2054

**Comment by isidentical** [comment]
Thanks for the quick response @elprans! Indeed #2054 seems really cool. I'll probably switch the current model to use `property ops -> array<cmpop>` instead of `multi property ops -> cmpop` to support multiple same values.

**Comment by elprans** [comment]
Yeah, using an array instead of a `multi` property is a good workaround.  Furthermore, if you treat the whole array as a single value, i.e. you don't often need to filter on individual elements or modify the array frequently, an array is better than a multi property, because it's more compact and local to the host object.
