### ISSUE TITLE
Make server command-line equivalent environment variables have the uniform `EDGEDB_SERVER_` prefix

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#2643]
Currently the environment variables corresponding to server command-line flags are prefixed with `EDGEDB_`, which makes them overlap with the environment variables used for client connections, which might lead to surprises.  Fix this by prefixing the server variables uniformly with `EDGEDB_SERVER_` and deprecate the old set.  The docker image is affected in a similar way.

**Comment by fmoor** [comment]
@elprans we aren't updating the prefix for the development debug variables too are we?

**Comment by elprans** [comment]
No, debug vars may stay the same as they already have a prefix.

**Comment by tailhook** [comment]
I'm not sure I nderstand the problem. It was always nice that `EDGEDB_PORT` works both for server and client. So if you change it both server runs on a new port and client does that too.

**Comment by elprans** [comment]
> 'm not sure I nderstand the problem. It was always nice that `EDGEDB_PORT` works both for server and client.

It's cool if you intended that, but is very bad if you didn't.  IMO, explicit separation is more reliable here.
