### ISSUE TITLE
edgedb CLI command readability, verb-object regularity, usability and ergonomics

### ISSUE THREAD

**Issue by DavidPratten** [edgedb/edgedb#2647]
While the following edgedb commands are clear as to what is being acted on:

`edgedb create-superuser-role`
`edgedb alter-role`
`edgedb drop-role`
`edgedb server reset-password`

most CLI commands are more cryptic.  

What would be the impact on the cognitive load for learners and developers, if we made both the verb and the object clear in the canonical version of CLI commands? 

There are many approaches to regularising naming conventions.  I'm not precious about which approach is chosen, just keen on improving usability and ergonomics.

I'm interested in contributing. If the edgedb team is supportive of this direction, then I am interested in assisting creation of the pull requests to chip away at this refactoring of code and documentation over coming releases.  Let me know if this is of interest.

Command | Possible Canonical Version Showing Verb-Object|Other possibilities.
-- | --|--
`edgedb configure` | `edgedb configure-instance`| Or possibly `edgedb instance configure` 
`edgedb   create-migration` | `edgedb   create-migration-database`| Or possibly `edgedb database create-migration`
`edgedb dump` | `edgedb dump-database`
`edgedb migrate` | `edgedb   migrate-database`
`edgedb migration-log` | `edgedb migration-log-database`
`edgedb   project init` | `edgedb project   init-instance`
`edgedb project unlink` | `edgedb project unlink-instance`
`edgedb restore` | `edgedb restore-database`
`edgedb self-upgrade` | `edgedb server self-upgrade`| Moving this command into the `server` namespace.
`edgedb   server destroy` | `edgedb server   destroy-instance`
`edgedb server info` | `edgedb server info-version`
`edgedb   server init` | `edgedb server   init-instance`|Or possibly `edgedb instance init`
`edgedb server install` | `edgedb server install-version`
`edgedb   server list-versions` | `edgedb server   list-version`
`edgedb server logs` | `edgedb server logs-instance`
`edgedb   server revert` | `edgedb server   revert-instance`
`edgedb server start` | `edgedb server start-instance`
`edgedb   server status` | `edgedb server   status-instance`
`edgedb server stop` | `edgedb server stop-instance`
`edgedb   server uninstall` | `edgedb server   uninstall-version`
`edgedb server upgrade` | `edgedb server upgrade-instance`
`edgedb   show-status` | `edgedb   show-migration-status-database`

**Comment by 1st1** [comment]
Hi David, thanks for the suggestions! We're actually redesigning our CLI just in time for our upcoming Beta 3 release. Read more about that here: https://github.com/edgedb/rfcs/blob/master/text/1006-simplified-cli.rst

The "server" vs "instance" vs "system" confusion is definitely still there, though. For the latter, most likely, we'll rename EdgeQL's statement `CONFIGURE SYSTEM` to `CONFIGURE INSTANCE`. As for the CLI, I'm not sure that adding `-instance` suffix to virtually all `server` subcommands would actually improve the DX. 

cc @edgedb/engineering

**Comment by DavidPratten** [comment]
Hi Yuri,

[RFC1006](https://github.com/edgedb/rfcs/blob/4229bac7a66cb5e0b97bf7ee2bca81ae6eae0a24/text/1006-simplified-cli.rst) is a great step for DX.  

Yes, renaming EdgeQL's statement `CONFIGURE SYSTEM` to `CONFIGURE INSTANCE` will remove a synonym from the glossary.

For further consideration, do any of the following suggestions add DX value?  The main focus is on clarifying which of the `server` commands are about the server context and which are about instance context.  Also a few suggestions to group database specific commands together in the same namespace.

| Command | Description | Which of these proposals increase regularity and improve DX? |
| -- | -- | -- |
| dump | Create a database backup | `database dump`
| restore | Restore a database backup from file | `database restore`
| config | Configure a DB or a server instance | _If the names of configurable flags/settings clearly indicate the object then this would be clear to developers._ Otherwise consider `database config` , `server config` and `instance config`.
| migration apply | Migrate the database to the latest revision |
| migration create | Create a new migration |
| migration log | Show the migrations log |
| migration status | Show the current migration state |
| migrate | An alias for `edgedb migration apply` |
| project init | Initialize a new EdgeDB project |
| project status | Show the status of the current project |
| project list | List all projects |
| project unlink | Clean-up the project configuration |
| server status | Status of an instance |
| server init | Initialize a new server instance | `instance init`
| server start | Start an instance | `instance start`
| server stop | Stop an instance | `instance stop`
| server restart | Restart an instance | `instance restart`
| server info | Show server information |
| server install | Install edgedb-server |
| server uninstall | Uninstall edgedb-server |
| server upgrade | Upgrade installations and instances | `instance upgrade` 
| server destroy | Destroy a server instance and remove the data stored | `instance destroy`
| server list-versions | List available and installed versions of the server |
| server logs | Show logs of an instance | `instance logs`
| server reset-password | Reset password for a user in the instance |
| database create | Create a new DB |
| database drop | Drop the DB |
| describe object | Describe a database object |
| describe schema | Describe the database schema |
| list | List matching database objects by name and type (run `edgedb list --help` for more info) | `instance list`
| self upgrade | Upgrade this tool to the latest version |
| self uninstall | Uninstall this tool |

**Comment by 1st1** [comment]
> database dump

We considered this, but the `dump` command can also dump multiple different databases at once. So nesting it into the `database` subgroup would be confusing.

> If the names of configurable flags/settings clearly indicate the object then this would be clear to developers. Otherwise consider database config , server config and instance config.

BTW, thanks to your GH threads we're keeping the `edgedb configure` name (the current `edgedb config` rename was done by mistake; I'll fix the RFC today). I'm not sure that splitting configuration into separate three commands would make it simpler, conceptually.

> instance init

I'm on the fence about this suggestion. There pros -- it's logical, and cons - more to type, more nesting. We'll discuss this proposal on one of our engineering calls this Wednesday or Friday.

**Comment by DavidPratten** [comment]
Thanks Yuri, for your prompt responses.  All good, however, I didn't follow your last point. 

> more to type, more nesting

The typing involved is of the same order as the RFC1006, and I'm not proposing deeper nesting.

My observation is that these commands operate in one context.

| Server Context |
| -- |
| edgedb server info |
| edgedb server install | 
| edgedb server uninstall |
| edgedb server list-versions | 

And that these commands operate in another. 

| Instance Context |
| -- |
| edgedb instance init |
| edgedb instance start |
| edgedb instance stop |
| edgedb instance restart |
| edgedb instance upgrade |
| edgedb instance destroy |
| edgedb instance logs |

**Comment by DavidPratten** [comment]
Hi @1st1,

Any update on the engineer's evaluation of this proposal for Beta 3?

Also on the proposed [DX implications of 'named instance' and possible improvements](https://github.com/edgedb/edgedb/issues/2651) 

Thanks
David

**Comment by 1st1** [comment]
Hi David, we're still working on implementing the current RFC. Probably won't have time to do anything else before the b3. The current changes are already invasive enough. That said we'll have a couple more internal discussions if we want to introduce `edgedb instance` or not.

**Comment by 1st1** [comment]
@DavidPratten We've release EdgeDB b3 with your recommendations implemented, David. Thanks so much for bringing this topic up!  https://www.edgedb.com/blog/edgedb-beta-3-ross
