### ISSUE TITLE
Docs: headerLink_anchor blocks links at the end of the previous section

### ISSUE THREAD

**Issue by KaelWD** [edgedb/edgedb#2673]
Example:
https://www.edgedb.com/docs/clients/01_js/usage#transactions
![image](https://user-images.githubusercontent.com/16421948/125198943-67927780-e2a7-11eb-87fe-639f82a42b4f.png)

I can't click the link to the Pool API because it's covered by the heading for the Transactions section.

**Comment by jaclarke** [comment]
Fixed in https://github.com/edgedb/edgedb.com/pull/323.

@1st1 Docs build is fixed now (#2650), so I think https://github.com/edgedb/edgedb.com/pull/323 is ready to be merged once it's approved.
