### ISSUE TITLE
Trying to update listen_addresses triggers ISE: address already in use

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#2696]
- EdgeDB Version: 1.0-beta.2+ga7130d5c7.cv202104290000 
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. create server instance
2. edgedb -I SERVER_NAME configure set listen_addresses 127.0.0.1 ::1 0.0.0.0

```python

edgedb error: ERROR: InternalServerError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 10700): address already in use
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "edb/server/protocol/binary.pyx", line 1694, in edb.server.protocol.binary.EdgeConnection.main
        File "edb/server/protocol/binary.pyx", line 950, in simple_query
        File "edb/server/protocol/binary.pyx", line 1045, in _simple_query
        File "edb/server/protocol/binary.pyx", line 1002, in edb.server.protocol.binary.EdgeConnection._simple_query
        File "edb/server/protocol/binary.pyx", line 1405, in _execute_system_config
        File "edb/server/dbview/dbview.pyx", line 515, in apply_config_ops
        File "edb/server/dbview/dbview.pyx", line 649, in apply_system_config_op
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta2/lib/python3.9/site-packages/edb/server/server.py", line 629, in _on_system_config_set
          await self._restart_servers_new_addr(value, self._listen_port)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta2/lib/python3.9/site-packages/edb/server/server.py", line 573, in _restart_servers_new_addr
          self._servers, _ = await self._start_servers(nethost, netport)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta2/lib/python3.9/site-packages/edb/server/server.py", line 786, in _start_servers
          tcp_srv = await self._loop.create_server(
        File "uvloop/loop.pyx", line 1768, in create_server
      OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 10700): address already in use
```

Despite the error, value is changed in config:
```
edgedb> SELECT cfg::DatabaseConfig.listen_addresses;
{'0.0.0.0', '127.0.0.1', '::1'}
```

**Comment by elprans** [comment]
It seems to me like we should explicitly check for `0.0.0.0` and either reject or ignore the other entries in the `listen_addresses` set.

**Comment by fantix** [comment]
It's a bit over-complex to reject the other entries if `0.0.0.0` is present before actually updating the system config into the database, and rejecting when starting the server is just as bad as the error reported in this issue. So I think I'll create a PR to simply ignore the other entries and print a warning log entry about the misconfiguration.

**Comment by 1st1** [comment]
> So I think I'll create a PR to simply ignore the other entries and print a warning log entry about the misconfiguration.

That works

**Comment by fantix** [comment]
Oh seems like this is not only an issue of `0.0.0.0` - the current `_restart_servers_new_addr()` method is simply binding to each new hosts without checking if we're already listening on that host. I'll also compute a diff, bind to newly-added hosts/ports and unbind the old ones that is no longer in the `listen_addresses`.

**Comment by fantix** [comment]
Ahhh asyncio `Server` doesn't support binding to new hosts or unbinding existing hosts on the fly ... so we'll likely have to customize asyncio server (maybe in uvloop) if we want to smoothly support "add a new host to the current `listen_addresses` list".

**Comment by 1st1** [comment]
> Found another bug: when using --port auto with multiple hosts, the bound port is not consistent on different hosts. I'll fix this in the same PR as the approach is the same.

I'm not sure this is fixable though. `port=auto` essentially means binding to port 0, and it's expected that the port would be different for different hosts, or am I missing something?

**Comment by fantix** [comment]
You're very much on the same page. I'm thinking about binding to those hosts sequentially, or at least bind to the first host first, get the port, and use that port for the remaining hosts. But the problem would then be that, binding to the same port on other hosts may fail due to conflict.

On the other hand, the issue for not fixing the `--port=auto` issue on multiple hosts is that, it's likely that only the first host works with the logged port - other hosts are having different ports (+1 incremental on at least macOS). Neither does `--emit-server-status` report all the ports.

**Comment by 1st1** [comment]
>  But the problem would then be that, binding to the same port on other hosts may fail due to conflict.

Exactly.

> Neither does --emit-server-status report all the ports.

I think we should fix this -- it should emit pairs of host/port. When `port=auto`, ports can be different for every host and that's fine. @elprans does this sound OK to you?

**Comment by fantix** [comment]
Also the admin UNIX socket file is named after a port - we should pick one port, or use PID instead 🤔

**Comment by 1st1** [comment]
I'm not sure I like the idea of picking one port for multiple hosts. We've been there before, see the git log. I really like the comfort of the OS selecting an available port for us in a non-racing fashion.

**Comment by 1st1** [comment]
Perhaps we shouldn't create admin sockets for `--port=auto` since that's used only in CI/testing.

**Comment by elprans** [comment]
> ports can be different for every host and that's fine.

I feel like this is too complicated for no good reason.  Is it possible to use the result of binding on the first address for the remaining sockets?  This will be fallible, but I think this failure mode is quite marginal, as, like is mentioned elsewhere, `--port=auto` is mostly used for testing and there multiple listen interfaces are unlikely.

**Comment by 1st1** [comment]
> Is it possible to use the result of binding on the first address for the remaining sockets?

It is possible, but it is racy. I also don't view it as super complicated; the recommendation will be "don't configure the server to use multiple hosts with port=auto". On the server side of things, outputting pairs of host/port in emit-server-status is more future-proof anyways.
