### ISSUE TITLE
Can't use backlinks if a link with the same name is computed

### ISSUE THREAD

**Issue by kafein** [edgedb/edgedb#2698]
- EdgeDB Version: 1.0b2+ga7130d5c7.cv202104290000  
- OS Version: macOS Big Sur / MacBook Air (M1, 2020) /  Memory: 8 GB 

Steps to Reproduce:

Simplified Schema;

```
using extension graphql;

module default {
    type User {
        required property email -> str {
            constraint exclusive;
        }
        multi link entries := .<author[IS Entry]; 
    }

    type Entry {
        link author -> User; 
        link topic := .<entries[IS Topic];
    }

    type Topic {
        multi link entries -> Entry; 
    }
};
```
GraphQL Query;
```
User {
      email
      entries {
        topic {
          id
        }
      }
}
```

When trying to use this query I am getting **"QueryError: relation \"edgedbpub.718fcee6-e765-11eb-9572-8bb96a65cb68_t\" does not exist"** error

With the following schema change it's working well. I think this is a name collision issue. I wonder if this is a bug or am I doing something wrong?

```
using extension graphql;

module default {
    type User {
        required property email -> str {
            constraint exclusive;
        }
        multi link entries := .<author[IS Entry]; 
    }

    type Entry {
        link author -> User; 
        link topic := .<topic_entries[IS Topic];
    }

    type Topic {
        multi link topic_entries -> Entry; 
    }
};
```

**Comment by msullivan** [comment]
It is definitely a bug that you get *that* error!

Whether it should be accepted is a more complicated question, but I think the answer is "probably yes"? The tricky thing here is that we don't allow backlinks of computable links. (If you ask for `.<entries` in the second schema, you'll get an error). So then the questions are:
 * What should we do about `.<entries` if one of the links named `entries` is computable?
 * Should we do something different when there's a type intersection after, like `.<author[IS Topic]`?

**Comment by kafein** [comment]
@msullivan Will you add a bug tag to this issue? Otherwise this restriction should be documented.

**Comment by 1st1** [comment]
@msullivan Sully, has this one been fixed?

**Comment by kafein** [comment]
I know you are very busy with too many issues and I really appreciate your efforts. Just wondering, is this issue will be fixed in short term? I've just started a pet project and this issue blocking me. Good luck!

**Comment by msullivan** [comment]
@kafein yeah, this will either be fixed or made to produce an error (though I think probably fixed). It shouldn't be blocking you though, since you can work around it with a name change?

**Comment by kafein** [comment]
@msullivan Thanks for information. Yes I can do it, but generally I don't like workarounds much :) Just want to check to see if you have a plan to fix this. 

Great project, great team. Good luck!

**Comment by msullivan** [comment]
It looks like we do now produce a proper error:
```cannot follow backlink 'entries' because link 'entries' of object type 'default::User' is computed```

**Comment by kafein** [comment]
@msullivan Great job! Thanks
