### ISSUE TITLE
Wrong results for a combination of shape, path and multiple inheritance.

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#2708]
See [test_edgeql_computable_nested_02](https://github.com/edgedb/edgedb/blob/46bd8847158e84c2ae9b82c0e86697ed631e531a/tests/test_edgeql_expr_aliases.py#L375-L405) and [test_edgeql_computable_nested_03](https://github.com/edgedb/edgedb/blob/46bd8847158e84c2ae9b82c0e86697ed631e531a/tests/test_edgeql_expr_aliases.py#L407-L440).

The following query is producing wrong results for `typename`: 
```
WITH C := Card { ava_owners := .<avatar }
SELECT C {
    name,
    ava_owners: {
        multi typename := (
            WITH name := C.ava_owners.__type__.name
            SELECT name
        )
    }
}
FILTER EXISTS .ava_owners
ORDER BY .name;
```

The `typename` as specified should fairly trivially always be a `singe` result for any given `ava_owner`, however, it produces multiple results when the "owners" can be of different (related) types.

**Comment by elprans** [comment]
Fixed by #2715.
