### ISSUE TITLE
Confusing `__slots__` behavior of `struct.ProtoField` subtypes

### ISSUE THREAD

**Issue by sobolevn** [edgedb/edgedb#2723]
After fixing https://github.com/edgedb/edgedb/pull/2722 I realiazed that probably current `edb/schema/objects.Field` behavior is not what users / developers might expect.

Since it has `__slots__` defined without explicit `__dict__`, it is expected to fail on unknown attribute assign.
But, this does not happen right now, because `struct.ProtoField` does not have `__slots__`, but has `__dict__`.

Short repro:

```python
class A:
   ...

class B(A):
    __slots__ = ('b',)
    def __init__(self) -> None:
        self.a = 1  # works, but is missing from slots
        self.b = 2  # ok
```

So, there are two ways of "fixing" this:
1. Add empty `__slots__` to `struct.ProtoField` (I will go this way for now, feel free to correct me)
2. Add explicit `__dict__` to `__slots__` of `edb/schema/objects.Field` and friends

**Comment by elprans** [comment]
Adding empty `__slots__` to `ProtoField` seems OK to me.  @msullivan?
