### ISSUE TITLE
edgedb project init failed

### ISSUE THREAD

**Issue by ovverd** [edgedb/edgedb#2828]
- EdgeDB Version: 1-Beta3
- OS Version: Mac OSX

`ImportError: dlopen(/Library/Frameworks/EdgeDB.framework/Versions/1-beta3/lib/edgedb-server-1-beta3/lib/python3.10/site-packages/_cffi_backend.cpython-310-darwin.so, 2): Library not loaded: /usr/local/opt/libffi/lib/libffi.7.dylib Referenced from: /Library/Frameworks/EdgeDB.framework/Versions/1-beta3/lib/edgedb-server-1-beta3/lib/python3.10/site-packages/_cffi_backend.cpython-310-darwin.so Reason: image not found`

'Image Not found error' Occurred and Failed

If you look closely at the error, it says something about libffi.

you have to

`brew reinstall libffi`

**Comment by 1st1** [comment]
Hi, thanks for submitting the issue. Why did you close it? Have you been able to resolve it?

**Comment by elprans** [comment]
This was fixed in https://github.com/edgedb/edgedb-pkg/issues/46, however the CLI still seems to be picking up the old broken build.

**Comment by elprans** [comment]
Opened https://github.com/edgedb/edgedb-cli/issues/477

**Comment by laosb** [comment]
Reinstalling libffi doesn't fix this problem for me.
