### ISSUE TITLE
Failing to install native/docker package on M1 Mac

### ISSUE THREAD

**Issue by limx0** [edgedb/edgedb#2940]
- EdgeDB Version: `1.0b3+gb4f275394.cv202108020000` / `nightly`
- OS Version: Macos Big Sur (11.5.2) - M1 Macbook Pro

Steps to Reproduce:

1. Install edgedb cli
2. Install server via `edgedb server install`
3. Install instance via `edgedb instance create test`

Setting debug logging shows a bunch of 

```
[2021-09-15T21:15:03Z DEBUG edgedb_client::builder] Temporary connection error: No such file or directory (os error 2)
[2021-09-15T21:15:03Z DEBUG edgedb_client::builder] Is temporary? Os {
        code: 2,
        kind: NotFound,
        message: "No such file or directory",
    }
```

**Comment by tailhook** [comment]
These debug messages are fine. Try `RUST_LOG=debug,edgedb_client::builder=info` or `RUST_LOG=info` to filter them out.

**Comment by limx0** [comment]
Thanks for the prompt response @tailhook. It looks like this is actually failing on the specific database name I'm trying to create. It works fine with `test` or `database` but not `property_database` for some reason.

**Comment by limx0** [comment]
Final few lines of output:

```
[2021-09-15T21:34:49Z INFO  edgedb::process] Running "launchctl" "enable" "gui/501/edgedb-server-propertydatabase"
[2021-09-15T21:34:49Z INFO  edgedb::process] Running "launchctl" "bootstrap" "gui/501" "/Users/brad/Library/LaunchAgents/com.edgedb.edgedb-server-propertydatabase.plist"
[2021-09-15T21:34:49Z INFO  edgedb::process] Running "launchctl" "kickstart" "gui/501/edgedb-server-propertydatabase"
[2021-09-15T21:34:49Z DEBUG edgedb_client::tls] Loading native root certificates
[2021-09-15T21:34:49Z INFO  edgedb_client::builder] Connecting via Unix `/Users/brad/Library/Caches/edgedb/run/propertydatabase/.s.EDGEDB.admin.10704`
[2021-09-15T21:35:19Z ERROR edgedb::server::create] Bootstrap error, cleaning up...
```

And full log: [log.txt](https://github.com/edgedb/edgedb/files/7173417/log.txt)

**Comment by limx0** [comment]
I'm going to close this now because I've just changed the name of my db. Still unclear why it's failing though.

**Comment by tailhook** [comment]
Sorry for the late reply. I needed to check it myself, and I have to admit that I can't reproduce the issue.

We had a limitation recently that long names were not working. But it doesn't look like the case for you. So there are two things to check:
1. Take a look in a log ~/Library/Caches/edgedb/logs/propertydatabase.log if that's still there
2. Try running `edgedb instance destroy propertydatabase` and then create again. Guess here is that you have interrupted the build at some point (or got a different error) and then restarted, while some files specific to the instance have left. `destroy` should take care of that. But let us know if this is the case so we can make it work without destroy too.

Also we probably need better logging settings propagated through CLI and/or even better default logging. Will look into that.

**Comment by limx0** [comment]
Okay @tailhook it looks like it might have been the path length issue.

I see this error in that log
```
2021-09-16 07:34:51.175 AEST [70696] LOG:  database system is shut down
---- Exception occurred: AF_UNIX path too long ----

1. OSError: AF_UNIX path too long
```

**Comment by elprans** [comment]
@limx0, could you attach the whole log or paste a bit more context around the error please?  From the earlier snippets it isn't clear why any Unix socket path in EdgeDB would exceed the OS limit in your case.

**Comment by limx0** [comment]
Hey @elprans - [stdout](https://github.com/edgedb/edgedb/files/7213953/property_database_stdout.txt) and [~/Library/caches](https://github.com/edgedb/edgedb/files/7213954/property_database.log) logs

**Comment by elprans** [comment]
Thanks, @limx0.  It seems like the crash is in the internal process pool initialization which uses Unix sockets for IPC.  However, it's still a mystery why the failure is there, since the full path of the Unix socket should be `/Users/limx0/Library/Caches/edgedb/run/property_database/edgedb-internal-xxxxxxxx/compilers.socket`, a 98 character string, which is below the 108 character limit for Unix socket paths on macOS.  The only scenario that comes to mind is that `--runtime-dir` gets a relative path and that doesn't get canonicalized before the socket is created. @tailhook, @fantix any thoughts?

**Comment by limx0** [comment]
@elprans  - I've abbreviated my actual username above (its actually >20 characters, not limx0) which probably explains it.

**Comment by elprans** [comment]
Oh, yes, that explains it.  We'll look into trimming the lengths of the socket paths as much as possible #2954 should help, but, importantly we also need to shorten the IPC socket paths.  Unfortunately, shortening will not make this issue go away completely as a very long username+instance name combination would still trigger this.  We'll likely need to add an ahead of time check to make this failure more user-friendly.
