### ISSUE TITLE
Query fails at EdgeDB clients (golang, py, js) but not the REPL

### ISSUE THREAD

**Issue by clmno** [edgedb/edgedb#2943]
- EdgeDB Version: EdgeDB 1.0-beta.3+g8ab4a7be0.cv202108020000 (repl 1.0.0-beta.3)
- OS Version: Ubuntu

## Issue
1. Query fails when using EdgeDB client, but works when the REPL is used.

The error:
> edgedb.InternalServerError: column User~2.target does not exist

## Steps to Reproduce:

1. Clone the repo - [Link](https://github.com/clmno/edgedb_client_error_report)
    ```
    get clone https://github.com/clmno/edgedb_client_error_report.git
    ```
2. Update `go`. `python` and `javascript` dependencies using their corresponding tools
    ```
    go mod download
    poetry install
    yarn install
    ```
3. Migrate EdeDB and populate the DB with the queires in `init_queries.edgeql`
    ```sql
    INSERT Company {name := "ABC"};
    INSERT Company {name := "XYZ"};
    INSERT User {
        name := "Alice", company := {
            (SELECT Company FILTER .name = "ABC"),
            (SELECT Company FILTER .name = "XYZ")
        }
    };
    INSERT User {name := "Bob"};
    
    # This one will fail with the error: edgedb.InternalServerError: column User~2.target does not exist
    SELECT User {id, name, c := .company.id};
    ```
4. Run each of the client implementation to find the same exception
    > edgedb.InternalServerError: column User~2.target does not exist
5. The query
    ```sql
    SELECT User {id, name, company_id := .company.id}
    ```

Here a quick look at the python client

```python

import edgedb

conn = edgedb.connect('edgedb_error')
query = '''SELECT User {
            id,
            name,
            company_id := .company.id
        }'''
print(f"result :{conn.query(query)}")

conn.close()
```

**Comment by 1st1** [comment]
@msullivan @elprans any ideas?

**Comment by jaclarke** [comment]
The error can be reproduced in the CLI with implicit limit disabled (`\set limit 0`). It specifically seems to be this part of the query that causes the error: `select User {company_ids := .company.id}` (this query works: `select User {company_names := .company.name}`).

As a workaround, this query seems to work: `select User {company_ids := (select .company).id}`.

**Comment by msullivan** [comment]
`SELECT User {id, name, card_ids := .deck.id}` repros this in our `cards` test database
