### ISSUE TITLE
Shorten the length of internal Unix socket paths

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#2954]
Move postres socket to runtime-dir instead of data-dir.

This should allow longer names for the database instances since runtime dir is often shorter.

One of such issues is here: https://github.com/edgedb/edgedb/issues/2940#issuecomment-923283784 although it's not entirely clear why socket length overflows in that case yet.

**Comment by elprans** [comment]
Per further investigation in #2940, the actual failing component is the compiler pool IPC socket which uses a needlessly long path, so we need to trim that also.
