### ISSUE TITLE
A query playground. 

### ISSUE THREAD

**Issue by spa5k** [edgedb/edgedb#3019]
What I want to see is a type of Query playground, like how graphql playground is, or how new prisma playground is.

Not only it'll make discovering queries much easier, it'll also bring more people in due to sheer ease of usage.

The playground can provide suggestions like intellisense do in typescript, or graphql playground does. It'll make building optimal queries much easier.

As an additional feature, it can also provide language specific snippets generated automatically from the language like how they do in supabase.

**Comment by elprans** [comment]
We have a notebook-style interactive showcase that lets you try and modify various queries on a predefined schema at https://www.edgedb.com/tutorial. 

A more elaborate playground is in the works.

**Comment by spa5k** [comment]
Very impressive work you guys are doing.

**Comment by CodesInChaos** [comment]
Is there any update on the "more elaborate playground"?
