### ISSUE TITLE
Syntax update: "WITH := MODULE" to "WITH AS MODULE"

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#302]
Currently:

```
WITH
   a := MODULE aaa
SELECT
   a::Type;
```

Proposed:

```
WITH
   a AS MODULE aaa
SELECT
   a::Type;
```

The key problem with the current approach is that this violates the general rule of thumb: we always have EdgeQL on the righthand side of `:=`.  `MODULE ident` is not a valid EdgeQL expression; it's a special syntax valid only in `WITH` blocks.

Changing `:=` to `AS` fixes this discrepancy, and in addition to that:

1. Makes it possible to have type aliases needed for https://github.com/edgedb/edgedb/issues/219.

2. Makes aliasing in `WITH` consistent with aliasing of schema types in DDL, as in:

   ```
   CREATE FUNCTION foo(a: SET OF int64) -> in64 {
     SET finalizer AS FUNCTION() -> int64 $$ ... $$;
   }
   ```

3. Allows us to implement lambda functions at some point, see https://github.com/edgedb/edgedb/issues/301 for details.

**Comment by elprans** [comment]
Done in #354
