### ISSUE TITLE
edgedb error: InternalServerError: dependency cycle

### ISSUE THREAD

**Issue by sfermigier** [edgedb/edgedb#3027]
- EdgeDB Version: 1.0rc1
- OS Version: MacOS 10.15.7

Steps to Reproduce:

I have created and run 3 migrations, now it seems there is an internal issue in the server:

```
> edgedb migration create
edgedb error: InternalServerError: dependency cycle between ('delete', 'default::__|name@default|Employer') and ('rebase', 'default::Employer')

> edgedb migration status
edgedb error: InternalServerError: dependency cycle between ('delete', 'default::__|name@default|Employer') and ('rebase', 'default::Employer')

> edgedb migration log --from-db
m1ikvvdzvzmdjenuzzvlwyqpocfu5vbzy7oq2vitlj3sm2kkpngqja
m1it4vuijzlnmxq7k44lilmpxv545taxi7hery7rfpeidlr25ongtq
m1onvevhe4iy5oijoxwtbqglmqtfmd4h4nbhvz4auoea3xyhq4pveq

> edgedb migration log --from-fs
m1ikvvdzvzmdjenuzzvlwyqpocfu5vbzy7oq2vitlj3sm2kkpngqja
m1it4vuijzlnmxq7k44lilmpxv545taxi7hery7rfpeidlr25ongtq
m1onvevhe4iy5oijoxwtbqglmqtfmd4h4nbhvz4auoea3xyhq4pveq

# (I then create a new instance and apply the migrations)

> edgedb -I joinux2 migration apply
Applied m1ikvvdzvzmdjenuzzvlwyqpocfu5vbzy7oq2vitlj3sm2kkpngqja (00001.edgeql)
Applied m1it4vuijzlnmxq7k44lilmpxv545taxi7hery7rfpeidlr25ongtq (00002.edgeql)
Applied m1onvevhe4iy5oijoxwtbqglmqtfmd4h4nbhvz4auoea3xyhq4pveq (00003.edgeql)
> edgedb -I joinux2 migration status
edgedb error: InternalServerError: dependency cycle between ('delete', 'default::__|name@default|Employer') and ('rebase', 'default::Employer')
```

I'd rather not publish my schema and my migrations, as it's not a public project.

I don't care about the issue right now, as I'm still developing the application, but I would be worried if it happened in production.

**Comment by elprans** [comment]
Hi Stefane,

The error is very specific to the migration, so it'd be tremendously helpful if you could share the schema and the migrations.  If you're not comfortable posting to Github, you can send them via email to `elvis @edgedb.com` or send me a private message in [Discord](https://discord.gg/tU97MX6Q)

**Comment by msullivan** [comment]
I took a look at what you shared with us out of band, and came to the conclusion that you ran into the same cluster of issues as #2399 (the dependency cycle part of which has been fixed, though there were enough other problems that it still probably won't work---see #3118 and #3119).

Thanks!
