### ISSUE TITLE
Rethink cardinality

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#303]
Problems with the current way of setting link/property cardinality:

* `**` and `*1`-like symbols turn out to be challenging to understand:

  ```
  link foo -> Foo:
    cardinality := '**'
  ```

* In addition to the "cardinality" property we also have a `required` modifier, which is also related to the cardinality of a link.

* Cardinality of a link is its core property.  It's suboptimal to express it as an attribute.

* We need to invent extra syntax for queries to inform the compiler of the query cardinality.  At one point we had `SINGLETON` keyword, which was eventually replaced with `WITH cardinality '*' SELECT`.  Both of those are unintuitive and require deep understanding of EdgeDB data model and of EdgeQL in order to be used correctly.

The alternative design is to:

* Replace cardinality settings we have now (`1*`, `11`, `**`, and `*1`) with simpler `single` and `multi` qualifiers:

  ```
  multi link foo -> Foo
  required link bar -> Bar
  required multi link baz -> Baz
  ```

  This allows us to express `**` and `*1` cardinalities.

* Enforcing `1*` and `11` can be done via an `exclusive` constraint:

  ```
  multi link foo -> Foo:
    constraint exclusive
  ```

* In select shapes we can now use `required` and `single`/`multi` qualifiers to define computables:

  ```
  SELECT User {
    required foo := (SELECT 1),  # required single property
    required multi bar := (SELECT 2)  # required multi property

    single foo := (expr)  # the compiler will statically check 
                          # that "expr" has cardinality "1"
  }
  ```

* `WITH cardinality '*'` syntax is no longer needed.

**Comment by elprans** [comment]
Note: the `exclusive` constraint above is simply a current `unique` with a more appropriate name.  It is more natural to say that a given **relationship** is *exclusive*, rather than *unique*.  For example, in the relationship `Person -> owns -> Chair`, "this chair is exclusive to this person" is better than "the Person/Chair relationship is unique".
