### ISSUE TITLE
`naive_date` becomes `naive_datetime` after arithmetic with `timedelta`

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#311]
Example of the offending query:
```
SELECT <naive_date>'2017-10-10' + <timedelta>'1 day';
```

This is reflected in `test_edgeql_dt_naive_date_01`.

**Comment by elprans** [comment]
This is expected.

**Comment by vpetrovykh** [comment]
After some deliberations we agreed that various datetime scalars can be added to `timedelta` and the result type is the same as the original datetime scalar.

This has been implemented in #365
