### ISSUE TITLE
Describe instance config yields invalid values for timeouts

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#3139]
- EdgeDB Version: 1.0-rc.2+dev6155.d2021110503.g2dcab136e.cv202111031900

```
edgedb> describe instance config;
{'CONFIGURE INSTANCE SET session_idle_timeout := \'PT10M\';CONFIGURE INSTANCE SET session_idle_transaction_timeout := \'PT0S\';'}
```
1. There is no `<duration>` qualification
2. `session_idle_transaction_timeout` has default value so should not be emitted

(related failures https://github.com/edgedb/edgedb-cli/pull/543 / [build](https://github.com/edgedb/edgedb-cli/runs/4120321539))

**Comment by elprans** [comment]
I can't reproduce the default value thing.  Are you sure you haven't overridden it?

**Comment by tailhook** [comment]
> I can't reproduce the default value thing. Are you sure you haven't overridden it?

This is weird. I can reproduce it on the newly created DB on: `1.0-rc.2+dev6160.d2021110621.g69c3b45b2.cv202111050000`
