### ISSUE TITLE
Changing type of overloaded link leads to weird errors during migration creation

### ISSUE THREAD

**Issue by CodesInChaos** [edgedb/edgedb#3183]
- EdgeDB Version: 1-rc2
- OS Version: xubuntu 20.04.3

Steps to Reproduce:

Running `edgedb migration create --non-interactive --allow-unsafe` using the schema below returns the following error:

> edgedb error: SchemaError: link 'entity' of object type 'default::DogVersion' cannot be cast automatically from object type 'default::Versioned' to object type 'default::Dog'
  Hint: You might need to specify a conversion expression in a USING clause
  Server traceback: [...]

The interactive version is even worse, it gets stuck in an endless loop attempting to roll back a step.

Schema:
```
module default {
	abstract type Version {
		required link entity -> Versioned {
			readonly := true;
		}
	}

	abstract type Barks {
	}

	abstract type Versioned {
	}

	type DogVersion extending Version, Barks {
		overloaded required link entity -> Dog;
	}

	type Dog extending Versioned {
		multi link versions := (SELECT Dog.<entity[IS DogVersion]);
	}

	type CatVersion extending Version {
		overloaded required link entity -> Cat;
	}

	type Cat extending Versioned {
	}
}
```

This example is very fragile, even apparently unrelated changes like removing `Barks` from `Dog` or renaming types can lead to it successfully creating a migration.

The migration it produces when I remove `Barks` from `Dog`:

```
CREATE MIGRATION m1qqz546xpyqxoha4ipcw3upqbnzzudphdkihdojuu6bbui4r53gwq
    ONTO initial
{
  CREATE ABSTRACT TYPE default::Barks;
  CREATE ABSTRACT TYPE default::Versioned;
  CREATE TYPE default::Cat EXTENDING default::Versioned;
  CREATE ABSTRACT TYPE default::Version {
      CREATE REQUIRED LINK entity -> default::Versioned {
          SET readonly := true;
      };
  };
  CREATE TYPE default::CatVersion EXTENDING default::Version {
      ALTER LINK entity {
          SET OWNED;
          SET REQUIRED;
          SET TYPE default::Cat;
      };
  };
  CREATE TYPE default::Dog EXTENDING default::Versioned;
  CREATE TYPE default::DogVersion EXTENDING default::Version {
      ALTER LINK entity {
          SET OWNED;
          SET REQUIRED;
          SET TYPE default::Dog;
      };
  };
  ALTER TYPE default::Dog {
      CREATE MULTI LINK versions := (SELECT
          default::Dog.<entity[IS default::DogVersion]
      );
  };
};
```

I also had a variant where interactive mode asked for a conversion expression for such a link.

**Comment by elprans** [comment]
```
CREATE TYPE DogVersion EXTENDING default::Version ...;
CREATE TYPE default::Dog EXTENDING default::Versioned;
ALTER TYPE DogVersion ALTER LINK entity SET TYPE default::Dog;
```

Taken in isolation `ALTER TYPE` requires a `USING` conversion expression as you cannot simply change the type from `Versioned` to `Dog` because there might already be data in the link.   In this case, it's nonsensical of course, because the `ALTER` was generated from the initial creation.

**Comment by elprans** [comment]
@msullivan, I propose we note that `ALTER` is the result of breaking down a `CREATE` and automatically inject `USING (.link[IS NewTarget])` into any generated `SET TYPE`.  It'd also be great if we could place a check so that we never emit `SET TYPE` without `USING` if one is mandatory for the operation.

**Comment by CodesInChaos** [comment]
Would it be possible to use a type assertion which fails if an invalid link exists, instead of a filter which silently removes it?

**Comment by elprans** [comment]
Good question.  I think `assert_type` could be useful in this scenario, although I'd also consider adding a generic `assert(condition: bool, message: OPTIONAL str)` instead.

**Comment by CodesInChaos** [comment]
Besides fixing the DDL generation, it might also be a good idea to change how the CLI reacts to errors, since the interactive mode going into an endless loop looks like broken error handling.

**Comment by elprans** [comment]
The endless loop is a separate bug, yes.
