### ISSUE TITLE
Don't have `{}` act as a wildcard in `assert_query_result`

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#3196]
For assert_query_result, the empty dict `{}` currently acts as a "wild card", that will match anything.

This is because it checks each element in the dict, and so if the dict is empty, it doesn't look at the returned data at all.

I think we should make sure that `{}` only matches dictionaries, and should add in a separate wildcard facility.
We should maybe also have it check that the result dictionary doesn't contain any *extra* keys, except for `id` and `__tname__`. (We don't really have a good way to distinguish between named tuples and objects in this interface, so I don't think we can do the *best* thing and *insist* that those are inserted when appropriate).

**Comment by 1st1** [comment]
+1
