### ISSUE TITLE
Migration creation fails despite no questions asked

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb#3208]
In a project with lots of migrations, I'm no longer able to create new migrations. The `edgedb migration create` command fails without asking any questions.

```
$ edgedb migration create
edgedb error: EdgeDB could not resolve migration with the provided answers. Please retry with different answers.
```

This is a path-dependent problem - when I deleted the existing migrations and “squashed” them into a single new migration this went away. 

Repro

```
git clone git@github.com:colinhacks/lotsa-migrations.git
cd lotsa-migrations
edgedb project init
edgedb migration create
```

[lotsa-migrations.zip](https://github.com/edgedb/edgedb/files/7584266/lotsa-migrations.zip)

**Comment by msullivan** [comment]
Fortunately, the lots of migrations part of this was a red herring. Migrating from
```
module default {
  type Bag {
    property switching_tuple -> tuple<name: str, age: int64>;
  };
}
```
to
```
module default {
  type Bag {
    property switching_tuple -> tuple<name: str, weight: int64>;
  };
}
```
is the issue.

Hopefully shouldn't be tough.

**Comment by 1st1** [comment]
> Fortunately, the lots of migrations part of this was a red herring. Migrating from

Why was the CLI "hanging" though?

**Comment by tailhook** [comment]
> > Fortunately, the lots of migrations part of this was a red herring. Migrating from
> 
> Why was the CLI "hanging" though?

It wasn't hanging it errors out with "could not resolve migration", as far as I can see.
