### ISSUE TITLE
cannot bootstrap EdgeDB instance While trying edgedb project init

### ISSUE THREAD

**Issue by J-Nova** [edgedb/edgedb#3297]
- EdgeDB Version: 1.0-rc.3+2b303d3
- OS Version: MacOS Monterey 12.2 Beta, Apple air m1 2020

Steps to Reproduce:

1. running edgedb project init
2. Gives these errors: https://ibb.co/H4MyF5S

Version 1.0-rc.3+2b303d3 is already installed
Initializing EdgeDB instance...
[edgedb] CRITICAL 5103 2021-12-19T15:41:24.861 edb.server: the length of the specified path for server run state exceeds the maximum of 82 bytes: '/Users/juuppikkemaat/Library/Application Support/edgedb/data/.~TradingBacktester.tmp' (84 bytes)
edgedb error: cannot bootstrap EdgeDB instance: bootstrap failed: exit status: 1 (command-line: "/Users/juuppikkemaat/Library/Application Support/edgedb/portable/1.0-rc.3/bin/edgedb-server" "--bootstrap-only" "--data-dir" "/Users/juuppikkemaat/Library/Application Support/edgedb/data/.~TradingBacktester.tmp" "--tls-cert-mode=generate_self_signed" "--bootstrap-command" "\n            ALTER ROLE edgedb {\n                SET password_hash := \"SCRAM-SHA-256$4096:vEHs/JJPllVZ5jKrrlfLDQ==$zisdYOLImYj+Zek77ZYc59C1ko+blgxXJKkdxHwnnIM=:zM6/z87SnF4b9TT62pXkrW0Z2B42gIzZgKL3q4lV2VY=\";\n            };\n            ")

Getting this bug/error, dont know how to fix it neither dont know if its a fault on my side or something else. any input / help is appreciated.

**Comment by elprans** [comment]
The key part is

> edb.server: the length of the specified path for server run state exceeds the maximum of 82 bytes

This is because the combined length of your OS username and the name of the DB instance cause an internal Unix socket path to be longer than is supported by the OS.  Reduce the length of the instance/project name and it should work.

@tailhook, ideally we need to trap this error in CLI and show a hint similar to the above.  I'll see that we exit with a specific exit code to avoid matching the message string.

**Comment by J-Nova** [comment]
> 

Okey, reduced my folder its name to 3 characters and now works! Thanks for the quick help.

**Comment by tailhook** [comment]
@elprans, this is interesting. I thought there is no unix socket creation during bootstrap. As later:
1. Runstate dir is in `Caches` so it 14 chars shorter
2. There is no `.~<snip>.tmp` in path so path is 6 chars shorter

So did we start creating unix sockets or this check is superfluous? Apparently I can fix it anyway by using `--runstate-dir` during bootstrap.

**Comment by elprans** [comment]
> So did we start creating unix sockets or this check is superfluous?

We create and use a Postgres Unix socket at bootstrap.

> Apparently I can fix it anyway by using `--runstate-dir` during bootstrap.

Yes, that's what we should do.  And still do the exit code thing since it's possible to overflow the limit even with a shorter `runstate-dir`.

**Comment by comwt** [comment]
Hi all!

FYI, this issue still appears to be occurring with EdgeDB Version 2.14+7aec755.  I tried troubleshooting the install for a while when the following message was displayed and then I searched and found this thread about the instance name length:

`[edgedb] CRITICAL 20488 2023-04-30T00:35:11.678 postgres: lock file "/run/user/1000/edgedb-server/.s.PGSQL.5432.lock" already exists
[edgedb] WARNING 20463 2023-04-30T00:35:11.682 edb.server: server bootstrap did not complete successfully, removing the data directory
[edgedb] ---- Exception occurred: The backend exited with 1 ----
[edgedb] 
[edgedb] 3. FileNotFoundError: [Errno 2] No such file or directory: '/home/<user>/.local/share/edgedb/data/.~server.tmp/postmaster.pid'
[edgedb] 
[edgedb] ---- Traceback ----
. . .
edgedb error: cannot bootstrap EdgeDB instance: bootstrap failed: exit status: 1 (command-line: "/home/<user>/.local/share/edgedb/portable/2.14/bin/edgedb-server" "--bootstrap-only" "--data-dir" "/home/<user>/.local/share/edgedb/data/.~server.tmp" "--runstate-dir" "/run/user/1000/edgedb-server" "--tls-cert-mode=generate_self_signed" "--jose-key-mode=generate" "--bootstrap-command" "\n            ALTER ROLE edgedb {\n                SET password_hash := \"SCRAM-SHA-256$4096:DDjnadf9fq3qxTMcpRmRwA==$vG9y8jZlzPucsibbyLYPa0tzyqySuMwXeajuObO0xNQ=:xHHb/ElKq5ifYt4fnn5853i23AImSU41V3T5uSLKKDM=\";\n            };\n            ")`

After using a shorter name, the install completed successfully!

Thanks for all your hard work. :)
