### ISSUE TITLE
can not delete Vampire: InternalServerError: column "dde51130-637a-11ec-81ea-854924cb81a5" does not exist

### ISSUE THREAD

**Issue by slavugan** [edgedb/edgedb#3309]
- EdgeDB Version: EdgeDB 1.0-rc.3+147eb62 (repl 1.0.0-rc.4+eb50f45)
- OS Version: Ubuntu 20.04.3

Steps to Reproduce:

1. Download project https://drive.google.com/file/d/1lkK-0AJRg_0QONZnGHiojdMygdoWTGsY/view?usp=sharing
2. unpack project
3. go to project directory and init project `edgedb project init`
4. in edgedb shell insert a Vampire object `INSERT Vampire {name := 'Some Name'};`
5. try to delete Vampire `DELETE Vampire;`
at this moment I get this error:
`edgedb error: InternalServerError: column "dde51130-637a-11ec-81ea-854924cb81a5" does not exist
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: column "dde51130-637a-11ec-81ea-854924cb81a5" does not exist`

Current error is caused by one of migrations in the project. If I create migration from scratch for existing schema there are no problems with deleting Vampire.

**Comment by msullivan** [comment]
I think the issue is going to be some busted trigger stuff.

**Comment by msullivan** [comment]
Minimized test case:
```
create type Foo;
create type Bar { create link foo -> Foo; };
alter type Bar { drop link foo; };
insert Foo;
delete Foo;
```
