### ISSUE TITLE
InvalidReferenceError when migrating to a schema with a nested alias

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#3371]
- EdgeDB Version: rc4 (current master)
- OS Version: linux

Try migrating to this schema:
```
type Bar;
type Foo;
alias DeepAlias := (
    select Foo {
        bars := (
            select Bar {
                extra_data := 'only in alias'
            }
        ),
    } limit 2
);
```
Get the following error: `edgedb error: InvalidReferenceError: object type '__default::Foo' does not exist`

Unlike #3369 this only happens in SDL mode, while breaking down the schema into 3 DDL commands works just fine. So this is much more likely to be an ordering issue.

**Comment by msullivan** [comment]
This seems fixed
