### ISSUE TITLE
Missing reserved keyword 'Release' in documentation

### ISSUE THREAD

**Issue by rdlaitila** [edgedb/edgedb#3386]
- EdgeDB CLI 1.0.0-rc.6+4b9d831
- EdgeDB Instance 1.0-rc.4+1850eff

Steps to Reproduce:

1. Create a schema type named `Release`
2. attempt to create a migration `edgedb migration create`
3. observe error `error: Unexpected 'Release'`

Schema:

```
module software {
	type Release {
		required property version -> str;
	}
}
```

I was unable to locate `Release` as a reserved keyword in the docs https://www.edgedb.com/docs/reference/edgeql/lexical#names-and-keywords 

Subjective minor annoyance not being able to use the suspected keyword as a type name. 

Thanks!

**Comment by elprans** [comment]
Actually, `release` doesn't _have_ to be reserved.  I've opened #3387 to unreserve it and a few others.  

@vpetrovykh, please sync the documentation keyword list with that of the tokenizer (ideally we should generate the list).

**Comment by msullivan** [comment]
Fixed a long time ago
