### ISSUE TITLE
Setting a type as abstract preserves existing data

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#3399]
```
edgedb> create type Foo;
OK: CREATE TYPE
edgedb> insert Foo;
{default::Foo {id: 6d4cab68-8528-11ec-b417-ab253b541761}}
edgedb> alter type Foo { set abstract; };
OK: ALTER TYPE
edgedb> select Foo;
{default::Foo {id: 6d4cab68-8528-11ec-b417-ab253b541761}}
```

Since it isn't possible to insert into an abstract type, I would expect that the abstract type shouldn't be able to contain data either?

It seems that on the pgsql schema side we don't have any special handling of abstract types at all, and they get tables and everything.

**Comment by elprans** [comment]
I think it should be an error to convert a non-empty type.

**Comment by msullivan** [comment]
Oh, yeah, I think that is clearly right.
