### ISSUE TITLE
UDF InvalidReferenceError on inherited type

### ISSUE THREAD

**Issue by rdlaitila** [edgedb/edgedb#3426]
I understand 1.0 has not been officially announced but it was available for upgrade via cli.

- EdgeDB CLI Version: EdgeDB CLI 1.0.0+7b66089
- EdgeDB Instance Version: 1.0+9236fa8
- OS Version: macosx

Steps to Reproduce:

1. issue `edgedb migration create` with the schema shown in the `schema` section
2. observe error 'edgedb error: InvalidReferenceError: object type 'default::Entity' has no link or property 'name''

__optionally__

1. comment out the UDF function `create_project`
2. issue `edgedb migration create` with the schema shown in the `schema` section
3. observe successful migration creation
4. issue `edgedb migration apply`
5. observe successfull migration application
4. issue the following query below and observe successful execution:

```
with
	name := "my project",
	project := (
		insert Project {
			name := name,
		}
	),
	event := (
		insert ProjectCreatedEvent {
			entity := project,
			name := name,
		}
	),
select event {
	id,
	typename,
	emittedAt,
	name,
	entity: {
		id,
		typename,					
	}
}
{default::ProjectCreatedEvent {id: dfa460ee-8a77-11ec-aca2-5fc77c199fd0, typename: 'default::ProjectCreatedEvent', emittedAt: <datetime>'2022-02-10T13:46:39.947598Z', name: 'my project', entity: default::Project {id: dfa450c2-8a77-11ec-aca2-eff5c502242d, typename: 'default::Project'}}}
```

Schema:

```
module default {
	abstract type Base {
		property typename := .__type__.name;
	}

	abstract type Entity extending Base {
	}

	abstract type Event extending Base {
		required link entity -> Entity;
		required property emittedAt -> datetime {
			default := datetime_current()
		};
	}

	type Project extending Entity {
		required property name -> str {
			constraint exclusive;
		};
	}

	type ProjectCreatedEvent extending Event {
		required property name -> str;
	}

	function create_project(name: str) -> ProjectCreatedEvent {
		using (
			with
				project := (
					insert Project {
						name := name,
					}
				),
				event := (
					insert ProjectCreatedEvent {
						entity := project,
						name := name,
					}
				),
			select event {
				id,
				typename,
				emittedAt,
				entity: {
					id,
					typename,
					name,
				}
			}
		)
	}
}
```

Aside from the failure to create the migration, it would be helpful to know where in the schema the reference error was thrown, as the error does not provide that context. Thanks!

**Comment by rdlaitila** [comment]
After more fiddling this may be a non issue. removing the `name` property from the resulting event shaping select results in 

```
error: data-modifying statements are not allowed in function bodies
```

So is this use case not permitted inside UDFs?

**Comment by msullivan** [comment]
Sorry I missed this one:

Yeah, DML is not yet permitted in function bodies.
The `name` property in the `entity` event is an error, since Entity doesn't have name.

But it's a bug that we don't show the source location!
