### ISSUE TITLE
DigitalOcean: 1-click deploy button does not work

### ISSUE THREAD

**Issue by mirrorrim** [edgedb/edgedb#3428]
The link in the documentation leads to a non-existent DigitalOcean Marketplace page.

https://github.com/edgedb/edgedb/blob/master/docs/guides/deployment/digitalocean.rst

**Comment by elprans** [comment]
We're still waiting for DO to approve our listing, unfortunately.

**Comment by fmoor** [comment]
DO has approved our listing :tada: the guide is back and the link works now.
