### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by chancez** [edgedb/edgedb#3437]
I'd love if I could install edgedb via homebrew on MacOS. 

Currently:
```
~ ❯❯❯ brew search edgedb
Error: No formulae or casks found for "edgedb".
```

**Comment by elprans** [comment]
We have a tap: https://github.com/edgedb/homebrew-tap

**Comment by chancez** [comment]
Great! It would be nice if this was mentioned in the docs/website, even if it wasn't the default method.

**Comment by elprans** [comment]
We have it in the ["Other installation options"](https://www.edgedb.com/install#macos-homebrew), but it's somewhat obscure currently.

**Comment by chancez** [comment]
Ah I just didn't scroll down enough! I see.
