### ISSUE TITLE
Incorrect comment in `Operators` `Logical and Comparison` codeblock in EdgeQL Tutorial

### ISSUE THREAD

**Issue by runawaykiwi** [edgedb/edgedb#3440]
Very last example in https://www.edgedb.com/tutorial/building-blocks/operators/logical-and-comparison

Says 
```sql
# strings are ordered lexicographically
SELECT <duration>'15m' < <duration>'1h';
```

which doesn't make sense since it's not a string, but a duration.

I'd make a PR, but I literally cannot find the code for this tutorial anywhere in your organization (used Github search).

**Comment by 1st1** [comment]
Thank you, we'll fix this.

> I'd make a PR, but I literally cannot find the code for this tutorial anywhere in your organization (used Github search).

The tutorial is part of our website repo, which is currently closed source.

**Comment by colinhacks** [comment]
Fixed in https://github.com/edgedb/edgedb.com/pull/441

Should be live soon
