### ISSUE TITLE
edgedb.com/blog does not have an rss feed

### ISSUE THREAD

**Issue by NiloCK** [edgedb/edgedb#3446]
Steps to Reproduce:

1. visit edgedb.com
2. open page source
3. search for `rss`, `feed`, etc.

Apologies if this isn't the correct place for this issue. I didn't see a website or blog repo among the org's list.

**Comment by colinhacks** [comment]
This is the right place! The `edgedb.com` repo isn't public because a) it's preposterously over-engineered and b) we need a place to privately draft blog posts and whatnot. We'll work on this.

**Comment by jaclarke** [comment]
We do generate this file: https://www.edgedb.com/rss.xml. Though we need to add a link to it somewhere, and maybe there's some meta tag we can add.

**Comment by colinhacks** [comment]
Colin! All Colins are always welcome here (except those two-L weirdos) 😛

As usual James is one step ahead of m
<img width="442" alt="Screen Shot 2022-02-11 at 11 47 00 PM" src="https://user-images.githubusercontent.com/3084745/153702355-0f56aa15-40a3-4711-95b4-ee8465797d00.png">
e here. I just added the `<link rel="alternate">` tag and a visible link to the footer on all pages. 🤙
