### ISSUE TITLE
Can't stop edge server instance (1.0+9236fa8) on M1 Mac - times out

### ISSUE THREAD

**Issue by mphuie** [edgedb/edgedb#3476]
- EdgeDB Version: 1.0+9236fa8
- OS Version: 12.1
- Tested on M1 Macbook Air, M1 Macbook Pro (M1 Pro)

Steps to Reproduce:

1.  `edgedb instance stop <instance name>`

    WARN  edgedb::portable::macos] Timing out; send SIGKILL now.

Killing the PID only only has the server run spawn on another PID

    >edgedb instance status  <instance name>
    Running, pid 5411

    >kill 5411
    >edgedb instance status  <instance name>
    Running, pid 5515

**Comment by elprans** [comment]
Thanks for the report!  This is already filed as edgedb/edgedb-cli#663
