### ISSUE TITLE
"On AWS Aurora and ECS​" Deployment Guide references a non-public CloudFormation Template

### ISSUE THREAD

**Issue by aaronbrighton** [edgedb/edgedb#3477]
Steps to Reproduce:

1. Visit the following guide: https://www.edgedb.com/docs/guides/deployment/aws_aurora_ecs
2. The link in this section https://www.edgedb.com/docs/guides/deployment/aws_aurora_ecs#cloudformation-web-portal results in `S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html` when trying to proceed using the CloudFormation console.
3. Likewise, in this section https://www.edgedb.com/docs/guides/deployment/aws_aurora_ecs#cloudformation-cli results in `An error occurred (ValidationError) when calling the CreateStack operation: S3 error: Access Denied`

**Comment by elprans** [comment]
Fixed. The template wasn't assigned correct access permissions on the last update.  Thanks for the report!
