### ISSUE TITLE
Minimum and maximum cardinality inference

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#349]
Cardinality inference comes in two flavors: minimum and maximum. The basic idea is that just as we can infer the upper bound on a set size we can also infer the lower bound on it. It is useful in cases where a link or property is `required` and must have a minimum cardinality of 1.

Minimum is 0 by default and can become 1 due to `required` keyword or explicit literals being used. For purposes of inference we only care about 0 and 1 values treating any set with cardinality > 1 as having minimum cardinality of 1 (e.g. the literal `{1, 2, 3}` would be treated as having the same minimum cardinality as `{1}`).
Maximum cardinality is infinite (corresponding to `multi link`) by default and can be lowered if `single` keyword is used or by a `LIMIT 1`. We infer maximum cardinality of a singleton set to be 1.

The `{}` has both minimum and maximum cardinality as 0. 

The `OPTIONAL` type modifier implies that the minimum cardinality can be 0. This is especially important for return type specification of functions where a return type without any modifiers is intended as a contract that the minimum and maximum cardinality are both 1. In order to validate that we need to be able to infer the cardinality from the function body (and input signature).

The following function should be illegal because the minimum cardinality of the return signature is greater than the minimum cardinality of the function body:
```
CREATE FUNCTION
my::foo(val: str) -> str
{
    FROM EdgeQL $$
        SELECT <str>{} IF val = 'foo' ELSE val;
    $$;
};
```

**Comment by 1st1** [comment]
This one is implemented, isn't it? @vpetrovykh

**Comment by elprans** [comment]
This isn't implemented.  Our current cardinality inference is binary -- `SINGLE`, `MULTI`.  We need to extend it to return an interval, i.e.  [0, 1], [0, inf], [1, 1], [1, inf]

**Comment by 1st1** [comment]
Got it. I guess this is something that Victor can tackle.

Do you actually want to return intervals or can we just make a bigger enum:

* `ONE` [1, 1]
* `MANY` [0, inf]
* `AT_LEAST_ONE` [1, inf]
* `AY_MOST_ONE` [0, 1]

?

**Comment by elprans** [comment]
A bigger enum is ok
