### ISSUE TITLE
Cardinality validation for aggregates mapped onto SQL

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#350]
This is related to #349 

For standard library functions there's a need to map them onto existing SQL functions. Sometimes aggregate functions in SQL can return `NULL` for cases that in EdgeDB we would consider invalid. Consider `stddev` (sample standard deviation) that is not defined for sets of cardinality < 2. On the other hand for all other sets it is a single number. So in our definition of cardinality we expect the return value to be of cardinality exactly 1, neither more nor less (much like `count`). Unfortunately Postgres will return `NULL` for the input sets that are too small and we need a way of handling that with some sort of graceful error message instead.

The proposal is to have a special attribute like `empty_result_error` that provides a way to customize the error message. While a `NULL` test of the result is only added if the function return type is declared to be of cardinality >= 1 (not `OPTIONAL` or `SET OF`).

**Comment by 1st1** [comment]
This can be closed now, right? @vpetrovykh

**Comment by vpetrovykh** [comment]
The examples of `SELECT math::stddev({})` or `SELECT math::stddev({1})` should not return any value as they have no valid value, much like `1/0`. Sample standard deviation is not defined for sets of fewer than 2 elements.

The desired behavior would be for these types of functions to raise an error instead of silently producing invalid output. The error message needs to reflect the fact that the function is not defined for certain input.

**Comment by elprans** [comment]
Fixed in #521
