### ISSUE TITLE
Error using UNLESS CONFLICT with abstract types 

### ISSUE THREAD

**Issue by vonkoff** [edgedb/edgedb#3518]
- EdgeDB Version: 1.0
- OS Version: Mac OS Monterey version 12.1

Steps to Reproduce:
1. 
```
edgedb> INSERT Countries {
....... name := 'USA'
....... } UNLESS CONFLICT ON .name ELSE Countries;
error: UnsupportedFeatureError: UNLESS CONFLICT can not use ELSE when constraint is from a parent type
```

It's a simple error. The way I fixed it was by getting rid of the "abstract type Named" that I created and adding the "required property name...constraint exclusive" to the Countries table instead. 

Not the biggest issue, but would save me some lines of code if abstract types could work with UNLESS CONFLICT  :)

Schema:
```
abstract type Named {
    required property name -> str {
      constraint exclusive;
    }
  }

types Countries extending Named;
```

**Comment by CodesInChaos** [comment]
You will not get this error if you use a `delegated` constraint. A delegated constraint will behave like a constraint specified on each concrete type (i.e. you can have a `Country` and `Person` with the same name, while an ordinary constraint will ensure uniqueness across all instances of `Named` (i.e. you can not have a `Person` and `Country` with the same name).

> `delegated`
>
> If specified, the constraint is defined as delegated, which means that it will not be enforced on the type it’s declared on, and the enforcement will be delegated to the subtypes of this type. This is particularly useful for exclusive constraints in abstract types.

P.S. I'd call the type `Country` not `Countries`
