### ISSUE TITLE
UnsupportedFeatureError: unexpectedly long path in simple expr with whole schema

### ISSUE THREAD

**Issue by AdrienPensart** [edgedb/edgedb#3523]
Hello this is my first schema so it may not be optimized or well declared but still, when I built it migration by migration it worked well and when I dropped everything to create a unique migration file, the schema is not accepted anymore.

- EdgeDB Version: 1.0.0+5724c50
- OS Version: Debian bookworm/sid

Steps to Reproduce:

1. edgedb migration create
2. edgedb migrate

edgedb error: UnsupportedFeatureError: unexpectedly long path in simple expr

Schema:
```
module default {
    abstract type Entity {
        required property name -> str;
        required property created_at -> datetime {
            default := std::datetime_current();
            readonly := true;
        }
        required property updated_at -> datetime {
            default := std::datetime_current();
        }
    }

    scalar type Rating extending float32 {
        constraint one_of (0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0);
    }

    scalar type Size extending int64 {
        constraint min_value(0);
    }

    type Artist extending Entity {
        overloaded required property name -> str {
            constraint exclusive;
        }
        multi link albums := .<artist[is Album]
    }

    type Album extending Entity {
        required link artist -> Artist {
            on target delete delete source;
        }

        multi link musics -> Music {
            constraint exclusive;
        }
        constraint exclusive on ( (.name, .artist ) );
        multi link musics := .<album[is Music]
    }

    type Music extending Entity {
        required property path -> str;
        required property rating -> Rating {
            default := 0.0
        }
        required property duration -> duration;
        required property size -> Size;
        property track -> int16;

        required link album -> Album {
            on target delete delete source;
        }

        required link genre -> Genre {
            on target delete delete source;
        }

        multi link keywords -> Keyword;

        constraint exclusive on ( (.name, .album ) );
    }

    type Keyword extending Entity {
        overloaded required property name -> str {
            constraint exclusive;
        }
        multi link musics := .<keywords[is Music]
    }

    type Genre extending Entity {
        overloaded required property name -> str {
            constraint exclusive;
        }
        multi link musics := .<genre[is Music]
    }
}

using extension graphql;
using extension edgeql_http;
```

**Comment by elprans** [comment]
The error is in `Album`, where you have both a `multi link musics` and a computed `musics`.  What happens is that the computed overrides the "real" link making the exclusive constraint illegal, because exclusive constraints are not supported on backlinks.

**Comment by elprans** [comment]
@vpetrovykh, we should reject an SDL redefinition like this properly.

**Comment by AdrienPensart** [comment]
Ok understood! By the way this is an amazing project, for me it's like the Rust correct way of doing things for databases.

But how can I express the facts that : 
- one music belongs to only one album
- when an album is deleted, all its musics are deleted
- the one-to-many relation accessible from both sides

thank you so much!

**Comment by elprans** [comment]
> Ok understood! By the way this is an amazing project, for me it's like the Rust correct way of doing things for databases.

Thank you! :heart:

> But how can I express the facts that :
> 
> * one music belongs to only one album

You have already achieved this with the `exclusive` constraint on the `musics` link.

> * when an album is deleted, all its musics are deleted

We indeed need to add a `on source delete` knob.  This shouldn't be hard, since it's basically `on source delete` in reverse.  I'll open an issue.

> * the one-to-many relation accessible from both sides

You can access any relation from the other side with backlink syntax, and if you need to traverse them frequently, declare a computed link, like you already do above.

**Comment by elprans** [comment]
> * one music belongs to only one album
> * when an album is deleted, all its musics are deleted

Oh and you can also do this by reversing the relationship in your schema, i.e:

```
type Music {
   required link album -> Album {
      constraint exclusive;
      on target delete delete source;
   }
}

type Album {
   link musics := .<album[is Music]
}
```
