### ISSUE TITLE
Unable to create migration altering a property from required to optional

### ISSUE THREAD

**Issue by fanliver** [edgedb/edgedb#3542]
- EdgeDB Version: EdgeDB CLI 1.1.0+8bc2c20
- OS Version: MacOS Catalina 10.15.7

Steps to Reproduce:

1. Create a new EdgeDB project (version 1.0) with `default` module as below:
```
module default {
    abstract type Person {
        required property name -> str;
    }

    type PC extending Person {
    }
}
```
2. Create and apply migration
```
user@local> edgedb migration create
did you create object type 'default::Person'? [y,n,l,c,b,s,q,?]
> y
did you create object type 'default::PC'? [y,n,l,c,b,s,q,?]
> y
Created ./dbschema/migrations/00001.edgeql, id: m1clwlsejlohyzkgrc234l4etgml2mnq6ttpfvvpaykmrfujj5lzaq

user@local> edgedb migrate
Applied m1clwlsejlohyzkgrc234l4etgml2mnq6ttpfvvpaykmrfujj5lzaq (00001.edgeql)
Note: adding first migration disables DDL. More info: https://edgedb.com/p/bare_ddl

```
3. Remove `required` from `default::Person::name` property and create new migration.
```
user@local> edgedb migration create
did you make property 'name' of object type 'default::Person' optional? [y,n,l,c,b,s,q,?]
> y
edgedb error: EdgeDB could not resolve migration with the provided answers. Please retry with different answers.

```

As you see from the terminal output above, the migration to make property `default::Person::name` optional could not be created. The error message is quite confusing `EdgeDB could not resolve migration with the provided answers. Please retry with different answers`.

How can I fix it?

**Comment by elprans** [comment]
It's a bug, we are looking into it.  A workaround for now is to declare the `name` property as `optional` explicitly:


```
    abstract type Person {
        optional property name -> str;
    }
```
