### ISSUE TITLE
Unable to create migration to add default value for `multi link`

### ISSUE THREAD

**Issue by fanliver** [edgedb/edgedb#3544]
- EdgeDB Version: `EdgeDB CLI 1.1.0+8bc2c20`
- OS Version: `MacOS Catalina 10.15.7`

Steps to Reproduce:

1. Create a default EdgeDB project with `default` module with below schema, then migrate the database
```
module default {
    abstract type Person {
        multi link visited_places -> Place;
    }

    type Firefighter extending Person {}
    
    type Place {
        required property name -> str {
            constraint exclusive;
        }
    }
}

```

2. Update the schema to add default value for `default::Person::visited_places` as below
```
module default {
    abstract type Person {
        multi link visited_places -> Place { default := ( select Place filter .name = 'London' ) };
    }

    type Firefighter extending Person {}
    
    type Place {
        required property name -> str {
            constraint exclusive;
        }
    }
}
```
3. Try to create new migration and error will show `EdgeDB could not resolve migration with the provided answers. Please retry with different answers.`
```
user@local> edgedb migration create
did you alter link 'visited_places' of object type 'default::Person'? [y,n,l,c,b,s,q,?]
> y
edgedb error: EdgeDB could not resolve migration with the provided answers. Please retry with different answers.

```

**Notice**: 
The step 3 can be done without error if 
- `default::Place::name` does not have `exclusive` constraint.
OR
- type `default::Firefighter` does not exists

Is it a bug?

**Comment by elprans** [comment]
It's a bug.

**Comment by msullivan** [comment]
Oh, and it's even spicier than just that: we fail to migrate to that second schema from an empty schema.
