### ISSUE TITLE
is_empty for array

### ISSUE THREAD

**Issue by AdrienPensart** [edgedb/edgedb#3549]
Hello!

As cast from bool to int64 and int64 to bool does not exist we can't : 

<bool>len(array) or contains(array, needle)
OR
len(array) or <int64>contains(array, needle)

Objective : create query filters objects (in python).

So we need an : is_empty(array) -> bool or permit to cast bool to int64 easily

Could you add it ? 
thank you!

**Comment by CodesInChaos** [comment]
What's wrong with `len(array) != 0`?

**Comment by 1st1** [comment]
Yeah, we considered that before, but since we have a concept of "empty set" adding a function called `is_empty()` would be confusing. As suggested, `len(ar) != 0` should be used.
