### ISSUE TITLE
Error location is missing for "schema intem does not exist"

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb#3560]
It seems like it would be helpful to have the filename, line and column number for this error. Forgetting to prefix properties with a dot seems like an easy mistake.

- EdgeDB Version: 1.1
- OS Version: ubuntu 21.04

Steps to Reproduce:
```bash
$ edgedb migration create
edgedb error: InvalidReferenceError: schema item 'std::b' does not exist
edgedb error: cannot proceed until .esdl files are fixed
```

Schema:

```
module a {
	type Thing {
		property b -> str;
		property c := (select b);
	}
}
```

**Comment by msullivan** [comment]
Oh this particular case is long fixed
