### ISSUE TITLE
Where is the dockerfile

### ISSUE THREAD

**Issue by OhBonsai** [edgedb/edgedb#357]
Hi:
   Where is dockerfile,  Is there any document about deployment.

**Comment by pratikpparikh** [comment]
@elprans it be good to understand how you are creating a edgedb-preview.

**Comment by pratikpparikh** [comment]
@elprans much appreciated.  Looking forward to integrating edgedb in our postgres implementation.

**Comment by 1st1** [comment]
> Looking forward to integrating edgedb in our postgres implementation.

Keep in mind that EdgeDB won't run on vanilla postgres.

**Comment by pratikpparikh** [comment]
@1st1 good to know.  Thank you build hoping that the docker container will help understand how the components come together.

**Comment by OhBonsai** [comment]
https://github.com/edgedb/edgedb-docker
