### ISSUE TITLE
Unable to inherit enum type

### ISSUE THREAD

**Issue by fanliver** [edgedb/edgedb#3578]
- EdgeDB Version: EdgeDB CLI 1.1.0+8bc2c20
- Server version: 1.1
- OS Version: Mac OS Catalina 10.15.7

Steps to Reproduce:

1. Just create a new instance with following schema
```
    scalar type Status extending enum<pending, in_progress, finished>;
    scalar type ImportStatus extending Status;
    scalar type ImportAnalyticsStatus extending Status;
```
2. Running `edgedb migration create` and get error message
```
> edgedb migration create
did you create scalar type 'default::Status'? [y,n,l,c,b,s,q,?]
> y
did you create scalar type 'default::ImportAnalyticsStatus'? [y,n,l,c,b,s,q,?]
> y
did you create scalar type 'default::ImportStatus'? [y,n,l,c,b,s,q,?]
> y
edgedb error: EdgeDB could not resolve migration with the provided answers. Please retry with different answers.

```

**Comment by msullivan** [comment]
Yeah it looks like this is just not really implemented. I'm going to put up a PR to produce a real error message, for now.

**Comment by msullivan** [comment]
Alright, I actually ended up taking a second look and realized that actually implementing it would be pretty easy.

And then, after I had finished all the parts that I felt were the core of the implementation, I stumbled across some very fiddly interactions with our mechanism for deleting an element from an enum, which wound up requiring some nontrivial changes to that mechanism.
