### ISSUE TITLE
Incorrect cardinality inference on update

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb#3590]
A cardinality inference bug in `update` queries. Using the [query builder schema](https://github.com/edgedb/edgedb-js/blob/master/qb/dbschema/default.esdl) the following query has inferred cardinality `Many`:

```
WITH
  __scope_0_Hero := DETACHED default::Hero
UPDATE __scope_0_Hero
FILTER (__scope_0_Hero.name = "Spider-Man")
SET {
  name := ("The Amazing " ++ __scope_0_Hero.name)
}
```

Though `Hero.name` has an exclusive constraint. Regression possibly introduced in https://github.com/edgedb/edgedb/pull/3585.

**Comment by msullivan** [comment]
It is indeed a regression from #3585

**Comment by msullivan** [comment]
(Though the reason it worked before https://github.com/edgedb/edgedb/pull/3585 was basically by accident)
