### ISSUE TITLE
Reorganize EdgeDB documentation

### ISSUE THREAD

**Issue by ansarizafar** [edgedb/edgedb#360]
The current documentation format needs improvement. I recommend a CockroachDB https://www.cockroachlabs.com/docs/stable/ like format for EdgeDB documentation.

- Guides
- Reference
- Concepts
- Faqs
- Releases

**Comment by 1st1** [comment]
I'm going to close this issue as it's too broad.  FWIW we're slowly converging docs to the format you suggested, but we don't need an issue for that.
