### ISSUE TITLE
Adding computed properties and links with queries selecting values fails migrations

### ISSUE THREAD

**Issue by tdolsen** [edgedb/edgedb#3635]
- EdgeDB Version: 1.2+5aecabc
- CLI Version: 1.1.1+5bb8bad
- OS Version: Linux 5.16.14-arch1-1

Steps to Reproduce:

0. Run migrations on provided schema - it's valid as is now
1. Uncomment any of the commented links or properties
2. The run migrations again to see error

Description:

The error is caused by selecting values in the computed properties or links, stating that the object type selected for doesn't exist.

For links it's understandable that won't work, but for computed properties it's not quite as obvious; while the document specifies that properties are primitive types and is pretty clear about it's meaning in the "Schema > Properties" section, the "Schema > Computeds" section gives an impression computed properties are much more accommodating.

> Computed fields are associated with an EdgeQL expression. This expression can be an arbitrary EdgeQL query.

It also mentions that computed fields behave exactly the same in queries, linking to the "EdgeQL > Select > Computed" section, which goes on to show examples of sub-queries selecting values much in the same way as done here. And testing any of the failing computed in the REPL surely works as expected.

I understand now that this might be the correct behavior, and that it's not as much a bug with the database, but in that case it's still a terribly misleading error message and frustratingly inconsistent/vague documentation.

Schema:
```esdl
module default {
	type UserGroup {
		property name -> str;
		property is_active -> bool;
	}

	type User {
		multi link groups -> UserGroup;
		link valid_link := (select UserGroup);

		# raises error, but it's as expected
		# property invalid_prop := (select UserGroup);

		# raises error "object type 'default::UserGroup' does not exist"
		# property invalid_prop := (select UserGroup { id });
		# property invalid_prop := (select .groups { id });
		# link invalid_link := (select UserGroup { id });
		# link invalid_link := (select .groups { id });
		
		# raises error "object type 'std::FreeObject' does not exist"
		# property first_group_name := (
		# 	with n := (select .groups { name } limit 1)
		# 	select { name := n.name }
		# );
	}
}
```

**Comment by tdolsen** [comment]
Interestingly, selecting a tuple instead of a set works... Now i'm even more confused.

```esdl
property first_group_name := (
	with n := (select .groups { name } limit 1)
	select ( name := n.name )
);
```

**Comment by msullivan** [comment]
Aha, the issue here is that computed links with shapes on them don't work.

It would be nice to make this work, but we should at least produce a real error message.

**Comment by msullivan** [comment]
Aha, we already have it as #3369
