### ISSUE TITLE
SCRAM authentication server key mismatch with concurrency

### ISSUE THREAD

**Issue by quinchs** [edgedb/edgedb#3639]
While working on my library, I've notice that scram seems to return another clients server key in the [AuthenticationSASLFinal](https://www.edgedb.com/docs/reference/protocol/messages#authenticationsaslfinal) packet.

I'm fairly certain this isn't an issue with my library but feel free to reviev my scram implementation [here](https://github.com/quinchs/EdgeDB.Net/blob/master/src/EdgeDB.Driver/EdgeDBTcpClient.cs#L544).

#### Things to note
- I can reproduce this bug nearly 100% of the time with 2 or more client. The first client always succeeds and the correct signature is returned while any proceeding clients fail.
- The clients I'm using to test all connect at the same time.

EdgeDB Version:  1.2+5aecabc
OS Version: Windows 10 Home N 21H2

Steps to Reproduce:
1. Connect 2 or more clients at the same time and observe the [AuthenticationSASLFinal](https://www.edgedb.com/docs/reference/protocol/messages#authenticationsaslfinal)'s returned `v` key.

Expected behavior 
- The `v` key should match the expected signature that the client makes in its final scram message

Actual behavior 
- The `v` key is a previous clients key

Packet logs
```py
# both clients send handshake and receive handshake
[ 0 ] Sent message type ClientHandshake
[ 1 ] Sent message type ClientHandshake
[ 1 ] Got message type ServerHandshake
[ 0 ] Got message type ServerHandshake

# both clients respond to the sasl message
[ 1 ] Got message type Authentication:AuthenticationRequiredSASLMessage
[ 0 ] Got message type Authentication:AuthenticationRequiredSASLMessage
[ 1 ] Sent message type AuthenticationSASLInitialResponse
[ 0 ] Sent message type AuthenticationSASLInitialResponse

# first challenge
[ 1 ] Got message type Authentication:AuthenticationSASLContinue
       - 'r=8tMlBxjXDne/2cHFVYUHyUMLBJpJEwIt/M54Qb0SrmzVsQ8Q,s=dSNTp1avqtVWqlKWD4wNYw==,i=4096'
[ 0 ] Got message type Authentication:AuthenticationSASLContinue
       - 'r=8tMlBxjXDne/2cHFVYUHyUMLBJpJEwIt/M54Qb0SrmzVsQ8Q,s=dSNTp1avqtVWqlKWD4wNYw==,i=4096'

# response to challenge 
[ 1 ] Sent message type AuthenticationSASLResponse
[ 0 ] Sent message type AuthenticationSASLResponse

# server final message
[ 1 ] Got message type Authentication:AuthenticationSASLFinal
    - 'v=AoCTbHI3BJJ+NgDO2I5rawmaJUOqPRADoK6Ovbflq8c='
[ 0 ] Got message type Authentication:AuthenticationSASLFinal
    - 'v=D5OnJP7xZ/+46AfGDOqP5otpDj5XHSdMPdepouQt4gk='

# auth ok message: notice both 'v' keys are the same
[ 1 ] Got message type Authentication:AuthenticationOK
    - 'v=D5OnJP7xZ/+46AfGDOqP5otpDj5XHSdMPdepouQt4gk='
[ 0 ] Got message type Authentication:AuthenticationOK
    - 'v=D5OnJP7xZ/+46AfGDOqP5otpDj5XHSdMPdepouQt4gk='
```

**Comment by fantix** [comment]
The `AuthenticationOK` message shouldn't include the server signature - it's probably the `AuthenticationSASLFinal` message?

For the repeated response from the server - is there any shared resource among the concurrent clients? From the client implemtation I didn't see any (or maybe I'm totally wrong because of my rusty C#), but perhaps trying with separate OS processes would help, like I did this in Python (with logs of the `AuthenticationSASLFinal` response):

```
import os
import edgedb

os.fork()
os.fork()
os.fork()
c = edgedb.create_client("test")
c.query("SELECT 42")
```

It's like 8 concurrent authentications, but I always get different responses 🤔

**Comment by quinchs** [comment]
I've actually found the issue, My packet deserializer was using singletons for packets, meaning it would reuse the last provided packet of the same type to deserialize: hence the OK packet had a key in it.

**Comment by fantix** [comment]
Ah, good to know!
