### ISSUE TITLE
Bulk Inserting Error: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by jerber** [edgedb/edgedb#3669]
I'm getting the error `edgedb.errors.InternalServerError: maximum recursion depth exceeded while calling a Python object` when I'm bulk-inserting ~50 small objects in one query.

The schema is:
```
  type Person {
    required property first_name -> str;
    property last_name -> str;
    multi property tags -> str;
    property ordered_tags -> array<str>;
    required property inserted_at -> datetime {
        readonly := true;
        default := datetime_current();
    }
    property created_at -> datetime;
    multi link people_i_follow -> Person {
        on target delete allow;
    }
    required property slug -> str {
        constraint exclusive;
    }
    multi link my_followers := .<people_i_follow[is Person];
    link best_friend -> Person {
        on target delete allow;
    }
    property full_name :=
      .first_name ++ ' ' ++ .last_name
      if exists .last_name
      else .first_name;
  }
```

And the code creates this query:
```
with
model_1 := (insert Person {first_name := <str>$first_name_1, slug := <str>$slug_1}),
model_2 := (insert Person {first_name := <str>$first_name_2, slug := <str>$slug_2}),
...
model_50 := (insert Person {first_name := <str>$first_name_50, slug := <str>$slug_50}),
models := (model_1 union model_1 ... union model_50)
select models {id}
```

My current workarounds are 1) only bulk inserting a small number of objects at a time ~3, and 2) asynchronously inserting objects individually.

**Comment by elprans** [comment]
It seems like the size of the query overflows the call stack in the compiler.

This can easily be solved by using a `for` instead:

```
for data in array_unpack(<array<tuple<first_name: str, slug: str>>>$json_data)
insert Person { first_name := data.first_name, slug := data.slug }
```

where `data` is a json array in this format:

```
[{"first_name": "foo", "slug": "bar"}, ...]
```

**Comment by elprans** [comment]
Use individual statements for each kind of mutation or combination of fields and wrap the whole thing in a [transaction](https://www.edgedb.com/docs/clients/01_js/driver#transactions).

**Comment by jerber** [comment]
Got it. Is there a difference between doing a transaction and doing a for loop?

**Comment by elprans** [comment]
An EdgeQL `for` or a programming language `for` loop?

**Comment by jerber** [comment]
An EdgeQL `for`

**Comment by elprans** [comment]
An EdgeQL `for` is a single statement and all statements are atomic.  Transaction blocks are also atomic, but each statement within a block is sent individually in sequence.  So, from the latency standpoint, it's better to use EdgeQL `for` whenever you can.

**Comment by msullivan** [comment]
Using `for` to do bulk operations in general is a better approach than generating queries dynamically (dynamic queries will miss the cache a lot!).

That said, as a workaround here you can use `{model_1, model_2, ..., model_50}` instead of `union`. The issue here is that `union` is a left associative binary operation, so it is really `(........((((model_1 union model_2) union model_3) union model_4.....)`

We could probably work around this by rebalancing `union` the same way we do explicit sets?

**Comment by msullivan** [comment]
Can also repro with `select (0+0 union 1+0 union 2+0 union 3+0 union 4+0 union 5+0 union 6+0 union 7+0 union 8+0 union 9+0 union 10+0 union 11+0 union 12+0 union 13+0 union 14+0 union 15+0 union 16+0 union 17+0 union 18+0 union 19+0 union 20+0 union 21+0 union 22+0 union 23+0 union 24+0 union 25+0 union 26+0 union 27+0 union 28+0 union 29+0 union 30+0 union 31+0 union 32+0 union 33+0 union 34+0 union 35+0 union 36+0 union 37+0 union 38+0 union 39+0 union 40+0 union 41+0 union 42+0 union 43+0 union 44+0 union 45+0 union 46+0 union 47+0 union 48+0 union 49+0);`

**Comment by elprans** [comment]
Yes, let's rebalance the `union` tree. After all, `{}` is a syntax sugar of `union`.
