### ISSUE TITLE
GraphQL field is of the wrong type for computable that filters another field for a subtype 

### ISSUE THREAD

**Issue by jonaird** [edgedb/edgedb#3683]
- EdgeDB Version: 1.2
- OS Version: MacOS 12.12.1

Steps to Reproduce:

1. Create a multi link property on a type. The link target type should be an abstract type.
2. Create a computable multi link that simply filters the previous property for a specific subtype.
3. In the GraphQL endpoint check the type of the second computed field.

The type in GraphQL is of the super type not the subtype

For example:

Schema:

```
type SomeType {
   multi link someProperty -> SomeAbstractType;
   multi link typeFilter := (.someProperty[IS SomeSubtype]);
}
```

In the above example `typeFilter` will be of `SomeAbstractType` in the GraphQL endpoint not `SomeSubtype` as it should be.

**Comment by 1st1** [comment]
@vpetrovykh
