### ISSUE TITLE
Allow direct cast from 'json string' to 'bigint'

### ISSUE THREAD

**Issue by jaclarke** [edgedb/edgedb#3736]
- EdgeDB Version: 2.0-dev.6500+local

Casting a 'json string' to a 'bigint' fails, though there doesn't seem to be any reason why this shouldn't work since casting via a 'str' works:

```edgeql
with test := to_json('{"bigint": "12345678901234567890"}')
select <bigint>test['bigint']
# InvalidValueError: expected JSON number or null; got JSON string

with test := to_json('{"bigint": "12345678901234567890"}')
select <bigint><str>test['bigint']
# 12345678901234567890n
```

**Comment by msullivan** [comment]
I think the current behavior is correct and preferable.

All of our json casts just directly extract the existing values, without doing any extra processing. I don't think we should add extra automatic casting.
