### ISSUE TITLE
Issue overloading abstract type's required property with a computed

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb#3742]
- EdgeDB Version: 1.2
- OS Version: latest mac

```
❯ edgedb migration create
error: possibly an empty set returned by an expression for the computed property 'name' of object type 'default::Course' explicitly declared as 'required'
    ┌─ ./dbschema/default.esdl:203:26
    │
203 │         property name := (.title if exists .title else 'Untitled Course');
    │                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ error

```

Schema
```
 abstract type Entity{
        required property name -> str;
}
type Course extending Entity {
  property title -> str;
  property name := (.title if exists .title else 'Untitled Course');
}
```

The expression never returns an empty set.

The migration was to actually overload the abstract type's property with a computed

**Comment by elprans** [comment]
Use `??` instead: `.title ?? 'Untitled Course'`.  

(We can improve cardinality inference on the `if` condition, but since it's an arbitrary expression it might not be possible to always bound the cardinality of subject based on some presence of `exists` in the condition)

**Comment by msullivan** [comment]
Yeah, I do not think this is a bug. I think that cardinality inference that understands the `if` condition should be avoided unless we really need it.
