### ISSUE TITLE
DDL can make `execute` not atomic

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#3748]
Create a schema:
```
create type Log { create property n -> int64; }; 
create type Foo;
```

Then, create and run this python script (edit the create_client call for whatever your dev environment test setup is):
```
#!/usr/bin/env python3

import os.path
import edgedb

def q(text, database='edgedb'):
    db = edgedb.create_client(
        port=5656,
        database=database,
        tls_ca_file=os.path.expanduser("~/.edgedb-test/edbtlscert.pem"),
    )
    db.execute(Q)

Q = '''
insert Log { n := count(Foo) };
create type asdf1;
select sys::_sleep(10);
create type asdf2;
insert Log { n := count(Foo) };
'''

q(Q, 'edgedb')
```

Run it, and *while it is running*, run `select Log { n }; insert Foo;` in the CLI.
You should be able to see that first Log insert, and then after, if you run `select Log { n }`, you should be able to see a skew in `n`

**Comment by 1st1** [comment]
Yeah, it's not. We execute a series of postgres' "simple query" messages. We have to change this to a series of "execute"s in one implicit transaction.

**Comment by msullivan** [comment]
Fixed by the elimination of simple_query. (Probably it's still a bug in protocol v0 but oh well.)
