### ISSUE TITLE
`session_idle_transaction_timeout` is racy with `START TRANSACTION`

### ISSUE THREAD

**Issue by fantix** [edgedb/edgedb#3749]
- EdgeDB Version: 1.2, nightly
- OS Version: *

Steps to Reproduce (thanks @msullivan):

1. Connect in the CLI (`CONFIGURE SESSION SET session_idle_transaction_timeout := ` 5 minutes)
2. Run a query via one of the language bindings (reuse the same pgcon, reset `session_idle_transaction_timeout` to 10 seconds)
3. Start a transaction in the CLI; it will time out after 10 seconds (should have restored the state to 5 minutes)

See also: [this line in #2236](https://github.com/edgedb/edgedb/pull/2236/files#diff-b039a6bd14ce31ad50b05a56c6ec1fee36666ca1bd27f2089029dd6c42838210R1413).

~- [ ] Restore state after `START TRANSACTION` as a special case~
- [x] Use `READONLY` / `DEFERRABLE` transactions (implement if not sufficient) to write test cases to cover the regression fixed in #2236

**Comment by 1st1** [comment]
> Run a query via one of the language bindings (reuse the same pgcon, reset session_idle_transaction_timeout to 10 seconds)

FWIW this also works

`edb cli query "CONFIGURE SESSION SET session_idle_transaction_timeout := <duration>'5 seconds';"`

**Comment by 1st1** [comment]
> Per @1st1 we can also add a Postgres Sync after state sync. Though that'll probably require moving away from SimpleQuery altogether.

Adding SYNC fixes the bug and it's the correct way forward. SimpleQuery already does this, we don't have to move away from it because of this fix. (We will for other unrelated reasons).
