### ISSUE TITLE
Support custom ids

### ISSUE THREAD

**Issue by vedantroy** [edgedb/edgedb#3759]
The default ids are UUIDS. These are too long to use inside of a URL. It would be nice if we could specify custom ids.

For example, a nanoid:
- https://github.com/Jakeii/nanoid-postgres/blob/main/nanoid.sql
- https://github.com/ai/nanoid

**Comment by 1st1** [comment]
You can create your own IDs with ease:

This is how the standard ID property is defined:

```
    required single property id -> uuid {
        default := (select
            uuid_generate_v1mc()
        );
        readonly := true;
    };
```

You cannot redefine it, but nothing prevents you from creating your own on a side:

```
    required single property my_id -> uuid {
        default := (select
            my_random_func()
        );
        readonly := true;
    };
```

You can also emulate auto-incrementing IDs with sequences https://www.edgedb.com/docs/stdlib/sequence

**Comment by 1st1** [comment]
You can even re-implement https://github.com/Jakeii/nanoid-postgres/blob/main/nanoid.sql in edgeql (just replace `&` with `%`).

**Comment by msullivan** [comment]
```
WITH                                                                     
  X := {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20},           
  alphabet := 'ModuleSymbhasOwnPr-0123456789ABCDEFGHNRVfgctiUvz_KqYTJkLxpZXIjQW',                                                                
  L := (                                                                 
    for i in X union (alphabet[<int64>math::floor(random()*64)])         
  )                                                                      
select array_join(array_agg(L), "");
```
computes a nanoid, I think. Really wants ranges
