### ISSUE TITLE
edgedb.EdgeQLSyntaxError: Unexpected 'REPEATABLE'

### ISSUE THREAD

**Issue by rdlaitila** [edgedb/edgedb#3763]
- EdgeDB Version: 1.3+804c096 and 1.3+5d0197d
- OS Version: macosx, ubuntu:20.04 (docker)

fb9be56121bcb3a35494667b2d1bcbffbaed83ad appears to have broken edgedb-go by removing 'repeatable' statements 

Steps to Reproduce:

1. Upgrade instance to 1.3+XXXX
2. Execute queries inside transactions with edgedb-go v0.9.3 or v0.9.4

Schema:

**Comment by elprans** [comment]
Fixed in https://github.com/edgedb/edgedb-go/pull/208
