### ISSUE TITLE
Bit operations

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#3799]
## Logical bit operations

The `and`, `or`, `not`, `xor` bit operations on `int` types are fairly straightforward and uncontroversial. They can be implemented by `std` library functions such as `bit_and`, etc.

Making them into operators would necessitate using some obscure symbols for some of them (e.g. `not` and `xor` don't have obvious good candidates). Since these aren't necessarily super-common operations, we can use functions instead.

## Bit shifting

There is some general concensus in programming when it comes to how to apply bit shifting to int types, when the number of bits used in bit shifting is between 0 and the bit length of the int representation.

When shifting an unsigned int, the bit shifting happens as one might expect the logical operation to happen and the newly added bits are 0.

When shifting a signed int, so-called "arithmetic" shifting is used, which preserves the sign bit. Well, the bit is preserved for right shifts while it can be overwritten in left shifts.

There's no concensus in programming languages on how bit shifting operators are generalized when the operand indicating the number of bits is either negative or greater than the bit length of the int in question.

### Postgres

First let's see what happens as the number of bits right-shifted increases in Postgres in more detail:

```
 val | numbits | result |            bitresult
-----+---------+--------+----------------------------------
 123 |       0 |    123 | 00000000000000000000000001111011
 123 |       1 |     61 | 00000000000000000000000000111101
 123 |       2 |     30 | 00000000000000000000000000011110
 123 |       3 |     15 | 00000000000000000000000000001111
 123 |       4 |      7 | 00000000000000000000000000000111
 123 |       5 |      3 | 00000000000000000000000000000011
 123 |       6 |      1 | 00000000000000000000000000000001
 123 |       7 |      0 | 00000000000000000000000000000000
 123 |       8 |      0 | 00000000000000000000000000000000
 123 |       9 |      0 | 00000000000000000000000000000000
 123 |      10 |      0 | 00000000000000000000000000000000
 123 |      11 |      0 | 00000000000000000000000000000000
 123 |      12 |      0 | 00000000000000000000000000000000
 123 |      13 |      0 | 00000000000000000000000000000000
 123 |      14 |      0 | 00000000000000000000000000000000
 123 |      15 |      0 | 00000000000000000000000000000000
 123 |      16 |      0 | 00000000000000000000000000000000
 123 |      17 |      0 | 00000000000000000000000000000000
 123 |      18 |      0 | 00000000000000000000000000000000
 123 |      19 |      0 | 00000000000000000000000000000000
 123 |      20 |      0 | 00000000000000000000000000000000
 123 |      21 |      0 | 00000000000000000000000000000000
 123 |      22 |      0 | 00000000000000000000000000000000
 123 |      23 |      0 | 00000000000000000000000000000000
 123 |      24 |      0 | 00000000000000000000000000000000
 123 |      25 |      0 | 00000000000000000000000000000000
 123 |      26 |      0 | 00000000000000000000000000000000
 123 |      27 |      0 | 00000000000000000000000000000000
 123 |      28 |      0 | 00000000000000000000000000000000
 123 |      29 |      0 | 00000000000000000000000000000000
 123 |      30 |      0 | 00000000000000000000000000000000
 123 |      31 |      0 | 00000000000000000000000000000000
 123 |      32 |    123 | 00000000000000000000000001111011
 123 |      33 |     61 | 00000000000000000000000000111101
 123 |      34 |     30 | 00000000000000000000000000011110
 123 |      35 |     15 | 00000000000000000000000000001111
 123 |      36 |      7 | 00000000000000000000000000000111
 123 |      37 |      3 | 00000000000000000000000000000011
 123 |      38 |      1 | 00000000000000000000000000000001
 123 |      39 |      0 | 00000000000000000000000000000000
 123 |      40 |      0 | 00000000000000000000000000000000
```

It appears that the way shifting works is that the number of bits shifted gets truncated by taking a positive *mod 32* of it. Same thing appears to happen for negative vaues of bits shifted:

```
 val | numbits | result |            bitresult
-----+---------+--------+----------------------------------
 123 |       0 |    123 | 00000000000000000000000001111011
 123 |      -1 |      0 | 00000000000000000000000000000000
 123 |      -2 |      0 | 00000000000000000000000000000000
 123 |      -3 |      0 | 00000000000000000000000000000000
 123 |      -4 |      0 | 00000000000000000000000000000000
 123 |      -5 |      0 | 00000000000000000000000000000000
 123 |      -6 |      0 | 00000000000000000000000000000000
 123 |      -7 |      0 | 00000000000000000000000000000000
 123 |      -8 |      0 | 00000000000000000000000000000000
 123 |      -9 |      0 | 00000000000000000000000000000000
 123 |     -10 |      0 | 00000000000000000000000000000000
 123 |     -11 |      0 | 00000000000000000000000000000000
 123 |     -12 |      0 | 00000000000000000000000000000000
 123 |     -13 |      0 | 00000000000000000000000000000000
 123 |     -14 |      0 | 00000000000000000000000000000000
 123 |     -15 |      0 | 00000000000000000000000000000000
 123 |     -16 |      0 | 00000000000000000000000000000000
 123 |     -17 |      0 | 00000000000000000000000000000000
 123 |     -18 |      0 | 00000000000000000000000000000000
 123 |     -19 |      0 | 00000000000000000000000000000000
 123 |     -20 |      0 | 00000000000000000000000000000000
 123 |     -21 |      0 | 00000000000000000000000000000000
 123 |     -22 |      0 | 00000000000000000000000000000000
 123 |     -23 |      0 | 00000000000000000000000000000000
 123 |     -24 |      0 | 00000000000000000000000000000000
 123 |     -25 |      0 | 00000000000000000000000000000000
 123 |     -26 |      1 | 00000000000000000000000000000001
 123 |     -27 |      3 | 00000000000000000000000000000011
 123 |     -28 |      7 | 00000000000000000000000000000111
 123 |     -29 |     15 | 00000000000000000000000000001111
 123 |     -30 |     30 | 00000000000000000000000000011110
 123 |     -31 |     61 | 00000000000000000000000000111101
 123 |     -32 |    123 | 00000000000000000000000001111011
 123 |     -33 |      0 | 00000000000000000000000000000000
 123 |     -34 |      0 | 00000000000000000000000000000000
 123 |     -35 |      0 | 00000000000000000000000000000000
 123 |     -36 |      0 | 00000000000000000000000000000000
 123 |     -37 |      0 | 00000000000000000000000000000000
 123 |     -38 |      0 | 00000000000000000000000000000000
 123 |     -39 |      0 | 00000000000000000000000000000000
 123 |     -40 |      0 | 00000000000000000000000000000000
```

Left-shifting has a similar repeating pattern. Since we're shifting a *signed* integer, eventually the sign bit starts getting affected producing negative values, but nothing surprising here:

```
 val | numbits |   result    |            bitresult
-----+---------+-------------+----------------------------------
 123 |       0 |         123 | 00000000000000000000000001111011
 123 |       1 |         246 | 00000000000000000000000011110110
 123 |       2 |         492 | 00000000000000000000000111101100
 123 |       3 |         984 | 00000000000000000000001111011000
 123 |       4 |        1968 | 00000000000000000000011110110000
 123 |       5 |        3936 | 00000000000000000000111101100000
 123 |       6 |        7872 | 00000000000000000001111011000000
 123 |       7 |       15744 | 00000000000000000011110110000000
 123 |       8 |       31488 | 00000000000000000111101100000000
 123 |       9 |       62976 | 00000000000000001111011000000000
 123 |      10 |      125952 | 00000000000000011110110000000000
 123 |      11 |      251904 | 00000000000000111101100000000000
 123 |      12 |      503808 | 00000000000001111011000000000000
 123 |      13 |     1007616 | 00000000000011110110000000000000
 123 |      14 |     2015232 | 00000000000111101100000000000000
 123 |      15 |     4030464 | 00000000001111011000000000000000
 123 |      16 |     8060928 | 00000000011110110000000000000000
 123 |      17 |    16121856 | 00000000111101100000000000000000
 123 |      18 |    32243712 | 00000001111011000000000000000000
 123 |      19 |    64487424 | 00000011110110000000000000000000
 123 |      20 |   128974848 | 00000111101100000000000000000000
 123 |      21 |   257949696 | 00001111011000000000000000000000
 123 |      22 |   515899392 | 00011110110000000000000000000000
 123 |      23 |  1031798784 | 00111101100000000000000000000000
 123 |      24 |  2063597568 | 01111011000000000000000000000000
 123 |      25 |  -167772160 | 11110110000000000000000000000000
 123 |      26 |  -335544320 | 11101100000000000000000000000000
 123 |      27 |  -671088640 | 11011000000000000000000000000000
 123 |      28 | -1342177280 | 10110000000000000000000000000000
 123 |      29 |  1610612736 | 01100000000000000000000000000000
 123 |      30 | -1073741824 | 11000000000000000000000000000000
 123 |      31 | -2147483648 | 10000000000000000000000000000000
 123 |      32 |         123 | 00000000000000000000000001111011
 123 |      33 |         246 | 00000000000000000000000011110110
 123 |      34 |         492 | 00000000000000000000000111101100
 123 |      35 |         984 | 00000000000000000000001111011000
 123 |      36 |        1968 | 00000000000000000000011110110000
 123 |      37 |        3936 | 00000000000000000000111101100000
 123 |      38 |        7872 | 00000000000000000001111011000000
 123 |      39 |       15744 | 00000000000000000011110110000000
 123 |      40 |       31488 | 00000000000000000111101100000000
```

A thing worth noting, though, is that left-shifting is *not* the same as simply multiplying by 2. It is fundamentally an agnostic manipulation of the underlying bit pattern, otherwise sign-flipping wouldn't happen.

Left-shifting by negative values has effects consistent with just taking a positive *mod 32* value of the bit shift argument.

Right-shifting negative integers preserves the sign bit, resulting in the following:
```
 val  | numbits | result |            bitresult
------+---------+--------+----------------------------------
 -123 |       0 |   -123 | 11111111111111111111111110000101
 -123 |       1 |    -62 | 11111111111111111111111111000010
 -123 |       2 |    -31 | 11111111111111111111111111100001
 -123 |       3 |    -16 | 11111111111111111111111111110000
 -123 |       4 |     -8 | 11111111111111111111111111111000
 -123 |       5 |     -4 | 11111111111111111111111111111100
 -123 |       6 |     -2 | 11111111111111111111111111111110
 -123 |       7 |     -1 | 11111111111111111111111111111111
 -123 |       8 |     -1 | 11111111111111111111111111111111
 -123 |       9 |     -1 | 11111111111111111111111111111111
 -123 |      10 |     -1 | 11111111111111111111111111111111
 -123 |      11 |     -1 | 11111111111111111111111111111111
 -123 |      12 |     -1 | 11111111111111111111111111111111
 -123 |      13 |     -1 | 11111111111111111111111111111111
 -123 |      14 |     -1 | 11111111111111111111111111111111
 -123 |      15 |     -1 | 11111111111111111111111111111111
 -123 |      16 |     -1 | 11111111111111111111111111111111
 -123 |      17 |     -1 | 11111111111111111111111111111111
 -123 |      18 |     -1 | 11111111111111111111111111111111
 -123 |      19 |     -1 | 11111111111111111111111111111111
 -123 |      20 |     -1 | 11111111111111111111111111111111
 -123 |      21 |     -1 | 11111111111111111111111111111111
 -123 |      22 |     -1 | 11111111111111111111111111111111
 -123 |      23 |     -1 | 11111111111111111111111111111111
 -123 |      24 |     -1 | 11111111111111111111111111111111
 -123 |      25 |     -1 | 11111111111111111111111111111111
 -123 |      26 |     -1 | 11111111111111111111111111111111
 -123 |      27 |     -1 | 11111111111111111111111111111111
 -123 |      28 |     -1 | 11111111111111111111111111111111
 -123 |      29 |     -1 | 11111111111111111111111111111111
 -123 |      30 |     -1 | 11111111111111111111111111111111
 -123 |      31 |     -1 | 11111111111111111111111111111111
 -123 |      32 |   -123 | 11111111111111111111111110000101
 -123 |      33 |    -62 | 11111111111111111111111111000010
 -123 |      34 |    -31 | 11111111111111111111111111100001
 -123 |      35 |    -16 | 11111111111111111111111111110000
 -123 |      36 |     -8 | 11111111111111111111111111111000
 -123 |      37 |     -4 | 11111111111111111111111111111100
 -123 |      38 |     -2 | 11111111111111111111111111111110
 -123 |      39 |     -1 | 11111111111111111111111111111111
 -123 |      40 |     -1 | 11111111111111111111111111111111
```
This is equivalent of first performing a `bit_not` on the integer, perform a bit shift and another `bit_not` at the end. It happens to be the case that the arithmetic unary `-` performs a 2's complement on an integer and so the combination of the `bit_not` and bit shifting works.

Also worth noting that in Postgres right-shifting a negative value is not the same as division by 2. E.g. `select -123/2` gets `-61`.

Left-shifting a negative integer will overwrite the sign bit with whatever bits that get shifted, just like for positive integers. This results in the sign potentially flipping due to left-shifting:
```
 val  | numbits |   result    |            bitresult
------+---------+-------------+----------------------------------
 -123 |       0 |        -123 | 11111111111111111111111110000101
 -123 |       1 |        -246 | 11111111111111111111111100001010
 -123 |       2 |        -492 | 11111111111111111111111000010100
 -123 |       3 |        -984 | 11111111111111111111110000101000
 -123 |       4 |       -1968 | 11111111111111111111100001010000
 -123 |       5 |       -3936 | 11111111111111111111000010100000
 -123 |       6 |       -7872 | 11111111111111111110000101000000
 -123 |       7 |      -15744 | 11111111111111111100001010000000
 -123 |       8 |      -31488 | 11111111111111111000010100000000
 -123 |       9 |      -62976 | 11111111111111110000101000000000
 -123 |      10 |     -125952 | 11111111111111100001010000000000
 -123 |      11 |     -251904 | 11111111111111000010100000000000
 -123 |      12 |     -503808 | 11111111111110000101000000000000
 -123 |      13 |    -1007616 | 11111111111100001010000000000000
 -123 |      14 |    -2015232 | 11111111111000010100000000000000
 -123 |      15 |    -4030464 | 11111111110000101000000000000000
 -123 |      16 |    -8060928 | 11111111100001010000000000000000
 -123 |      17 |   -16121856 | 11111111000010100000000000000000
 -123 |      18 |   -32243712 | 11111110000101000000000000000000
 -123 |      19 |   -64487424 | 11111100001010000000000000000000
 -123 |      20 |  -128974848 | 11111000010100000000000000000000
 -123 |      21 |  -257949696 | 11110000101000000000000000000000
 -123 |      22 |  -515899392 | 11100001010000000000000000000000
 -123 |      23 | -1031798784 | 11000010100000000000000000000000
 -123 |      24 | -2063597568 | 10000101000000000000000000000000
 -123 |      25 |   167772160 | 00001010000000000000000000000000
 -123 |      26 |   335544320 | 00010100000000000000000000000000
 -123 |      27 |   671088640 | 00101000000000000000000000000000
 -123 |      28 |  1342177280 | 01010000000000000000000000000000
 -123 |      29 | -1610612736 | 10100000000000000000000000000000
 -123 |      30 |  1073741824 | 01000000000000000000000000000000
 -123 |      31 | -2147483648 | 10000000000000000000000000000000
 -123 |      32 |        -123 | 11111111111111111111111110000101
 -123 |      33 |        -246 | 11111111111111111111111100001010
 -123 |      34 |        -492 | 11111111111111111111111000010100
 -123 |      35 |        -984 | 11111111111111111111110000101000
 -123 |      36 |       -1968 | 11111111111111111111100001010000
 -123 |      37 |       -3936 | 11111111111111111111000010100000
 -123 |      38 |       -7872 | 11111111111111111110000101000000
 -123 |      39 |      -15744 | 11111111111111111100001010000000
 -123 |      40 |      -31488 | 11111111111111111000010100000000
```

Contrasting this with bit shifting operations on bitstrings:
```
V2f144f3c41_edgedb=# select (123::int4)::bit(32) >> 2;
             ?column?
----------------------------------
 00000000000000000000000000011110
(1 row)

V2f144f3c41_edgedb=# select (123::int4)::bit(32) >> 34;
             ?column?
----------------------------------
 00000000000000000000000000000000
(1 row)

V2f144f3c41_edgedb=# select (123::int4)::bit(32) >> -2;
             ?column?
----------------------------------
 00000000000000000000000111101100
(1 row)

V2f144f3c41_edgedb=# select (123::int4)::bit(32) >> -30;
             ?column?
----------------------------------
 11000000000000000000000000000000
(1 row)

V2f144f3c41_edgedb=# select (-123::int4)::bit(32) >> 2;
             ?column?
----------------------------------
 00111111111111111111111111100001
(1 row)

V2f144f3c41_edgedb=# select (-123::int4)::bit(32) >> 34;
             ?column?
----------------------------------
 00000000000000000000000000000000
(1 row)

V2f144f3c41_edgedb=# select (-123::int4)::bit(32) >> -2;
             ?column?
----------------------------------
 11111111111111111111111000010100
(1 row)

V2f144f3c41_edgedb=# select (-123::int4)::bit(32) >> -30;
             ?column?
----------------------------------
 01000000000000000000000000000000
(1 row)
```

The positive and negative shift values work about as directly as you'd expect, actually being the bit offset. Any time the offset is larger than the length of the bitstring, the bits get shifted outside of the string without any looping effects. So shifting a `bit(32)` string by 32, 40, or 4000 all result in simply a bitstring full of `0`s, regardless of direction of the shift.

To summarize, the bit shifting operators for integers appear to take the positive value of *mod 32* of the second argument before performing the bit shift. Right-shifting negative integers preserves the sign bit.

I used this query (and some variations of it) to get the Postgres data:
```sql
SELECT data.val, data.numbits, data.result, data.result::bit(32) AS bitresult
FROM (
    SELECT raw.val, raw.numbits, raw.val >> raw.numbits AS result
    FROM (
        SELECT
            123::int4 AS val, n AS numbits
        FROM generate_series(0, 40) AS n
    ) AS raw
) AS data;
```

### Python

Without going into as many details, here's the summary of Python's approach to bit shifting operators:

* It is a `ValueError` to shift by a negative value.
* Any positive shift value is valid for both left and right bit shifting.
* A positive integer being bit shifted behaves as if there was an unlimited number of bits available to represent the integer, the sign never flips.
* A negative integer being bit shifted *always* preserves the sign bit no matter what. Otherwise the operation behaves as if there's an unlimited number of bits available for the integer.
* This is about as close as it gets to the pure "it's a logical bit shift for positive integers and an arithemtic bit shift for negative integers".

### GO

Without going into as many details, here's the summary of GO's approach to bit shifting operators:

* It is an error to shift by a negative value.
* Any positive shift value is valid for both left and right bit shifting.
* A positive integer being bit shifted behaves as if we are performing a logical bit shift of the underlying bit pattern without ever changing the total number of significant bits we consider. We then interpret the result as an integer, potentially flipping the sign. Shifting by a large enough number of bits in either direction just results in `0`.
* A negative integer being right-shifted preserves the sign bit. Eventually right-shifting resutls in `-1` regardless of how much more you shift. Left-shifting a negative integer works the same as for positive integers, eventually shifting it all the way to `0`.
* This is similar to Python, but because there's no unlimited number of bits available to represent the underlying integers, the results of logical and arithmetic bit shifts gets clipped to the integer size.

### JavaScript

Without going into details JavaScript treats bit shift operators pretty much the same as Postgres including taking the positive *mod 32* of the second argument. The main difference is in how many significant bits integers have and when exactly sign bit gets affected by bit shifting.

## Recommendation for EdgeDB

* It may be reasonable to require the second argument in `bit_rshift` and `bit_lshift` to be positive and an error otherwise. Generally, shifting by negative amounts is either forbidden in other languages (Python and GO) or behaves unintuitively (Postgres and JavaScript).
* None of the other examples treat shifting a number beyond either edge of the bit pattern as overflow or underflow. It is simply allowed. This suggests that EdgeDB should allow shifting in either direction by any positive amount.
* It seems that there's concensus that negative values should use arithemtic (sign-bit preserving) shifting when shifted to the right, specifically.
* It seems that shifting to the left can eventually flip sign bits in any language where shifting applies to a finite integer (Postgres, GO, JavaScript).
* It seems intuitive that shifting by `n` bits in some direction should get the same result regardless of whether the shift happens in a single step or multiple steps. This makes any approach taking a mod of the second argument unacceptable. If it's legal to shift a number by 1 bit 100 times, it should be just as legal to shift it by 100 bits 1 time and it should produce the same result.
* Postgres does not seem to allow casting `numeric` into `bit`, so we probably can't have a practical implementation of bit shifting for `bigint` (like Python does) in EdgeDB.

From all of the above it seems that EdgeDB should have pretty much the same approach as GO. This can be achieved by using the Postres's operators for shifting by a positive amount smaller than the bit length of a given integer type, while using `CASE WHEN` branches to provide an error for negative shifts and `0` or `-1` for shifts beyond the bit length.

P.S. The reason why Postgres examples use `int4` and not a shorter `int2` is because you cannot cast an `int2` into `bit(16)` and so showing the explicit bit-pattern would not be easy. The `>>` and `<<` are still valid for `int2`, though.
P.P.S. The *mod 32* behavior is applicable to both `int2` and `int4` in Postgres, whereas bit shifting `int8` uses *mod 64* for the second argument instead.
P.P.P.S. I haven't tried checking whether big- and little-endian encoding has any effect on the interaction of bit-shifting operators and ints, but it might. In practical terms it seems that modern systems use LE or support LE, so this concern is not likely to come up.

**Comment by tailhook** [comment]
So these operators in postgres, C, Rust behave like that because most common processors do that without additional checks. So technically if someone ever needs that performance we can provide `quick_shl` and `quick_shr` functions that compile directly to the operator. I still have concerns whether the performance difference will be noticeable in Postgres (i.e. at least only for JIT'ed queries, and so forth). And I guess that if noticeable amount of bit manipulation is needed it should be better solved by WebAssembly function eventually.

So yes, throwing on negative values and capping shift amount (instead of using `mod`) is the most promising solution.

**Comment by msullivan** [comment]
To do a logical shift in terms of arithmetic shifts, we can do an arithmetic shift, and then mask off the top bits:
```
int16_t logical_rsh(int16_t n, int amt) {
    int16_t mask = ((int16_t)(1 << (16-1)) >> (amt)) << 1;
    return (n >> amt) & ~mask;
}
```

**Comment by vpetrovykh** [comment]
We've implemented logical operations as well as a few more standard library functions in #3784
