### ISSUE TITLE
Automatically create object-getter functions

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#3810]
Currently, the shortest way to convert an object id into an object value is to do `SELECT MyObject FILTER .id = some-uuid`.  Since converting ids to objects is a fairly common operation, it seems like a good idea to auto-generate getter functions like:

```
type SomeObject;

# auto-generated function
function SomeObject(id: uuid) -> optional SomeObject {}
```

Whether it should be a regular function or some function-like intrinsic is an open question.

**Comment by elprans** [comment]
Sure.

**Comment by liron00** [comment]
It might also be useful to have an idiomatic way to pass around object IDs in string form like `Movie.xxxxxx-xxxx-xxxx`. E.g. these kinds of typed IDs are used as cache keys in frontend GraphQL libraries.

**Comment by liron00** [comment]
I also think it might be a bit nicer to be able to write a Typescript command like `e.selectById(e.Movie, 'xxx-xxx-xxx', {title: true})` rather than using `movie => ({filter: e.op(movie.id, '=', e.uuid('xxx-xxx-xxx-))})` because selecting by ID is such a fundamental concept to most DBs and such a common operation, it's not quite like other queries IMO.

**Comment by liron00** [comment]
For inserting/updating links, consider:

```
  const myDirectorId = 'xxxx-xxxx-xxxx';
  e.insert(e.Movie, {
    director: e.select(e.Director, director => ({
      filter: e.op(director.id, '=', e.uuid(myDirectorId)),
    })
  }).run(edgeClient)
```

vs something like

```
  const myDirectorId = 'xxxx-xxxx-xxxx';
  e.insert(e.Movie, {
    director: e.selectById(e.Director, myDirectorId),
  }).run(edgeClient)
```

Because this kind of situation comes up often for me

**Comment by colinhacks** [comment]
Once we commit to implementing Elvis's original proposal, we can add this into the query builder:

```ts
const myDirectorId = 'xxxx-xxxx-xxxx';
  e.insert(e.Movie, {
    director: e.Director(myDirectorId),
  }).run(edgeClient)
```

**Comment by msullivan** [comment]
We added casting to object types from `uuid`
