### ISSUE TITLE
Installation instrustion on website is wrong

### ISSUE THREAD

**Issue by locriacyber** [edgedb/edgedb#3815]
This is about https://www.edgedb.com/, not the database itself. I can't find another place to report this issue.

In the section

> One CLI
> to rule them all

```
curl --proto '=https' --tlsv1.2 -sSf https://get.edgedb.com | sh

edgedb project init

edgedb
```

`get.edgedb.com` is not a working domain name. Maybe it's `sh.edgedb.com`?

**Comment by elprans** [comment]
Fixed. Thank you very much for noticing and reporting!
