### ISSUE TITLE
Allow nested modules

### ISSUE THREAD

**Issue by rdlaitila** [edgedb/edgedb#3821]
When attempting to use nested modules with the following example schema:

```
module foo {
	module bar {
		type Thing {
			required property baz -> str;
		}
	}
}
```

We get an error when calling `edgedb migration create`:

```
error: nested module declaration is not allowed
  ┌─ ./dbschema/testmodule.esdl:2:2
  │  
2 │ ╭     module bar {
3 │ │         type Thing {
4 │ │             required property baz -> str;
5 │ │         }
6 │ │     }
  │ ╰─────^ error

edgedb error: cannot proceed until .esdl files are fixed
```

I think it would be a great value add to allow nested modules. Some of our projects require us to store objects relating to third-party vendors and their domains of interest. Only having the `<module>::<type>` convention can lead to a messy model in some situations. 

As one example:

```
<vendor>::<product>::<type>
```

Would allow one to model differentiating products from a single vendor. In the current module system we have to model as:

```
<vendor><product>::<type>
```

or 

```
<vendor>::<product><type>
```

which gets messy when recording facts about multiple products from a single vendor. I would hope allowing nested modules would benefit other dense domain models as well.

**Comment by d4h0** [comment]
This would be great.

I'm working on a project that probably will have several hundred of different kinds of objects/tables, so nested modules would be a huge help to organize these properly.

Directory-based nested modules would be great as well (either implicit, or explicit like e.g. Rust does).

**Comment by 1st1** [comment]
This has been implemented in 4.x I think.
