### ISSUE TITLE
Add dump of tutorial database for offline use

### ISSUE THREAD

**Issue by locriacyber** [edgedb/edgedb#3825]
Having an online tutorial connected to remote database is fine and all, but it's slower than connecting to local database.

It would be nice if the tutorial database is ready to be imported for offline exploration.

**Comment by colinhacks** [comment]
Here's a version you can play with locally: https://github.com/edgedb/movies. The README contains instructions for how to get started and seed the database with the sample data.

**Comment by locriacyber** [comment]
The repo is literally nonexistence.
