### ISSUE TITLE
Update parts of JSON properties with a json_set function

### ISSUE THREAD

**Issue by liron00** [edgedb/edgedb#3826]
Let's say initially `myMovie.json = {"a": 10, "b": 20}`

Instead of `update Movie set {myJson := to_json('{"a": 11, "b": 20}')};`, make it possible to do something like: `update Movie set {myJson := json_set(.myJson, 'a', .myJson['a'] + 1)}`.

It could just be syntactic sugar for cloning the whole JSON object and updating a deep field.

The syntax could be similar to `json_get` where the first argument specifies the JSON property, then the middle arguments are a path to a location within the JSON object to update, and the last argument is the value to set.

What if the path is invalid, e.g. `json_set(.myJson, 'a', 'x', 'y', 11)`? Maybe create singleton objects along the way to make it valid like `{"a": {"x": {"y": 11}}}`.

If there's an array along the path, could use numbers to specify indexes, and error if the path part isn't a number.

The command can potentially have a merge flag, so if `myMovie.myJson` initially equals `{"a": {"x": 5, "y": 6}}`, then `json_set(.myJson, 'a', to_json('{"y": 7, "z": 8}'))` could return `{"a": {"x": 5, "y": 7, "z": 8}}`.

**Comment by elprans** [comment]
I propose the following signature:

```
json_set(
  target: json,
  path: array<str>,  # We can't use variadic here, because new_value follows.
  new_value: optional json,
  named only create_if_missing: bool = false,
  named only empty_treatment: JsonSetEmptyTreatment = JsonSetEmptyTreatment.ReturnEmpty,
) -> optional json
```

Where `create_if_missing=true` causes intermediate elements to be created if missing, and `empty_treatment` is an enum determining what to do if *new_value* is an empty set:

```
scalar type JsonSetEmptyTreatment extending enum<
  ReturnEmpty,     # Return empty set, default 
  ReturnTarget,    # Return *target* unmodified
  RaiseException,  # Raise a ValueError
  UseJsonNull,     # Use a 'null` JSON value
  DeleteKey,       # Delete the object key
>;
```

This is basically the equivalent of PostgreSQL's `jsonb_set` and `jsonb_set_lax` functions.

**Comment by liron00** [comment]
Looks about right.

`path` probably needs to be something like `array<str|Int32>` to index into arrays.

I guess you're thinking `ReturnEmpty` would cause json_set to always be a no-op, i.e. doesn't make sense to call it this way in a command by itself, but sometimes useful as part of a larger expression?

Maybe the idea about being able to merge objects together at the end of the path, rather than replacing the whole leaf object, could be yet another named enum argument. Or a separate function `json_update` instead of `json_set`.

**Comment by elprans** [comment]
> `path` probably needs to be something like `array<str|int32>` to index into JSON arrays along the path.

Not really, in JavaScript `foo["1"]` and `foo[1]` are equivalent, so it's safe to use strings to index into arrays (`json_get` uses a `variadic` `str`).

> Maybe the idea about being able to merge objects together at the end of the path

This is where you should probably just use `++` instead.
