### ISSUE TITLE
`select *` for EdgeQL

### ISSUE THREAD

**Issue by liron00** [edgedb/edgedb#3838]
It's very common for me to want to use the CLI to just inspect an entire record. I know the JS client now supports a shortcut for `select *`. Can EdgeQL itself have it?

**Comment by Sikarii** [comment]
There is some discussion around this here: <https://github.com/edgedb/edgedb/issues/180>

**Comment by liron00** [comment]
Ah ok, I agree it makes sense as a REPL feature because the semantics are too ambiguous for EdgeQL.

I think it would be a very commonly used REPL feature, like more common than not to want to press tab and get that autocomplete for `select` commands done in the REPL.

**Comment by AnsonHwang86** [comment]
This issues should be closed, the splats syntax has come out https://www.edgedb.com/docs/edgeql/select#splats
