### ISSUE TITLE
edb.errors.IdleSessionTimeoutError: closing the connection due to idling

### ISSUE THREAD

**Issue by Androidown** [edgedb/edgedb#3853]
- EdgeDB Version: 2.0 (built from master branch)
- OS Version: Linux 3.10.0-1127.19.1.el7.x86_64

Steps to Reproduce:

Sorry that I'm using a custom java client and there might be some difference in implemention detail between the official library and my one. So I cannot give a minial reproducible example.
But I think the bug is actually quite obvious that maybe I can just explain it with code.

`_reinit_idle_gc_collector` returns timeout in seconds. 

```python
    def _reinit_idle_gc_collector(self) -> float:
        ...

        session_idle_timeout = config.lookup(
            'session_idle_timeout', self._dbindex.get_sys_config())

        timeout = session_idle_timeout.to_microseconds()
        timeout /= 1_000_000.0  # convert to seconds

        if timeout > 0:
            self._idle_gc_handler = self.__loop.call_later(
                timeout, self._idle_gc_collector)
        return timeout
```

Thus the `idle_timeout` in following code will be in seconds。 And the calculation:  `expiry_time  = now (microseconds) - idle_timeout (seconds)`  will be problematic. Which in some cases, lead to the IdleSessionTimeoutError.

```python

    def _idle_gc_collector(self):
        try:
            self._idle_gc_handler = None
            idle_timeout = self._reinit_idle_gc_collector()

            if idle_timeout <= 0:
                return

            now = time.monotonic()
            expiry_time = now - idle_timeout
```

**Comment by jhult** [comment]
@Androidown, do you have a link to the official and/or custom Java clients/libraries?

**Comment by msullivan** [comment]
That would be a nice easy fix, but unfortunately (for this bug!) `time.monotonic` does return seconds, not microseconds.

**Comment by msullivan** [comment]
How quickly are you timing out?

**Comment by Androidown** [comment]
> That would be a nice easy fix, but unfortunately (for this bug!) `time.monotonic` does return seconds, not microseconds.

Sorry, my mistake.

**Comment by Androidown** [comment]
> How quickly are you timing out?

> How quickly are you timing out?

Almost immediately after a command issued.  Maybe it's because I maintained a connection pool and didn't set `idle_session_timeout` to null for each connection. I'll take a look into it. Thanks for your reply.
