### ISSUE TITLE
Incorrect result when joining on a property of a computed link

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#3898]
### Discussed in https://github.com/edgedb/edgedb/discussions/3897

<div type='discussions-op-text'>

<sup>Originally posted by **stregouet** May 25, 2022</sup>
Hi,
I'm trying to query some of my data but I find strange behavior probably with `filter` clause which seems not so obvious to me.

Here is my schema:

```edgeql
module default {
  scalar type EventType extending str {
    constraint one_of ('wall', 'water', 'electrity', 'other');
  }

  type Building {
    required property number -> str {
      constraint exclusive;
    };

    link last_wall := ( select .events filter .evtype = <EventType>'wall' order by .datetime desc limit 1 );
    multi link events := .<building[is Event];
  }

  type Event {
    required property datetime -> datetime;
    property evtype -> EventType;
    link building -> Building;
  }
}
```
with some data

```
with 
  b1 := (insert Building {
    number := 'aa1',
  })
insert Event {
  datetime := <datetime>'2020-12-27T23:00:00Z',
  evtype := <EventType>'wall',
  building := b1,
};


with b1 := (select Building filter .number = 'aa1')
insert Event {
  datetime := <datetime>'2022-01-18T23:00:00Z',
  evtype := <EventType>'wall',
  building := b1,
};
with b1 := (select Building filter .number = 'aa1')
insert Event {
  datetime := <datetime>'2022-02-18T23:00:00Z',
  evtype := <EventType>'water',
  building := b1,
};
```

and here is my query

```edgeql
select Building { 
  number,
  last_wall: { datetime }, 
  w := (with lw := .last_wall select .events  filter .datetime = lw.datetime) };
```
I expect to get one element in `w` field (because there is only one event with `last_wall` datetime). But I got 2 (the 2 with `evtype` of `wall`). To get only 1 I need to modify query as follow:

```edgeql
select Building { 
  number,
  last_wall: { datetime }, 
  w := (with lw := .last_wall select (.events.datetime,)  filter .0 = lw.datetime) };
```

I suppose I miss something but I can't find what, could you help please?</div>

**Comment by msullivan** [comment]
Slight test case reduction:
Using the `cards` db:
```
alter type Card create single link best_award := (select .awards order by .name limit 1);
update Card filter .name = 'Dragon' set { awards += (select Award filter .name = '3rd') };
```
then
```
select Card { multi w := (select .awards filter .name = Card.best_award.name) }
filter .name = 'Dragon';
```

In this case, if you leave off the `multi` you get an ISE, since the cardinality gets inferred as single because of the constraint on `name`.

Wrapping `.awards` in another select (`select (select .awards) ...`) works around it, as does wrapping it in a tuple and immediate projection (`select (.awards,).0 ...`).

There is some sort of scope leakage: the broken case is only selecting from the awards table once, and it needs to be doing it twice.
