### ISSUE TITLE
General documentation update

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#39]
Here's a list of commits that require some amount of documentation updates:

- [x] lexical.rst has a bunch of empty sections. 

- [x] graphql: Implement reflection of ObjectTypes. (commit 0d8d5a7215f15ae16e2127f0973cfb5364e18b16)

    ObjectTypes get reflected as type INTERFACE into GraphQL. Additionally,
    non-abstract ObjectTypes get reflected as type OBJECT, but with the
    "Type" appended at the end of their name.

    This allows the return type of fields/functions to be specified in terms
    of INTERFACE types and the actual object __typename to reflect the
    OBJECT type of the specific instance.

- [x] Allow aliasing links in shapes (commit ec91dcedc1d764d02dbef8badaac759f1830e2e0)

    When a computable expression contains a path, use the trailing
    link or property as a base for the computable in shape.
    For example, in `Spam { alias := Foo.bar }`, `Spam.alias`
    is derived from `Foo.bar` inheriting its properties.

- [x] edgeql: Add `re_replace` function to `std`. (commit 9c20ef1b6768b616a91d09d66269068c1a586d73)

- [x] graphql: Use a `filter` argument for more flexible filtering. (commit aa1c201e77c8aa7494a1819c1266ced29320fffa)

    Rather than taking arguments corresponding to the individual fields, use
    a single `filter` argument to specify the filtering conditions. This is
    more generic and easier to add more functionality to in the future.

- [x] graphql: Add `orderBy` argument. (commit 20f59c43d0df12996fda5f19e815350b01834716)

    All fields that return a list of objects can now be ordered by one or
    more of the scalar fields on that object.

- [x] Disallow overriding the 'id' property (commit e502f4c8b96c6b45d26b8b9a0ea56908a1583146)

    The value of the `id` property of an object coresponds to object's identity
    (and value).  It is both unsafe and unintuitive to allow arbitrary
    re-definition of `id`.

    ```
    SELECT Foo ORDER BY Foo;
    SELECT Foo ORDER BY Foo.id;
    ```

    The above queries are equivalent by default, but would stop being equivalent
    if `id` was re-defined in a view.

    Fixes: #214

- [x] graphql: Add slicing support. (commit f0190771b99d8608c1f3f92d437283193437967c)

    Add `after`, `first`, `before` and `last` arguments to anything that
    returns an object list. The arguemnts have the same semantics as in
    Relay Connections regardless of whether the field returns a Connection
    or a plain List.

- [x] edgeql: Update the type specification syntax. (commit 03b3d5219eab8b5e5798bbfcfc613549264423df)

    Introduce type expressions - syntactical constructs denoting types and
    type composition.

    Operator `|` produces a union type that is a duck type having the
    intersection of all of the links and properties of the component types.
    Semantically any object that is an instance of at least one of the
    component types is also an instance of the union type.

    Operator `&` produces an intersection type that is a duck type having
    the union of all of the links and properties of the component types.
    Semantically only an object that is an instance of all of the component
    types is also an instance of the intersection type.

    Syntactically type expressions are general and can be used anywhere
    where a type can be used. There may be some exceptions, notably only
    base types can be used in `extending` specification.

- [x] edgeql: Add `REQUIRED expr` syntax. (commit 1bf7fd96ecf9100e90a818004b764131741e3848)

    Issue #217.

- [x] edgeql: Add `INDEX` syntax. (commit 1ae3b8b3d5592ce436e6b6f52724ae07dd3b3b5c)

    Issue #148.

- [x] Add schema::Database type to allow listing cluster databases (commit a6dbe9dd9192f3e2c64c78eb5261b22e694f851d)

- [x] edgeql: Add `ON TARGET DELETE...` syntax to concrete links. (commit 69feb44b431eae162560ac643c393f6d37285aec)

- [x] schema: Add `on target delete ...` syntax to the schema. (commit 9306fffb10e18a97c1962730c3e693565e7af9e2)

- [x] edgeql: Disable `GROUP` statements util they are implemented. (commit d9ad223ee84de02379649482213e482cee3081dd)

- [x] edgeql: Add `array_get`. (commit 2b309f9932d625e78ad921994cf666db84ade3b8)

    Function `array_get` returns an array element or an empty set if the
    index is out of bounds.

- [x] Implement new syntax for function parameters (commit 78b97c3227a46ebabb1f3fa2b87c1a430deb5c14)

    Paremeter kind and parameter type are now different things.
    The following parameter kinds are supported right now:

     * regular positional parameters
     * VARIADIC
     * NAMED ONLY

    The syntax for declaring functions & constraints not longer
    allows to specify unnamed parameters -- names are required.

    Old syntax:

        CREATE FUNCTION foo(int64)
        CREATE FUNCTION foo(VARIADIC SET OF str)
        CREATE FUNCTION foo($a: VARIADIC SET OF str)

    New syntax:

        CREATE FUNCTION foo($p: int64)
        CREATE FUNCTION foo(VARIADIC $name: SET OF str)
        CREATE FUNCTION foo(VARIADIC $a: SET OF str)

    Syntax for declaring named-only parameters (not yet supported by the
    compiler):

        CREATE FUNCTION foo($pos1: int64, $pos2: str,
                            NAMED ONLY $n1: str, NAMED ONLY $n2: int64)

    Named-only parameters will only be supported by functions (not
    constraints).

- [x] edgeql: Add JSON funcitonality. (commit 6d3352c5509ab9fd9b985b51ec8b8b2dffd64fa9)

    New JSON functions:
    - str_to_json
    - json_to_str
    - json_typeof
    - json_array_unpack
    - json_object_unpack
    - json_get

    The `[]` indexing operator is also available for JSON. This operator is
    strict and will raise an exception if it is used with a non-existent
    index value (this is true for JSON, strings and arrays).

    There's a new `array_get` function that doesn't perform the boundary
    check on the index value and returns an empty set if there is no such
    index.

- [x] Add support for casting objects and tuples to std::json (commit 8b7a72e27f9d45d55d1c10ab638c630f9becdd9d)

    `<json>Object` now always returns a `std::json` value containing
    the output representation of the object. That is, the result is
    the same as the output of `SELECT Object` in JSON mode, including
    the type shape.

    Now, casting a non-named tuple to `std::json` returns a JSON array,
    and casting a named tuple to `std::json` returns a JSON object.

    Casting non-scalar JSON values to scalars is now an error, as well as
    casting a non-matching JSON scalar value.

    Issue: #251.

- [x] Prohibit VARIADIC parameters from having default values (commit 952be2f82e897f0b994553ec017d1432e2e18267)

- [x] Implement named and variadic arguments; fix type system. (commit 57a24bfd5f4556adc42ac084a1b2846eb38722e9)

    1. Now we support named arguments and variadic parameters:

       SELECT foo(1, 2, 3, $arg := 'val')

    2. Type system was fixed to correctly handle implicit casts for
       ints and floats.

- [x] Add support for `on target delete` clause for links (commit ef120bd52bbb3bd846be303f850571b895998e29)

    The new `on target delete` clause of concrete links is a mechanism
    to specify what happens when a target object of a link instance
    is deleted.

    Currently implemented modes are:

    * `RESTRICT` -- produce an error indicating that deletion cannot be
      done due to an existing link. This is the default.
    * `DEFERRED RESTRICT` -- same as the above, but the check is postponed
      until the end of the current transaction, if there is no transaction,
      equivalent to `RESTRICT`.
    * `SET EMPTY` -- remove the link, can only be used with links that are
      not required.
    * `DELETE SOURCE` -- remove the link and the source of the link
      (cascaded deletion).

- [x] Update function declaration and call syntax (commit 6377f9309d90216c40d3a79c0ea873fa72aa88ef)

    No longer use '$' as a prefix for parameter names in function
    signatures and call expressions.  This is to declutter the syntax
    in expressions like the following:

        func($foo, $default := $something)

    which now becomes

        func($foo, default:=$something)

    It's now immediately clear what refers to a variable and what sets a
    value for a named argument.

- [x] edgeql: Alter the precedence rules. (commit c9a3164b7a190555fae53311f24e65ca0acc96fa)

    Move shapes `{}` to a higher precedence, same group as `[]`.

    Move `DETACHED` in between `::` and `.` in precedence.

    Update existing tests and add more tests on interactions between
    precedence, shapes, scopes, and `DETACHED`.

- [x] Add new b'bytes' literal (commit 7cecc9bb8e4e204837cac5f36e76fe5fed4d2573)

    Can contain (lexical structure):

    * any printable ascii character
    * \xXX hex escapes
    * \', \", \\
    * \n, \t, \r
    * new lines

    Requires a 'b' prefix before quotes, e.g.:

        SELECT b'bytes';

    Supports slicing and indexing:

        db> SELECT b'bytes'[1]
        b'y'

        db> SELECT b'bytes'[0:2]
        b'by'

- [x] Enforce lexical structure in string literals; support escape seqs (commit 094fc1830e1b227cf192679917d724d11fafc482)

    Allowed escape codes in string literals:

    * \n, \t, \r
    * \\, \', \"
    * \xXX, \uXXXX, \UXXXXXXXX

    Otherwise string literals allow any unicode characters and new lines.

- [x] Add support for raw string literals; tweak lexer/ast. (commit 399cb02fe8b86fbcccbc4b6ec985c455b68b0249)

    1. Add raw strings.

    * `$$ ... $$` strings are now raw strings.

    * New syntax: `r'...'` and `r"..."` -- raw string literals.

    Raw strings do not process any escapes, meaning that `\` symbol
    acts just as any other one.

    2. Tweak string literals.

    Regular strings no longer accept \xhh codes over 0x7F.  This is
    modeled after Rust strings [1], quoting:

    "Higher values are not permitted because it is ambiguous whether
    they mean Unicode code points or byte values."

    3. New AST nodes.

    EdgeQL and IR implementations got two new nodes: `StringConstant` and
    `RawStringConstant`.  SQL has also a new node: `EscapedStringConstant`
    (compiles to an `E'...'` string).

    [1] https://doc.rust-lang.org/reference/tokens.html#character-escapes

- [x] schema: Add support for spaces + tabs indents. (commit af76bc27c0b97348330dc007159b0916ce338e51)

    Indentation must be consistent, so if a mix of tabs and spaces is used,
    tabs must come first and shallow indentation must be an exact prefix of
    deeper indentation.

    It is illegal to use a tab after a space in indentation.

    It is illegal to use a line continuation immediately after indentation.
    Some other content must appear first on that line.

    Whitespace is still ignored in parentheses or in the middle of a line
    even if it is extended via line continuation.

- [x] Implement support for polymorphic functions (commit a8424aaa6625f92e093017b3b9d1f552e8400c2f)

- [x] Update re_* functions to have "pattern" as a first parameter (commit c69770b8f648e7069b8612a4ab21426501699325)

    Closes #269.

- [x] Make regular division return floats and add a floor division operator (commit d0b572ecd6e050e3c61ec82998147ca2423a9d38)

    In another break with tradition, `/` now always performs a true division:
    even if the operands are integers, the result is a floating point
    approximation of the division result.  The new `//` operator allows
    pefforming floor division explicitly.

    In this change we largely follow the motivation of Python's PEP 238.
    Classic behavior of integer division makes it hard to write polymorphic
    functions that work with arbitrary numeric types, especially if one
    considers numbers beyond the real plane, as blind casting of one of the
    operands may not work as expected.

- [x] Allow indexing named tuples by position; fix named tuples serialization (commit 3e0832cb1f631fade5e3efebc904d61576c4f1ca)

    Named tuples can now be indexed by position.  The below two queries are
    equivalent:

        db> SELECT (a:=1).a;
        db> SELECT (a:=1).0;

    Named tuples will now be correctly serialized to JSON in more cases,
    for example:

        db> SELECT [(a:=1)][0];
        {"a": 1}

    Serialization of nested named tuples is still broken in some cases
    though:

        db> SELECT [(a:=(x:=1))][0];
        {"a": {"f1": 1}}

- [x] Rename "any" to "anytype" (commit ac30a5ffb8293ed54180c885b0b71e4052590ab1)

    We want to add a "std::any()" function and it seems that renaming
    "any" to "anytype" is a better option than specialcasing any()
    production in the grammar.  Also "anytype" plays nice with "anyscalar"
    and "anyint".

- [x] Rework the way relationship cardinality constraints are expressed (commit f77fe8c84b522f1129d8958bfdfe19347e148327)

    We currently represent relationship cardinality as the `cardinality`
    attribute in concrete link and property definitions.  The accepted
    values are `'11'` (one-to-one), `'1*'` (one-to-many), `'*1'` (may-to-one),
    and `'**'` (many-to-many).  While this is accepted parlour, the
    interpretation of the constraints, together with the separate `required`
    qualifier produces a fair amount of cognitive load.

    In reality, the current monolithic relationship cardinality actually
    represents two distinct properties: the cardinality of the target set
    when traversing a pointer from a given source (the second '1' or '*'),
    and the *exclusivity* constraint on the target (the first '1' or '*').
    The first property needs to be specified far more often than the second,
    so it makes sense to separate them.

    Now, a concrete link or property declaration can include the new target
    set cardinality qualifier in the form of the new `single` and `multi`
    keywords.  For example:

        type User:
            link friends -> User:
                cardinality: '**'

    becomes:

        type User:
            multi link friends -> User

    The `single` qualifier is the default, but can still be specified:

        type Issue:
            single link status -> Status

    The `required` qualifier can be combined with the `single`/`multi`
    qualifier to form a precise target set cardinality requirement:
    `single` means zero-or-one, `required single` means `exactly one`,
    `multi` means zero-or-more, `required multi` means `one-or-more`.

    The second relationship cardinality property is target exclusivity, i.e.
    how many sources can relate to a given target, is now represented by the
    `exclusive` constraint, which is the current `unique` constraint, but with
    a new, more appropriate name.  It is more natural to say that a given
    relationship is exclusive, rather than unique. For example, in the
    relationship `Person -> owns -> Chair`, "this chair is exclusive to this
    person" is better than "the Person/Chair relationship is unique":

        type Person:
            single link owns -> Chair:
                constraint exclusive

    So, to summarize:

    Former '11' is now `single` + `constraint exclusive`.
    Former '1*' is now `multi` + `constraint exclusive`.
    Former '*1' is now just `single` (this is the default).
    Former '**' is now just `multi`.

    The new qualifier syntax is also significantly more natural to use with
    computable links and properties when an explicit cardinality qualifier
    needs to be given to override the inferred value:

        type Person:
            multi link items := {'item'}

    This now extends to ad-hoc computables in queries as well, so:

        SELECT Person {
            multi items := {'item'}
        }

    instead of the awkward and somewhat arcane:

        SELECT Person {
            items := (WITH CARDINALITY '*' SELECT 'item')
        }

    The `WITH CARDINALITY '*'` syntax is now entirely unnecessary and has
    been removed.

    The new syntax also allows expressing the non-zero cardinality
    requirement with the `required` qualifier on the computable, but that is
    left for a subsequent commit (see #217).

    Closes: #303.

- [x] edgeql: Update how time and date is handled. (commit a3457f33b7af7739ece0cad19bc66d1cccfb02bc)

    The time and date scalars are:
    - datetime
    - naivedatetime
    - naivedate
    - naivetime
    - timedelta

    There are 3 different functions for obtaining "current" datetime:
    - datetime_now
    - datetime_of_statement
    - datetime_of_transaction

    There are also a suite of functions that extract specific date or time
    parts:
    - datetime_get
    - date_get
    - time_get
    - timedelta_get

- [x] edgeql: Add converter functions for multiple data types. (commit 19e6a2343fb0f652dac2e2f9f779ebd3816b2a15)

    The `to_str` function is meant to be like a cast when called
    without the format parameter.

    `to_str` usage with `json` scalars is not equivalent to casting, it is
    producing a string representation of JSON. The inverse function `to_json`
    is therefore parsing a string, not casting either:
    - `str_to_json` becomes `to_json`
    - `json_to_str` becomes `to_str`

    Add various date and time converter functions.

- [x] Restrict usage of abstract scalars and anytype. (commit a23af17c68ca45e0e9eb6e80b5b6fc6a9997f2d6)

    Casting into an abstract scalar or anytype is now forbidden.

    Technically anytype is a valid type that is the supertype for both
    anyscalar and Object. However, it is currently illegal to use it
    anywhere outside of a function signature definition.

    Anytype is also special in the fact that it doesn't have a corresponding
    entry in the schema module (no Type object).

- [x] edgeql: Make casts more consistent. (commit fe0e8cb48fcd67fd1b6c22ebeb710bb08e3d3dbd)

    Forbid casting bytes into anything other than bytes (this makes sense
    for scalar types derived from bytes).

    Make JSON casts symmetric. For any type that allows a cast into json, it
    should also allow to cast back without additional intermediate steps
    (such as casting into str first).

- [x] Formally implement fundamental operators as part of stdlib (commit f406f99ea951bf96df33424a5d02bf610dd17775)

    This declares currently supported binary and prefix operators
    on standard scalar types using the new `CREATE OPERATOR` DDL.
    Expression type inference has been switched over from a
    hardcoded table to looking up operators from the schema.

    This also allows removing a bunch of hardcoded logic from the
    compiler, since we can now consistently rely on the operators
    properly reflected in the backend.

    This commit also features correct implementation of the floor division
    (`//`) and division remainder (`%`) operators, which now truncate toward
    negative infinity, like Python does.

- [x] Implement array, string and byte concatenation via the `++` operator (commit de73ddf94951dccaccfe031cd473f0852ef1ec14)

    The current `+` operator is a poor choice for concatenation, especially
    in the array case, since the latter may be interpreted as an
    element-wise vector addition.  Instead, use `++` consistently as the
    concatenation operator for all data types that support it.

    Closes: #330.

- [x] Prohibit casting of object types (commit deacffbdf50e4c7dbcff060f53f66b5423376b74)

    Object types cannot be cast between themselves, as cast is a
    _constructor_ operation, and the only valid way to construct
    an object is to INSERT it.

- [x] Implement new syntax for the SET command. (commit 6bd90217c495358825954b27162a573154a1d615)

    Supported variants:

    * SET CONFIG name := expr;
    * SET MODULE default;
    * SET ALIAS my_foo AS MODULE foo;

    Partially addresses issue #347.

- [x] edgeql: Add more library functions. (commit 1553f270f07ab58b890464958a32b64d35156653)

    Add more generic functions to `std` module like min, max, round, etc.

    Add some specialized functions to `math` module.

- [x] Remove invalid DETACHED test (commit c323d4b994e8a0714612839c5a6d34b4e1dd8b4d)

    DETACHED no longer works the way the test expects it to.

- [x] Rework schema item attributes (commit 9cf7c8aab936824202d24c32763defb329ef0e81)

    Schema attributes are named values associated with schema items and are
    designed to hold arbitrary user-defined schema-level metadata.

    There are several shortcomings with the current implementation that
    need tweaking.

    First issue: attributes can currently be of any primitive type, which
    makes it really hard to represent the attribute collection as a
    coherent whole without resorting to some string serialization, and that
    can go sideways quickly if the attribute type is reasonably complex.
    Thus, we stop pretending to support arbitrary types in attributes, and
    only support `std::str`.  Complex structures can be stored as JSON and
    coerced to a specific EdgeQL type explicitly, so this change has no
    practical usability loss.  This also means that abstract attribute
    declaration does not require a type specification anymore, although we
    may revisit this in the future and allow `std::str` sub-types to be used,
    to, for example, allow specifying constraints on attribute values.
    Abstract attribute declarations continue to be required for
    disambiguation purposes.

    Second issue: standard schema item aspects, like link cardinality, are
    represented as attributes in the introspection schema. There is no
    reason to do it, and this creates confusing duality, since some aspects
    are represented as properties and links of the appropriate
    `schema::Object` subtype. We stop doing this, and only reserve
    `schema::Object.attributes` to things that are true annotations and bear
    no effect on the core schema behavior. Currently the only attributes
    that satisfy this requirement are `"title"` and `"description"`.

    In DDL, the `SET <attribute-name> := <attribute-value>` is changed to
    `SET ATTRIBUTE <attribute-name> := <attribute-value>`.

    In schema DSL we allow setting attribute values on foreign schema items
    using the regular declaration syntax with a qualified name:

        type othermod::Foo:
            attribute attr := 'value'

    Issue: #306

- [x] Make attributes non-inheritable by default (commit 9798846ddd7cc6192dea4f2de9376a1d5414e718)

    Automatic inheritance of attributes is sometimes inconvenient or
    undesirable. A "description" attribute, for example, is unlikely to be
    useful when inherited. Thus, we make all attributes non-inheritable by
    default, with an option to opt-in to automatic inheritance with the new
    `INHERITABLE` qualifier for `CREATE ATTRIBUTE`:

        CREATE INHERITABLE ATTRIBUTE foo;

    Issue: #306

**Comment by vpetrovykh** [comment]
Some functions to consider for standard library:
- `position(sub: str, full:str) -> int32` find a position of a substring in a string
- `position(el: anytype, arr: array<anytype>) -> int32` find a position of an element within an array
- `str_join(sep: str, arr: array<anytype>) -> str` cast each element into <str> and join them, or we can have only the version that handles specifically an `array<str>`
- `str_split(sep: str, full: str) -> array<str>` split a string by non-overlapping instances of separator

**Comment by elprans** [comment]
@vpetrovykh It occurred to me that we use explicit `std::` in docs examples a lot.  Since `std::` is always implicitly available in the namespace, please drop its use from the examples.

**Comment by 1st1** [comment]
Another TODO: `lexical.rst` has a bunch of empty sections.  Need to fix that.

**Comment by vpetrovykh** [comment]
Documentation is now up-to-date.
