### ISSUE TITLE
Union of objects with identical property names assigned with different base types

### ISSUE THREAD

**Issue by Krande** [edgedb/edgedb#3935]
Hey, this is a continuation of the question I asked on [Discord](https://discord.com/channels/841451783728529451/849377751370432573/981203479425069136) regarding union of objects with similar property names assigned with different base types. I have tried to find answers in the docs or in the issues/discord, but unfortunately I could not find exactly what I was looking for.

Specs:

- EdgeDB Version: 1.4+ffe1237
- OS Version: Windows 11

My question is why boolean of 2 objects with identical property names assigned with different base types are not OK (like below)

resulting in `edgedb error: SchemaError: cannot create a union of std::bool, std::float64`

```
module default {

    type IfcAbsorbedDoseMeasure {
        required property value -> float64;
    }

    type IfcBoolean {
        required property value -> bool;
    }

    type IfcValue {
        required property somevalue -> IfcAbsorbedDoseMeasure | IfcBoolean;
    }
}
```

But if I change the property names, 

```
module default {

    type IfcAbsorbedDoseMeasure {
        required property value1 -> float64;
    }

    type IfcBoolean {
        required property value2 -> bool;
    }

    type IfcValue {
        required property somevalue -> IfcAbsorbedDoseMeasure | IfcBoolean;
    }
}
```

it is considered fine. 

The reason why I am asking is that I am converting a rather large existing schema written in EXPRESS, and it contains a lot of identical property names with this exact issue. 

Any help is much appreciated!

Best Regards
Kristoffer

**Comment by elprans** [comment]
The issue is that EdgeDB does not support unions of scalar types yet (i.e. there is no `int64 | str`).  On the other hand a union of object types is an _intersection_ of common properties and links, but since it's impossible to derive a proper type for a common property, union fails.

Looking at the schema, I'd suggest using a tagged union (as an object type) instead, e.g:

```
scalar type TypeEnum extending enum<Boolean, Float64, ...>;

type IfcValue {
    required property type -> TypeEnum;
    property bool_value -> bool;
    property float64_value -> float64;
    ...
}
```

If your values are all primitive (i.e bools, numbers and strings), then another option is to use `std::json` and discriminate on `json_typeof`.

**Comment by Krande** [comment]
Hello, thank you for the quick response!

Okay, what you suggest seems like a fair compromise. 

I am also experiencing issues with union/intersection of `enums` that I believe could be related?

The following example results in an issue: `SchemaError: cannot create a union of default::IfcExternalSpatialElementTypeEnumBase, default::IfcSpaceTypeEnumBase`

```
module default {

    scalar type IfcExternalSpatialElementTypeEnumBase extending enum<`EXTERNAL`, `EXTERNAL_EARTH`, `EXTERNAL_FIRE`, `EXTERNAL_WATER`, `NOTDEFINED`, `USERDEFINED`>;
    
    type IfcExternalSpatialElementTypeEnum {
        required property IfcExternalSpatialElementTypeEnum -> IfcExternalSpatialElementTypeEnumBase;
    }

    scalar type IfcSpaceTypeEnumBase extending enum<`EXTERNAL`, `GFA`, `INTERNAL`, `NOTDEFINED`, `PARKING`, `SPACE`, `USERDEFINED`>;
    
    type IfcSpaceTypeEnum {
        required property IfcSpaceTypeEnum -> IfcSpaceTypeEnumBase;
    }

    type IfcExternalSpatialElement {
        required property PredefinedType -> IfcExternalSpatialElementTypeEnumBase;
    }

    type IfcSpace {
        required property PredefinedType -> IfcSpaceTypeEnumBase;
    }

    type IfcSpaceBoundarySelect {
        link IfcSpaceBoundarySelect -> IfcExternalSpatialElement | IfcSpace;
    }
}
```

I tried wrapping the `enum`s in objects, but that resulted in a different error: `edgedb error: InvalidReferenceError: object type 'default::(default:IfcExternalSpatialElementTypeEnum | default:IfcSpaceTypeEnum)' does not exist`

```
module default {

    scalar type IfcExternalSpatialElementTypeEnumBase extending enum<`EXTERNAL`, `EXTERNAL_EARTH`, `EXTERNAL_FIRE`, `EXTERNAL_WATER`, `NOTDEFINED`, `USERDEFINED`>;
    
    type IfcExternalSpatialElementTypeEnum {
        required property IfcExternalSpatialElementTypeEnum -> IfcExternalSpatialElementTypeEnumBase;
    }

    scalar type IfcSpaceTypeEnumBase extending enum<`EXTERNAL`, `GFA`, `INTERNAL`, `NOTDEFINED`, `PARKING`, `SPACE`, `USERDEFINED`>;
    
    type IfcSpaceTypeEnum {
        required property IfcSpaceTypeEnum -> IfcSpaceTypeEnumBase;
    }

    type IfcExternalSpatialElement {
        required link PredefinedType -> IfcExternalSpatialElementTypeEnum;
    }

    type IfcSpace {
        required link PredefinedType -> IfcSpaceTypeEnum;
    }

    type IfcSpaceBoundarySelect {
        link IfcSpaceBoundarySelect -> IfcExternalSpatialElement | IfcSpace;
    }
}
```

similarly to the original issue the root cause is likely the intersection of objects and the shared property name `PredefinedType`. 

To solve this I guess I could change the `PredefinedType` property name to make it unique for all objects, but that would mean I would have to move further away from the original schema. Any suggestions on how I should proceed here?

Out of curiosity, when you say _"support union of scalar types `yet`"_. Does it mean that this is on the roadmap? If so any ideas on when it can be expected to be rolled out for testing?
