### ISSUE TITLE
InternalServerError: column "f68496a2-eca2-11ec-b62e-d34bce7c0a12" is of type uuid but expression is of type record

### ISSUE THREAD

**Issue by MainTobias** [edgedb/edgedb#3966]
- EdgeDB Version: 1.4
- OS Version: Windows 10.0.19044

edgedb migrate
Connecting to an EdgeDB instance at localhost:10701...
edgedb error: InternalServerError: column "f68496a2-eca2-11ec-b62e-d34bce7c0a12" is of type uuid but expression is of type record
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: column "f68496a2-eca2-11ec-b62e-d34bce7c0a12" is of type uuid but expression is of type record

[Project stucture](https://drive.google.com/file/d/1gecCtXrjQjRKPfD8poaxd22g9FNz4nnz/view?usp=sharing)

**Comment by msullivan** [comment]
The culprit as to why things are going wrong is this expression for populating the newly created `logo` field:
```
          SELECT
              default::Logo {
                  url := 'some_url'
              }
          LIMIT
              1
```
We generate bogus code for it because of the presence of the shape, but the shape doesn't accomplish anything even if we didn't mess up

I think it should produce an error
