### ISSUE TITLE
Property of array<ENUM> breaks the graphql extension

### ISSUE THREAD

**Issue by jerber** [edgedb/edgedb#3990]
- EdgeDB Version: 1.4
- OS Version: tested on many

Steps to Reproduce:

1. See schema below and add the graphql extension line and then go to the gql endpoint.

Schema:

```
scalar type Tag extending enum<Rock, HipHop>;

type Artist {
   property name -> str;
   property tags -> array<Tag>;
}
```

When you go to the graphql endpoint you get the error `TypeError: InsertArtist fields cannot be resolved.` When you comment out the property `tags` it works again. If you do `multi property tags -> Tag` it works. So there is something with the `array<Tag>` that is breaking the gql extension.

**Comment by ccsv** [comment]
Should it be like this:

```
scalar type Tag extending enum<Rock, HipHop>;

type Artist {
   property name -> str;
   property tags -> Tag;
}
```

I thought the enums are like a list of strings that you are selecting one string to be stored as the enum value not an array
