### ISSUE TITLE
Network unreachable while listing EdgeDB versions. Version file not found

### ISSUE THREAD

**Issue by ranfdev** [edgedb/edgedb#4010]
- EdgeDB Version:  EdgeDB CLI 1.1.2+58eb29e

- OS Version: I'm running this on podman (docker alternative): podman version 4.1.1. The OS is NixOS but shouldn't make a difference here

- Container info
```
{
...
"Image": "df7745db3c57451bea3e8c3da1dbaa9a2c39875ee130125119a39079d7553ef6",                                 
"ImageName": "docker.io/edgedb/edgedb-cli:latest",    
...
}
```
Error: 
```
edgedb error: failed to fetch JSON at URL: https://packages.edgedb.com/archive/.jsonindexes/x86_64-unknown-linux-gnu.json: HTTP error: An error occured while creating a new object: Network unreachable (os error 101)
```
The error says the network is unreachable, but that's not true. I can connect to my instance with podman. I just can't init a project in it, because of this error. The real problem is the JSON file at `https://packages.edgedb.com/archive/.jsonindexes/x86_64-unknown-linux-gnu.json` doesn't exist (status 404).

Steps to Reproduce:

```
❯ podman run -it --rm --net=edgedb   -e EDGEDB_SERVER_PASSWORD=... -v ./:/home/edgedb edgedb/edgedb-cli project init --project-dir=/home/edgedb
[2022-06-30T16:12:33Z WARN  edgedb::version_check] Cannot check for updates: failed to fetch JSON at URL: https://packages.edgedb.com/archive/.jsonindexes/x86_64-unknown-linux-musl.json: HTTP error: An error occured while creating a new object: Network unreachable (os error 101)
No `edgedb.toml` found in `/home/edgedb` or above
Do you want to initialize a new project? [Y/n]
> Y
Specify the name of EdgeDB instance to use with this project [default: edgedb]: 
> edgedb
Checking EdgeDB versions...
edgedb error: failed to fetch JSON at URL: https://packages.edgedb.com/archive/.jsonindexes/x86_64-unknown-linux-gnu.json: HTTP error: An error occured while creating a new object: Network unreachable (os error 101)
```

What I've tried:
I've tried setting the version manually by passing the flag `--server-version=1.4` but the program keeps trying to fetch that JSON file.

**Comment by elprans** [comment]
> The real problem is the JSON file at `https://packages.edgedb.com/archive/.jsonindexes/x86_64-unknown-linux-gnu.json` doesn't exist (status 404).

Hm.  It exists.  Your error seems to suggest that your container does not have proper outbound Internet access.

**Comment by ranfdev** [comment]
Ah, I had opened the link in my web browser by clicking on my terminal, and it added a `:` at the end, so my browser returned 404.
That was an unfortunate chain of problems...
Sorry for the mess.

Anyway, is it really necessary for the cli to require internet access when I have everything installed locally?

**Comment by ranfdev** [comment]
I just wanted to test the db without encountering possible linking issues related to NixOS, which is common.
I'm happy to know the cli is statically linked.

I'm going to make a proper Nix package soon anyway.
