### ISSUE TITLE
Slow query when filtering by second link

### ISSUE THREAD

**Issue by rileytomasek** [edgedb/edgedb#4160]
- EdgeDB Version: 1.4+ffe1237 
- OS Version: your CloudFormation template

Simplified schema:
```
Person { multi link personPosts := .<person[is Profile].profilePosts; }
Profile {
  link person -> Person {
    delegated constraint exclusive;
  }
  multi link profilePosts := .<owner[is Post];
}
IGProfile {}
TTProfile {}
Post { required link owner -> Profile; }
IGPost { overloaded required link owner -> IGProfile; }
TTPost { overloaded required link owner -> TTProfile; }
```

These queries are both fast:
```
select Post filter .owner.id = <uuid>"";
select Person { personPosts } filter .id = <uuid>"";
```

But this one take 5+ seconds:
```
select Post filter .owner.person.id = <uuid>"";
```

Number of objects:
Person: 100
Profile: 150k
Post: 431k

I'm happy to share more details if it would be helpful.

**Comment by msullivan** [comment]
Interesting. I was able to reproduce this slowness.

If we do the select on just one of the post types, like
```
select TTPost filter .owner.person.id = <uuid>'3752263c-12a0-11ed-80df-cbe9314dd309';
```
it is much faster, but still kind of slow: 250ms vs 2.6ms for one of the shape ones.

**Comment by msullivan** [comment]
I think the crux of the issue is that we are doing a semi-join on `.person` because `Post.owner` isn't visible.
If we do 
```
select Post filter (for x in .owner union (x.person.id = <uuid>$uid))
```
or
```
select Post filter (.owner, .owner.person.id = <uuid>$uid).1
```
then it is fast.

I think it should be possible to disable the semi-join in this case, since `Post` is visible and `.owner` is single

**Comment by rileytomasek** [comment]
Thank you 🙏🏻
