### ISSUE TITLE
EdgeDB site looks ugly under dark theme: square "snowflakes" 

### ISSUE THREAD

**Issue by mrkeuz** [edgedb/edgedb#4178]
Sorry, that I post here, but not found separate repo for site. GitHub link on site follow me here. 

### Problem 

EdgeDB site looks ugly under dark theme (DarkReader) - square "snowflakes" (see screenshot).
So it interferes with viewing and also flikering when you move mouse.

- EdgeDB Version: N/A
- OS Version: N/A

### Steps to Reproduce:

1. Install DarkReader plugin
2. Open site https://www.edgedb.com/

### Expected

- Plain site with readable text

### Screenshot

![image](https://user-images.githubusercontent.com/6247921/182033484-ab02b4a8-ccf7-435a-9ade-7b9b4cde40f1.png)

Schema:

**Comment by 1st1** [comment]
@mrkeuz Thank for reporting this! We'll take a look, but it might be challenging to support every plugin like this.

@jaclarke please take a quick look if we can detect DarkReader and disable/hide certain elements.

**Comment by 1st1** [comment]
@mrkeuz The website should redeploy within the next few minutes with the dark reader rendering much improved.

**Comment by mrkeuz** [comment]
@1st1, @jaclarke, looks very good! DarkReader quite popular extension as I know. Now other users will no longer stumble over the design and will be satisfied. First impression is very important in my opinion.

Thanks! 🚀
