### ISSUE TITLE
unless conflict throws if constraints are declared at object level

### ISSUE THREAD

**Issue by lu-zen** [edgedb/edgedb#4227]
- EdgeDB Version: 2.1+c73716f
- OS Version: linutx lts

Steps to Reproduce:

1. Given the reprodution schema, run an insert with a conflict clause with one exclusive prop;
Query: 
```
INSERT User {
  email := 'a@example.com',
  social_num := 11313132,
} UNLESS CONFLICT ON .email;
```

Error:
```
error: QueryError: UNLESS CONFLICT property must have a single exclusive constraint
  ┌─ query:4:22
  │
4 │ } UNLESS CONFLICT ON .email;
  │                      ^^^^^^ error
```
Moving the constraint declaration into properties solves the issue.

Schema:
[schema for reprodution](https://github.com/lu-zen/edgedb-upsert-bug/blob/main/dbschema/default.esdl)

**Comment by Sikarii** [comment]
Did you mean to do ... `UNLESS CONFLICT ON (.email, .social_num)` to match your reproduction schema?

**Comment by lu-zen** [comment]
> Did you mean to do ... `UNLESS CONFLICT ON (.email, .social_num)` to match your reproduction schema?

Oops, tks, just updated it. With many props it doesn't work btw

**Comment by colinhacks** [comment]
As discussed on Discord:

The following snippet defines a composite exclusive constraint on the "tuple" of those two properties. i.e. two users could have the same email, or the same social, but not both.

```
constraint exclusive on ((.email, .social_num))
```

I think you want this - separate constraints for each.

```
constraint exclusive on (.email);
constraint exclusive on (.social_num);
```

Or better yet, define these constraints in the property definition instead the object definition (though it should work either way). There's currently no way to provide multiple `else` clauses that "catch" constraint violation errors on multiple distinct exclusive properties. 

A workaround is to leave of the `on/else` clause, check if the result is an empty set, then run an additional query to identify the conflicting object and conditionally execute update logic. All this should probably be executed in a transaction.

```
INSERT User {
  email := 'a@example.com',
  social_num := 11313132,
} UNLESS CONFLICT;
```
