### ISSUE TITLE
Deployment in Azure only connectable after linking with CLI. Unable to use DSN

### ISSUE THREAD

**Issue by Krande** [edgedb/edgedb#4252]
Hey, I am having some issues with reaching my Azure deployment using anything but the CLI linking. 

- EdgeDB Version: 2.1
- OS Version: Windows 10
- python package 0.24.0
- CLI version 2.1.0-dev.831+55a6e2b`

I have recently deployed EdgeDB on Azure. I  seem to be able to link with the instance just fine and run client queries based on that already linked instance like this:

```python
import edgedb


client = edgedb.create_client("azure")
res = client.query("select 3+2")
print(res)
```

However, when trying to connect using the `EDGEDB_DSN` environment variable (or passing the dsn string directly into the client) from either locally or a docker container I keep getting this error 

`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)`

Container log is this:

```
---- Exception occurred: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:997) ----

1. ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:997)

---- Traceback ----

    edb/server/protocol/protocol.pyx, line 350, in _start_tls
        
    uvloop/loop.pyx, line 1624, in start_tls
        
    uvloop/loop.pyx, line 1617, in uvloop.loop.Loop.start_tls
        
    uvloop/sslproto.pyx, line 517, in uvloop.loop.SSLProtocol._on_handshake_complete
        
    uvloop/sslproto.pyx, line 499, in uvloop.loop.SSLProtocol._do_handshake
        
    /usr/lib/x86_64-linux-gnu/edgedb-server-2/lib/python3.10/ssl.py, line 975, in do_handshake
        > self._sslobj.do_handshake()

ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:997)
ERROR 19 2022-08-11T11:49:31.234 asyncio: Task exception was never retrieved
future: <Task finished name='Task-111' coro=<<coroutine without __name__>()> exception=SSLError(1, '[SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:997)')>
```

When running this:

```python
import edgedb


client = edgedb.create_client()
res = client.query("select 3+2")
print(res)
```

If I use the `tls_security="insecure"` flag then I get a different error: 

`edgedb.errors.AuthenticationError: authentication failed`

Any help is much appreciated!

**Comment by elprans** [comment]
Linking with CLI effectively records the TLS certificate and the _password_ of the remote instance.  If you want to connect without linking, you can specify these in the environment (`EDGEDB_PASSWORD` and `EDGEDB_TLS_CA`).  More info here: https://www.edgedb.com/docs/reference/connection#ref-reference-connection

**Comment by Krande** [comment]
Thanks for the quick response! 

Hm, I seem to have tried all possible combinations of env vars (including the ones you suggested), but so far I haven't found the correct combination :(

I suspect my issues are related to https://github.com/edgedb/edgedb/issues/4239.

The reoccurring error message is:

`edgedb.errors.ClientConnectionFailedError: no start line: cadata does not contain a certificate (_ssl.c:3989)`


I have tried different representations of my certificate string in my `EDGEDB_TLS_CA` env variable formatting:

```
# Using spaces
-----BEGIN CERTIFICATE----- <CERT STR...==> -----END CERTIFICATE-----
# Using newlines
-----BEGIN CERTIFICATE-----\n<CERT STR...==>\n-----END CERTIFICATE-----
```

But they all end with the error message reported in the text above.

FYI: I pass env variables to my local development docker container using `docker run .. --env-file .env`. 

In addition to specifying the env variables in the .env file I have also tried to set the env variables directly into my Dockerfile, but with no further success. 

If there is any further information I can provide to make debugging this easier, please let me know!

**Comment by elprans** [comment]
You can put the certificate into a file and then specify the path to that file with `EDGEDB_TLS_CA_FILE` (most environment variables support the `_FILE` variant).

**Comment by Krande** [comment]
Success! I could have sworn I had tried using the _FILE in one of my attempts with different env variable combos. But at the very least I can confirm it works on Azure :)

Thanks a lot for the swift response! 

Have a nice weekend!
