### ISSUE TITLE
Duplicated item on select if two select policies exists

### ISSUE THREAD

**Issue by lu-zen** [edgedb/edgedb#4258]
- EdgeDB Version: 
    EdgeDB CLI 2.0.4+c7a8cb4
    EgdeDB 2.1+c73716f
- OS Version: linux lts

Steps to Reproduce:
1. Create two users, and 1 post with one of the user as .author;
2. set global current_user_id with the author user id;
3. update the post .reviewer with the second user;
4. select the Post.

The select will return the same object twice.
It doesn't occurs if the select policy expressions are unified or only the `.author` is defined;

Schema:
[example schema](https://github.com/lu-zen/edgedb-duplicated-select)

**Comment by msullivan** [comment]
Fascinatingly, it seems that access policies are actually a red herring here, and it is a bug in computed globals. If we have two `User`s, and do:
```
select (detached global current_user, global current_user);
```
we get back two results! The second global reference is somehow becoming just a `User` reference.
