### ISSUE TITLE
incorporate changes from cpython TaskGroup into edb.common.TaskGroup

### ISSUE THREAD

**Issue by graingert** [edgedb/edgedb#4266]
currently the cpython taskgroup behaves differently to the edb.common.TaskGroup. These differences should be resolved.

see also https://discord.com/channels/841451783728529451/1007824214641881088/1008791006671556688

**Comment by graingert** [comment]
Some specific differences include an "uncancel() stack", changing when uncancel is called, and how "side errors" are handled

**Comment by 1st1** [comment]
We'll be switching to 3.11 and dropping our `taskgroup.py`. I don't think there will be any extra work associated with that.
