### ISSUE TITLE
InternalServerError when trying to create an exclusive constraint at base type

### ISSUE THREAD

**Issue by fikisipi** [edgedb/edgedb#4268]
- EdgeDB Version: 2.1+52c90a7 (repl 2.1.0-dev.837+77d7d80)
- OS Version: Mac m1 Kernel Version 21.6.0

Run this: 
```sql
CREATE MIGRATION m1tnwlplgljiafydd3xfu7ks7syxrmp6pwyzigtxv3n4ssseibzfla
    ONTO initial
{
  CREATE TYPE default::MenuItem {
      CREATE MULTI LINK children -> default::MenuItem;
      CREATE REQUIRED PROPERTY name -> std::str;
      CREATE PROPERTY page -> std::str;
  };
  CREATE TYPE default::Menu {
      CREATE CONSTRAINT std::exclusive;
      CREATE REQUIRED LINK item -> default::MenuItem;
  };
};
```

Output:
```bash
Error: InternalServerError: syntax error at or near "."
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
```

**Comment by elprans** [comment]
Oh. `exclusive`, when defined on a `type` requires an expression, e.g. `exclusive on (.foo)`.

**Comment by elprans** [comment]
The confusing ISE is a bug, of course.

**Comment by fikisipi** [comment]
> Oh. exclusive, when defined on a type requires an expression

That's not what the migration generator thinks.

**Comment by elprans** [comment]
> I didn't generate the migration, EdgeDB gladly liked my `.esdl` and created that blob above.

That's the bug I was referring to.  Your schema should have been rejected.
