### ISSUE TITLE
Migration error without context of the source

### ISSUE THREAD

**Issue by fantix** [edgedb/edgedb#4270]
- EdgeDB Version: 2.1+52c90a7

The following schemas are generating contextless errors, which are uneasy to address the issue in `.esdl` files when they are big.

1. Querying polymorphic computables mentioned in #2536:

   ```
   module default {
       type A {
           property p := <int32>42;
           link c -> C;
       }

       type B {
           property p := <str>'42';
           link c -> C;
       }

       type C {
           multi link a := .<c[is A];
       }
   }
   ```

   ```console
   $ edgedb migration create
   edgedb error: SchemaError: it is illegal to create a type union that causes a computed property 'p' to mix with other versions of the same property 'p'
   edgedb error: cannot proceed until .esdl files are fixed
   ```

   > illegal to create a type union

   Which type union? `C.<c` is never mentioned in the error, or pointed out.

2. Index on access-controlled links complains about globals:

   ```
   module default {
       global current_user_id -> uuid;

       type User {
           access policy self_only
               allow all using ((.id = global current_user_id) ?? true);
       }

       type Post {
           link user -> User;
           property created_at -> datetime;
           index on ((.user, .created_at));
       }
   }
   ```

   ```console
   $ edgedb migration create
   edgedb error: SchemaDefinitionError: global variables cannot be referenced from index
   edgedb error: cannot proceed until .esdl files are fixed
   ```

   Which global variables and which index? When the schema file is large, it's hard to find out.

**Comment by fknop** [comment]
Same issue here, did you fin a solution?

**Comment by msullivan** [comment]
The index part of this issue is also just a bug, I think. I think we should disable compiling access policies when doing indexes, like we did for constraints in #4245

**Comment by dnwpark** [comment]
Fixed in other issues.
