### ISSUE TITLE
Add support for triggers

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#4272]
This has been briefly discussed in edgedb/rfcs#50, which has been reworked and split into edgedb/rfcs#54.  The second part of query rewrite is action triggers, i.e the ability to specify an expression that is executed whenever in addition to a mutation statement.

**Comment by msullivan** [comment]
This has split into https://github.com/edgedb/edgedb/issues/4936 and https://github.com/edgedb/edgedb/issues/4937
