### ISSUE TITLE
Add `to_bytes` converter function.

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#4281]
Currently `bytes` are hard to work with because they can't be cast into any other type (except `json`), nor can other types be cast into `bytes`. So this type becomes a kind of opaque blob that is basically good for storing some raw data, but not for much else.

We can introduce converter functions that take "encoding" as the second argument and then we could find more uses for the `bytes` type.

We can have the `str`/`bytes` converters:
```
function to_bytes(val: str, encoding: str) -> bytes
function to_str(val: bytes, encoding: str) -> str
```
We can also have `int16`/`int32`/`int64`/`bytes` converters:
```
function to_bytes(val: int16, little_endian: bool = true) -> bytes
function to_bytes(val: int32, little_endian: bool = true) -> bytes
function to_bytes(val: int64, little_endian: bool = true) -> bytes
function to_bytes(val: bytes, little_endian: bool = true) -> int16
function to_bytes(val: bytes, little_endian: bool = true) -> int32
function to_bytes(val: bytes, little_endian: bool = true) -> int64
```

**Comment by tailhook** [comment]
I'm not sure why `little_endian = true` is the default. I would say that network byte order should be default. As it's more common in storage and data transmission.

I would also prefer enum instead of boolean flag, but that is probably too slow.

Also what are the downsides of using `utf-8` encoding by default?

**Comment by 1st1** [comment]
> I would say that network byte order should be default.

+1

**Comment by 1st1** [comment]
> Also what are the downsides of using utf-8 encoding by default?

None, I also think this is what we should do.

**Comment by elprans** [comment]
int -> bytes converters have dubious value IMO.  I added the `to_str` / `to_bytes` in #5960.
