### ISSUE TITLE
Document `globals` argument for HTTP/GraphQL protocols

### ISSUE THREAD

**Issue by fritzblue** [edgedb/edgedb#4314]
What is the best way to specify globals in graphql?

In other words, if a resource has a specific access policy, what is the best way to indicate "session data" like the current user ID when interfacing with edgedb over the graphql interface?

**Comment by msullivan** [comment]
You can pass a `globals` argument to the endpoint, similar to `variables`.
The keys should be fully qualified, like `"default::global_var"`.

This ought to be documented, of course.

**Comment by MiroslavPetrik** [comment]
@fritzblue does global even work with your GQL client?

I have added 2 globals `currentUserId` (scalar) and `currentUser` (query).

With the current extension, when I visit `http://localhost:10704/db/edgedb/graphql/explore`
I get the following error:

```
{
  "errors": [
    {
      "message": "TypeError: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but 'Filterdefault|currentUser@default|currentUser@global' does not.\n\nNames must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but 'default|currentUser@default|currentUser@global' does not.\n\nNames must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but 'default|currentUser@default|currentUser@global' does not.\n\nNames must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but 'Orderdefault|currentUser@default|currentUser@global' does not.\n\nNames must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but 'delete_default|currentUser@default|currentUser@global' does not."
    }
  ]
}
```

**Comment by fritzblue** [comment]
@MiroslavPetrik I'm seeing this issue as well (cc @msullivan)

**Comment by sirkonst** [comment]
I've also faced with it because it is not documented.
