### ISSUE TITLE
Can't delete objects via REPL: InternalServerError: relation "..." does not exists

### ISSUE THREAD

**Issue by mperezous-sigillum** [edgedb/edgedb#4320]
- EdgeDB Version: EdgeDB CLI 2.0.4+a7fc49b, server is 1.4 Docker image on GCP
- OS Version: masOS Monterey 12.4

I added an endpoint to my new FastAPI application - one which connects to an EdgeDB instance previously accessed from my JavaScript app. It simply collects form data and creates a new `Merchant`, but as you can see by the below I'm unable to delete the created `Merchant`s from the REPL after.

```
dev> select Merchant { name, merchant_id, logo_url, emails, wallets, locations, website, business_types, main_contact_index } filter .name = "Michael";
{
  default::Merchant {
    name: 'Michael',
    merchant_id: '34550715062af006ac4fab288de67ecb44793c3a05c475227241535f6ef7a81b',
    logo_url: '',
    emails: ['test@test.com'],
    wallets: ['2umBR0hVvii7XbwL6RYmwJfmvj9dpv5LNE3hDYHqQ7LMjVxJZi0bkJ7CqXkuDKeiKWz2K7flpBLi01ln'],
    locations: ['Here, TH'],
    website: {},
    business_types: ['{business_type}'],
    main_contact_index: 0,
  },
}
dev> delete Merchant filter .name = "Michael";
edgedb error: InternalServerError: relation "edgedbpub.e63d2cdc-1e65-11ed-8843-43d0592a625a_t" does not exist
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: relation "edgedbpub.e63d2cdc-1e65-11ed-8843-43d0592a625a_t" does not exist
dev> delete Merchant filter .merchant_id = "34550715062af006ac4fab288de67ecb44793c3a05c475227241535f6ef7a81b";
edgedb error: InternalServerError: relation "edgedbpub.e63d2cdc-1e65-11ed-8843-43d0592a625a_t" does not exist
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: relation "edgedbpub.e63d2cdc-1e65-11ed-8843-43d0592a625a_t" does not exist
```

Steps to Reproduce:

1. I simply added a new endpoint to my application to create a Merchant object, e.g. `insert Merchant { name := "Michael", merchant_id := "...", ... }`
2. Attempt to delete the merchant based on either the `name` or `merchant_id` fields (secondary, primary key analogs respectively).

Schema:
[dbschema.zip](https://github.com/edgedb/edgedb/files/9501009/dbschema.zip)

**Comment by msullivan** [comment]
This bug can be reproduced with the schema:
```
module default {                                                         
    type M;                                                              
    abstract type Base { link l -> M };                                  
    type A extending Base;                                               
    type B extending Base;                                               
    type L { link l -> A | B };                                          
} 
```
and doing `insert M; delete M;`

The problem is that we are including the type `A | B` in the triggers!

**Comment by msullivan** [comment]
There's another nasty issue here which is that the migration scripts won't apply on 2.x, because of the `insert` in a default. See https://github.com/edgedb/edgedb/issues/3592#issuecomment-1239797739.

I discuss some of the issues involved there in https://github.com/edgedb/edgedb/issues/4330

**Comment by mperezous-sigillum** [comment]
Ouch.... that one might hurt come upgrade time. I'll hold off on upgrading, then - is #4329 (above) only available in 2.x?
