### ISSUE TITLE
Convert Postgres errors to EdgeDB errors

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#433]
```
db> SELECT to_naive_date('2000    JUN', 'FXYYYY MON');
InternalServerError: invalid value "   " for "MON"
```

Fix `errmech.py` to recognize Postgres' error and convert it to a proper EdgeDB error.

**Comment by vpetrovykh** [comment]
Another thing that we need is to replace references to Postgres types with EdgeDB types in error messages. E.g. "cannot index json object by bigint" -> "cannot index json object by int64", etc.

**Comment by 1st1** [comment]
Anything left to do here, @vpetrovykh?

**Comment by elprans** [comment]
Closing this as too broad. Specific leftovers will get done in granular issues.
