### ISSUE TITLE
Property update in EdgeDB UI -> InternalServerError: "cannot find ptrref matching typeref .."

### ISSUE THREAD

**Issue by Krande** [edgedb/edgedb#4333]
## EdgeDB installation

- EdgeDB Version: 2.1
- OS Version: Ubuntu 20.04.4 LTS
- The EdgeDB instance is based on the "bare metal installation" procedure in the docs and is installed on a VM in Azure.

## Schema
- [My Schema](https://github.com/Krande/ifcdb/blob/22639fd19327a312d53f1cced8aa7773bd5cb603/src/server/schema/mixed/dbschema/default.esdl)

## Problem

When running the following query using Edgedb UI on an EdgeDB v2.1 instance running on ubuntu VM:

```
with
    obj1 := (select IfcBuildingElementProxy FILTER .GlobalId=<str>'3vJeEVZYzA3vP81uCmY9l4'),
    obj2 := (select array_agg(obj1.Representation.Representations)[0][is IfcShapeRepresentation]),
    obj3 := (select array_agg(obj2.Items)[0][is IfcExtrudedAreaSolid])

UPDATE obj3
SET {
    Depth := 11.3781298010066
}
```

I receive the following error

```
InternalServerError: cannot find ptrref matching typeref e4b022c7-2f70-11ed-b079-b3aa5757e1a2
```
FYI: When I re-run the exact same query the typeref keeps changing.

I am certain that the objects in question exists given that it works just fine when I try to change nested linked properties of this object like so:

```
with
    obj1 := (select IfcBuildingElementProxy FILTER .GlobalId=<str>'3vJeEVZYzA3vP81uCmY9l4'),
    obj2 := (select array_agg(obj1.Representation.Representations)[0][is IfcShapeRepresentation]),
    obj3 := (select array_agg(obj2.Items)[0][is IfcExtrudedAreaSolid]),

SELECT {
    update1 := (
        with
            lvl3 := (select obj3.Position.Location),
        UPDATE lvl3
        SET {
            Coordinates := [.Coordinates[0], .Coordinates[1], -5.68906497955322]
        }
    ),
    update2 := (
        with
            lvl3 := (select obj3.Position.RefDirection),
        UPDATE lvl3
        SET {
            DirectionRatios := [-1.0, .DirectionRatios[1], .DirectionRatios[2]]
        }
    )
}
```
which returns 

```json
[
  {
    "update1": {
      "id": "6c9893b1-2ac3-11ed-b002-3b8ce12b219e"
    },
    "update2": {
      "id": "6c9893af-2ac3-11ed-b002-0f7d4644546b"
    }
  }
]
```
Let me know if there is anything else you need from my in order to advance this issue and I'll happily supply it :)

Best Regards
Kristoffer

UPDATE: 

Hm, I just tried the exact same query that was failing in EdgeDB UI using my python client and it works fine. 

```
res = client.query_json(edql_str)
```
and it successfully returns 

```json
[
  {
    "id": "6dee380b-2ac3-11ed-b002-1b0c12bc1491"
  }
]
```

Maybe it's just a EdgeDB UI error?

**Comment by msullivan** [comment]
As a tip, you're probably better off doing `(select obj2.Items limit 1)` instead of `array_agg(obj2.Items)[0]`. Skips the need to actually create an array.
(And coincidentally I think works around the bug here.)

**Comment by Krande** [comment]
Okay, thanks for the tip! 

So I changed it to this:

```
with
    obj1 := (select IfcBuildingElementProxy FILTER .GlobalId=<str>'3vJeEVZYzA3vP81uCmY9l4'),
    obj2 := (select (select obj1.Representation.Representations limit 1)[is IfcShapeRepresentation]),
    obj3 := (select (select obj2.Items limit 1)[is IfcExtrudedAreaSolid]),

SELECT {
    update3 := (
        UPDATE obj3
        SET {
            Depth := 11.3781298010066
        }
    )
}
```

I am still seeing the same error, but I guess this is more performant once I try to scale this up?
