### ISSUE TITLE
Migration wrongly states dropping an abstract type property will cause dependency problem in its concrete type

### ISSUE THREAD

**Issue by avedetvedea** [edgedb/edgedb#4345]
```
abstract type Schedule extending Node {
    required property name -> str;
    # required link owner -> Athlete | Team; # ---> dropped
    required multi link sessions -> Session;
}
type AthleteSchedule extending Schedule {
    required link owner -> Athlete;
}
type TeamSchedule extending Schedule {
    required link owner -> Team;
    multi link subscribedAthletes := TeamSchedule.<teamSchedule[IS Athlete];
}

```

The error states: Athlete type's link 'schedules' is dependent on the dropped field.

Athlete has the following link:
`multi link schedules := Athlete.<owner[IS AthleteSchedule]; # 1-to-n (backlink)`
As seen, the owner is from the AthleteSchedule, and not the Schedule.

Also, I couldn't get the abstract type work with Athlete | Team, and then have concrete types have owner fields as Athlete and Team respectively. Any help in that direction would also be appreciated.

**Comment by msullivan** [comment]
I think this was fixed by #4345?
