### ISSUE TITLE
Does the edgedb postgres driver work with upstream postgres?

### ISSUE THREAD

**Issue by pwtail** [edgedb/edgedb#4368]
As I see, edgedb doesn't use asyncpg. I suppose that it uses something better. Does it's driver work with upstream postgresql?

Does that mean we should use the driver from edgedb instead of asyncpg?

**Comment by 1st1** [comment]
EdgeDB does work with vanilla Ppostgres, and yes, it's correct that it's using something "better" than asyncpg, but it's better only in a sense that our Postgres bridge is hand coded specifically for the EdgeDB needs and it makes pretty much no sense to use it outside of the EdgeDB project.

**Comment by pwtail** [comment]
Thank you!
