### ISSUE TITLE
Removing `required` constraint on link fails to create migration

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb#4371]
- EdgeDB Version: EdgeDB CLI 2.0.5+53f9c9b, EdgeDB 2.1+9c4bc9f
- OS Version: macOS 12.6

(Follow up from [discord](https://discord.com/channels/841451783728529451/841451783728529454/1020400707406405783))

Steps to Reproduce:

1. Drop a `required` constraint on a link, making it optional.

```
-        required link subject -> SignalSubject;
+        link subject -> SignalSubject;
```

```
$  edgedb migration create
did you make link 'subject' of object type 'default::Signal' optional? [y,n,l,c,b,s,q,?]
> l
The following DDL statements will be applied:
    ALTER TYPE default::Signal {
        ALTER LINK subject {
            RESET OPTIONALITY;
        };
    };
did you make link 'subject' of object type 'default::Signal' optional? [y,n,l,c,b,s,q,?]
> y
edgedb error: EdgeDB could not resolve migration with the provided answers. Please retry with different answers.
```

Schema:

**Comment by jackfischer** [comment]
This appears more complicated than the above; just made the same change on another `required link` successfully:

```
  ALTER TYPE default::StrategyNode {
      ALTER LINK documentVersion {
          RESET OPTIONALITY;
      };
  };
 ```

**Comment by msullivan** [comment]
I was unable to reproduce this issue while doing the obvious thing, so there must be something more subtle going on that is triggering this for you.
Do you have a more complete example of a schema where it is failing? Are there a lot of migrations that have been run already?

**Comment by jackfischer** [comment]
Attempted to reproduce more cleanly [here](https://github.com/jackfischer/edgedb-4371).

Unfortunately my theory it was due to `SignalSubject` being abstract is wrong
https://github.com/jackfischer/edgedb-4371/commit/4bee1e78aa04edb46e1caa56ca9605ca5d5b7481

**Comment by jackfischer** [comment]
Found it!!

Making the following change to remove the computed backlink for this relationship allowed the removal of `required`. 

```
   abstract type SignalSubject {
-        multi link signals := .<subject[is Signal];
+        # multi link signals := .<subject[is Signal];
     }
```

**Comment by msullivan** [comment]
Great! Do you have a small reproducing case you can share, then?

**Comment by jackfischer** [comment]
Yup live here - https://github.com/jackfischer/edgedb-4371, `default.esdl` is edited so it's ready for the failing `edgedb migration create`.
