### ISSUE TITLE
BackendUnavailableError when trying to connect to Fly.io EdgeDB instance

### ISSUE THREAD

**Issue by vonkoff** [edgedb/edgedb#4389]
- EdgeDB Version: EdgeDB CLI 2.0.5+53f9c9b
- OS Version: Mac OS & Amazon Linux 2 

Steps to Reproduce:

1. Try to connect to EdgeDB instance setup on Fly.io, that worked successfully a while before. Nothing has changed since then. 
2. Put in the command
```
edgedb instance link \
  --trust-tls-cert \
  --dsn $DSN \
  --non-interactive \
  fly
```
with the proper DSN variable. It tries to connect and spits out the following error. 
```
edgedb error: BackendUnavailableError: cannot fetch database version: Postgres is not available: Connection is lost, please check server log for the reason.
  Server traceback:
      Traceback (most recent call last):
        File "edb/server/protocol/binary.pyx", line 1364, in edb.server.protocol.binary.EdgeConnection.main
        File "edb/server/protocol/binary.pyx", line 1270, in execute
        File "edb/server/protocol/binary.pyx", line 1073, in _execute
        File "edb/server/protocol/binary.pyx", line 258, in get_pgcon
        File "edb/server/protocol/binary.pyx", line 252, in edb.server.protocol.binary.EdgeConnection.get_pgcon
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-2/lib/python3.10/site-packages/edb/server/server.py", line 552, in acquire_pgcon
          raise errors.BackendUnavailableError(
      edb.errors.BackendUnavailableError: Postgres is not available: Connection is lost, please check server log for the reason.
```

Running `fly checks list -a` for both the fly.io EdgeDB app and postgres app attached to it. All checkmarks are there meaning it should be good to go. 

Not sure what the issue is and how to fix it.

**Comment by elprans** [comment]
Is the Postgres instance sufficiently sized?  Their smallest instance is too small to fit EdgeDB currently.

**Comment by vonkoff** [comment]
@elprans No volume is being used. Only setup the schema and never sent any data in. It is set to 10GB as per the installation instructions on EdgeDB documentation.

**Comment by elprans** [comment]
@vonkoff I meant the size of the Postgres VM, should be at least `dedicated-cpu-1x`

**Comment by vonkoff** [comment]
@elprans That fixed it. Might be good to update the Fly.io documentation to mention setting the size to `dedicated-cpu-1x`

**Comment by elprans** [comment]
The docs already say so: https://www.edgedb.com/docs/guides/deployment/fly_io#create-a-postgresql-cluster
