### ISSUE TITLE
Add set intersection and difference operators

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#4392]
The hardest part of this is probably figuring out syntax/naming, since we probably don't want to add any reserved keywords.

We can use either symbol operators `&` and `\` or just function names.

```
select set_intersection({1,2,3}, {2,3,4}} == {2,3}
select set_difference({1,2,3}, {2,3,4}} == {1}
```
the implementation can be defined straightforwardly in terms of select:
```
set_intersection(X, Y) = select x := X filter x in (select Y)
set_difference(X, Y) = select x := X filter x not in (select Y)
```

**Comment by msullivan** [comment]
Right, but do we want to create a compatibility hazard by adding new reserved keywords?

**Comment by elprans** [comment]
Good point.

**Comment by vpetrovykh** [comment]
So when you say that the multiplicity is no longer an issue, what exactly do you mean?

What's the result of: `set_difference({1, 1, 1}, {1})`?
What's the result of: `set_intersection({1, 1, 1}, {1, 1})`?

Typically, the intersection of two multisets A and B, is a multiset such that the multiplicity of an element is the minimum of the multiplicity of an element in A and B. Are we going to be able to preserve that?

**Comment by vpetrovykh** [comment]
Both of the above `filter` based definitions will mess up the multiplicity that you'd expect from a multiset. And intersections would not be commutative (`select A filter A in B` is generally not the same as `select B filter B in A`), but most intuitive notions of "intersection" are supposed to be commutative.

**Comment by elprans** [comment]
SQL supports commutative multiset semantics on `intersect` and `except` (via the `all`) modifier, so there's no problem here.

Also, per discussion with @vpetrovykh, we should look into the possibility of reducing the reserved keyword impact (e.g. allow them in DDL and paths without quoting).
