### ISSUE TITLE
Ensure that array arguments are 1-indexed and 1 dimentional

### ISSUE THREAD

**Issue by aljazerzen** [edgedb/edgedb#4405]
Postgres supports arbitrary array indexes:
```
SELECT '[5:10]={1,2,3,4,5,6}'::int[] -- array that starts indexing at 5
```
... but they default to being 1-indexed. Our compiler and stdlib assume that all arrays are 1-indexed, which is almost true: we never construct non-1-index array, but one may be passed as query argument.

This is probably the indexing offset: https://github.com/edgedb/edgedb-python/blob/master/edgedb/protocol/codecs/array.pyx#L82

> It should actually be pretty easy to add a check for this in the server's protocol handling code, because we already have code for doing special handling of array parameters. Postgres's encoding of arrays requires including the internal type ID of the element; we didn't want to make our clients need to understand that, so we have to handle it in our server: https://github.com/edgedb/edgedb/blob/a8633eb9d19e8696b0f04fce86a49435ac7124d0/edb/server/protocol/args_ser.pyx#L169-L177

> So that gives a pretty natural place to also check the dimensions and flags.

**Comment by msullivan** [comment]
I think there is also an issue where a parameter could be passed that contains a NULL inside the array, which could cause us grief.

**Comment by msullivan** [comment]
Oh, argh, and the python binding will happily encode None in an array as null, too!
