### ISSUE TITLE
Support pre-commit and CI

### ISSUE THREAD

**Issue by i0bs** [edgedb/edgedb#4408]
I'm a really big fan of pre-commit. It's saved me a lot of time and hassle getting several tools to work together nicely in my Python projects. I couldn't help but notice Its not used here despite some tools, such as `.flake8` for style guide enforcement being present.

I can't think of a good way to provide an example for how I wish this feature to be implemented: after all, the idea is that this all happens right before you can commit code. An offending line or violation of the tools' policies will result in immediately halting the commit process. Instead, I've listed some bullet points for why I think it may be worth considering:
- [Its natively faster than using GitHub CI workflows](https://github.com/pre-commit-ci-demo/demo#results).
- [Numerous hooks can be created](https://pre-commit.com/#creating-new-hooks) to represent GitHub actions.
- Some actions, such as unit testing, could be automated through pre-commit.ci on condition of [`autoupdate_branch`](https://pre-commit.ci/#configuration-autoupdate_branch).

There's also some reasons why it may not be good:
- We already have GitHub actions or commands to execute these tasks.
- Unit testing could diminish rapid iteration commits on a branch or Pull Request.
- There's no problem to warrant the need of integrating this.

Overall, I believe pre-commit could greatly benefit the project with development and make it nicer for both internal and OSS developers to work with. There may also be plenty of other reasons to not consider this which is valid. Please feel free to share your thoughts! 😃

**Comment by 1st1** [comment]
I'm not a big fan of using such hooks as they can get pretty annoying when you just develop locally and make WIP commits all the time.

**Comment by msullivan** [comment]
Yeah, running commit hooks on every `git commit` definitely does not match my workflow.

I always use `hub pull-request` to create PRs, and wouldn't mind pre-commit hooks *there*. Not sure if that is how other people develop, though.
