### ISSUE TITLE
Document path factoring behavior

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#4441]
In EdgeQL, common paths are "factored" to the closest surrounding subquery.

This is what allows
```
select User.first_name ++ ' ' ++ User.last_name
```
to return one row per user, as well as causing
```
select (User.name, count(User))
```
to always report `1` as the count, as well as letting
```
select (User.name, count(User.friends))
```
return each user's number of friends.

I don't believe that this is currently documented anywhere but https://www.edgedb.com/docs/reference/edgeql/eval, which does not explain it at all, it just shows how to define it.

**Comment by vpetrovykh** [comment]
The PR #4959 (mentioned above) adds a section on path resolution to the docs.
