### ISSUE TITLE
Setting enforce_access_policies to false doesn't work inside functions

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#4461]
Functions are precompiled, so setting enforce_access_policies to false doesn't affect their behavior at all.

Fixing this is not too hard: functions already take an extra json argument that encodes global variables, and we can just put the value of enforce_access_policies in it, and check that when evaluating access policies inside the function

**Comment by zerosym** [comment]
I was wondering if this flag to ignore access policies for a particular function will be exposed for schema use too.  I've been wanting to extract portions of my access policies into functions but this is complicated or made impossible by the functions themselves respecting access policies.  

A contrived example:
```
function complex_check(obj: A) -> bool {
    using (...);
}

type A {
    link parent -> A;
    link sibling -> A;

    access policy complicated_policy
        allow all using (
            complex_check(.parent) and complex_check(.sibling);
        );
}
```

Is there some way to achieve the above or am I missing an easier option?

**Comment by msullivan** [comment]
@zerosym that's a good point. I'll think about it.

One simple option might be for us to expose the "current function" as a built-in global, and then you can use that in policies to "bless" certain functions. We'd probably want to do a bit of special casing to optimize, maybe?
I don't know.

I now realize though that using functions in insert/update constraints is perilous: newly inserted/updated data is not visible to functions.
