### ISSUE TITLE
Reference properties in a default Schema value

### ISSUE THREAD

**Issue by avedetvedea** [edgedb/edgedb#4473]
Current error message goes: `edgedb error: QueryError: could not resolve partial path`. I had to dig in multiple places (as always) and found a similar topic in Discord, which was not reported as a limitation in docs, and still is not AFAI searched the docs. 

Discord have a lot of conversation where limitations of certain things are well known especially by @elprans and @colinhacks, but they kindly move around in Discord as walking encyclopedias of EdgeDB but AFAI experienced often do not report them on docs.

**Comment by msullivan** [comment]
To make it precise, this issue here is that if we do something like
```
create type Foo { create property x -> str; create property y -> str { set default := .x }; };
```
we get that partial path error message. (Which should be improved in general!)
We should explain that we don't support referring to other properties in a default.

**Comment by msullivan** [comment]
Or actually we could just implement referring to other properties in a default.

**Comment by IgnisDa** [comment]
Any workarounds for this?
