### ISSUE TITLE
`InternalServerError: None` when query has multiple `delete`s in `with` clause

### ISSUE THREAD

**Issue by avedetvedea** [edgedb/edgedb#4475]
If one wants to delete multiple records, the error just states **None** in red. Then when trying to delete all records one by one, one is able to see the real error, like prohibited by link target policy etc. 

Interesting thing is, even if you try to delete 2 records which are non-deletable (i.e., they will indeed give you any error, unlike the first description where deletable and non-deletable were mixed), the **None** still appears and you aren't informed. Moreover, those two instances in my case are non-deletable because of the exact same reason (they only differ by some uuid in the error message, naturally), which still results in **None** error message. So I guess any number of messages that are different in content result in non-informative **None**.

**Comment by jaclarke** [comment]
This seems to be an error in edgedb itself; the full error message is: `InternalServerError: None`.

The query the UI generates is this:
```
with
delete1 := assert_exists((delete default::Example filter .id = <uuid>'...'), message := 'delete1 was blocked by access policy'),
delete2 := assert_exists((delete default::Example filter .id = <uuid>'...'), message := 'delete2 was blocked by access policy')
select {
  delete1,
  delete2
}
```
