### ISSUE TITLE
Objects in `cfg` and `sys` are in a somewhat busted state

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#4491]
Most of types in `cfg` and `sys` are represented in the database as views that live in the `edgedbss` schema, and which are created in `metaschema.py`.

However the knowledge that they should live in `edgedbss` is somewhat inconsistent.
Duplicates of each of those types exist in `edgedbstd`, and those are used by `BaseObject`s views.
Some of the abstract types in `cfg`/`sys` have views created explicitly in `metaschema`, but some don't.

`cfg` and `sys` special cased in relctx to point at `edgedbss`.

This should all get rationalized, so that one version of each of these tables exists and is routed to in one place (pgsql/common.py, ideally).

What is the reason why these views are in `edgedbss` instead of just `edgedbstd`? Is this important?

Here are some of the bugs that result from this state:
```
edgedb> select cfg::ConfigObject;
edgedb error: InternalServerError: relation "edgedbss.734bd415-4670-11ed-88a5-6d9ebab1a5f7_t" does not exist
```

```
edgedb> select count(BaseObject[is cfg::AbstractConfig]);
[0]
edgedb> select count(cfg::AbstractConfig);
[3]
```

**Comment by elprans** [comment]
> What is the reason why these views are in `edgedbss` instead of just `edgedbstd`? Is this important?

Mostly historical.  Ideally we should teach system DDL to special-case these and create in `edgedbstd` properly.
