### ISSUE TITLE
Why support Graphql natively?

### ISSUE THREAD

**Issue by ansarizafar** [edgedb/edgedb#450]
EdgeQL is a superset and much more powerful/useful then why support Graphql natively? Anyone can develop a graphql schema in his language of choice.

Yes, Graphql is becoming popular but it has its own set of problems and the majority of companies/developers are still using Rest APIs. 

I am concern that with built-in Graphql support people will consider EdgeDB just like an ORM or an extra layer/library on top of an existing database which generates a graphql schema automatically (like Prisma, graphql-genie, postgraphpeli etc. ) and not a complete database.

EdgeDB should be projected as a new, modern and better database with its own,  much more powerful/useable query language.

@1st1 @elprans Is there any possibility of Alpha/Beta release in near future? Waiting forever for a new beginning.

**Comment by elprans** [comment]
> EdgeQL is a superset and much more powerful/useful then why support Graphql natively?

GraphQL is (and will be) implemented as an extension and will be one of the available protocols for HTTP app ports.  It's not so much "native" as it is "bundled".

The point of EdgeDB is to be *useful* in the context of modern development practices, and that means the ability to align with existing systems and protocols.  GraphQL is just one such protocol, and is a good capability demonstration.

> Anyone can develop a graphql schema in his language of choice.

And we would prefer that choice to be EdgeQL :-)

> I am concern that with built-in Graphql support people will consider EdgeDB just like an ORM

I'm not sure I follow this line of reasoning.

> EdgeDB should be projected as a new, modern and better database with its own, much more powerful/useable query language.

This is exactly the plan.

> Is there any possibility of Alpha/Beta release in near future?

We have landed a ton of critical bits recently, the protocol is stabilizing quickly, and we have a proper Python client, so yes.

**Comment by 1st1** [comment]
Closing this one. The GraphQL implementation is in and it's here to stay for a while.
