### ISSUE TITLE
SQL name resolution

### ISSUE THREAD

**Issue by aljazerzen** [edgedb/edgedb#4540]
For the upcoming SQL support, we essentially need to implement a basic SQL name resolver. We will not support all of the SQL, but we need following features:

(using the Movies schema)
```sql
-- map Movie to our ObjectType
-- map Movie.title to the correct property
SELECT Movie.title FROM Movie;

-- figure out that property title comes from ObjectType Movie
SELECT title FROM Movie;

-- case insentive by default, lowercase when strictly-typed
SELECT tItLe, `relase_year` FROM `movie`;

-- table aliases
SELECT m.title FROM Movie AS m;

-- resolve <link>_id
SELECT title FROM Movie JOIN Genre ON Movie.genre_id = Genre.id

-- resolve <parent_type>_id
SELECT c.title, m.release_year FROM Content c JOIN Movie m ON m.content_id = c.id

-- infer subquery types
SELECT title, t.name FROM (SELECT *, title as name FROM Movie) t JOIN Genre ON ...
```

## Inheritance

We have to decide what to do when selecting from a parent object. Should rows of child tables be included?

@1st1 says no, because SQL is low level and we should expose only this low-level data.

@msullivan says that we should at least provide some syntax to allow access to the inheriting views we already have so the SQL interface is not such a pain in the ass to use.

I think that we should avoid having two different syntaxes (or any kind of table name suffixes), because this adds much more surface for bugs and confusion. 

While it would be convenient to expose inheriting views, the exposed database would not be normalized so I agree with Yury to stick only to base tables.

## Names of multi-multi link tables

```
type Movie {
    multi link actors -> Person {
      property character_name -> str;
    };
}
type Person {
    link filmography := .<actors[is Content];
}
```

These tables do not have a name in EdgeQL, but need one in SQL. I suggest `movie_actors_person_filmography`:
- object name where link is defined,
- link name on that object
- object name where link is referenced,
- link name on that object.

**Comment by msullivan** [comment]
For many-to-many links, I don't think we need to include anything but `Movie` and `actors` in the table name. That fully identifies the link. The `filmography` computed backlink is helpful for writing edgeql queries, but is not fundamental.

So I think it should be named `Movie_actors`, or `"Movie.actors"` if we are willing to require quoting.

**Comment by msullivan** [comment]
I also tend towards thinking that rows of child tables *should* be included by default. We can use the `ONLY` keyword to suppress that.

(Though it might also be worth doing a bit of investigation about any tools we expect to be automatically generating these SQL queries, and what their capabilities are.)

**Comment by msullivan** [comment]
For single links, my inclination is to just name the column the same thing as the link, instead of adding `_id` to the end?

**Comment by elprans** [comment]
> We have to decide what to do when selecting from a parent object. Should rows of child tables be included?

We should compile references to inheritance views, and also support the `ONLY` postfix, in which case a direct reference to an underlying table should be generated.

**Comment by elprans** [comment]
Yeah, I'd avoid adding suffixes and prefixes to names unless absolutely necessary.

**Comment by msullivan** [comment]
Also, regardless of whether we include subtypes, we don't need the `-- resolve <parent_type>_id` thing. All of our tables *include* all the properties from parent types

**Comment by aljazerzen** [comment]
@msullivan 
> Also, regardless of whether we include subtypes, we don't need the -- resolve <parent_type>_id thing. All of our tables include all the properties from parent types

If we decide to include subtypes, you may want to select all Content but to also have properties from Movies (for those objects that are a Movie). You can't do that with UNION, because rows would be duplicated and columns would not match.

If we decide not to include subtypes, you also need a way to get all Content subtypes instances.

The more I think about it, the more I lean toward exposing the normalized database. No inheritance, no showing the same values in two different tables.

This will also inflict the appreciation for all the work EdgeDB is doing over the low-level SQL database.

---

> For many-to-many links ...

Ok, agree `Movie_actors` is probably best.

**Comment by msullivan** [comment]
Like we discussed offline, we need to duplicate pointers from parent objects in the children type--that is how we store it in edgedb, with each object in one table.

Implementation work doesn't need to wait on a final decision on inheritance; it shouldn't be hard to change
