### ISSUE TITLE
EdgeDB windows without powershell

### ISSUE THREAD

**Issue by ccsv** [edgedb/edgedb#4586]
Is there any way to run EdgeDB CLI on windows without powershell? Like directly on cmd?

**Comment by PastelStoic** [comment]
A shell of some kind is required to use a CLI. Both classic command prompt and Powershell will function.

**Comment by elprans** [comment]
You can download the CLI from this URL directly: https://packages.edgedb.com/dist/x86_64-pc-windows-msvc/edgedb-cli.exe

Then, open `cmd`, change the directory to where you downloaded the executable and run:

```
edgedb-cli.exe _self_install
```

**Comment by MiroslavPetrik** [comment]
I'm using the Git bash. Works like a charm.

![image](https://user-images.githubusercontent.com/38855190/198557812-1abf30a9-2661-45d2-b4dc-bb190d14f454.png)

**Comment by ccsv** [comment]
> You can download the CLI from this URL directly: https://packages.edgedb.com/dist/x86_64-pc-windows-msvc/edgedb-cli.exe
> 
> Then, open `cmd`, change the directory to where you downloaded the executable and run:
> 
> ```
> edgedb-cli.exe _self_install
> ```

Yep this is the solution I was looking for. Might be a good idea to put it in the docs. It is a lot cleaner than downloading and installing powershell when it does not come with windows

**Comment by elprans** [comment]
@raddevon, let's find a way to document manual installation of the CLI.
