### ISSUE TITLE
Database triggers to handle referenced objects when deleted

### ISSUE THREAD

**Issue by ccsv** [edgedb/edgedb#4594]
I know that triggers are pretty new but what do you do when you need to delete objects that have referenced link to them when deleted?

If you have lots of reference links it might be difficult to write a couple of queries to handle them.

Maybe have some triggers with one of these options on delet:

* set the linked objects to a default value / null
* delete the linked objects and their children so you do not have orphan objects in the database
* throw an error if child objects exist

**Comment by elprans** [comment]
Looks like a job for [link deletion policies](https://www.edgedb.com/docs/datamodel/links#deletion-policies).

**Comment by ccsv** [comment]
@elprans Thanks that is just what I was looking for. But It looks like you can't linked objects to null when deleted.

**Comment by elprans** [comment]
>  But It looks like you can't linked objects to null when deleted.

This is what `on target delete allow` does.

**Comment by msullivan** [comment]
Is there language changes we could make to the documentation that would make some of this clearer?

Otherwise I think we can close this
