### ISSUE TITLE
Consider adding syntax to refer to a link/property default in mutations

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#4595]
SQL has the `DEFAULT` keyword to indicate that the default value is to be used.  This is a useful pattern when a value for property/link is passed via an `optional` argument, e.g something like:

```
insert Obj {
  foo := <optional str>$foo ?? defaultof Obj.foo
}
```

**Comment by msullivan** [comment]
Closed in favor of doing https://github.com/edgedb/edgedb/issues/4803 instead
