### ISSUE TITLE
Directions for building documentation are broken

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#4610]
When I run `make docs`, I get
```
Warning, treated as error:
/home/sully/src/e/edgedb/docs/clients/index.rst:26:toctree contains reference to nonexisting document 'clients/js/index'
```

I think the disconnect here is that the production docbuild is part of the internal website, and so this flow doesn't get used. I think it is probably worth having a dev flow for doc changes, though.

**Comment by 1st1** [comment]
Gonna be fixed by https://github.com/edgedb/edgedb/pull/4615
