### ISSUE TITLE
Consider not actually storing `__type__` in database

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#4637]
`__type__` is fully determined by what table a row comes from. We could populate it in the inheritance views instead of actually storing it in the database.

The space saving could add up and if there is a significant downside, I haven't though of it yet.
(I guess the downside is that it makes `__type__` a hacky special case instead of just a link, though there are already special cased things about it)

**Comment by elprans** [comment]
Yeah, persisting `__type__` was necessary back when we were still using table inheritance, but now shouldn't be necessary. `insert` should also get a tad faster.

**Comment by 1st1** [comment]
> Yeah, persisting __type__ was necessary back when we were still using table inheritance, but now shouldn't be necessary.

Right. Interesting idea.
