### ISSUE TITLE
Documentations on migrating for tutorials

### ISSUE THREAD

**Issue by ccsv** [edgedb/edgedb#4638]
I was looking through the docs and tutorials. The database migration part is missing

For the tutorials it needs to mention somewhere that you need to create and migrate the db schema using
`edgedb migration create` and `edgedb migration apply`

I would be confusing for beginners if they get stuck because of an migration issue.

**Comment by raddevon** [comment]
Here's the page I think you're looking for on migrations in our Getting Started tutorial: https://www.edgedb.com/docs/intro/migrations

The first step covers the initial creation of your schema, creation of the first migration, and the initial migration. The last three steps cover editing your schema, creating a new migration, and applying it.

I'll close this issue for now, but please reopen if this doesn't address your concern.
