### ISSUE TITLE
Add unix socket

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#465]

**Comment by 1st1** [comment]
Implemented in https://github.com/edgedb/edgedb/commit/4b1320b130b940155c4e4c47baa1d8d497a572da

**Comment by merqurio** [comment]
As far as I understand the idea behind implementing UNIX sockets is just to allow inter-process communication and avoid doing some checks and operations (like routing) right ?

I guess that if edgedb and the client are in the same node this make sense ?
Thanks @1st1 !

**Comment by 1st1** [comment]
You got it right.
