### ISSUE TITLE
Cannot use edgdb list types

### ISSUE THREAD

**Issue by Smixi** [edgedb/edgedb#4659]
- EdgeDB Version: `2.6`, CLI: EdgeDB CLI 2.1.0+e136de4
- OS Version: 
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
```
Under WSL2 Windows 11
Steps to Reproduce:

1. Follow tutorial
2. Make Migration: `edgedb migration create`
3. Migrate: `edgedb migrate` -> 
4. Show result `edgedb list types`
 
`edgedb error: DescriptorMismatch: unexpected field id, expected name`
Schema:

```module default {
  type Person {
    required property name -> str;
  }

  type Movie {
    property title -> str;
    multi link actors -> Person;
  }
};```

**Comment by nprbst** [comment]
Same here. Not an auspicious (quick)start...

**Comment by nprbst** [comment]
@Smixi `curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com | sh -s -- --nightly` got me unstuck.

**Comment by Smixi** [comment]
We can obviously finish the quickstart :D, just felt weird that it wasn't working.
I'll wait for the release to close the tickets then, in case anyone have this issue to.

**Comment by Smixi** [comment]
https://github.com/edgedb/edgedb/releases/tag/v2.7 fixed this :)
