### ISSUE TITLE
Migrations fail when abstract properties are referenced in globals

### ISSUE THREAD

**Issue by fritzblue** [edgedb/edgedb#4683]
- EdgeDB Version: 2.6
- OS Version: macOS 13.0

Steps to Reproduce:

1. Create the schema below
2. Run `edgedb migration create`

Expected behavior: Migration should run successfully.
Actual behavior: This produces the error `error: object type 'default::Role' has no link or property 'slug'`

Schema:

```
module default {
  global current_user_id -> uuid;
  global current_user := (
    select User filter .id = global current_user_id
  );
  global current_user_role := (
    (global current_user).role.slug
  );

  abstract type WithSlug {
    property slug -> str
  }

  type Role extending WithSlug {
    property description -> str
  }

  type User {
    required link role -> Role;
  }
}
```

**Comment by msullivan** [comment]
This is probably an instance of the more general problem that we are trying to sort the items in the schema before we can properly typecheck expressions in them.
Possibly `current_user` just isn't getting checked properly and can be fixed.
I've got two ideas. The first doesn't technically always work but would probably work very well in practice:
1. Always sort everything with an expression in it after everything without an expression. And always sort things with expressions that can't be referenced (indexes, rewrites, defaults, triggers, policies) after things that can be. Then maybe add weak dependencies based on pointer names.
2. Interleave the declarative ordering with the construction of the schema; use the schema in declarative as a source of truth alongside inferred state. Like above, process everything without expressions first. When trying to sort things with expressions, defer expressions that the simplified inference system can't fully understand and retry them after having built more of the schema.
