### ISSUE TITLE
bind on address: address already in use

### ISSUE THREAD

**Issue by divan** [edgedb/edgedb#4735]
On local dev setup I have from time to time issues with starting old instances due to "address already in use" error (port is not used by any other service, something goes wrong during edgedb startup).

Here is the case from today:

I have 4 instances:

<pre>
edgedb instance list
┌───────┬───────────────┬───────┬──────────────────┬──────────┐
│ Kind  │ Name          │ Port  │ Version          │ Status   │
├───────┼───────────────┼───────┼──────────────────┼──────────┤
│ local │ [redacted]    │ 10707 │ 1.4+0b7ba44      │ inactive │
│ local │ old           │ 10700 │ 2.0-rc.3+f035802 │ inactive │
│ local │ [redacted]    │ 10706 │ 2.5+5f12a50      │ inactive │
│ local │ [redacted]    │ 10704 │ 2.7+a86e274      │ inactive │
└───────┴───────────────┴───────┴──────────────────┴──────────┘
</pre>

`old` (redacted name) means that this instance was created earlier (few months back) and went through upgrades once or twice (just in case it matters).

I haven't used this instance for a month or so, and today, trying to work on the project, noticed that instance can't start. Here is `edgedb instance logs -I old` output:

```
WARNING 29138 2022-11-29T22:10:13.141 edb.server: could not create listen socket for '::1:10700': [Errno 48] error while attempting to bind on address ('::1', 10700, 0, 0): address already in use
WARNING 29138 2022-11-29T22:10:13.141 edb.server: could not create listen socket for '127.0.0.1:10700': [Errno 48] error while attempting to bind on address ('127.0.0.1', 10700): address already in use
```

<details>
  <summary>Full log:</summary>
  
Specifying instance name as positional argument is deprecated. Use `-I old` instead.
INFO 29138 2022-11-29T22:10:09.831 edb.server: starting EdgeDB server 2.0-rc.3+f035802, built on 2022-07-18T23:07Z from revision b25eb140d (2022-07-18T02:03Z) for x86_64-apple-darwin
INFO 29138 2022-11-29T22:10:09.831 edb.server: instance name: 'old'
INFO 29138 2022-11-29T22:10:10.691 edb.server: Using 81 max backend connections based on total memory.
INFO 29155 2022-11-29T22:10:10.760 postgres: starting PostgreSQL 14.4 on x86_64-apple-darwin20.6.0, compiled by Apple clang version 13.0.0 (clang-1300.0.29.30), 64-bit
INFO 29155 2022-11-29T22:10:10.760 postgres: listening on Unix socket "/Users/divan/Library/Caches/edgedb/run/old/.s.PGSQL.5432"
INFO 29155 2022-11-29T22:10:10.767 postgres: database system was shut down at 2022-11-29 22:10:03 EET
INFO 29155 2022-11-29T22:10:10.778 postgres: database system is ready to accept connections
WARNING 29138 2022-11-29T22:10:11.220 edb.server: more than one socket returned by launch_activate_socket(edgedb-server), ignoring all but the first
INFO 29138 2022-11-29T22:10:13.137 edb.server: started 1 compiler worker process
WARNING 29138 2022-11-29T22:10:13.141 edb.server: could not create listen socket for '::1:10700': [Errno 48] error while attempting to bind on address ('::1', 10700, 0, 0): address already in use
WARNING 29138 2022-11-29T22:10:13.141 edb.server: could not create listen socket for '127.0.0.1:10700': [Errno 48] error while attempting to bind on address ('127.0.0.1', 10700): address already in use
INFO 29138 2022-11-29T22:10:13.141 edb.server: Shutting down.
CRITICAL 29138 2022-11-29T22:10:13.323 edb.server: could not create any listen sockets
INFO 29155 2022-11-29T22:10:13.346 postgres: received fast shutdown request
INFO 29155 2022-11-29T22:10:13.347 postgres: aborting any active transactions
INFO 29155 2022-11-29T22:10:13.348 postgres: background worker "logical replication launcher" (PID 29162) exited with exit code 1
INFO 29155 2022-11-29T22:10:13.348 postgres: shutting down
INFO 29155 2022-11-29T22:10:13.357 postgres: database system is shut down
</details>

And it gets stuck in the endless loop of restarts.

I double checked that the port is not used, and while instance is starting it seems like another one is already up. This is what appears in netstat output immediately after `edgedb instance start`:

```
netstat -anvp tcp | awk 'NR<3 || /LISTEN/' | grep '\.107'
tcp4       0      0  127.0.0.1.10700        *.*                    LISTEN       131072  131072      1      0 00080 00000006 000000000002a3c2 00000000 00000900      1      0 000001
tcp6       0      0  ::1.10700              *.*                    LISTEN       131072  131072      1      0 00080 00000006 000000000002a3c1 00000000 00000800      1      0 000001
```

I tried to upgrade the instance, but upgrade failed, because it could not connect to the instance for dumping schema.

Newly created instances (like today), start perfectly.

- EdgeDB CLI Version: 2.2.6+7eabbf9
- OS Version:  MacOS 13.0.1

Any ideas what can be done to start that instance? It's a blocker right now and I'm not sure what I can do to help debug the problem.

**Comment by elprans** [comment]
Hm, this appears to be buggy interaction with socket activation.  Try running the server manually:

```
"/Users/$(whoami)/Library/Application Support/edgedb/portable/2.7/bin/edgedb-server" \
  --data-dir="/Users/$(whoami)/Library/Application Support/edgedb/data/old" \
  --runstate-dir="/Users/$(whoami)/Library/Application Support/edgedb/data/old" \
  --port=12345 \
  --security=insecure_dev_mode
```

and then 

```
edgedb -H localhost -P 12345 --tls-security=insecure
```

**Comment by divan** [comment]
@elprans thanks, that helped! (just needed to change "2-rc3" to "2.0-rc.3")
