### ISSUE TITLE
Index on a mutable computed property is recognized as a valid SDL

### ISSUE THREAD

**Issue by crasite** [edgedb/edgedb#4796]
- EdgeDB Version: 2.7+a86e274
- EdgeDB CLI Version: 2.2.6+7eabbf9
- OS Version: macOS 13.0.1 (22A400) 

Explanation:  

- Schema which have an index on a mutable expression shouldn't be possible.  
- The following schema will create a valid migration file, but it won't be able to migrate.

Steps to Reproduce:

1. Create the following schema with `edgedb migration create`
2. This create a valid migration file which shouldn't be possible, because `link_count` is a mutable expression
3. Call `edgedb migrate`
4. An error `edgedb error: UnsupportedFeatureError: unexpectedly long path in simple expr` is shown

Schema:
```esdl
module default {
  Type Sample{
    multi link simple_link -> Sample;
    property link_count := count(.<simple_link[IS Sample]);
    index on (.link_count);
  }
}
```

**Comment by aljazerzen** [comment]
The problem here is not the computed, but rather using aggregation and accessing links from indexes.

#4869 adds a check for this when migration is created.

This can be cherry-picked to be released in 2.8.
