### ISSUE TITLE
InvalidReferenceError when migrating to an empty schema

### ISSUE THREAD

**Issue by stealth-toucan** [edgedb/edgedb#4804]
- EdgeDB Version: `2.8`
- EdgeDB CLI Version: Irrelevant
- OS Version: Irrelevant

Steps to Reproduce:

1. Migrate to the schema below using `start migration to ...; populate migration; commit migration;`.
2. Migrate to an empty schema in the same way.
3. If step 2 does not fail, retry steps 1 and 2. This bug may be nondeterministic.
4. At some iteration, step 2 will fail with `InvalidReferenceError: constraint 'std::exclusive' does not exist`.

This is a minimal, or near-minimal, reproduction.

Schema:

```
module default {     
    abstract type A;
    
    abstract type B {
        link z -> G {
            constraint exclusive;
        }
    }
    
    abstract type C extending B {
        link y -> H {
            constraint exclusive;
        }
    }
    
    abstract type D;
    
    type E extending D;
    
    type F extending C, B, D;
    
    type G extending D, A {
        link x := assert_single(.<z[IS B]);
    }
    
    type H extending B, D, A {
        link w := assert_single(.<y[IS C]);
    }
}
```

**Comment by msullivan** [comment]
Further reduced version that I've found:
Start with schema
```
module default {
    abstract type A;
    abstract type B {
        link z -> default::A;
    };
    abstract type C extending default::B;
    abstract type D;
    type F extending default::C, default::B, default::D;
};
```
and run
```alter type B drop link z;```
produces
```link 'z' does not exist```

Which notably is not the same error as reported, but is the one I got when I tried...
