### ISSUE TITLE
Getting the same result a multiple times when using WITH and a schema computed

### ISSUE THREAD

**Issue by IngoOutgo** [edgedb/edgedb#4820]
- EdgeDB Version: 2.7+5b16920
- EdgeDB CLI Version: 1.1.2+0cdbb5f
- OS Version: macOS Monterey Version 12.5

Steps to Reproduce:

1. Use this schema:
```
module Subject{
    type Company {
        property country_code -> str;
        link country := (
            select Misc::Country filter .code = Company.country_code
        );
    }
}

module Misc{
    type Country {
        required property name -> str {
            constraint exclusive;
        };
        required property code -> str {
            constraint exclusive;
        };
        required property continent -> str;
    }
}
```
2. Run the following query. You should get the same result 10 times. At least I do with my dataset.
```
WITH
  __scope_0_Company := DETACHED Subject::Company
SELECT __scope_0_Company {
  id
}
FILTER (__scope_0_Company.country.continent = "Asia")
LIMIT 10;
```
3. (optional) For sanity-checking, you can run the query without DETACHED. You should get 10 different results, as I would have expected.
```
SELECT Subject::Company {
  id
}
FILTER (Subject::Company.country.continent = "Asia")
LIMIT 10;
```

When using the edgeDB query builder, the generated query uses DETACHED, which thus gives unusable results.

**Comment by IngoOutgo** [comment]
An interesting observations:

When wrap the erroneus query with a GROUP BY, I get the following result.
```
GROUP(
WITH
  __scope_0_Company := DETACHED Subject::Company
SELECT __scope_0_Company {
  id
}
FILTER (__scope_0_Company.country.continent = "Asia")
)USING _id := .id BY _id
```

![image](https://user-images.githubusercontent.com/10791710/207566990-a0ad9ef2-64eb-49ca-9777-d620672af12e.png)

If I wrap THAT query with a `SELECT (...).elements`, I would have expected to still get duplicate results. But I don't.
![image](https://user-images.githubusercontent.com/10791710/207568020-542df8ac-5f6e-4b11-9e2f-c756d6badd13.png)

Is that part of the bug or my wrong understanding?

**Comment by msullivan** [comment]
It doesn't even take the `detached`... just the with binding

**Comment by msullivan** [comment]
This is related to https://github.com/edgedb/edgedb/issues/4142, though hopefully easier to fix on our side.

There's a simple workaround for you, though, which is to define `country` as
```
select Misc::Country filter .code = __source__.country_code
```
instead of referring explicitly to `Company` there
