### ISSUE TITLE
Using "detached" breaks filters

### ISSUE THREAD

**Issue by IngoOutgo** [edgedb/edgedb#4822]
Disclaimer: This bug might be related to https://github.com/edgedb/edgedb/issues/4820, might even have the same underlying cause.

- EdgeDB Version: 2.7+5b16920
- EdgeDB CLI Version: 1.1.2+0cdbb5f
- OS Version: macOS Monterey Version 12.5

Steps to Reproduce:

1. Use this schema. You see that the country of a company is computed by matching country code.
```
module Subject{
    type Company {
        property country_code -> str;
        link country := (
            select Misc::Country filter .code = Company.country_code
        );
    }
}

module Misc{
    type Country {
        required property name -> str {
            constraint exclusive;
        };
        required property code -> str {
            constraint exclusive;
        };
        required property continent -> str;
    }
}
```
2. Run the following query, in which I filter for Companies in South America. It was generated with the edgedb-js query builder.
```
SELECT(DISTINCT(
    WITH
        __scope_0_Company := DETACHED Subject::Company
    SELECT __scope_0_Company {
        id,
        country_code
    }
    FILTER (__scope_0_Company.country.continent = "South America")
    ORDER BY __scope_0_Company.name ASC EMPTY LAST
    LIMIT 1)
);
```

The bug: The results of this query are Companies that have the country_code set to "US", which definitely doesn't have "South America" set as its continent. In other words, the filter doesn't work correctly. Even when filtering for other continents like "Oceania" I get Companies with the country_code "US", even though there is no country with "US" as country_code and "Oceania" as a continent.
We can even check that this is the result of the "detached" keyword: If I remove it (and adjust the query accordingly), you will get correct results. Sadly the query was generated by the edgedb-js query builder, so I can't just rewrite it.

Here's a screenshot from the REPL.

<img width="749" alt="image" src="https://user-images.githubusercontent.com/10791710/207623320-b86264a2-1f7d-4817-8bc8-53801a91ab45.png">

**Comment by msullivan** [comment]
I'm almost certain this is the same bug as https://github.com/edgedb/edgedb/issues/4820, so I'm going to close this as a dupe, but I'm tracking both sides of it.
