### ISSUE TITLE
invalid constraint expression reported on apply instead of create

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb#4833]
- EdgeDB Version: 2.8+afca054
- EdgeDB CLI Version: 2.3.0-dev.895+cba06af
- OS Version: ubuntu 22.04

The following schema doesn't generate errors on migration create, but it produces `edgedb error: UnsupportedFeatureError: set returning operator <QualName std::DISTINCT> is not supported in simple expressions` on migration apply. It seems like this could be detected at create time instead.

```
module default {
  type MyThing {
    property traits -> array<str> {
      constraint expression on (array_agg(distinct array_unpack(__subject__)) = __subject__)
    }
  };
}
```

**Comment by msullivan** [comment]
Yeah there are a lot of similar errors we should detect at create time.

We should also probably avoid the QualName turd
