### ISSUE TITLE
Improve error message on abstract property with default value

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb#4837]
A user [encountered this on Discord](https://discord.com/channels/841451783728529451/849377751370432573/1054704821560684564) and assumed abstract properties were bugged. Adding a default value to an abstract property appears to be prohibited, but the error message does not indicate the problem:

```
edgedb error: InternalServerError: no referrer context for <class 'edb.schema.properties.AlterProperty'>
```

Can a more specific error be returned in this case to reflect that abstract properties do not support default values (or maybe that they only support `readonly` and annotations)?

**Comment by elprans** [comment]
`InternalServerError` is always a bug.

**Comment by raddevon** [comment]
@elprans Do you mean that `default` should work in this context, or is the bug that the error message isn't specific?

**Comment by elprans** [comment]
Either would be a valid fix here.  As for which exactly I defer to @msullivan and @aljazerzen.

**Comment by aljazerzen** [comment]
Abstract properties don't have a type, so they cannot have default value.

My PR just correctly throws an error (as was already implemented for most cases).
