### ISSUE TITLE
Add support for bare metal RHEL9

### ISSUE THREAD

**Issue by MazeXP** [edgedb/edgedb#4852]
Currently I have servers running RHEL 9 and want to run EdgeDB on bare metal.
Therefore it would be nice if RPM packages for RHEL9 could be built and provided.

As side effect of RHEL9 support it would also support RHEL9 upstream forks like Alma Linux, RockyLinux and so on.

**Comment by msullivan** [comment]
@elprans any thoughts on whether we might do this?

**Comment by elprans** [comment]
It should be straightforward enough, however it's not clear which base image we should use to build artifacts so that they're compatible with the new RHEL reality.
