### ISSUE TITLE
Liveness & Readiness endpoints

### ISSUE THREAD

**Issue by XAMPPRocky** [edgedb/edgedb#4854]
In kubernetes, you typically expose a set of probes to allow the system to know when it's live, when it's ready to serve traffic, and when it has started up. As far as I can tell Edgedb currently doesn't have any documented way to check for it's liveness and readiness. It would be nice if there was documented way to check for Edgedb's liveness and readiness.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by elprans** [comment]
Documentation is, indeed, lacking for these.

The (HTTP) endpoints are: `/server/status/ready` and `/server/status/alive`
