### ISSUE TITLE
Custom access control policy fails for Insert operations (RBAC Implementation)

### ISSUE THREAD

**Issue by davidfries** [edgedb/edgedb#4860]
Posting this on behalf of spost on Discord as he's OOO currently. 

[Discord thread](https://discord.com/channels/841451783728529451/1055624003508776970/1055624008655183872) for context 

- EdgeDB Version: 2.8+afca054
- EdgeDB CLI Version: EdgeDB CLI 2.2.6+b869667
- OS Version: Pop!_OS 22.04 LTS x86_64

Steps to Reproduce:
Attached is a mostly-empty edgedb project with the RBAC schema, an Example type that extends RBAC::Controlled, and a setup.edgeql file

1.  Use attached zip and run `edgedb query -f setup.edgeql`
2. Try to add an Example that belongs to that organization while using that role

[edgedb-rbac-repro.zip](https://github.com/edgedb/edgedb/files/10320540/edgedb-rbac-repro.zip)

**Comment by aljazerzen** [comment]
I've checkout the RBAC repro project and I must say it's impressive!

First, I think that in `setup.edgeql`, you have a minor mistake:

```diff
# Set our role_ids
 set global RBAC::role_ids := <str>(
 	select RBAC::DbRole
 	filter .name = "Organization Admin" and .organization.name = "Example Organization"
-	limit 1).organization.id;
-	limit 1).id;
```
... but this is not the crux of the problem.


I've debugged it down to this condition:
```
# ... within a policy when condition
    # A permission covers this scope, or all scopes (*)
    equal_or_star(
        permissions.scope,
        pluck_scope_annotation(__subject__.__type__)
    )
```
`pluck_scope_annotation` returns an empty set even though `__subject__.__type__` should refer to `default::Example`. I've checked that this does return the value of scope annotation:
```
select RBAC::pluck_scope_annotation(
  (select schema::ObjectType filter .name = 'default::Example' limit 1)
)
```

Which means that this is a bug or an undocumented limitation. I'll ask @msullivan about it.

**Comment by spost-stateless** [comment]
Cheers, thanks DJ, and good catch on the repro @aljazerzen.  I'm back in the office now, so free to answer any questions about this.

**Comment by msullivan** [comment]
I think I can reproduce this with
```
create type T {
    create access policy ok allow all;
    create access policy asdf deny insert using (.__type__.name ?!= 'default::T');
};
```
