### ISSUE TITLE
Document the 3.0 situation for nonrecursive_access_policies

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#4874]
https://github.com/edgedb/edgedb/pull/4845 will make nonrecursive_access_policies the only behavior. It doesn't update the docs, since 3.0 isn't out yet, but we'll need to.

(Do we need to start rethinking our documentation versioning strategy?)

**Comment by raddevon** [comment]
Should the documentation be done as part of #4845, or should it be a separate PR?

**Comment by msullivan** [comment]
This seems like it happened
