### ISSUE TITLE
Add 'CORRELATED TO' variant of functions call

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#492]
Currently queries like `SELECT Object.id ORDER BY random()` and `SELECT (Object, random())` produce what a naïve user might not expect: `random()` (a volatile function) is calculated only once.  To fix that we need to somehow hint to the compiler that the `random()` call is related to elements of some set.  A proposed syntax for that is as follows:

```
<callable expr> '(' [<args expr>, ] ')' CORRELATED TO '(' <cor expr> ')'
```

Where `<cor expr>` expression must be evaluated to a singleton set.

Examples:

```
SELECT (Object.id, random() CORRELATED TO (Object.id));
SELECT x := {1, 2, 3, 4} ORDER BY random() CORRELATED TO (x);
```

**Comment by elprans** [comment]
Depends on #310

**Comment by msullivan** [comment]
`SELECT Object.id ORDER BY random()` works now and `SELECT (Object, random())` is disallowed.

We can do the thing discussed with a `for`: `for x in Object union (x, random())`, so I don't think we need this anymore
