### ISSUE TITLE
Document version pinning behavior for `edgedb instance create` et al

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#4929]
Currently
```
edgedb instance create --version 2.6 demo2something
```
will install the latest version of 2.x while in order to install 2.6 you need to put an `=` in front, like so:
```
edgedb instance create --version =2.6 demo26
```

There is similar behavior in pyproject.toml.

We should document this.

(I also still think that on the command line, it should install the actual specified version, but I won't insist on relitigating that)

**Comment by AnsonHwang86** [comment]
thanks, Yes,we can't specify version of edgedb in cli now. It will always use the latest version.

**Comment by msullivan** [comment]
> thanks, Yes,we can't specify version of edgedb in cli now. It will always use the latest version.

You can, you just need to put an `=` in front of the version.
