### ISSUE TITLE
EdgedB UI not working on nightly build

### ISSUE THREAD

**Issue by Jarrodsz** [edgedb/edgedb#4975]
- EdgeDB Version: "3.0-dev.7211+4d63593"
- EdgeDB CLI Version: EdgeDB CLI 2.2.6+7eabbf9
- OS Version: OSX Ventura latest

Steps to Reproduce:

1. Install regular edgedb 
3. Upgrade to nightly build edgedb project upgrade --to-nightly

Edgedb works fine

edgedb ui
``` jordan@dev  ~/Desktop/edgedb  edgedb ui
Cannot read JOSE key files: failed to open file `/Users/jordan/Library/Application Support/edgedb/data/edgedb/edbjwekeys.pem`: No such file or directory (os error 2))
Opening URL in browser:
https://localhost:10700/ui```

1. Throws error
2. Loads the UI in browser but asks for username, password
3. Existing credentials do not work the pem file is not available so I guess it cannot login at all but tried the edgedb, edgedb and edgedb, info

**Comment by fantix** [comment]
Please use a nightly CLI to open the UI for nightly servers - the use of JWE is abandoned in 3.0.

**Comment by CSFlorin** [comment]
@fantix how do you use the nightly CLI? Trying `edgedb ui --nightly` gives

```
error: Found argument '--nightly' which wasn't expected, or isn't valid in this context
```

**Comment by fantix** [comment]
Yes that, or you could also:

```
edgedb cli upgrade --to-nightly
```
