### ISSUE TITLE
User-defined functions with variadic+optional arguments have problems

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#4982]
Variadic functions have all their variadic arguments packed into an array. If one of those arguments is `NULL`, the array will have a `NULL` in it, which is not legit in edgeql.

```
edgedb> create function foo(variadic doc: optional int64) -> array<int64> using (assert_exists(doc));
OK: CREATE FUNCTION
edgedb> select foo(1, <int64>{}, 3);
[[1, null, 3]]
edgedb> \set output-format default
edgedb> select foo(1, <int64>{}, 3);
edgedb error: ProtocolEncodingError: ProtocolEncodingError: unexpected end of frame
Reconnecting...
```

I'm not sure that there is any sensible way to handle this in edgeql as it exists now, so we should probably just ban this.

**Comment by elprans** [comment]
Yes, variadic+optional should be banned
