### ISSUE TITLE
custom function wasn't supported via HTTP

### ISSUE THREAD

**Issue by AnsonHwang86** [edgedb/edgedb#4989]
- EdgeDB Version: V2.9
- EdgeDB CLI Version:
- OS Version: WSL in widows 10

Steps to Reproduce:

1. run the query `select SellingOrder {computedPurchaseDateTime }` via repl will return the correct result.
2. run the query `select SellingOrder {computedPurchaseDateTime }` via http by insomnia will result null.

![image](https://user-images.githubusercontent.com/16233397/217168121-c41857f3-79e9-4d68-b4aa-96ab77724264.png)

![image](https://user-images.githubusercontent.com/16233397/217168182-96745e71-685b-4f7b-9c1c-b0322c42514b.png)

Schema:
```
type SellingOrder {
		property purchaseDateTime -> datetime;
		property computedPurchaseDateTime := get_fdow(.purchaseDateTime);
	}

	function get_fdow(dt: datetime) -> str # get the first day of specified week
        	using (
            	with pur_date := cal::to_local_datetime(dt,"America/Los_Angeles"),
            	weeks := datetime_get(pur_date, "isodow"),
            	first_date_of_week := pur_date - <duration>(<str>((weeks-1)*24*60*60*1000) ++ " milliseconds"),
            	week := str_split(<str>first_date_of_week, "T")[0],
            	select week
        );
```

**Comment by raddevon** [comment]
Confirmed this doesn't seem to be related to the computed property. Even just calling the function directly in a query (like `select get_fdow(datetime_current());`) doesn't work over HTTP even though it works fine in the REPL. That returns just an object with a `data` key containing an empty array.
