### ISSUE TITLE
Mysql Support

### ISSUE THREAD

**Issue by rverma-nsl** [edgedb/edgedb#5045]
Is it possible to support MySql too? What would be the steps involved, I can give it a shot.
Thanks

**Comment by msullivan** [comment]
It would be a pretty huge engineering effort:
 * Managing a mysql server and speaking its protocol
 * Finding a way to replicate all of the things we use postgres specific features for. MySQL doesn't have arrays, which we use heavily, so we'd need to be able to use json everywhere for aggregations and for array types. 
 * Work around mysql not having transactional DDL somehow

And in the end there wouldn't be that much of a gain from it. Postgres is good, and from a point of view of our users, should mostly be an implementation detail.
