### ISSUE TITLE
Range ignoring inc_upper := true

### ISSUE THREAD

**Issue by cipherlock** [edgedb/edgedb#5047]
- EdgeDB Version: 2.9+9449999
- EdgeDB CLI Version: EdgeDB CLI 2.2.6+7eabbf9
- OS Version: OS X 13.2.1

Steps to Reproduce:

1.  When trying to insert a range and setting inc_upper: = true the range gets inserted into the database as inc_upper:= false
  sample insert
  ```
    with raw_data:= <json>$data,
    for item in json_array_unpack(raw_data) union (
      insert A {
        property_a := <str>item['property_a'],
        property_b := <str>item['property_b'],
        name := <str>item['name'],
        range:= range(<int64>item['START_INT'], <int64>item['END_INT'], inc_upper := true)
      }
    )
   ```
   sample range value
   ```
   range(1111111111, 2222222222, inc_lower := true, inc_upper := false)
   ```

Schema:
```
module default {
abstract type Base {
    required property range -> range<int64>;
    property property_a -> str;
    property property_b -> str;
    index on ((.property_a, .property_b));
  }

  type A extending Base {
    property name -> str;
  }
}
```

**Comment by vpetrovykh** [comment]
First of all, I took the liberty to re-format your question, so that the code blocks are easier to read.

**Comment by vpetrovykh** [comment]
Now as for the range issue, I think what you're experiencing here is range normalization that happens for integer ranges. Basically, because integers are discrete including the upper bound is the same as increasing it by one and omitting it:
```
edgedb> select range(111, 222, inc_upper := true);
{range(111, 223)}
edgedb> select range(111, 223, inc_upper := false);
{range(111, 223)}
edgedb> select range(111, 222, inc_upper := true) = range(111, 223, inc_upper := false);
{true}
```
You can treat the lower bound similarly:
```
edgedb> select range(111, 222, inc_upper := true) = range(110, 223, inc_lower := false);
{true}
```
The ranges `range(0, 3, inc_lower := false, inc_upper := true)` and `range(1, 4, inc_lower := true, inc_upper := false)` are in fact mathematically equivalent: they are describing the same exact set of integers. So EdgeDB treats them as the same value and uses the same representation for them. By default all ranges assume that the lower bound is included and the upper bound is excluded, so a `range(1, 4)` contains the following: 1, 2, 3.

Note that this normalization doesn't apply to ranges based on floats:
```
edgedb> select range(111.0, 222.0, inc_upper := true);
{range(111, 222, inc_upper := true)}
edgedb> select range(111.0, 222.0, inc_upper := true) = range(111.0, 223.0, inc_upper := false);
{false}
```

**Comment by vpetrovykh** [comment]
This feature is briefly mentioned in the [ranges documentation](https://www.edgedb.com/docs/stdlib/range#constructing-ranges).

**Comment by cipherlock** [comment]
@vpetrovykh thank you for re-formatting the question.  I will try to follow that style if I need to submit another issue!

Regarding the range in this case I actually need the upper bound to be included since it would result in some potential data loss.

Based on your explanation it was not clear if this is considered expected behavior or if this would be considered a bug.  Any thoughts and/or insights would be appreciated.

**Comment by msullivan** [comment]
Yeah, this is intended (and even documented!) behavior, inherited from postgres's treatment of ranges.

If you need to preserve the `inc_upper` and `inc_lower` bounds specifically in your use-cases, you'll probably want to store a tuple (possibly a named tuple) that stores your bounds and your inc_lower/inc_upper flags, and then construct a range from that when you want to do range operations on it.

Closing this issue, but feel free to ask any follow up questions!

**Comment by cipherlock** [comment]
@msullivan 
Thanks for the clarification!  I looking through the data it appears that you are actually modifying the data and doing the increment on my behalf.  As a quality of life documentation improvement I would suggest that you spell out the behavior a little more explicitly since to a newbie like myself the function was not performing as expected since the flag that I set was not actually getting set 😀.
