### ISSUE TITLE
Expose cryptography and hashing functions

### ISSUE THREAD

**Issue by mritzerfeld** [edgedb/edgedb#5065]
What I'm currently missing are some basic cryptography and hashing functions like plain old md5() or digest() from pgcrypto for use in custom functions and computeds.

From what I take from other standard library EdgeQL modules, it is possible (and most problaly sufficient) to expose the underlying Postgres functions.

If I'm not mistake here and there is interest in this request, I could draft a pull request.

BTW is there any word on when custom extensions will be supported as such could provide a way for interim solutions in urgent cases?

**Comment by jnak** [comment]
That would be great!

Core team -- could you confirm there is interest on your end?
