### ISSUE TITLE
Our ancestor resolution order isn't *quite* C3

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#5118]
I think that our ancestor ordering is intended to be the C3 linearization ordering (https://en.wikipedia.org/wiki/C3_linearization), which is what Python uses, but we don't include the list of base classes in the list of orders to merge.

I believe this results in us not always having the second of the C properties, "preservation of local precedence order" (which makes our algorithm one of several possible "C2" algorithms :P).

I think, though I may be wrong, that the cases in which we *don't* preserve local precedence order are all cases that would be rejected by the C3 algorithm.

I'd like to fix this, but it might not be worth the compatibility break. No idea how common this will be in user code. Probably not that common.

```
with X := schema::InheritingObject
select X {
  name,
  bases: {name, @index} order by @index,
  ancestors: {name, @index} filter X.ancestors in X.bases order by @index,
  mismatch := (array_agg((select .bases order by @index).name) != array_agg((select .ancestors {name} filter X.ancestors in X.bases order by @index).name)),
}
filter .mismatch;
```
will find all the object types in a schema that don't obey the ordering.

There are a few in the schema, and most seem to be caused by the reflection machinery adding in base classes that weren't written in the schema and not being careful about where in the list they get added.

**Comment by elprans** [comment]
Ideally we should document and fix this.  The release notes can have a section on porting and we can go as far as introducing a pre-flight check for CLI-driven upgrades using the introspection query above.

**Comment by msullivan** [comment]
Well, this'll be a good chance to put our new tools for rewriting and squashing migrations into practice, then :)

**Comment by msullivan** [comment]
(Also that query takes almost 20s, which is way more than makes sense to me)
