### ISSUE TITLE
ISE when creating a recursive trigger

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#5164]
- EdgeDB Version: EdgeDB 3.0-dev.7307+local (repl 3.0.0-dev) (current master 44928f0aa3854b3779073852d2ab1a6054285e47)
- EdgeDB CLI Version: current master 
- OS Version: Ubuntu

Steps to Reproduce:

Setup:
```
create type Foo {
  create required property val -> str;
  create trigger t0 after insert for each do (
    insert Foo {val := '!'}
  );
};
```
This is already a problem because recursion should be detected at this stage, before any queries run.

Then when we make an insert we get a ISE:
```
edgedb> insert Foo{val := 'test'};
edgedb error: InternalServerError: syntax error at or near "("
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: syntax error at or near "("
```

**Comment by msullivan** [comment]
We've decided that triggers should chain and that we should prohibit recursion, which means this is subsumed by  #5186
