### ISSUE TITLE
Encrypted table and column names in GCP PostgreSQL

### ISSUE THREAD

**Issue by rajeshdhanda** [edgedb/edgedb#5216]
**Description:**

I have built a database in EdgeDB using GCP PostgreSQL as the backend. I can see the data through EdgeDB SDK or EdgeDB UI, but when I connect to the GCP PostgreSQL instance directly or through Fivetran, the table and column names are encrypted. I need to see the table and column names to work with the data properly. Additionally, I need to sync non-encrypted data from Edgedb/PostgreSQL to Snowflake using Fivetran.

**Steps to reproduce:**

1. Build a database in EdgeDB using GCP PostgreSQL as the backend.
2. Create tables in EdgeDB.
3. Connect to the GCP PostgreSQL instance through Fivetran.
4. Try to access the table and column names.

**In Edgedb:** 
![IMG_20230321_140757](https://user-images.githubusercontent.com/50963889/226554682-b3957dac-68ce-4684-aa5a-7e1a8c1827b0.png)

**In Postgres:**
![image](https://user-images.githubusercontent.com/50963889/226547034-776402a0-4e0a-4069-9ff7-9d2e997de46e.png)

**fivetran to GCP postgresql sync :** 
![image](https://user-images.githubusercontent.com/50963889/226547551-00b03537-8d95-4071-9aa1-6fbace6d2a27.png)

**Expected behaviour:**

I should be able to see the table and column names in the GCP PostgreSQL instance when connecting through Fivetran.

**Actual behaviour:**

The table and column names are encrypted, making it difficult to work with the data properly. Additionally, I need assistance in syncing non-encrypted data from Edgedb/PostgreSQL to Snowflake using Fivetran.

@elprans

**Comment by raddevon** [comment]
We are adding support for some data analysis tools in our upcoming 3.0 release, but it's not available in 2.x. See https://github.com/edgedb/edgedb/issues/4814 for more information about the support we're adding.
