### ISSUE TITLE
Rename constraints to avoid potential clashes and ambiguity

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#524]
Constraints like `min`, `max`, `length` and other similar ones potentially clash with function names. Here's the proposed renaming:
* constraint  ->  constraint (abstract parent of all constraints, hardly ever used explicitly)
* enum  ->  one_of
* exclusive  ->  exclusive
* expression  ->  expression
* len_constraint  ->  len_value
* max  ->  max_value
* max_ex  ->  max_ex_value
* max_len  ->  max_len_value
* min  ->  min_value
* min_ex  ->  min_ex_value
* min_len  ->  min_len_value
* regex  ->  regex (this one doesn't need to be renamed, since regexp functions are all prefixed with "re_" and doing so here might be more ambiguous)

**Comment by vpetrovykh** [comment]
@1st1 and @elprans, do you have any more thoughts on this?

**Comment by 1st1** [comment]
+1;

"regex -> re_matches" is not necessary.

**Comment by elprans** [comment]
-1 on renaming "regex", everything else looks ok

**Comment by vpetrovykh** [comment]
OK, I've updated the list.

**Comment by vpetrovykh** [comment]
Implemented by #525.
