### ISSUE TITLE
Find a better separator for the list of Access Policy violations

### ISSUE THREAD

**Issue by avedetvedea** [edgedb/edgedb#5245]
A comma doesn't look like it was a well thought out decision. There is a good chance that a comma will be placed in the `errmessage`s of Access Policies, so things will look messy. A semicolon would be better, both in terms of meaning and is not as omnipotent as a comma, but better options may be found

**Comment by msullivan** [comment]
I agree that a semicolon is better and we should switch to it.
Not sure if there is anything preferable to that, though. We want it to read naturally, so don't want to do anything obscure.
