### ISSUE TITLE
InternalServerError: prepared statement "63a348b751d5ec3b8042b06e1092bf254cd7409c" already exists

### ISSUE THREAD

**Issue by avedetvedea** [edgedb/edgedb#5246]
I don't even know how to even begin trying to provide a repro, but I will say for now that the error happened while testing my Access Policies and some of my working queries are blown. Any direction on why this would happen would both help me provide a repro and find workarounds myself

**Comment by avedetvedea** [comment]
Queries are working again (without doing anything). Is it possible that a migration (that doesn't necessarily had an effect on the query) wasn't applied properly in the UI causing a discrepancy leading to that error? I refreshed the page a couple of times to make sure before opening the issue, so if that was the reason then some weird (and prolonged) things happened in the process. 

How can we make sure that this error won't come back in production? (i.e., what is this error and what just happened (why the queries are 'fixed'))

**Comment by avedetvedea** [comment]
After creating a new Access Policy and then deleting them (and doing nothing in the process), i.e., after returning to the exactly the same migration state, this error occurred

**Comment by msullivan** [comment]
That's kind of wild. @fantix any idea what could cause this?

**Comment by avedetvedea** [comment]
@msullivan This error literally disappeared 2 different times! (after reverting my migrations) after waiting for a couple of minutes and trying it again

**Comment by avedetvedea** [comment]
the suspect

```
access policy CANT_UPDATE_UPCOMING_POLLS
            deny update read
            using (.id not in (
                with userCurrentPollIndex := .user.currentPollIndex
                select .user.currentPolls order by .random limit userCurrentPollIndex
            ).id) {
                errmessage := 'Can only update the nextPoll or the previous polls from the currentPolls';
            };
```

Again, I strongly stress that even after reverting this migration the error persists, and disappears after some time. This behavior is highly problematic

**Comment by fantix** [comment]
Which version of server are you running on? Will you be able to set some environment variables to get more details in server log:

```
EDGEDB_DEBUG_SERVER_PROTO=1
EDGEDB_DEBUG_PGSERVER=1
```

**Comment by avedetvedea** [comment]
@fantix I am running nightly. I am unable to reproduce this bug.

**Comment by fantix** [comment]
In that case, could you pls get the `stage_no` in `select sys::get_version();`?

**Comment by avedetvedea** [comment]
Sorry for that; I took my time to break it similarly but couldn't get it to that. 

```
{
  "major": 3,
  "minor": 0,
  "stage": "dev",
  "stage_no": 7341,
  "local": [
    "6ae43f0"
  ]
}
```

**Comment by fantix** [comment]
No worries! Theoretically (by reviewing the code) this may be caused by a certain type of weird network error that only closes half of the client connection during a slow script execution, leaving the backend connection in a inconsistent state; but I need to try harder to reproduce it.

**Comment by avedetvedea** [comment]
One thing I'm certain about is that the errors disappeared without me doing **anything** other then waiting and trying again; hope that and the fact that I couldn't reproduce (by doing the **exact** same things) may help finding the root.

**Comment by fantix** [comment]
I think I eventually reproduced this issue - it involves a few steps happening in a very subtle order. Let me push a fix with an explanation of the issue.
