### ISSUE TITLE
ISE inserting empty id with allow_user_specified_id enabled

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb#5284]
- EdgeDB Version: 3.0-dev.7343+4d0b071
- EdgeDB CLI Version: 3.0.0-dev.941+730fc35
- OS Version: ubuntu 22.04

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/8278635/229178480-e1dd32c1-bfbf-4191-bde0-faebd2ebb155.png)

Schema:
```
module default {
  type User {
    required property name -> str;
  }
}
```

**Comment by msullivan** [comment]
An error processing bug in `errormech.py`. This one happens whether in a transaction or not
