### ISSUE TITLE
InternalServerError on migration with new constraint

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb#5326]
I figured this constraint probably wouldn't work but wanted to try it anyway. It gives me an ISE.

- EdgeDB Version: 2.13+ad0eb0f
- EdgeDB CLI Version: 3.0.0-dev.946+93cec91
- OS Version: macOS 13.2.1

Steps to Reproduce:

1. Create a project with `edgedb project init`
2. Add the problematic schema to `dbschema/default.esdl`
3. Attempt to create migration with `edgedb migration create`

Schema:

```
module default {
  type Cause {
    required property name -> str;
    required multi link charities -> Charity {
      property weight -> float64;
      constraint expression (sum(.charities@weight) <= 10);
    }
  }
  type Charity {
    required property name -> str;
  }
}
```

**Comment by msullivan** [comment]
Could you include the ISE traceback?

**Comment by msullivan** [comment]
There is an issue in the schema, which is that `(sum(.charities@weight) <= 10)` is an *argument* to the constraint, not a constraint subject (which would be `on (...)`)
But expression doesn't *take* any arguments, and the code path dereferences a `None`

We should produce a proper error message
