### ISSUE TITLE
TLS issues on Local Setup

### ISSUE THREAD

**Issue by MohitDeshwal** [edgedb/edgedb#5354]
- EdgeDB Version: 2.13+ad0eb0f
- EdgeDB CLI Version: EdgeDB CLI 2.3.1+5d93f42
- OS Version: Macos 13.3.1

Steps to Reproduce:

1. Install EdgeDb
2. Try to connect it by golang driver
`opts := edgedb.Options{Concurrency: 4}
	client, err := edgedb.CreateClientDSN(ctx, "edgedb://edgedb@localhost:port/mydb", opts)`

Schema:
 Gives error: 
 **Error executing EdgeDB query: edgedb.ClientConnectionFailedError: tls: failed to verify certificate: x509: “EdgeDB Server” certificate is not standards compliant** 

According to edgeDb docs:

> TLS is required to connect to any EdgeDB instance. To do so, the client needs a reference to the root certificate of your instance’s certificate chain. **Typically this will be handled for you when you create a local instance or link a remote one**.

**Comment by elprans** [comment]
Do not use a DSN.  Local EdgeDB projects are auto-configured (via `edgedb.toml` presence in project root), so 

```
opts := edgedb.Options{Concurrency: 4} client, err := edgedb.CreateClient(ctx, opts)
```

should work.

Local servers use self-signed certificates, so if you are providing an explicit connection configuration, you must also configure TLS (either explicitly trust the certificate, or disable TLS verification), but that is not recommended.

**Comment by MohitDeshwal** [comment]
Thanks for the details @elprans. 
PS, We may also update edgedb docs with this info.
