### ISSUE TITLE
Can't set password using --admin

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb#5383]
- EdgeDB Version: 3.0-alpha.3+9047228 (apt package edgedb-3-alpha3)
- EdgeDB CLI Version: EdgeDB CLI 3.0.0-alpha.6+c5ba4fd (apt package edgedb-3-alpha3)
- OS Version: ubuntu 22.04

Steps to Reproduce:
Follow the [bare metal guide](https://www.edgedb.com/docs/guides/deployment/bare_metal), but using the `testing` channel and install `edgedb-3-alpha3` instead of `edgedb-2`. The step that has you set the password using the `--admin` flag fails:

```bash
$ sudo edgedb --port 5656 --tls-security insecure --admin query  "ALTER ROLE edgedb SET password := '$PASSWORD'"
edgedb error: PasswordRequired: Password required for the specified user/host
```

**Comment by hongquan** [comment]
On EdgeDB 3, to use `--admin`, you have to:
- Connect to server via Unix domain socket, via `--unix-path` option.
- Switch to Linux user `edgedb` to connect: `sudo -u edgedb`.

**Comment by fmoor** [comment]
fixed with https://github.com/edgedb/edgedb/pull/5760
