### ISSUE TITLE
Prohibit self-reference in INSERT

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#539]
Consider this statement:
```
INSERT SelfRef {
    name := 'myself',
    ref := SelfRef
};
```

What does the nested `SelfRef` actually refer to? Is it the instance being inserted (which technically doesn't exist yet)? Is it always an empty set? Is it equivalent to `DETACHED SelfRef` (semantically the total set of `SelfRef` *prior* to this statement)?

Considering the amount of ambiguity we may want to ban this usage altogether.

See `test_edgeql_insert_selfref...` from #537 

@1st1 and @elprans what are your thoughts?

**Comment by elprans** [comment]
Yes, it should be banned (at least for now).
