### ISSUE TITLE
InternalServerError: binary data has type 0 (-) instead of expected 25 (text) in record column 1

### ISSUE THREAD

**Issue by quinchs** [edgedb/edgedb#5400]
- EdgeDB Version: 3.0-dev.7435+bb3b78c
- EdgeDB CLI Version: EdgeDB CLI 2.3.1+ef99779
- OS Version: Windows 10

Schema:
```
module default {
  global abc -> tuple<str, int64>;
}
```

Query:
```cs
var result = await client
    .WithGlobals(new Dictionary<string, object?>
    {
        { "abc", ("abc", 123L) }
    })
    .QueryAsync<(string, long)>("select global abc");
```

State data:
```
00000001000000030000002B00000001000000000000001F0000000200000000000000036162630000000000000008000000000000007B
```

`Parse` succeeds, `Execute` throws the ISE.

Can other people test in different bindings? I don't think this is only a .NET binding issue.

**Comment by quinchs** [comment]
seems to happen with any tuple type

**Comment by fantix** [comment]
Yup I'm getting the following in Python:

```
edgedb.errors.InternalServerError: binary data has type 0 (-) instead of expected 25 (text) in record column 1
```

**Comment by jaclarke** [comment]
JS client as well: https://github.com/edgedb/edgedb/issues/5356

**Comment by msullivan** [comment]
It works in the CLI, but that has a pretty different path

**Comment by msullivan** [comment]
dupe
