### ISSUE TITLE
Trying to assign result of two coalesced select queries to a union type link throws an InvalidLinkTargetError 

### ISSUE THREAD

**Issue by Arrow7000** [edgedb/edgedb#5407]
- EdgeDB Version: 2.13+c171f92
- EdgeDB CLI Version: 2.3.1+ef99779
- OS Version: Windows 10 Home build 19045.2846

I'm trying to update a union type link based on whichever of the two types contains the record I'm looking for

Schema:

```
# Vehicles
abstract type Vehicle {
    required property model -> str { constraint exclusive; }
}
type Motorcycle extending Vehicle {
    required property geared -> bool;
}
type Car extending Vehicle {
    required property numOfDoors -> int16;
}
type Bicycle extending Vehicle {
    required property frameMaterial -> str;
}

# Drivers/riders
abstract type Driver {
    required link vehicle -> Vehicle;
}
type CarDriver extending Driver {
    overloaded required link vehicle -> Car;
}
type MotorcycleRider extending Driver {
    overloaded required link vehicle -> Motorcycle;
}
type Cyclist extending Driver {
    overloaded required link vehicle -> Bicycle;

    # Don't want to use the common abstract type Vehicle because this should not include other Bicycles
    link hobbyVehicle -> Car | Motorcycle; 
}
```

Query:
```
with
  hobbyVehicleModel := <str>$hobbyVehicleModel
update Cyclist
filter .vehicle.id = <uuid>$lorryId
set {
  hobbyVehicle := (
    # Try to look in both types to find the model that matches 🔍
    (select Motorcycle filter .model = hobbyVehicleModel) ?? (select Car filter .model = hobbyVehicleModel)
    # Also tried: `(select Vehicle filter .model = vehicleModel and (Vehicle is Car or Vehicle is Motorcycle))`
  )
}
```
The above update statement fails with error
```
InvalidLinkTargetError: invalid target for link 'hobbyVehicle' of object type 'default::Cyclist': 'default::Vehicle' (expecting 'default::Car | default::Motorcycle')
```
Even though as far as I can tell this should work, since the `select` query should return a record of type `Car | Motorcycle`, so why does it think I'm trying to assign the link a value of type `Vehicle`? 
But either way, how would I get this working without needing to run a separate update statement to try to find each of the allowed subtypes separately?

**Comment by msullivan** [comment]
I think this is kind of tricky, and speaks to a common problem in systems that have both an inheritance hierarchy and union types of: when should you infer a union type and when should you infer a common parent?

Possibly the solution is to support type operators in `IS` so you can write `[is Car | Motorcycle]` after?

**Comment by Arrow7000** [comment]
To me it feels like the natural shape of a query like this should just be `A | B`. I don't want the type system to get too clever and figure out that since these two queries have an ancestor type that that's what the return type should be. Especially since if I were to coalesce two queries on types that have no common ancestor I would expect that expression to just return `A | B`, so changing that behaviour just because the two types have a common ancestor is "surprising."

**Comment by msullivan** [comment]
Actually, I think you are right, and in this context union types are probably better.
(The situation is different in other type systems I've worked on, like mypy for python, where the interaction with things like mutable lists causes trouble.)

We already have UNION and IF produce a union type, we should just do it for coalesce also
