### ISSUE TITLE
Trigger: access to the full tuple supported?

### ISSUE THREAD

**Issue by dvv** [edgedb/edgedb#5459]
I am experimenting with triggers to try to log in full the tuple being affected.
As can be seen below so far it logs only the id of the tuple.
I can not figure out whether it is due to inheritance, due to the way I write trigger internals or due to edgedb failure?

- EdgeDB Version: 3.0-dev.7478+0bbf060
- EdgeDB CLI Version: EdgeDB CLI 3.0.0-dev.980+968ca50
- OS Version: Linux vd 5.4.0-148-generic Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. `insert Project { name := "Xxx" };` gives ok
```
{default::Project {id: ceb80140-eefe-11ed-bb60-fbb202c854e2}}
```
2. `select Log { * };` gives
```
{
  default::Log {
    id: ceb806a4-eefe-11ed-bb60-6324179d68cd,
    body: Json("{\"id\": \"ceb80140-eefe-11ed-bb60-fbb202c854e2\", \"op\": \"upsert\"}"),
  },
}
```
Notice the absense of the `name` field in the `body` ^^^.

Schema:

```
type Log {
  required property body: json {}
}

abstract type Resource {
  required property name: str {
    rewrite insert, update using (str_trim(.name)); # NB: same behavior despite this rule
  }
  trigger _log_upsert_changes after insert, update for each do (
    insert Log { body := <json>__new__ ++ <json>{ op := "upsert" } }
  );
}

type Project extending Resource {
}
```

TIA

**Comment by msullivan** [comment]
If you do `select <json>Resource` you'll get the same thing. It jsonifies based on the *shape*. You could try `<json>(Resource {*})`, though as a matter of style and architecture I'd maybe recommend enumerating the fields you actually want

**Comment by dvv** [comment]
@msullivan Thank you for the reply. Am I right that triggers in abstract types do not "delegate" to real derived type of `__new__` etc? So that to log changes to the derived types we need to move triggers to that types?

**Comment by dvv** [comment]
This did the trick:
```
abstract type Resource {
  trigger _do_log_upsert_changes after insert, update for each do (
    insert Log { body := <json>(__new__ {*}) ++ <json>{ op := "upsert" } }
  );
}
```

**Comment by jinxmcg** [comment]
Hi, 



I tried like this and it does not work.

`module default {
    type Log {
        action: str;
        timestamp: datetime {
            default := datetime_current();
        }
        new: json;
        old: json;
    }


     abstract type Auditable {
        trigger _do_log_upsert_changes after insert, update for each do (
            insert Log { new := <json>(__new__ {*}) ++ <json>{ op := "upsert" } }
        );
    }

    type Person extending Auditable {
        required property name -> str {
            constraint exclusive;
            constraint max_len_value(50);
        };
    }

}`

Still think there is a issue here. Any hints are appreciated.

Thank you
