### ISSUE TITLE
Add Limit none value

### ISSUE THREAD

**Issue by avedetvedea** [edgedb/edgedb#5485]
I have been using `limit` as a variable for some of my queries and often I need to fallback to or decide in-query that all data should be fetched. In those cases I use `limit` with `count` to get all of them, which is unnecessary incurred cost in many ways. I think something like `limit all` or `limit inf` would be helpful

**Comment by elprans** [comment]
Use `limit <int64>{}`

**Comment by elprans** [comment]
@raddevon, let's make sure this is explicitly documented.

**Comment by avedetvedea** [comment]
@elprans thanks
