### ISSUE TITLE
Generated TypeScript do not work in a SvelteKit or Nuxt project

### ISSUE THREAD

**Issue by notramo** [edgedb/edgedb#5486]
Latest version from NPM.
When `preserveValueImports` and `isolatedModules` are both enabled, the TypeScript checker throws errors on the generated bindings, like this:
```
Error: 'ExpressionRoot' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.
```

These tsconfig options are required for JS framework compilers such as Svelte and Vue to function properly.

**Comment by lu-zen** [comment]
It works fine here using typescript v5. I noticed `preserveValueImports` was deprecated, try upgrading and see how it goes.

**Comment by notramo** [comment]
@lu-zen, I'm already using typescript v5.

**Comment by progrestian** [comment]
@notramo Can you test the issue again? My commit is merged and a new version for the generator have been released. For me on SvelteKit it works but maybe you can also test it for Vue.

**Comment by notramo** [comment]
It seems resolved, it no longer errors out in vanilla SvelteKit project TS config.
