### ISSUE TITLE
Function cannot accept array<enum> as parameter in `migration create` tool

### ISSUE THREAD

**Issue by d-lapirov** [edgedb/edgedb#5492]
- EdgeDB Version: 2.14+7aec755
- EdgeDB CLI Version: 2.3.1+ef99779
- OS Version: Linux 6.2.12-zen1-1-zen

Steps to Reproduce:

1. `edgedb migration create`
2. accept creation of function
3. see message with failure

```
did you create function 'default::check_my_enum_in'? [y,n,l,c,b,s,q,?]
> y
edgedb error: EdgeDB could not resolve migration with the provided answers. Please retry with different answers.
```

Note that it's actually possible to:
1. get this prompt
2. hit `l` to get the ddl statements
3. hit `s` to create an empty migration
4. paste ddl to create this function in migration
5. successfully apply edited migration

I'm not really sure how the migration process is structured, but I guess that would mean that such arguments are fully supported by the server, but migration tool itself is failing

**Update 1.** I've also tested that is works if you ask for `array<str>`, so it seems like its the problem with possibly only enums.

**Update 2.** It is not possible to request `array<MyStr>` where `MyStr` is defined as `scalar type MyStr extending str;`.
Maybe it's the problem with the custom scalars?

Schema:
```
module default {
  scalar type MyEnum extending enum<option1, option2>;

  function check_my_enum_in(lst: array<MyEnum>) -> bool
    using (true);
}
```

**Comment by Dhghomon** [comment]
I'm not sure when the fix happened but looks like this no longer fails! (Including a function taking an array of MyStr, no errors there either)

```
did you create function 'default::check_my_enum_in'? [y,n,l,c,b,s,q,?]
> y
Created C:\rust\anything\dbschema\migrations\00016.edgeql, id: m1g2qhv4hmwxycfwmootlhv673fg7xixubpwai2rll2xwjearwn5mq
anything:edgedb> \migrate
Applied m1g2qhv4hmwxycfwmootlhv673fg7xixubpwai2rll2xwjearwn5mq (00016.edgeql)
anything:edgedb> select check_my_enum_in([MyEnum.option1]);
{true}
```
