### ISSUE TITLE
Unless conflict fails when inserting a different subtype

### ISSUE THREAD

**Issue by hbriese** [edgedb/edgedb#5498]
- EdgeDB Version: `2.14+7aec755`
- EdgeDB CLI Version: `2.3.1+ef99779`
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Insert SubtypeA
```
insert SubtypeA { name := "abc" }
```

2. Try insert existing the same SubtypeA as a SubtypeB, unless conflict
```
insert SubtypeB { name := "abc" } unless conflict
```

3. Observe bug
`ConstraintViolationError: name violates exclusivity constraint`

It is interesting to note that this query succeeds with `apply_access_policies: false`

Schema:
```
abstract type Base {
  required property name -> str {
    constraint exclusive;
  }
  
type SubtypeA extending Base {
    access policy anyone_can_insert
     allow insert;
}

type SubtypeB extending Base {
    access policy anyone_can_insert
     allow insert;
}
```

**Comment by hbriese** [comment]
> This is by design since you've placed your constraint on the base type. You may want [a delegated constraint](https://www.edgedb.com/easy-edgedb/chapter7#passing-constraints-with-delegated) instead. This would allow you to place the constraint on the base type but it would be applied individually for each extending type allowing you to insert objects with the same name for both subtypes.
> 
> I do see that running the query with `apply_access_policies` set to `false` doesn't produce the constraint error, although it also doesn't insert the object. The query "succeeds" but only in the sense that it doesn't throw. I think maybe we would still like to throw the error in that case. @msullivan?

I want the constraint to be on the base type i.e. only one of either subtype should exist.

I understand your reasoning, but it seems wrong to get an exclusivity constraint error when `unless conflict` is provided.
To be clear, my desired behaviour is the behaviour in the `apply_access_policies: false` case - the object should not be inserted due to the exclusivity constraint, but the statement should not produce an error as `unless conflict` is provided.

**Comment by raddevon** [comment]
@hbriese Ah, yes. Thank you for clarifying.

I think you're right. Seems like `unless conflict` should suppress the error.

**Comment by hbriese** [comment]
Upon further investigation I believe this to actually be a simpler issue: [Unless conflict misbehaves when the caller lacks select access to the object](https://github.com/edgedb/edgedb/issues/5504)

I am closing this issue as the other is simpler to reproduce and better isolates the bug
