### ISSUE TITLE
Always allow bare DDL in notebook protocol

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb#5527]
When running migrations for a local tutorial instance to run alongside a local web site dev server, `allow_bare_ddl` gets set to `NeverAllow`. Ignore this setting for the notebook protocol so that it doesn't block the web site from building.

**Comment by elprans** [comment]
I'm not sure this is a good idea. I think what the local bootstrap script should do is to do what the tutorial Docker script does and run `configure current database set allow_bare_ddl := cfg::AllowBareDDL.AlwaysAllow;` after migrations are applied.
