### ISSUE TITLE
Investigate if error raised with concurrent DDL is retryable (and consider making it retryable if not)

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb#5546]

**Comment by tailhook** [comment]
Looks like it's retryable. Reproduction case.

This is one console:
```
edgedb> start transaction;
OK: START TRANSACTION
edgedb[tx]> create type X;
OK: CREATE TYPE
edgedb[tx]> commit;
OK: COMMIT TRANSACTION
edgedb>
```
This is second one:
```
edgedb> start transaction;
OK: START TRANSACTION
edgedb[tx]> create type Y;
Error: TransactionSerializationError: could not serialize access due to concurrent update
edgedb[tx:failed]>
```

Note the following:
1. `TransactionSerializationError` is retriable
2. Second transaction hangs on `create type Y` until first transaction is commited or rolled back.

**Comment by tailhook** [comment]
The first thing we do, is do `SELECT.. FOR UPDATE` for database version, so I'm pretty confident that this behavior should be consistent.
