### ISSUE TITLE
Named tuples with empty set fields are erroneously completely empty

### ISSUE THREAD

**Issue by lithdew** [edgedb/edgedb#5583]
- EdgeDB Version: 4.0-dev.7515+6f86d18
- EdgeDB CLI Version: EdgeDB CLI 3.0.0-beta.2+97ce8b7
- OS Version: macOS 13.3.1 (22E261)

Steps to Reproduce:

```
edgedb> select (innerIndex := <int64>{});
{}
edgedb> select <tuple<innerIndex: int64>>(innerIndex := <int64>{});
{}
edgedb> select <tuple<innerIndex: int64, test: str>>(innerIndex := <int64>{}, test := "hello");
{}
edgedb> select (<tuple<innerIndex: int64, test: str>>(innerIndex := <int64>{}, test := "hello"));
{}
edgedb> select (test := "hello");
{(test := 'hello')}
edgedb> select (test := "hello", innerIndex := <int64>{});
{}
```

**Comment by elprans** [comment]
This is expected.  "Empty" in EdgeDB is not a value, and so cannot be contained in any other value.  In this regard `(1, <int64>{})` is not different from `1 + <int64>{}`.  If you have optional data, use objects instead.

**Comment by lithdew** [comment]
> This is expected. "Empty" in EdgeDB is not a value, and so cannot be contained in any other value. In this regard `(1, <int64>{})` is not different from `1 + <int64>{}`. If you have optional data, use objects instead.

Would using objects require declaring the type in the schema + how would instantiating a free object instance work?

Or, is this something to be solved via. https://github.com/edgedb/rfcs/blob/master/text/1022-freetypes.rst?

**Comment by elprans** [comment]
Depends on whether data needs to be stored or computed ad-hoc.  In the latter case you can use free shapes.

**Comment by elprans** [comment]
https://www.edgedb.com/docs/edgeql/select#free-objects
