### ISSUE TITLE
Unable to facilitate conditionals without the for loop hack

### ISSUE THREAD

**Issue by avedetvedea** [edgedb/edgedb#5609]
```
with
    selectedUser := (select User limit 1),
    boolean := <bool>$boolean, # or derived in-query
    option1 := (
      selectedUser {
        currentPolls: {
          id,
          ratingPoint,
          selectedIndex,
        }
      }
    ),
    option2 := (
      selectedUser {
        posts: {
          id,
          postType
        }
      }
    ),
select {
  option1 := option1 if boolean else <User>{},
  option2 := option2 if not boolean else <User>{},
}
```

gives `SchemaError: it is illegal to create a type union that causes a computed link 'currentPolls' to mix with other versions of the same link 'currentPolls'`

```
with
    selectedUser := (select User limit 1),
    boolean := <bool>$boolean, # or derived in-query
    option1 := (
      selectedUser {
        _currentPolls := .currentPolls {
          id,
          ratingPoint,
          selectedIndex,
        }
      }
    ),
    option2 := (
      selectedUser {
        _posts := .posts {
          id,
          postType
        }
      }
    ),
select {
  option1 := option1 if boolean else <User>{},
  option2 := option2 if not boolean else <User>{},
}
```

gives `[
  {
    "option1": null,
    "option2": {
      "id": "ed46cb88-d189-11ed-9abc-7f176e38926c"
    }
  }
]` (shape is lost)

and 
```
with
    selectedUser := (select User limit 1),
    boolean := <bool>$boolean, # or derived in-query
    option1 := (
      selectedUser {
        _currentPolls := .currentPolls {
          id,
          ratingPoint,
          selectedIndex,
        }
      }
    ),
    option2 := (
      selectedUser {
        _posts := .posts {
          id,
          postType
        }
      }
    ),
select {
  option1 := option1 {
    currentPolls: {
      id,
      ratingPoint,
      selectedIndex,
    }
  } if boolean else <User>{},
  option2 := option2 {
    posts: {
      id,
      postType,
    }
  } if not boolean else <User>{},
}
```

gives `SchemaError: it is illegal to create a type union that causes a computed link 'currentPolls' to mix with other versions of the same link 'currentPolls'`

I am really sick of using the for-loop hack everywhere. Am I doing something wrong? My working solution

```
with
    old := <bool>$old, # or derived in-query
    new1 := (for _ in (select () filter old) union (
      select (select User limit 1) {
        currentPolls := (select .currentPolls {
          id,
          ratingPoint,
          selectedIndex,
        })
      }
    )),
    new2 := (for _ in (select () filter not old) union (
      select (select User limit 1) {
        posts := (select .posts {
          id,
          postType
        })
      }
    )),
select {
  old := old,
  currentPolls := new1.currentPolls {
    id,
    ratingPoint,
    selectedIndex,
  },
  posts := new2.posts {
    id,
    postType
  },
}
```

which gives 
```
[{
  "id": "1bde3c78-ef59-11ed-b23b-b397d47286ee",
  "ratingPoint": null,
  "selectedIndex": 2
}, {
  "id": "1cb13fec-ef59-11ed-b23b-fbe64321188e",
  "ratingPoint": null,
  "selectedIndex": 0
}]
```
...

**Comment by avedetvedea** [comment]
(by the way I think the UI's parsing is once again wrong, as we would be getting an empty array and not null - TS type generation agrees)

**Comment by msullivan** [comment]
Instead of `option1 if boolean else <User>{}`, try `select option1 filter boolean`?

**Comment by avedetvedea** [comment]
@msullivan Thanks, that works. Also, is there any reason why I have to re-specify the shape again in the end when selecting, even though I did specify it in the `with` clause? i.e., why the shape is lost? 
(this is also really problematic working with `group`s and I _think_ I filed something about it - I often need to trial error on how to get the shape I want between `with` and main `select` which is unsustainable)

**Comment by msullivan** [comment]
Because only the final output shape determines what actually gets output to users. I probably just wouldn't specify shapes in the WITH except when adding computeds that you need to use later

**Comment by avedetvedea** [comment]
I thought that would create an inefficiency but `analyze` shows that the compiler is smart enough to detect that only some columns were initially selected with `with`. 

My problem was that it does slice the columns, they are just hidden; I can access it with correct path, so found it unintuitive. So what if as you said when I do use that `with` clause member in multiples places in the `with` or the final `select`; doesn't re-selecting them on the final `select` feels unintuitive?
