### ISSUE TITLE
invoke `@edgedb/generate` on `edgedb watch` change

### ISSUE THREAD

**Issue by ssendev** [edgedb/edgedb#5640]
It would be nice to have an option to let `edgedb watch` run the edgedb generator when schema changes were applied.

A simple implementation would be to add a flag which specifies a command to run
```sh
edgedb watch --execute "npx run @edgedb/generate edgeql-js"
```

**Comment by PastelStoic** [comment]
This belongs in the edgedb-js repo, not the db itself.

**Comment by ssendev** [comment]
Seeing tat there are multiple repositories i would put this in edgedb-cli.

**Comment by ssendev** [comment]
Duplicate of https://github.com/edgedb/edgedb-cli/issues/1099
