### ISSUE TITLE
Cannot create tuple of objects

### ISSUE THREAD

**Issue by tetotechy** [edgedb/edgedb#5689]
- EdgeDB Version: EdgeDB 3.0+7d903be
- EdgeDB CLI Version: EdgeDB CLI 3.3.0+3f6a0a0
- OS Version: MacOS Ventura 13.4

Steps to Reproduce:

1. .esdl file partial content:
```
   type Country {
      required code: str {
         constraint exclusive;
      }
      name: str;
   }

   type Team {
      required name: str;
      required country: Country;

      constraint exclusive on ((.name, .country));
   }

   type Pairing {
      required pairing: tuple<Team, Team>;
   }
```
2.
```
error: invalid property type: expected a scalar type, or a scalar collection, got collection 'tuple<default::Team, default::Team>'
```

**Comment by elprans** [comment]
That's expected.  EdgeDB cannot (currently) provide referential integrity for references stored in collections (e.g. arrays, tuples), so such usage is disallowed.  Use regular links instead, e.g:

```
type Pairing {
  required x: Team;
  required y: Team;
}
```

**Comment by tetotechy** [comment]
Thanks for clarifying, then it might be the case that the website docs are a bit on the overpromising side. See for instance [here](https://www.edgedb.com/docs/datamodel/primitives#tuples) and [here](https://www.edgedb.com/docs/edgeql/literals#ref-eql-literal-tuple) and [here](https://www.edgedb.com/docs/stdlib/tuple#type-syntax). GPT also gave me this answer:

![image](https://github.com/edgedb/edgedb/assets/3603600/e9565c64-ebca-433a-86a4-a5c52c123255)

Same docs looks consistent with your answer afa _arrays_ are concerned.

In any case, looking forward to it!

**Comment by elprans** [comment]
As far as I can see, the docs are correct: you can use tuples/arrays of _scalars_, but not objects.  As for GPT, it's an imperfect technology, unfortunately.  Please use the thumbs down feedback button when you think the answer is bad, as we continue to tune the embeddings.

**Comment by tetotechy** [comment]
mmmhhh... not sure I agree here. not a big deal @elprans, but the wording is pretty straightforward: "... Tuple elements can be **any** type, including primitives, **objects,** arrays, and other tuples." GPT might not be a perfect technology (what is...?) but it was probably misled, as I was, by the docs.

I am with you that the examples only show scalars being used, but that is inconsistent with the wording. "Code over English" always, but if wording is a proxy for "Spec", then I cannot agree

anyway, I love your project, I am planning to use it, I am rooting for you guys. docs consistency is important, nevertheless, and a projection of what we users might expect from the code
