### ISSUE TITLE
JSON properties cannot be indexed by pg::gin.

### ISSUE THREAD

**Issue by lithdew** [edgedb/edgedb#5703]
- EdgeDB Version: 3.0
- EdgeDB CLI Version:
- OS Version:

Steps to Reproduce:

https://github.com/edgedb/edgedb/blob/62bbaf17f8f00d2a8980f6a5d4c8090294842146/edb/schema/indexes.py#L67C30-L67C38

`alter type A { create index pg::gist on (.data) };`

```
error: SchemaDefinitionError: index expression (.data) is not of a valid type for the index 'pg::gin'
```

**Comment by msullivan** [comment]
@vpetrovykh could you make sure json is supported by pg::gin?

We should also test that the index actually can get hit; that might require some tweaks too
