### ISSUE TITLE
Fail to connect DB as a client on reboot, unless I ssh into it.

### ISSUE THREAD

**Issue by grvstick** [edgedb/edgedb#5726]
- EdgeDB Version: 3.0+e7d38e9
- EdgeDB CLI Version: 3.3.0+071876c
- OS Version:Ubuntu 22.04.2 LTS  

Steps to Reproduce:

1. On reboot, a tmux bash script runs a python script where it connects to the edgeDB project instance. It can either be a cronjob or system service.
2. Following error is raised. After I connect to the PC via SSH, the python client is able to connect right away.
`[Errno 111] Connection refused
After 255 attempts in 30.1 sec
 Is the server running on host 'localhost' and accepting
TCP/IP connections on port 10700? `

I've looked into the logs by command "edgedb instance logs" and found out the instance won't start until I access via SSH. Any suggestions for resolving this?

**Comment by hongquan** [comment]
When you install EdgeDB in dev mode, the server is started as "local" systemd unit, the service is started when user logging in. But your app starts as "system" systemd unit, it is started before EdgeDB server.
To resolve, run EdgeDB server as system unit.

**Comment by grvstick** [comment]
> When you install EdgeDB in dev mode, the server is started as "local" systemd unit, the service is started when user logging in. But your app starts as "system" systemd unit, it is started before EdgeDB server. To resolve, run EdgeDB server as system unit. How to do: https://www.edgedb.com/docs/guides/deployment/bare_metal

Thanks for the comment! I'm trying as you suggested. Let me get back to this issue after confirming this resolves the case. I think it will take a day or two. Is there any document pointing that "local" instances won't start unless a user is logged in?

**Comment by hongquan** [comment]
There is no document. But you can observe that when running `edgedb project init`. Notice the logging message.

**Comment by grvstick** [comment]
I see the issue resolved by changing into remote instance. Thanks for the help! Think I could close the issue for now
