### ISSUE TITLE
No way to set CORS headers in EdgeDB Cloud

### ISSUE THREAD

**Issue by jquesada2016** [edgedb/edgedb#5755]
This is related to #1230.

The current solution in the linked issue is to put the server behind nginx, or an equivalent, but this doesn't seem to be possible in EdgeDB Cloud.

- EdgeDB Version: N/A
- EdgeDB CLI Version: N/A
- OS Version: N/A

Schema:

**Comment by elprans** [comment]
Cloud instances currently allow all origins, i.e `Access-Control-Allow-Origin: *` is sent by default.  We plan to add more configurability there soon though.

**Comment by jquesada2016** [comment]
@elprans although `Allow-Origin` is set to `*`, CORS is not actually satisfied because preflight checks are rejected by the server.

This is, the preflight with method `OPTIONS` and headers `Access-Control-Request-Method`, `Access-Control-Request-Headers`, and `Origin` responds with a `400` status code and a text response of "expected a GET or a POST request" causing CORS preflight to fail.

**Comment by jquesada2016** [comment]
To add further context, queries for instance information at the `/status/*` endpoints seem to be passing CORS validation. Specifically the endpoint that seems to be failing is `/db/<db-name>/edgeql`

**Comment by jquesada2016** [comment]
@elprans any updates for this issue?

**Comment by msullivan** [comment]
This should be fixed by https://github.com/edgedb/edgedb/pull/6577.
https://github.com/edgedb/edgedb/issues/6655 is open to track making it properly configurable.
