### ISSUE TITLE
Remote Statement Cache

### ISSUE THREAD

**Issue by CarsonF** [edgedb/edgedb#5761]
Currently pg query statements are only [cached in memory](https://github.com/edgedb/edgedb/tree/master/edb%2Fserver%2Fcache).
It would be great to allow a remote cache, like Redis, for production.
This would allow the cache to stay warm between processes, and would be shared across multiple instances for high availability.

I think the only additional concern is if the cache needed to be invalidated on upgrade. Maybe each cached item would need an additional version prop. Or maybe it would be included in the key, so they are just ignored and eventually dropped.

**Comment by Dhghomon** [comment]
A pre-RFC discussion on remote caching has just been created if you'd like to have a look:

https://github.com/edgedb/edgedb/discussions/6567

**Comment by CarsonF** [comment]
It appears now that v5 stores cache within PG?
If this scales horizontally, I'd consider this done.

**Comment by fantix** [comment]
Yes, the query cache is now stored also in the backend Postgres. All tenants sharing the same backend will be able to synchronize their in-memory query cache with the persistent cache maintained in the backend.
