### ISSUE TITLE
Casting error when using optional with select

### ISSUE THREAD

**Issue by Darkle** [edgedb/edgedb#5807]
With the following schema:
```
module default {
  type Post {
    required postId: str;
  };
}

```
Running the following:
```
insert Post{ postId := "post1"};

select <optional Post>Post{*} limit 1;
```
I get an error message of:
```
QueryError: cannot cast object type 'default::Post' to 'default::Post', use `...[IS default::Post]` instead
```

Versions:
- EdgeDB Version:3.1+1f030a7
- EdgeDB CLI Version:3.4.0+160d07d
- OS Version:Debian bullseye

Some (perhaps not relevant) context: https://discord.com/channels/841451783728529451/950503041889628200/1130007847233659010

**Comment by elprans** [comment]
This is expected.  Casts are not valid for object types.  Also, `select Object` is already `optional` because we can never guarantee that there is at least one such object in the database.

**Comment by Darkle** [comment]
Ok, thanks. I'll close this.
