### ISSUE TITLE
edb.errors.InternalServerError: 'NoneType' object has no attribute 'is_single'

### ISSUE THREAD

**Issue by m-usa** [edgedb/edgedb#5808]
```
create type a;
create type b;
with  x := (insert b) insert a;
```
edb.errors.InternalServerError: 'NoneType' object has no attribute 'is_single'

(nightly 4.0-dev.7669+aff1ecb)

**Comment by msullivan** [comment]
Whoops, wish I hadn't missed this issue!
Fixed by https://github.com/edgedb/edgedb/pull/6287
