### ISSUE TITLE
Using type intersection with computed fails with `InternalServerError: can't lookup computable ptrref`

### ISSUE THREAD

**Issue by llJochemll** [edgedb/edgedb#5846]
- EdgeDB Version: 3.2+bb17a05
- EdgeDB CLI Version: 3.5.0-dev.1025+21b3681
- OS Version: Windows 11 (WSL)

Steps to Reproduce:

1. Run the follwing query:
```
select Dog {
  uppername := [is Cat].name_upper
}
```
2. Server returns: `InternalServerError: can't lookup computable ptrref`

Same problem when using a computed link, although it fails with a different error: `InternalServerError: relation "edgedbpub.e6ce820e-2bb9-11ee-90ee-29650b039dc4_t" does not exist`

Schema:
```
module default {
    abstract type Pet {
        name: str;
        property name_upper := std::str_upper(.name);
    }

    type Cat extending Pet {
    }

    type Dog extending Pet {
    }
}
```

**Comment by dnwpark** [comment]
With the schema:
```
module default {
    abstract type Pet {
        name: str;
        property name_upper := std::str_upper(.name);

        link owner: Person;
        link siblings := .owner.<owner;
    }

    type Cat extending Pet {
    }

    type Dog extending Pet {
    }

    type Person;
}
```

And data:
```
insert Person;
insert Dog {name := "d1", owner := (select Person limit 1)};
insert Dog {name := "d1", owner := (select Person limit 1)};
```

**Comment by dnwpark** [comment]
The computed property works now, but computed links still don't.
