### ISSUE TITLE
Standard Ternary Syntax

### ISSUE THREAD

**Issue by CarsonF** [edgedb/edgedb#5871]
Currently the conditional syntax is the pythonic:
```python
yes if condition else no
```
However, python is the only language with this baffling syntax.
It's very foreign to non-python devs, and catches us for a loop since we can't read it left to right.

I'd like to request support for the standard ternary syntax:
```
condition ? yes : no
```
Looking at all of the client languages supported, they all support this syntax other than python (and rust/go which use keywords - still condition first).
So it would be much more natural and dev friendly.

This would also fall inline with EdgeDB's philosophy of syntax over keywords.

Thanks for considering!

**Comment by elprans** [comment]
The advantage of the Pythonic syntax is that it is much better for when you have more than one arm, e.g:

```
foo if cond_1 else
bar if cond_2 else
baz
```

The C-style ternary is much worse for this case.

**Comment by CarsonF** [comment]
```
cond1 ? foo :
cond2 ? bar :
baz
```
What am I missing?

**Comment by avedetvedea** [comment]
@elprans 4 things: 
1- I don't think it's much worse, I think this is still the pytonic inclination of yours
2- this proposes an addition rather than a change, so people can decide which is "much worse"
3- people probably use these without nesting most of the time
4- if https://github.com/edgedb/rfcs/pull/74/files is implemented, the need for these multiple branches may be decreased in 'switch-like' scenarios

**Comment by elprans** [comment]
Sorry guys, addition of new syntax, especially if it duplicates existing functionality, has to clear a fairly high bar. Stylistic preference alone wouldn't cut it.  What we don't want is for EdgeQL to become a hodgepodge of syntax like SQL. 

> What am I missing?

If conditions are non-trivial and have lots of punctuation it would take longer to scan for a list of outcomes.  Also, we tend to prefer keywords for longer constructs. 

Consider:

```
(some_long and complex_condition ?? and_syntax) ? (this_could_be_messy ?? too) :
(more_complexity or (nesting ?? coalescing))    ? other :
default
```

vs

```
(this_could_be_messy ?? too) if (some_long and complex_condition ?? and_syntax) else
other                        if (more_complexity or (nesting ?? coalescing)) else
default
```

**Comment by msullivan** [comment]
Alright we changed our minds and implemented "standard ternary syntax", except the "standard" is "Standard ML" (https://en.wikipedia.org/wiki/Standard_ML). We went with `if <condition> then <then_branch> else <else_branch>`, which is the syntax used by a bunch of functional languages (SML, OCaml, Haskell). See #6074.

The reasoning was:
1. We wanted to support doing DML in conditional statements, and thought that the existing python-style syntax read very badly that way
2. The keywords read nicer to us than ? and :, especially in the sort of DML situations we were thinking about. I think Elvis's concern about scanning punctuation is much less of an issue with `if`/`then`/`else`

So I'm going to close this as "resolved", even though technically it is not.
If people still want C-style ternary, you can open a new issue but I might close it WONTFIX ;)
