### ISSUE TITLE
Rewrite in abstract types possible?

### ISSUE THREAD

**Issue by dvv** [edgedb/edgedb#5883]
- EdgeDB Version: 4.0-dev.7696+eae6d5a
- EdgeDB CLI Version: 3.5.0-dev.1025+fec3413
- OS Version: Linux hp 6.1.39-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 19 Jul 2023 17:58:31 +0000 x86_64 GNU/Linux

Steps to Reproduce:

1. `insert Foo { name := "f1" };`
2. `update Foo set { name := "f1" };`
```
InternalServerError: could not resolve trailing pointer class for (__derived__::__old__)
Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
```

Schema:

```
abstract type Revisable {
  required rev: int32 {
    default := 1;
    # increase revision iff object _really_ changes
    rewrite update using (
      (__old__.rev + 1) if __subject__ != __old__ else __old__.rev
      # NB: also tried the following
      #(__old__.rev + 1) if __subject__{*} != __old__{*} else __old__.rev
      #(__old__.rev + 1) if <json>__subject__{*} != <json>__old__{*} else __old__.rev
      #(__old__.rev + 1) if exists std::assert_distinct({__subject__, __old__}) else __old__.rev
    );
  }
}

type Foo extending Revisable {
  name: str {}
}
```

**Comment by msullivan** [comment]
A few things:
1. There's definitely a bug here, since ISE's are always a bug
2. If the code worked (which it should), it wouldn't do what you want: objects are compared by their `id`s
3. I don't think there is currently a way to do this in the generic way that you want. There is `__specified__`, but it only shows the properties on the actual type the rewrite is defined on, not on the subtype it's operating on. It's a feature we could consider, though. Do you have a lot of no-op updates that make it a bad idea to always update the rev?

**Comment by dvv** [comment]
@msullivan thank you!

1. I see
2. Still I would expect `<json>__subject__{*} != <json>__old__{*}` to work, `__subject__` and `__old__` being the properties of subtype it's operating on. I _personally_ believe it's the least surprise
3. I can stand with always updating rev. The question still how (if somehow) to mimic sql `create or replace trigger _100_on_before_update before update on Bebebe for each row when (new is distinct from old) execute procedure Bububu;`

Shall I expect some update on the subject or just punt on that?

**Comment by aljazerzen** [comment]
I've fixed the ISE, but the remaining question is this:

How to compare two objects of type T by their properties, without knowing the type T?

Also, would you want to compare link values too? And multi properties and multi links?

**Comment by dvv** [comment]
Thank you.

I do not know the internals but I would think that any work defined in abstract/delegated object would be delegated to the end (leaf) object. I do understand it's a vague definition.

Personally I would like to compare by direct properties and direct link values only.

**Comment by aljazerzen** [comment]
What I'm saying is that if you do `__old__ = __subject__`, this would be the same as `__old__.id = __subject__.id` (comparing their identities).

What you'd need is a way to compare their properties, generically.

I'll ask about this on a team call.

**Comment by dvv** [comment]
Aha, I see.

I believe then `__old__{*} != __subject__{*}` is the way to compare objects my way, providing properties are compared by the value and links are compared by their ids. So that the above expression denote _the change to the object itself_.

I wonder how to get the fix in `docker pull edgedb/edgedb` )

**Comment by aljazerzen** [comment]
I've tried that, but as I expected, it still does not work - `std::=` and `std::!=` can compare arbitrary objects, but they will compare them by ids.

---

To get the latest changes, I think you have to wait for 4.2 (which should be out in a week or so) or for us to fix the flaky tests in nightly :sweat:

**Comment by dvv** [comment]
I think the following would do:

```
rewrite update using ((__old__.rev + 1) if exists ((select json_object_unpack(<json>__subject__{*}) except json_object_unpack(<json>__old__{*}))) else __old__.rev);
```

Would be clearer if we had `when` clause for rewrites, too:
```
rewrite update when (
   exists ((select json_object_unpack(<json>__subject__{*}) except json_object_unpack(<json>__old__{*}))
) using (__old__.rev + 1);
```

**Comment by dvv** [comment]
On `std::= !== std::!=`:
What if consider introducing `std::===` or alike to compare not only ids but all direct fields of the arguments?

**Comment by aljazerzen** [comment]
> I think the following would do:

Yup, that would do it. But we cannot say that this is the idiomatic way - ideally there would be `std::===` or `std::eq_properties()`.

**Comment by dvv** [comment]
Aha ^^^ Because such a comparison is very common imo. Kinda sql-ish `(new is distinct from old)` guard in triggers.

**Comment by aljazerzen** [comment]
@dvv we have an old issue for structural comparisons: #5335
