### ISSUE TITLE
Docs claim that we can't cast JSON to tuple

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb#5888]
Our documentation says that JSON cannot be cast to a tuple.

> Unlike other casts to JSON, tuple casts to JSON are not reversible (i.e., it is not possible to cast a JSON value directly into a [tuple](https://www.edgedb.com/docs/stdlib/tuple#type::std::tuple)).

 This holds true in the CLI REPL, but casting _does_ appear to work when querying over HTTP.

- EdgeDB Version: 3.2+44862ed
- EdgeDB CLI Version: 3.4.0+4d95a2c
- OS Version: macOS 13.4.1

Steps to Reproduce:

1. Create new project
2. Migrate schema below
3. Send this query over http:
```bash
curl --data '{"query":"with data := <tuple<a:str,b:str>><json>$data, select data;", "variables":{"data":{"a":"eee","b":"smstr"}}}' --header 'Content-Type: application/json' http://localhost:<port>/db/edgedb/edgeql
```

The output of this query is `{"data":[{"a" : "eee", "b" : "smstr"}]}` which indicates the JSON to tuple cast has succeeded.

Schema:
```
using extension edgeql_http;
module default {
}
```

**Comment by msullivan** [comment]
This is a pure docs error, I think. It should work everywhere, and we have tests. LMK if you find a query that doesn't work!
