### ISSUE TITLE
uuid-ossp optional

### ISSUE THREAD

**Issue by petersamokhin** [edgedb/edgedb#5890]
If you use any managed postgres cluster where you cannot modify the extensions from SQL, you need to create the extension manually before connecting to the DB.

when I did that, I receive an error while trying to start a docker edgedb instance:
```
edb.server.pgcon.errors.BackendError: extension "uuid-ossp" already exists
ERROR: Could not complete instance bootstrap
exited with code 1
```

any chance to update CREATE EXTENSION "uuid-ossp" WITH SCHEMA edgedbext to use if not exists?

```
starting EdgeDB server 3.2+99ce519, built on 2023-07-21T19:07Z from revision b7dc55395 (2023-07-21T01:09Z)
```

**Comment by elprans** [comment]
Are you able to create extensions in a specific Postgres schema or is it some predefined schema?
