### ISSUE TITLE
ISE using named tuple argument

### ISSUE THREAD

**Issue by fantix** [edgedb/edgedb#5905]
- EdgeDB Version: 3.2

Running this script:

```python
import typing
import edgedb


class Cursor(typing.NamedTuple):
    x: int
    y: int


edgedb.create_client().query(
    """
        with c := <tuple<x: int64, y: int64>>$cursor
        select c.x * c.y;
    """,
    cursor=Cursor(x=2, y=3),
)
```

Getting this error:

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    edgedb.create_client().query(
  File "edgedb/abstract.py", line 146, in query
    return self._query(QueryContext(
  File "edgedb/blocking_client.py", line 370, in _query
    return self._iter_coroutine(super()._query(query_context))
  File "edgedb/blocking_client.py", line 359, in _iter_coroutine
    coro.send(None)
  File "edgedb/base_client.py", line 743, in _query
    return await con.raw_query(query_context)
  File "edgedb/blocking_client.py", line 156, in raw_query
    return await super().raw_query(query_context)
  File "edgedb/base_client.py", line 243, in raw_query
    raise e
  File "edgedb/base_client.py", line 238, in raw_query
    return await self._protocol.query(**args)
  File "edgedb/protocol/protocol.pyx", line 594, in query
  File "edgedb/protocol/protocol.pyx", line 559, in execute
  File "edgedb/protocol/protocol.pyx", line 464, in _execute
edgedb.errors.InternalServerError: a column definition list is redundant for a function returning a named composite type
```

With server log:

`Aug 08 10:30:55 host-pc edgedb[18894]: ERROR 18901 2023-08-08T10:30:55.616 postgres: a column definition list is redundant for a function returning a named composite type at character 757`
`Aug 08 10:30:55 host-pc edgedb[18894]: INFO 18901 2023-08-08T10:30:55.616 postgres: WITH  "p~1" AS NOT MATERIALIZED  ( (SELECT (("expr-4~2"."0_value~1", "expr-4~2"."1_value~1"))::edgedbpub."690c5b9e-27fe-11ee-a107-bd421336dea6_t" AS "tuple_value~1" FROM  LATERAL  (SELECT "q~1"."expr~2_value~1" AS "0_value~1", "q~2"."expr~3_value~1" AS "1_value~1" FROM  LATERAL  (SELECT ($1)::int8 AS "expr~2_value~1" ) AS "q~1" CROSS JOIN LATERAL  (SELECT ($2)::int8 AS "expr~3_value~1" ) AS "q~2" ) AS "expr-4~2" )) SELECT "expr-5~2"."expr~5_serialized~1" AS "expr~5_serialized~2" FROM  LATERAL  (SELECT (SELECT "t~1"."tuple_value~1" AS "tuple_value~2" FROM  "p~1" AS "t~1" ) AS "tuple_value~3" ) AS "tuple<x:std|int64, y:std|int64>~2" CROSS JOIN LATERAL  (SELECT (SELECT "0" FROM  unnest(ARRAY["tuple<x:std|int64, y:std|int64>~2"."tuple_value~3"]) AS ("0" int8, "1" int8) ) AS "x_value~1" ) AS "int64_x~2" CROSS JOIN LATERAL  (SELECT (SELECT "1" FROM  unnest(ARRAY["tuple<x:std|int64, y:std|int64>~2"."tuple_value~3"]) AS ("0" int8, "1" int8) ) AS "y_value~1" ) AS "int64_y~2" CROSS JOIN LATERAL  (SELECT ("int64_x~2"."x_value~1" * "int64_y~2"."y_value~1") AS "expr~5_serialized~1" ) AS "expr-5~2" WHERE ("expr-5~2"."expr~5_serialized~1" IS NOT NULL)`

**Comment by msullivan** [comment]
Fixed by #5964
