### ISSUE TITLE
Computed backlink in query results in `edgedb error: ProtocolEncodingError: object data size does not match its shape`

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb#5930]
- EdgeDB Version: 3.2+44862ed
- EdgeDB CLI Version: 3.4.0+4d95a2c
- OS Version: macOS 13.4.1

Steps to Reproduce:

1. Run this query against the schema below:
```
select Person {name, descendants := .<ancestors[is Person]};
```

Schema:
```
module default {
  type Person {
    required name: str;
    multi ancestors: Person;
  }
}
```

**Comment by msullivan** [comment]
```
select schema::Type {name, refs := .<target[is schema::Pointer]};
```
hits it with an empty schema

The issue seems to be that the injected typename isn't getting reported in the type descriptor sent to the client.

This is a 3.x regression, it worked in 2.16. Probably introduced by the big refactors to sertypes.py

**Comment by msullivan** [comment]
Oh, actually, looks like it was introduced by some of the backlink link properties stuff
