### ISSUE TITLE
Module resolution during migration does not resolve default::Object

### ISSUE THREAD

**Issue by usaccounts** [edgedb/edgedb#5952]
EdgeDB Version: 3.2+75dd258
EdgeDB CLI Version: EdgeDB CLI 3.4.0+97cad0e
OS Version: Mac OS 13.0.1 (22A400)

Steps to Reproduce: ```edgedb migration create```

error: type 'default::Object' does not exist

```Schema:
module default {
   type Object {
   }
    type atype {
        obj:default::Object;
    }
}
```
Furthermore, there's positional sensitivity this one resolves obj to std::Object
```module default {
    type atype {
        obj:Object;
    }
   type Object {
   }
}
```
while this one resolves to default::Object:
```module default {
   type Object {
   }
    type atype {
        obj:Object;
    }
}
```

**Comment by msullivan** [comment]
Fixed by https://github.com/edgedb/edgedb/pull/6155
