### ISSUE TITLE
Ability for an extension to depend on other extensions

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#5966]
The upcoming `ext::auth` needs `ext::pgcrypto` to validate authentication tokens, so we need the ability to declare EdgeQL dependencies in extensions.  Unlike current SQL extension dependencies, an EdgeQL dependency should automatically create or upgrade all dependent extensions if they don't exist in the target schema already.

Proper dependency solver is hard, so we can either consider borrowing one from something like Poetry or implementing something basic a-la pre-solver pip.

**Comment by msullivan** [comment]
Done in #6139
