### ISSUE TITLE
`extending` using a new `BaseObject` ended up extending different `BaseObject` types

### ISSUE THREAD

**Issue by mrmntte** [edgedb/edgedb#5972]
- EdgeDB Version: 3.2+bb17a05
- EdgeDB CLI Version: EdgeDB CLI 3.0.0-beta.2+2ce3d4c
- OS Version: Ubuntu-20.04

The Identity type does not extend auth::BaseObject, however the types declared below do.
I think both should extend from auth::BaseObject and if there is a naming conflict within the module with std, I should only be able to refer to the external types with their fully-qualified name.

Schema:
```sql
module auth {
  abstract type BaseObject {}

  type Identity extending BaseObject {
    # this causes the problem
    link user := .<identity[is default::User];
  }

  type IdentityCredential extending BaseObject {}
}

module default {
  type User {
    single link identity: auth::Identity;
  }
}
```

![image](https://github.com/edgedb/edgedb/assets/49642108/f0f87bff-d59a-479e-b2fc-61f02cfe7f14)

**Comment by msullivan** [comment]
Thanks for the report, I think this is the same issue as #5952

**Comment by msullivan** [comment]
And it'll be fixed by https://github.com/edgedb/edgedb/pull/6155
