### ISSUE TITLE
Empty set returned by a function with cardinality one, but not returned by an identical computed expression.

### ISSUE THREAD

**Issue by HamishWHC** [edgedb/edgedb#5979]
- EdgeDB Version: 3.2+44862ed
- EdgeDB CLI Version: 3.4.0+4d95a2c
- OS Version: macOS 13.4.1

Steps to Reproduce:

Setup a database with the below schema.
Run the following query:
```
insert Challenge {
    visibility := "shown"
};
```
Execute the following query (note that `test` is a function identical to the computed's expression):
```
with
  challenge := (select Challenge limit 1),
  user := <User>{},
select {
  func := test(challenge, user),
  comp := (
    (user.is_admin ?? false)
    or (challenge.visibility = "shown")
    or (
      (challenge.visibility = "obfuscated")
      and ((user in challenge.solved_by_users) ?? false)
    )
  )
};
```
I get the following result:
```
{
  "func": null,
  "comp": true
}
```
Given that the expressions in the `test` function and the computed are identical, this doesn't make sense. The `test` function is also has a cardinality that requires a return value.

I have played around with modifying the expression (while keeping the computed and function identical) to find the minimal expression where this issue occurs and have found the following results:

<table>
<tr>
 <td>Expression
 <td>Result
<tr>
 <td>

```
(user.is_admin ?? false)
# or (challenge.visibility = "shown")
or (
  (challenge.visibility = "obfuscated")
  and ((user in challenge.solved_by_users) ?? false)
)
```
 <td>

```
{
  "func": null,
  "comp": false
}
```
<tr>
 <td>

```
# (user.is_admin ?? false)
# or (challenge.visibility = "shown")
# or (
  (challenge.visibility = "obfuscated")
  and ((user in challenge.solved_by_users) ?? false)
# )
```
 <td>

```
{
  "func": false,
  "comp": false
}
```
<tr>
 <td>

```
(user.is_admin ?? false)
# or (challenge.visibility = "shown")
# or (
  # challenge.visibility = "obfuscated"
  # and ((user in challenge.solved_by_users) ?? false)
# )
```
 <td>

```
{
  "func": false,
  "comp": false
}
```
</table>

Schema:
```
module default {
    type User {
        required name: str {
            constraint exclusive;
        }
        required is_admin: bool {
            default := false;
        }
    }

    function test(challenge: Challenge, user: optional User) -> bool
        using (
            (user.is_admin ?? false)
            or (challenge.visibility = "shown")
            or (
                challenge.visibility = "obfuscated"
                and ((user in challenge.solved_by_users) ?? false)
            )
        );

    type Challenge {
        multi link solved_by_users: User;

        required property visibility: str;
    }
}
```

**Comment by HamishWHC** [comment]
Testing further combinations:

<table>
<tr>
 <td>

```
# (user.is_admin ?? false)
# or
(challenge.visibility = "shown")
or (
  challenge.visibility = "obfuscated"
  and ((user in challenge.solved_by_users) ?? false)
)
```
 <td>

```
{
  "func": true,
  "comp": true
}
```
<tr>
 <td>

```
(user.is_admin ?? false)
or (challenge.visibility = "shown")
# or (
#   challenge.visibility = "obfuscated"
#   and ((user in challenge.solved_by_users) ?? false)
# )
```
 <td>

```
{
  "func": true,
  "comp": true
}
```
</table>

It seems to be the combination of the first and last conditions that cause the mismatch.
I have also tried replacing first condition (`(user.is_admin ?? false)`) with a variety of others (while keeping the final condition the same) and have not yet found another condition that causes this issue. I have tried the following (with notes in brackets about what I was testing):

- `1 + 1 = 2` (always true)
- `1 + 1 = 3` (always false)
- `<bool>{} ?? false` (uses coalesce operator)
- `exists user` (interacts with `user`)

This issue is bizarre.

**Comment by msullivan** [comment]
Here's a reduced version:
```
create function test(user: optional Object) -> str using (
    (<str>user.id ?? "") ++ <str>(exists user)
);
```

```
scope> select test(<Object>{});
{}
```

Elvis spotted that the problem is that we are trying to fetch the User from the database at the top level of the function.

I think something is going wrong with the scoping when an optional argument is used both in an OPTIONAL (`??`) and a SET OF argument (`IN` in the original, `EXISTS` in my minimized version)

**Comment by msullivan** [comment]
I can produce the issue without a function too:
```
edgedb> with user := array_unpack(<array<Object>>[])
....... select
.......     (<str>user.id ?? "") ++ <str>(exists user)
....... ;
{}
```

The issue is the same: when we `ensure_source_rvar`, it gets joined unconditionally, instead of using optional wrapping

**Comment by msullivan** [comment]
It doesn't need to be an optional and a set of; having references in two separate optional arguments fails too:
```
scope> with c := array_unpack(<array<Card>>[])
...... select (c.name ?= c.element);
[]
```
