### ISSUE TITLE
WITH bound variables in aliases create views that don't get deleted

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#5987]
1. Use the branch in #5977 (`auth-jwt` branch)
2. Add extensions (`create extension pgcrypto; create extension auth;`)
3. Attempt to drop `auth` (`drop extension auth;`).

I'm getting:

```
edgedb error: SchemaError: cannot drop module 'ext::auth' because it is not empty
```

I suspect this is due to aliases in the `auth` schema.

**Comment by msullivan** [comment]
Definitely a alias issue; not actually related to extensions even, I think.
```
type X;
alias Z := (with lol := X, count(lol));
```
Trying to migrate that schema to empty fails.
