### ISSUE TITLE
Can't find materialized set in volatile with+for+insert

### ISSUE THREAD

**Issue by vwkd** [edgedb/edgedb#6024]
## Problem

I'm trying to run an insert query a random number of times for every element in a list.

But I got the error

```
InternalServerError: Can't find materialized set ns~5@@(__derived__::random_value@w~4)
```

- EdgeDB Version: 3.2+75dd258
- EdgeDB CLI Version: EdgeDB CLI 3.4.0+97cad0e
- OS Version: macOS 12.6.7

## Steps to Reproduce

1. Insert movies

```edgeql
for movie_name in {"Foo", "Bar", "Baz"}
union (
  insert Movie {
    name := movie_name,
  }
);
```

2. Run query

```edgeql
for movie_name in {"Foo", "Bar", "Baz"}
union (
  with
    min := 5,
    max := 10,
    random_value := min + <int64>std::round((max - min) * std::random()),
  for _ in range_unpack(range(0, random_value))
  union (
    insert WatchHistory {
      movie := (select Movie filter .name = movie_name),
    }
  )
);
```

## Schema

```
type Movie {
  required name: str;
}

type WatchHistory {
  required movie: Movie;
}
```

**Comment by msullivan** [comment]
This is more-or-less an effect of https://github.com/edgedb/edgedb/issues/2809

**Comment by dnwpark** [comment]
Should work now, though the original query may need cardinality constraints for `WatchHistory.movie`
