### ISSUE TITLE
Error in the tutorial

### ISSUE THREAD

**Issue by sfermigier** [edgedb/edgedb#612]
When running the tutorial, after inserting the Blade Runner 2049 movie, I get an error when I insert the Dune movie:

```
tutorial> INSERT Movie {
.........     title := 'Dune',
.........     director := (
.........         SELECT Person
.........         FILTER
.........             # the last name is sufficient
.........             # to identify the right person
.........             .last_name = 'Villeneuve'
.........     )
......... };
MissingRequiredError: missing value for required link default::Movie.cast
```

**Comment by 1st1** [comment]
Yeah, we need to fix the tutorial, thank you for reporting this!

Here's a query that should work:

```
INSERT Movie {
    title := 'Dune',
    director := (
        SELECT Person
        FILTER
            .last_name = 'Villeneuve'
    ),
    cast := (
        SELECT Person
        FILTER
            .last_name = 'Gosling'
    )
};
```

**Comment by 1st1** [comment]
I've updated the tutorial.  The proper fix is to make the "cast" link optional for Movies. https://github.com/edgedb/edgedb/commit/aa8818f6f4d9c1f54b61583880383c99dba708e3

Closing this one. Thank you for reporting issues and trying out EdgeDB!
