### ISSUE TITLE
Is it possible to run EdgeDB on CitusData or TimescaleDB

### ISSUE THREAD

**Issue by sirex** [edgedb/edgedb#614]
Very interesting project! Is PostgreSQL a hard dependency for EdgeDB, is it possible to use it with CitusData or TimescaleDB?

**Comment by elprans** [comment]
Both are PostgreSQL extensions, so it’s technically possible.

**Comment by rongfengliang** [comment]
@sirex i do some test it works . by the way need  install  timescaledb_11 for pg11

**Comment by 1st1** [comment]
While it's technically possible we don't plan to work on that in the foreseeable future (no capacity), so I'm closing this one.
