### ISSUE TITLE
How to import/use .esdl file

### ISSUE THREAD

**Issue by ansarizafar** [edgedb/edgedb#618]
> Each .esdl file represents a complete schema state for a particular module.
https://edgedb.com/docs/edgeql/sdl/index

I want to use .esdl file to define my schema but how can I import/use an ,esdl file to update schema in my database?

**Comment by elprans** [comment]
@ansarizafar The example on the documentation page you linked shows how to do this.

**Comment by vpetrovykh** [comment]
To clarify, @ansarizafar, if you were wondering whether there's a tool/command that would take the `.esdl` *filename* and migrate the database to that state, then currently we don't have any such tool. For the moment you'd have to copy the contents of that file into the `CREATE MIGRATION foo TO {...}` command.

We have plans for this kind of tool, which would allow to manage your schema in the form of `.esdl` files.

**Comment by ansarizafar** [comment]
@vpetrovykh Thanks for the clarification.

**Comment by tslocke** [comment]
In case anyone ended up here like me, here's a very basic but working node.js script to load an esdl file and migrate to that schema:

```
const edgedb = require("edgedb")
const fs = require("fs")

const SCHEMA_FILE = "db/schema.esdl"

async function main() {
  const conn = await edgedb.connect({ 
    dsn: "edgedb://edgedb@localhost/YOUR_DB",
    user: "YOUR_USER",
    password: "YOUR_PW" 
  })
  
  const schema = fs.readFileSync(SCHEMA_FILE, "utf8")

  try {
    await conn.execute(`
      START TRANSACTION;
      CREATE MIGRATION m TO {
        ${schema}
      };
      COMMIT MIGRATION m;
      COMMIT;
    `)
  } catch (e) {
    console.error(e.message)
    process.exit(1)
  }
  process.exit(0)
}

main()
```

Haven't been able to figure out how to retrieve the line number of syntax errors :(

**Comment by 1st1** [comment]
We need to start covering this in the docs (even before we build schema-reflection language tooling)

**Comment by d4h0** [comment]
I might miss something, but I believe this issue can be closed. The `edgedb migration *` CLI commands seem to handle what was asked for in this issue.

Btw., I was looking for a way to import a schema module into another schema module (similar to `with module my_module` in queries) – this feature doesn't exist, right?
