### ISSUE TITLE
InternalServerError on long enum labels

### ISSUE THREAD

**Issue by linaouro** [edgedb/edgedb#6186]
- EdgeDB Version: '3.1+1f030a7'
- EdgeDB CLI Version: EdgeDB CLI 3.5.0+907ff37
- OS Version: Ubuntu 20.04.5 LTS (Focal Fossa)

Steps to Reproduce:

1. Declare a scalar type extending enum which contains a value that is 65 characters long
2. Create migration
3. Apply migration
```
 `edgedb error: InternalServerError: invalid enum label`

**Comment by elprans** [comment]
This is a Postgres limitation, I believe, but we ought to produce a nicer error of course.
