### ISSUE TITLE
Sharing Types between multiple database in the same instance. E.g. share Type User across all databases

### ISSUE THREAD

**Issue by ICTServ** [edgedb/edgedb#6220]
I'm using multiple database in one instance, dbA and dbB. I want all other database share dbA types. E.g. Type User in dbA needs to be shared across all databases. 

**SCHEMA**
dbschema
 ┣ dbA
 ┃ ┗ dbA.esdl
 ┣ dbB
 ┃ ┗ dbB.esdl

module dbA { 
  type User { 
       # properties...
    }; 
} 

module dbB { 
  type Customer { 
          # properties... 
     }; 
} 

**PROBLEM** 
 How can I link "type Customer" in a database "dbB" to type User in a database "dbA"? 

**TRIED**
module dbB { 
    type Customer { 
            user: dbA::User; 
      }
} 
This will work only when the database is the same. Otherwise I get the following error.
error: type 'dbA::User' does not exist"

How can I solve this problem?

**Comment by msullivan** [comment]
We don't support this, and I'm not totally sure what benefit you'd get from splitting things into multiple databases on one instance.

If you are set on doing this, though, what you could do is to just reference the `id` of the user from the other database. So, `user_id: uuid`. 
You'd need to fetch the user information via a separate query to the other database, though, and you wouldn't be able to mutate things transactionally, and you wouldn't have any validation that the target id exists and doesn't get deleted.
