### ISSUE TITLE
Cardinality of polymorphic shape field isn't optional

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb#6254]
**Describe the bug**
Polymorphic EdgeQL query where a string field may not be present is inferred as `string`

**Reproduction**
Schema
```
type Message {}
type SlackMultiUserMessage extending Message {
  slackDisplayName: str;
}
```
edgeql query file
```
select Message {
  *,
  [is SlackMultiUserMessage].slackDisplayName
}
```
Generated TS
```typescript
export type TestReturns = {
  "slackDisplayName": string;
  "id": string;
}[];
```

**Expected behavior**
`slackDisplayName` would be optional.

**Versions (please complete the following information):**

- OS: macos 13.5
- EdgeDB version: 3.3
- EdgeDB CLI version : 3.5.0
- `edgedb-js` version :  "edgedb": "^1.3.6", "@edgedb/generate": "^0.3.3",
- Node/Deno version: 18.16.0

**Comment by msullivan** [comment]
It is a bug in edgedb's card inference
