### ISSUE TITLE
Document how to uninstall on macOS

### ISSUE THREAD

**Issue by gwk** [edgedb/edgedb#630]
I installed the EdgeDB alpha for macOS sometime after it was announced. I never actually ran it, but I just looked at Activity Monitor and see that the `prostgres` process running under user `edgedb` has both sent and received 18.5MB of data, presumably since my last restart which was only a couple of days ago.

This violates my basic expectations about software installation. Please tell me how I can completely remove edgedb from my machine. Furthermore, I would like to know what edgedb has been sending, and where.

**Comment by elprans** [comment]
> I installed the EdgeDB alpha for macOS sometime after it was announced.

Thanks for trying it out!

> This violates my basic expectations about software installation.

Unfortunately, Apple does not seem to provide a standard way of uninstalling packages installed with Installer.app.  We are working on a custom installer/uninstaller tool for the next release.

> Please tell me how I can completely remove edgedb from my machine. 

The following is sufficient to remove EdgeDB installed using the *.pkg installer:

```shell
sudo launchctl bootout system /Library/LaunchDaemons/com.edgedb.edgedb-1-alpha1.plist
sudo rm -rf /Library/Frameworks/EdgeDB.framework/
sudo rm -rf /var/lib/edgedb/
sudo rm -rf /etc/paths.d/com.edgedb.edgedb
```

> Furthermore, I would like to know what edgedb has been sending, and where.

EdgeDB uses network sockets for interprocess comunication (there are multiple processes coordinating).  It does not send anything anywhere by itself otherwise.

**Comment by gwk** [comment]
Thank you for the explanation, and the instructions. Best of luck with the project!

**Comment by isidentical** [comment]
Hey @elprans! Is there a Linux version of the commands you gave as an example. I want to remove everything (like literally, if it is possible postgresql itself) and have the latest version on a clean installation? (my system is just messed up with tons of different versions, half upgrades etc)

**Comment by elprans** [comment]
@isidentical, which distro are you on?

**Comment by isidentical** [comment]
@elprans ubuntu 20

**Comment by elprans** [comment]
This should do the trick:

```
systemctl --user stop edgedb*.service
rm -rf $HOME/.local/share/edgedb
rm -rf $HOME/.edgedb
sudo apt-get remove 'edgedb*'
```

Probably also worth rebooting in case some processes are still up.

**Comment by isidentical** [comment]
Thanks
