### ISSUE TITLE
Graphql and Edgeql port is consuming too much memory

### ISSUE THREAD

**Issue by ansarizafar** [edgedb/edgedb#631]
Without Graphql or Edgeql, EdgeDB uses around 382MB but If I set up GraphQL or Edgeql access to the database by using the following command then EdgeDB uses around 382MB + (300MB * Nos of connections  (300MB per conection).

```
CONFIGURE SYSTEM INSERT Port {
    protocol := "graphql+http", OR "edgeql+http"
    database := "tutorial",
    address := "127.0.0.1",
    port := 8888,
    user := "http",
    concurrency := 1,
};
```
Why Graphql/Edgeql is using so much memory? Grapgql queries are also a bit faster then Edgeql queries, If you send the same query again.

 If I send a filter query with Edgeql which should return empty set then I get an errror. 

![image](https://user-images.githubusercontent.com/5788284/56726519-59a8b880-6768-11e9-83d9-14ac86ddf8d2.png)

The same query in Edgedb client is returning correct result.

![image](https://user-images.githubusercontent.com/5788284/56726713-c02dd680-6768-11e9-9feb-24381d812dcd.png)

**Comment by 1st1** [comment]
> Why Graphql/Edgeql is using so much memory?

In the current implementation, `concurrency=N` translates to `N` python processes and `N` Postgres processes.  Python processes are rather heavy, but there're many different ways of optimizing that.  We'll be focuses on that once EdgeDB hits beta.

> Grapgql queries are also a bit faster then Edgeql queries, If you send the same query again.

When an EdgeQL or GraphQL query is compiled it is cached.  If you the send the same query over and over again it will hit that cache and the compilation will be avoided.  The mechanism is the same, so I'm surprised you see a difference between EdgeQL and GraphQL here.

> If I send a filter query with Edgeql which should return empty set then I get an errror.

This is very interesting.  Can you replicate this if you switch to JSON mode in the REPL (press the F3 key to switch)?

**Comment by ansarizafar** [comment]
Here is the result of the same query with JSON mode on in the REPL

![image](https://user-images.githubusercontent.com/5788284/56747026-b4f19f80-6796-11e9-8932-ac89d9274e59.png)

**Comment by 1st1** [comment]
Alright, this means that GraphQL compiles the query in some surprising way. @vpetrovykh please take a look.

**Comment by 1st1** [comment]
I've just fixed it in https://github.com/edgedb/edgedb/commit/f4d27bab225d061ab258bd1c1bbd1352eb2dd5ae.  We're thinking about releasing an updated version in a couple of days as this is a pretty serious bug.

**Comment by ansarizafar** [comment]
Ok. Thanks for the quick fix. I hope this feature https://github.com/edgedb/edgedb/issues/528 with permission system will land soon.
