### ISSUE TITLE
Improve backtick quoting

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#632]
Currently backticks themselves cannot be used inside a backtick-quoted identifier. The proposal is to use double backticks to mean a single backtick character in the identifier:

```edgeql
SELECT `a ``quoted`` identifier`;
```

Also, the error message for starting a quoted identifier with an `@` should be more user-friendly, like "identifiers cannot start with '@'"

**Comment by Sija** [comment]
> The proposal is to use double backticks to mean a single backtick character in the identifier:

I'd suggest more popular backslash (`\`) character.
