### ISSUE TITLE
Schema types introspection is broken for required and default values.

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#634]
Currently if a schema type has a required link or property it can still show up as `{}` in the introspection. Similarly, default values are also ignored.

See #633 for tests that show this behavior.

Incidentally, we may want to review what is required in the schema. For example, why is `__type__` not a required link? Why `is_abstract` and `is_final` have a default, but aren't required? Also `readonly` should be exposed.

**Comment by 1st1** [comment]
@vpetrovykh is this still the case?

**Comment by elprans** [comment]
This is fixed.
