### ISSUE TITLE
contains() for json doesn't work when casting to <json>

### ISSUE THREAD

**Issue by Dhghomon** [edgedb/edgedb#6363]
(Context: contains() for json has been added to 4.0 and am writing documentation for it)

I think this is a bug, if not then will be a note to add to the documentation to explain the behaviour.

- EdgeDB Version: 4.0-beta.1+0f54951'
- EdgeDB CLI Version: 3.5.0+40f966d
- OS Version: Windows 11

Steps to Reproduce:

```
edgedb> with str1 := '{"Hi": "Bye", "One": "Two"}',
....... str2 := '{"Hi": "Bye"}',
....... select {
....... contains(to_json(str1), to_json(str2)),
....... contains(<json>str1, <json>str2)
....... };
{true, false}
```

I see the two jsons generated from the strings aren't quite equivalent to each other and a to_json(string) and a `<json>`string will display differently:

```
edgedb> with str1 := '{"Hi": "Bye", "One": "Two"}',
....... str2 := '{"Hi": "Bye"}',
....... select
....... { to_json(str1), <json>str1 };
{
  Json("{\"Hi\": \"Bye\", \"One\": \"Two\"}"),
  Json("\"{\\\"Hi\\\": \\\"Bye\\\", \\\"One\\\": \\\"Two\\\"}\""),
}
```

**Comment by msullivan** [comment]
> I see the two jsons generated from the strings aren't quite equivalent to each other and a to_json(string) and a `<json>`string will display differently:
> 
> ```
> edgedb> with str1 := '{"Hi": "Bye", "One": "Two"}',
> ....... str2 := '{"Hi": "Bye"}',
> ....... select
> ....... { to_json(str1), <json>str1 };
> {
>   Json("{\"Hi\": \"Bye\", \"One\": \"Two\"}"),
>   Json("\"{\\\"Hi\\\": \\\"Bye\\\", \\\"One\\\": \\\"Two\\\"}\""),
> }
> ```

Yes, casting a string to json produces a json object that is a json-string.
It doesn't parse the string as json, which is what `to_json` does.

This all seems to be working as intended?
