### ISSUE TITLE
Using splat in coalescing operator don't return all expected properties.

### ISSUE THREAD

**Issue by AnsonHwang86** [edgedb/edgedb#6372]
- EdgeDB Version:4.0-rc.1+fd5ed53

Steps to Reproduce:

1.Just run following edgedql against example movie database.
```
select (select Movie filter .title = "Ant-Man2")??(insert Movie{title:="Ant-Man2"}){*}
```
Then it will return only id property
![image](https://github.com/edgedb/edgedb/assets/16233397/f3ee4f84-4e68-4265-b741-fadbad2e0c90)

If I specify the properties 
```
select (select Movie filter .title = "Ant-Man2")??(insert Movie{title:="Ant-Man2"}){id,title}
```
The result would be the same.

And I will add more `*`
```
```
select (select Movie filter .title = "Ant-Man2")??(insert Movie{title:="Ant-Man2"}){**}
```
It will throw an error
![image](https://github.com/edgedb/edgedb/assets/16233397/07f7ba48-00fd-4276-95b6-6650d81ef518)

**Comment by elprans** [comment]
This is due to shape operator associativity, it is associated with the right operand of coalesce, not the entire coalesce expression.  Put extra parentheses around it:

```
select ((select Movie filter .title = "Ant-Man2")??(insert Movie{title:="Ant-Man2"})){*}
```

**Comment by AnsonHwang86** [comment]
Yes, it worked. Thanks. I will close this issue.
