### ISSUE TITLE
Document 4.0 trigger changes

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb#6416]
Looks like `when` was added to the syntax on the [DDL](https://www.edgedb.com/docs/reference/ddl/triggers#triggers)/[SDL](https://www.edgedb.com/docs/reference/sdl/triggers#ref-eql-sdl-triggers-syntax) reference pages, but there are a few problems:

- `when` is visible in the syntax even when I switch back to v3 in the docs. If this had been backported to v3, the addition of `when` wouldn't be in the 4.0 changelog, so I think it's incorrect to show it in the syntax when switching the version selector to v3.
- The function of `when` is not described in the "Description" on [the SDL reference page](https://www.edgedb.com/docs/reference/sdl/triggers#ref-eql-sdl-triggers-syntax).
- Might be good to add a `when` to the example on these pages (although only for v4)
- We probably need mention and maybe an example of `when` on [the Schema > Triggers page](https://www.edgedb.com/docs/datamodel/triggers#triggers) (behind a `versionadded:: 4.0` directive).

**Comment by raddevon** [comment]
@msullivan Can you confirm whether conditional triggers was backported?

**Comment by raddevon** [comment]
or maybe @aljazerzen can confirm?

**Comment by aljazerzen** [comment]
Conditional triggers (PR #6184) are in 4.x, but not in 3.x
