### ISSUE TITLE
Plans for Golang driver?

### ISSUE THREAD

**Issue by koddr** [edgedb/edgedb#643]
Hello! And thanks for EdgeDB.

Simple question: would your have any plans about Golang driver?
I know, officially "EdgeDB love Python", but..

Roadmap for other programming languages — would be great. 👍

**Comment by andriisoldatenko** [comment]
it's work in progress :)

**Comment by nkev** [comment]
It would be interesting to know what the performance increase would be if EdgeDB was ported to Go

**Comment by elprans** [comment]
Most performance-critical parts of EdgeDB are actually written in C (or transpiled to C), so it's already quite fine on the fast path.  Here are some benchmarks: https://edgedb.com/blog/edgedb-1-0-alpha-1/#benchmarks

There is room for improvement, and a partial rewrite to a systems language is something we might consider.

**Comment by nkev** [comment]
Cool. Thank you for the explanation.

**Comment by ansarizafar** [comment]
> There is room for improvement, and a partial rewrite to a systems language is something we might consider.

Edgedb is an amazing project and Edgeql is a game changer. The project is in alpha stage and I am sure memory/cpu usage will improve but I in my opinion partial/full rewrite to a systems language is absolutely necessary for efficient use of memory/cpu. Python process are heavy and currently, Edgedb is consuming around 400mb for database service, 100mb for repl and 400mb of ram for each http (Edgeql/Graphql) connection.

**Comment by OhBonsai** [comment]
> it's work in progress :)

Show us the code ^_^

**Comment by tredoe** [comment]
> > There is room for improvement, and a partial rewrite to a systems language is something we might consider.
> 
> Edgedb is an amazing project and Edgeql is a game changer. The project is in alpha stage and I am sure memory/cpu usage will improve but I in my opinion partial/full rewrite to a systems language is absolutely necessary for efficient use of memory/cpu. Python process are heavy and currently, Edgedb is consuming around 400mb for database service, 100mb for repl and 400mb of ram for each http (Edgeql/Graphql) connection.

At the first, I got excited about the project until I found out that Python was the language chosen, which is strange since there are languages like Rust or Go nowadays.

**Comment by elprans** [comment]
> At the first, I got excited about the project until I found out that Python was the language chosen, which is strange since there are languages like Rust or Go nowadays for a task like this

The EdgeDB codebase predates both Rust and Go.  All performance-critical paths are written in C or Cython and we are working on making parts of the system to be more amenable to a progressive rewrite in Rust, so don't get discouraged at the sight of Python :-)  Also, here are some early perf benchmarks: https://edgedb.com/blog/edgedb-1-0-alpha-1/#benchmarks

**Comment by ansarizafar** [comment]
Is there any new update regarding Go Driver?

**Comment by elprans** [comment]
@ansarizafar Not yet, unfortunately. Alpha 2 will see the release of a NodeJS binding, and there's early work on the Rust driver.  Golang binding is next in queue, we expect to start working on it early next year.

By the way, the protocol is fully [documented](https://github.com/edgedb/edgedb/tree/master/docs/internals/protocol), and there are two complete implementations of the protocol ([Python](https://github.com/edgedb/edgedb-python) and [JavaScript](https://github.com/edgedb/edgedb-js)) to draw inspiration from, so if anyone wants to make Golang (or any other platform) happen sooner, please feel free to contribute!

**Comment by fmoor** [comment]
There is now an official Go driver for edgedb :tada: 
More information can be found at the links below.

https://www.edgedb.com/blog/edgedb-1-0-beta-1-sirius/#a-new-first-party-database-client-for-go
https://pkg.go.dev/github.com/edgedb/edgedb-go

**Comment by maaft** [comment]
> There is now an official Go driver for edgedb
sorry, but this is a client not a driver, right?
How does this solve server-side issues with python?

**Comment by elprans** [comment]
> Sorry, but this is a client not a driver, right?

A client and a driver are synonyms here, meaning the same thing.

> How does this solve the mentioned server-side issues with python?

What issues specifically?
