### ISSUE TITLE
Expose if a property is marked as secret in introspection

### ISSUE THREAD

**Issue by jaclarke** [edgedb/edgedb#6444]
Some properties are marked as secret in the auth ext schema, and cause an error to be thrown if you try to query them. It would be useful if whether a property is secret was exposed in schema introspection, so that the UI could omit these properties when querying data for the data view. (See https://github.com/edgedb/edgedb-ui/issues/282)

**Comment by msullivan** [comment]
Fixing this for nightly/5.0 should be trivial, but backporting it to 4.0 would require writing some new patching infrastructure (doable, but probably not worth it).

So we can fix this, but for now I think you should just hardcode it in the UI somehow :(
