### ISSUE TITLE
`password` CLI option and ENV variable don't work

### ISSUE THREAD

**Issue by jsimonlane** [edgedb/edgedb#6454]
Basically, `password` doesn't work properly in the CLI.

- EdgeDB Version: "3.3+d5734dd"
- EdgeDB CLI Version: EdgeDB CLI 4.0.2+500be79
- OS Version: MacOS 13.3.1 (a)

Steps to Reproduce:

1. Make a new edgedb instance
2. Set an edgedb password -- the below script sets it to "your_new_password"
3. Unfortunately:
  * The EDGEDB_PASSWORD env variable doesn't work
  * the `--password` option doesn't actually take arguments. Ie, I have to hit `--password` and type it in every time, instead of saying `--password "your_new_password"`

```bash
# Clones a repo into a new instance

PROJECT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" && git rev-parse --show-toplevel)

# Variables
SCHEMA_PATH="$PROJECT_ROOT/dbschema/"
INSTANCE_NAME="intergration_tests"
VERSION="3.5"

echo $SCHEMA_PATH

# 1. Delete the db instance, if it exists... we want to start fresh.
if edgedb instance list | grep -q $INSTANCE_NAME; then
  echo "Deleting existing database instance: $INSTANCE_NAME"
  # TODO: include a `--version` flag
  edgedb instance destroy --force -I $INSTANCE_NAME 
else
  echo "Database instance $INSTANCE_NAME does not exist. Moving on to creation."
fi

# 2. Create a db instance, using the most up-to-date schema available.
# Note: EdgeDB creation, and project linking, are different things.
echo "Creating database instance: $INSTANCE_NAME with version $VERSION"
edgedb instance create $INSTANCE_NAME  --non-interactive --version $VERSION

# 3. Optionally, we also introduce test data in there here.
# Replace /path/to/schema.esdl with the path to your schema file.
echo "Loading schema into $INSTANCE_NAME"
edgedb -I $INSTANCE_NAME migrate --schema-dir=$SCHEMA_PATH --instance=$INSTANCE_NAME

# Set the password, do this last because it makes everything else painful.
edgedb -I $INSTANCE_NAME query "ALTER ROLE edgedb { SET password := 'your_new_password'; }"
```

**Comment by elprans** [comment]
This is due to how [connection parameter priority levels](https://www.edgedb.com/docs/reference/connection#ref-reference-connection-priority) work.  Command-line and environment variables generally don't mix.  The rationale is to reduce ambiguity leading to wrong configuration and to avoid sending credentials to the wrong instance accidentally.

You can fix your script by setting `EDGEDB_INSTANCE` alongside `EDGEDB_PASSWORD`, e.g:

```shell
export EDGEDB_INSTANCE=intergration_tests
export EDGEDB_PASSWORD=<your-password>
```

and omitting `-I` when running queries or migrations (`instance create/destroy` still takes an explicit instance name)

**Comment by jsimonlane** [comment]
Interesting. Maybe it would be good to put a warning about that in the `edgedb` cli (ie if some of your parameters are being ignored)? Strikes me as a 'gotcha'.

**Comment by jsimonlane** [comment]
Closing this due to the existence of https://github.com/edgedb/edgedb-cli/issues/1179
