### ISSUE TITLE
Unable to create a migration to an alias of a type

### ISSUE THREAD

**Issue by aljazerzen** [edgedb/edgedb#6459]
`edb cli migration create` fails when trying to migrate from:

```
# schema 1
    type User {
        link currentPolls: Poll;
    };

    type Poll;
```
... to:
```
# schema 2
    alias TEMP := User;

    type User {
        link currentPolls: Poll;
    };

    type Poll;
```

- EdgeDB Version: ced39b843

**Comment by aljazerzen** [comment]
This is delta mismatch:
```
================================================================================
DESCRIBE CURRENT MIGRATION AS JSON mismatch
================================================================================
<DeltaRoot at 0x7f92da98b510> (
    <AlterObjectType canonical=True, classname=default::TEMP, annotations={'confidence': 1.0}, orig_cmd_type=<class 'edb.schema.objtypes.AlterObjectType'> at 0x7f92d9a0f8d0> (
        <AlterLink canonical=True, classname=default::__|currentPolls@default|TEMP, annotations={'confidence': 1.0}, aux_object_data={'from_alias': True} at 0x7f92d9a0ee50> (
            computable       = False | None,
            inherited_fields = edb.common.checked.FrozenCheckedSet[str]({'computable', 'readonly', 'target', 'cardinality'}) | edb.common.checked.FrozenCheckedSet[str]({'readonly', 'target', 'cardinality'})
        )
    )
)
```

It seems like the `computable` gets inherited as `False` from the parent of the link, on the current schema, but not on the target schema.

**Comment by avedetvedea** [comment]
I thought Elvis told you, but he found that out initially. Only after he couldn't reproduce, I sent the full dbschema folder and things blew up

**Comment by aljazerzen** [comment]
He did not, but in retrospect, it would not have mattered - I had to do the long schema pruning and bug isolation, and only now its easy to find the cause issue:

I'm able to reproduce this by:
1. migrating to:
  ```
  # schema 0
  type User {
      multi link currentPolls := (SELECT Poll);
  };

  type Poll;
  ```
2. migrating to schema 1,
3. migrating to schema 2 fails

So the cause is (most probably) in the code that converts a computed link into a non-computed, also known as RESET EXPRESSION, also known as `qlast.SetField(name='expr', value=None, special_syntax=True)`, also known as `sd.AlterObjectProperty`.

**Comment by aljazerzen** [comment]
Also fails with `single link`, `single property` and `multi property`.

**Comment by avedetvedea** [comment]
Hmm yeah, I missed that, thanks. Also, when do nightlies get released in GMT?

**Comment by elprans** [comment]
[1 AM](https://github.com/edgedb/edgedb/blob/c6dd33a6696924c6093081add4bad723b4c6163d/.github/workflows/nightly.yml#L5) currently

**Comment by aljazerzen** [comment]
(currently they are not released every 1AM UTC, because we have a few flaky tests)
