### ISSUE TITLE
SQLite back end

### ISSUE THREAD

**Issue by gisborne** [edgedb/edgedb#648]
I’m sure there’s a lot to do. But SQLite as a back end would probably not be monstrously hard (its basic features and syntax are quite similar to Postgres).

SQLite is the most different in application of all possible alternative back-ends, so I propose adding support for it next.

**Comment by 1st1** [comment]
> I’m sure there’s a lot to do. But SQLite as a back end would probably not be monstrously hard 

Unfortunately it would be "monstrously hard".  We rely on quite a lot of PostgreSQL advanced features.

What can happen in the future is adding a way to connect EdgeDB to another database, be it SQLite or MongoDB.  We have no ETA on that though.

**Comment by gisborne** [comment]
I would have thought FDW would make anything like that relatively easy? Thanks for the response.

**Comment by 1st1** [comment]
> I would have thought FDW would make anything like that relatively easy?

Yes, the hard part would be to correctly map the foreign DB structure to EdgeDB schema so that EdgeQL can reliably query that.  It's doable though.

**Comment by icefoxen** [comment]
Is there anywhere I can start digging to find what PostgreSQL advanced features are actually used?  Being able to be independent of a specific database backend would be a quite killer feature.  Even just inspiring someone else to make their own EdgeDB fork targeting a different database entirely would be really cool.  Depending on the application, it may also be feasible to give up features or robustness for functionality; ie if I'm making a small application that only talks to its own SQLite database it would be really nice to use EdgeQL, but migration robustness might not be that important to me.

**Comment by 1st1** [comment]
I'm going to close this as it's extremely unlikely we will do anything about plugging SQLite into EdgeDB anytime soon.

**Comment by MrFoxPro** [comment]
@1st1 how about reopen this?

**Comment by Boscop** [comment]
@icefoxen I agree with all your points and would love to have a SQLite backend.

> Is there anywhere I can start digging to find what PostgreSQL advanced features are actually used?

I'm curious, have you looked into it? :)
