### ISSUE TITLE
unknown issue the cli produced the link of issue

### ISSUE THREAD

**Issue by mammhoud** [edgedb/edgedb#6482]
EdgeDB CLI 4.0.2+da2788e
- OS Version: macos monterey

Steps to Reproduce:
![default_esdl_—_playground](https://github.com/edgedb/edgedb/assets/98676093/c1144cd5-c1b9-4384-879f-9b03d25c8111)

there are some changes before the error, removed abstract from person db, scalar enum type of task status, overloaded name of employee and default value of name

Schema:
module default {
    type Person {
        required name: str;
        user: User;
        optional contact_info: ContactInfo;
    };

    type User {
        required username: str;
        created_at: datetime;
        optional password: str;
        required person: Person;
    };

    type ContactInfo {
        optional email: str;
        optional phone: str;
        optional second_phone: str;
        optional address: str;
        optional city: str;
        optional state: str;
        optional zipcode: str;
        optional country: str;
    };

    type Company {
        required name: str;
        optional website: str;
    };

    type Employee extending Person {
        required company:  Company;
        required salary: int32;
        multi tasks: Task;
    };

    type Task {
        required description: str;
        optional due_date: datetime;
        optional status: enum<pending, completed, in_progress, on_hold, cancelled>;
        multi assignee: Employee;
    };

    type Role {
        required name: str;
        description: str;
    };
};

**Comment by aljazerzen** [comment]
I'm baffled we don't have a test for this!

What you've hit is a bug that masks the correct error message that you get if you try to convert your schema to DDL:

```
_localdev:edgedb> create type Task {
.................     create property status: enum<pending, completed, in_progress, on_hold, cancelled>;
................. };
error: InvalidPropertyDefinitionError: this type cannot be anonymous
  ┌─ <query>:2:33
  │
2 │         create property status: enum<pending, completed, in_progress, on_hold, cancelled>;
  │                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ error
  │
  = you may want define this enum first:

      scalar type MyEnum extending enum<...>;
```
