### ISSUE TITLE
Instances are killed after 600 seconds. Lack of Documentation and Configurability for `--auto-shutdown-after`.

### ISSUE THREAD

**Issue by bastien8060** [edgedb/edgedb#6514]
# Lack of Documentation and Configurability for `--auto-shutdown-after` Parameter in EdgeDB

## Summary
I've encountered significant operational challenges due to the lack of documentation and configurability for the `--auto-shutdown-after` parameter in EdgeDB. This has led to unexpected auto-shutdown behaviors that are particularly problematic in scenarios where constant availability and low latency are crucial.

## Detailed Description
EdgeDB instances in my setup are unexpectedly shutting down after a certain period of inactivity, causing a delay of 5-10 seconds upon the first request after the shutdown. This delay is detrimental to the performance and user experience of my application. Furthermore, the auto-shutdown also disrupts access to the EdgeDB UI, requiring manual intervention to restart the service or trigger an EdgeQL query to reactivate it.

No Google search led me to anything, which is definitely a bummer. While investigating, I lost crucial time debugging the "unexpected shutdowns". I looked through the code in this repo, and found the guilty parameter. `--auto-shutdown-after`. A quick `$ top` revealed that it was indeed passed to the running instances, with value 600, or 10min. I found a discussion ([EdgeDB GitHub Discussion #4298](https://github.com/edgedb/edgedb/discussions/4298)) mentioning that `--auto-shutdown-after` can't be altered except by running EdgeDB with the `--foreground` flag, which sets `--auto-shutdown-after=-1`. However, running EdgeDB outside of a systemd service is not viable for production environments.

## Steps to Reproduce
1. Set up EdgeDB in a production environment.
2. Observe the automatic shutdown of EdgeDB instances after a period of inactivity.
3. Experience delays in response time and UI access upon reactivation.

## Relevant Logs and Discussions
- [Gist with Logs](https://gist.github.com/bastien8060/11c0adf81018e3f4a0c40da9ae19a069)
- [EdgeDB GitHub Discussion #4298](https://github.com/edgedb/edgedb/discussions/4298)
- [Discussion about the reason behind auto-shutdown](https://github.com/edgedb/edgedb-cli/issues/710#issuecomment-1101826628)

## Proposed Solution
1. **Documentation**: Update the EdgeDB documentation to include information about the `--auto-shutdown-after` parameter, its default behavior, and its impact on EdgeDB instances.
2. **Configurability**: Introduce a way to configure the `--auto-shutdown-after` parameter value, either through service files or server configuration (similar to existing parameters like `session_idle_timeout` or `session_idle_transaction_timeout`). This would provide much-needed flexibility for different production scenarios.

## Conclusion
The current lack of documentation and configurability for the `--auto-shutdown-after` parameter significantly hampers the usability of EdgeDB in production environments where constant availability and low latency are essential. Addressing these issues would greatly enhance the operational experience for users like myself.

**Comment by bastien8060** [comment]
Forgot to mention, but let's say in a situation where my app is not very busy, like during off-peak hours, and there's only one request every 10 minutes or so. In this case, each of these requests could end up taking an extra 5-10 seconds because of the auto-shutdown. This is a significant concern for maintaining smooth user experience.

**Comment by bastien8060** [comment]
I'm open to any interim solutions or workarounds that you might suggest. If there's a temporary fix or a best practice to mitigate this issue until a permanent solution is implemented, that would be greatly appreciated

**Comment by 1st1** [comment]
@bastien8060 Bastien, are you using `edgedb` CLI tooling to run EdgeDB in prod? We do use `auto-shutdown-after` parameter but only in development mode to allow people to run multiple versions of EdgeDB side by side without worrying about RAM/CPU.

**Comment by bastien8060** [comment]
Hi, and thanks a lot for the reply! I did a bit more research on my end in the meantime! Seems like my instances are still restarting (receiving signal 15) every so often, despite overriding auto shutdown to -1. Something else might be at play. I am on the latest version of both cli and edgedb. I ran the simple installation guide from edgedb quickstart.

On a side thought, EdgeDB doesn't run in development mode by default, right? Or should I try installing EdgeDB like in the bare-metal deployment guide? I have an edgedb.toml file with all my migrations in a `dbschema` folder, and `edgedb project info` shows my instance. i assume from that I have a project. Are projects not intended for development?

Cli: 4.0.2+be1da74
Server: 4.0+d568f08

**Comment by bastien8060** [comment]
> @bastien8060 Bastien, are you using `edgedb` CLI tooling to run EdgeDB in prod? We do use `auto-shutdown-after` parameter but only in development mode to allow people to run multiple versions of EdgeDB side by side without worrying about RAM/CPU.
> 
> The reason why `auto-shutdown-after` parameter isn't documented is because it's only used for dev mode, there don't seem to be other good use cases for it (especially in prod).

But about your comment, it does make a lot of sense! I'm guessing I should follow the docs here then: https://www.edgedb.com/docs/guides/deployment/bare_metal. Correct?

**Comment by raddevon** [comment]
Yes, that's right, @bastien8060. The CLI instances are intended for development only. When you install using the instructions at the guide you cited, you won't experience the auto-shutdown.

**Comment by aliwo** [comment]
Hi @raddevon :),
I have a same issue, (I think I did something wrong with bare metal set up) how to check if my edge db is running on production mode?
<img width="1549" alt="image-48" src="https://github.com/edgedb/edgedb/assets/22769112/c1179e74-6d40-4128-b855-d40189b7dfc2">
