### ISSUE TITLE
Access policies completely unusable because of slow performance

### ISSUE THREAD

**Issue by notramo** [edgedb/edgedb#6517]
Using the TypeScript client, querying all users takes ~35 ms, querying `ext::auth::ClientTokenIdentity` takes ~140 ms, but querying the user who is currently authenticated takes not 35+140 ms, but ~750 ms. The worst part is that if it's used in access policies (just like it's mentioned in the docs), it takes 750 ms for every row! It makes access policies completely unusable. 40-60 rows would make the HTTP request time out. One average user hitting the refresh button a few times (because of the timeout) can completely DOS the server.

Given the following schema:
```
using extension auth;

type default::User {
  required identity: ext::auth::Identity { constraint exclusive; }
}
```

Query all users:
```
select User;
```

Query ClientTokenIdentity:
```
select global ext::auth::ClientTokenIdentity;
```

Query authenticated user:
```
select User
filter .identity ?= global ext::auth::ClientTokenIdentity;
```

Note that I'm using the TypeScript client, it's not possible to test it on the CLI because of #6516.

Here is a JS code to reproduce:
```
import { createClient } from 'edgedb';

const client = createClient().withGlobals({
  'ext::auth::client_token':
    'your valid JWT token',
});

const usersStart = Date.now();
console.debug('all users: ', await client.query('select User'));
console.debug('all users select time: ', Date.now() - usersStart);

const currentUserStart = Date.now();
console.debug(
  'current user: ',
  await client.query(
    'select User filter .identity ?= global ext::auth::ClientTokenIdentity',
  ),
);
console.debug(
  'current user select time: ',
  Date.now() - currentUserStart,
);

const identityStart = Date.now();
console.debug(
  'identity: ',
  await client.query(
    'select global ext::auth::ClientTokenIdentity',
  ),
);
console.debug('identity query time: ', Date.now() - identityStart);
```

**Comment by scotttrinh** [comment]
Thanks for the report @notramo going to dig in here and see if we're missing some simple optimizations on our part.
