### ISSUE TITLE
Confusing behavior of the `order by <expression>` 

### ISSUE THREAD

**Issue by MiroslavPetrik** [edgedb/edgedb#6518]
The `order by` accepts expression which when references object property, it does access the currently computed property instead of the 'original/subject' one.

With the data:
<img width="524" alt="image" src="https://github.com/edgedb/edgedb/assets/38855190/e4bd39a6-5ff1-4722-96fb-1a5b243104ec">

I would expect the query:
```
select ProductCategory {name := .name ?? "Other"} order by .name desc empty first;
```
to return

```javascript
[{name: 'Other'}, {name: 'Crusher'}]

/*
the sorting should get empty value for the 'Other' and thus the _empty first_ should be applied for it.
 the 'Other' should be returned as the select demands it
*/
```

instead it returns:
```js
[{name: 'Crusher'}, {name: 'Other'}]
// the Other was used as input to the sorting and was placed after the Crusher as "C" < "O"
// the empty first was not applied
```

I would expect the `empty first` to apply to the 'stored property' instead of the 'computed property'.
I didn't expect that the computed property would overwrite the property in the rest of the select query. 
I've tried to get to the 'stored property' via `detached` keyword, as something similar could change the behavior but it doesn't work (logically).
Also I tried to use the `order by __subject__.name` but that is not permitted in the EdgeQL.

At least it illustrates what I mean by the 'stored property' here.
 

- EdgeDB Version: 4.1+2194ddc
- EdgeDB CLI Version: 4.0.2+b26c502
- OS Version: Win 11

Schema:
```
  type ProductCategory {
    name: str;
    required icon: str;
    constraint exclusive on (.name ?? "_MAKE_NULL_EXCLUSIVE_");
  }
```

**Comment by aljazerzen** [comment]
The problem here is that in `order by`, `.name` refers to the computed `name := ...`, not the original `name` in your object. This means that the values that are being ordered are `'cursher'` and `'other'`.

Think of this as "overshadowing" the initial `name` with the computed.

What you probably want, is a subquery, so you apply the ordering before the computed:
```
select (select ProductCategory order by .name desc empty first) {
   name := .name ?? "Other"
};
```
... or with a `with` block:
```
with ordered := (select ProductCategory order by .name desc empty first)
select ordered { name := .name ?? "Other" };
```

**Comment by aljazerzen** [comment]
If you have any more questions, feel free to re-open.
