### ISSUE TITLE
FTS indexes are broken after a restore

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#6550]
`__fts_document__` doesn't get dumped, and we disable triggers when restoring, so `__fts_document__` never gets populated. We should probably run SQL that populates it after the restore

**Comment by s0l4r** [comment]
If anyone runs into this, the quick fix is to drop the ftx indexes and recreate them again after restore.

**Comment by msullivan** [comment]
It might be worth doing measurement to see if it would be faster on restore to actually dump `__fts_document__`, and then we can weigh that against the increased cost of dump and the increased size of dumps to decide if we think it is worthwhile.

That said, either way we will need to support restoring from dumps that don't have it.

**Comment by aljazerzen** [comment]
Dumping `__fts_document__` along with the data feels wrong. This is basically a cache, an internal detail. We might even change it in the future.

**Comment by aljazerzen** [comment]
But yes, if you have a lot of objects and a complex index expression, restore operation might take a long time.
