### ISSUE TITLE
ISE on basic grouping

### ISSUE THREAD

**Issue by themajashurka** [edgedb/edgedb#6557]
I've discovered this ISE by just playing with the shape of `group`

- EdgeDB Version: 4.2+7038dfc / 4.2+8778fc1
- EdgeDB CLI Version: 4.0.2+da2788e / 4.0.2+b26c502
- OS Version: macOS 11.7.10 / Windows 10

Steps to Reproduce:

```
select (group Foo
by .detail).key.detail
```

Schema: 

```
type Foo {
    property detail -> str;
}
```

Problem:

`InternalServerError: Can't compile ref to visible binding (__derived__::detail~1@w~1)`

**Comment by themajashurka** [comment]
Here I shared a stripped down of my current schema, excluding other 49 types :) (I assume here should be absolutely no crosstalk between different tables with a simple `select/group` like this)
Just to make sure, I created a brand new project with a fresh out-of-the-oven instance, including nothing but this `Foo` type, on Windows 10 (happened to work on two machines at the same time), but I still experience the same problem.

**Comment by Dhghomon** [comment]
Weird! I can't get the same error to reproduce regardless of if I give it the same property names or paste in your schema exactly as you have it. And I'm on Windows 11 which isn't different from Windows 10 which you've confirmed does generate this error. I'll see if anyone else has any idea of what it might be.

**Comment by Dhghomon** [comment]
In the meantime here is another idea: do you see anything interesting when you set RUST_LOG to trace? It'll be pages and pages of output (including every keystroke) but might be something in there of note.

**Comment by themajashurka** [comment]
Some dummy data, but the CLI finally does it's thing: 
![image](https://github.com/edgedb/edgedb/assets/81056844/0dba8c16-5a55-4022-af6b-3d6bb643847e)

**Comment by Dhghomon** [comment]
Ah ha! That narrows it down at least to a UI issue and I guess we can move
it to there. I'll see if I can reproduce it too in a few minutes.

2023년 12월 4일 (월) 오후 11:18, themajashurka ***@***.***>님이 작성:

**Comment by Dhghomon** [comment]
Yes! I'm getting the same error in the UI, you are not alone.

**Comment by Dhghomon** [comment]
> I've inserted some dummy data, but the CLI finally does it's thing: ![image](https://private-user-images.githubusercontent.com/81056844/287726460-0dba8c16-5a55-4022-af6b-3d6bb643847e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDIwMjMsIm5iZiI6MTcwMTcwMTcyMywicGF0aCI6Ii84MTA1Njg0NC8yODc3MjY0NjAtMGRiYThjMTYtNWE1NS00MDIyLWFmNmItM2Q2YmI2NDM4NDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDE0NTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZDFjYzQ1MGUzMjRiZTJlM2I1MGM4YTY1MTQ5MzU3NTRkZDE2MGY3YjlkNmEwYWE5MmYzMjFmMDBhMjhlMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OgTqzflAJ-VGnDXNJYg9PtI4fZVeMM1Y6CNTzvd56Ig)

Okay, looks like the issue is going to stay here - James mentioned that it's probably not a UI issue but a something the UI uses issue and related to the compiler:

>Since the error message is an ISE, I think it's probably not directly a UI issue, but a compiler bug related to one of the implicit typename/typeid/objectid injection flags the UI uses and the CLI/bindings don't.

**Comment by msullivan** [comment]
The weird non reproducibility seems to be based on whether an implicit limit is injected into the query, which is kind of wild.

By default the CLI has a limit of 100; maybe the UI doesn't have one.
(I disabled the limit on my CLI so I reproduced it immediately)
