### ISSUE TITLE
401 Unauthorized error in preflight Options request

### ISSUE THREAD

**Issue by AnsonHwang86** [edgedb/edgedb#6569]
- EdgeDB Version: v4.2 Cloud

Steps to Reproduce:

1. On the chrome extension code writing following:

```
const headers = {
        'Accept': '*',
                'Content-Type': 'application/json',
        'Authorization': `Bearer nb******Nw`,
};
const options = {
      "method": "POST",
      "mode": "cors",
      headers,
      "body": JSON.stringify({"query":"select 222"})
     };

// send to the endpoint
fetch("https://******.c-75.i.aws.edgedb.cloud:5656/db/edgedb/edgeql", options).then(function(response) {
    console.log(response);
});
```

2. the browser will auto send Options request before POST.
![image](https://github.com/edgedb/edgedb/assets/16233397/95d422f0-a981-4152-82bb-7e3df87d998c)
![image](https://github.com/edgedb/edgedb/assets/16233397/ac414a6b-5089-4f5d-bb0b-1ea7c6cda7eb)

3.when I run chrome with following command without preflight OPTIONS request, it work fine.
chrome.exe --user-data-dir="C://chrome-dev-disabled-security" --disable-web-security --disable-site-isolation-trials

![image](https://github.com/edgedb/edgedb/assets/16233397/68d442f1-944d-4a3c-ad34-58d1997117d1)

Authorization should not be checked in preflight Options request.

**Comment by aljazerzen** [comment]
We do have something similar in debug mode: 

https://github.com/edgedb/edgedb/blob/master/edb/server/protocol/protocol.pyx#L529-L536

https://github.com/edgedb/edgedb/blob/master/edb/server/protocol/protocol.pyx#L635-L642

@fantix will know more about this

**Comment by fantix** [comment]
Yeah I think we should just replicate the same CORS handler for the extensions endpoint, before `self._check_http_auth()`.

Refs #5755, we have `debug.flags.http_inject_cors = True` in Cloud for now.

**Comment by 1st1** [comment]
@fantix We should work on this before 5.0.

**Comment by AnsonHwang86** [comment]
Hello, I want to know if team to push this fix to Cloud now or just wait next  update?

**Comment by aljazerzen** [comment]
Yes, this will be backported to v4.3, which should land over the weekend.

**Comment by AnsonHwang86** [comment]
hello, I upgrade to 4.3 and test it locally.
The error is still exists
![image](https://github.com/edgedb/edgedb/assets/16233397/1392e26c-33d7-4c74-be6d-f1fb33a37565)

When I run it with `chrome.exe --user-data-dir="C://chrome-dev-disabled-security" --disable-web-security --disable-site-isolation-trials`, there will be not error appear.

**Comment by AnsonHwang86** [comment]
hello, I upgrade to 4.3 and test it locally.
The error is still exists
![image](https://github.com/edgedb/edgedb/assets/16233397/57ef4b77-9691-4f69-96b2-e58a8b502652)

When I run it with `chrome.exe --user-data-dir="C://chrome-dev-disabled-security" --disable-web-security --disable-site-isolation-trials`, there will be not error appear.

**Comment by msullivan** [comment]
Oh, right, you need to run the server with the environment variable EDGEDB_DEBUG_HTTP_INJECT_CORS=1

**Comment by AnsonHwang86** [comment]
thanks. is possible to configure this on Cloud V4.3?

**Comment by msullivan** [comment]
I think that it is supposed to always be set on cloud?

**Comment by aljazerzen** [comment]
We need docs for this.

**Comment by msullivan** [comment]
Closed in favor of https://github.com/edgedb/edgedb/issues/6654 for the documentation issue and https://github.com/edgedb/edgedb/issues/6655 for configurability
