### ISSUE TITLE
.NET Driver

### ISSUE THREAD

**Issue by brettrowberry** [edgedb/edgedb#657]
This looks really great. Any plans for a .NET driver?

**Comment by elprans** [comment]
We are currently working on JavaScript and Go bindings.  Java and .NET will be the next two platforms we will add support for.

Meanwhile, you can use the [EdgeQL over HTTP API](https://edgedb.com/docs/clients/90_edgeql/index)

**Comment by Swoorup** [comment]
Would also like to add a F# typeprovider driver. 👍

**Comment by jhult** [comment]
Released client drivers/libraries:

- Python: https://www.edgedb.com/docs/clients/00_python/index
- TypeScript/JavaScript: https://www.edgedb.com/docs/clients/01_js/index
- Go: https://www.edgedb.com/docs/clients/02_go/index

**Comment by 1st1** [comment]
FWIW there's this now: https://github.com/quinchs/EdgeDB.Net

**Comment by msullivan** [comment]
And also it is official and first-party now
