### ISSUE TITLE
Constraint Exclusive on Link Property throw 'violates exclusivity constraint' error in for loop even the data is empty.

### ISSUE THREAD

**Issue by AnsonHwang86** [edgedb/edgedb#6570]
- EdgeDB Version: v4 Cloud
- EdgeDB CLI Version: via http

Steps to Reproduce:

1. Migrate the schema
2.and run
```
with data := <json>$data,
	  for item in json_array_unpack(data) union(
		insert SaleFetch {
		   dailySaleSnapshots := (
			insert DailySaleSnapshot {
			  @date := <cal::local_date>"2023-12-06",
			}
		  )
		}
	  )
```
data: [ {"a":1},{"a":2} ]

_Note: the DailySaleSnapshot and SaleFetch  are empty before this insert._

![image](https://github.com/edgedb/edgedb/assets/16233397/5d67a975-36c4-411a-ac76-33d3a3d9a12a)

Then let's insert a data and change insert to update
```
with data := <json>$data,
	  for item in json_array_unpack(data) union(
		update SaleFetch filter .id = <uuid>"6b927cf8-93d1-11ee-a237-7b76965035f6"  set {
		   dailySaleSnapshots := (
			insert DailySaleSnapshot {
			  @date := <cal::local_date>"2023-12-06",
			}
		  )
		}
	  )
```
Here is error
![image](https://github.com/edgedb/edgedb/assets/16233397/6a4d4d68-dd60-4b41-bc1b-2094aa0d9cbc)

Schema:

```
type SaleFetch{
        productId: str {constraint exclusive;};
        multi dailySaleSnapshots: DailySaleSnapshot {
            date: cal::local_date{
                constraint exclusive;
                default := cal::to_local_date( datetime_current(), 'US/Pacific');
                # default := to_str(cal::to_local_date(datetime_current(),'US/Pacific'));
            };
        };
    }

    type DailySaleSnapshot{
        salePrice: float32;
    }
```

**Comment by msullivan** [comment]
The second query is failing as a side effect of trying to update the same object multiple times, which is not really supported. Probably shouldn't be an ISE though.

**Comment by msullivan** [comment]
The current behavior, where the exclusive constraint applies for *all* the values, is intended.
There should be a way (... and *almost* is) to get the behavior you want. I'll try to make it possible.

**Comment by msullivan** [comment]
If I understand correctly what you are trying to do,https://github.com/edgedb/edgedb/pull/6585 will make it possible to do what you want by declaring a constraint like:
```
constraint exclusive on ((@source, @date))
```

**Comment by AnsonHwang86** [comment]
Maybe yes, I am waiting the merge to download docker image to test it. Yes, there is not any document about @source @target now.
I used to find many solution to workaround this, currently my solution is add the exclusive property value of source as part of target.
![image](https://github.com/edgedb/edgedb/assets/16233397/5a61b8cf-e767-4f91-94df-c2d96d18dc9c)

Also, there are serveral bug about link property mutation reported at issues which stop me to use link property. If any priority would be great. Thanks for your quickly response.
