### ISSUE TITLE
constraint exclusive not work on link property

### ISSUE THREAD

**Issue by AnsonHwang86** [edgedb/edgedb#6571]
- EdgeDB Version: v4.2 cloud
- EdgeDB CLI Version:
- OS Version:

Steps to Reproduce:

1. migrate the schema
2.run following edgeql multi time will not throw constraint exclusive violate.

```
update SaleFetch filter .id = <uuid>"6b927cf8-93d1-11ee-a237-7b76965035f6"  set {
   dailySaleSnapshots := (
    insert DailySaleSnapshot {
      @date := <cal::local_date>"2023-12-06",
    }
  )
}
```

![image](https://github.com/edgedb/edgedb/assets/16233397/4f73c111-4054-4223-bf6f-2c5c9ce6e54f)

Excepted result is error will throw on the second run and after but not.

Schema:
```
    type SaleFetch {
        productId: str {constraint exclusive;};
        multi dailySaleSnapshots: DailySaleSnapshot {
            date: cal::local_date{
                constraint exclusive;
                default := cal::to_local_date( datetime_current(), 'US/Pacific');
                # default := to_str(cal::to_local_date(datetime_current(),'US/Pacific'));
            };
        };
    }

    type DailySaleSnapshot{
        salePrice: float32;
    }
```

**Comment by raddevon** [comment]
I don't follow. Are you saying you already have a linked item on a different `SaleFetch` with the same `date` property value you're updating to on this one?

**Comment by AnsonHwang86** [comment]
Hello, I update the same SaleFetch with a new DailySaleSnapshot  but with same link properties every time. 
![image](https://github.com/edgedb/edgedb/assets/16233397/6a4aca7c-9834-4f36-ac6e-94efcb040282)

**Comment by raddevon** [comment]
I'll close for now, but please re-open if I've missed something or if there's still a problem.
