### ISSUE TITLE
Rust driver

### ISSUE THREAD

**Issue by icefoxen** [edgedb/edgedb#658]
This seems to be a popular sort of question.  ;-)  So I'll throw my hat in, any plans for a Rust driver?

Perhaps it would be most useful to simply document the process of how to write a new driver, and then people could implement their own?  Not sure if that's feasible in terms of API interface.  I seem to recall it being mentioned that you use protobuf at some level for serialization but I can't find where in the source.  If that's accurate, is it stable enough to be considered an API others could write clients for?

Thank you!

**Comment by 1st1** [comment]
> This seems to be a popular sort of question. ;-) So I'll throw my hat in, any plans for a Rust driver?

We want a Rust driver but have no ETA for it yet. Any help would be welcome! :)

> Perhaps it would be most useful to simply document the process of how to write a new driver, and then people could implement their own?

* The protocol is fully documented here: https://edgedb.com/docs/internals/protocol/overview

* The Python implementation is here: https://github.com/edgedb/edgedb-python

* The JS/TS driver is almost completed and can be found here: https://github.com/edgedb/edgedb-js

Our vision is that EdgeDB drivers should look similar across different languages. Given that we already have two drivers, the Rust driver should be designed to have a somewhat similar API.  If you want to assist us with this, I think a good starting point would be to outline the API design first.

> [..] is it stable enough to be considered an API others could write clients for?

The current protocol is designed to be extensible, so I don't expect any significant changes to it.

**Comment by agritheory** [comment]
I'm not saying its a good idea, but one could wrap the python driver api in rust. Rust supports running arbitrary python code inline, but I'd call it experimental.
https://news.ycombinator.com/item?id=19728112

And a follow-on-step, optimizing the hottest pieces of the python driver with Rust makes complete sense as well.

**Comment by 1st1** [comment]
@tailhook we need to think about this one and preferrably have at least a blocking driver before 1.0

**Comment by PastelStoic** [comment]
Not to necro, but I think this issue can safely be closed.
