### ISSUE TITLE
EdgeDB Auth: Resend verification flow requires that you have an existing (expired?) token

### ISSUE THREAD

**Issue by scotttrinh** [edgedb/edgedb#6581]
- EdgeDB Version: >4

---

We currently require that you provide a `verification_token` to resend the token, which only makes sense in the context of an expired token, but if you never got it (due to email undeliverability, or deleted email, etc), you won't have one to provide.

**Comment by KyleXie** [comment]
Hey, any updates for this issue?

**Comment by scotttrinh** [comment]
Apologies for the wait on this! This is a next-up issue for us.
