### ISSUE TITLE
ISE `unsupported Unicode escape sequence`

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb#6582]
- EdgeDB Version: 4.2 
- EdgeDB CLI Version: 4.0.2
- OS Version: macos 13

NB: seemingly only reachable via the JS client, but the actual problem is with the server, so filing here

Steps to Reproduce:

```typescript
const fileBuffer = fs.readFileSync("png.txt");
const ostensibleString = fileBuffer.toString("utf-8");

await e
  .params({ body: e.json }, $ =>
    e.insert(e.Event, {
      body: $.body,
    }),
  )
  .run(client, { body: ostensibleString });
```

```
InternalServerError: unsupported Unicode escape sequence
```

Obviously bad query, but also not an actual ISE.

Schema:
```
type Event {
    required property body: json;
}
```
[png.txt](https://github.com/edgedb/edgedb/files/13603231/png.txt)

**Comment by elprans** [comment]
ISE due to missing Postgres error code translation.

**Comment by dnwpark** [comment]
I am getting a slightly different error than reported

```
InvalidValueError: invalid byte sequence for encoding "UTF8": 0x00
```

Unsure if this counts as fixed.
