### ISSUE TITLE
Migration script suggests impossible cast from datetime to cal::local_date

### ISSUE THREAD

**Issue by Dhghomon** [edgedb/edgedb#6602]
When starting with this schema:

```
module default {
  type SomeType {
    d: datetime;
  }
}
```

And migrating to this:

```
module default {
  type SomeType {
    d: cal::local_date;
  }
}
```

The prompt suggests a cast: `<cal::local_date>.d` which does not work. Suggesting `cal::to_local_date(.d)` with a timezone will work, however. I can think of two possible options when doing so:

- cal::to_local_date(.d) which will err but suggest three possible function signatures, one of which has a `str` for the timezone
- cal::to_local_date(.d, 'UTC') which will work outright but the user might hit enter without giving the prompt enough thought.

Other possible prompts like cal::to_local_date(.d, <TIMEZONE>) would be nice but output misleading errors. Eventually could be nice to have an enum for timezones that begins half completed, like cal::to_local_date(.d, std::TimeZone.)

**Comment by msullivan** [comment]
The suggested cast is produced by the CLI, not by the compiler/server. The server just reports the old_type and the new_type back to the CLI

**Comment by Dhghomon** [comment]
> The suggested cast is produced by the CLI, not by the compiler/server. The server just reports the old_type and the new_type back to the CLI

Ah, good to know. I'll open the issue up there.
