### ISSUE TITLE
Sequence doesn't get incremented when items are inserted with explicit sequence value

### ISSUE THREAD

**Issue by MrFoxPro** [edgedb/edgedb#6632]
- EdgeDB Version: 4.2+8778fc1 (on 5+ proably happens too)
- EdgeDB CLI Version: EdgeDB CLI 4.1.0-dev
- OS Version: GNU/Linux 6.6.7-arch1-1

Steps to Reproduce:

1. **Fully remove** database and create new 
2. Apply schema
3. Run query 3 times in sequence

Schema:
```edgeql
scalar type TestSubtypeNumericSequence extending sequence;
type TestSubtype {
  required num: TestSubtypeNumericSequence { readonly := true; constraint exclusive; };
  required name: str;
  constraint exclusive on (.name);
}
type TestType {
  required multi subs: TestSubtype {
     on target delete allow;
     default := (select detached TestSubtype limit 1);
  };
}
```

Query
```edgeql
insert TestType {
  subs := {
     (insert TestSubtype { num := 0, name := "A" }),
     (insert TestSubtype { num := 1, name := "B" }),
     (insert TestSubtype { num := 2, name := "C" }),
  }
};

with
  subs := array_unpack(<array<json>>to_json(<str>$subs)),
select (insert TestType {
  subs := distinct (for sub in subs union (
     insert TestSubtype {
        name := <str>sub["name"],
     } unless conflict on .name
     else (select TestSubtype)
  )),
}) { subs: { num, name } }
```
arguments $subs:
```json
[
  { "name": "A" },
  { "name": "B" },
  { "name": "D" }
]
```
It will fail for two times and will work after.

Obviously reason is that `num` property was not incremeneted after inital data insertion.

Isn't it undefined behaviour?

**Comment by raddevon** [comment]
First attempt to run the query failed for me, FYI.

**Comment by raddevon** [comment]
This may be the expected result after all:
> Sequence advancement is done atomically; each concurrent session and transaction will receive a distinct sequence value.

https://www.edgedb.com/docs/stdlib/sequence#function::std::sequence_next

Sounds like the sequence is not incremented within a transaction.

**Comment by MrFoxPro** [comment]
> This may be the expected result after all:
> 
> > Sequence advancement is done atomically; each concurrent session and transaction will receive a distinct sequence value.
> 
> https://www.edgedb.com/docs/stdlib/sequence#function::std::sequence_next
> 
> Sounds like the sequence is not incremented within a transaction.

I mean maybe there should be a way to make it forbid assign a sequence value on `INSERT`?

**Comment by raddevon** [comment]
> I mean maybe there should be a way to make it forbid assign a sequence value on INSERT?

You're saying you want insert to fail unless the insert explicitly contains a manually assigned sequence value? You might be able to do this with a mutation rewrite + assertion on `exists __specified__.num`. https://www.edgedb.com/docs/datamodel/mutation_rewrites#available-variables

**Comment by MrFoxPro** [comment]
> > I mean maybe there should be a way to make it forbid assign a sequence value on INSERT?
> 
> You're saying you want insert to fail unless the insert explicitly contains a manually assigned sequence value? You might be able to do this with a mutation rewrite + assertion on `exists __specified__.num`. https://www.edgedb.com/docs/datamodel/mutation_rewrites#available-variables

No, I mean opposite, I want insert to fail if sequence value was specified explicitly.

**Comment by raddevon** [comment]
OK, that might also work. Change your assertion to `not exists __specified__.num`.

**Comment by MrFoxPro** [comment]
I'm not sure it's actually a bug. Maybe it's worth to better document / warn that it's important to reset sequence after manipulating it directily.
