### ISSUE TITLE
[Question] SELECT inside an INSERT statement

### ISSUE THREAD

**Issue by pedronc** [edgedb/edgedb#665]
Consider this example from the EdgeDB docs:

```
WITH MODULE example
INSERT Issue {
    number := '100',
    body := 'Fix errors in INSERT',
    owner := (
        SELECT User FILTER User.name = 'Bob Johnson'
    )
};
```

Suppose that my application already has the data of the inner SELECT statement. In a traditional SQL database, my app would simply insert a foreign key in the owner field and the insert query would run in O(1).  In the EdgeDB looks like I always have to perform the select statement to insert new data, preventing me to cache data in the application layer, for example. 

Is there a way to insert a new data that references previously inserted data without having to create an inner select statement?

**Comment by elprans** [comment]
Foreign keys aren't O(1), the database has to do a lookup in the target table, which is equivalent to the nested `SELECT` above (assuming you have an index on `name`).

**Comment by pedronc** [comment]
I wasn't sure if it was really O(1), but I couldn't explain why it wouldn't be. It makes sense totally now. Thank you for your time.
