### ISSUE TITLE
Incompatibility with lib/pq Golang PostgreSQL driver for read-only SQL

### ISSUE THREAD

**Issue by tomnz** [edgedb/edgedb#6682]
We utilize the [read-only SQL](https://www.edgedb.com/docs/reference/sql_support) feature of EdgeDB to export data to various third-party tools. We were having difficulty hooking up one of these tools - and after working with that provider, we were able to narrow down the issue to some unsupported functionality on the EdgeDB PostgreSQL side. Reporting it here so that it can be fixed, as it may be affecting others.

- The provider uses [lib/pq](https://github.com/lib/pq/) (a Golang library) to connect to Postgres databases.
- A common pattern with that library is to use `db.Ping()` ([code here](https://github.com/lib/pq/blob/3d613208bca2e74f2a20e04126ed30bcb5c4cc27/conn_go18.go#L90-L100)) to test the new database connection before continuing.
- Under the hood, this appears to make some sort of "no-op" query to PostgreSQL, although the [code](https://github.com/lib/pq/blob/master/conn.go#L701) is hard for me to grok what is going on.
- This no-op query made by `db.Ping()` is what ultimately raises an error and prevents the code from continuing. The error reportedly seen by the provider was: `pq: unknown response for simple query: 'n'`

Reproducing should be as simple as connecting to the read-only SQL endpoint of an EdgeDB instance with lib/pq and calling the `db.Ping()` function.

The provider was able to work around the issue by switching to use `sqlx.Open` - and avoiding the use of the `Ping()` function.

- EdgeDB Version: 4.2+539e5c8
- EdgeDB CLI Version: 4.0.2+6d63edc
- OS Version: Debian Bullseye (Docker)

**Comment by msullivan** [comment]
(I *think* this seems like a server protocol issue?)

**Comment by fantix** [comment]
Yeah, `'n'` seems to be the [`NoData`](https://www.postgresql.org/docs/current/protocol-message-formats.html#PROTOCOL-MESSAGE-FORMATS-NODATA) message we yield.

**Comment by fantix** [comment]
... which we shouldn't have in the case of an empty SQL query like `;`, because Postgres doesn't. I'll push a fix.

**Comment by Novark** [comment]
@fantix Out of curiosity, would this issue affect other providers that don't use lib/pq, or is this strictly an issue with the way that lib/pq implements its `Ping()` functionality?  In other words, is this something that third party providers should be mindful of, or is this strictly an issue with the way the edgedb replies to `no-op` queries?

**Comment by aljazerzen** [comment]
@Novark From what I understand, this part is not really clear, because postgres docs don't specify this sufficiently. Because of that, the exact behavior is defined by "what Postgres does".

So it is up to edgedb to do "exactly what Postgres does", so any Postgres client is also compatible with edgedb.

**Comment by Novark** [comment]
@aljazerzen Thanks for that clarification - it sounds like the fix is to adjust how edgedb responds to `no-op` queries in order to match how Postgres does things, and shouldn't require any action by third-party providers.

Fingers crossed for a fix here so that #6437 can be resolved!

**Comment by aljazerzen** [comment]
I've verified that the go pq library's ping now works.
