### ISSUE TITLE
Computeds in SQL adapter

### ISSUE THREAD

**Issue by aljazerzen** [edgedb/edgedb#6692]
Continuing discussion from #6017

**Comment by aljazerzen** [comment]
@jnak Can I ask, which tool are you using for reverse-ETL? Is there an option to include auto-generated columns? And views?

Current plan is to expose single computeds as [GENERATED columns](https://www.postgresql.org/docs/current/ddl-generated-columns.html) and multi computeds as `CREATE VIEW X (source uuid, target computed_type)`. This is the plan because pg_dump does not dump GENERATED columns and views, but it would be useless if they were unavailable to ETL tools.

An alternative approach would be

**Comment by jnak** [comment]
Thanks for continuing the discussion!

> @jnak Can I ask, which tool are you using for reverse-ETL? Is there an option to include auto-generated columns? And views?

We're not yet using a proper reverse-ETL tool, as we've purposefully pushed back on investing too much into our warehouse for now. However, we're currently using services such as Metabase and Customer IO that query EdgeDB via the SQL interface. We'll be looking at tools such as FiveTran or Airbyte when we're ready to invest to our warehouse.

> Current plan is to expose single computeds as [GENERATED columns](https://www.postgresql.org/docs/current/ddl-generated-columns.html) and multi computeds as CREATE VIEW X (source uuid, target computed_type). This is the plan because pg_dump does not dump GENERATED columns and views, but it would be useless if they were unavailable to ETL tools.

This is super exciting! I can't wait to use it. What's the timeline there?

Tangantially-related, are you planning to allow computed fields to be materialized/generated in EdgeDB? That would be huge! We don't need it yet, but it would be amazing to know that, at some point, we could speed up slow computed values by materializing them :)

**Comment by aljazerzen** [comment]
> What's the timeline there?

This is hard to say, as I have a different task before this one which has a lot of unknowns with it. The worst-worst scenario would be 6.0, which will release end of June.

> Are you planning to allow computed fields to be materialized/generated in EdgeDB?

They will definitely be computed during query-time. We don't want to unnecessary space. If you'd want things materialized, you could use regular pointers with mutation rewrites to update the value on inserts and updates.

**Comment by jnak** [comment]
> This is hard to say, as I have a different task before this one which has a lot of unknowns with it. The worst-worst scenario would be 6.0, which will release end of June.

Exciting!

> They will definitely be computed during query-time. We don't want to unnecessary space. If you'd want things materialized, you could use regular pointers with mutation rewrites to update the value on inserts and updates.

Yeah, I know it's possible with triggers, but then it can get tricky to write it in the first place if the computed field queries multiple types. Also, the logic is no longer encapsulated in one place, which increases the likelihood that some refactoring will introduce an unwanted consistency bug. It would be nice if the compiler could take care of that automatically for us. But that's a non-trivial project to handle all the edge cases.

**Comment by jackfischer** [comment]
Sadly it looks like this didn't make it into 5.0. Can we still expect it in 6.0?

**Comment by jnak** [comment]
Yes, that's too bad. We were looking to clean up the mess we've created by re-implementing the logic in SQL of our many computed files. Any update on this?

**Comment by aljazerzen** [comment]
I don't want to say I promise it, because that rarely has a good outcome :D

But I can say that it is in the roadmap for 6.0 and I will be starting work on it these days.

**Comment by jackfischer** [comment]
That is huge. Thank you
