### ISSUE TITLE
Cannot select overloaded property

### ISSUE THREAD

**Issue by CarsonF** [edgedb/edgedb#6695]
- EdgeDB Version: 4.4+aa576e1
- EdgeDB CLI Version: 4.0.2+500be79
- OS Version: macOS 14.1.2

Steps to Reproduce:

I believe the link is correctly set in the insert statement, but the select query never gives it back - it's always an empty set.
```edgeql
select (insert Post {
  container := (select TranslationProject limit 1),
  body := to_json('{"hello":"world"}'),
  type := Post::Type.Note,
  shareability := Post::Shareability.External
}) {
  container
}
```
Here's [the schema](https://github.com/SeedCompany/cord-api-v3/compare/edgedb/posts-bugged).

I think it's somehow related to the `overloaded` type.
```edgeql
module Mixin {
  abstract type Embedded {
    required single link container: default::Resource;
```
And then overloaded here to
```edgeql
module default {
  type Post extending Resource, Mixin::Embedded, Mixin::Owned {
    overloaded required single link container: Mixin::Postable;
```

**Comment by raddevon** [comment]
I tried to reproduce with a simpler schema, and I'm having some trouble. I applied this schema:

```esdl
module default {
  abstract type Animal {
    parent: Animal;
  }
  type Human extending Animal {
    overloaded parent: Human;
  }
}
```

and ran these two queries:
```edgeql
insert Human;
```

```edgeql
select (
  insert Human {parent := (select detached Human limit 1)}
) {parent};
```

This select-wrapped insert query _does_ correctly produce a result with the `parent` object, so there must be some x-factor here, either in the query or in the schema… 🤔

**Comment by CarsonF** [comment]
I should clarify:
- The query does successfully finish, and this field is required. So that leads me to believe that the relationship was stored, but obviously I could be wrong on this.
- It's not just a select wrapped insert, but _any_ select that fails to produce the linked object.

Based on recent conversations with @msullivan I'd believe that it could take a complex schema to reproduce this.

**Comment by CarsonF** [comment]
I actually cannot reproduce this now either.
I guess it's possible it was related to #6699 or #6706. I've since worked around those. And it appears to be working.
I'll try a few more things before closing.

**Comment by CarsonF** [comment]
Yeah I think I'm good here now. If I'm remembering correctly, this didn't happen with other objects as the `container`. It only happened with `TranslationProjects`. So that points to #6706, which came from my bug which had a rewrite on `TranslationProject`. Now that I have that commented out, as a work around, this appears to be fine. So closing this as a symptom of that same root issue.
