### ISSUE TITLE
Overloading a link with a more specific type fails

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb#6716]
When this schema is described, the overload on the `parent` link to link it to a different type appears to have been ignored.

`describe schema as sdl;` produces this for `Human`:
```esdl
type Human extending default::Animal {
    overloaded link parent;
};
```

`describe schema;` produces this:
```edgeql
create module default if not exists;
create abstract type default::Animal {
    create link parent: default::Animal;
    create property name: std::str;
};
create type default::Human extending default::Animal {
    alter link parent {
        SET OWNED;
    };
};
```

- EdgeDB Version: 4.4+aa576e1
- EdgeDB CLI Version: 4.0.2+500be79
- OS Version: macOS 14.0

Steps to Reproduce:

1. Migrate the schema
2. Describe the schema

Schema:

```esdl
abstract type Animal {
  name: str;
  parent: Animal;
}
type Human extending Animal {
  overloaded parent: Human;
}
```

**Comment by corbinday** [comment]
#6701

**Comment by msullivan** [comment]
I feel pretty silly about this one: seems like it is a bug in the code for omitting `link`/`property` specifiers. If you write `overloaded link parent: Human`, it works.

**Comment by corbinday** [comment]
@msullivan 

Other aspects of overloading links still fail for me, even if I add `link`. 

Here's an example schema that I cannot create a migration for:

```edgeql
module default {

  type User {
    height := .<user[is UserInputReply];
  }
  
  abstract type Question;

  type HealthQuestion extending Question;

  abstract type Reply {
    required user: User;
    required single question: Question;
  }

  abstract type UserInputReply extending Reply {
    overloaded link question: HealthQuestion;
  }

  type HeightReply extending UserInputReply;
}
```

It fails with this message:

```
SchemaError: link 'question' of object type 'default::HeightReply' cannot be cast automatically from object type 'default::Question' to object type 'default::HealthQuestion'
  Hint: You might need to specify a conversion expression in a USING clause
```

It seems like the migration tool looks to the place the original link was defined and ignores the overloaded reference.
