### ISSUE TITLE
please add a favicon to your website

### ISSUE THREAD

**Issue by jensneuse** [edgedb/edgedb#673]
Looks much better with a favicon.

**Comment by cosmophile** [comment]
It would also be great to have proper page titles on the doc pages - I'm sure it's common to have several doc pages open at once, and it's very helpful to be able to get some idea of the subject from the tab instead of having to click and scan the page contents. Just a nice-to-have.

**Comment by 1st1** [comment]
Thank you, we'll add both titles and a fav icon soon!

**Comment by NiloCK** [comment]
Edgebd.com currently has a favicon. This issue should be closed.

**Comment by elprans** [comment]
Roger.
