### ISSUE TITLE
Issue of `ext::pgcrypto::crypt()` and `ext::pgcrypto::gen_salt()`

### ISSUE THREAD

**Issue by jrycw** [edgedb/edgedb#6742]
- EdgeDB Version: 4.5+28216a1
- EdgeDB CLI Version: 4.0.2+b26c502
- OS Version: Windows 11

Description:

I encountered unexpected behavior while using the `ext::pgcrypto::crypt()` function in EdgeDB, as described in the documentation [here](https://www.edgedb.com/docs/stdlib/pgcrypto#function::ext::pgcrypto::crypt).

The documentation provides an example:
```
db> with module ext::pgcrypto
... select crypt('new password', gen_salt('des'));
{'0ddkJUiOnUFq6'}

db> with hash := '0ddkJUiOnUFq6'
... select hash = ext::pgcrypto::crypt(
...   'new password',
...   hash,
... );
{true}
```

Subsequently, when comparing the hashed result with a different input but with the first few characters unchanged, the result is unexpectedly **true**:
```
db> with hash := '0ddkJUiOnUFq6'
... select hash = ext::pgcrypto::crypt(
...   'new passabcdefghj',
...   hash,
... );
{true}
```
Additionally, I observed that using a different salt type, such as the default `bf`, results in behavior that aligns with expectations:
```
db> with module ext::pgcrypto
... select crypt('new password', gen_salt());
{'$2a$06$ElyvQFLUPjSGcZO39/gmvuuk3sjbe.Rnjz6hq7P1Xs18v2j8GUw.C'}

db> with hash := '$2a$06$ElyvQFLUPjSGcZO39/gmvuuk3sjbe.Rnjz6hq7P1Xs18v2j8GUw.C'
... select hash = ext::pgcrypto::crypt(
...   'new password',
...   hash,
... );
{true}

db> with hash := '$2a$06$ElyvQFLUPjSGcZO39/gmvuuk3sjbe.Rnjz6hq7P1Xs18v2j8GUw.C'
... select hash = ext::pgcrypto::crypt(
...   'new passabcdefghj',
...   hash,
... );
{false}
```
I'm unsure if this behavior is a potential bug or if I might be misusing or misunderstanding the usage of these two functions.

**Comment by CodesInChaos** [comment]
The `des` and `xdes` algorithms truncate passwords to 8 bytes, so this is expected behaviour. `bf` has a limit of 72 bytes. `md5` is unlimited. See [postgres docs](https://www.postgresql.org/docs/current/pgcrypto.html#PGCRYPTO-PASSWORD-HASHING-FUNCS).

You should never use the `des`, `xdes` and `md5` algorithms of the `crypt` function. Of the currently supported algorithms only `bf` (blowfish based crypt, aka bcrypt) is should be used with a sufficiently high iteration count/work factor.

**Comment by jrycw** [comment]
> The `des` and `xdes` algorithms truncate passwords to 8 bytes, so this is expected behaviour. `bf` has a limit of 72 bytes. `md5` is unlimited. See [postgres docs](https://www.postgresql.org/docs/current/pgcrypto.html#PGCRYPTO-PASSWORD-HASHING-FUNCS).
> 
> You should never use the `des`, `xdes` and `md5` variants of the `crypt` function. Of the currently supported algorithms only `bf` (blowfish based crypt, aka bcrypt) is should be used with a sufficiently high iteration count/work factor. (10 or higher)

Thanks so much for the information.
