### ISSUE TITLE
Provide a way to force close all connections to a database

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#6776]
This would be useful for certain anticipated branch-related dev workflows.

It doesn't need to be instant, necessarily. Maybe it would be enough to close all the client connections and then wait for everything to clean itself up?

**Comment by msullivan** [comment]
I am assigning this to @fantix aspirationally; if you don't think you'll have time, we can sync up about what I would need to do to implement it.
(And if you do have some time, you could make `DROP DATABASE` apply this unconditionally and then leave me to worry about making it conditional in some useful way.)

**Comment by themajashurka** [comment]
I was about to ask about this on Discord! So +1, would be very useful!

**Comment by themajashurka** [comment]
I was about to post a question on Discord of this feature (request). Would be very useful!
