### ISSUE TITLE
Can't make View example work

### ISSUE THREAD

**Issue by cosmophile** [edgedb/edgedb#681]
Hi, I'm working through the tutorial example of Movie and Person types and trying to incorporate a View example into it. 

These are my types with relevant properties and links:

```
  type Movie {
    required property title -> str;
    multi link cast -> Person; 
  }
  type Person {
    property first_name -> str;
    required property last_name -> str;
    property name :=
      .first_name ++ ' ' ++ .last_name
      IF EXISTS .first_name
      ELSE .last_name;
  }
  view PersonView := Person {
    stars_in := Person.<cast[IS Movie]
  }
```
When I run the following query, I get an **`Unexpected {`** error. 
```
SELECT PersonView { 
  stars_in {
    title 
  } 
} FILTER .name = 'Ryan Gosling';
```

However, when I run the query without destructuring the Movie type, I am able to get the `id` object of the movies:
```
SELECT PersonView { 
  stars_in 
} FILTER .name = 'Ryan Gosling';
```

Am I missing some obvious way to declare the shape of the Movie in the PersonView? Thanks for your help!

PS: I am able to get what I want by using the following query, but leaving the issue open in case you can help with the above regardless.
```
SELECT Person {
    name,
    stars_in := (SELECT
        Person.<cast[IS Movie] {
            title
        }
    )
}
FILTER Person.name = 'Ryan Gosling';
```

**Comment by elprans** [comment]
You have missed the colon in your first query, it should read:

```
SELECT PersonView { 
  stars_in: {
    title 
  } 
} FILTER .name = 'Ryan Gosling';
```

**Comment by 1st1** [comment]
@vpetrovykh Can we have a better error message for this case? Essentially add another production `ShapeElement_BRACE` which would error out suggesting how to fix this?
