### ISSUE TITLE
Disallow `00000000-0000-0000-0000-000000000000` as `.id`

### ISSUE THREAD

**Issue by CodesInChaos** [edgedb/edgedb#6815]
Currently it is possible to insert a document with an all-zero UUID as `.id` when using `allow_user_specified_id`.

This UUID is often used as a special value, e.g. to indicate that an entity is not stored in the database yet. If code encounters an object in the database with such an id it can cause bugs and possibly even security issues. Plus I don't really see any use-case where you'd want to store an all-zero id.

So I'd suggest rejecting inserts using this id, even when `allow_user_specified_id` is specified.

**Comment by msullivan** [comment]
I think it's unlikely we're going to add checks like this; the intention really is that `allow_user_specified_id` should typically be for easing migrations, and not the typical course of operations.

You should be able to put your own constraint on it in a base type for your application, though, if you want.
