### ISSUE TITLE
Unexpected CardinalityViolationError when querying schema with backlink and access policy

### ISSUE THREAD

**Issue by VictorPruefer** [edgedb/edgedb#6825]
We have implemented access policies in our data schema and highly appreciate them. However, we are running into unexpected _CardinalityViolationErrors_ when running certain types of queries. More specifically, the error occurs when the data schema has two levels of composition, i.e. A <- B <- C with A, B being access-constrained and B having a backlink to C. I could isolate the issue and created the following minimal reproducible sample schema:

## Setup
<details><summary>Minimal reproducible schema with House (A), Room (B), Lamp (C).</summary>
<p>

```edgeql
type House {
    required inhabitant: User;

    multi link rooms := (select Room filter .house = House);

    access policy owner_access
        allow all
        using (global current_user.id ?= .inhabitant.id);
}

type Room {
    required inhabitant: User;
    required house: House;

    multi lamps := (select Lamp filter .room = Room);

    access policy owner_access
        allow all
        using (global current_user.id ?= .inhabitant.id);
}

type Lamp {
    required room: Room;
}
``` 

</p>
</details> 

<details><summary>As sample data, I add two users A (Daniel) and B (Mike), and for each of them one house, room, lamp, i.e. there are no "overlapping" links.</summary>
<p>
Sample data query:

```edgeql
select House {
  *,
  inhabitant_name := .inhabitant.name,
  rooms: {
    *,
    inhabitant_name := .inhabitant.name,
    lamps: {
      *
    }
  }
}
``` 

Sample data:
```
[
  {
    "inhabitant_name": "Daniel",
    "rooms": [
      {
        "inhabitant_name": "Daniel",
        "lamps": [
          {
            "id": "c9e764f6-c9f2-11ee-8924-4b0973051bc3"
          }
        ],
        "id": "b2d48c26-c9f2-11ee-8924-0ba1e03f097a"
      }
    ],
    "id": "8968c4d8-c9f2-11ee-8924-c73ce3bc9ea1"
  },
  {
    "inhabitant_name": "Mike",
    "rooms": [
      {
        "inhabitant_name": "Mike",
        "lamps": [
          {
            "id": "c9e79282-c9f2-11ee-8924-978a329ed77d"
          }
        ],
        "id": "b2d4c9de-c9f2-11ee-8924-0f1043bf3558"
      }
    ],
    "id": "8968ce60-c9f2-11ee-8924-a76760288f39"
  }
]
``` 
</p>
</details> 

## Reproduction
The error occurs when querying type B, i.e. rooms. When querying type Room without links, it works fine.
### Query 1: Works ✅
```edgeql
select Room {
  *
}
``` 
**Expected behavior:** All rooms that the current user (Daniel) has access to are returned.
**Actual behavior:** Correct, only one room, namely _"b2d48c26-c9f2-11ee-8924-0ba1e03f097a"_ is returned.

### Query 2: Fails ❌
```edgeql
select Room {
  *,
  lamps: {*}
}
``` 
**Expected behavior:** The query first determines the rooms that the current user (Daniel) has access to, i.e. one, and then computes the lamps property for those.
**Actual behavior:** Fails with the following error:
```
CardinalityViolationError: required link 'room' of object type 'default::Lamp' is hidden by access policy (while evaluating computed link 'lamps' of object type 'default::Room')
``` 

This behavior is unexpected and appears buggy, as lamps are not access-protected. I expect the query to only return those rooms that I have access to and hence only to "hydrate" the lamps link for those rooms. Even when I extend the second query with a _filter_ by id and use the room's id where it is _known_ that it belongs to current user Daniel, the query fails.

### Conclusion
Our migrated data schema with access policies is currently unusable due to this behavior. We would appreciate any available workaround, as we may have to completely remove them otherwise.

## System:
- EdgeDB Version: 4.5+641a8f3
- EdgeDB CLI Version: 4.1.0+a8fe4d7
- OS Version: macOS 13.6

**Comment by raddevon** [comment]
I am able to reproduce here. Just to make things a little quicker for anyone trying to reproduce in the future, here's what I did. This is the complete schema that worked for me:

```esdl
module default {
  global current_user_id: uuid;
  global current_user := (
    select User filter .id = global current_user_id
  );
  type User {
    required name: str;
  }
  type House {
      required inhabitant: User;

      multi link rooms := (select Room filter .house = House);

      access policy owner_access
          allow all
          using (global current_user.id ?= .inhabitant.id);
  }

  type Room {
      required inhabitant: User;
      required house: House;

      multi lamps := (select Lamp filter .room = Room);

      access policy owner_access
          allow all
          using (global current_user.id ?= .inhabitant.id);
  }

  type Lamp {
      required room: Room;
  }
}
```

Then I ran these queries to seed the data:
```edgeql
for name in {'Mike', 'Daniel'} union (insert User {name := name});
```

```edgeql
set global current_user_id := (select User filter .name = 'Mike').id;
```

```edgeql
with inhab := (select User filter .name = 'Mike' limit 1)
  insert Lamp {room := (
    insert Room {inhabitant := inhab, house := (
      insert House {inhabitant := inhab}
    )}
  )};
```

```edgeql
set global current_user_id := (select User filter .name = 'Daniel').id;
```

```edgeql
with inhab := (select User filter .name = 'Daniel' limit 1)
  insert Lamp {room := (
    insert Room {inhabitant := inhab, house := (
      insert House {inhabitant := inhab}
    )}
  )};
```

Followed by the test queries:

```edgeql
select Room {
  *
}
```
and
```edgeql
select Room {
  *,
  lamps: {*}
}
```

One thing that may be helpful to you in the interim, @VictorPruefer: it looks like if you use the more idiomatic backlinks, the queries produce the expected results against your access policies. Here's a tweaked schema:

```esdl
module default {
  global current_user_id: uuid;
  global current_user := (
    select User filter .id = global current_user_id
  );
  type User {
    required name: str;
  }
  type House {
      required inhabitant: User;

      multi link rooms := .<house[is Room];

      access policy owner_access
          allow all
          using (global current_user.id ?= .inhabitant.id);
  }

  type Room {
      required inhabitant: User;
      required house: House;

      multi lamps := .<room[is Lamp];

      access policy owner_access
          allow all
          using (global current_user.id ?= .inhabitant.id);
  }

  type Lamp {
      required room: Room;
  }
}
```

This still probably needs @msullivan or @aljazerzen to take a look though and see why the original schema doesn't work.

**Comment by msullivan** [comment]
I would try to see if you can adapt @raddevon's advice; you probably can do the additional filtering and ordering even with a backlink, and we'd be happy to help with any follow up questions needed to help you figure that out.

I believe this to be working as intended.

The issue is that when doing `select Lamp filter .room = Room`, the reference to `.room` has to be filtered by access policies before it can be compared to `Room`. `required link`s are not allowed to be empty, so when a required link is accessed that requires filtering with an access policy, we wrap it with an `assert_exists`. 
This means that when computing `lamps`, we need to assert that the Room is visible before we can compare it in the filter, and so we get a failure.

I hope that makes sense; I'm happy to answer a follow-up question if needed.

**Comment by VictorPruefer** [comment]
Thanks @msullivan for the quick response. I can now see that I misinterpreted the access policies' behavior, particularly the part in the documentation that says: "_The access policies [...] define a “subgraph” of data that is visible to a particular query._". I assumed that as a consequence of a `Room` being inaccessible but `required` in `Lamp`, the lamp would be not accessible either. I think my intuitive understanding was that the data being returned from the query is tested against the access policy, not the "process" of retrieving it.

I have two follow-up questions and I'd appreciate your thoughts on them:
- It was my understanding that behind the scenes, `select Lamp filter .room = Room` is comparable to `.<room[is Lamp]`. Since the latter seems to handle the access policy without running into the same filtering issue you described, I'm wondering what the (technical) difference is and why the idiomatic backlink doesn't face the same problem.
- You mentioned the possibility of applying additional filtering and ordering on a backlink. Could you provide additional guidance on that matter, particularly when using the `select Room ...` statement as a subquery?

Thanks in advance.

**Comment by VictorPruefer** [comment]
@msullivan Just adding to my previous message: I've tried various approaches to combine the idiomatic backlink with a `filter` or `order by` statement to achieve the desired result without access policy errors - however, no luck so far. The following excerpt (which works fine in the query)...
```
multi rooms := (
     with unordered_rooms := .<house[is Room]
     select unordered_rooms order by .some_number asc
);
```
...doesn't work in the data schema, unfortunately. It triggers a `edb.errors.UnsupportedFeatureError: including a shape on schema-defined computed links is not yet supported` error (which looks a bit confusing to me at first as I didn't specify any shape in the select query). So any suggestion here would be appreciated.
