### ISSUE TITLE
SELECT Object IF EXISTS Object ELSE INSERT 

### ISSUE THREAD

**Issue by cosmophile** [edgedb/edgedb#684]
Hi, I tried to use the IF...ELSE and EXISTS clauses in order to construct a query that either selects an item if it exists or else inserts it. So since I can do the following:
```
SELECT 1 IF EXISTS (SELECT Person FILTER .name = 'Ryan Gosling') 
....... ELSE (SELECT 0);
```
...I tried to do
```
SELECT Person FILTER .name = 'Ryan Gosling' 
....... IF EXISTS (SELECT Person FILTER .name = 'Ryan Gosling') 
....... ELSE (SELECT <int64>{});
```
However I get the error: **QueryError: operator 'std::IF' cannot be applied to operands of type 'std::bool', 'std::bool', 'std::int64'**

Am I making some syntax error or is this kind of selection not allowed? I assumed it would work because the documentation on IF states `anytype` as the left assignment, but I have not been able to figure out how to make it work with my schema types. 

Thank you very much for your help.

**Comment by cosmophile** [comment]
Soon after opening this and trying various permutations, I realized that the left and right assignments need to be identical in type and be a singleton on both ends if I want to make an insert statement.

Closing this.

**Comment by 1st1** [comment]
@vpetrovykh should we enhance our error message here?

**Comment by cosmophile** [comment]
Another related question / error message confusion: 

This is how I am inserting a Person if they don't exist:
```
SELECT ( SELECT Person FILTER .name = 'Zendaya' LIMIT 1 ) 
....... IF 'Zendaya' IN Person.name 
....... ELSE (INSERT Person { last_name := 'Zendaya'  }  );
```
I am also able to use `FOR x IN ...` to separately _either_ insert or select multiple persons. However, if I try to use the above statement to try to do both at once in my `UNION` clause (i.e, select x if it exists or insert it if it doesn't), like this:
```
FOR x IN { 
....... ( name := 'Zendaya' ), 
....... ( name := 'Madonna') 
....... } UNION ( 
....... SELECT ( SELECT Person FILTER .name = x.name LIMIT 1 ) 
....... IF x.name IN Person.name 
....... ELSE (INSERT Person { last_name := x.name  }  ) 
....... );
```
I get the following error message (even if both Persons exist): **InternalServerError: missing FROM-clause entry for table "__derived__|x@@w-1~2"**

It's clear to me from the message that I shouldn't be trying this, but it would be a common use case for me and others so I want to make sure there isn't a right way to attempt this using `FOR`. Hope my question is clear.

Thank you again.

**Comment by elprans** [comment]
The `InternalServerError` is a bug, but the real issue here is that you cannot really do conditional `INSERT` like that, and that has to do with how Postgres handles DML CTEs internally -- it always executes the statement regardless of whether the logical flow reaches it or not.  EdgeDB currently allows nesting `INSERT` arbitrarily, but we will have to tighten the rules, and only allow it in the top-level `WITH` block and as a value expression in another `INSERT` statement.

Unfortunately, there's currently no good way to do conditional `INSERT` in a single statement other than via the `ON CONFLICT` clause in SQL, but we currently lack the syntax to do that.  One possible way is to specialize the `??` operator,  so:

```
INSERT Movie {
    cast := (
        FOR actor_name IN {'Zednaya', 'Madonna'}
        UNION (
            (SELECT Person FILTER .name =  actor_name) 
            ?? (INSERT Person { name := actor_name})
        )
    )
}
```

**Comment by cosmophile** [comment]
Thank you for taking the time to explain that. Your suggested syntax looks very clear and I'll be on the lookout for that ahead.

For now I understand that I cannot use either of the queries I constructred in my example, because `SELECT...IF EXISTS...ELSE INSERT` will always insert the item anyway. Gotcha. So my approach would be to run all the SELECT queries separately as a `FOR x IN...` and construct the `INSERT Movie` statement in my Python/Node script based on the result of that.

**Comment by elprans** [comment]
To be clear `SELECT Foo ?? Bar` already works as a concise spelling of `SELECT Foo IF EXISTS FOO ELSE Bar`, it's just that `INSERT` specifically doesn't respect the flow and is always executed.

**Comment by vpetrovykh** [comment]
I do like this syntax sugar because it seems to be quite a natural use of `??`. I'm all for this if we could do it reliably and have clear errors for when this construct cannot be cleanly compiled.

**Comment by Mulugruntz** [comment]
Hi,

Is there no way to insert a record if not exist as of today?
Maybe an "exclusive" mode? (silent, etc...)

Thanks!

**Comment by elprans** [comment]
There is a (slightly verbose) way using the `FOR` statement:

```
FOR _ IN {
    (SELECT true FILTER (NOT EXISTS (<your-condition>)))
}
UNION (
    INSERT <your-insert>
)
```

**Comment by Mulugruntz** [comment]
Looks more like a hack ^^.
I'll use it for now then ;-). Thanks @elprans again

**Comment by Mulugruntz** [comment]
I've created a gist, if anyone needs...
https://gist.github.com/Mulugruntz/97d904db4446428d0815dd626b812cbd

**Comment by 1st1** [comment]
@elprans @vpetrovykh anything to act on here?

**Comment by elprans** [comment]
Yes, the pattern is quite useful, so we need to look into implementing the coalesce specialization as I alluded to in https://github.com/edgedb/edgedb/issues/684#issuecomment-515720863

**Comment by msullivan** [comment]
Remaining pieces:
[ ] Update query normalization so that this works for constants
[ ] Support nested inserts

**Comment by msullivan** [comment]
I'm going to close this in favor of https://github.com/edgedb/edgedb/issues/1639 which reflects our new strategy.
