### ISSUE TITLE
`MissingRequiredError` no longer thrown. Now it's just an ISE

### ISSUE THREAD

**Issue by corbinday** [edgedb/edgedb#6845]
I noticed recently that I no longer get the `MissingRequiredError` like mentioned [here](https://www.edgedb.com/docs/guides/migrations/tips#adding-a-required-link) when trying to apply a migration that doesn't properly set a newly required property. Instead, the migration fails with the following error:

```
edgedb error: InternalServerError: RuntimeError: unhandled error while calling interpret_backend_error(); run with EDGEDB_DEBUG_SERVER to debug.
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: RuntimeError: unhandled error while calling interpret_backend_error(); run with EDGEDB_DEBUG_SERVER to debug.
edgedb error: error in one of the migrations
```

I tested this out with edgedb versions `4.5`, `4.4`, `4.3`, `4.0`, and `3.5`, so I think it's an issue introduced by the recent CLI `4.1` release.

- EdgeDB Version:
- EdgeDB CLI Version:
- OS Version:

Steps to Reproduce:

1. Init a project with the below schema.
2. Seed some data without lastName's.
```edgeql
for name in { 'hello', 'world'} union ( insert User { name := name } );
```
3. Uncomment the required lastName property.
4. Attempt migration.

Schema:

```edgeql
module default {
    type User {
        name: str;
        # required lastName: str;
    }
}
```

**Comment by msullivan** [comment]
This is actually a pure edgedb issue, though your diagnosis of it being introduced by CLI 4.1 is also correct:
The bug is that edgedb doesn't produce a proper error message here if the DDL is executed *outside of a transaction*. CLI 4.1 stopped wrapping migration applications in transactions.

**Comment by corbinday** [comment]
Was the CLI intentionally changed to stop wrapping migrations in transactions, or is that a bug too?

**Comment by msullivan** [comment]
> Was the CLI intentionally changed to stop wrapping migrations in transactions, or is that a bug too?

That was intentional.
