### ISSUE TITLE
Unable to create more than 1 Python pool

### ISSUE THREAD

**Issue by cosmophile** [edgedb/edgedb#685]
I'm attempting to create multiple python servers for multiple edgedb databases. I'm not very familiar with Python (eagerly awaiting the TS driver) so I used the async connection pool example [here](https://edgedb.com/docs/clients/00_python/usage#connection-pools).

However, as soon as I create more than 1 web app (running at different ports of course, and connecting to different databases, but as the same user), I get the following error on querying the second app:

```
edgedb.errors.InternalServerError: unhandled errors in a TaskGroup; 1 sub errors: (ConnectionError)
+ ConnectionError: lost connection to the worker during a call
|   File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/baseport.py", line 65, in new_compiler
|     await compiler_worker.call('connect', dbname, dbver)
|   File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/procpool/pool.py", line 108, in call
|     data = await self._con.request(msg)
|   File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/procpool/amsg.py", line 160, in request
|     return await waiter

```
I'm working around this by creating long-running connections to each individual db in the same server app, using multiple `async_connect` calls at the app level instead of a single call to `create_async_pool`, but I'm pretty sure it's a sub-optimal solution. (Although still better than creating the connection to a specific database at the request level, which is much slower.)

Any suggestions on how to make connections to multiple databases within the same async pool, or creating multiple async pools that can be running within different apps?

Thanks.

**Comment by elprans** [comment]
Interesting.  Do you have some code to share to help reproduce this?

**Comment by cosmophile** [comment]
I troubleshooted (troubleshot?) it to the `min_size` argument of `create_async_pool` (default value is 10). I am working on a tiny server and it ran out of workers on a single app. Setting `min_size` to 2 works fine. 

Closing with thanks.
