### ISSUE TITLE
Can't create migration after changing pgvector length

### ISSUE THREAD

**Issue by MrFoxPro** [edgedb/edgedb#6854]
- EdgeDB Version: 4.5+28216a1
- EdgeDB CLI Version: 4.0.2+be1da73
- OS Version: GNU/Linux 6.7.3-arch1-1

```esdl
scalar type SearchEmbeddings extending ext::pgvector::vector<384>;
abstract type DealBase {
   embeddings: SearchEmbeddings;
}
```

create some DealBase with pgvector (attached example json with vector of 384 length)
[deal.json](https://github.com/edgedb/edgedb/files/14292723/deal.json)

Change pgvector length (e.g. to 768) and try to apply create migration. I'm getting following error:

```
edgedb error: EdgeDB could not resolve migration with the provided answers. Please retry with different answers.
```

**Comment by msullivan** [comment]
We should produce a better failure than this, probably, but I think even if that is fixed it probably won't be possible to migrate directly like this.

You'll need to drop and recreate the `embeddings` field or you'll want to create a new search embeddings type, change the type in place (providing a conversion expression), and then drop the old type and rename
