### ISSUE TITLE
Optimize the IR compiler

### ISSUE THREAD

**Issue by ambv** [edgedb/edgedb#694]
Currently the IR compiler is pure Python and it takes a long time for most EdgeQL queries, most likely in edgeql/compiler/func.py. Investigate and implement ways to make it faster.

**Comment by ambv** [comment]
An aggregation of `edb/server/compiler/compiler.py:_compile_ql_query()` calls over all unit tests shows that:
- `compile_ast_to_ir` takes 80% of time
- from that, 42% is just `compile_BinOp`

This is the first thing I'll be looking at optimizing. Interestingly, there is a lot of time spent in those as well:
- `edb/schema/types.py:derive_subtype` takes 25% of the cumulative time
- `edb/common/ast/base.py:_check_type` takes 18% of the cumulative time and the longest "per call"

The cast distance calculation that was suspected as taking a lot of time, is not *that* expensive alone (although it still clocks at 10.5% of the cumulative time). I'll look into it while investigating `compile_BinOp`.

In terms of code structure, we're creating a ton of AST objects (over 2 mil in my sampling) which I'll look into decreasing. `edb/common/ast/base.py:__init__` also does a lot of work (cumulative time clocking at 18% which I suspect is due to type checking that I already covered above).

We're calling a lot of `__hash__` functions (50 mil calls during my sampling), out of which `UUID.__hash__` is dominant at 47 mil calls (taking 22.5 seconds in total). Maybe we can decrease that.

Raw data: https://gist.github.com/ambv/7b9e6b72d923ec9845c549e8fc47e6eb

**Comment by 1st1** [comment]
Thanks! A few questions:

* What was the query you profiled? Did you profile more than one?
* Ideally we need to profile like 10 queries of various complexity and features. Use `edb inittestdb` to generate test databases and then you can profile some queries from our tests.
* Can you share the test script you used to generate this?

For example, the high cost of `compile_BinOp` could also be explained if the benchmark query was `SELECT a + b`. Moreover, since operators in EdgeQL are compiled in the same way we compile function calls, the high cost of compiling them is explained by the same complex quadratic algorithm we use for our multiple dispatch.

> We're calling a lot of __hash__ functions (50 mil calls during my sampling), out of which UUID.__hash__ is dominant at 47 mil calls (taking 22.5 seconds in total). Maybe we can decrease that.

Interesting. We can probably use our own UUID implementation from https://github.com/MagicStack/py-pgproto/blob/master/uuid.pyx.  We can add a custom `__hash__` implementation that would cache the computed hash to make it as fast as possible.

**Comment by ambv** [comment]
This is an aggregate from all tests. I specifically didn't want a single query because it would likely not be representative. This is an average of 17k queries.

**Comment by 1st1** [comment]
> This is an aggregate from all tests. I specifically didn't want a single query because it would likely not be representative. This is an average of 17k queries.

Wow, that's quite interesting! Not sure about the "not representative" part though. I don't think that our test queries are representative of real world kind of queries that users will benchmark EdgeDB with or use. Specifically, a lot of unit test queries test a particular feature like one function call or a binary operator multiple times over and over again; most queries are simple on purpose to isolate a specific feature.  Also make sure we don't profile DDL queries -- they go through completely different code paths and we aren't interested in optimizing them at all right now. Only `SELECT` / `INSERT` and `UPDATE` are interesting; I'd start with only `SELECT` to keep the results simple.

It would be interesting to benchmark queries from this blog post: https://edgedb.com/blog/edgedb-1-0-alpha-1. They are closer to queries we expect people to use with EdgeDB extensively. And we will use them in our alpha 2 blog post. 

Could you take a look at them too?  You can use the schema from this repo https://github.com/edgedb/webapp-bench; the queries are here: https://github.com/edgedb/webapp-bench/blob/master/_edgedb/queries_async.py.

**Comment by ambv** [comment]
Running on the webapp benchmarks, we have a related but different picture:
- compiling AST to IR takes 78% of the time
- compiling IR to SQL takes 21% of the time

In IR compilation, compiling view shapes in set takes half of this time. This will be what I'll be investigating next. But first, runtime type checking is 14.9% of the time spent which is why making it configurable looks like the lowest hanging fruit to me.

In SQL compilation, almost all time is spent in edb/pgsql/compiler/shapecomp.py:compile_shape, out of which the call to compile_OperatorCall is 20% so I'll be looking at that next.

As I mentioned in the meeting yesterday, I was surprised to see 33k AST objects created for just 25 queries. I'll be looking into figuring out whether we really need 1.3k objects per query. 64% of those are created in IR compilation, the remainder in SQL compilation. Similarly, there's quite a lot of ordered sets (45k), pathids (25.6k), and structs (22.8k).

Here's an aggregation of `edgedb_json_async` and `edgedb_repack_sync` after running all three queries `get_movie()`, `get_person()`, `get_user()`: https://gist.github.com/ambv/9b124e868910950b051f625fff263dc3

**Comment by ambv** [comment]
## Current state of things for `edb.server.compiler.compiler._compile`

- INSERT statements from the benchmark: http://langa.pl/random/graphs/compile-bench-inserts-2019-11-27.svg
- SELECT statements from the benchmark: http://langa.pl/random/graphs/compile-bench-selects-2019-11-27.svg
- all queries in tests: http://langa.pl/random/graphs/compile-tests-2019-11-27.svg

SELECTs are an aggregation of `edgedb_json_async` and `edgedb_repack_sync` as in the comment above.

These show all phases and it's pretty clear we can shave a lot simply by replacing pickle with something faster. Then we'll hunt further optimizations.

**Comment by ambv** [comment]
Python 3.7.5:
compile_edgeql_script: Mean +- std dev: 2.78 ms +- 0.07 ms
compile_edgeql_script_webapp_configure_system: Mean +- std dev: 45.4 ms +- 1.2 ms
compile_edgeql_script_webapp_get_movie: Mean +- std dev: 279 ms +- 79 ms
compile_edgeql_script_webapp_get_person: Mean +- std dev: 272 ms +- 65 ms
compile_edgeql_script_webapp_get_user: Mean +- std dev: 126 ms +- 3 ms
compile_edgeql_script_webapp_insert_movie: Mean +- std dev: 183 ms +- 45 ms
compile_edgeql_script_webapp_insert_person: Mean +- std dev: 67.5 ms +- 1.5 ms
compile_edgeql_script_webapp_insert_review: Mean +- std dev: 100 ms +- 2 ms

Python 3.8.1rc1:
compile_edgeql_script: Mean +- std dev: 2.29 ms +- 0.09 ms
compile_edgeql_script_webapp_configure_system: Mean +- std dev: 35.6 ms +- 1.0 ms
compile_edgeql_script_webapp_get_movie: Mean +- std dev: 190 ms +- 11 ms
compile_edgeql_script_webapp_get_person: Mean +- std dev: 192 ms +- 5 ms
compile_edgeql_script_webapp_get_user: Mean +- std dev: 107 ms +- 11 ms
compile_edgeql_script_webapp_insert_movie: Mean +- std dev: 154 ms +- 13 ms
compile_edgeql_script_webapp_insert_person: Mean +- std dev: 54.6 ms +- 4.1 ms
compile_edgeql_script_webapp_insert_review: Mean +- std dev: 79.4 ms +- 6.5 ms

**Comment by ambv** [comment]
Comparison between EdgeDB 655230a20a6b728fe18bfe36876bb4fb918bb4d8 and master + #1028:

```
compile_edgeql_script_simple: Mean +- std dev: 2.24 ms += 0.07 ms (46.25% faster)
compile_edgeql_script_webapp_configure_system: Mean +- std dev: 49.8 ms += 22.4 ms (20.46% faster)
compile_edgeql_script_webapp_get_movie: Mean +- std dev: 209 ms += 7 ms (31.01% faster)
compile_edgeql_script_webapp_get_person: Mean +- std dev: 242 ms += 7 ms (24.83% faster)
compile_edgeql_script_webapp_get_user: Mean +- std dev: 135 ms += 7 ms (13.54% faster)
compile_edgeql_script_webapp_insert_movie: Mean +- std dev: 135 ms += 6 ms (39.96% faster)
compile_edgeql_script_webapp_insert_person: Mean +- std dev: 55.1 ms += 13.5 ms (40.05% faster)
compile_edgeql_script_webapp_insert_review: Mean +- std dev: 79.9 ms += 14.1 ms (41.77% faster)
```

32.2% performance gain on average.

**Comment by 1st1** [comment]
Closing this one.
