### ISSUE TITLE
Re-commit of unchanged migration causes `InternalServerError`

### ISSUE THREAD

**Issue by imbolc** [edgedb/edgedb#695]
![image](https://user-images.githubusercontent.com/747996/63206392-9d3f7d80-c0dd-11e9-8aae-20c3b1cd5be4.png)

I was using docker version of the db.

**Comment by elprans** [comment]
This is already fixed in `824f14a687fc3a968238a23be32ca32b3afe973f`.

**Comment by imbolc** [comment]
Ah, sorry, I didn't look at the version of docker build. I just checked dev version and there's no such error.
