### ISSUE TITLE
Get rid of `astmatch` infrastructure

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#6980]
It is cool, but probably we wouldn't use it anymore now that pattern matching is in the language.

I think we use it in one place, in `DistinctConjunctionExpr`, where we try to detect uses of `_is_exclusive` inside a constraint body in a substantially more general way than is supported in most of the rest of the codebase. (Which is happy to just look at whether a constraint is `std::exclusive`)

**Comment by dnwpark** [comment]
Removed in #7159
