### ISSUE TITLE
ISE: cannot create root rvar for non-object path

### ISSUE THREAD

**Issue by mkhlsavin** [edgedb/edgedb#6988]
- EdgeDB Version: 5.0-beta.1+15775e6
- EdgeDB CLI Version: 4.1.0+127aeb9
- OS Version: Win 11

Steps to Reproduce:

1. Try to make a migration `edgedb migrate` with attached initial migration: 
[00001_edgeql.txt](https://github.com/edgedb/edgedb/files/14491317/00001_edgeql.txt)

**Comment by msullivan** [comment]
Here's a reduced version:
```
  CREATE GLOBAL val := ('asdf');
  CREATE FUNCTION test() -> OPTIONAL str {
      USING (GLOBAL val)
  };
```

There is a dumb bug in how we handle `single` computed globals, where we try to cache them but get our wires crossed.

For you, this is happening with the global variable `default::dayClosure`. A workaround would be to declare it as `multi`.

Fix forthcoming.
