### ISSUE TITLE
Poor error message when applying migration with required value being set to {}

### ISSUE THREAD

**Issue by jollygreenlaser** [edgedb/edgedb#7011]
- EdgeDB Version: EdgeDB Version: 4.4+596d0e4 on Ubuntu 22.04.3 LTS
- EdgeDB CLI Version: EdgeDB CLI 4.1.0+a8fe4d7

Migration was:

```
CREATE MIGRATION m1jto6s4t5bbqc4aob7nfiuirktl6aq4ipmtri6qs3jzidevtbkkza
    ONTO m14qywourfxnhrnufcfe5p277h7qajcrdqueifecd75caewdmzdvda
{
  ALTER TYPE default::Thing {
      CREATE REQUIRED PROPERTY thing_1: std::str {
          SET REQUIRED USING (<std::str>{});
      };
      CREATE REQUIRED PROPERTY thing_1: std::str {
          SET REQUIRED USING (<std::str>{});
      };
  };
};
```

Applying, to the same server that just made it, gave:

```
edgedb error: InternalServerError: RuntimeError: unhandled error while calling interpret_backend_error(); run with EDGEDB_DEBUG_SERVER to debug.
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: RuntimeError: unhandled error while calling interpret_backend_error(); run with EDGEDB_DEBUG_SERVER to debug.
edgedb error: error in one of the migrations
```

Turns out I was silly and forgot to delete an instance of the type. I figured this out by using `journalctl -u edgedb-server-4 -e` and reading the logs, thanks for that trick. I saw:

```
Mar 07 17:04:48 rurl edgedb-server[946]: ERROR 1096 2024-03-07T17:04:48.474 postgres: column "dc276640-dce7-11ee-a18c-5377f3f0817d" of relation "cc6a94a0-da52-11ee-a8a2-c19739d96ede" contains null values
```

And went ohhhh duh yep I know what I forgot to delete. 

But: Would be nice if the error message was better. I swear I've seen better failure messages for a similar "added a required field with an empty set using" but for some reason this one decided to give a useless message.

**Comment by jollygreenlaser** [comment]
PS I can't seem to find `EDGEDB_DEBUG_SERVER` in the docs

**Comment by msullivan** [comment]
Thanks for the report!

This is already fixed by https://github.com/edgedb/edgedb/pull/6852. We'll try to release 4.6 on Friday or Monday with it.

You are right that it used to work: the bug in the server is actually quite longstanding, but it worked right when the migrations were run *in a transaction*.  In https://github.com/edgedb/edgedb-cli/pull/1189 we stopped running migrations in a transaction, which exposed this bug more broadly.

It looks like you can get the old behavior with `--single-transaction`, though, if you run into this again before we fix it.

**Comment by msullivan** [comment]
> PS I can't seem to find `EDGEDB_DEBUG_SERVER` in the docs

It's an internal debug flag. You'd set it as an environment variable when running the server.
Honestly it wouldn't really help here. I think it is mostly a hint to edgedb developers who are getting this error while running the test suite.
Probably we should change it, though ISEs aren't really supposed to happen anyway

**Comment by jollygreenlaser** [comment]
Neat, thanks. 

I promise I did some searches before submitting!
