### ISSUE TITLE
Initial migration fails after upgrading to v4.6

### ISSUE THREAD

**Issue by lsdch** [edgedb/edgedb#7056]
- EdgeDB Version: 4.6+0632dff
- EdgeDB CLI Version: 4.1.0+03ae624
- OS Version: Linux Mint 21.3

After I reset my dev database instance, and upgrade to v4.6, I get a cryptic error that suggests a bug was introduced in 4.6 (everything works fine in 4.5).

Steps to Reproduce:

1. Run `edgedb project init` with `server-version="4.6'` in `edgedb.toml`
2. When applying initial migrations, the following error is thrown:
```
edgedb error: InternalServerError: relation "edgedbpub.19b9270f-e2cf-11ee-86bc-774ffaf8bef2_t" does not exist
  Server traceback:
      edb.errors.InternalServerError: relation "edgedbpub.19b9270f-e2cf-11ee-86bc-774ffaf8bef2_t" does not exist
edgedb error: error in one of the migrations
```

Schema:

The schema definition is too large to be provided in the issue body, but I can upload it somewhere if that helps in any way.

**Comment by msullivan** [comment]
Yes, I'll need the schema in order to debug the issue. (And ideally the migration scripts too.)
If you don't want to post them publicly you can email them to `sully at edgedb dot com`

**Comment by lsdch** [comment]
Here is a gist with all the schema definition files : https://gist.github.com/lsdch/22ea6f875e7df4481e73da26dd0ca891
And here is one with the migration: https://gist.github.com/lsdch/bd3b54d8221547bc301fbb28b0de6c0e

(In case this is relevant)
I regenerated the migration file from scratch, resulting in the relation identifiers reported in the error message to change. Here is the updated error message:
```
edgedb error: InternalServerError: relation "edgedbpub.97608d4f-e2e3-11ee-8835-c1c46ce2e0ff_t" does not exist
  Server traceback:
      edb.errors.InternalServerError: relation "edgedbpub.97608d4f-e2e3-11ee-8835-c1c46ce2e0ff_t" does not exist
edgedb error: error in one of the migrations
```

**Comment by msullivan** [comment]
Thanks!

The tables names in our underlying postgres database are based on the uuids of the types, so change is expected

**Comment by msullivan** [comment]
I also have a workaround for your schema: try dropping the shape in the defintion of `default::current_user`. It isn't necessary, and the bug is related to it.

**Comment by msullivan** [comment]
Minimized test case:
```
  create global current_user_id -> uuid;
  create type User;
  create global current_user := (
      SELECT User { * }
      FILTER .id = global current_user_id
  );

  create type Meta {
      create link created_by_user: User {
          set default := (global current_user);
      };
  };

  insert Meta;
```

**Comment by msullivan** [comment]
Oh or just:
```
  create global current_user_id -> uuid;
  create type User;
  create global current_user := (
      SELECT User { * }
      FILTER .id = global current_user_id
  );

  select global current_user;
```

**Comment by lsdch** [comment]
I managed to upgrade to 4.6 after removing the shape, as you suggested. Thank you so much ! :pray:
