### ISSUE TITLE
Add a temporary config to switch query cache mode

### ISSUE THREAD

**Issue by fantix** [edgedb/edgedb#7102]
Before the end goal of proper persistent query cache is achieved with Postgres functions, we'd like to have a config to control the cache mode the server is running in, that is `Config._query_cache_mode`, which is an enum of:

* `IN_MEMORY` - query cache lives in memory and resets on server restart, no persistent cache is used
* `REG_INLINE` - query cache (the actual SQL) is placed inline in the cache registration table
* `PG_FUNC` - the actual SQL is encapsulated in Postgres functions and the cache registration table contains function calls
* `DEFAULT` - the distribution-default mode, currently `REG_INLINE` but it will be `PG_FUNC` in a future release

This will be a system config and server restart is needed for changes to be effective. If the effective config value changes on start, the cache registration table will be cleared.

This config is not permanent and will be dropped once the persistent cache system is stable.

**Comment by 1st1** [comment]
Looks good Fantix!
