### ISSUE TITLE
No keyboard echo until terminal resize | edgedb shell in podman

### ISSUE THREAD

**Issue by buckle2000** [edgedb/edgedb#713]
I tried to run edgedb shell with this command: `podman exec -it edgedb-server edgedb -u edgedb`. The `edgedb>` prompt and the bottom `[F3] [F4] [F5]` status bar were invisible (no key echo either) until I resized the terminal window. I could type `\q` to exit. This is the case for both gnome-terminal and xterm.
bash works fine in podman, so I suspect this problem is specific to edgedb.

Example session:
```
EdgeDB 1.0.alpha.1
Type "\?" for help.
(I type \?)
  \c DBNAME            connect to database DBNAME
  \l                   list databases
  \errverbose          show most recent error message at maximum verbosity
  \q or "exit"         quit
(I type \q)
```

**Comment by 1st1** [comment]
@tailhook Please see if this is applicable to the new CLI and if we need / can do anything about this.

**Comment by tailhook** [comment]
I'm assuming it's this issue: https://github.com/containers/libpod/issues/351 Which should be fixed now.
