### ISSUE TITLE
Dubious error when attempt to migrate twice.

### ISSUE THREAD

**Issue by buckle2000** [edgedb/edgedb#714]
If you run the following block twice,
```
start transaction;
create migration a to {
    type Person {
        required property first_name -> str;
        required property last_name -> str;
    }
};
commit migration a;
commit;
```
you will get `InternalServerError: string index out of range`.
The schema doesn't matter in this case. It must only remain the same.

**Comment by elprans** [comment]
This has been fixed in master via #686. but as this seems to be a frequent issue, I backported the fix to the alpha-1 branch (via c92df1339e1a).

**Comment by buckle2000** [comment]
I think there should be some sort of error message for this.

**Comment by elprans** [comment]
@buckle2000 No-effect migrations are not an error.
