### ISSUE TITLE
`bool` field is not set when using mutation rewrites

### ISSUE THREAD

**Issue by hrasoa** [edgedb/edgedb#7148]
- EdgeDB Version: 4.7+39afbed
- EdgeDB CLI Version: EdgeDB CLI 4.0.0-alpha.1+285f84f
- OS Version: macOS Sonoma Version 14.4 (23E214)

Steps to Reproduce:

Create or edit a `Bookmark`, `published_at` is never set.

In my understanding it should set `published_at` when I create with `is_draft = false` , or when I update from `is_draft = true` to `is_draft = false`, but in both cases `published_at` is never set. There is no errors.

Schema:
```edgeql
  abstract type HasDraft {    
    published_at: datetime {
      rewrite insert using (
        datetime_of_statement()
          if __specified__.is_draft = false
          else .published_at
      );
      rewrite update using (
        datetime_of_statement()
          if (__specified__.is_draft = false and __old__.is_draft = true) 
          else __old__.published_at
      );
    }
    required is_draft: bool;
  }

  type Bookmark extending HasDraft {
  };
```

**Comment by aljazerzen** [comment]
I don't think this is a bug, you are probably mis-using `__specified__`.

`__specified__` contains one boolean for each of the properties (and links) of the subject, indicating if that property has been specified in the insert query.

In your case, `is_draft` is required so user will always have to specify it, which means that `__specified__.is_draft` will always be `true`.

You probably meant this:
```
      rewrite insert using (
        datetime_of_statement()
          if __subject__.is_draft = false
          else .published_at
      );
```
or idiomatically:
```
      rewrite insert using (
          if not .is_draft
          then datetime_of_statement()
          else .published_at
      );
```

**Comment by aljazerzen** [comment]
This is the full schema:
```
abstract type HasDraft {
  published_at: datetime {
    rewrite insert using (
      if .is_draft
      then .published_at
      else datetime_of_statement()
    );
    rewrite update using (
      if __old__.is_draft and not .is_draft
      then datetime_of_statement()
      else __old__.published_at
    );
  }
  required is_draft: bool;
}

type Bookmark extending HasDraft {
};
```

**Comment by hrasoa** [comment]
Thanks that's working. So what I had initially works only if `is_draft` is optional ?

**Comment by aljazerzen** [comment]
No, what you had initially works if `is_draft` is optional or required. It being required just gave me a hint what you meant with the rewrite.

Let me try to explain `__specified__` again:
```
type X {
  a: str;
  b: str;
  c: str;
}

insert X { a := 'a', b:= 'b' }   ->   __specified__ = { a := true, b := true, c := false }
insert X { a := 'a', c:= 'c' }   ->   __specified__ = { a := true, b := false, c := true }
insert X { }                     ->   __specified__ = { a := false, b := false, c := false }
```

**Comment by hrasoa** [comment]
Ok got it, thanks !
