### ISSUE TITLE
Backup options?

### ISSUE THREAD

**Issue by cosmophile** [edgedb/edgedb#720]
I've read the docs a couple of times now but haven't run across any information about how to back up databases. How can this be achieved? 

I know it's PostgreSQL under the hood so I'm also curious if EdgeDB would or does enable any direct interaction with those tables as such, as far as reading/exporting data is concerned.

Thanks!

**Comment by agritheory** [comment]
See #702. TL;DR: not currently available, high-ish priority, expected to be included in the 1.0 release

**Comment by cosmophile** [comment]
I did see that, although the conversation seemed focused on schema, not data. But thanks for the reply.

**Comment by elprans** [comment]
@cosmophile `edgedb dump` will be a thing soon, which, aside from backup, would be required to upgrade to newer versions of EdgeDB (in-place upgrade support is also planned).

**Comment by 1st1** [comment]
`edgedb dump` and `restore` are implemented in alpha 2
