### ISSUE TITLE
Constraint: insert one object type or the other, but not both.

### ISSUE THREAD

**Issue by ishea1999** [edgedb/edgedb#7205]
Schema migration error: InternalServerError: UnresolvedReferenceError: reference to an undefined item default::NULL in default::CourseDeployment@std::expression@@(((.school IS NOT NULL) AND (.user IS NULL)) 
OR ((.school IS NULL) AND (.user IS NOT NULL)))
  Hint: This is most likely a bug in EdgeDB. Please consider opening : reference to an undefined item default::NULL in default::CourseDeployment@std:
an issue ticket at https://github.com/edgedb/edgedb/issues/new?templal IS NULL) AND (.user IS NOT NULL)))te=bug_report.md  

- EdgeDB Version: 4.0-rc.2+f457342
- EdgeDB CLI Version: EdgeDB CLI 4.1.0+127aeb9
- OS Version: Windows 10 Home 

Steps to Reproduce:

1. insert one object type or the other, but not both.
2.

Schema:
  ```type CourseDeployment extending Timestamped {
    required course: Course;
    school: School;
    user: User;
    audience: Audience;
    link stageDeployment := .<courseDeployment [is StageDeployment];
    constraint expression on (
    (__subject__.school IS NOT NULL AND __subject__.user IS NULL)
    OR
    (__subject__.school IS NULL AND __subject__.user IS NOT NULL)
);

  }```

**Comment by ishea1999** [comment]
constraint expression on ( (exists(__subject__.school)  AND not exists(__subject__.user)) OR (exists(__subject__.school)  AND not exists(__subject__.user)) ); worked just fine

**Comment by elprans** [comment]
The ISE wrapping _is_ a (usability) bug though.

**Comment by dnwpark** [comment]
Message improved in #7351
