### ISSUE TITLE
Property-level annotations

### ISSUE THREAD

**Issue by agritheory** [edgedb/edgedb#723]
By supporting property-level annotations, human-readable property names could be stored as part of the DB schema, otherwise something like this would need to be stored in another table/schema/object.

    tutorial> type Status { 
    .........     annotation title := 'Activity status'; 
    .........     annotation description := 'All possible user activities'; 
    .........     required property name -> str { 
    .........         annotation title := 'User Name'; 
    .........         constraint exclusive 
    .........     } 
    ......... };

**Comment by elprans** [comment]
Annotations are already supported on all schema objects, including properties.  Is there something else you had in mind?

**Comment by agritheory** [comment]
I think I got hung up on this sentence in the documentation:

> Annotations are named values associated with schema items and are designed to hold arbitrary schema-level metadata represented as a `str`.

Which I read as "annotations are only available at the schema level, not the property level". When I tried to add an annotation in the client, I ran into another error that make it seem like it wouldn't be possible, but it looks like I misread that too.

**Comment by agritheory** [comment]
Sorry @elprans, a related question, probably not worth opening a new issue about... it is currently _not_ possible to have custom annotations, only `title` and `description`?

**Comment by elprans** [comment]
You can define annotations in the schema like this:

```
abstract annotation foo_anno;

type User {
    annotation foo_anno := 'My Annotation';
}
```

**Comment by agritheory** [comment]
Perfect. Thank you very much.
