### ISSUE TITLE
Add support for python dataclasses 

### ISSUE THREAD

**Issue by LeonardAukea** [edgedb/edgedb#724]
Hi guys, this project looks very promising. Looks like a game changer. 
Are you guys planning to or do you already support schema inference from python classes.
It would be pretty wicked. 

Looking at the similarities between:

```
type User {
    property name -> str;
    property address -> str;
    multi link friends -> User;
}
``` 

```python
from dataclasses import dataclass
from typing import List NewType

User = NewType('User', User)

@dataclass
class User:
    name: str
    address: str 
   friends: List[User]
```
Not sure if this make sense at all but, it would be nice to be able to `generate_schema` based on your already existing python classes. Furthermore, If one could apart from `CREATE TYPE User` also `INSERT USER` based on already existing Instances of a class it's definition. What It would probably be nicer than feeding in commands in the form of a string to `conn.execute(query_string)`. Not pro at all here. But it seems like it would be useful

**Comment by elprans** [comment]
Hey @LeonardAukea.  EdgeDB itself is agnostic as to how the schema is originally defined, so it is entirely possible to derive an SDL definition out of a dataclass or a similar definition, if you wanted to.  

That said, EdgeDB schema contains aspects that are hard or impossible to express reasonably via the dataclass syntax (constraints, annotations etc), so a more useful approach would be to do it the other way around: generate Python classes from the schema definition.  You could then use the generated classes to form queries.  This is [planned](https://www.edgedb.com/roadmap#client_language_bindings).

**Comment by adsharma** [comment]
If you prefer to write your schema using dataclasses, there is some infra here:

https://github.com/adsharma/fquery/blob/master/tests/mock_user.py

It should be possible to generate an EdgeDB data model from it.

If you don't care about GraphQL and fquery and only interested in dataclasses + SQL, this may be of interest:

https://github.com/adsharma/dataclasses-sql/commit/023a5e5df25c7d3b44479c7a45fb018243b353da
