### ISSUE TITLE
Unexpected keyword 'USING' when missing semicolon between link properties

### ISSUE THREAD

**Issue by dnwpark** [edgedb/edgedb#7249]
When trying to use this schema:
```
  type Foo;
  type Bar {
    link l -> Foo {
      a -> bool # missing semicolon
      b -> bool;
      c -> bool;
    };
  };
```

This error is produced:
```
error: Unexpected keyword 'USING'
  ┌─ /home/dnwpark/test/dbschema/futures.esdl:4:1
  │
4 │ using future nonrecursive_access_policies;
  │ ^^^^^ error
```

This is the `futures.esdl` referenced:
```
4:    using future nonrecursive_access_policies;
```

This error is confusing when compared with the error produced by missing semicolons between type properties. This schema:
```
  type Bar {
    a -> bool # missing semicolon
    b -> bool;
    c -> bool;
  };
```

Produces this error:
```
error: Missing ';'
38 │       a -> bool # missing semicolon
   │ ╭──────────────^
39 │ │     b -> bool;
   │ ╰────^ error
```

**Comment by aljazerzen** [comment]
When the schema is sent to server it is joined with semicolons. I've tweaked the parser to never ignore semicolons while recovering from the error so this error is not reported at the correct location.
