### ISSUE TITLE
Code quality automation

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#725]
We currently use flake8 to lint the codestyle and the initial work on integrating mypy is done in #693.  We need to investigate which cqa tools could further be used to enhance and maintain the quality and uniformity of the codebase.

Areas: formatting (black), idiomaticness (various tools in the PyCQA org), test coverage (we already have it, but proper tracking is needed).  Ideally we want this to extend to Cython code as much as possible as well.

Automation should ideally be done via Github Actions workflows.

- [x] Setup mypy (#693)

**Comment by 1st1** [comment]
Closing this one.
