### ISSUE TITLE
`@source` breaks on certain update queries

### ISSUE THREAD

**Issue by jollygreenlaser** [edgedb/edgedb#7263]
- EdgeDB Version: 4.7+45e4acc
- EdgeDB CLI Version: EdgeDB CLI 5.0.0+c9dfeec
- OS Version: Ubuntu 22, OSX 14.4.1

[Discord](https://discord.com/channels/841451783728529451/1232465043648544880)

```
EdgeQLSyntaxError: unexpected reference to link property 'source' outside of a path expression
```

```
with 
c := (select C filter .id = <uuid>"ecc71393-0370-11ef-9fcf-eff76ddca10a"),
b1 := (select B filter .id = <uuid>"387e4c34-0366-11ef-b5d7-bf01271f0bc5"),
b2 := (select B filter .id = <uuid>"207c0356-0366-11ef-b5d7-336ae71573b1"),
select {
  b1u := (update b1 set { val := 'asdf' }),
  b2u := (update b2 set { a := c.a,  }),
};
```

```
module default {
    type A {
        name: str;
    }

    type B {
        val: str;
        multi a -> A {
            is_active: bool;
            constraint exclusive on ((@source, @is_active));
        }
        c -> C;
    }

    type C {
        multi a -> A;
    }
}
```

Works if either update line is commented out or if constraint is removed

I'd provide a dump, but this query fails at compile time so my database values don't matter. You can have gibberish in those UUIDs.

**Comment by msullivan** [comment]
The issue is probably being caused by something in our "conflict detection" code, which explicitly enforces exclusive constraints in queries that do multiple inserts/updates to related types. (This is because the triggers we use don't work in this situation, so we do it manually).

I'll dig into it
