### ISSUE TITLE
Migration creation allows invalid aggregate functions in constraints

### ISSUE THREAD

**Issue by jollygreenlaser** [edgedb/edgedb#7264]
- EdgeDB Version: 4.7+45e4acc
- EdgeDB CLI Version: EdgeDB CLI 5.0.0+c9dfeec
- OS Version: Ubuntu 22, OSX 14.4.1

```
type User {
   name: str;
}

type HasTwoOrFewerUsers {
   users: User;
   constraint expression on (count(.users) <= 2);
}
```

This will work to create a migration, but then fail to apply:

```
InternalServerError: aggregate functions are not allowed in check constraints
```

If `users` is updated to be correctly `multi` then it properly fails at migration creation time:

```
error: cannot use aggregate functions or operators in a non-aggregating constraint
```

Seems this should always be caught at creation time.

**Comment by msullivan** [comment]
I thought this was going to have been fixed by https://github.com/edgedb/edgedb/pull/7128/, but it looks like we don't catch this at all, and the error comes from postgres.

The funny bit is that if `users` is actually a multi link, *then* we correctly reject it at migration create time!

**Comment by dnwpark** [comment]
@msullivan Thoughts on adding whether the set op is permitted in singleton to the schema?
