### ISSUE TITLE
Cannot alter schema: relation does not exist

### ISSUE THREAD

**Issue by cosmophile** [edgedb/edgedb#727]
I started with a clean test database and committed the example schema on the front page of edgedb.com (the one with types like Issue, Comment, LogEntry etc).

Then I tried to overwrite the whole schema with an SDL that only contained a type called User, and got the following error:
```
SchemaError: cannot drop object type 'default::Status' because other objects in the schema depend on it

DETAILS: link 'status' of object type 'default::Issue' depends on default::Status
```

I had been under the mistaken impression that SDL could overwrite relational schemas and simply migrate the schema to a new state, but even without any data I couldn't remove multiple relations at once. 

OK. So I tried to drop related types one by one.
```
DROP type Comment;
ALTER type Issue { drop link status; drop link priority; drop link watchers; };
DROP type Status;
DROP type Priority;
ALTER type Owned drop link owner;
DROP type User;
```
But every time I try to run the following:
```
ALTER TYPE Issue { drop link time_spent_log };
```
I get the following error (which I also get if I just straight up try to drop type Issue without dropping its links first):
```s,
InternalServerError: relation "edgedb_0c374af0-b9e5-11e9-9e0e-8386bcc80f19.fd59ef02-ded1-11e9-9af1-2767b4bb0170" does not exist
```
Can't understand this error. I saw that `time_spent_log` has an `exclusive` constraint (and is mullti) so I tried to remove the constraint first (even though it surely shouldn't be necessary?):
```
ALTER TYPE Issue ALTER LINK time_spent_log DROP CONSTRAINT exclusive;
```
and got this new error:
```
InvalidReferenceError: reference to a non-existent schema item: default::std|exclusive@@default|default|time_spent_log@@default|Issue
```
So then I tried to alter the link like so (because why not):
```
ALTER TYPE Issue ALTER LINK time_spent_log SET SINGLE;
```
This worked, but _now_ when I tried to drop the link `time_spent_log` from type `Issue`, I got a new error again:
```
InternalServerError: trigger "6f581a40-ded7-11e9-bfc4-81bfc26ffadb;schemaconstr_instrigger" for table "6f47b3c8-ded7-11e9-8f18-c9bcacf4759e" does not exist
```
Note that when I introspect the Issue type, the exclusive constraint does show up and the cardinality has become ONE. 

So any help on how I can alter this schema to something potentially completely unrelated would be much appreciated!

Also would love more clarity on how to validate SDL migrations. Is it intended behaviour that links must be dropped first (using DDL) before a linked type can be deleted? Thanks again.

PS: Since the exclusive constraint is the only thing that's different about the error-giving link, I'm guessing it is in fact required to remove the constraint first? In which case it could be a syntax error on my part. FWIW I used the example at the bottom of the DDL Constraints doc page as my reference.

**Comment by cosmophile** [comment]
Just wanted to add that on a bit more testing with a minimal schema like the following:
```
  type LogEntry {
    required property spent_time -> int64;
  }
  type Issue {
    multi link time_spent_log -> LogEntry {
      constraint exclusive;
    }
  } 
```
... the error of "relation doesn't exist" only appears when both multi and exclusive are present. If I remove either of those, the Issue type becomes droppable as expected.

**Comment by elprans** [comment]
Hi @cosmophile.  We have made a bunch of fixes for migrations in master, so most of those issues have be fixed.  We are working on setting the nightly builds up to make it easier to test the master branch.  Meanwhile you can try setting up a dev version, the instructions are here: https://edgedb.com/docs/internals/dev

**Comment by elprans** [comment]
@vpetrovykh, can you check that the above examples work on master, please?

**Comment by cosmophile** [comment]
Thanks for the tip @elprans. I have installed and tested the dev branch and the error above has indeed disappeared. I <3 edgedb!

FWIW I got a couple of "pickle" errors during build. I installed edgedb-dev on a fresh 32g ram VPS. (I had to install a few extra libs - for zlib, readline and uuid - and also install wheel manually in the venv or else I got bdist_wheel errors for uvloop). Pickle errors didn't go away although the installation completed fine!
```
Running setup.py develop for edgedb-server
    Running command /home/kay/dev/edgedb-dev/bin/python3.7 -c "import setuptools, tokenize;__file__='/home/kay/dev/edgedb/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps
    running develop
    Parsing.Spec: Introspecting to acquire formal grammar specification...
    Parsing.Spec: 195 tokens, 369 non-terminals, 1079 productions
    Parsing.Spec: Attempting to use pickle from file "build/lib/edb/edgeql/parser/grammar/single.pickle"...
    Parsing.Spec: Pickle open failed: Exception <class 'FileNotFoundError'>: [Errno 2] No such file or directory: 'build/lib/edb/edgeql/parser/grammar/single.pickle'
```
and
```
Parsing.Spec: Validating grammar...
    Parsing.Spec: 5 unused definitions
    Parsing.Spec: Unused token: ADDASSIGN
    Parsing.Spec: Unused token: REMASSIGN
    Parsing.Spec: Unused nonterm: OptDeltaTarget
    Parsing.Spec: Unused production: OptDeltaTarget ::= . [none]
    Parsing.Spec: Unused production: OptDeltaTarget ::= TO AnyIdentifier BaseStringConstant. [none]
    Parsing.Spec: 195 tokens, 369 non-terminals, 1079 productions
    Parsing.Spec: Creating skinny Spec pickle in build/lib/edb/edgeql/parser/grammar/single.pickle...
    Parsing.Spec: Introspecting to acquire formal grammar specification...
    Parsing.Spec: 195 tokens, 377 non-terminals, 1097 productions
    Parsing.Spec: Attempting to use pickle from file "build/lib/edb/edgeql/parser/grammar/block.pickle"...
    Parsing.Spec: Pickle open failed: Exception <class 'FileNotFoundError'>: [Errno 2] No such file or directory: 'build/lib/edb/edgeql/parser/grammar/block.pickle'
```
Also the test command had the following final output:
```
SUCCESS
  tests ran: 2411
  expected failures: 35
  not implemented: 42
  skipped: 3

Running times: 
  bootstrap: 00:01:17.9
  tests: 00:04:17.3
  total: 00:05:35.2
```
I feel a bit apologetic for taking up your time because I simply don't know any of your stack well enough to contribute, but I can't help playing with this kickass database and I am working my way up to using it in personal projects asap. If there's any way I can help besides testing and using edgedb, please let me know.

**Comment by vpetrovykh** [comment]
I've added the examples from this issue to our test-suite to make sure we do regression testing. Incidentally, I ran into a bug while trying out a few things. I'll open up a separate issue for that.

**Comment by elprans** [comment]
@cosmophile 

> I <3 edgedb!

Glad to hear that!  :-) 

> Pickle errors didn't go away

Those are expected, and just indicate that the parser cache is empty and  needs to be rebuilt

> If there's any way I can help besides testing and using edgedb, please let me know.

Actually, testing, and writing extra tests for things that break, would be very helpful to the stabilization effort.
