### ISSUE TITLE
Sequence doesn't work as a required property.

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#730]
Consider the following:
```
# self incrementing integer sequence
scalar type int_seq_t extending sequence;

type DefaultTest8 {
    required property number -> int_seq_t {
        # The number values are automatically
        # generated, and are not supposed to be
        # directly writable.
        readonly := true;
    }
}
```

Attempting to `INSERT DefaultTest8` fails, because the `number` is required, but is missing (it works fine if the property is not `required`). This is counter-intuitive.

**Comment by vpetrovykh** [comment]
This example originally comes from the front-page schema (`type Issue`).

**Comment by vpetrovykh** [comment]
This goes into the exact semantics of `required`. The way I understand it, it's basically a guarantee that the property will be non-empty for all objects. Whether or not that value needs to be explicitly supplied with an `INSERT` depends on whether this property has a default, and a self-incrementing scalar always has an implicit default "next value".

Incidentally, this makes me wonder, do we currently allow computables to be classified as `required`? We should be able to validate that the computable expression is guaranteed to be non-empty and providing such a guarantee may be useful. Let's say that `full_name` is a computable and gets used everywhere in forms & webpages, but it may be very nice to be able to enforce that it is _in fact_ never empty. This would mean that if one of the fields it relies upon stops being required, it would be a migration error.

**Comment by vpetrovykh** [comment]
@elprans, @1st1 what are your thoughts?

**Comment by elprans** [comment]
@vpetrovykh See #117 and #349

**Comment by elprans** [comment]
Re the semantics of `required`, you got that right.  It guarantees that the property or link will always be there when selected.  How it got into the database is not important.

**Comment by vpetrovykh** [comment]
I've added a couple more `INSERT` tests for the sequences. They have unexpected results (as far as I can tell), but additionally trying to replicate them in REPL gave me even stranger results.

**Comment by 1st1** [comment]
@vpetrovykh Please close issues when you commit.  You should always add a `Fixes: #NNN` to let github close things automatically.
