### ISSUE TITLE
Don't allow setting a global if it was declared with a computable expression

### ISSUE THREAD

**Issue by aljazerzen** [edgedb/edgedb#7368]
Schema:

```
module default {
    global test := 'hello';
}
```

```
> set global test := 'world'; <--- this should error out, but it does not
OK

> select global test;
{'hello'}    <--- because this is confusing
```

**Comment by msullivan** [comment]
We'll also want to test that it fails when trying to set it directly from a client, also. That might be either more or less gnarly.

See `test_edgeql_globals_composite` for a test where we set globals using the protocol
