### ISSUE TITLE
No index names in interactive migrations

### ISSUE THREAD

**Issue by themajashurka** [edgedb/edgedb#7371]
I have to go blindfolded when creating a migration. Index names should be more descriptive than this:

```
did you drop index '__::idx' of object type 'default::Shift'? [y,n,l,c,b,s,q,?]
> y
did you drop index '__::idx' of object type 'default::Shift'? [y,n,l,c,b,s,q,?]
> y
did you create index '__::idx' of object type 'default::Shift'? [y,n,l,c,b,s,q,?]
> y
did you create index '__::idx' of object type 'default::Shift'? [y,n,l,c,b,s,q,?]
> y
did you drop index '__::idx' of object type 'default::Shift'? [y,n,l,c,b,s,q,?]
> y
```

- EdgeDB Version: 5.2
- EdgeDB CLI Version: 5.1.0+7c5764f
- OS Version: Linux

Steps to Reproduce:

1. `edgedb migration create`

Schema:
```
type Shift {
    ...
    property date -> datetime;
    index on (.date);
    ...
}
```

**Comment by msullivan** [comment]
@dnwpark See `get_friendly_description` and the stuff it calls; you'll probably want to overload those in `IndexCommand`

**Comment by msullivan** [comment]
Probably `get_friendly_object_name_for_description` is the main thing you care about here
