### ISSUE TITLE
Reimplement datetime literal validation in a way that works on unpatched Postgres

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#740]

**Comment by 1st1** [comment]
To be clear, the action plan here is that @elprans validates if there's no way we can use some Postgres function to tell if there's an explicit TZ in a date/time string or not.  If there's no such way, then @vpetrovykh will probably implement some rudimentary date parsers in EdgeQL/SQL/PlSQL using regexps.

**Comment by elprans** [comment]
I have the good news, and the bad news.

The good news is that the following is a way to detect whether an explicit timezone was specified in the literal or not:

```
create or replace function dt(spec text) 
returns timestamptz 
language plpgsql AS $$
DECLARE
    result timestamptz;
    chk timestamptz;
BEGIN
    result := spec::timestamptz;
    PERFORM set_config('TimeZone', 'America/Toronto', true);
    chk := spec::timestamptz;

    IF result != chk THEN
        RAISE EXCEPTION 'bad date';
    END IF;

    RETURN result;
END;
$$;
```

Assuming EdgeDB Postgres sessions are always using 'UTC' as the timezone (as they should), we can temporarily switch the server timezone and compare the result of coercion.

The bad news is that the function above is 47 times slower than a pure cast.  60% of that slowdown comes just from the config shenanigans, and the rest is the PL/pgSQL overhead.  Replacing the config trick with a simple regexp nets a 20x slowdown relative to a cast.

So, if we are looking to keep performance reasonable here, then we must avoid using PL/pgSQL at all and implement parsing in pure SQL, e.g

```
create or replace function dt(spec text)
returns timestamptz
language sql AS $$
  SELECT
    CASE WHEN spec !~ 'check-regexp' THEN
        raise_exception('bad date', NULL::timestamptz)
    ELSE
        spec::timestamptz

    END;

$$;
```

This version, depending on the complexity of the condition is relatively close to a cast.

**Comment by 1st1** [comment]
Unassigning this -- this issue is up for grabs.

**Comment by vpetrovykh** [comment]
Here's the big reason why we wanted to patch Postgres's handling of `to_timestamp`. Basically, it treats the format string so loosely that it's virtually impossible for it to fail. The input characters don't quite match the format? No problem, skip the correct number of characters and move on. The input doesn't actually _have_ something from the format? No problem, just ignore it and see if it gets you _any_ result.

E.g. from Postgres docs:
> Ordinary text is allowed in to_char templates and will be output literally. You can put a substring in double quotes to force it to be interpreted as literal text even if it contains template patterns. For example, in '"Hello Year "YYYY', the YYYY will be replaced by the year data, but the single Y in Year will not be. In to_date, to_number, and to_timestamp, literal text and double-quoted strings result in skipping the number of characters contained in the string; for example "XX" skips two input characters (whether or not they are XX).

```
postgres=# SELECT to_timestamp('          2020~01/01 01"02"03 +0009', 'YYYY-MM-DD HH24:MI:SS "TZ"TZH');
      to_timestamp      
------------------------
 2019-12-31 11:02:03-05
(1 row)

postgres=# SELECT to_timestamp('   2020~01/01 01"02"03 +09', 'YYYY-MM-DD HH24:MI:SS "TZ"TZH');
      to_timestamp      
------------------------
 2019-12-31 11:02:03-05
(1 row)

postgres=# SELECT to_timestamp('   2020~01/01 01"02"03 +9', 'YYYY-MM-DD HH24:MI:SS "TZ"TZH');
      to_timestamp      
------------------------
 2020-01-01 01:02:03-05
(1 row)
```

And what I kinda expected the correct input to look like:
```
postgres=# SELECT to_char('2019-12-31 11:02:03-05'::timestamptz, 'YYYY-MM-DD HH24:MI:SS "TZ"TZH');
          to_char          
---------------------------
 2019-12-31 11:02:03 TZ-05
(1 row)
```

So it is not sufficient to detect the presence of the special parsing tokens for the timezone in the converter spec to guarantee that the converter function will actually produce the right result. We will need to use the config trick with changing time zones to validate the result as well.
