### ISSUE TITLE
Place restrictions on the use of DML statements 

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#741]
The behavior of DML CTEs in postgres dictates that they: a) must be a top-level CTE; b) always execute to completion.  These restrictions must be respected by the semantics of EdgeQL DML.  The top-level CTE requirement can only be satisfied if the use of correlated vars inside a DML statement is prohibited, i.e:

```SELECT (Foo, (INSERT Bar { foo := Foo }));```

The execute-to-completion requirement can be satisfied by prohibiting the use of DML inside a conditional construct, like `??` or `IF`.

See #110 for an earlier discussion and #684 for an example user issue.

**Comment by 1st1** [comment]
What about cases like `SELECT (Foo, (INSERT Bar { foo := Foo })) FILTER false`?

**Comment by elprans** [comment]
`FILTER false` is not considered a conditional, since the body of the statement is logically evaluated first.
