### ISSUE TITLE
Remove SELECT-like clauses from the FOR statement

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#743]
Currently, the `FOR` statement accepts the `FILTER`, `ORDER BY`, `OFFSET` and `LIMIT` clauses that apply to the *result* of the `UNION`. In essense, `FOR x IN <expr> UNION <expr> FILTER <flt>` is equivalent to `SELECT <implicit_alias> := (FOR x IN <expr> UNION <expr>) FILTER <flt>`

The problem is that the above transformation is arguably not intuitive, since it is possible to *also* assume that the `FILTER` clause etc. apply to the expression in the `UNION` clause.  The current
implementation is also incorrect, since it doesn't hide the iterator variable from the followup clauses, and doing that would also be an exception from all other statements.

For those reasons, remove the clause sugar support from the `FOR` statement until we figure out an intuitive way of reintroducing them.

**Comment by vpetrovykh** [comment]
Looks like in general `FOR x IN {<expr0>} UNION <expr1>{<shape>}` is sugar for the following:
```
WITH 
    x := <expr0>,
    tup := (x, <expr1>)
SELECT tup.1 {<shape>};
```
With the assumption that `<expr1>` and/or `<shape>` refer to `x` in some way and `<shape>` specifically can be re-written with references to `tup.0` instead. Is this true or is `FOR` doing something more than is expressed by this convoluted cross-product? @elprans @1st1 what are your thoughts?

**Comment by elprans** [comment]
@vpetrovykh, this is roughly how FOR is interpreted, only we elide the intermediate tuple.
