### ISSUE TITLE
AssertionError: TODO: properly infer Pointer-as-Expr

### ISSUE THREAD

**Issue by AdrienPensart** [edgedb/edgedb#7433]
Hello!

since a few releases after 5.0b my big upsert query is not working anymore : AssertionError: TODO: properly infer Pointer-as-Expr

See linked files.

[query.txt](https://github.com/user-attachments/files/15597817/query.txt)
[schema.txt](https://github.com/user-attachments/files/15597829/schema.txt)

**Comment by ahirner** [comment]
> big upsert

Hit the same error after upgrading from 4.7 to 5.3. Did you find a workaround by any chance?

**Comment by jollygreenlaser** [comment]
Also hitting this. Hard blocker on upgrading to 5.6 (from 4.7)

Also doing insert in for loops for json input

**Comment by msullivan** [comment]
Before I dive in on this, does anybody have a more reduced query that triggers it?

**Comment by msullivan** [comment]
Minimized:
```
module default {
    type Album {
        constraint std::exclusive on (.artist);
        link artist: default::Artist;
    };
    type Artist;
    type Music {
        link album: default::Album;
    };
};
```
and
```
with
    upsert_artist := <Artist>{},
    upsert_album := (
        insert Album {
            artist := upsert_artist
        }
        unless conflict
    ),
insert Music {
    album := upsert_album,
};
```
