### ISSUE TITLE
Prohibit tuples as query arguments

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#745]
Postgres does not support anonymous rowtypes as input, and there is no way to specify the tuple descriptor on the fly, so we have no choice but to inherit this limitation.

**Comment by ambv** [comment]
@elprans, how about I do this to kick the tires on EdgeQL?

**Comment by elprans** [comment]
@ambv Yes, this is a perfect type of an issue to start.

**Comment by aeros** [comment]
@ambv Are you still interested in working on this? If not, it would be a great introduction for me to learn about how query arguments are parsed.
