### ISSUE TITLE
Allow wildcard subdomains for allowed_redirect_urls

### ISSUE THREAD

**Issue by patrikengborg** [edgedb/edgedb#7468]
When using EdgeDB Auth, wildcard subdomains would be very convenient. In my case, almost a necessity, since every user gets their own subdomain. Configuring this via a query is probably possible but very cumbersome.

So for example, instead of adding:
a.myapp.com
b.myapp.com

I should just be able to use *.myapp.com in the allowed_redirect_urls config setting.

**Comment by scotttrinh** [comment]
For context, we intend for this to work without needing an explicit wildcard for subdomains, so this is a bug.
