### ISSUE TITLE
No need to use sha1 in edb/edgeql/declarative.py

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#751]
No need to use sha1 on rendered parameters, just use the rendered string as `extra_name`.

**Comment by vpetrovykh** [comment]
I copied this practice from `trace_ConcreteConstraint` handling of `extra_name` to be honest. Should I also remove the sha1 from there? Is there some deeper reason behind it @elprans?

**Comment by 1st1** [comment]
No deeper reason, just drop it.
