### ISSUE TITLE
error: QueryError: complex type expressions are not supported here

### ISSUE THREAD

**Issue by Lionad-Morotar** [edgedb/edgedb#7591]
- EdgeDB Version: "5.6+adb9e77"
- EdgeDB CLI Version: EdgeDB CLI 5.1.0+8ff9f85
- OS Version: MacOS 14.5

Steps to Reproduce:

1. I have such schema

![image](https://github.com/user-attachments/assets/9a3b0f88-7e5d-40d3-8dca-c1cd5b2631a2)

2. then try to drop "FieldDataInt16", I tried two ways to cast .data to a new type, but got "SchemaError" and "QueryError"

![image](https://github.com/user-attachments/assets/c9ae384d-ac94-4674-8fbd-773d92c5639c)

---

Creating a new prop called 'data2', copying the value of 'data' to 'data2', then delete 'data', and renaming 'data2' to 'data' might solve the problem, but If theres better (or automatic) way?

I'm new to EdgeDB and not sure if this is a syntax error or an issue with EdgeDB, appreciate it if someone could point it out.

reproduce link：https://github.com/Lionad-Morotar/reproduce-edgedb-query-error-001

**Comment by elprans** [comment]
Fixed in #7172, which will ship in 6.0.  Meanwhile, use `??` as a workaround in the conversion expression:

```edgeql
(.data[is FieldDataShort] ?? .data[is FieldDataLong])
```
