### ISSUE TITLE
Allow validating EdgeQL queries

### ISSUE THREAD

**Issue by jquesada2016** [edgedb/edgedb#7592]
It would be great if EdgeDB provided an in-database solution for validating an arbitrary string as a valid EdgeDB query that checks also against the schema.

If an EdgeDB query is not valid, EdgeDB can return a standardized message that describes what and where things went wrong, whether it's a syntax or type error.

This would make creating compile-time and runtime checking of queries before executing them much easier, and for languages such as Rust, that have a compile-time macro system, it would make creating a validating macro pretty trivial to create.

It might also be useful to expose a parser validator where the string is checked only for syntax correctness, not types.

**Comment by elprans** [comment]
We are adding [language server support](https://github.com/edgedb/edgedb/tree/master/edb/language_server) which should cover those use cases.

**Comment by jquesada2016** [comment]
Great! will the LSP be run on the CLI or remotely on EdgeDB itself?

**Comment by elprans** [comment]
It will be shipped as a special build of the server that you can run on the command line. We'll be integrating it into the main CLI for convenience as well.

**Comment by jquesada2016** [comment]
That sounds perfect! I suppose you can close this issue in favor of that PR

**Comment by CodesInChaos** [comment]
I don't think a language server fully covers the relevant use-cases of query validation. For example a user might want to validate all queries on the build server as part of the pull-request/merge workflow.
