### ISSUE TITLE
PKCE Verification fails when there is a trailing `=` in the challenge string.

### ISSUE THREAD

**Issue by devNamanG** [edgedb/edgedb#7596]
First of All, thank you for such an amazing Database!

So I want to use the Auth extension for handling authentication, and am using the builtin-ui auth method. For this, we are required to perform a PKCE-like flow, wherein my application server generate a verifier and challenge pair. When i send a request to the `token` endpoint for retrieving the auth token, it always responds with a failure, and states that PKCE Challenge and Verifier do not match. At first I tried debugging things on my end. Then I checked out the code that handles [the flow](https://github.com/edgedb/edgedb/blob/d215dad54fb17474253a83c947bd20f22305a79e/edb/server/protocol/auth_ext/http.py#L435), and noticed that this removes the trailing `=` at the end of the challenge (which is the processed verifier). Then I checked [this file](https://github.com/edgedb/edgedb/blob/d215dad54fb17474253a83c947bd20f22305a79e/edb/server/protocol/auth_ext/http.py#L542) and [this file](https://github.com/edgedb/edgedb/blob/d215dad54fb17474253a83c947bd20f22305a79e/edb/server/protocol/auth_ext/pkce.py#L52), wherein the challenge being saved is not processed to remove the trailing `=` in the challenge. Hence, the challenge must be failing.

Since I haven't been able to find this behaviour being documented anywhere, is this the normal/expected Behaviour? Am I required to remove the trailing `=` in the challenge string before providing it to the auth flows?

- EdgeDB Version: 5.6+51fd5fe
- EdgeDB CLI Version: EdgeDB CLI 5.1.0+7c5764f
- OS Version: Fedora 40 (Server/Workstation)

Steps to Reproduce:

1. Create an authentication flow with a Challenge string having a trailing `=`
2. Send a GET request to the `token` endpoint to retrieve a token, with the appropriate code and verifier parameters.

The response will be a `PKCEVerificationFailed` error.

Schema: N/A

**Comment by scotttrinh** [comment]
> Since I haven't been able to find this behaviour being documented anywhere, is this the normal/expected Behaviour? Am I required to remove the trailing = in the challenge string before providing it to the auth flows?

Thanks for bringing this up, I'll update the documentation in the Auth guide to point out that any padding characters should be removed. The Node.js implementation of `Buffer` to `base64url`-encoded string always omits the padding, so it's not very clear in our reference implementation in the guide. For further context about stripping the padding, this is due to `=` having a special meaning in URLs, which makes the padding not actually URL-safe without further encoding (percent encoding).

**Comment by devNamanG** [comment]
> For further context about stripping the padding, this is due to = having a special meaning in URLs, which makes the padding not actually URL-safe without further encoding (percent encoding).

Okay thank you very much for the details! I am sorry I didn't mention earlier, but my application server is written in Go, which doesn't exhibit the said behaviour:

>The Node.js implementation of Buffer to base64url-encoded string always omits the padding, so it's not very clear in our reference implementation in the guide.

So I assume it is safe to remove the padding characters like `=` before sending the challenge strings to the Auth Flows, right?

**Comment by scotttrinh** [comment]
@devNamanG 

> So I assume it is safe to remove the padding characters like = before sending the challenge strings to the Auth Flows, right?

Yeah, for Go, I think you'd do roughly this:

```go
	// Generate a random string (length 43 for this example
	verifier := make([]byte, 43)
	if _, err := rand.Read(verifier); err != nil {
		panic(err)
	}

	// Use RawURLEncoding to encode the verifier without padding
	encodedVerifier := base64.RawURLEncoding.EncodeToString(verifier)

	// Generate SHA256 hash of the verifier
	hash := sha256.New()
	hash.Write([]byte(encodedVerifier))
	hashedVerifier := hash.Sum(nil)

	// Use RawURLEncoding to encode the challenge without padding
	challenge := base64.RawURLEncoding.EncodeToString(hashedVerifier)
```

**Comment by devNamanG** [comment]
@scotttrinh Thank you so much for the code example! I was doing literally the same thing, except used `base64.URLEncoding` instead of `base64.RawURLEncoding`.

**Comment by scotttrinh** [comment]
@devNamanG 

> Should I keep this issue open till the documentation is updated?

Yeah, it'll get closed when that PR gets merged, so feel free to leave this open.

**Comment by devNamanG** [comment]
@scotttrinh okay great! Thank you!
