### ISSUE TITLE
Feature request: Filtering a set of scalars / __self__ keyword

### ISSUE THREAD

**Issue by jollygreenlaser** [edgedb/edgedb#7642]
[Discord Thread](https://discord.com/channels/841451783728529451/1242935687934644285) where I started from the question of counting things in a set of scalars

It is weird/hard to filter a set of scalars right now. Scott provided a workaround to convert to a tuple (which I haven't tested) but is very hacky. 

In the same way that triggers have `__new__` and `__old__`, a `__self__` keyword would be useful. 

```
select { true, false, true }
filter __self__ = true
```

Alternatively something like:

```
select { true, false, true }
filter [is bool] = true
```

(which currently does not work as `[is type]` only works on objects)

**Comment by MrFoxPro** [comment]
@jollygreenlaser 
Right now you can do it without converting:
```edgeql
with 
  s := {1, 2}
select s filter s > 1
# outputs { 2 }
```

**Comment by msullivan** [comment]
SELECT lets you define an alias as part of the select, for just this case:
```
select _ := { true, false, true }
filter _ = true
```

... do we not document this anywhere?
