### ISSUE TITLE
Proper function DML support

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#7692]
In order to support the Networking Module RFC (https://github.com/edgedb/rfcs/blob/master/text/1026-net-module.rst), I think we need to support functions that contain DML.

Currently there is a flag that allows it, but it doesn't work very well. The DML is actually contained inside the postgres function, and it doesn't work very well. In particular, it can be potentially optimized away and also can't properly return the created object.

I think the correct approach here is to support them by inlining functions that contain DML.

I'm filing this now as a tracking issue but there are some serious semantic questions to answer.

**Comment by msullivan** [comment]
The semantic question:

Imagine a function like:
```
function make_user(name: str) -> User using (insert User { name := name })
```

The behavior of `select make_user('Bob')` is clear, but how about `select make_user(<str>{})` or `select make_user({'foo', 'bar'})`.

I think we really do *not* want to have the number of inserts done be implicitly determined by the cardinality of the argument (we firmly disallow that sort of thing with DML currently).

I think the alternative is rejecting those queries with a cardinality error, which requires making DML containing functions have a very different argument matching behavior than regular ones.

Sigh. I think the second choice is the right one but it means more design to be done.

**Comment by elprans** [comment]
> I think we really do not want to have the number of inserts done be implicitly determined by the cardinality of the argument (we firmly disallow that sort of thing with DML currently).

How is this different from DML in a `for` over a set with variable cardinality?

**Comment by msullivan** [comment]
Because the FOR makes it explicit.

**Comment by msullivan** [comment]
We should write some docs but this is done, right?

**Comment by dnwpark** [comment]
@msullivan Yeah, I would say so. Just tidying some stuff up with the volatility before starting on the docs.
