### ISSUE TITLE
Support making SQL queries over edgedb protocol

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#7732]

**Comment by themajashurka** [comment]
Does it mean that with this feature it'll be possible to directly send SQL queries from client libraries and get a parsed object back?

**Comment by msullivan** [comment]
> Does it mean that with this feature it'll be possible to directly send SQL queries from client libraries and get a parsed object back?

Yes

**Comment by msullivan** [comment]
What are the known remaining tasks here?
 - [ ] Globals don't work, right?
 - [ ] @aljazerzen thought something was broken with constant extraction?
