### ISSUE TITLE
Typo EdgeBD

### ISSUE THREAD

**Issue by cphares** [edgedb/edgedb#774]
https://edgedb.com/docs/clients/99_graphql/index/#ref-graphql-index
 **EdgeBD** should read **EdgeDB**

**Comment by aeros** [comment]
Good catch. Here's a screenshot confirming the typo:
![image](https://user-images.githubusercontent.com/44193521/67155346-212f0500-f2db-11e9-8406-559010e32ed0.png)

**Comment by 1st1** [comment]
Yeah, feel free to submit a PR!

**Comment by aeros** [comment]
@cphares Since you found the typo, would you like to submit the PR? If not, I'd be glad to open one myself.
