### ISSUE TITLE
Rounding is incorrect 

### ISSUE THREAD

**Issue by janwirth** [edgedb/edgedb#7800]
```
EdgeDB 5.6+adb9e77 (repl 5.0.0+c9dfeec)
Type \help for help, \quit to quit.
my_db:edgedb> select round(482.5);
{482}
```

**Comment by scotttrinh** [comment]
Yeah, this can be a gotcha, but [there is no "correct" way to round.](https://en.wikipedia.org/wiki/Rounding) The rules for rounding are [explained in the docs](https://docs.edgedb.com/database/stdlib/numbers#function::std::round) and are mostly inherited from [PostgreSQL's own rounding rules](https://www.postgresql.org/docs/current/functions-math.html).

**Comment by janwirth** [comment]
Okay, thanks for clearing this up. In school I was taught 0.5 is always rounding up.
