### ISSUE TITLE
Name 'qlast.Stmt' is not defined

### ISSUE THREAD

**Issue by ambv** [edgedb/edgedb#785]
mypy 0.740 reports as of be705ce77d6a5f6d66a94691b4f7d0fb555b34b0 (possibly sooner):

edb/edgeql/compiler/stmt.py:488: error: Name 'qlast.Stmt' is not defined

**Comment by elprans** [comment]
This is fixed already, not a coverage issue.   @ambv Please use the `Fixes: ####` notation in commits to close issues automatically.

**Comment by elprans** [comment]
Ah, sorry, that commit wasn't merged yet.

**Comment by ambv** [comment]
It was fixed [as part of](https://github.com/edgedb/edgedb/pull/783/commits/34fd28c5a1c9d9d02800e27ce3eefe744531f199#diff-90135b116f92cefdad495d9a9996d7fdR488) #793 per @1st1's request.

**Comment by 1st1** [comment]
@ambv but we didn't add a regression/functional test to cover this, right?

**Comment by elprans** [comment]
It’s an annotation issue, not a code bug

**Comment by 1st1** [comment]
Sorry, missed that :(
