### ISSUE TITLE
Add language-level support for schema description

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb#790]
Currently, there is no way for an EdgeDB client to obtain an SDL or DDL representation of a given part of a schema or a part of a schema, except by using introspection queries and implementing client-side code generation.  Since the facilities to produce correct schema dumps already exist in the server, it makes a lot of sense to expose the functionality as commands:

```
DESCRIBE { <schema-object> [, ...] | SCHEMA } [AS  {DDL|SDL|TEXT}] [VERBOSE]
```

`DDL`, `SDL` and `TEXT` determine the output format, `SDL` being the default.

`<schema-object>` is a valid reference to a schema object: a (possibly qualified) name, or an object type followed by a name.  If the object is global, then the type is required.

If the entire schema is to be described, the sole `SCHEMA` keyword is used.

Examples:

```
# Return the description of the `User` object type as SDL
DESCRIBE TYPE User AS SDL;

# Return the description of the `orders` module as DDL.
DESCRIBE MODULE orders AS DDL;

# Return the description of the entire schema as DDL.
DESCRIBE SCHEMA AS DDL;

# Return the annotated description of the `User` type with verbosity
DESCRIBE TYPE User AS TEXT VERBOSE;
```

**Comment by 1st1** [comment]
I think for consistency sake we should have `DESCRIBE TYPE User`. Just like we have `ALTER TYPE User` even though we could theoretically support `ALTER User`.

**Comment by elprans** [comment]
OK, no abbreviated form then.  `DESCRIBE <objtype> <objname>` is the required syntax.

**Comment by 1st1** [comment]
Or maybe we should support both -- what if someone is creating a tool to display tooltips or something -- it would be convenient for them to just query `DESCRIBE <name>` in some cases.

Other thought: is it possible we can make this query support parameters? E.g. `DESCRIBE TYPE $typename` or `DESCRIBE TYPE UNQUOTE $typename`?

**Comment by elprans** [comment]
> is it possible we can make this query support parameters?

Not currently. That would require elaborate support for introspection and codegen in Postgres.

**Comment by 1st1** [comment]
> Not currently. That would require elaborate support for introspection and codegen in Postgres.

But `DESCRIBE` will be statically compiled, won't it?

**Comment by elprans** [comment]
In pseudocode terms:

```
`DESCRIBE <obj>`:
  obj_delta = get_delta(obj)
  ddl = delta_to_ddl(obj_delta)
  return f'SELECT "{ddl}"'
```

The above is only possible if <obj> is given as an identifier, and not a variable.

**Comment by 1st1** [comment]
Ah, right, we'd need to compile it in the main process for this... Never mind.

**Comment by elprans** [comment]
Optional type qualification would require making `TYPE`, `MODULE`, etc reserved keywords.

**Comment by elprans** [comment]
We can use some generic keyword like `DESCRIBE ITEM Foo` when the type is not known.

**Comment by 1st1** [comment]
> We can use some generic keyword like DESCRIBE ITEM Foo when the item class is not known.

Yeah. We can skip it for now, I guess. Let's see if anyone requests that.

**Comment by elprans** [comment]
I updated the issue description to match the latest design:

* format selector is now a suffix
* removed the ability to describe multiple objects
* added `TEXT` and `VERBOSE` options
