### ISSUE TITLE
Collections comparisons don't always work.

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#799]
Currently we don't have working comparison between collections that contain decimal vs non-decimal numbers.

Consider the following:
```
victor> SELECT 1.0 IN {1n, 2n};
{true}
victor> SELECT [1.0] IN {[1], [2]};
{true}
victor> SELECT [1.0] IN {[1n], [2n]};
QueryError: operator 'IN' cannot be applied to operands of type 
'array<std::float64>' and 'array<std::decimal>'
Hint: Consider using an explicit type cast or a conversion function.
### SELECT [1.0] IN {[1n], [2n]};
###        ^
```

See #356 for more details on decimal/non-decimal separation and why we treat operators a certain way.

**Comment by elprans** [comment]
See #445

**Comment by vpetrovykh** [comment]
What's blocking the merge there?

The comparison is not limited to `IN`, there are issues with `=`, `<` and `?=`, but I think they are not limited to the decimal/non-decimal separation. See the `test_edgeql_expr_valid_collection` xfails.

Both of these fail now:
```
SELECT [1.0] < [1];
SELECT [1.0] < [1n];
```

**Comment by elprans** [comment]
The merge is currently blocked because there wasn't a consensus on whether that is the best approach.

**Comment by elprans** [comment]
There are issues with arrays specifically. Upstream Postgres currently has a restriction that both array operands *must* be of the same type, even if an operator for the element types or implicit cast exists. This means that we must do a full explicit cast for arrays (and possibly tuples) in operations where operands are of a different type and there is an implicit cast.

**Comment by 1st1** [comment]
@elprans I vaguely recall this was resolved or something. Please comment.

**Comment by elprans** [comment]
This is resolved.
