### ISSUE TITLE
Adding non-scalar link property cases field to be added to properties parent type

### ISSUE THREAD

**Issue by Gobot1234** [edgedb/edgedb#8087]
Version: {"major": 5, "minor": 6, "stage": "final", "stage_no": 0, "local": ["adb9e77"]}

Given a schema like this
```esdl
module users {
    type User {
        multi training: Training {
            created_at: datetime {
                readonly := true;
                default := datetime_of_statement();
            }
        }
    }

	type Infraction {};
    type Training {};
}
```
I added an Infraction link property to user.training when going to migrate I got this message
```
did you create link 'infraction' of object type 'users::User'? [y,n,l,c,b,s,q,?]
>
```
Which added the infraction link to the user and didn't tell me what I was trying to do wasn't possible like using raw DDL would have.

**Comment by msullivan** [comment]
That's actually pretty funny.
Thanks for the report.
