### ISSUE TITLE
Introduce `USING` keyword for language-related data

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#829]
The idea is to make the (DDL/SDL) syntax for defining expressions and function bodies more consistent. So the general syntax would revolve around the `USING` keyword. Typically it would be `USING lang ...`.

What this affects:
- functions: instead of `FROM ...` simply become `USING ...`, but otherwise stay unchanged
- operators: same as functions
- casts: `FROM type TO type` remains unchanged, but the body definition changes to `USING ...` much like function bodies.
- views: we will retain the shorthand `CREATE VIEW foo := <expr>`, but instead of using `SET expr := <expr>` in the long form, the syntax will be `USING <lang> "<expr>"` or `USING <expr>`
- computables: similarly to views they will retain the `:=` shorthand, but will switch to `USING` clause instead of `SET expr := ...`

One of the big changes is to drop the rather obscure `SET expr := ...` syntax in favor of the somewhat more natural `USING ...` syntax. However, constraints, for example, will retain their `SET expr := ...` because it is not a shorthand for `ON (...)`.

**Comment by 1st1** [comment]
Done in master.
