### ISSUE TITLE
Volatile functions behave as if they were stable

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#830]
When running on top of Postgres 12 queries like the below one do not seem to interpret volatile calls correctly:

```
                WITH MODULE test
                SELECT Obj {
                    # volatile function should be called once for each
                    # Obj, generating different values
                    x := vol_volatile()
                };

```

**Comment by 1st1** [comment]
Marking `test_edgeql_volatility_function_03` as xfail.

**Comment by elprans** [comment]
This seems to be a Postgres regression:

```
volatility=# SELECT
   (SELECT random()) AS v1,
   random() AS v2
FROM
   generate_series(1, 2);
         v1         │         v2
────────────────────┼────────────────────
 0.6381342073143692 │ 0.5827781474844613
 0.6381342073143692 │ 0.7479476494195545
(2 rows)
```

**Comment by elprans** [comment]
Reported as [#16121](postgr.es/m/16121-b8e8dc82e608b89d@postgresql.org) upstream

**Comment by 1st1** [comment]
The upstream discussion makes me think that the only way forward is to implement https://github.com/edgedb/edgedb/issues/492 and make it required for volatile functions to use `CORRELATED TO` when we can't infer the correlation ourselves.

**Comment by elprans** [comment]
Not really. `CORRELATED TO` is essentially the explicit variant of the implicit correlation we have in shape computables. Same underlying mechanism.  #844 should fix this.

**Comment by elprans** [comment]
Also, longer term we may consider wrapping all volatile functions with a wrapper that takes a magic argument with the correlated var.

**Comment by 1st1** [comment]
> Also, longer term we may consider wrapping all volatile functions with a wrapper that takes a magic argument with the correlated var.

This is what I meant -- if we do that and compile

```
WITH MODULE test
                SELECT Obj {
                    # volatile function should be called once for each
                    # Obj, generating different values
                    x := vol_volatile()
                };
```

into

```
.... SELECT vol_volatile(Obj.id) ....
```

then it would be a more robust solution.  Otherwise is it guaranteed that Postgres' optimizer isn't smart enough one day to optimize away the hacks of #844?

**Comment by elprans** [comment]
> Otherwise is it guaranteed that Postgres' optimizer isn't smart enough one day to optimize away the hacks of #844

Well, if they optimize away an explicit `WHERE` clause, then I don't even know how the documentation stating "A query using a volatile function will re-evaluate the function at every row where its value is needed." is not a lie anymore.  Anyway, the wrapper function is orthogonal to an explicit `CORRELATED` modifier.  I'll open an issue so we don't forget to revisit this.
