### ISSUE TITLE
Bug with tuple element cardinality.

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#833]
Consider the following:
```
scope> WITH
......     MODULE test,
......     letter := {'A', 'B'},
......     tup := (
......         letter,
......         (
......             SELECT User
......             FILTER .name[0] = letter
......         )
......     )
...... SELECT _ := tup.1 {
......     name,
......     l := tup.0,
...... }
...... ORDER BY .name;
......
{Object { name: 'Alice', l: {'A'} }, Object { name: 'Bob', l: {'B'} }
```
(see `test_edgeql_scope_tuple_13`)

The goal here is to re-package the tuple elements such that one of them becomes a computable in the shape of the other. 

The first question is: is this even legal? It intuitively makes sense, but technically it *looks* as if two different prefixes `tup.1` and `tup.0` are combined in a way that would be definitely illegal if they were regular paths like `Foo.bar1` and `Foo.bar0`. I would argue that this should be legal because the `.` in tuple dereferencing is not really a path, but is more akin to `[...]` index access. So there's no violation of the common path prefix rule. More pragmatically, making it hard to repackage tuples makes tuples less useful.

The reason why I came up with this example of tuple usage is #743. Basically, it's an attempt to rewrite a `FOR` in terms of tuples. Although I agree with the point that the additional clauses are ambiguous when used with `FOR` and they cause problems, it means that if I want to order my `FOR` computable (because I'll use it in output) I need to jump through hoops. See `test_edgeql_for_in_computable_01` (which works) and `test_edgeql_for_in_computable_02` (which doesn't work) in #832 . Correlating link props and link targets is one of good examples why we even need a `FOR`.

**Comment by 1st1** [comment]
Fixed in https://github.com/edgedb/edgedb/commit/9011c8213260366491b60c11896613637cc920fe
