### ISSUE TITLE
Build instructions are not full

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#838]
Looking at https://edgedb.com/docs/internals/dev/:

1. (minor) We might want to add `git submodule update --init` as most projects do, as it took me few minutes to find out :)
2. Currently, postgres (or a module of?) is built as part of edgedb develop installation, and I needed `libreadline-dev zlib1g-dev uuid-dev` on ubuntu bionic to build it. I don't see it mentioned somewhere.

(no PR as I'm not sure how to describe latter in particular minumum versions... or maybe postgres modules will be obsolete soon enough)

**Comment by 1st1** [comment]
Re 1: we recommend to use `git clone --recursive` -- doesn't it make `git submodule update --init` unnecessary?

Re 2: we can just say that libreadline-dev, zlib1g-dev, uuid-dev might be needed on some systems (without pinning minimal versions)

**Comment by tailhook** [comment]
> Re 1: we recommend to use `git clone --recursive` -- doesn't it make `git submodule update --init` unnecessary?
> 

Hm, yes, but it's quite common to skip cloning line from guide (i.e. I've clonned earlier).

Anyway, currently it fails like this:
```
postgres submodule not initialized, run `git submodule init; git submodule update`
```
Probably, as a side effect of another change. So should be good enough.
> Re 2: we can just say that libreadline-dev, zlib1g-dev, uuid-dev might be needed on some systems (without pinning minimal versions)

Added in #842
