### ISSUE TITLE
(Un)signed ints in protocol documentation

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#848]
Reading the [documentation](https://edgedb.com/docs/internals/protocol/overview):
```rst
    * - ``int8``
      - 8-bit integer
    * - ``int8<T>``
      - an 8-bit integer enumeration, where *T* denotes the name of
        the enumeration
    * - ``int16``
      - 16-bit integer, most significant byte first
    * - ``byte``
      - 8-bit unsigned integer
```
It's unclear whether integers are signed. Because of difference with `byte` they should be signed.

Except when used as length:
```rst
    * - ``string``
      - a UTF-8 encoded text string prefixed with its byte length as ``int16``
```
Where it's unclear what negative numbers mean.

And also enums:
```C++
struct ErrorResponse {
    ...
    int8<ErrorSeverity> severity;
    ...
};

enum ErrorSeverity {
    ERROR = 120,
    FATAL = 200,   # larger than 127
    PANIC = 255
};
```

So at a glance everywhere I see integers should rather be unsigned. Which is also proved by cython code (if I remember correctly, these casts are wrapping, i.e. -1 becomes 65535):
```
261:        hi = <uint16_t>self.buffer.read_int16()
262:        lo = <uint16_t>self.buffer.read_int16()
264:        nparams = <uint16_t>self.buffer.read_int16()
270:        nexts = <uint16_t>self.buffer.read_int16()
724:        cdef int16_t nheaders = self.buffer.read_int16()
736:        num_fields = <uint16_t>self.buffer.read_int16()
738:            key = <uint16_t>self.buffer.read_int16()
```
There might be related issue with cython implementation:
https://github.com/MagicStack/py-pgproto/blob/93f8959715aac18ce2769bdd3e80434fc2258066/buffer.pyx#L459:
```python

    cdef inline int16_t read_int16(self) except? -1:
        # ...
            return hton.unpack_int16(cbuf)
        # ...
```
If there were literally bytes `b'\xFF\xFF'` (i.e. `-1`) they produce:
```
SystemError: error return without exception set
```
If I remember correctly.

----

So are the integers unsigned? Or should protocol limit int16 lengths to 0-32767? I expect this is some legacy thing from postgres protocol with C semantics, and hopefully, we can make it more clear.

**Comment by elprans** [comment]
This is mostly C legacy, yes.  Negative integers are reserved to signal errors, so signed ints should be limited to the positive half.

@1st1 do you think we can get away with removing the `_ensure_first_buf` assertion from the read methods?

**Comment by 1st1** [comment]
> So are the integers unsigned? Or should protocol limit int16 lengths to 0-32767? I expect this is some legacy thing from postgres protocol with C semantics, and hopefully, we can make it more clear.

> So at a glance everywhere I see integers should rather be unsigned. Which is also proved by cython code (if I remember correctly, these casts are wrapping, i.e. -1 becomes 65535):

Yes, in *most* places they should be unsigned. There might be a few cases where we specifically want it to be signed, so this needs to be checked on a case by case basis. I can't remember if we have any such places off the top of my head.

If you started to work on Rust driver I'd appreciate you update the spec where necessary.  Also, it might make sense to check if edgedb-python and [edgedb-js](https://github.com/edgedb/edgedb-js) are in sync with the updated spec :)

edgedb-js is also a more recent implementation that is probably easier to follow than edgedb-python, please take a look at it.

--------

> If there were literally bytes b'\xFF\xFF' (i.e. -1) they produce:
>
> SystemError: error return without exception set

Hmm, logically, Cython should execute `hi = <uint16_t>self.buffer.read_int16()` in the following order:

1. call `self.buffer.read_int16()`
2. if the result is -1, throw an error
3. orelse cast the result to `uint16_t`

This is what Cython generates for this code `edb/server/mng_port/edgecon.c:6518`:

```C
/* "edb/server/mng_port/edgecon.pyx":261
 *             dict params = {}
 * 
 *         hi = <uint16_t>self.buffer.read_int16()             # <<<<<<<<<<<<<<
 *         lo = <uint16_t>self.buffer.read_int16()
 * 
 */
__pyx_t_2 = (
   (struct __pyx_vtabstruct_3edb_6server_7pgproto_7pgproto_ReadBuffer*)
        __pyx_cur_scope->__pyx_v_self->buffer->__pyx_vtab
)->read_int16(__pyx_cur_scope->__pyx_v_self->buffer); 

if (unlikely(__pyx_t_2 == ((int16_t)-1) && PyErr_Occurred())) 
     __PYX_ERR(0, 261, __pyx_L1_error)

__pyx_cur_scope->__pyx_v_hi = ((uint16_t)__pyx_t_2);
```

So I think that this particular aspect is fine.

**Comment by 1st1** [comment]
> @1st1 do you think we can get away with removing the _ensure_first_buf assertion from the read methods?

No, I don't think so. But why? This seems like an unrelated question...

**Comment by elprans** [comment]
Because we use -1 as a magical indicator of error, and -1 is a valid signed int.

**Comment by tailhook** [comment]
Hm, `PyErr_Occurred()` looks a bit magical, but okay.

> edgedb-js is also a more recent implementation that is probably easier to follow than edgedb-python, please take a look at it.

I see that python version checks for negative values but JS version does not. Looks like an oversight?

So I propose to mark such integer as some other type, like `pint16` where (p means positive), or some other way, in the spec. To make it's clear which numbers should be checked and which not (e.g. can versions be "negative"?). What do you think?

Do you have any tests for wire data?

**Comment by 1st1** [comment]
> Hm, PyErr_Occurred() looks a bit magical, but okay.

> I see that python version checks for negative values but JS version does not. Looks like an oversight?

I think I understand why you're confused with this.  The `-1` value has **nothing to do** with what arrives on the wire. It's a protocol Cython uses to signal if a Python exception occurred in a function, e.g. say we have a function `cdef foo(): int32_t except -5`, then:

* if a Python exception occurs in `foo()`, it will return `-5` immediately. Cython knows that when `foo()` returns `-1` it should check if there was any Python exception with Python C API (`PyErr_Occurred()`).

* if `foo()` returns `-5` as a legitimate result, Cython will still check `PyErr_Occurred()`, but since there was no exception `-5` will be used as result.

if `foo()` returns anything but `-5` Cython won't even bother checking `PyErr_Occurred()`.

So in our case, `except -1` is just a sentinel value that Cython will use to optimize detecting if there was a Python exception.

**Comment by tailhook** [comment]
I mean this check on `size < 0` (-1 raises exception on the first line, but any other value...):
```
    cdef bytes read_len_prefixed_bytes(self):
        cdef int32_t size = self.read_int32()
        if size < 0:
            raise exceptions.BufferError(
                'negative length for a len-prefixed bytes value')
        if size == 0:
            return b''
        return self.read_bytes(size)
```
And this check on `size > _MAXINT32`:
```
    cdef write_len_prefixed_bytes(self, bytes data):
        # Write a length-prefixed (not NULL-terminated) UTF-8 string.
        cdef:
            char *buf
            ssize_t size

        cpython.PyBytes_AsStringAndSize(data, &buf, &size)
        if size > _MAXINT32:
            raise exceptions.BufferError('string is too large')
        # `size` does not account for the NULL at the end.
        self.write_int32(<int32_t>size)
        self.write_cstr(buf, size)
```

**Comment by 1st1** [comment]
This PR https://github.com/edgedb/edgedb/pull/1410 fixes all (hopefully) signed/unsigned issues.
