### ISSUE TITLE
Terminal detection is weird

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#859]
While working on #857 I noticed that "script mode" is activated in a weird way:
```
> echo rollback | edgedb --admin
{}
> {sleep 1; echo rollback;} | edgedb --admin
Warning: Input is not to a terminal (fd=0).
EdgeDB 1.0-alpha.2+dev.261.g655230a2
Type "\?" for help.

edgedb> rollback 
.......                     
```
The code is basically:
```
        if select.select([sys.stdin], [], [], 0.0)[0]:
            # script mode
        else:
            # interactive mode
```

Usually, it's detected by `isatty` function? Are there any problems with it? Assuming that data is already in stdin isn't a good idea, as I've demonstrated above.

Also, I think that doing `sys.stdin.read()` (read until eof) in non-interactive mode isn't good, as pipelining should be supported too.

But at the end of the day is it worth fixing?

**Comment by 1st1** [comment]
@elprans I think you had an explanation for why we want to use `select()` there.

**Comment by 1st1** [comment]
Evidently this was added by me https://github.com/edgedb/edgedb/commit/7b1792857d124429b93cc2c3d9e2b08f73c0bfd2. :)

And also evidently postgres is using `isatty`.

So let's try to use `isatty` too. Paul, please submit a PR.
