### ISSUE TITLE
Trailing comma doesn't work

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#868]
In the statement like this:
```
with 
  a := (...),
select ...
```
Trailing comma doesn't work in `WITH`. It works fine in objects, though. I believe it should work here too.

Version: alpha1

**Comment by 1st1** [comment]
@vpetrovykh please take a look. Would be nice to support trailing commas in this context as we support them pretty much everywhere else. Although I think it might be impossible due to grammar conflicts.
