### ISSUE TITLE
Rework MIGRATION command

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#896]
Current `MIGRATION` commands assume that each migration is either some arbitrary DDL or SDL for a single module. This presents a problem expressing migrations for several interdependent SDL modules.

The broad idea is that the SDL supplied to the `MIGRATION` command should reflect the entire schema and not just a single module. This necessitates some syntax changes for `MIGRATION` commands. Additionally, there are changes needed to accommodate interactive approach to adjusting auto-generated SDL migrations.

**Comment by vpetrovykh** [comment]
First of all, what is SDL? It's a special declarative language for describing the schema state and it's only valid within the context of a `MIGRATION` command. It *must* unambiguously describe the schema state, but unlike DDL it does not necessarily provide an unambiguous description of the sequence of steps that achieves that schema state. As stated earlier, SDL must also describe the entire schema (otherwise migrating a module on which other modules depend may be inexpressible in SDL format, which makes the format far less useful).

This means that SDL must enforce unambiguous name resolution, which can be achieved by forcing the use of fully-qualified names in it. Since this is rather onerous, we can introduce a special syntax to group together things that are in the same module:
```
module default {
   # the default module here is "default"
   type Foo {
      # the module "std" is also part of the default name 
      # resolution as usual
      property name -> str;
      link bar -> other_mod::Bar;
   }
}

module other_mod {
   # the default module here is "other_mod"
   type Bar {
      link bar -> Bar;
      link foo -> default::Foo;
   }
}
``` 

This would also be equivalent to the following SDL:
```
# only the "std" module can be omitted here, all other 
# names have to be fully-qualified, even "defaut"
type default::Foo {
   property name -> str;
   link bar -> other_mod::Bar;
}

type other_mod::Bar {
   link bar -> other_mod::Bar;
   link foo -> default::Foo;
}
```

In principle, an SDL declaration could contain multiple `module` blocks of the same name. They should be interpreted as being the same module. This would allow an easy way to break up a large module into several files without a complex mechanism for stitching  together the SDL from these files. So the following should be valid:
```
module default {
   type Foo;
}

module other_mod {
   type Bar;
}

module default {
   type Foo2;
}
```
...and equivalent to:
```
module default {
   type Foo;
   type Foo2;
}

module other_mod {
   type Bar;
}
```

**Comment by vpetrovykh** [comment]
We want EdgeDB to actually store a linear history of migrations. These `schema::Migration` objects would store the actual DDL commands (as `str`), have an `id` and `name` (probably just mapping to the `id`) which can be referenced by various migration tools, a link to the latest `Migration` at the time when this one was created, and annotations with `title` and `description` as a human-readable comment detailing what the migration is doing. 

There are 2 ways to create these objects:
1) A single `CREATE MIGRATION { ... }` command. The body of the migration can contain any mix of DDL and queries. This creates a `schema::Migration` object, which can then be executed. 
2) The command `START MIGRATION` which would enter an interactive state where no queries are possible and every DDL command instead of being executed gets appended to the list of migration DDL. In this mode it's possible to `DECLARE SAVEPOINT` and `ROLLBACK TO SAVEPOINT` in this state, which will restore the state of the DDL list as it was at the `SAVEPOINT`. The current transient migration state can also either be discarded by a `ROLLBACK` (much like a transaction) or written into the database with a `COMMIT MIGRATION`. After a `COMMIT` a `schema::Migration` object is created (much like by a `CREATE MIGRATION` command).

There should be a way of applying a `schema::Migration` as well as possibly rebasing it to the current top of the list. Commands like `APPLY MIGRATION <migration_id>` and `REBASE MIGRATION <migration_id>` could be introduced to handle that. We probably want the `APPLY` command to be different from `COMMIT` to avoid confusion between creating a migration object and applying the changes described by this object.

`TO { <SDL block> }` can be an optional parameter to both ways of creating a `schema::Migration` object which would specify the final state that the migration is obligated to achieve.

In `START MIGRATION` mode we also want a command that looks at the target SDL (if any) and the current transient migration state and automatically adds all the DDL that's needed to finish migrating to the specified state. Maybe something along the lines of `APPLY DIFF` or maybe `AUTO MIGRATION`.

Also, in `START MIGRATION` mode we want an optional parameter that can specify a bunch of DDL commands to run as a prefix to whatever other commands will be generated in the interactive session. Possibly `USING DDL { ... }`. Something like `START MIGRATION USING DDL { ... } TO { ... };`

In order for this to work better a command that shows a diff (as a `str`) between the current schema state and a given SDL would be useful. Something like `DIFF {<SDL block>}`. This command could help guide the interactive `START MIGRATION` process without needing to specify the target SDL from the beginning.

`SHOW MIGRATION` in `START MIGRATION` mode could show the list of DDL for the current migration. This would allow exporting this value into an external tool without having to commit the migration and introspecting the committed value.

**Comment by vpetrovykh** [comment]
I'm sort of left wondering what happens to this whole nice arrangement if after applying several proper migrations I go and just run a bare DDL, say `CREATE TYPE Foo;`. Does this automatically create a `schema::Migration` object with a single command and appends it to the migrations list? I would assume it does, since otherwise the "latest" `Migration` is no longer accurate representation of the current schema state.

**Comment by elprans** [comment]
@vpetrovykh Please create a separate issue for the `module` changes in SDL. The migration system rework is a large project and will probably not make it into Alpha 2.

**Comment by 1st1** [comment]
> The migration system rework is a large project

I'm writing a full RFC (yes, we will have RFCs!) on this as we need to document pretty much all decisions and make it's as thorough as possible. That will save us a lot of time in the long run. 

I'll post a link when I have a first draft. No need to discuss it here before that.

**Comment by 1st1** [comment]
I guess we can close this one now. We have an RFC for A4.
