### ISSUE TITLE
Can't update multi link with link property

### ISSUE THREAD

**Issue by cosmophile** [edgedb/edgedb#904]
I cannot figure out how to update multi links with link properties. Everything I try results in the error: **QueryError: invalid reference to link property in top level shape**.

To illustrate using an example from the docs (bottom of [this](https://edgedb.com/docs/edgeql/statements/for#ref-eql-forstatement) page), here's a simple schema:
```
type User { 
    property name -> str; 
    multi link friends -> User { 
        property nickname -> str; 
    } 
}
```
As the docs demonstrate, I can insert all the users and use the WITH + FOR + array_unpack statement to set multiple links and their corresponding link properties.

But now if I add another user and want to update any of the existing users' friends list with a link and a link property, it just doesn't happen. The following (and all permutations I could think of as far as adding and removing round brackets) does not work:
```
WITH U2 := User UPDATE User FILTER .name = 'Bob' 
SET { 
    friends := User.friends UNION (
        SELECT U2 { @nickname := 'new guy' } FILTER U2.name = 'John' 
    )
};  
```
Result: *QueryError: invalid reference to link property in top level shape* with the error arrow pointing to the beginning of the `{ @nickname` ... part

Note that just without the link property part I am able to add the new friend to the friends list using the query above. 

I am also able to add the link with its link property if I replace all existing friends (by omitting User.friends UNION). So clearly this should be possible, but I can't find/understand my syntax error. 

Thanks for your help!

**Comment by elprans** [comment]
This looks like a bug.  Your query should work.  I'll take a look soon.  Also, #165 will make these sorts of queries much simpler.   Meanwhile, the following workaround should work:

```
 WITH U2 := User UPDATE User FILTER .name = 'Bob'
 SET {
     friends := (
        FOR f in {(User.friends, User.friends@nickname) 
                  UNION ((SELECT U2 FILTER .name = 'John'), 'new guy')}
        UNION f.0 {
           @nickname := f.1
        }
     )
 };
```

**Comment by cosmophile** [comment]
OK I think I see what you did there. I ended up implementing pretty much that in my Typescript using 2 queries but thank you very much for the direction. 

+= and -= went right to the top of my wish list.

**Comment by cosmophile** [comment]
Hi again, my attempts to set link properties are still failing in every case where all the link properties are not set on every linked item. 

So for instance the query you posted above will also remove all existing friends of Bob that don't have a nickname assigned, since they I'm guessing don't make it into the tuple set which FOR is iterating on.

**Comment by cosmophile** [comment]
This is not an urgent issue for me as I have wrangled my TS queries to set empty strings or 'null' as enum as the case may be, but just wanted to report it because link properties are powerful and I hope the set/update syntax becomes as clean and clear as top level queries.

**Comment by elprans** [comment]
> still failing in every case where all the link properties are not set on every linked item.

You can guard against an empty nickname with `??` like this:

```
 WITH U2 := User UPDATE User FILTER .name = 'Bob'
 SET {
     friends := (
        FOR f in {(User.friends, User.friends@nickname ?? '') 
                  UNION ((SELECT U2 FILTER .name = 'John'), 'new guy')}
        UNION f.0 {
           @nickname := f.1 IF f.1 != '' ELSE <str>{}
        }
     )
 };
```

>  link properties are powerful and I hope their set/update syntax becomes as clean and clear as the top level queries.

Definitely! We're working on improving this aspect of EdgeQL.

**Comment by cosmophile** [comment]
Hi @elprans, part of my project implements a rating/feedback system which I am representing via link properties, so there are lot of link property updates, and I'm confused about a part of it even though it works.

Simplified schema:

```
scalar type Rating extending enum<'great', 'ok', 'terrible', 'null'>;
type User { ... }
type Product {
  multi link buyers -> User {
    property rating -> Rating
  }
}
```
Update query on receiving a rating:

```
WITH P := (SELECT Product FILTER .id= someProduct LIMIT 1), 
    BuyerSet := {(P.buyers, P.buyers@rating)},
    CurrentUser := (SELECT User FILTER .id = currentUser LIMIT 1),
    Combined := DISTINCT((SELECT BuyerSet FILTER .0 != CurrentUser ) UNION (CurrentUser, <Rating>'great')),
    Buyers := Combined.0, Ratings := Combined.1
    UPDATE P SET { 
        buyers := (
            FOR x IN { (Buyers, Ratings) } 
            UNION (
                SELECT x.0 { @rating := x.1 } 
            ) 
        ) 
    }
```

It works, but I hit upon it after a lot of trial and error, and repeatedly seeing the same error: **InternalServerError: scoped set must not contain itself**. This error only goes away if I destructure the `Combined` Tuple into separate `Buyers` and `Ratings`, even though I use them again as exactly that in the `FOR` clause.  Why does directly saying `FOR x IN { Combined }` cause this error? What is the error trying to say? Is this a bug or an inherent characteristic of EdgeDB sets that I don't understand? 

PS, FYI: miscasting (or not casting) integers gives a cryptic error about "missing from clause".

**Comment by elprans** [comment]
Hey @cosmophile.  The `InternalServerError` is always a bug, please don't hesitate to open bugs when you see one.

**Comment by 1st1** [comment]
@elprans Can we fix this for alpha 3? If not please move to alpha 4.

**Comment by elprans** [comment]
The `+=` shape operator is now supported in `UPDATE`, so the original query can be written as:

```
WITH U2 := User 
UPDATE User 
FILTER .name = 'Bob'
SET {
    friends += (
        SELECT U2 {
            @nickname := 'new guy'
        } FILTER .name = 'John'
    )
};
```
