### ISSUE TITLE
Make decision on bigint  `123n` syntax

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#905]
[This commit](https://github.com/edgedb/edgedb/commit/a5d7707cf72a6647b599156fe4fd35d9ac638e1d) introduces syntax for decimal constants, that also provisions bigint type.

Bigint vs Decimal types should coerce similarly to int vs float, i.e. it's possible to coerce bigint to decimal, but not vice versa (because this means losing precision in some cases).

If we want `12n` (without decimal point) being a bigint, changing it later will be a **breaking change**.

So instead we have two alternatives:
1. Disable bigint syntax now, and only allow decimals (with decimal point `123.0n`)
2. Implement bigint now

One consequence of (1) is that `123.0n` has a precision of *1 decimal places* whereas in current implementation `123n` is a decimal with precision of *zero*. Basically this means it's impossible to create a decimal constant with a precision of zero (which is essentially an equivalent of bigint, so it's not a problem when bigint type is already introduced).

**Comment by 1st1** [comment]
> Implement bigint now

+1. Shouldn't take too much time.

**Comment by 1st1** [comment]
Implemented in https://github.com/edgedb/edgedb/commit/6e0bc3d5646385e1a1a476ba01d3af848529469b
