### ISSUE TITLE
Can we improve `type or view does not exist` message?

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#915]
Here is the query:
```
SELECT User { id } FILTER email = <str>$email
```
And the error is:
```
edgedb.errors.InvalidReferenceError: object type or view 'email' does not exist
```

My points are:
1. It would be quite common error (as it closely matches SQL `WHERE email =`)
2. It's hard to understand what `object type or view` means in this context.

The best fix would be to look through all the names and make a suggestion:
```
edgedb.errors.InvalidReferenceError: object type or view 'email' does not exist. Try `User.email`?
```

If it's hard to implement we can use some heuristics (like 99% that lowercase name is a field). Or at least add an explanation `You can't reference field directly use 'Object.field'`.

**Comment by elprans** [comment]
Yes, this can be improved.  FYI, you don't have to use `Object.field`, `.field` (with a leading dot) is enough.
