### ISSUE TITLE
Adding enum option fails with weird error

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#916]
I'm upgrading a schema:
```
scalar type TicketStatus extending enum<
        'new',
        'closed'
>;
```
To:
```
    scalar type TicketStatus extending enum<
        'new',
        'assigned',
        'closed'
    >;
```
Using `CREATE MIGRATION .. TO` (I mean schema is bigger, but I'm just adding an option)

And I get this error:
```
InternalServerError: ALTER TYPE ... ADD cannot run inside a transaction block
```
I assume that that alter type is generated somewhere internally. Anyway, it should either be fixed or some workarounds proposed in the error message.

(removing an option works, though)

Server version `1.0-alpha.2+dev.333.gf30744d`

**Comment by elprans** [comment]
Hm. This is weird.  Postgres documentation states that `ALTER TYPE .. ADD` can run inside a transaction block, but the new value cannot be used until the transaction is committed (https://www.postgresql.org/docs/current/sql-altertype.html#id-1.9.3.42.7)

**Comment by elprans** [comment]
The error seems to be PostgreSQL 11 behavior.  You need to rebuild your checkout (drop `build/postgres`) and run `pip install -e .`)

**Comment by tailhook** [comment]
I use a nightly package `1.0a2.dev333+gf30744d-2019113000~xenial.nightly` and don't install postgres myself. So if it's old postgres the nightly package must be fixed.

**Comment by tailhook** [comment]
But yes, postgres is old:
```
/usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/bin/postgres -V    
postgres (PostgreSQL) 11.2
```

**Comment by elprans** [comment]
Ah. Right. That's a packaging bug. Will fix

**Comment by 1st1** [comment]
> Ah. Right. That's a packaging bug. Will fix

@elprans Is this now resolved?

**Comment by elprans** [comment]
Yes, this is fixed.
