### ISSUE TITLE
Semantics of new-line escaping in edgedb

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#921]
Currently, all spaces are preserved, like in python:
```
edgedb>SELECT "hello \ 
.......       xxx";                    
{'hello       xxx'}
```
But I believe that's legacy and I very much like rust's semantics:
```
rust> println!("{:?}", "hello \
              world")
"hello world"
```
(i.e. stripping all whitespace at the start of the next line

This allows nicely indented long string phrases, and also allows breaking non-whitespace-separated texts:
```
WITH
    url := "http://example.com/\
            some/very/long/path"
```
(which is super-ugly with python semantics)

The downside is that you need to put whitespace before continuation:
```
second_line_indented := "def x():\n    \
                             return 'x'"
```
But with python's semantics, inside and outside indentation typically do not match anyway.

What do you think?

**Comment by 1st1** [comment]
+1 for rust semantics.

**Comment by vpetrovykh** [comment]
I'm not convinced that the convenience of writing paragraphs of plain text is actually outweighed by the inconvenience of writing anything with indentation.
Compare the following:
```
WITH a := "\
some text or code
         that has
      indentation"
SELECT a;
```
```
WITH a := "some text or code\n         \
           that has\n      \
           indentation"
SELECT a;
```
I think that we need some mechanism flexible enough to either ignore leading whitespace or to preserve it, both are very useful and valid use-cases.

**Comment by elprans** [comment]
I'm also not convinced that the Rust semantics is strictly better. 

> I think that we need some mechanism

We already have a mechanism: string concatenation (which is optimized away by the constant folder).

```
WITH
    url := "http://example.com/"
           ++ "some/very/long/path"
```

**Comment by 1st1** [comment]
@elprans 
> I'm also not convinced that the Rust semantics is strictly better.

@vpetrovykh 
>  Compare the following:

> ```
>  WITH a := "some text or code\n         \
>             that has\n      \
>             indentation"
>  SELECT a;
>  ```

Why don't you just use our multi-line raw string for this? **Using raw literals for code is more preferable anyways**:

```
WITH a := r"some text or code         
            that has      
            indentation"
SELECT a;
```

I personally think that for single-line strings the Rust way is more convenient -- that's what you actually want for formatting long paragraphs of **text**.  For code use raw multi-line raw literals.

But **for text**

```
a := 'Lorem ipsum dolor sit amet, consectetur \
      adipiscing elit, sed do eiusmod tempor'
```

is way more readable than

```
a := 'Lorem ipsum dolor sit amet, consectetur ' ++
     'adipiscing elit, sed do eiusmod tempor'
```

**Comment by vpetrovykh** [comment]
The zoom conversation clarified that actually the Rust semantics of `\` are fine. All strings are white-space preserving in EdgeDB and the `\` allows to _opt out_ of that in specific cases. I got confused by the indentation example (which is easier to do by not using the unnecessary line continuation). 
So +1 on Rust semantics.

**Comment by elprans** [comment]
Yeah, I withdraw my objection as well.

**Comment by 1st1** [comment]
Do we have time or are we confident enough to ship rust lexer in alpha 2? If not then we need to update our current lexer.  This is a backwards incompatible change.

**Comment by vpetrovykh** [comment]
Why is it the lexer that needs an update? The line continuation symbol is already valid in strings. The update is purely to the semantics of the token, not its syntax. The semantics are relevant to the step when we convert the token value into something that we can put in SQL. As far as I can tell this is what [lexutils.unescape_string](https://github.com/edgedb/edgedb/blob/a5e8e344b108bb68211ed2d57f27e5149a2f7712/edb/edgeql/parser/grammar/lexutils.py#L142) is doing. This is happening in IR stage, which makes sense as we're talking about correctly representing EdgeQL value in SQL and this aspect is irrelevant to lexing and parsing steps, while it can interfere with error messages, etc. 

One big reason why lexer is not mangling the value is that we want to preserve the property that given a token stream we can reconstruct the original document perfectly. As far as I recall, we've had some issues with string "values" when we tried to convert them early (having to do with handling escape sequences).

So yeah, we need to update compiler code, but lexer remains the same here.

**Comment by elprans** [comment]
> Do we have time or are we confident enough to ship rust lexer in alpha 2

I wouldn't rush it.  There's work to be done to integrate Rust into our build system as well.

**Comment by tailhook** [comment]
> Do we have time or are we confident enough to ship rust lexer in alpha 2?

Surely, no. My plan is to integrate it right after cutting alpha 2, so we have plenty of time to alpha 3 to test it.

This issue is trivial to fix, though, and it doesn't touch lexer as @vpetrovykh said.

> As far as I recall, we've had some issues with string "values" when we tried to convert them early (having to do with handling escape sequences).

Well, usually lexers don't unescape values, that's true. But I would like to do it when we're going to integrate rust code to python. The reason is performance: python is bad at working with individual characters and there is a little sense to move strings back and forth between python and rust.

What I'm trying to say if you recall what were specific issues let me know, so I can choose the right approach earlier.

**Comment by 1st1** [comment]
Implemented in https://github.com/edgedb/edgedb/commit/7b982e0966dd1cb1b83b5796cfb7a89ce8a5524a
