### ISSUE TITLE
Improve tokenization of variables

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#923]
The current tokenizer separates `$` and ident or number tokens. This means the following is valid (apart from mixing positional and named arguments):
```
SELECT $   x, $   12, $   `test`
```
It's okay, but isn't needed per se.

It also means tuple access doesn't work sometimes:
```
edgedb> select $0.1;                   
EdgeQLSyntaxError: Unexpected '0.1'
### select $0.1;
###         ^
```

Making `$xxxx` a single token should fix the latter (and disallow spaces as a side-effect).

**Comment by vpetrovykh** [comment]
Right, looks like among other things we need more tests using parametrized queries. Good catch!
