### ISSUE TITLE
Fix repl to render std::bigint correctly

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#924]
```
yury> select 1n;
{1}    # <- add 'n'
yury> select 1.0n;
{1.0n}
```

**Comment by tailhook** [comment]
We kinda discussed this in the bigint PR and I would not waste much time on this as we're going to have Rust repl in alpha 3 (unless you have a very simple way to do that).

**Comment by 1st1** [comment]
I don't think fixing this will take a lot of time, but yeah, the priority is relatively low.
