### ISSUE TITLE
Docs: where to search for logs especially issued queries to postgresql?

### ISSUE THREAD

**Issue by abetkin** [edgedb/edgedb#925]

**Comment by elprans** [comment]
For the embedded PostgreSQL instance, look in the EdgeDB data directory, which is a regular PostgreSQL data directory.  You can configure the underlying Postgres instance logging by editing `postgresql.conf`, as usual.

Future versions of EdgeDB will feature a more elaborate logging system.

**Comment by abetkin** [comment]
Thank you
