### ISSUE TITLE
`edb profviz` seems to be generating wrong flame charts data

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#956]
**Here's output of `edb profviz`:**

![Screen Shot 2019-12-10 at 7 11 57 PM](https://user-images.githubusercontent.com/239003/70580262-2133de80-1b81-11ea-9a15-e065737b7427.png)

**Here's output of baverman/flameprof** for the same `compile_edgeql_script_webapp_get_movie.prof` file:

![Screen Shot 2019-12-10 at 7 12 02 PM](https://user-images.githubusercontent.com/239003/70580289-3a3c8f80-1b81-11ea-895f-84a583da7052.png)

While flameprof does not unwind singledispatch calls, the shape of the flamechart it produces seems to make more sense, as it doesn't have anomalies like the below:

![Screen Shot 2019-12-10 at 7 14 53 PM](https://user-images.githubusercontent.com/239003/70580348-6c4df180-1b81-11ea-9088-d1f014bcbf08.png)

I'm not sure but we might have a bug either in the flamechart rendering logic or in singledispatch unwind logic.

**Comment by 1st1** [comment]
Context: @elprans asked me to file this; it looks like baverman/flameprof is also wrong w.r.t. single dispatch. I'll let Elvis elaborate on this.

**Comment by elprans** [comment]
Yea, something is up with the rendering:

![Screenshot_20191210_192555](https://user-images.githubusercontent.com/347119/70580778-fcd90180-1b82-11ea-91b2-12897d954a98.png)

**Comment by tailhook** [comment]
Well, actually I think that `_compile_view_shapes_in_set` is rendered correctly (as much as possible):
1. It's a recursive function
2. cprofile only collects one frame deep (i.e only calee)
3. That's the downside of this kind of profiling: if there are two paths `a -> x -> b` and `d -> x -> e` the `b` and `e` will be shown and have same fractions in the flame graph both above `a` and above `d` even if `b` is never called from inside `a` indirectly (and vice versa)
4. You can observe that on the bottom-most `_compile_view_shapes_in_set` left column of callees is exactly the same as on the next one (it could draw it recursively forever if not stopped)

(And I can say again that py-spy could provide more specific profile as it captures more than 1 frame as far as I understand, even if it would skip some fastest functions)

**Comment by elprans** [comment]
> 1. It's a recursive function
> 2. cprofile only collects one frame deep (i.e only calee)

Right.  Ideally, the recursive calls should be detected and "collapsed".  kcachegrind does this quite nicely.

> And I can say again that py-spy could provide more specific profile

Technically, the cumulative cost of the function (however it was called) is more useful than the precise call stack, so cProfile is mostly sufficient.  We just need to polish the rendering a bit more.

**Comment by 1st1** [comment]
Seems that everything is fine after all, should this be closed?

**Comment by ambv** [comment]
Yes, I think everything is fine with this. Once we dry up the well of cProfile-based profiling, we should definitely look into py-spy.

**Comment by ambv** [comment]
> Yea, something is up with the rendering in profviz

The rendering mishap that @elprans is observing in large zooms is due to the fact that the data is not granular enough. I could smoothen the graph a bit for zoom but for the time being it's low-pri.
