### ISSUE TITLE
Errors while trying out functions and custom constraints

### ISSUE THREAD

**Issue by cosmophile** [edgedb/edgedb#957]
I'm using the latest dev build, where I have a `Tagged` type which derives a computed `tag` property from a `title` property by normalizing it.

At the basic level it's something like:
```
type default::Tagged {
    required property title -> str;
    property tag := str_lower(
        re_replace(r' ', r'-', ( 
            re_replace( r'[^(\w|\s)]', r'', __source__.title, flags := 'g') ), 
        flags := 'g')
    )
}
```
^This works, but then I tried to abstract the tag-making to a function and reference the function in my computable with a view to using the function in multiple types:
```
function default::make_tag(s: str) -> str
    using EdgeQL $$
        select str_lower(
            re_replace( r' ', r'-', 
                re_replace( r'[^(\w|\s)]', r'', s, flags := 'g'),
            flags := 'g')
        );
    $$;

type default::Tagged {
    required property title -> str;
    property tag := default::make_tag(__source__.title);
}
```
With this schema I can no longer run *any* command (error on any commands in the REPL: `InvalidReferenceError: reference to a non-existent schema item 34d5c5e2-1bdf-11ea-8881-e9bcd78fe63f in schema <Schema gen:3834 at 0x7fe23355a898>`), and once I disconnect from the database I can no longer establish a connection to it using `\c myDb` (error: `Could not establish connection to 'myDb'`). Oooops!

I'm also not able to drop the database: (error: `InternalServerError: database "myDb" is being accessed by other users`).

On a related note, I would also love to reject any title whose tag form already exists, since it seems disallowed to use constraints on computables. But it also does not seem possible to reference functions in constraints or create constraints that can be used in an SDL schema _if the constraint references a type_, with the error that the type or the constraint does not exist, depending on what is declared first in the schema. 

So I create an SDL schema with my type and make_tag function (without referencing the function in the computable but using the same formula directly) and then create a DDL function to use in a constraint, 
```
CREATE function unique_tag ( s: str ) -> bool {
    USING EdgeQL $$ 
        WITH tag := (default::make_tag(s)) SELECT tag NOT IN default::Tagged.tag; 
    $$; 
};
```
It's basically my attempt to implement an exclusivity check on a transformed subject.

Then I tried to use this as an abstract constraint with the objective of using it in the `title` property of my TaggedType:
```
create abstract constraint exclusive_tag { USING ( unique_tag(__subject__)) }; 
```

Finally, I try to use the the constraint on the title property:
```
alter type Tagged alter property title create constraint exclusive_tag; 
```
I get the error: `InvalidReferenceError: schema item 'default::default::exclusive_tag' does not exist`

Tried variously specifying the default:: module on Tagged as well as constraint but the error persists. 

So ultimately I've left out the extra functions and constraints and am using Tagged as an abstract type with `title` and computed `tag`. Then before insert a new concrete type object, I run the query
```
SELECT make_tag('my new object title') NOT IN myObject.tag;
```
and then insert the title if it returns true. Then all works well. (But it still seems to me like a good use case for a constraint.)

My thinking was it would be possible to create functions in the schema and reference them in either computables or constraints. Would be great to get clarity in the Alpha2 documentation of what's possible in both. Unless I've missed it somewhere. I also remember reading that within constraints it is not possible to access anything else about the subject - do I have that correct? I cannot reference the subject's type and use IS to reference other properties, or generally use EdgeQL in there - correct?

Apologies for going on and on. And thanks as always!

**Comment by elprans** [comment]
> My thinking was it would be possible to create functions in the schema and reference them in either computables or constraints.

Yes, this is an SDL dependency sorting bug.  @vpetrovykh is working on fixing these.  Victor, please take a look at the examples @cosmophile has showed.

> Unless I've missed it somewhere. I also remember reading that within constraints it is not possible to access anything else about the subject - do I have that correct? I cannot reference the subject's type and use IS to reference other properties, or generally use EdgeQL in there

Currently, the constraint expression on a property must only reference the property itself and the entire expression must return a singleton `bool`.  It must also be a simple expression, i.e. no subqueries etc.  This is actually a PostgreSQL restriction.  A workaround for that is to put the constraint logic into a function.

Regarding constraints on computables, I don't think that's possible to implement in a generic fashion.  Since the computable is not actually stored anywhere, your would need to put triggers on the inputs you use in the transformation function, and that can get very complicated very quickly, especially when aggregation is involved.

So, the best way to handle use cases like yours is to put the transformation expression into a function, and use it in both the constraint and the computable:

```
function default::make_tag(s: str) -> str {
    using (
        select str_lower(
            re_replace( r' ', r'-', 
                re_replace( r'[^(\w|\s)]', r'', s, flags := 'g'),
            flags := 'g')
        )
    );
    volatility := 'IMMUTABLE';  # needed for the constraint
}

type default::Tagged {
    required property title -> str {
        constraint exclusive on (default::make_tag(__subject__))
    }
    property tag := default::make_tag(.title);
}

```

Naturally, we must fix the dependency issue for this to work.

Thanks for reporting, @cosmophile!

**Comment by cosmophile** [comment]
Intuitively it makes sense to me that constraints wouldn't apply to computables. I just had to try whatever isn't expressly forbidden. 😁 

The schema you posted is exactly what I'm hoping for, and thanks for the hint about volatility. So excited about Alpha2 and new/more documentation. Good luck to you guys for the final stretch!
