### ISSUE TITLE
Validate names of datetime units to only support plurals

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#958]
This includes:

* `datetime_get`
* `datetime_trunc`

`duration_get` is already works. Maybe other?

**Comment by 1st1** [comment]
Is this done?

**Comment by tailhook** [comment]
As far as I know, no.

**Comment by 1st1** [comment]
np, do you think you can take a look at this next week?

**Comment by tailhook** [comment]
Oops, sorry, forgot about this. Will take a look tomorrow.

**Comment by tailhook** [comment]
I've fixed datetime_truncate but I'm not sure what to do with datetime_get:
    - ``'epoch'`` - the number of seconds since 1970-01-01 00:00:00
      UTC for :eql:type:`datetime` or local time for
      :eql:type:`cal::local_datetime`. It can be negative.
    - ``'century'`` - the century according to the Gregorian calendar
    - ``'day'`` - the day of the month (1-31)
    - ``'decade'`` - the decade (year divided by 10 and rounded down)
    - ``'dow'`` - the day of the week from Sunday (0) to Saturday (6)
    - ``'doy'`` - the day of the year (1-366)
    - ``'hour'`` - the hour (0-23)
    - ``'isodow'`` - the ISO day of the week from Monday (1) to Sunday (7)
    - ``'isoyear'`` - the ISO 8601 week-numbering year that the date falls in.
      See the ``'week'`` element for more details.
    - ``'microseconds'`` - the seconds including fractional value expressed
      as microseconds
    - ``'millennium'`` - the millennium. The third millennium started
      on Jan 1, 2001.
    - ``'milliseconds'`` - the seconds including fractional value expressed
      as milliseconds
    - ``'minute'`` - the minutes (0-59)
    - ``'month'`` - the month of the year (1-12)
    - ``'quarter'`` - the quarter of the year (1-4)
    - ``'second'`` - the seconds, including fractional value from 0 up to and
      not including 60
    - ``'week'`` - the number of the ISO 8601 week-numbering week of
      the year. ISO weeks are defined to start on Mondays and the
      first week of a year must contain Jan 4 of that year.
    - ``'year'`` - the year

Some of them like `epoch` are `seconds` but.... Some of them like `dow` don't make sense as plural. And if day of week isn't plural, it's unclear why would other be plurals.

**Comment by tailhook** [comment]
We're going to make the following renames
* `epoch` -> `epochseconds`
* `minute` -> `minutes`
* `second` -> `seconds`
And leave others as is.
