### ISSUE TITLE
Documentation on links is unclear

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#967]
I'm looking at https://edgedb.com/docs/datamodel/links:

1. There is no single example of how links are defined
2. I think linking from SDL to DDL for explanation is ugly. If I understand correctly, most users should never use DDL directly.
3. Docs don't mention backwards link. I.e. if have `Ticket { link owner -> User; }` should I also define `User { multi link tickets -> Ticket }` or not?
4. What indexes are provided on the link by default and what indexes you need to define yourself? (I.e. if no ones provided then user needs indexes in 99.9% cases). 
5. There should be the discussion of forward vs backward links: I.e. whether `User` needs a multi link to `Session`, or whether `Session` needs a single link to `User` (probably we can come up with more controversial example).

**Update:** added (5)

**Comment by 1st1** [comment]
@tailhook Can you work on this?
