### ISSUE TITLE
Where is the documentation "index"?

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#970]
We have a lot of `:index:` directives and custom roles that should be present in the sphinx's documentation index, but I can't find one.

**Comment by elprans** [comment]
Those are search index keywords, not "index" in the sphinx meaning.  IMO, the "index" is not very useful as opposed to properly working search.  Also, if you're looking for the "list of definitions" page, it's here: https://edgedb.com/docs/glossary/, although very incomplete.

**Comment by tailhook** [comment]
Can't find a link to the glossary from the frontpage. But it mostly empty, doesn't seem to be useful.

What I'm usually looking for: documentation on an operator or a function. Functions are spread by category, which isn't always clear. And operators are deep in lexical structure, which I struggle to find every time. And not all of them there.

**Comment by elprans** [comment]
Why not use search?  You would end up using it on the index page anyway, it would be huge if we just dump everything there.  If you see a gap in search terms for something, feel free to add `:index:`

**Comment by 1st1** [comment]
Shall we close this one?

**Comment by tailhook** [comment]
Let's close for now. It's always possible to reopen later.
