### ISSUE TITLE
Graphql error when sending query variables with a null value 

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb#993]
I created a simple schema and i get the following error when querying data trough graphql when sending query variables with a value of null.
```
ValueError: unexpected constant type: <class 'NoneType'>
```
![image](https://user-images.githubusercontent.com/8558836/71169127-88742180-2258-11ea-9f69-5757faafb0f6.png)

Expected: Ignore it or a friendly error message that says `null values are not permitted in query variables`

**Comment by 1st1** [comment]
@vpetrovykh please take a look.

**Comment by vpetrovykh** [comment]
The PR that fixes this is #1012 (there's a typo in the issue number that it refers to).
